// CFA Level I completeness expansion (pass 10). Adds the remaining current-
// curriculum learning modules so every CFA L1 module is represented, taking the
// exam to 93 topics. Each new topic has a 2-minute study note and a full
// 12-question drill.
import type { AuthoredMaterial } from "./builder";
import type { Question, Topic } from "@jyotir/core";

export const exp10Topics: Topic[] = [
  // Ethics (max orderIndex now 7)
  { id: "cfa-ethics-ethics-and-trust", subjectId: "cfa-ethics", name: "Ethics & Trust in the Investment Profession", slug: "ethics-and-trust", orderIndex: 8 },
  // Quantitative Methods
  { id: "cfa-quantitative-methods-portfolio-mathematics", subjectId: "cfa-quantitative-methods", name: "Portfolio Mathematics", slug: "portfolio-mathematics", orderIndex: 8 },
  { id: "cfa-quantitative-methods-simulation-methods", subjectId: "cfa-quantitative-methods", name: "Simulation Methods", slug: "simulation-methods", orderIndex: 9 },
  { id: "cfa-quantitative-methods-big-data-techniques", subjectId: "cfa-quantitative-methods", name: "Introduction to Big Data Techniques", slug: "big-data-techniques", orderIndex: 10 },
  // Economics
  { id: "cfa-economics-capital-flows-fx", subjectId: "cfa-economics", name: "Capital Flows & the FX Market", slug: "capital-flows-fx", orderIndex: 8 },
  // Financial Statement Analysis
  { id: "cfa-financial-reporting-long-term-assets", subjectId: "cfa-financial-reporting", name: "Analysis of Long-Term Assets", slug: "long-term-assets", orderIndex: 8 },
  { id: "cfa-financial-reporting-financial-modeling", subjectId: "cfa-financial-reporting", name: "Introduction to Financial Statement Modeling", slug: "financial-modeling", orderIndex: 9 },
  // Corporate Issuers
  { id: "cfa-corporate-issuers-corporate-restructuring", subjectId: "cfa-corporate-issuers", name: "Corporate Restructuring", slug: "corporate-restructuring", orderIndex: 8 },
  // Equity Investments
  { id: "cfa-equity-company-forecasting", subjectId: "cfa-equity", name: "Company Analysis: Forecasting", slug: "company-forecasting", orderIndex: 8 },
  // Fixed Income
  { id: "cfa-fixed-income-cash-flows-types", subjectId: "cfa-fixed-income", name: "Fixed-Income Cash Flows & Types", slug: "cash-flows-types", orderIndex: 8 },
  { id: "cfa-fixed-income-government-corporate-markets", subjectId: "cfa-fixed-income", name: "Government & Corporate Fixed-Income Markets", slug: "government-corporate-markets", orderIndex: 9 },
  { id: "cfa-fixed-income-curve-empirical-duration", subjectId: "cfa-fixed-income", name: "Curve-Based & Empirical Duration", slug: "curve-empirical-duration", orderIndex: 10 },
  // Portfolio Management
  { id: "cfa-portfolio-management-active-management", subjectId: "cfa-portfolio-management", name: "Analysis of Active Portfolio Management", slug: "active-management", orderIndex: 8 }
];

export const exp10Materials: AuthoredMaterial[] = [
  { id: "cfa-ethics-ethics-and-trust-m01", topicId: "cfa-ethics-ethics-and-trust", title: "Ethics & Trust in the Investment Profession", content: `The investment industry runs on **trust**: clients hand over capital and rely on professionals to act in their interest. **Ethics** are the shared beliefs about what is good/acceptable conduct — they go **beyond the law**, which sets only a minimum.

## Ethics vs legal standards
Some acts are legal but unethical, and some ethical acts may be illegal. High-quality conduct meets the **stricter** of law or ethics.

## Why conduct lapses
- **Situational influences** (money, loyalty, peer pressure) and cognitive limitations can crowd out principles.
- **Overconfidence** leads people to overrate their own ethical judgement.

## A framework for ethical decision-making
1. **Identify** the relevant facts, stakeholders, duties, and conflicts.
2. **Consider** guidance (the Code and Standards), alternatives, and consequences.
3. **Decide and act.**
4. **Reflect** on the outcome.

## The role of the profession
A **profession** serves society and holds members to a code. The **CFA Institute** promotes ethics and professional excellence. Unethical behaviour by a few damages trust for all — trust is hard to build and easily lost, and its loss raises costs and harms markets.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "cfa-quantitative-methods-portfolio-mathematics-m01", topicId: "cfa-quantitative-methods-portfolio-mathematics", title: "Portfolio Mathematics", content: `## Expected return
A portfolio's expected return is the **weighted average** of the assets' expected returns:
\`\`\`
E(Rp) = w₁E(R₁) + w₂E(R₂) + …
\`\`\`

## Risk depends on covariance
Portfolio **variance is not** a simple weighted average — it depends on how assets move together. For two assets:
\`\`\`
σ²p = w₁²σ₁² + w₂²σ₂² + 2w₁w₂ρ₁₂σ₁σ₂
\`\`\`
- **Covariance** measures the co-movement of two returns; **correlation (ρ)** standardises it to a range of **−1 to +1**.
- \`Cov(1,2) = ρ₁₂ × σ₁ × σ₂\`.

## Diversification
The lower the correlation, the greater the **diversification benefit** — risk falls below the weighted average of the individual risks. With **ρ = +1** there is no diversification; with **ρ = −1** risk can be driven toward zero. Because covariance drives portfolio risk, adding an asset with low or negative correlation reduces total portfolio variance.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "cfa-quantitative-methods-simulation-methods-m01", topicId: "cfa-quantitative-methods-simulation-methods", title: "Simulation Methods", content: `Simulation models uncertainty by generating many possible outcomes.

## Monte Carlo simulation
Repeatedly draws **random values** for the uncertain inputs (from assumed distributions), computes the result each time, and builds a **distribution of outcomes**.
- **Uses**: valuing complex options, estimating **Value at Risk**, retirement/financial planning, and stress testing.
- **Strengths**: handles complex, path-dependent problems with no closed-form solution.
- **Limitations**: results are only as good as the input assumptions ('garbage in, garbage out'); it is a **statistical estimate**, not an analytical/exact answer.

## Bootstrapping
**Resamples** (with replacement) from an **observed** data set to build a sampling distribution, rather than assuming a theoretical distribution. It is useful when the true distribution is unknown.

## Asset prices
Asset **prices** are often modelled as **lognormal** (they cannot fall below zero), while continuously compounded **returns** are modelled as normal.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "cfa-quantitative-methods-big-data-techniques-m01", topicId: "cfa-quantitative-methods-big-data-techniques", title: "Introduction to Big Data Techniques", content: `**Big data** is characterised by the **'three Vs' — volume, velocity, variety** (some add veracity/value).

## Data types
- **Structured** data fit neatly in rows/columns (e.g., prices, financial statements).
- **Unstructured** data have no predefined format (text, images, audio, social media, sensor/satellite data — 'alternative data').

## Processing steps
Data must be **captured, cleansed** (fix errors/missing values), and **wrangled/transformed** into a usable format before analysis.

## Analytical techniques
- **Machine learning**: **supervised** (labelled data → prediction/classification), **unsupervised** (find structure, e.g., clustering), and **deep learning** (neural networks).
- **Natural language processing (NLP)** extracts meaning and sentiment from text.

## Applications & cautions
Big-data techniques power sentiment analysis, factor discovery and risk models. Key risks: poor **data quality**, and **overfitting** a model to noise so it fails on new data.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "cfa-economics-capital-flows-fx-m01", topicId: "cfa-economics-capital-flows-fx", title: "Capital Flows & the FX Market", content: `The **foreign exchange (FX) market** is the largest financial market; participants include banks, corporations, investors, governments and central banks.

## Quotes
- A **spot** rate is for near-immediate delivery; a **forward** rate is for a future date.
- The **real exchange rate** adjusts the nominal rate for relative price levels (purchasing power).

## Balance of payments
A country's international transactions are recorded in the:
- **Current account** (trade in goods/services, income, transfers), and the
- **Capital and financial account** (cross-border investment flows). A current-account deficit is financed by a financial-account surplus (net capital inflows).

## Drivers of exchange rates
- **Relative interest rates** and **inflation** (higher relative inflation tends to weaken a currency).
- **Capital flows**: strong investment inflows raise demand for a currency.
- **Trade balances**, risk sentiment, and central-bank/exchange-rate **regimes** (fixed, pegged, floating).

A stronger domestic currency makes exports dearer and imports cheaper, affecting the trade balance.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "cfa-financial-reporting-long-term-assets-m01", topicId: "cfa-financial-reporting-long-term-assets", title: "Analysis of Long-Term Assets", content: `## Capitalise vs expense
Costs that provide future benefits beyond one period are **capitalised** (recorded as assets and depreciated/amortised); costs consumed now are **expensed**. Capitalising raises current income and assets but lowers future income (via depreciation).

## Property, plant & equipment
Depreciated over useful life. Methods: **straight-line** (equal each year), **accelerated/double-declining balance** (more early), and **units-of-production**.

## Intangibles
- **Finite-life** intangibles (patents) are **amortised**; **indefinite-life** intangibles are **not amortised** but tested for impairment.
- **Goodwill** (from acquisitions) is **not amortised** — it is tested annually for **impairment**.

## Impairment & revaluation
- An asset is **impaired** when its carrying value exceeds its recoverable amount; the write-down reduces income.
- **IFRS** permits the **revaluation model** (upward revaluation to fair value); **US GAAP** uses historical cost only. Under IFRS, impairment losses (except goodwill) may be reversed; under US GAAP they generally may not.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "cfa-financial-reporting-financial-modeling-m01", topicId: "cfa-financial-reporting-financial-modeling", title: "Introduction to Financial Statement Modeling", content: `Financial modelling builds **pro-forma (forecast) statements** to value a company or test scenarios.

## Building the model
1. **Forecast revenue** — **top-down** (from the economy/industry to market share) or **bottom-up** (from the company's units/segments up).
2. **Model costs and margins** (fixed vs variable; economies of scale).
3. Link the **income statement → balance sheet → cash flow statement**; the statements must **articulate** (tie together), often using a financing **'plug'** (revolving debt or cash) to balance.

## Techniques
- **Sensitivity analysis** varies one input; **scenario analysis** varies a coherent set (e.g., recession vs boom).
- Consider the **competitive environment** (Porter's forces), pricing power and industry structure.

## Behavioural pitfalls
Analysts are prone to **overconfidence**, **anchoring** to past figures, **confirmation bias**, and **base-rate neglect** — all of which can distort forecasts. Good modelling checks assumptions against history and the competitive reality.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "cfa-corporate-issuers-corporate-restructuring-m01", topicId: "cfa-corporate-issuers-corporate-restructuring", title: "Corporate Restructuring", content: `Corporate restructuring changes a firm's **structure, operations, or ownership**. Actions fall into three types:
| Type | Examples |
| --- | --- |
| **Investment** (expansion) | Acquisitions, mergers, joint ventures, equity investments |
| **Divestment** (contraction) | **Spin-offs**, split-offs, **carve-outs**, sales of divisions |
| **Restructuring** | Cost cuts, balance-sheet restructuring, reorganisation, **bankruptcy** |

## Mergers & acquisitions
- Motivations: **synergies** (cost or revenue), growth, diversification, market power, and acquiring undervalued targets.
- **Synergy** means the combined firm is worth more than the sum of the parts.

## Valuation of targets
Three common approaches:
- **Comparable company analysis** — multiples of similar public firms (plus a takeover premium).
- **Comparable transaction analysis** — multiples paid in similar past deals (premium already embedded).
- **Premium-paid analysis** — the premium over the target's pre-announcement price.

Firms restructure to unlock value, respond to distress, refocus on core operations, or exploit perceived mispricing.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "cfa-equity-company-forecasting-m01", topicId: "cfa-equity-company-forecasting", title: "Company Analysis: Forecasting", content: `Company analysis forecasts a firm's future **revenues, costs, and cash flows** to support valuation.

## Forecasting revenue
- Identify **growth drivers**: volume, price, market size, and **market share**.
- Approaches: **top-down** (economy → industry → company) and **bottom-up** (product/segment build-up). A **hybrid** blends both.

## Costs and profitability
Separate **fixed vs variable** costs, model **operating leverage**, and consider **economies of scale** and input-cost trends. This yields forecast margins.

## Competitive position
A firm's **competitive advantage** (a 'moat' — brands, patents, network effects, cost advantage) determines whether high returns are **sustainable**. Porter's five forces frame the industry's attractiveness.

## Scenarios and pitfalls
Use **scenario analysis** (base/bull/bear) to reflect uncertainty. Beware behavioural biases — **overconfidence**, **anchoring**, and extrapolating recent trends too far. Forecasts feed directly into DCF and multiple-based valuations.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "cfa-fixed-income-cash-flows-types-m01", topicId: "cfa-fixed-income-cash-flows-types", title: "Fixed-Income Cash Flows & Types", content: `Bonds differ in how **principal** is repaid and how **coupons** are paid.

## Principal repayment structures
| Structure | Description |
| --- | --- |
| **Bullet** | Coupons over the life; **entire principal at maturity** |
| **Fully amortising** | Level payments repay principal gradually to zero |
| **Partially amortising** | Amortises partly, leaving a **balloon** payment at maturity |
| **Sinking fund** | Issuer retires part of the principal on a schedule |

## Coupon structures
- **Fixed-rate**, **floating-rate (FRN)** (reference rate + spread), **step-up** (rises on a schedule), **deferred/split** (no early coupons), and **payment-in-kind (PIK)** (pays coupons in more bonds, not cash).
- **Index-linked** bonds tie coupon/principal to an index (e.g., inflation-linked).

## Contingency provisions (embedded options)
- **Callable** (issuer may redeem early — benefits the issuer), **putable** (holder may sell back early — benefits the investor), and **convertible** (holder may convert into equity).`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "cfa-fixed-income-government-corporate-markets-m01", topicId: "cfa-fixed-income-government-corporate-markets", title: "Government & Corporate Fixed-Income Markets", content: `## Government (sovereign) debt
- **Treasury bills** (≤1 year, zero-coupon, sold at a discount), **notes** (2–10 years) and **bonds** (>10 years).
- The most recently issued, most liquid security is **on-the-run**; older issues are **off-the-run**.
- **Non-sovereign** (local government) and **quasi-government/agency** bonds also exist, as do **supranationals**.

## Corporate & financial issuers
Non-financial corporations raise debt through:
- **Bank loans** and **syndicated loans** (a group of lenders),
- **Commercial paper** (short-term, unsecured),
- **Medium-term notes (MTNs)**, and **corporate bonds**.

Financial issuers (banks) rely heavily on **deposits**, **interbank funding**, and the **repo market** for funding.

## Markets & seniority
Corporate bonds carry a **credit spread** over government yields for default and liquidity risk. In the capital structure, **secured** debt ranks above **senior unsecured**, which ranks above **subordinated** debt.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "cfa-fixed-income-curve-empirical-duration-m01", topicId: "cfa-fixed-income-curve-empirical-duration", title: "Curve-Based & Empirical Duration", content: `Beyond a single yield duration, several measures capture interest-rate risk more richly.

## Curve-based (effective) duration
**Effective duration** estimates price sensitivity to a **parallel shift in the benchmark yield curve**, computed from the bond's prices under small up/down shifts. It is essential for bonds with **embedded options**, whose cash flows change with rates.

## Key rate durations
**Key rate (partial) durations** measure sensitivity to a yield change at a **specific maturity**, capturing the effect of **non-parallel** (steepening/flattening) curve moves that one duration number misses.

## Empirical duration
**Analytical (yield) durations** are computed from a pricing formula. **Empirical duration** is instead **estimated statistically** — by regressing a bond's actual price changes on benchmark yield changes using historical data.
- It captures how yields and **credit spreads move together**. For example, in a risk-off episode government yields fall while high-yield spreads widen, so a high-yield bond's **empirical duration is often lower** than its analytical duration.
- Empirical duration is especially useful for **credit-risky** bonds and portfolios.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "cfa-portfolio-management-active-management-m01", topicId: "cfa-portfolio-management-active-management", title: "Analysis of Active Portfolio Management", content: `**Active management** seeks returns above a benchmark; its value is judged by return **relative to the benchmark**.

## Active return and active risk
- **Active return** = portfolio return − benchmark return (also 'value added').
- **Active risk** = **tracking error** = the standard deviation of active returns.

## The information ratio
\`\`\`
Information Ratio (IR) = active return / active risk
\`\`\`
The IR measures **risk-adjusted active performance** — value added per unit of tracking error. A higher IR is better; it is unaffected by the amount of leverage/scaling of active positions.

## The fundamental law of active management
\`\`\`
IR ≈ IC × √(breadth)
\`\`\`
- **IC (information coefficient)** — the skill/quality of the manager's forecasts.
- **Breadth (BR)** — the number of **independent** active decisions per year.

So performance improves with **more skill** and **more independent bets**. Active management must overcome its **higher fees and costs**; if the expected value added does not exceed those costs, low-cost passive/index investing is preferable.`, estimatedReadTime: 2, orderIndex: 0 }
];

export const exp10Questions: Question[] = [
  // ── Ethics & Trust in the Investment Profession ──
  { id: "cfa-ethics-ethics-and-trust-q01", topicId: "cfa-ethics-ethics-and-trust", text: "The investment profession fundamentally depends on:", optionA: "Client trust", optionB: "High leverage", optionC: "Frequent trading", optionD: "Tax avoidance", correctOption: "A", explanation: "Because clients entrust their capital to professionals, trust is the foundation of the industry.", orderIndex: 0 },
  { id: "cfa-ethics-ethics-and-trust-q02", topicId: "cfa-ethics-ethics-and-trust", text: "Ethical standards, relative to legal standards, generally:", optionA: "Go beyond the minimum set by law", optionB: "Are always identical to law", optionC: "Are less demanding than law", optionD: "Replace the law", correctOption: "A", explanation: "Laws set a minimum; ethics often demand more, and high conduct meets the stricter of the two.", orderIndex: 1 },
  { id: "cfa-ethics-ethics-and-trust-q03", topicId: "cfa-ethics-ethics-and-trust", text: "An act can be:", optionA: "Legal but unethical", optionB: "Never legal and ethical at once", optionC: "Only ethical if legal", optionD: "Only legal if ethical", correctOption: "A", explanation: "Legality and ethics do not always coincide — some legal acts are unethical, and vice versa.", orderIndex: 2 },
  { id: "cfa-ethics-ethics-and-trust-q04", topicId: "cfa-ethics-ethics-and-trust", text: "A common situational influence that undermines ethical behaviour is:", optionA: "Money and loyalty pressures", optionB: "Reading the Standards", optionC: "Reflecting on outcomes", optionD: "Disclosure", correctOption: "A", explanation: "Money, loyalty and peer pressure are situational influences that can override principles.", orderIndex: 3 },
  { id: "cfa-ethics-ethics-and-trust-q05", topicId: "cfa-ethics-ethics-and-trust", text: "A robust ethical decision-making framework typically begins by:", optionA: "Identifying the facts, stakeholders and conflicts", optionB: "Executing the trade", optionC: "Ignoring the Code", optionD: "Maximising personal gain", correctOption: "A", explanation: "The first step is to identify relevant facts, stakeholders, duties and conflicts of interest.", orderIndex: 4 },
  { id: "cfa-ethics-ethics-and-trust-q06", topicId: "cfa-ethics-ethics-and-trust", text: "Overconfidence in one's own ethics tends to:", optionA: "Increase the risk of misconduct", optionB: "Guarantee ethical behaviour", optionC: "Have no effect", optionD: "Improve compliance", correctOption: "A", explanation: "People who overrate their ethical judgement are less vigilant and more prone to lapses.", orderIndex: 5 },
  { id: "cfa-ethics-ethics-and-trust-q07", topicId: "cfa-ethics-ethics-and-trust", text: "A defining feature of a 'profession' is that it:", optionA: "Serves society and holds members to a code of conduct", optionB: "Maximises members' pay only", optionC: "Has no standards", optionD: "Avoids regulation", correctOption: "A", explanation: "A profession serves the greater good and enforces ethical standards among its members.", orderIndex: 6 },
  { id: "cfa-ethics-ethics-and-trust-q08", topicId: "cfa-ethics-ethics-and-trust", text: "Unethical behaviour by a few investment professionals tends to:", optionA: "Damage trust across the whole profession", optionB: "Only affect those individuals", optionC: "Improve market confidence", optionD: "Reduce systemic risk", correctOption: "A", explanation: "Misconduct erodes trust broadly, harming clients and markets beyond the wrongdoers.", orderIndex: 7 },
  { id: "cfa-ethics-ethics-and-trust-q09", topicId: "cfa-ethics-ethics-and-trust", text: "When ethics and law conflict, a member should follow:", optionA: "The stricter standard", optionB: "Whichever is cheaper", optionC: "The law only", optionD: "Personal preference", correctOption: "A", explanation: "Members should adhere to the more demanding of the ethical or legal standard.", orderIndex: 8 },
  { id: "cfa-ethics-ethics-and-trust-q10", topicId: "cfa-ethics-ethics-and-trust", text: "Trust in the investment industry is best described as:", optionA: "Hard to build and easily lost", optionB: "Automatic and permanent", optionC: "Irrelevant to returns", optionD: "Guaranteed by law", correctOption: "A", explanation: "Trust takes time to earn but can be destroyed quickly by misconduct.", orderIndex: 9 },
  { id: "cfa-ethics-ethics-and-trust-q11", topicId: "cfa-ethics-ethics-and-trust", text: "The final step of an ethical decision-making framework is usually to:", optionA: "Reflect on the outcome", optionB: "Forget the decision", optionC: "Hide the result", optionD: "Blame others", correctOption: "A", explanation: "Reflecting on the outcome supports learning and better future decisions.", orderIndex: 10 },
  { id: "cfa-ethics-ethics-and-trust-q12", topicId: "cfa-ethics-ethics-and-trust", text: "A loss of trust in financial markets tends to:", optionA: "Raise costs and reduce participation", optionB: "Lower transaction costs", optionC: "Increase liquidity", optionD: "Have no economic effect", correctOption: "A", explanation: "When trust falls, participants demand more protection, raising costs and shrinking markets.", orderIndex: 11 },

  // ── Portfolio Mathematics ──
  { id: "cfa-quantitative-methods-portfolio-mathematics-q01", topicId: "cfa-quantitative-methods-portfolio-mathematics", text: "The expected return of a portfolio is the:", optionA: "Weighted average of the assets' expected returns", optionB: "Sum of the assets' variances", optionC: "Highest asset return", optionD: "Product of the returns", correctOption: "A", explanation: "Portfolio expected return is the weight-weighted average of the component expected returns.", orderIndex: 0 },
  { id: "cfa-quantitative-methods-portfolio-mathematics-q02", topicId: "cfa-quantitative-methods-portfolio-mathematics", text: "Unlike expected return, portfolio variance depends on:", optionA: "The covariance/correlation between assets", optionB: "Only the weights", optionC: "The largest variance alone", optionD: "The number of assets only", correctOption: "A", explanation: "Portfolio variance is driven by how assets co-move, captured by covariance/correlation.", orderIndex: 1 },
  { id: "cfa-quantitative-methods-portfolio-mathematics-q03", topicId: "cfa-quantitative-methods-portfolio-mathematics", text: "The correlation coefficient ranges between:", optionA: "−1 and +1", optionB: "0 and 1", optionC: "−∞ and +∞", optionD: "0 and 100", correctOption: "A", explanation: "Correlation is a standardised measure of co-movement bounded by −1 and +1.", orderIndex: 2 },
  { id: "cfa-quantitative-methods-portfolio-mathematics-q04", topicId: "cfa-quantitative-methods-portfolio-mathematics", text: "Covariance between two assets equals:", optionA: "Correlation × σ₁ × σ₂", optionB: "Correlation / (σ₁σ₂)", optionC: "σ₁ + σ₂", optionD: "σ₁ − σ₂", correctOption: "A", explanation: "Cov(1,2) = ρ₁₂ × σ₁ × σ₂.", orderIndex: 3 },
  { id: "cfa-quantitative-methods-portfolio-mathematics-q05", topicId: "cfa-quantitative-methods-portfolio-mathematics", text: "The diversification benefit is greatest when the correlation between assets is:", optionA: "As low (or negative) as possible", optionB: "Exactly +1", optionC: "Zero only", optionD: "Undefined", correctOption: "A", explanation: "Lower correlation reduces portfolio risk more; at ρ = −1 risk can approach zero.", orderIndex: 4 },
  { id: "cfa-quantitative-methods-portfolio-mathematics-q06", topicId: "cfa-quantitative-methods-portfolio-mathematics", text: "If two assets have a correlation of +1, combining them provides:", optionA: "No diversification benefit", optionB: "Maximum diversification", optionC: "Zero risk", optionD: "Negative risk", correctOption: "A", explanation: "Perfectly correlated assets move together, so no risk reduction is achieved.", orderIndex: 5 },
  { id: "cfa-quantitative-methods-portfolio-mathematics-q07", topicId: "cfa-quantitative-methods-portfolio-mathematics", text: "In the two-asset variance formula, the term 2w₁w₂ρσ₁σ₂ represents the:", optionA: "Covariance contribution", optionB: "Total variance", optionC: "Expected return", optionD: "Risk-free rate", correctOption: "A", explanation: "That cross term is the covariance contribution to portfolio variance.", orderIndex: 6 },
  { id: "cfa-quantitative-methods-portfolio-mathematics-q08", topicId: "cfa-quantitative-methods-portfolio-mathematics", text: "Adding an asset with low correlation to a portfolio tends to:", optionA: "Reduce total portfolio variance", optionB: "Increase total variance", optionC: "Leave variance unchanged", optionD: "Eliminate expected return", correctOption: "A", explanation: "Low-correlation assets lower overall portfolio variance through diversification.", orderIndex: 7 },
  { id: "cfa-quantitative-methods-portfolio-mathematics-q09", topicId: "cfa-quantitative-methods-portfolio-mathematics", text: "A positive covariance between two assets means they tend to:", optionA: "Move in the same direction", optionB: "Move in opposite directions", optionC: "Be uncorrelated", optionD: "Have zero variance", correctOption: "A", explanation: "Positive covariance indicates the returns tend to rise and fall together.", orderIndex: 8 },
  { id: "cfa-quantitative-methods-portfolio-mathematics-q10", topicId: "cfa-quantitative-methods-portfolio-mathematics", text: "The correlation coefficient is preferred to covariance because it is:", optionA: "Standardised and unit-free", optionB: "Always positive", optionC: "Larger", optionD: "Equal to variance", correctOption: "A", explanation: "Correlation rescales covariance to a bounded, unit-free measure that is easier to interpret.", orderIndex: 9 },
  { id: "cfa-quantitative-methods-portfolio-mathematics-q11", topicId: "cfa-quantitative-methods-portfolio-mathematics", text: "A correlation of 0 between two assets implies:", optionA: "No linear relationship between their returns", optionB: "They are identical", optionC: "Perfect negative co-movement", optionD: "Zero variance", correctOption: "A", explanation: "Zero correlation means no linear co-movement between the two return series.", orderIndex: 10 },
  { id: "cfa-quantitative-methods-portfolio-mathematics-q12", topicId: "cfa-quantitative-methods-portfolio-mathematics", text: "Portfolio risk is generally ___ the weighted average of the individual asset risks when correlations are below 1.", optionA: "Less than", optionB: "Greater than", optionC: "Equal to", optionD: "Unrelated to", correctOption: "A", explanation: "Imperfect correlation makes portfolio standard deviation less than the weighted average of the components.", orderIndex: 11 },

  // ── Simulation Methods ──
  { id: "cfa-quantitative-methods-simulation-methods-q01", topicId: "cfa-quantitative-methods-simulation-methods", text: "Monte Carlo simulation works by:", optionA: "Repeatedly generating random inputs to build a distribution of outcomes", optionB: "Solving one exact equation", optionC: "Averaging two data points", optionD: "Ignoring uncertainty", correctOption: "A", explanation: "Monte Carlo draws many random scenarios for uncertain inputs and aggregates the results.", orderIndex: 0 },
  { id: "cfa-quantitative-methods-simulation-methods-q02", topicId: "cfa-quantitative-methods-simulation-methods", text: "A common application of Monte Carlo simulation is:", optionA: "Estimating Value at Risk", optionB: "Filing taxes", optionC: "Auditing", optionD: "Setting coupon rates", correctOption: "A", explanation: "Monte Carlo is widely used for VaR, option pricing and retirement planning.", orderIndex: 1 },
  { id: "cfa-quantitative-methods-simulation-methods-q03", topicId: "cfa-quantitative-methods-simulation-methods", text: "Bootstrapping generates a sampling distribution by:", optionA: "Resampling with replacement from observed data", optionB: "Assuming a normal distribution", optionC: "Using a single observation", optionD: "Ignoring the data", correctOption: "A", explanation: "Bootstrapping repeatedly resamples the actual data set to approximate the sampling distribution.", orderIndex: 2 },
  { id: "cfa-quantitative-methods-simulation-methods-q04", topicId: "cfa-quantitative-methods-simulation-methods", text: "A key limitation of Monte Carlo simulation is that:", optionA: "Its output is only as good as the input assumptions", optionB: "It gives an exact analytical answer", optionC: "It cannot handle uncertainty", optionD: "It needs no computer", correctOption: "A", explanation: "'Garbage in, garbage out' — poor assumptions produce misleading simulated results.", orderIndex: 3 },
  { id: "cfa-quantitative-methods-simulation-methods-q05", topicId: "cfa-quantitative-methods-simulation-methods", text: "Asset prices are commonly modelled as following a ___ distribution.", optionA: "Lognormal", optionB: "Uniform", optionC: "Binomial only", optionD: "Negative", correctOption: "A", explanation: "Prices are modelled as lognormal because they cannot be negative; continuously compounded returns are modelled as normal.", orderIndex: 4 },
  { id: "cfa-quantitative-methods-simulation-methods-q06", topicId: "cfa-quantitative-methods-simulation-methods", text: "A strength of simulation methods is that they can:", optionA: "Handle complex problems that lack closed-form solutions", optionB: "Eliminate all uncertainty", optionC: "Guarantee accuracy", optionD: "Avoid assumptions", correctOption: "A", explanation: "Simulation is valuable for complex, path-dependent problems where analytical solutions do not exist.", orderIndex: 5 },
  { id: "cfa-quantitative-methods-simulation-methods-q07", topicId: "cfa-quantitative-methods-simulation-methods", text: "Bootstrapping is especially useful when:", optionA: "The true underlying distribution is unknown", optionB: "The distribution is known exactly", optionC: "There is no data", optionD: "Only the mean matters", correctOption: "A", explanation: "Bootstrapping avoids assuming a theoretical distribution, using the observed data instead.", orderIndex: 6 },
  { id: "cfa-quantitative-methods-simulation-methods-q08", topicId: "cfa-quantitative-methods-simulation-methods", text: "A Monte Carlo result is best described as a:", optionA: "Statistical estimate, not an exact value", optionB: "Precise closed-form answer", optionC: "Deterministic constant", optionD: "Guaranteed forecast", correctOption: "A", explanation: "Simulation produces an approximate, statistical estimate that varies with the random draws.", orderIndex: 7 },
  { id: "cfa-quantitative-methods-simulation-methods-q09", topicId: "cfa-quantitative-methods-simulation-methods", text: "Increasing the number of Monte Carlo trials generally:", optionA: "Improves the precision of the estimate", optionB: "Reduces precision", optionC: "Has no effect", optionD: "Changes the assumptions", correctOption: "A", explanation: "More simulation runs reduce sampling error and sharpen the estimated distribution.", orderIndex: 8 },
  { id: "cfa-quantitative-methods-simulation-methods-q10", topicId: "cfa-quantitative-methods-simulation-methods", text: "In Monte Carlo simulation, each uncertain input is drawn from:", optionA: "An assumed probability distribution", optionB: "A single fixed value", optionC: "The mean only", optionD: "The risk-free rate", correctOption: "A", explanation: "Each simulated input is sampled from a specified probability distribution.", orderIndex: 9 },
  { id: "cfa-quantitative-methods-simulation-methods-q11", topicId: "cfa-quantitative-methods-simulation-methods", text: "Continuously compounded asset returns are typically assumed to be:", optionA: "Normally distributed", optionB: "Lognormally distributed", optionC: "Uniformly distributed", optionD: "Always positive", correctOption: "A", explanation: "If prices are lognormal, the continuously compounded returns are normally distributed.", orderIndex: 10 },
  { id: "cfa-quantitative-methods-simulation-methods-q12", topicId: "cfa-quantitative-methods-simulation-methods", text: "Both Monte Carlo and bootstrapping are used to:", optionA: "Model uncertainty and build distributions of outcomes", optionB: "Eliminate randomness", optionC: "Replace the balance sheet", optionD: "Set interest rates", correctOption: "A", explanation: "Both are simulation techniques for characterising uncertainty in outcomes.", orderIndex: 11 },

  // ── Introduction to Big Data Techniques ──
  { id: "cfa-quantitative-methods-big-data-techniques-q01", topicId: "cfa-quantitative-methods-big-data-techniques", text: "The 'three Vs' of big data are volume, velocity and:", optionA: "Variety", optionB: "Volatility", optionC: "Value", optionD: "Verification", correctOption: "A", explanation: "Big data is characterised by volume, velocity and variety (sometimes plus veracity/value).", orderIndex: 0 },
  { id: "cfa-quantitative-methods-big-data-techniques-q02", topicId: "cfa-quantitative-methods-big-data-techniques", text: "Text, images and social-media posts are examples of:", optionA: "Unstructured data", optionB: "Structured data", optionC: "Tabular data", optionD: "Numeric-only data", correctOption: "A", explanation: "Unstructured data lacks a predefined row/column format, unlike structured data.", orderIndex: 1 },
  { id: "cfa-quantitative-methods-big-data-techniques-q03", topicId: "cfa-quantitative-methods-big-data-techniques", text: "Fixing errors and handling missing values in a dataset is part of:", optionA: "Data cleansing", optionB: "Data capture only", optionC: "Model deployment", optionD: "Forecasting", correctOption: "A", explanation: "Cleansing corrects errors and missing values before analysis.", orderIndex: 2 },
  { id: "cfa-quantitative-methods-big-data-techniques-q04", topicId: "cfa-quantitative-methods-big-data-techniques", text: "Supervised machine learning uses:", optionA: "Labelled data to predict or classify", optionB: "Only unlabelled data", optionC: "No data", optionD: "Manual rules only", correctOption: "A", explanation: "Supervised learning trains on labelled inputs/outputs to make predictions.", orderIndex: 3 },
  { id: "cfa-quantitative-methods-big-data-techniques-q05", topicId: "cfa-quantitative-methods-big-data-techniques", text: "Clustering is an example of:", optionA: "Unsupervised learning", optionB: "Supervised learning", optionC: "Regression", optionD: "Manual sorting", correctOption: "A", explanation: "Clustering finds structure in unlabelled data — a form of unsupervised learning.", orderIndex: 4 },
  { id: "cfa-quantitative-methods-big-data-techniques-q06", topicId: "cfa-quantitative-methods-big-data-techniques", text: "Natural language processing (NLP) is used to:", optionA: "Extract meaning and sentiment from text", optionB: "Store numbers", optionC: "Set coupon rates", optionD: "Audit accounts", correctOption: "A", explanation: "NLP analyses text data such as filings, news and social media.", orderIndex: 5 },
  { id: "cfa-quantitative-methods-big-data-techniques-q07", topicId: "cfa-quantitative-methods-big-data-techniques", text: "'Alternative data' refers to:", optionA: "Non-traditional sources such as satellite images and social media", optionB: "Audited financial statements", optionC: "Official GDP data", optionD: "Company filings only", correctOption: "A", explanation: "Alternative data comes from non-traditional sources like sensors, satellites and web activity.", orderIndex: 6 },
  { id: "cfa-quantitative-methods-big-data-techniques-q08", topicId: "cfa-quantitative-methods-big-data-techniques", text: "Deep learning relies on:", optionA: "Multi-layered neural networks", optionB: "A single linear equation", optionC: "Manual rules", optionD: "Spreadsheets only", correctOption: "A", explanation: "Deep learning uses neural networks with many layers to model complex patterns.", orderIndex: 7 },
  { id: "cfa-quantitative-methods-big-data-techniques-q09", topicId: "cfa-quantitative-methods-big-data-techniques", text: "A major risk when fitting models to big data is:", optionA: "Overfitting to noise", optionB: "Too little computation", optionC: "Excessive simplicity always", optionD: "Having no data", correctOption: "A", explanation: "Overfitting captures noise rather than signal, harming out-of-sample performance.", orderIndex: 8 },
  { id: "cfa-quantitative-methods-big-data-techniques-q10", topicId: "cfa-quantitative-methods-big-data-techniques", text: "Transforming raw data into a usable analytical format is called:", optionA: "Data wrangling (preparation)", optionB: "Data destruction", optionC: "Backtesting", optionD: "Reporting", correctOption: "A", explanation: "Wrangling/preparation reshapes and transforms cleansed data for analysis.", orderIndex: 9 },
  { id: "cfa-quantitative-methods-big-data-techniques-q11", topicId: "cfa-quantitative-methods-big-data-techniques", text: "Structured data are best described as:", optionA: "Organised in rows and columns", optionB: "Free-form text", optionC: "Images only", optionD: "Audio recordings", correctOption: "A", explanation: "Structured data fit neatly into a predefined tabular (rows/columns) format.", orderIndex: 10 },
  { id: "cfa-quantitative-methods-big-data-techniques-q12", topicId: "cfa-quantitative-methods-big-data-techniques", text: "The reliability/accuracy dimension sometimes added to big data's characteristics is:", optionA: "Veracity", optionB: "Velocity", optionC: "Volume", optionD: "Variety", correctOption: "A", explanation: "Veracity refers to the trustworthiness and accuracy of the data.", orderIndex: 11 },

  // ── Capital Flows & the FX Market ──
  { id: "cfa-economics-capital-flows-fx-q01", topicId: "cfa-economics-capital-flows-fx", text: "A spot exchange rate is for:", optionA: "Near-immediate delivery", optionB: "Delivery in one year", optionC: "A future date only", optionD: "Interest payments", correctOption: "A", explanation: "The spot rate settles almost immediately; forward rates apply to future dates.", orderIndex: 0 },
  { id: "cfa-economics-capital-flows-fx-q02", topicId: "cfa-economics-capital-flows-fx", text: "A country's trade in goods and services is recorded in the:", optionA: "Current account", optionB: "Capital account only", optionC: "Financial account only", optionD: "Reserve account", correctOption: "A", explanation: "The current account captures trade, income and transfers.", orderIndex: 1 },
  { id: "cfa-economics-capital-flows-fx-q03", topicId: "cfa-economics-capital-flows-fx", text: "Cross-border investment flows are recorded in the:", optionA: "Capital and financial account", optionB: "Current account", optionC: "Income statement", optionD: "Trade balance only", correctOption: "A", explanation: "The capital and financial account records international investment (capital) flows.", orderIndex: 2 },
  { id: "cfa-economics-capital-flows-fx-q04", topicId: "cfa-economics-capital-flows-fx", text: "A current-account deficit is generally financed by:", optionA: "A financial-account surplus (net capital inflows)", optionB: "A larger trade surplus", optionC: "Lower investment", optionD: "Higher exports only", correctOption: "A", explanation: "A current-account deficit must be offset by net capital inflows in the financial account.", orderIndex: 3 },
  { id: "cfa-economics-capital-flows-fx-q05", topicId: "cfa-economics-capital-flows-fx", text: "All else equal, higher relative inflation tends to:", optionA: "Weaken a country's currency", optionB: "Strengthen the currency", optionC: "Have no effect", optionD: "Fix the exchange rate", correctOption: "A", explanation: "Higher relative inflation erodes purchasing power and tends to depreciate the currency.", orderIndex: 4 },
  { id: "cfa-economics-capital-flows-fx-q06", topicId: "cfa-economics-capital-flows-fx", text: "The real exchange rate adjusts the nominal rate for:", optionA: "Relative price levels (inflation)", optionB: "Interest income", optionC: "Trade volume", optionD: "Coupon payments", correctOption: "A", explanation: "The real exchange rate accounts for relative price levels between countries.", orderIndex: 5 },
  { id: "cfa-economics-capital-flows-fx-q07", topicId: "cfa-economics-capital-flows-fx", text: "Strong foreign investment inflows into a country tend to:", optionA: "Increase demand for its currency (appreciation)", optionB: "Weaken its currency", optionC: "Have no effect", optionD: "Cause deflation", correctOption: "A", explanation: "Capital inflows raise demand for the domestic currency, tending to appreciate it.", orderIndex: 6 },
  { id: "cfa-economics-capital-flows-fx-q08", topicId: "cfa-economics-capital-flows-fx", text: "A stronger domestic currency tends to make exports:", optionA: "More expensive to foreign buyers", optionB: "Cheaper abroad", optionC: "Free", optionD: "Unaffected", correctOption: "A", explanation: "Currency appreciation raises the foreign-currency price of exports, hurting competitiveness.", orderIndex: 7 },
  { id: "cfa-economics-capital-flows-fx-q09", topicId: "cfa-economics-capital-flows-fx", text: "The largest financial market in the world by volume is the:", optionA: "Foreign exchange market", optionB: "Equity market", optionC: "Corporate bond market", optionD: "Commodity market", correctOption: "A", explanation: "The FX market has the highest daily trading volume of any financial market.", orderIndex: 8 },
  { id: "cfa-economics-capital-flows-fx-q10", topicId: "cfa-economics-capital-flows-fx", text: "An exchange-rate regime in which the currency's value floats freely is called a:", optionA: "Floating (flexible) regime", optionB: "Fixed peg", optionC: "Currency board", optionD: "Gold standard", correctOption: "A", explanation: "Under a floating regime, market forces determine the exchange rate.", orderIndex: 9 },
  { id: "cfa-economics-capital-flows-fx-q11", topicId: "cfa-economics-capital-flows-fx", text: "Higher relative real interest rates in a country tend to:", optionA: "Attract capital and strengthen its currency", optionB: "Repel capital", optionC: "Weaken the currency", optionD: "Cause a trade surplus only", correctOption: "A", explanation: "Higher real rates draw yield-seeking capital, tending to appreciate the currency.", orderIndex: 10 },
  { id: "cfa-economics-capital-flows-fx-q12", topicId: "cfa-economics-capital-flows-fx", text: "A forward exchange rate is:", optionA: "Agreed now for currency exchange on a future date", optionB: "The current spot rate", optionC: "An interest rate", optionD: "A tax on trade", correctOption: "A", explanation: "A forward rate locks in today the exchange rate for a transaction settling in the future.", orderIndex: 11 },

  // ── Analysis of Long-Term Assets ──
  { id: "cfa-financial-reporting-long-term-assets-q01", topicId: "cfa-financial-reporting-long-term-assets", text: "A cost that provides benefits beyond the current period should generally be:", optionA: "Capitalised", optionB: "Expensed immediately", optionC: "Ignored", optionD: "Recorded as revenue", correctOption: "A", explanation: "Costs with future benefits are capitalised as assets and depreciated/amortised over time.", orderIndex: 0 },
  { id: "cfa-financial-reporting-long-term-assets-q02", topicId: "cfa-financial-reporting-long-term-assets", text: "Capitalising a cost rather than expensing it initially results in:", optionA: "Higher current-period net income", optionB: "Lower current assets", optionC: "Lower current income", optionD: "No effect on income", correctOption: "A", explanation: "Capitalising defers the expense, raising current income (and assets) but lowering future income.", orderIndex: 1 },
  { id: "cfa-financial-reporting-long-term-assets-q03", topicId: "cfa-financial-reporting-long-term-assets", text: "Goodwill is:", optionA: "Not amortised but tested for impairment", optionB: "Amortised over 10 years", optionC: "Expensed at purchase", optionD: "A current asset", correctOption: "A", explanation: "Goodwill has an indefinite life; it is not amortised but tested for impairment at least annually.", orderIndex: 2 },
  { id: "cfa-financial-reporting-long-term-assets-q04", topicId: "cfa-financial-reporting-long-term-assets", text: "A finite-life intangible asset such as a patent is:", optionA: "Amortised over its useful life", optionB: "Never expensed", optionC: "Revalued upward under US GAAP", optionD: "A liability", correctOption: "A", explanation: "Finite-life intangibles are amortised; indefinite-life intangibles are tested for impairment instead.", orderIndex: 3 },
  { id: "cfa-financial-reporting-long-term-assets-q05", topicId: "cfa-financial-reporting-long-term-assets", text: "The depreciation method producing the highest expense in the early years is:", optionA: "Double-declining balance", optionB: "Straight-line", optionC: "Units-of-production always", optionD: "No depreciation", correctOption: "A", explanation: "Double-declining balance is an accelerated method, front-loading depreciation.", orderIndex: 4 },
  { id: "cfa-financial-reporting-long-term-assets-q05b", topicId: "cfa-financial-reporting-long-term-assets", text: "Under IFRS, the model that allows carrying PP&E at fair value is the:", optionA: "Revaluation model", optionB: "LIFO model", optionC: "Historical cost model only", optionD: "Cash model", correctOption: "A", explanation: "IFRS permits the revaluation model for PP&E; US GAAP requires historical cost.", orderIndex: 5 },
  { id: "cfa-financial-reporting-long-term-assets-q07", topicId: "cfa-financial-reporting-long-term-assets", text: "An asset is impaired when its carrying value:", optionA: "Exceeds its recoverable amount", optionB: "Equals its cost", optionC: "Is below salvage value", optionD: "Rises with inflation", correctOption: "A", explanation: "Impairment occurs when carrying value exceeds the recoverable amount, requiring a write-down.", orderIndex: 6 },
  { id: "cfa-financial-reporting-long-term-assets-q08", topicId: "cfa-financial-reporting-long-term-assets", text: "Under US GAAP, reversal of a previously recognised impairment loss (other than assets held for sale) is:", optionA: "Generally prohibited", optionB: "Required annually", optionC: "Always allowed", optionD: "Recorded as revenue", correctOption: "A", explanation: "US GAAP generally prohibits reversing impairments; IFRS allows reversal (except goodwill).", orderIndex: 7 },
  { id: "cfa-financial-reporting-long-term-assets-q09", topicId: "cfa-financial-reporting-long-term-assets", text: "The units-of-production depreciation method bases expense on:", optionA: "Actual usage/output of the asset", optionB: "Time only", optionC: "The tax rate", optionD: "The market price", correctOption: "A", explanation: "Units-of-production allocates cost according to actual output or usage each period.", orderIndex: 8 },
  { id: "cfa-financial-reporting-long-term-assets-q10", topicId: "cfa-financial-reporting-long-term-assets", text: "Indefinite-life intangible assets are:", optionA: "Tested for impairment rather than amortised", optionB: "Amortised straight-line", optionC: "Expensed immediately", optionD: "Recorded as liabilities", correctOption: "A", explanation: "Indefinite-life intangibles (like some brands) are not amortised but tested for impairment.", orderIndex: 9 },
  { id: "cfa-financial-reporting-long-term-assets-q11", topicId: "cfa-financial-reporting-long-term-assets", text: "Compared with expensing, capitalising costs generally makes early-year cash flow from operations:", optionA: "Higher (the outflow is shown as investing)", optionB: "Lower", optionC: "Unchanged", optionD: "Negative", correctOption: "A", explanation: "Capitalised costs are classified as investing outflows, so operating cash flow appears higher.", orderIndex: 10 },
  { id: "cfa-financial-reporting-long-term-assets-q12", topicId: "cfa-financial-reporting-long-term-assets", text: "Straight-line depreciation allocates:", optionA: "An equal expense to each year of useful life", optionB: "More expense early", optionC: "More expense late", optionD: "No expense", correctOption: "A", explanation: "Straight-line spreads the depreciable cost evenly over the asset's useful life.", orderIndex: 11 },

  // ── Introduction to Financial Statement Modeling ──
  { id: "cfa-financial-reporting-financial-modeling-q01", topicId: "cfa-financial-reporting-financial-modeling", text: "Financial statement modelling produces:", optionA: "Pro-forma (forecast) financial statements", optionB: "Audited historical accounts only", optionC: "Tax returns", optionD: "Legal contracts", correctOption: "A", explanation: "Modelling builds forecast (pro-forma) statements to value a firm or test scenarios.", orderIndex: 0 },
  { id: "cfa-financial-reporting-financial-modeling-q02", topicId: "cfa-financial-reporting-financial-modeling", text: "Forecasting revenue from the overall economy down to a company's market share is a:", optionA: "Top-down approach", optionB: "Bottom-up approach", optionC: "Random approach", optionD: "Backward approach", correctOption: "A", explanation: "Top-down forecasting moves from macro/industry conditions to the individual company.", orderIndex: 1 },
  { id: "cfa-financial-reporting-financial-modeling-q03", topicId: "cfa-financial-reporting-financial-modeling", text: "Building revenue from a company's individual products or segments upward is a:", optionA: "Bottom-up approach", optionB: "Top-down approach", optionC: "Hybrid only", optionD: "Sensitivity test", correctOption: "A", explanation: "Bottom-up forecasting aggregates from the company's own units to a total.", orderIndex: 2 },
  { id: "cfa-financial-reporting-financial-modeling-q04", topicId: "cfa-financial-reporting-financial-modeling", text: "Varying a single input to see its effect on the output is:", optionA: "Sensitivity analysis", optionB: "Scenario analysis", optionC: "Auditing", optionD: "Consolidation", correctOption: "A", explanation: "Sensitivity analysis changes one variable at a time; scenario analysis changes a coherent set.", orderIndex: 3 },
  { id: "cfa-financial-reporting-financial-modeling-q05", topicId: "cfa-financial-reporting-financial-modeling", text: "A financing 'plug' in a model is used to:", optionA: "Balance the balance sheet (e.g., via debt or cash)", optionB: "Increase revenue", optionC: "Lower taxes", optionD: "Pay dividends", correctOption: "A", explanation: "The plug (revolver/cash) forces the projected balance sheet to balance.", orderIndex: 4 },
  { id: "cfa-financial-reporting-financial-modeling-q06", topicId: "cfa-financial-reporting-financial-modeling", text: "The behavioural bias of relying too heavily on an initial figure is:", optionA: "Anchoring", optionB: "Diversification", optionC: "Hedging", optionD: "Arbitrage", correctOption: "A", explanation: "Anchoring is over-reliance on an initial reference point when making estimates.", orderIndex: 5 },
  { id: "cfa-financial-reporting-financial-modeling-q07", topicId: "cfa-financial-reporting-financial-modeling", text: "Analysing coherent combinations of inputs (e.g., recession vs boom) is:", optionA: "Scenario analysis", optionB: "Sensitivity analysis", optionC: "Regression", optionD: "Reconciliation", correctOption: "A", explanation: "Scenario analysis evaluates outcomes under internally consistent sets of assumptions.", orderIndex: 6 },
  { id: "cfa-financial-reporting-financial-modeling-q08", topicId: "cfa-financial-reporting-financial-modeling", text: "The three financial statements in a model must:", optionA: "Articulate (tie together consistently)", optionB: "Be independent of each other", optionC: "Ignore cash flow", optionD: "Use different periods", correctOption: "A", explanation: "The income statement, balance sheet and cash flow statement must link consistently.", orderIndex: 7 },
  { id: "cfa-financial-reporting-financial-modeling-q09", topicId: "cfa-financial-reporting-financial-modeling", text: "The bias of seeking information that confirms one's existing view is:", optionA: "Confirmation bias", optionB: "Anchoring", optionC: "Recency", optionD: "Framing", correctOption: "A", explanation: "Confirmation bias leads analysts to favour evidence supporting their prior beliefs.", orderIndex: 8 },
  { id: "cfa-financial-reporting-financial-modeling-q10", topicId: "cfa-financial-reporting-financial-modeling", text: "Modelling a company's cost structure requires distinguishing:", optionA: "Fixed from variable costs", optionB: "Assets from equity", optionC: "Dividends from buybacks", optionD: "Spot from forward rates", correctOption: "A", explanation: "Separating fixed and variable costs drives margin and operating-leverage forecasts.", orderIndex: 9 },
  { id: "cfa-financial-reporting-financial-modeling-q11", topicId: "cfa-financial-reporting-financial-modeling", text: "Incorporating Porter's five forces into a model helps assess:", optionA: "The industry's competitive environment", optionB: "The tax rate", optionC: "The coupon rate", optionD: "The audit opinion", correctOption: "A", explanation: "The competitive environment shapes pricing power, margins and sustainable growth.", orderIndex: 10 },
  { id: "cfa-financial-reporting-financial-modeling-q12", topicId: "cfa-financial-reporting-financial-modeling", text: "Good modelling practice checks forecast assumptions against:", optionA: "Historical results and the competitive reality", optionB: "Nothing", optionC: "Only the best case", optionD: "The risk-free rate", correctOption: "A", explanation: "Grounding assumptions in history and competitive analysis reduces bias and improves realism.", orderIndex: 11 },

  // ── Corporate Restructuring ──
  { id: "cfa-corporate-issuers-corporate-restructuring-q01", topicId: "cfa-corporate-issuers-corporate-restructuring", text: "A spin-off is a form of corporate:", optionA: "Divestment (contraction)", optionB: "Investment (expansion)", optionC: "Dividend", optionD: "Share issuance", correctOption: "A", explanation: "A spin-off separates a business into an independent company — a form of divestment.", orderIndex: 0 },
  { id: "cfa-corporate-issuers-corporate-restructuring-q02", topicId: "cfa-corporate-issuers-corporate-restructuring", text: "An acquisition is an example of corporate:", optionA: "Investment (expansion)", optionB: "Divestment", optionC: "Liquidation", optionD: "Buyback", correctOption: "A", explanation: "Acquisitions and joint ventures expand the firm — investment actions.", orderIndex: 1 },
  { id: "cfa-corporate-issuers-corporate-restructuring-q03", topicId: "cfa-corporate-issuers-corporate-restructuring", text: "A primary motivation for mergers is to achieve:", optionA: "Synergies", optionB: "Higher taxes", optionC: "Lower revenue", optionD: "Fewer customers", correctOption: "A", explanation: "Synergies (cost or revenue) are a leading rationale for M&A.", orderIndex: 2 },
  { id: "cfa-corporate-issuers-corporate-restructuring-q04", topicId: "cfa-corporate-issuers-corporate-restructuring", text: "Synergy means the combined firm is worth:", optionA: "More than the sum of the separate parts", optionB: "Less than each part", optionC: "Exactly the sum of the parts", optionD: "Zero", correctOption: "A", explanation: "Synergy implies the whole is worth more than the standalone values combined.", orderIndex: 3 },
  { id: "cfa-corporate-issuers-corporate-restructuring-q05", topicId: "cfa-corporate-issuers-corporate-restructuring", text: "Valuing a target using multiples of similar listed firms is:", optionA: "Comparable company analysis", optionB: "Comparable transaction analysis", optionC: "Premium-paid analysis", optionD: "DDM", correctOption: "A", explanation: "Comparable company analysis applies peer multiples (adding a takeover premium).", orderIndex: 4 },
  { id: "cfa-corporate-issuers-corporate-restructuring-q06", topicId: "cfa-corporate-issuers-corporate-restructuring", text: "Valuing a target using multiples paid in past similar deals is:", optionA: "Comparable transaction analysis", optionB: "Comparable company analysis", optionC: "Residual income", optionD: "Cost approach", correctOption: "A", explanation: "Comparable transaction analysis uses precedent deal multiples, which embed the premium.", orderIndex: 5 },
  { id: "cfa-corporate-issuers-corporate-restructuring-q07", topicId: "cfa-corporate-issuers-corporate-restructuring", text: "A carve-out involves:", optionA: "Selling a stake in a subsidiary to the public via an IPO", optionB: "Buying a competitor", optionC: "Paying a special dividend", optionD: "Issuing bonds", correctOption: "A", explanation: "In an equity carve-out, the parent sells shares of a subsidiary to outside investors.", orderIndex: 6 },
  { id: "cfa-corporate-issuers-corporate-restructuring-q08", topicId: "cfa-corporate-issuers-corporate-restructuring", text: "Cost cutting and reorganisation in response to distress is a form of:", optionA: "Restructuring", optionB: "Expansion", optionC: "Acquisition", optionD: "Dividend policy", correctOption: "A", explanation: "Operational/financial restructuring reshapes a firm, often under distress.", orderIndex: 7 },
  { id: "cfa-corporate-issuers-corporate-restructuring-q09", topicId: "cfa-corporate-issuers-corporate-restructuring", text: "Premium-paid analysis measures the premium over the target's:", optionA: "Pre-announcement share price", optionB: "Book value", optionC: "Coupon rate", optionD: "Dividend", correctOption: "A", explanation: "Premium-paid analysis looks at the acquisition premium relative to the unaffected pre-deal price.", orderIndex: 8 },
  { id: "cfa-corporate-issuers-corporate-restructuring-q10", topicId: "cfa-corporate-issuers-corporate-restructuring", text: "A joint venture is best classified as a corporate:", optionA: "Investment action", optionB: "Divestment action", optionC: "Liquidation", optionD: "Buyback", correctOption: "A", explanation: "A joint venture is an expansion/investment where firms combine resources in a new entity.", orderIndex: 9 },
  { id: "cfa-corporate-issuers-corporate-restructuring-q11", topicId: "cfa-corporate-issuers-corporate-restructuring", text: "Firms may restructure when management believes the company is:", optionA: "Undervalued or in need of refocusing", optionB: "Perfectly valued", optionC: "Unable to change", optionD: "Barred from restructuring", correctOption: "A", explanation: "Perceived undervaluation, distress, or a desire to refocus commonly drive restructuring.", orderIndex: 10 },
  { id: "cfa-corporate-issuers-corporate-restructuring-q12", topicId: "cfa-corporate-issuers-corporate-restructuring", text: "The three broad categories of corporate restructuring are investment, divestment and:", optionA: "Restructuring (reorganisation)", optionB: "Dividends", optionC: "Auditing", optionD: "Hedging", correctOption: "A", explanation: "Actions are grouped as investment (expansion), divestment (contraction), and restructuring/reorganisation.", orderIndex: 11 },

  // ── Company Analysis: Forecasting ──
  { id: "cfa-equity-company-forecasting-q01", topicId: "cfa-equity-company-forecasting", text: "The main objective of company analysis forecasting is to:", optionA: "Project future revenues, costs and cash flows", optionB: "Audit past accounts", optionC: "Set the coupon rate", optionD: "File taxes", correctOption: "A", explanation: "Forecasting builds projections of a firm's financials to support valuation.", orderIndex: 0 },
  { id: "cfa-equity-company-forecasting-q02", topicId: "cfa-equity-company-forecasting", text: "A top-down revenue forecast starts from:", optionA: "The economy and industry, then the company", optionB: "The company's products only", optionC: "The share price", optionD: "The audit report", correctOption: "A", explanation: "Top-down forecasting moves from macro/industry conditions down to the company.", orderIndex: 1 },
  { id: "cfa-equity-company-forecasting-q03", topicId: "cfa-equity-company-forecasting", text: "A sustainable competitive advantage is often called a:", optionA: "Moat", optionB: "Coupon", optionC: "Hedge", optionD: "Spread", correctOption: "A", explanation: "A 'moat' (brands, patents, network effects, cost advantage) protects durable high returns.", orderIndex: 2 },
  { id: "cfa-equity-company-forecasting-q04", topicId: "cfa-equity-company-forecasting", text: "Modelling operating leverage requires separating:", optionA: "Fixed and variable costs", optionB: "Debt and equity", optionC: "Spot and forward rates", optionD: "Dividends and buybacks", correctOption: "A", explanation: "Operating leverage depends on the mix of fixed versus variable costs.", orderIndex: 3 },
  { id: "cfa-equity-company-forecasting-q05", topicId: "cfa-equity-company-forecasting", text: "Using base, bull and bear cases is an example of:", optionA: "Scenario analysis", optionB: "Reconciliation", optionC: "Consolidation", optionD: "Amortisation", correctOption: "A", explanation: "Scenario analysis captures a range of coherent outcomes under uncertainty.", orderIndex: 4 },
  { id: "cfa-equity-company-forecasting-q06", topicId: "cfa-equity-company-forecasting", text: "Key drivers of revenue growth include volume, price and:", optionA: "Market share", optionB: "The tax rate", optionC: "Depreciation", optionD: "The coupon", correctOption: "A", explanation: "Revenue is driven by volume, price and the company's share of its market.", orderIndex: 5 },
  { id: "cfa-equity-company-forecasting-q07", topicId: "cfa-equity-company-forecasting", text: "Porter's five forces help a forecaster assess:", optionA: "Industry attractiveness and competitive pressure", optionB: "The audit opinion", optionC: "The bond rating", optionD: "The dividend", correctOption: "A", explanation: "The five forces gauge competitive intensity, which shapes margins and growth.", orderIndex: 6 },
  { id: "cfa-equity-company-forecasting-q08", topicId: "cfa-equity-company-forecasting", text: "Extrapolating recent strong growth indefinitely reflects the bias of:", optionA: "Overconfidence/recency", optionB: "Diversification", optionC: "Hedging", optionD: "Arbitrage", correctOption: "A", explanation: "Over-extrapolating recent trends reflects overconfidence and recency bias.", orderIndex: 7 },
  { id: "cfa-equity-company-forecasting-q09", topicId: "cfa-equity-company-forecasting", text: "A hybrid forecasting approach:", optionA: "Combines top-down and bottom-up methods", optionB: "Ignores the industry", optionC: "Uses only history", optionD: "Avoids assumptions", correctOption: "A", explanation: "A hybrid approach blends macro/industry (top-down) with company-level (bottom-up) inputs.", orderIndex: 8 },
  { id: "cfa-equity-company-forecasting-q10", topicId: "cfa-equity-company-forecasting", text: "Company forecasts feed directly into:", optionA: "Valuation models such as DCF and multiples", optionB: "The audit", optionC: "The tax filing only", optionD: "The coupon schedule", correctOption: "A", explanation: "Forecast financials are inputs to DCF and multiple-based valuations.", orderIndex: 9 },
  { id: "cfa-equity-company-forecasting-q11", topicId: "cfa-equity-company-forecasting", text: "Economies of scale, if present, tend to:", optionA: "Lower unit costs as output rises", optionB: "Raise unit costs with output", optionC: "Have no effect on costs", optionD: "Eliminate revenue", correctOption: "A", explanation: "Economies of scale reduce average cost per unit as production increases.", orderIndex: 10 },
  { id: "cfa-equity-company-forecasting-q12", topicId: "cfa-equity-company-forecasting", text: "A wider economic moat generally supports:", optionA: "More sustainable margins and returns", optionB: "Rapid margin erosion", optionC: "Immediate bankruptcy", optionD: "Lower pricing power", correctOption: "A", explanation: "A durable competitive advantage helps sustain high margins and returns on capital.", orderIndex: 11 },

  // ── Fixed-Income Cash Flows & Types ──
  { id: "cfa-fixed-income-cash-flows-types-q01", topicId: "cfa-fixed-income-cash-flows-types", text: "A bullet bond repays its principal:", optionA: "Entirely at maturity", optionB: "In equal instalments", optionC: "Never", optionD: "Before the coupons", correctOption: "A", explanation: "A bullet structure pays coupons over the life and the full principal at maturity.", orderIndex: 0 },
  { id: "cfa-fixed-income-cash-flows-types-q02", topicId: "cfa-fixed-income-cash-flows-types", text: "A fully amortising bond:", optionA: "Repays principal gradually so nothing remains at maturity", optionB: "Repays all principal at maturity", optionC: "Never repays principal", optionD: "Pays only at issuance", correctOption: "A", explanation: "Level payments in a fully amortising bond retire the principal to zero by maturity.", orderIndex: 1 },
  { id: "cfa-fixed-income-cash-flows-types-q03", topicId: "cfa-fixed-income-cash-flows-types", text: "A partially amortising bond leaves a large final payment called a:", optionA: "Balloon payment", optionB: "Coupon", optionC: "Premium", optionD: "Discount", correctOption: "A", explanation: "Partial amortisation reduces principal partly, leaving a balloon payment at maturity.", orderIndex: 2 },
  { id: "cfa-fixed-income-cash-flows-types-q04", topicId: "cfa-fixed-income-cash-flows-types", text: "A floating-rate note pays a coupon of:", optionA: "A reference rate plus a spread", optionB: "A fixed rate always", optionC: "Zero", optionD: "The share price", correctOption: "A", explanation: "FRNs reset periodically to a benchmark reference rate plus a fixed spread.", orderIndex: 3 },
  { id: "cfa-fixed-income-cash-flows-types-q05", topicId: "cfa-fixed-income-cash-flows-types", text: "A step-up coupon bond has a coupon that:", optionA: "Rises on a predetermined schedule", optionB: "Falls to zero", optionC: "Stays fixed forever", optionD: "Equals inflation", correctOption: "A", explanation: "Step-up bonds increase the coupon at scheduled dates.", orderIndex: 4 },
  { id: "cfa-fixed-income-cash-flows-types-q06", topicId: "cfa-fixed-income-cash-flows-types", text: "A payment-in-kind (PIK) bond pays interest by:", optionA: "Issuing additional bonds instead of cash", optionB: "Paying cash coupons", optionC: "Repaying principal early", optionD: "Converting to equity", correctOption: "A", explanation: "PIK bonds pay coupons in the form of more bonds/notes rather than cash.", orderIndex: 5 },
  { id: "cfa-fixed-income-cash-flows-types-q07", topicId: "cfa-fixed-income-cash-flows-types", text: "A sinking fund provision requires the issuer to:", optionA: "Retire part of the principal on a schedule", optionB: "Pay a higher coupon", optionC: "Issue more debt", optionD: "Convert the bond", correctOption: "A", explanation: "A sinking fund repays portions of the principal over the bond's life, reducing credit risk.", orderIndex: 6 },
  { id: "cfa-fixed-income-cash-flows-types-q08", topicId: "cfa-fixed-income-cash-flows-types", text: "A callable bond gives the ___ the right to redeem it early.", optionA: "Issuer", optionB: "Bondholder", optionC: "Trustee", optionD: "Exchange", correctOption: "A", explanation: "A call option benefits the issuer, who may redeem the bond before maturity.", orderIndex: 7 },
  { id: "cfa-fixed-income-cash-flows-types-q09", topicId: "cfa-fixed-income-cash-flows-types", text: "A putable bond gives the ___ the right to sell it back early.", optionA: "Bondholder", optionB: "Issuer", optionC: "Government", optionD: "Rating agency", correctOption: "A", explanation: "A put option benefits the investor, who may sell the bond back to the issuer.", orderIndex: 8 },
  { id: "cfa-fixed-income-cash-flows-types-q10", topicId: "cfa-fixed-income-cash-flows-types", text: "A convertible bond can be exchanged by the holder into:", optionA: "Common shares of the issuer", optionB: "Another bond only", optionC: "Cash equal to par always", optionD: "A commodity", correctOption: "A", explanation: "Convertibles let the holder convert the bond into a set number of common shares.", orderIndex: 9 },
  { id: "cfa-fixed-income-cash-flows-types-q11", topicId: "cfa-fixed-income-cash-flows-types", text: "An inflation-linked bond ties its cash flows to:", optionA: "A price index", optionB: "The stock market", optionC: "A commodity future", optionD: "The exchange rate only", correctOption: "A", explanation: "Index-linked (inflation-linked) bonds adjust coupon and/or principal to an inflation index.", orderIndex: 10 },
  { id: "cfa-fixed-income-cash-flows-types-q12", topicId: "cfa-fixed-income-cash-flows-types", text: "Embedded options such as calls and puts are examples of:", optionA: "Contingency provisions", optionB: "Coupon structures only", optionC: "Amortisation schedules", optionD: "Credit ratings", correctOption: "A", explanation: "Callable, putable and convertible features are contingency provisions (embedded options).", orderIndex: 11 },

  // ── Government & Corporate Fixed-Income Markets ──
  { id: "cfa-fixed-income-government-corporate-markets-q01", topicId: "cfa-fixed-income-government-corporate-markets", text: "Treasury bills are:", optionA: "Short-term government securities issued at a discount", optionB: "Long-term coupon bonds", optionC: "Corporate equities", optionD: "Perpetual bonds", correctOption: "A", explanation: "T-bills mature in one year or less, pay no coupon, and are sold at a discount to par.", orderIndex: 0 },
  { id: "cfa-fixed-income-government-corporate-markets-q02", topicId: "cfa-fixed-income-government-corporate-markets", text: "The most recently issued and most liquid government bond of a maturity is called:", optionA: "On-the-run", optionB: "Off-the-run", optionC: "Callable", optionD: "Subordinated", correctOption: "A", explanation: "The on-the-run issue is the newest, most actively traded, most liquid security.", orderIndex: 1 },
  { id: "cfa-fixed-income-government-corporate-markets-q03", topicId: "cfa-fixed-income-government-corporate-markets", text: "A loan provided by a group of lenders is a:", optionA: "Syndicated loan", optionB: "Commercial paper", optionC: "Treasury note", optionD: "Convertible bond", correctOption: "A", explanation: "A syndicated loan spreads a large loan across a group (syndicate) of lenders.", orderIndex: 2 },
  { id: "cfa-fixed-income-government-corporate-markets-q04", topicId: "cfa-fixed-income-government-corporate-markets", text: "Commercial paper is:", optionA: "Short-term unsecured corporate debt", optionB: "A long-term secured bond", optionC: "A government bond", optionD: "An equity share", correctOption: "A", explanation: "Commercial paper is short-term, typically unsecured funding used by corporations.", orderIndex: 3 },
  { id: "cfa-fixed-income-government-corporate-markets-q05", topicId: "cfa-fixed-income-government-corporate-markets", text: "Banks (financial issuers) rely heavily for funding on:", optionA: "Deposits, interbank funding and the repo market", optionB: "Only equity", optionC: "Only government grants", optionD: "Dividends", correctOption: "A", explanation: "Financial institutions fund themselves largely through deposits, interbank markets and repos.", orderIndex: 4 },
  { id: "cfa-fixed-income-government-corporate-markets-q06", topicId: "cfa-fixed-income-government-corporate-markets", text: "A corporate bond's yield spread over a government benchmark compensates for:", optionA: "Credit and liquidity risk", optionB: "Reinvestment of coupons", optionC: "Currency risk only", optionD: "Inflation only", correctOption: "A", explanation: "The spread rewards investors for the corporate bond's default (credit) and liquidity risk.", orderIndex: 5 },
  { id: "cfa-fixed-income-government-corporate-markets-q07", topicId: "cfa-fixed-income-government-corporate-markets", text: "In the capital structure, which ranks highest in a default?", optionA: "Secured (senior) debt", optionB: "Subordinated debt", optionC: "Common equity", optionD: "Preferred equity", correctOption: "A", explanation: "Secured/senior debt is repaid before subordinated debt and equity in liquidation.", orderIndex: 6 },
  { id: "cfa-fixed-income-government-corporate-markets-q08", topicId: "cfa-fixed-income-government-corporate-markets", text: "Medium-term notes (MTNs) are:", optionA: "Debt offered continuously to investors through a program", optionB: "Short-term T-bills", optionC: "Equity shares", optionD: "Commodities", correctOption: "A", explanation: "MTNs are issued on an ongoing basis under a program, with flexible maturities.", orderIndex: 7 },
  { id: "cfa-fixed-income-government-corporate-markets-q09", topicId: "cfa-fixed-income-government-corporate-markets", text: "Older, less liquid government issues are described as:", optionA: "Off-the-run", optionB: "On-the-run", optionC: "Callable", optionD: "Convertible", correctOption: "A", explanation: "Off-the-run securities are previously issued bonds that trade less actively than on-the-run issues.", orderIndex: 8 },
  { id: "cfa-fixed-income-government-corporate-markets-q10", topicId: "cfa-fixed-income-government-corporate-markets", text: "A repo (repurchase agreement) is used mainly for:", optionA: "Short-term secured financing", optionB: "Long-term equity investment", optionC: "Paying dividends", optionD: "Issuing shares", correctOption: "A", explanation: "Repos provide short-term collateralised funding, widely used by financial institutions.", orderIndex: 9 },
  { id: "cfa-fixed-income-government-corporate-markets-q11", topicId: "cfa-fixed-income-government-corporate-markets", text: "Bonds issued by a national government in its own currency are:", optionA: "Sovereign bonds", optionB: "Corporate bonds", optionC: "Municipal bonds", optionD: "Agency MBS", correctOption: "A", explanation: "Sovereign bonds are issued by national governments and are typically the benchmark for a currency.", orderIndex: 10 },
  { id: "cfa-fixed-income-government-corporate-markets-q12", topicId: "cfa-fixed-income-government-corporate-markets", text: "Treasury bonds, versus Treasury notes, generally have:", optionA: "Longer maturities (over 10 years)", optionB: "Shorter maturities", optionC: "No coupon", optionD: "Equity features", correctOption: "A", explanation: "Treasury bonds have the longest maturities (typically over 10 years); notes are 2–10 years.", orderIndex: 11 },

  // ── Curve-Based & Empirical Duration ──
  { id: "cfa-fixed-income-curve-empirical-duration-q01", topicId: "cfa-fixed-income-curve-empirical-duration", text: "Effective duration measures sensitivity to a:", optionA: "Parallel shift in the benchmark yield curve", optionB: "Change in the coupon", optionC: "Change in the credit rating", optionD: "Change in maturity", correctOption: "A", explanation: "Effective (curve-based) duration estimates price change for a parallel curve shift.", orderIndex: 0 },
  { id: "cfa-fixed-income-curve-empirical-duration-q02", topicId: "cfa-fixed-income-curve-empirical-duration", text: "Effective duration is required for bonds that:", optionA: "Have embedded options", optionB: "Are option-free", optionC: "Never pay coupons", optionD: "Are equities", correctOption: "A", explanation: "Bonds with embedded options have cash flows that change with rates, requiring effective duration.", orderIndex: 1 },
  { id: "cfa-fixed-income-curve-empirical-duration-q03", topicId: "cfa-fixed-income-curve-empirical-duration", text: "Key rate durations capture the effect of:", optionA: "Non-parallel (curve-reshaping) yield changes", optionB: "Only parallel shifts", optionC: "Coupon changes", optionD: "Currency moves", correctOption: "A", explanation: "Key rate durations measure sensitivity to yield changes at specific maturities, capturing curve reshaping.", orderIndex: 2 },
  { id: "cfa-fixed-income-curve-empirical-duration-q04", topicId: "cfa-fixed-income-curve-empirical-duration", text: "Empirical duration is estimated using:", optionA: "Historical price and yield data (regression)", optionB: "A pricing formula only", optionC: "The coupon rate", optionD: "The credit rating", correctOption: "A", explanation: "Empirical duration is derived statistically from observed price/yield movements.", orderIndex: 3 },
  { id: "cfa-fixed-income-curve-empirical-duration-q05", topicId: "cfa-fixed-income-curve-empirical-duration", text: "Analytical (yield) duration is computed from:", optionA: "A bond pricing formula", optionB: "Historical regression", optionC: "Market sentiment", optionD: "The issuer's guidance", correctOption: "A", explanation: "Analytical duration comes from the mathematical relationship in a pricing model.", orderIndex: 4 },
  { id: "cfa-fixed-income-curve-empirical-duration-q06", topicId: "cfa-fixed-income-curve-empirical-duration", text: "Empirical duration is especially useful for:", optionA: "Credit-risky bonds where yields and spreads move together", optionB: "Risk-free zero-coupon bonds only", optionC: "Equities", optionD: "Commodities", correctOption: "A", explanation: "It captures the joint movement of benchmark yields and credit spreads, important for credit-risky bonds.", orderIndex: 5 },
  { id: "cfa-fixed-income-curve-empirical-duration-q07", topicId: "cfa-fixed-income-curve-empirical-duration", text: "For a high-yield bond in a risk-off episode, empirical duration is often:", optionA: "Lower than its analytical duration", optionB: "Much higher than analytical", optionC: "Exactly equal", optionD: "Negative and large", correctOption: "A", explanation: "When government yields fall but spreads widen, the high-yield bond moves less, lowering empirical duration.", orderIndex: 6 },
  { id: "cfa-fixed-income-curve-empirical-duration-q08", topicId: "cfa-fixed-income-curve-empirical-duration", text: "Effective duration is calculated using the bond's prices from:", optionA: "Small upward and downward curve shifts", optionB: "A single price", optionC: "The coupon only", optionD: "The maturity date", correctOption: "A", explanation: "Effective duration uses prices under small up and down shifts to estimate curve sensitivity.", orderIndex: 7 },
  { id: "cfa-fixed-income-curve-empirical-duration-q09", topicId: "cfa-fixed-income-curve-empirical-duration", text: "A single duration number can miss risk when the yield curve:", optionA: "Reshapes (steepens or flattens)", optionB: "Shifts perfectly in parallel", optionC: "Does not move", optionD: "Is flat", correctOption: "A", explanation: "Non-parallel moves affect maturities unevenly, which key rate durations capture but one duration cannot.", orderIndex: 8 },
  { id: "cfa-fixed-income-curve-empirical-duration-q10", topicId: "cfa-fixed-income-curve-empirical-duration", text: "Empirical duration reflects the observed relationship between a bond's price and:", optionA: "Benchmark yield changes", optionB: "Its coupon schedule", optionC: "Its issue size", optionD: "The exchange rate", correctOption: "A", explanation: "Empirical duration regresses the bond's price changes on benchmark yield changes.", orderIndex: 9 },
  { id: "cfa-fixed-income-curve-empirical-duration-q11", topicId: "cfa-fixed-income-curve-empirical-duration", text: "Curve-based effective duration is most appropriate for:", optionA: "Mortgage-backed and callable securities", optionB: "Simple option-free bonds only", optionC: "Common stocks", optionD: "Commodities", correctOption: "A", explanation: "Securities with prepayment or call features need effective (curve-based) duration.", orderIndex: 10 },
  { id: "cfa-fixed-income-curve-empirical-duration-q12", topicId: "cfa-fixed-income-curve-empirical-duration", text: "The advantage of empirical over analytical duration is that it:", optionA: "Reflects real-world co-movement of yields and spreads", optionB: "Requires no data", optionC: "Is always exact", optionD: "Ignores prices", correctOption: "A", explanation: "Empirical duration captures how yields and spreads actually move together in the market.", orderIndex: 11 },

  // ── Analysis of Active Portfolio Management ──
  { id: "cfa-portfolio-management-active-management-q01", topicId: "cfa-portfolio-management-active-management", text: "Active return is defined as:", optionA: "Portfolio return minus benchmark return", optionB: "Portfolio return minus risk-free rate", optionC: "Benchmark return only", optionD: "Total return", correctOption: "A", explanation: "Active return (value added) is the portfolio's return in excess of its benchmark.", orderIndex: 0 },
  { id: "cfa-portfolio-management-active-management-q02", topicId: "cfa-portfolio-management-active-management", text: "Active risk is also known as:", optionA: "Tracking error", optionB: "Total risk", optionC: "Systematic risk", optionD: "The risk-free rate", correctOption: "A", explanation: "Active risk is the standard deviation of active returns — the tracking error.", orderIndex: 1 },
  { id: "cfa-portfolio-management-active-management-q03", topicId: "cfa-portfolio-management-active-management", text: "The information ratio equals active return divided by:", optionA: "Active risk (tracking error)", optionB: "Total risk", optionC: "Beta", optionD: "The market return", correctOption: "A", explanation: "IR = active return ÷ tracking error, measuring risk-adjusted active performance.", orderIndex: 2 },
  { id: "cfa-portfolio-management-active-management-q04", topicId: "cfa-portfolio-management-active-management", text: "In the fundamental law of active management, IR ≈ IC × √(breadth), IC represents:", optionA: "The information coefficient (forecasting skill)", optionB: "The interest cost", optionC: "The index change", optionD: "The inflation rate", correctOption: "A", explanation: "IC (information coefficient) measures the quality/skill of the manager's forecasts.", orderIndex: 3 },
  { id: "cfa-portfolio-management-active-management-q05", topicId: "cfa-portfolio-management-active-management", text: "In the fundamental law, 'breadth' refers to:", optionA: "The number of independent active decisions", optionB: "The portfolio's total value", optionC: "The benchmark's size", optionD: "The management fee", correctOption: "A", explanation: "Breadth is the number of independent active investment decisions made per period.", orderIndex: 4 },
  { id: "cfa-portfolio-management-active-management-q06", topicId: "cfa-portfolio-management-active-management", text: "According to the fundamental law, performance improves with:", optionA: "More skill and more independent bets", optionB: "Fewer decisions", optionC: "Higher fees", optionD: "Less information", correctOption: "A", explanation: "A higher IR comes from greater skill (IC) and greater breadth of independent decisions.", orderIndex: 5 },
  { id: "cfa-portfolio-management-active-management-q07", topicId: "cfa-portfolio-management-active-management", text: "A higher information ratio indicates:", optionA: "Better risk-adjusted active performance", optionB: "Higher fees", optionC: "More leverage", optionD: "Lower skill", correctOption: "A", explanation: "A higher IR means more value added per unit of active risk taken.", orderIndex: 6 },
  { id: "cfa-portfolio-management-active-management-q08", topicId: "cfa-portfolio-management-active-management", text: "Active management must overcome its:", optionA: "Higher fees and trading costs versus passive investing", optionB: "Guaranteed losses", optionC: "Zero tracking error", optionD: "Lack of a benchmark", correctOption: "A", explanation: "If expected value added doesn't exceed the higher costs, low-cost passive investing is preferable.", orderIndex: 7 },
  { id: "cfa-portfolio-management-active-management-q09", topicId: "cfa-portfolio-management-active-management", text: "A portfolio that closely tracks its benchmark has a:", optionA: "Low tracking error", optionB: "High tracking error", optionC: "High active return always", optionD: "Zero beta", correctOption: "A", explanation: "Small deviations from the benchmark produce a low tracking error (active risk).", orderIndex: 8 },
  { id: "cfa-portfolio-management-active-management-q10", topicId: "cfa-portfolio-management-active-management", text: "The information ratio is useful because it is:", optionA: "Largely unaffected by the scale of active positions", optionB: "Dependent only on fees", optionC: "Always equal to the Sharpe ratio", optionD: "Based on total risk", correctOption: "A", explanation: "Scaling active positions changes active return and risk proportionally, leaving the IR roughly unchanged.", orderIndex: 9 },
  { id: "cfa-portfolio-management-active-management-q11", topicId: "cfa-portfolio-management-active-management", text: "Value added by a manager is measured relative to the:", optionA: "Benchmark", optionB: "Risk-free rate", optionC: "Inflation rate", optionD: "Coupon", correctOption: "A", explanation: "Active value added is judged against the portfolio's benchmark, not an absolute standard.", orderIndex: 10 },
  { id: "cfa-portfolio-management-active-management-q12", topicId: "cfa-portfolio-management-active-management", text: "If a manager's forecasting skill (IC) is zero, the expected information ratio is:", optionA: "Zero", optionB: "Very high", optionC: "Negative and large", optionD: "Equal to breadth", correctOption: "A", explanation: "With no skill (IC = 0), IR ≈ IC × √breadth = 0 — active management adds no expected value.", orderIndex: 11 }
];
