// CFA Level III — additional readings (12 questions each).
import type { AuthoredMaterial } from "./builder";
import type { Question, Subject, Topic } from "@jyotir/core";

export const expSubjects: Subject[] = [
  { id: "cfa3-equity-pm", examId: "cfa-3", name: "Equity Portfolio Management", slug: "equity-pm", orderIndex: 5 },
  { id: "cfa3-risk-management", examId: "cfa-3", name: "Risk Management", slug: "risk-management", orderIndex: 6 },
  { id: "cfa3-private-wealth", examId: "cfa-3", name: "Private Wealth Management", slug: "private-wealth", orderIndex: 7 },
  { id: "cfa3-institutional", examId: "cfa-3", name: "Institutional Investors", slug: "institutional", orderIndex: 8 },
  { id: "cfa3-ethics", examId: "cfa-3", name: "Ethics & Professional Standards", slug: "ethics", orderIndex: 9 },
  { id: "cfa3-alternative-investments", examId: "cfa-3", name: "Alternative Investments", slug: "alternative-investments", orderIndex: 10 },
  { id: "cfa3-manager-selection", examId: "cfa-3", name: "Manager Selection", slug: "manager-selection", orderIndex: 11 }
];

export const expTopics: Topic[] = [
  { id: "cfa3-equity-pm-passive-active-factor", subjectId: "cfa3-equity-pm", name: "Passive, Active & Factor Investing", slug: "passive-active-factor", orderIndex: 0 },
  { id: "cfa3-risk-management-derivatives", subjectId: "cfa3-risk-management", name: "Risk Management with Derivatives", slug: "derivatives", orderIndex: 0 },
  { id: "cfa3-private-wealth-tax-estate", subjectId: "cfa3-private-wealth", name: "Private Wealth: Tax & Estate Planning", slug: "tax-estate", orderIndex: 0 },
  { id: "cfa3-institutional-pensions-endowments", subjectId: "cfa3-institutional", name: "Pensions & Endowments", slug: "pensions-endowments", orderIndex: 0 },
  { id: "cfa3-asset-allocation-rebalancing-execution", subjectId: "cfa3-asset-allocation", name: "Rebalancing & Trade Execution", slug: "rebalancing-execution", orderIndex: 1 },
  { id: "cfa3-risk-management-currency", subjectId: "cfa3-risk-management", name: "Currency Management", slug: "currency", orderIndex: 1 },
  { id: "cfa3-ethics-asset-manager-code", subjectId: "cfa3-ethics", name: "Asset Manager Code & GIPS", slug: "asset-manager-code", orderIndex: 0 },
  { id: "cfa3-alternative-investments-portfolio-role", subjectId: "cfa3-alternative-investments", name: "Alternatives in Portfolio Management", slug: "portfolio-role", orderIndex: 0 },
  { id: "cfa3-manager-selection-due-diligence", subjectId: "cfa3-manager-selection", name: "Manager Selection & Due Diligence", slug: "due-diligence", orderIndex: 0 }
];

export const expMaterials: AuthoredMaterial[] = [
  {
    id: "cfa3-equity-pm-passive-active-factor-m01",
    topicId: "cfa3-equity-pm-passive-active-factor",
    title: "Passive, Active & Factor Investing",
    content: `## The spectrum
- **Passive** — track an index; low cost, low tracking error. Methods: full replication, **stratified sampling**, optimization.
- **Active** — seek alpha; higher fees and tracking error. Judged by the **information ratio** (active return / active risk).
- **Factor / smart beta** — rules-based tilts to rewarded factors (value, size, momentum, quality, low-volatility) — between passive and active.

## Building exposure
- **Index funds/ETFs** and **derivatives** (equity futures, total-return swaps) give cheap, liquid beta; a **completion overlay** fills gaps.
- **Long-only vs long/short**: market-neutral isolates alpha by removing beta.

## Costs & implementation
- Watch **management fees, transaction costs, market impact, and taxes**; rebalancing and turnover erode returns.
- **Tracking error** measures deviation from benchmark; passive minimizes it, active budgets it.
- Fundamental law: **IR ≈ IC × √breadth** — more independent, skillful bets raise the achievable information ratio.`,
    estimatedReadTime: 2,
    orderIndex: 0
  },
  {
    id: "cfa3-risk-management-derivatives-m01",
    topicId: "cfa3-risk-management-derivatives",
    title: "Risk Management with Derivatives",
    content: `Derivatives let managers **adjust exposures** cheaply without trading the underlying.

## Common overlays
- **Equity futures**: change beta. Contracts = [(β_target − β_port)/β_futures] × (Portfolio/Futures price). Sell to lower beta, buy to raise it.
- **Interest-rate futures/swaps**: adjust portfolio **duration**. Number of contracts ≈ [(D_target − D_port)/D_futures] × (Portfolio/Futures BPV).
- **Currency forwards**: hedge foreign-asset FX exposure (hedge ratio choice).
- **Options**: asymmetric protection — **protective put** (floor), **covered call** (income), **collar** (cap + floor cheaply).

## Discipline
- Define the **risk to hedge**, choose the instrument, size it, and monitor **basis risk** (the hedge and exposure not moving identically).
- Futures need **margin** and daily settlement; swaps/forwards are OTC with **counterparty risk** (mitigated by clearing/collateral).
- Hedging reduces both downside and upside; **dynamic** delta hedging requires rebalancing due to gamma.`,
    estimatedReadTime: 2,
    orderIndex: 0
  },
  {
    id: "cfa3-private-wealth-tax-estate-m01",
    topicId: "cfa3-private-wealth-tax-estate",
    title: "Private Wealth: Tax & Estate Planning",
    content: `## Taxes and returns
- **Tax drag** compounds: after-tax return r·(1 − t) over many years sharply reduces terminal wealth.
- **Asset location**: hold tax-inefficient assets (bonds, high-turnover) in **tax-deferred/exempt** accounts; tax-efficient (low-turnover equity) in taxable accounts.
- **Tax-loss harvesting** and deferring gains raise after-tax returns; **step-up in basis** at death can eliminate embedded gains.

## Account types
- **Tax-deferred** (contributions pre-tax, taxed on withdrawal) vs **tax-exempt** (after-tax in, tax-free out). Choice depends on current vs expected future tax rates.

## Estate planning
- **Gifting during life** (uses the lower of gift/estate tax, removes future growth from the estate) vs **bequests** at death.
- **Trusts** (revocable vs irrevocable), **life insurance**, and **charitable** vehicles manage transfer taxes and control.
- Core IPS inputs for individuals: **time horizon, liquidity needs, taxes, legal/regulatory, and unique circumstances** (the constraints), plus return/risk objectives. Human capital and **mortality/longevity risk** shape asset allocation and insurance needs.`,
    estimatedReadTime: 2,
    orderIndex: 0
  },
  {
    id: "cfa3-institutional-pensions-endowments-m01",
    topicId: "cfa3-institutional-pensions-endowments",
    title: "Pensions & Endowments",
    content: `## Defined-benefit pensions
- **Risk tolerance** rises with a younger workforce, a well-funded status, a lower plan/sponsor correlation, and a smaller plan relative to the sponsor.
- Liabilities are **bond-like** → **LDI** (match duration of assets to liabilities). Time horizon often long but tied to the active/retired mix.
- Liquidity needs depend on the **retired-lives proportion** and contributions.

## Endowments & foundations
- Goal: fund spending **in perpetuity** while preserving **real** value → high equity/alternatives allocation, long horizon, high risk tolerance.
- **Spending rules**: simple (% of beginning assets), rolling 3-year average (smooths), or **geometric/Yale** (weights prior spending and market value) to stabilize distributions.
- Return objective ≈ **spending rate + inflation + fees**; **US foundations** must typically distribute ~5% annually.

## Other institutions
- **Banks/insurers**: heavily regulated, liability-driven, lower risk tolerance, strong liquidity and ALM focus.`,
    estimatedReadTime: 2,
    orderIndex: 0
  },
  {
    id: "cfa3-asset-allocation-rebalancing-execution-m01",
    topicId: "cfa3-asset-allocation-rebalancing-execution",
    title: "Rebalancing & Trade Execution",
    content: `## Rebalancing
- **Calendar** rebalancing (e.g. quarterly) is simple but ignores market moves; **percentage-range (corridor)** rebalances when a weight breaches a band.
- Optimal corridor **width** is *wider* for higher transaction costs, higher risk tolerance, and lower correlation with the rest of the portfolio; *narrower* for higher volatility.
- Rebalancing is **contrarian** (sells winners, buys losers) and can capture a **diversification return**; it controls risk, it doesn't chase return.

## Execution costs
- **Implementation shortfall** = paper-portfolio return − actual return = explicit costs (commissions, fees, taxes) + implicit costs (**spread, market impact, delay/slippage, opportunity cost** of unfilled orders).
- **VWAP** benchmarks fills against volume-weighted average price.

## Trade strategy
- **Urgency vs cost**: aggressive (liquidity-demanding) trades pay more impact but less timing risk; patient (liquidity-supplying) trades risk adverse price moves.
- Algorithms: VWAP/TWAP, implementation-shortfall, and liquidity-seeking; large orders are **sliced** to limit impact.`,
    estimatedReadTime: 2,
    orderIndex: 1
  },
  {
    id: "cfa3-risk-management-currency-m01",
    topicId: "cfa3-risk-management-currency",
    title: "Currency Management",
    content: `Foreign assets carry **two** return sources: the local asset return and the **currency** return.

## The strategic decision
- **Hedging ratio** ranges from fully unhedged → fully hedged. Drivers toward **more hedging**: short horizon, risk-averse client, high hedging-cost tolerance, low correlation of currency with the asset.
- Bonds: currency risk is large relative to return → often **hedged**. Equities: currency is a smaller share and adds diversification → often **partially** hedged.

## Tools
- **Forwards** (most common — precise, low cost; roll at maturity), **currency futures**, **options** (asymmetric), and **cross-hedges/proxy hedges** when a direct forward is costly.
- **Minimum-variance hedge ratio** = regression beta of asset (domestic-currency) returns on the exchange-rate return.

## Active overlays
- A **currency overlay** manager seeks alpha from FX separately from the asset managers. Tactics use carry, value (PPP), momentum, and volatility trading. **Roll yield** matters: hedging a forward at a premium/discount adds or subtracts return.`,
    estimatedReadTime: 2,
    orderIndex: 1
  },
  {
    id: "cfa3-ethics-asset-manager-code-m01",
    topicId: "cfa3-ethics-asset-manager-code",
    title: "Asset Manager Code & GIPS",
    content: `## Asset Manager Code (AMC)
Voluntary, firm-level conduct code (vs. the individual Code & Standards). Firms **claim compliance** for the whole firm; CFA Institute does not verify it. Six pillars of ethical responsibilities:
1. **Loyalty to clients** (place client interests first; confidentiality)
2. **Investment process & actions** (reasonable basis, fair dealing, no manipulation)
3. **Trading** (best execution; client brokerage for client benefit; priority of client trades)
4. **Risk management, compliance & support** (designated compliance officer, controls, recordkeeping)
5. **Performance & valuation** (fair, accurate, complete; no cherry-picking)
6. **Disclosures** (truthful, timely; conflicts, fees, costs)

## GIPS (Global Investment Performance Standards)
- Voluntary, ethical performance-presentation standards ensuring **fair representation and full disclosure**; compliance is **firm-wide**, not per-composite.
- **Composites** group all fee-paying discretionary portfolios of similar mandate (prevents survivorship/cherry-picking). Must show ≥ history (building to 10 years).
- Returns are **time-weighted** (TWR removes the effect of client cash flows); show benchmark and dispersion. **Verification** by a third party is recommended but optional.`,
    estimatedReadTime: 2,
    orderIndex: 0
  },
  {
    id: "cfa3-alternative-investments-portfolio-role-m01",
    topicId: "cfa3-alternative-investments-portfolio-role",
    title: "Alternatives in Portfolio Management",
    content: `Alternatives (private equity, hedge funds, real assets, private debt, commodities) are added for **diversification, return enhancement, and inflation protection**.

## Portfolio role & allocation
- Low (and unstable) correlations with stocks/bonds — but correlations **rise in crises**.
- Reported returns are **smoothed** (appraisal-based/stale pricing) → **understated volatility and correlation**; "unsmooth" before optimizing or MVO over-allocates to alternatives.
- Liquidity, long lock-ups, the **J-curve**, high fees (2-and-20), and operational/manager risk constrain sizing.

## Approaches
- Allocate by **role** (capital growth, income, diversification, inflation hedge) rather than by traditional asset-class labels.
- Use **liquidity tiers** and commitment pacing for private funds; model **vintage-year** diversification.
- Risk tools must capture **non-normal** returns (fat tails, negative skew) — VaR/volatility alone understate risk; use scenario analysis and downside measures.
- Benchmarks are difficult: peer-group/IRR for private; absolute or risk-factor for hedge funds.`,
    estimatedReadTime: 2,
    orderIndex: 0
  },
  {
    id: "cfa3-manager-selection-due-diligence-m01",
    topicId: "cfa3-manager-selection-due-diligence",
    title: "Manager Selection & Due Diligence",
    content: `Manager selection has three steps: **universe definition → quantitative analysis → qualitative (operational) due diligence.**

## Type I vs Type II error
- **Type I**: hiring/keeping a manager with **no real skill** (false positive).
- **Type II**: rejecting/firing a **genuinely skilled** manager (false negative).
- Tightening selection criteria reduces Type I but raises Type II (and vice-versa).

## Quantitative
- Style/returns-based and holdings-based analysis; capture **alpha vs. factor exposures** (don't pay alpha fees for cheap beta). Assess **information ratio**, consistency, drawdowns, and capacity. Beware short, noisy track records and **backfill/survivorship bias**.

## Qualitative & operational due diligence
- **Investment**: philosophy, process repeatability, team, decision rights.
- **Operational** (a major source of fund failure): independent **administrator/custodian/auditor**, valuation policy, controls, compliance, key-person and business risk, fee terms, and alignment.
- Output: a conviction-weighted recommendation, not just past returns.`,
    estimatedReadTime: 2,
    orderIndex: 0
  }
];

export const expQuestions: Question[] = [
  // Passive/Active/Factor
  { id: "cfa3-equity-pm-passive-active-factor-q01", topicId: "cfa3-equity-pm-passive-active-factor", text: "Active management is most appropriately evaluated using the:", optionA: "Sharpe ratio", optionB: "Information ratio (active return / tracking error)", optionC: "Cap rate", optionD: "Current ratio", correctOption: "B", explanation: "The information ratio measures active return per unit of active risk, the natural gauge of active skill.", orderIndex: 0 },
  { id: "cfa3-equity-pm-passive-active-factor-q02", topicId: "cfa3-equity-pm-passive-active-factor", text: "A passive index fund seeks primarily to minimize:", optionA: "Tracking error relative to its benchmark", optionB: "Beta", optionC: "Dividend income", optionD: "The number of holdings", correctOption: "A", explanation: "Passive strategies aim to replicate the benchmark, so minimizing tracking error (and cost) is the objective.", orderIndex: 1 },
  { id: "cfa3-equity-pm-passive-active-factor-q03", topicId: "cfa3-equity-pm-passive-active-factor", text: "'Smart beta' / factor strategies are best described as:", optionA: "Purely passive cap-weighting", optionB: "Rules-based tilts toward rewarded factors, between passive and active", optionC: "High-frequency trading", optionD: "Risk-free investing", correctOption: "B", explanation: "Factor investing uses transparent rules to tilt toward factors like value or momentum, sitting between pure passive and discretionary active.", orderIndex: 2 },
  { id: "cfa3-equity-pm-passive-active-factor-q04", topicId: "cfa3-equity-pm-passive-active-factor", text: "Stratified sampling is a method of:", optionA: "Active stock picking", optionB: "Passively replicating an index without holding every constituent", optionC: "Hedging currency", optionD: "Estimating beta", correctOption: "B", explanation: "Stratified sampling matches index characteristics (sectors, size) with a subset of securities, approximating the index at lower cost.", orderIndex: 3 },
  { id: "cfa3-equity-pm-passive-active-factor-q05", topicId: "cfa3-equity-pm-passive-active-factor", text: "A market-neutral long/short strategy aims to:", optionA: "Maximize beta exposure", optionB: "Isolate alpha by removing market (beta) exposure", optionC: "Track the index exactly", optionD: "Eliminate all risk", correctOption: "B", explanation: "Balancing long and short positions removes net market exposure, isolating the manager's security-selection alpha.", orderIndex: 4 },
  { id: "cfa3-equity-pm-passive-active-factor-q06", topicId: "cfa3-equity-pm-passive-active-factor", text: "Which is a commonly cited rewarded equity factor?", optionA: "Ticker length", optionB: "Value (high book-to-market)", optionC: "Share price level", optionD: "Trading hours", correctOption: "B", explanation: "Value, size, momentum, quality, and low volatility are widely studied rewarded factors; value is a classic example.", orderIndex: 5 },
  { id: "cfa3-equity-pm-passive-active-factor-q07", topicId: "cfa3-equity-pm-passive-active-factor", text: "Equity futures or total-return swaps are often used to gain market exposure because they are:", optionA: "Free of any risk", optionB: "Cheap and liquid relative to buying all underlying stocks", optionC: "Always tax-exempt", optionD: "Guaranteed to outperform", correctOption: "B", explanation: "Derivatives provide efficient, low-cost, liquid beta exposure and are useful for overlays and completion strategies.", orderIndex: 6 },
  { id: "cfa3-equity-pm-passive-active-factor-q08", topicId: "cfa3-equity-pm-passive-active-factor", text: "According to the fundamental law of active management, the information ratio rises with:", optionA: "Higher fees", optionB: "Greater skill (IC) and breadth of independent decisions", optionC: "More tracking error alone", optionD: "Higher turnover alone", correctOption: "B", explanation: "IR ≈ IC × √breadth: combining skill with many independent bets raises the achievable information ratio.", orderIndex: 7 },
  { id: "cfa3-equity-pm-passive-active-factor-q09", topicId: "cfa3-equity-pm-passive-active-factor", text: "Higher portfolio turnover most directly increases:", optionA: "Transaction costs and tax drag", optionB: "Dividend yield", optionC: "Book value", optionD: "The risk-free rate", correctOption: "A", explanation: "Frequent trading raises explicit and implicit transaction costs and can trigger taxable gains, reducing net returns.", orderIndex: 8 },
  { id: "cfa3-equity-pm-passive-active-factor-q10", topicId: "cfa3-equity-pm-passive-active-factor", text: "A completion overlay is used to:", optionA: "Eliminate the benchmark", optionB: "Fill gaps so total exposures match the desired target", optionC: "Increase fees", optionD: "Remove all equities", correctOption: "B", explanation: "A completion overlay (often via derivatives) aligns the portfolio's net exposures with the intended target.", orderIndex: 9 },
  { id: "cfa3-equity-pm-passive-active-factor-q11", topicId: "cfa3-equity-pm-passive-active-factor", text: "Full replication of an index is most practical when the index has:", optionA: "Thousands of illiquid constituents", optionB: "A manageable number of liquid constituents", optionC: "No constituents", optionD: "Only derivatives", correctOption: "B", explanation: "Full replication works well for indices with relatively few, liquid names; otherwise sampling/optimization is used.", orderIndex: 10 },
  { id: "cfa3-equity-pm-passive-active-factor-q12", topicId: "cfa3-equity-pm-passive-active-factor", text: "Relative to passive management, active management generally has:", optionA: "Lower fees and lower tracking error", optionB: "Higher fees and higher tracking error", optionC: "Zero fees", optionD: "No benchmark", correctOption: "B", explanation: "Active strategies charge more and deliberately deviate from the benchmark, producing higher tracking error.", orderIndex: 11 },

  // Risk management with derivatives
  { id: "cfa3-risk-management-derivatives-q01", topicId: "cfa3-risk-management-derivatives", text: "To reduce a portfolio's equity beta, a manager would:", optionA: "Buy equity index futures", optionB: "Sell equity index futures", optionC: "Buy more stocks", optionD: "Buy call options", correctOption: "B", explanation: "Selling (shorting) index futures lowers the portfolio's effective beta/market exposure.", orderIndex: 0 },
  { id: "cfa3-risk-management-derivatives-q02", topicId: "cfa3-risk-management-derivatives", text: "Interest-rate futures and swaps are most commonly used to adjust a bond portfolio's:", optionA: "Credit rating", optionB: "Duration", optionC: "Coupon", optionD: "Currency", correctOption: "B", explanation: "Rate derivatives let managers raise or lower portfolio duration without buying/selling the underlying bonds.", orderIndex: 1 },
  { id: "cfa3-risk-management-derivatives-q03", topicId: "cfa3-risk-management-derivatives", text: "A protective put strategy provides:", optionA: "A floor on losses while retaining upside", optionB: "A cap on gains with no downside protection", optionC: "Income but unlimited downside", optionD: "No effect on the payoff", correctOption: "A", explanation: "Buying a put on a held asset sets a price floor while leaving upside intact (less the premium).", orderIndex: 2 },
  { id: "cfa3-risk-management-derivatives-q04", topicId: "cfa3-risk-management-derivatives", text: "A covered call (long stock + short call) primarily:", optionA: "Generates premium income but caps upside", optionB: "Provides downside protection below the strike", optionC: "Increases upside without limit", optionD: "Eliminates all risk", correctOption: "A", explanation: "Writing a call earns premium income but caps gains at the strike; downside is only cushioned by the premium received.", orderIndex: 3 },
  { id: "cfa3-risk-management-derivatives-q05", topicId: "cfa3-risk-management-derivatives", text: "A collar combines a:", optionA: "Long put and short call around a held asset", optionB: "Two long calls", optionC: "Two short puts", optionD: "Long stock only", correctOption: "A", explanation: "A collar buys a protective put and sells a call to finance it, bounding both downside and upside.", orderIndex: 4 },
  { id: "cfa3-risk-management-derivatives-q06", topicId: "cfa3-risk-management-derivatives", text: "Basis risk in a hedge refers to the risk that:", optionA: "The hedge and the exposure do not move perfectly together", optionB: "Margin is required", optionC: "The option expires worthless", optionD: "Interest rates are zero", correctOption: "A", explanation: "Basis risk arises when the hedging instrument and the hedged exposure are imperfectly correlated, leaving residual risk.", orderIndex: 5 },
  { id: "cfa3-risk-management-derivatives-q07", topicId: "cfa3-risk-management-derivatives", text: "Currency forwards are used to:", optionA: "Increase equity beta", optionB: "Hedge the FX exposure of foreign-currency assets", optionC: "Adjust credit risk", optionD: "Raise duration", correctOption: "B", explanation: "Currency forwards offset the exchange-rate exposure embedded in foreign-currency-denominated holdings.", orderIndex: 6 },
  { id: "cfa3-risk-management-derivatives-q08", topicId: "cfa3-risk-management-derivatives", text: "Compared with OTC forwards, exchange-traded futures require:", optionA: "No collateral", optionB: "Margin and daily mark-to-market settlement", optionC: "Bilateral negotiation of every term", optionD: "No clearinghouse", correctOption: "B", explanation: "Futures are margined and settled daily through a clearinghouse, reducing counterparty risk versus bilateral forwards.", orderIndex: 7 },
  { id: "cfa3-risk-management-derivatives-q09", topicId: "cfa3-risk-management-derivatives", text: "To raise a portfolio's duration toward a target, a manager would generally:", optionA: "Sell interest-rate futures", optionB: "Buy interest-rate futures (or receive-fixed in a swap)", optionC: "Buy protective puts", optionD: "Short equities", correctOption: "B", explanation: "Going long rate futures (or receiving fixed in a swap) adds duration, raising the portfolio toward its target.", orderIndex: 8 },
  { id: "cfa3-risk-management-derivatives-q10", topicId: "cfa3-risk-management-derivatives", text: "A drawback of hedging with a symmetric instrument like a forward or future is that it:", optionA: "Removes downside but keeps upside", optionB: "Removes both downside and upside exposure", optionC: "Has unlimited upside", optionD: "Requires no monitoring", correctOption: "B", explanation: "Forwards/futures lock in a rate, eliminating both adverse and favorable moves—unlike asymmetric options.", orderIndex: 9 },
  { id: "cfa3-risk-management-derivatives-q11", topicId: "cfa3-risk-management-derivatives", text: "Delta hedging an option position must be rebalanced over time because of:", optionA: "Theta", optionB: "Gamma (delta changes as the underlying moves)", optionC: "Rho", optionD: "The strike", correctOption: "B", explanation: "Gamma causes delta to change with the underlying, so a static delta hedge drifts and needs dynamic rebalancing.", orderIndex: 10 },
  { id: "cfa3-risk-management-derivatives-q12", topicId: "cfa3-risk-management-derivatives", text: "The number of equity futures to change beta depends on the target and current betas and the ratio of:", optionA: "Portfolio value to futures contract value", optionB: "Coupon to yield", optionC: "Dividends to price", optionD: "Duration to convexity", correctOption: "A", explanation: "Contracts ≈ [(β_target − β_portfolio)/β_futures] × (portfolio value / futures contract value).", orderIndex: 11 },

  // Private wealth: tax & estate
  { id: "cfa3-private-wealth-tax-estate-q01", topicId: "cfa3-private-wealth-tax-estate", text: "'Asset location' refers to:", optionA: "Geographic diversification", optionB: "Placing tax-inefficient assets in tax-advantaged accounts", optionC: "Choosing a custodian", optionD: "Currency hedging", correctOption: "B", explanation: "Asset location optimizes after-tax returns by holding tax-inefficient assets (e.g., bonds) in tax-deferred/exempt accounts.", orderIndex: 0 },
  { id: "cfa3-private-wealth-tax-estate-q02", topicId: "cfa3-private-wealth-tax-estate", text: "Tax drag is most damaging to terminal wealth when:", optionA: "Horizons are short", optionB: "Returns are taxed annually over long horizons", optionC: "There are no returns", optionD: "Assets are tax-exempt", correctOption: "B", explanation: "Annual taxation reduces the compounding base each year; over long horizons this drag compounds significantly.", orderIndex: 1 },
  { id: "cfa3-private-wealth-tax-estate-q03", topicId: "cfa3-private-wealth-tax-estate", text: "A tax-deferred account is most advantageous when the investor expects their future tax rate to be:", optionA: "Higher than today", optionB: "Lower than today", optionC: "Exactly the same", optionD: "Zero forever", correctOption: "B", explanation: "Deferring tax (pre-tax contributions, taxed on withdrawal) helps most when withdrawals are taxed at a lower future rate.", orderIndex: 2 },
  { id: "cfa3-private-wealth-tax-estate-q04", topicId: "cfa3-private-wealth-tax-estate", text: "Tax-loss harvesting improves after-tax returns by:", optionA: "Realizing losses to offset taxable gains", optionB: "Increasing turnover for its own sake", optionC: "Avoiding all equities", optionD: "Deferring dividends", correctOption: "A", explanation: "Harvesting losses offsets realized gains (and some income), lowering the current tax bill and deferring taxes.", orderIndex: 3 },
  { id: "cfa3-private-wealth-tax-estate-q05", topicId: "cfa3-private-wealth-tax-estate", text: "A 'step-up in basis' at death can benefit heirs by:", optionA: "Eliminating embedded capital gains on inherited assets", optionB: "Increasing the estate tax", optionC: "Forcing immediate sale", optionD: "Removing all dividends", correctOption: "A", explanation: "Resetting the cost basis to fair value at death can erase unrealized capital gains for heirs.", orderIndex: 4 },
  { id: "cfa3-private-wealth-tax-estate-q06", topicId: "cfa3-private-wealth-tax-estate", text: "Lifetime gifting can reduce estate taxes primarily by:", optionA: "Removing future appreciation of the gifted asset from the estate", optionB: "Increasing the taxable estate", optionC: "Raising the donor's income", optionD: "Eliminating the gift's value", correctOption: "A", explanation: "Gifting transfers an asset—and its future growth—out of the estate, often at a lower transfer-tax cost.", orderIndex: 5 },
  { id: "cfa3-private-wealth-tax-estate-q07", topicId: "cfa3-private-wealth-tax-estate", text: "Which is a constraint (not an objective) in an individual's IPS?", optionA: "Required rate of return", optionB: "Time horizon", optionC: "Risk tolerance", optionD: "Target alpha", correctOption: "B", explanation: "IPS constraints include time horizon, liquidity, taxes, legal/regulatory, and unique circumstances; return and risk are objectives.", orderIndex: 6 },
  { id: "cfa3-private-wealth-tax-estate-q08", topicId: "cfa3-private-wealth-tax-estate", text: "An irrevocable trust differs from a revocable trust in that the grantor:", optionA: "Can freely change or revoke it", optionB: "Generally gives up control, often removing assets from the taxable estate", optionC: "Pays no setup cost", optionD: "Retains full ownership", correctOption: "B", explanation: "Irrevocable trusts remove assets from the grantor's control (and often the estate), unlike revocable trusts.", orderIndex: 7 },
  { id: "cfa3-private-wealth-tax-estate-q09", topicId: "cfa3-private-wealth-tax-estate", text: "Holding low-turnover, tax-efficient equities in a taxable account is consistent with:", optionA: "Poor asset location", optionB: "Sound asset-location practice", optionC: "Maximizing tax drag", optionD: "Avoiding equities", correctOption: "B", explanation: "Tax-efficient assets belong in taxable accounts, leaving scarce tax-advantaged space for tax-inefficient holdings.", orderIndex: 8 },
  { id: "cfa3-private-wealth-tax-estate-q10", topicId: "cfa3-private-wealth-tax-estate", text: "An individual's 'human capital' is best described as:", optionA: "The present value of future labor income", optionB: "Their stock portfolio", optionC: "Their home equity", optionD: "Their pension only", correctOption: "A", explanation: "Human capital is the present value of expected future earnings; bond-like human capital argues for more equity in financial assets.", orderIndex: 9 },
  { id: "cfa3-private-wealth-tax-estate-q11", topicId: "cfa3-private-wealth-tax-estate", text: "Longevity risk for a retiree is the risk of:", optionA: "Dying earlier than expected", optionB: "Outliving one's assets", optionC: "Market volatility only", optionD: "Currency depreciation", correctOption: "B", explanation: "Longevity risk is the danger of living longer than planned and exhausting savings; annuities can hedge it.", orderIndex: 10 },
  { id: "cfa3-private-wealth-tax-estate-q12", topicId: "cfa3-private-wealth-tax-estate", text: "A tax-exempt account (after-tax contributions, tax-free withdrawals) is most attractive when future tax rates are expected to be:", optionA: "Lower than today", optionB: "Higher than today", optionC: "Zero", optionD: "Irrelevant", correctOption: "B", explanation: "Paying tax now (tax-exempt account) is favorable when withdrawals would otherwise be taxed at a higher future rate.", orderIndex: 11 },

  // Pensions & endowments
  { id: "cfa3-institutional-pensions-endowments-q01", topicId: "cfa3-institutional-pensions-endowments", text: "A defined-benefit pension generally has a HIGHER risk tolerance when:", optionA: "The workforce is older and the plan is underfunded", optionB: "The workforce is younger and the plan is well funded", optionC: "The sponsor is financially weak", optionD: "The plan is large relative to the sponsor", correctOption: "B", explanation: "Younger workforce, strong funded status, and a financially healthy sponsor all raise a DB plan's ability to bear risk.", orderIndex: 0 },
  { id: "cfa3-institutional-pensions-endowments-q02", topicId: "cfa3-institutional-pensions-endowments", text: "Because pension liabilities are bond-like, plans commonly adopt:", optionA: "Pure equity indexing", optionB: "Liability-driven investing (duration matching)", optionC: "Currency speculation", optionD: "Commodity-only portfolios", correctOption: "B", explanation: "LDI hedges the interest-rate sensitivity of the bond-like liabilities by matching asset and liability duration.", orderIndex: 1 },
  { id: "cfa3-institutional-pensions-endowments-q03", topicId: "cfa3-institutional-pensions-endowments", text: "An endowment's primary objective is typically to:", optionA: "Maximize short-term income", optionB: "Support spending in perpetuity while preserving real value", optionC: "Avoid all equities", optionD: "Minimize the time horizon", correctOption: "B", explanation: "Endowments aim to fund ongoing spending forever while maintaining the inflation-adjusted (real) value of the corpus.", orderIndex: 2 },
  { id: "cfa3-institutional-pensions-endowments-q04", topicId: "cfa3-institutional-pensions-endowments", text: "An endowment's return objective is approximately:", optionA: "The risk-free rate", optionB: "Spending rate + inflation + fees", optionC: "Zero", optionD: "The dividend yield only", correctOption: "B", explanation: "To preserve real value and fund spending, the required return ≈ spending rate + expected inflation + management costs.", orderIndex: 3 },
  { id: "cfa3-institutional-pensions-endowments-q05", topicId: "cfa3-institutional-pensions-endowments", text: "A rolling 3-year average spending rule is used to:", optionA: "Increase spending volatility", optionB: "Smooth distributions versus a simple percentage of current assets", optionC: "Eliminate spending", optionD: "Track a single year's return", correctOption: "B", explanation: "Averaging asset values over several years smooths spending, reducing year-to-year volatility in distributions.", orderIndex: 4 },
  { id: "cfa3-institutional-pensions-endowments-q06", topicId: "cfa3-institutional-pensions-endowments", text: "Endowments typically have a ____ risk tolerance and ____ time horizon.", optionA: "low; short", optionB: "high; long", optionC: "low; long", optionD: "high; short", correctOption: "B", explanation: "Their perpetual horizon and limited near-term liquidity needs give endowments high risk tolerance and a long horizon.", orderIndex: 5 },
  { id: "cfa3-institutional-pensions-endowments-q07", topicId: "cfa3-institutional-pensions-endowments", text: "A higher proportion of retired lives in a pension plan tends to increase its:", optionA: "Risk tolerance", optionB: "Liquidity needs", optionC: "Time horizon", optionD: "Equity allocation", correctOption: "B", explanation: "More retirees means larger, nearer-term benefit payments, raising liquidity needs and lowering risk tolerance.", orderIndex: 6 },
  { id: "cfa3-institutional-pensions-endowments-q08", topicId: "cfa3-institutional-pensions-endowments", text: "Banks and insurers, relative to endowments, generally have:", optionA: "Higher risk tolerance and longer horizons", optionB: "Lower risk tolerance with strong liability/ALM and liquidity focus", optionC: "No regulation", optionD: "No liabilities", correctOption: "B", explanation: "Regulated, liability-driven institutions like banks/insurers have lower risk tolerance and emphasize asset-liability management and liquidity.", orderIndex: 7 },
  { id: "cfa3-institutional-pensions-endowments-q09", topicId: "cfa3-institutional-pensions-endowments", text: "US private foundations are generally required to distribute about:", optionA: "1% of assets annually", optionB: "5% of assets annually", optionC: "20% of assets annually", optionD: "Nothing", correctOption: "B", explanation: "US private foundations typically must pay out roughly 5% of assets per year to maintain tax-exempt status.", orderIndex: 8 },
  { id: "cfa3-institutional-pensions-endowments-q10", topicId: "cfa3-institutional-pensions-endowments", text: "The 'Yale' (geometric/smoothing) spending rule blends:", optionA: "Prior spending and current market value", optionB: "Only the risk-free rate", optionC: "Dividends and coupons only", optionD: "Beta and alpha", correctOption: "A", explanation: "The geometric/Yale rule weights last year's (inflation-adjusted) spending and a percentage of current market value to stabilize payouts.", orderIndex: 9 },
  { id: "cfa3-institutional-pensions-endowments-q11", topicId: "cfa3-institutional-pensions-endowments", text: "A pension plan whose asset returns are highly correlated with the sponsor's operating results should generally take:", optionA: "More investment risk", optionB: "Less investment risk", optionC: "The same risk regardless", optionD: "Only currency risk", correctOption: "B", explanation: "High correlation between plan assets and sponsor health concentrates risk, arguing for a more conservative plan allocation.", orderIndex: 10 },
  { id: "cfa3-institutional-pensions-endowments-q12", topicId: "cfa3-institutional-pensions-endowments", text: "Endowments' long horizons and high risk tolerance often lead to large allocations to:", optionA: "Cash and T-bills", optionB: "Equities and alternative investments", optionC: "Short-term deposits only", optionD: "A single bond", correctOption: "B", explanation: "To meet real-return objectives over perpetual horizons, endowments tilt toward equities and alternatives (the 'endowment model').", orderIndex: 11 },

  // Rebalancing & execution
  { id: "cfa3-asset-allocation-rebalancing-execution-q01", topicId: "cfa3-asset-allocation-rebalancing-execution", text: "A percentage-range (corridor) rebalancing policy triggers a trade when:", optionA: "A fixed calendar date arrives", optionB: "An asset's weight breaches its tolerance band", optionC: "The market rises", optionD: "A dividend is paid", correctOption: "B", explanation: "Corridor rebalancing acts when an allocation drifts outside its preset band, regardless of the date.", orderIndex: 0 },
  { id: "cfa3-asset-allocation-rebalancing-execution-q02", topicId: "cfa3-asset-allocation-rebalancing-execution", text: "Optimal rebalancing corridors should be WIDER for assets with:", optionA: "Higher transaction costs", optionB: "Higher volatility", optionC: "Higher correlation with the rest of the portfolio", optionD: "Lower risk tolerance", correctOption: "A", explanation: "Higher trading costs justify wider bands to avoid frequent, costly rebalancing; higher volatility argues for narrower bands.", orderIndex: 1 },
  { id: "cfa3-asset-allocation-rebalancing-execution-q03", topicId: "cfa3-asset-allocation-rebalancing-execution", text: "Disciplined rebalancing is inherently:", optionA: "A momentum strategy", optionB: "A contrarian strategy (sell winners, buy losers)", optionC: "Identical to buy-and-hold", optionD: "Risk-free", correctOption: "B", explanation: "Rebalancing trims appreciated assets and tops up laggards—a contrarian action that can earn a diversification return.", orderIndex: 2 },
  { id: "cfa3-asset-allocation-rebalancing-execution-q04", topicId: "cfa3-asset-allocation-rebalancing-execution", text: "Implementation shortfall measures the difference between:", optionA: "Two benchmarks", optionB: "A paper portfolio's return and the actual executed return", optionC: "Beta and alpha", optionD: "Bid and ask only", correctOption: "B", explanation: "Implementation shortfall captures total trading cost as the gap between a hypothetical (decision-price) portfolio and the real one.", orderIndex: 3 },
  { id: "cfa3-asset-allocation-rebalancing-execution-q05", topicId: "cfa3-asset-allocation-rebalancing-execution", text: "Which is an IMPLICIT trading cost?", optionA: "Brokerage commission", optionB: "Market impact", optionC: "Exchange fee", optionD: "Transaction tax", correctOption: "B", explanation: "Market impact (the price move caused by trading) is implicit; commissions, fees and taxes are explicit costs.", orderIndex: 4 },
  { id: "cfa3-asset-allocation-rebalancing-execution-q06", topicId: "cfa3-asset-allocation-rebalancing-execution", text: "VWAP as an execution benchmark compares fills against the:", optionA: "Volume-weighted average price over the period", optionB: "Closing price only", optionC: "Risk-free rate", optionD: "Prior day's open", correctOption: "A", explanation: "VWAP measures execution quality against the volume-weighted average traded price during the order's horizon.", orderIndex: 5 },
  { id: "cfa3-asset-allocation-rebalancing-execution-q07", topicId: "cfa3-asset-allocation-rebalancing-execution", text: "A more aggressive (liquidity-demanding) execution generally has:", optionA: "Higher market impact but lower timing risk", optionB: "Lower impact and lower timing risk", optionC: "No costs", optionD: "Higher opportunity cost", correctOption: "A", explanation: "Trading quickly raises market-impact cost but reduces exposure to adverse price drift (timing risk).", orderIndex: 6 },
  { id: "cfa3-asset-allocation-rebalancing-execution-q08", topicId: "cfa3-asset-allocation-rebalancing-execution", text: "The opportunity cost component of implementation shortfall arises from:", optionA: "Commissions", optionB: "Portions of the order left unfilled as the price moves away", optionC: "Taxes", optionD: "The bid-ask spread only", correctOption: "B", explanation: "Unexecuted shares whose price moves adversely create an opportunity (missed-trade) cost.", orderIndex: 7 },
  { id: "cfa3-asset-allocation-rebalancing-execution-q09", topicId: "cfa3-asset-allocation-rebalancing-execution", text: "Slicing a large order into smaller child orders over time primarily aims to:", optionA: "Increase market impact", optionB: "Reduce market impact", optionC: "Raise commissions", optionD: "Avoid all risk", correctOption: "B", explanation: "Breaking a large order into pieces limits the price impact of demanding too much liquidity at once.", orderIndex: 8 },
  { id: "cfa3-asset-allocation-rebalancing-execution-q10", topicId: "cfa3-asset-allocation-rebalancing-execution", text: "Calendar rebalancing differs from corridor rebalancing in that it:", optionA: "Responds to market moves continuously", optionB: "Rebalances on fixed dates regardless of drift", optionC: "Never trades", optionD: "Eliminates transaction costs", correctOption: "B", explanation: "Calendar rebalancing is time-triggered, ignoring how far weights have drifted between dates.", orderIndex: 9 },
  { id: "cfa3-asset-allocation-rebalancing-execution-q11", topicId: "cfa3-asset-allocation-rebalancing-execution", text: "The diversification return captured by rebalancing is greatest when assets have:", optionA: "Perfectly correlated returns", optionB: "Volatile, less-than-perfectly correlated returns", optionC: "Zero volatility", optionD: "Identical returns", correctOption: "B", explanation: "Rebalancing benefits most from volatile assets whose correlations are below 1, harvesting relative mispricings.", orderIndex: 10 },
  { id: "cfa3-asset-allocation-rebalancing-execution-q12", topicId: "cfa3-asset-allocation-rebalancing-execution", text: "An implementation-shortfall execution algorithm explicitly trades off:", optionA: "Market impact against timing/price risk", optionB: "Dividends against coupons", optionC: "Beta against alpha", optionD: "Duration against convexity", correctOption: "A", explanation: "IS algorithms balance the cost of trading fast (impact) against the risk of trading slowly (price drift).", orderIndex: 11 },

  // Currency management
  { id: "cfa3-risk-management-currency-q01", topicId: "cfa3-risk-management-currency", text: "The total return on an unhedged foreign asset comprises the local asset return and the:", optionA: "Risk-free rate", optionB: "Currency (exchange-rate) return", optionC: "Dividend yield only", optionD: "Inflation rate", correctOption: "B", explanation: "An unhedged foreign investment earns the foreign asset's return plus the return from currency movements.", orderIndex: 0 },
  { id: "cfa3-risk-management-currency-q02", topicId: "cfa3-risk-management-currency", text: "The most commonly used instrument for currency hedging is the:", optionA: "Currency forward", optionB: "Equity index future", optionC: "Credit default swap", optionD: "Interest-rate cap", correctOption: "A", explanation: "Currency forwards are precise, low-cost and widely used; they are rolled at maturity to maintain a hedge.", orderIndex: 1 },
  { id: "cfa3-risk-management-currency-q03", topicId: "cfa3-risk-management-currency", text: "Currency risk is typically hedged MORE for foreign bond portfolios than equity portfolios because:", optionA: "Bonds have higher returns", optionB: "Currency volatility is large relative to bond returns", optionC: "Bonds have no issuer risk", optionD: "Equities cannot be hedged", correctOption: "B", explanation: "For bonds the currency swing can dwarf the yield, so hedging is common; for equities currency is a smaller, diversifying share.", orderIndex: 2 },
  { id: "cfa3-risk-management-currency-q04", topicId: "cfa3-risk-management-currency", text: "A fully hedged foreign-asset position is most appropriate for an investor who is:", optionA: "Long-horizon and risk-seeking", optionB: "Short-horizon and risk-averse", optionC: "Indifferent to risk", optionD: "Seeking maximum currency exposure", correctOption: "B", explanation: "Shorter horizons and risk aversion push toward higher hedge ratios to remove currency volatility.", orderIndex: 3 },
  { id: "cfa3-risk-management-currency-q05", topicId: "cfa3-risk-management-currency", text: "The minimum-variance hedge ratio is estimated as the:", optionA: "Beta from regressing domestic-currency asset returns on the exchange-rate return", optionB: "Ratio of durations", optionC: "Dividend yield", optionD: "Sharpe ratio", correctOption: "A", explanation: "The minimum-variance hedge ratio is the regression slope of the asset's domestic-currency return on the currency return.", orderIndex: 4 },
  { id: "cfa3-risk-management-currency-q06", topicId: "cfa3-risk-management-currency", text: "A proxy (cross) hedge is used when:", optionA: "A direct forward in the exposure currency is costly or unavailable", optionB: "The asset is domestic", optionC: "There is no currency risk", optionD: "Interest rates are zero", correctOption: "A", explanation: "A proxy hedge uses a correlated, more liquid/cheaper currency when a direct forward is impractical—introducing basis risk.", orderIndex: 5 },
  { id: "cfa3-risk-management-currency-q07", topicId: "cfa3-risk-management-currency", text: "Currency options differ from forwards as a hedge in that options:", optionA: "Provide asymmetric protection (downside hedged, upside kept) for a premium", optionB: "Lock in a single rate with no premium", optionC: "Cannot expire", optionD: "Have no cost", correctOption: "A", explanation: "Options hedge adverse moves while retaining favorable ones, at the cost of the premium—unlike symmetric forwards.", orderIndex: 6 },
  { id: "cfa3-risk-management-currency-q08", topicId: "cfa3-risk-management-currency", text: "A currency overlay manager is hired to:", optionA: "Manage the underlying stocks and bonds", optionB: "Manage currency exposure (and seek FX alpha) separately from the asset managers", optionC: "Set the strategic asset allocation", optionD: "Run the leaderboard", correctOption: "B", explanation: "A currency overlay separates FX management—hedging and active currency bets—from the underlying asset mandates.", orderIndex: 7 },
  { id: "cfa3-risk-management-currency-q09", topicId: "cfa3-risk-management-currency", text: "Maintaining a forward hedge requires periodically:", optionA: "Rolling the forward at maturity", optionB: "Paying dividends", optionC: "Exercising an option", optionD: "Issuing equity", correctOption: "A", explanation: "Forwards expire, so a continuing hedge is maintained by rolling into a new forward at each maturity.", orderIndex: 8 },
  { id: "cfa3-risk-management-currency-q10", topicId: "cfa3-risk-management-currency", text: "Active currency strategies commonly exploit which factor?", optionA: "Carry (interest-rate differentials)", optionB: "Bond convexity", optionC: "Equity book value", optionD: "Operating leverage", correctOption: "A", explanation: "Currency alpha tactics include carry, value (PPP), momentum and volatility trading.", orderIndex: 9 },
  { id: "cfa3-risk-management-currency-q11", topicId: "cfa3-risk-management-currency", text: "'Roll yield' on a currency hedge refers to the return from:", optionA: "Dividends on the foreign asset", optionB: "The forward premium/discount as the hedge is rolled", optionC: "Equity price changes", optionD: "Coupon reinvestment", correctOption: "B", explanation: "Hedging a currency trading at a forward premium or discount adds or subtracts return when the forward is rolled.", orderIndex: 10 },
  { id: "cfa3-risk-management-currency-q12", topicId: "cfa3-risk-management-currency", text: "Leaving foreign-equity currency exposure partially unhedged can be justified because currencies may:", optionA: "Guarantee higher returns", optionB: "Provide diversification to the overall portfolio", optionC: "Eliminate equity risk", optionD: "Remove the need for an IPS", correctOption: "B", explanation: "Currency returns are imperfectly correlated with equities, so some unhedged exposure can add diversification.", orderIndex: 11 },

  // Ethics: Asset Manager Code & GIPS
  { id: "cfa3-ethics-asset-manager-code-q01", topicId: "cfa3-ethics-asset-manager-code", text: "The Asset Manager Code applies at the level of the:", optionA: "Individual member", optionB: "Firm", optionC: "Regulator", optionD: "Client", correctOption: "B", explanation: "The AMC is a firm-level voluntary code of conduct, distinct from the individual Code and Standards.", orderIndex: 0 },
  { id: "cfa3-ethics-asset-manager-code-q02", topicId: "cfa3-ethics-asset-manager-code", text: "Compliance with the Asset Manager Code is:", optionA: "Verified by CFA Institute before a firm may claim it", optionB: "Self-claimed by the firm; CFA Institute does not verify it", optionC: "Mandatory for all firms", optionD: "Granted by regulators", correctOption: "B", explanation: "Firms claim AMC compliance themselves; CFA Institute does not certify or verify those claims.", orderIndex: 1 },
  { id: "cfa3-ethics-asset-manager-code-q03", topicId: "cfa3-ethics-asset-manager-code", text: "Which is one of the six components of the Asset Manager Code?", optionA: "Maximizing assets under management", optionB: "Trading (best execution, client brokerage)", optionC: "Beating the benchmark every year", optionD: "Avoiding all derivatives", correctOption: "B", explanation: "The AMC's six areas include Loyalty to Clients, Investment Process, Trading, Risk/Compliance, Performance/Valuation, and Disclosures.", orderIndex: 2 },
  { id: "cfa3-ethics-asset-manager-code-q04", topicId: "cfa3-ethics-asset-manager-code", text: "GIPS compliance must be applied on a ____ basis.", optionA: "Composite-by-composite", optionB: "Firm-wide", optionC: "Per-client", optionD: "Per-portfolio", correctOption: "B", explanation: "A firm either complies with GIPS firm-wide or it does not; partial (composite-only) compliance is not permitted.", orderIndex: 3 },
  { id: "cfa3-ethics-asset-manager-code-q05", topicId: "cfa3-ethics-asset-manager-code", text: "A GIPS composite must include:", optionA: "Only the firm's best-performing portfolios", optionB: "All fee-paying discretionary portfolios of a similar mandate", optionC: "Hypothetical model portfolios", optionD: "Only terminated accounts", correctOption: "B", explanation: "Composites group all actual fee-paying discretionary portfolios of a strategy, preventing cherry-picking and survivorship bias.", orderIndex: 4 },
  { id: "cfa3-ethics-asset-manager-code-q06", topicId: "cfa3-ethics-asset-manager-code", text: "GIPS requires returns to be calculated using a ____ return.", optionA: "Money-weighted", optionB: "Time-weighted", optionC: "Simple average", optionD: "Geometric-only nominal", correctOption: "B", explanation: "Time-weighted returns remove the distorting effect of client-driven external cash flows, the GIPS default for composites.", orderIndex: 5 },
  { id: "cfa3-ethics-asset-manager-code-q07", topicId: "cfa3-ethics-asset-manager-code", text: "Third-party verification under GIPS is:", optionA: "Mandatory", optionB: "Recommended but voluntary, and applies firm-wide", optionC: "Performed by CFA Institute", optionD: "Done per composite only", correctOption: "B", explanation: "Verification is recommended, voluntary, and assesses firm-wide compliance—not individual composites.", orderIndex: 6 },
  { id: "cfa3-ethics-asset-manager-code-q08", topicId: "cfa3-ethics-asset-manager-code", text: "Under the AMC, client brokerage (soft dollars) must be used:", optionA: "For the manager's overhead", optionB: "For the benefit of the client", optionC: "To reward the largest clients", optionD: "However the firm wishes", correctOption: "B", explanation: "The Trading component requires client brokerage to be used for the client's benefit, consistent with the Standards.", orderIndex: 7 },
  { id: "cfa3-ethics-asset-manager-code-q09", topicId: "cfa3-ethics-asset-manager-code", text: "The AMC requires firms to designate a:", optionA: "Marketing director", optionB: "Compliance officer responsible for policies and controls", optionC: "Chief investment officer only", optionD: "Board chair", correctOption: "B", explanation: "The Risk Management, Compliance and Support component requires a designated compliance officer and adequate controls.", orderIndex: 8 },
  { id: "cfa3-ethics-asset-manager-code-q10", topicId: "cfa3-ethics-asset-manager-code", text: "When first claiming GIPS compliance, a firm must present at least ____ of compliant history (building toward 10).", optionA: "1 month", optionB: "5 years (or since inception if shorter)", optionC: "20 years", optionD: "No history", correctOption: "B", explanation: "Firms must show a minimum of five years (or since inception) of GIPS-compliant performance, then build to ten.", orderIndex: 9 },
  { id: "cfa3-ethics-asset-manager-code-q11", topicId: "cfa3-ethics-asset-manager-code", text: "A primary purpose of the GIPS standards is to ensure:", optionA: "Higher returns", optionB: "Fair representation and full disclosure of performance", optionC: "Lower fees", optionD: "Tax efficiency", correctOption: "B", explanation: "GIPS exists to standardize performance reporting so it fairly represents results and fully discloses methodology.", orderIndex: 10 },
  { id: "cfa3-ethics-asset-manager-code-q12", topicId: "cfa3-ethics-asset-manager-code", text: "Under the AMC Disclosures component, firms must disclose:", optionA: "Only positive performance", optionB: "Conflicts of interest, fees and costs truthfully and on time", optionC: "Competitors' weaknesses", optionD: "Clients' identities publicly", correctOption: "B", explanation: "Disclosures must be truthful, accurate, complete and timely—covering conflicts, fees, costs and material information.", orderIndex: 11 },

  // Alternatives in portfolio management
  { id: "cfa3-alternative-investments-portfolio-role-q01", topicId: "cfa3-alternative-investments-portfolio-role", text: "A primary portfolio reason to add alternatives is:", optionA: "Guaranteed returns", optionB: "Diversification and potential return/inflation benefits", optionC: "Daily liquidity", optionD: "Zero fees", correctOption: "B", explanation: "Alternatives are added mainly for diversification, return enhancement, and inflation protection—not liquidity or low cost.", orderIndex: 0 },
  { id: "cfa3-alternative-investments-portfolio-role-q02", topicId: "cfa3-alternative-investments-portfolio-role", text: "Appraisal-based (stale) pricing of private assets causes reported returns to have:", optionA: "Overstated volatility", optionB: "Understated volatility and correlation (smoothing)", optionC: "No bias", optionD: "Negative returns", correctOption: "B", explanation: "Smoothing from infrequent appraisals understates measured volatility and correlation, flattering risk statistics.", orderIndex: 1 },
  { id: "cfa3-alternative-investments-portfolio-role-q03", topicId: "cfa3-alternative-investments-portfolio-role", text: "Feeding smoothed alternative returns directly into mean-variance optimization tends to:", optionA: "Under-allocate to alternatives", optionB: "Over-allocate to alternatives", optionC: "Have no effect", optionD: "Eliminate them", correctOption: "B", explanation: "Because risk looks artificially low, naive MVO over-allocates to alternatives; returns should be 'unsmoothed' first.", orderIndex: 2 },
  { id: "cfa3-alternative-investments-portfolio-role-q04", topicId: "cfa3-alternative-investments-portfolio-role", text: "The correlation of alternatives with public markets typically:", optionA: "Stays constant", optionB: "Rises during market crises, reducing diversification when most needed", optionC: "Falls to zero in crises", optionD: "Is always 1", correctOption: "B", explanation: "Diversification benefits weaken in stress as correlations spike across asset classes.", orderIndex: 3 },
  { id: "cfa3-alternative-investments-portfolio-role-q05", topicId: "cfa3-alternative-investments-portfolio-role", text: "Allocating alternatives by 'role' means grouping them by:", optionA: "Ticker", optionB: "Function (growth, income, diversification, inflation hedge)", optionC: "Manager surname", optionD: "Country only", correctOption: "B", explanation: "A functional/role-based approach allocates by the economic purpose each alternative serves, rather than rigid asset-class labels.", orderIndex: 4 },
  { id: "cfa3-alternative-investments-portfolio-role-q06", topicId: "cfa3-alternative-investments-portfolio-role", text: "Risk measurement for alternatives should account for returns that are:", optionA: "Perfectly normal", optionB: "Non-normal (fat-tailed, negatively skewed)", optionC: "Risk-free", optionD: "Symmetric and thin-tailed", correctOption: "B", explanation: "Alternative returns often have fat tails and negative skew, so volatility/VaR alone understate risk—use scenario and downside measures.", orderIndex: 5 },
  { id: "cfa3-alternative-investments-portfolio-role-q07", topicId: "cfa3-alternative-investments-portfolio-role", text: "The 'J-curve' affects private-fund allocations by producing:", optionA: "Immediate high returns", optionB: "Early negative returns before later gains", optionC: "Constant returns", optionD: "Guaranteed losses", correctOption: "B", explanation: "Fees and early markdowns create initial negative returns (the J-curve) before exits generate gains.", orderIndex: 6 },
  { id: "cfa3-alternative-investments-portfolio-role-q08", topicId: "cfa3-alternative-investments-portfolio-role", text: "Commitment pacing and vintage-year diversification are used to manage:", optionA: "Currency risk", optionB: "Liquidity and timing risk in private funds", optionC: "Interest-rate risk only", optionD: "Tax filing", correctOption: "B", explanation: "Spreading commitments across vintages manages liquidity, the J-curve, and timing concentration in private programs.", orderIndex: 7 },
  { id: "cfa3-alternative-investments-portfolio-role-q09", topicId: "cfa3-alternative-investments-portfolio-role", text: "A key constraint on sizing alternatives is:", optionA: "Excessive liquidity", optionB: "Illiquidity, lock-ups and high fees", optionC: "Daily pricing", optionD: "Government guarantees", correctOption: "B", explanation: "Long lock-ups, illiquidity, high fees and operational risk limit how much a portfolio can prudently allocate.", orderIndex: 8 },
  { id: "cfa3-alternative-investments-portfolio-role-q10", topicId: "cfa3-alternative-investments-portfolio-role", text: "Real assets (e.g., commodities, real estate, infrastructure) are often added for:", optionA: "Inflation protection", optionB: "Guaranteed income", optionC: "Tax exemption", optionD: "Zero volatility", correctOption: "A", explanation: "Real assets tend to provide inflation sensitivity, a key diversifying role in multi-asset portfolios.", orderIndex: 9 },
  { id: "cfa3-alternative-investments-portfolio-role-q11", topicId: "cfa3-alternative-investments-portfolio-role", text: "Benchmarking hedge funds is difficult, so investors often use:", optionA: "A government bond index", optionB: "Peer-group or absolute/risk-factor benchmarks", optionC: "The risk-free rate exactly", optionD: "No benchmark is ever possible", correctOption: "B", explanation: "Hedge funds are commonly assessed against peer groups, absolute-return targets, or factor-based benchmarks.", orderIndex: 10 },
  { id: "cfa3-alternative-investments-portfolio-role-q12", topicId: "cfa3-alternative-investments-portfolio-role", text: "'Unsmoothing' a private-asset return series generally:", optionA: "Lowers estimated volatility further", optionB: "Raises estimated volatility and correlation toward true levels", optionC: "Removes all risk", optionD: "Converts it to cash", correctOption: "B", explanation: "Unsmoothing reverses appraisal lag, increasing measured volatility/correlation to more realistic levels for allocation.", orderIndex: 11 },

  // Manager selection & due diligence
  { id: "cfa3-manager-selection-due-diligence-q01", topicId: "cfa3-manager-selection-due-diligence", text: "A Type I error in manager selection is:", optionA: "Rejecting a skilled manager", optionB: "Hiring/retaining a manager with no real skill", optionC: "A data entry mistake", optionD: "Choosing a benchmark", correctOption: "B", explanation: "Type I (false positive) is keeping or hiring an unskilled manager.", orderIndex: 0 },
  { id: "cfa3-manager-selection-due-diligence-q02", topicId: "cfa3-manager-selection-due-diligence", text: "A Type II error in manager selection is:", optionA: "Hiring an unskilled manager", optionB: "Rejecting or firing a genuinely skilled manager", optionC: "Overpaying fees", optionD: "Using time-weighted returns", correctOption: "B", explanation: "Type II (false negative) is failing to hire or wrongly firing a skilled manager.", orderIndex: 1 },
  { id: "cfa3-manager-selection-due-diligence-q03", topicId: "cfa3-manager-selection-due-diligence", text: "Tightening selection criteria to avoid unskilled managers tends to:", optionA: "Reduce Type I but increase Type II errors", optionB: "Reduce both error types", optionC: "Increase Type I errors", optionD: "Have no effect on errors", correctOption: "A", explanation: "Stricter screens cut false positives (Type I) but raise the chance of rejecting skilled managers (Type II).", orderIndex: 2 },
  { id: "cfa3-manager-selection-due-diligence-q04", topicId: "cfa3-manager-selection-due-diligence", text: "Operational due diligence is important because operational failures are:", optionA: "Never a cause of fund losses", optionB: "A major cause of fund failures", optionC: "Only relevant to equities", optionD: "Irrelevant to selection", correctOption: "B", explanation: "Many fund blow-ups stem from operational issues (controls, valuation, fraud), making ODD essential.", orderIndex: 3 },
  { id: "cfa3-manager-selection-due-diligence-q05", topicId: "cfa3-manager-selection-due-diligence", text: "An independent administrator, custodian and auditor primarily provide:", optionA: "Higher returns", optionB: "Checks on valuation and safekeeping that reduce operational/fraud risk", optionC: "Tax savings", optionD: "Lower volatility", correctOption: "B", explanation: "Independent service providers verify assets and valuations, a key operational-risk control in due diligence.", orderIndex: 4 },
  { id: "cfa3-manager-selection-due-diligence-q06", topicId: "cfa3-manager-selection-due-diligence", text: "Decomposing a manager's return into alpha and factor exposures helps avoid:", optionA: "Paying alpha fees for what is really cheap beta", optionB: "Using a benchmark", optionC: "Diversification", optionD: "Time-weighted returns", correctOption: "A", explanation: "Returns-based analysis separates true skill (alpha) from factor (beta) exposure so investors don't overpay for beta.", orderIndex: 5 },
  { id: "cfa3-manager-selection-due-diligence-q07", topicId: "cfa3-manager-selection-due-diligence", text: "Backfill and survivorship biases in a manager database tend to:", optionA: "Understate historical performance", optionB: "Overstate historical performance", optionC: "Have no effect", optionD: "Only affect fees", correctOption: "B", explanation: "Both biases inflate reported track records, so due diligence must adjust for them.", orderIndex: 6 },
  { id: "cfa3-manager-selection-due-diligence-q08", topicId: "cfa3-manager-selection-due-diligence", text: "A short, volatile track record makes it hard to:", optionA: "Compute fees", optionB: "Distinguish skill from luck statistically", optionC: "Define a universe", optionD: "Read disclosures", correctOption: "B", explanation: "Limited, noisy data reduces statistical confidence in separating genuine skill from random outcomes.", orderIndex: 7 },
  { id: "cfa3-manager-selection-due-diligence-q09", topicId: "cfa3-manager-selection-due-diligence", text: "Investment due diligence assesses the manager's:", optionA: "Office location only", optionB: "Philosophy, repeatable process, team and decision-making", optionC: "Auditor's fees", optionD: "Custodian's address", correctOption: "B", explanation: "Investment DD evaluates whether the strategy, process and team can plausibly repeat past success.", orderIndex: 8 },
  { id: "cfa3-manager-selection-due-diligence-q10", topicId: "cfa3-manager-selection-due-diligence", text: "Key-person risk in manager selection refers to:", optionA: "The custodian failing", optionB: "Over-reliance on one critical individual", optionC: "High portfolio turnover", optionD: "Currency exposure", correctOption: "B", explanation: "Key-person risk is dependence on a single individual whose departure would impair the strategy.", orderIndex: 9 },
  { id: "cfa3-manager-selection-due-diligence-q11", topicId: "cfa3-manager-selection-due-diligence", text: "Capacity analysis matters because a strategy that grows too large may:", optionA: "Always improve returns", optionB: "Suffer decayed alpha from market impact and crowding", optionC: "Become risk-free", optionD: "Lower its fees automatically", correctOption: "B", explanation: "Excess assets can erode a strategy's edge through higher transaction costs and reduced opportunity per dollar.", orderIndex: 10 },
  { id: "cfa3-manager-selection-due-diligence-q12", topicId: "cfa3-manager-selection-due-diligence", text: "The final output of a sound manager-selection process should be:", optionA: "A ranking by last year's return only", optionB: "A conviction-weighted recommendation grounded in skill and operations", optionC: "The cheapest manager", optionD: "The largest fund", correctOption: "B", explanation: "Selection should yield a forward-looking, conviction-based decision integrating skill evidence and operational soundness, not just past returns.", orderIndex: 11 }
];
