// CFA expansion 6 — one additional high-yield reading per topic area (12
// questions each), filling syllabus gaps not covered by exp-1..5.
import type { Question } from "@jyotir/core";
import type { AuthoredMaterial } from "./builder";

export const expansionTopics = [
  {
    id: "cfa-ethics-independence-objectivity",
    subjectId: "cfa-ethics",
    name: "Independence, Objectivity & Misrepresentation",
    slug: "independence-objectivity",
    orderIndex: 5,
    materialId: "cfa-ethics-independence-objectivity-m01",
    questionIds: Array.from({ length: 12 }, (_, i) => `cfa-ethics-independence-objectivity-q${String(i + 1).padStart(2, "0")}`),
  },
  {
    id: "cfa-quantitative-methods-probability-distributions",
    subjectId: "cfa-quantitative-methods",
    name: "Common Probability Distributions",
    slug: "probability-distributions",
    orderIndex: 5,
    materialId: "cfa-quantitative-methods-probability-distributions-m01",
    questionIds: Array.from({ length: 12 }, (_, i) => `cfa-quantitative-methods-probability-distributions-q${String(i + 1).padStart(2, "0")}`),
  },
  {
    id: "cfa-economics-currency-parity",
    subjectId: "cfa-economics",
    name: "Currency Exchange Rate Parity Conditions",
    slug: "currency-parity",
    orderIndex: 5,
    materialId: "cfa-economics-currency-parity-m01",
    questionIds: Array.from({ length: 12 }, (_, i) => `cfa-economics-currency-parity-q${String(i + 1).padStart(2, "0")}`),
  },
  {
    id: "cfa-financial-reporting-reporting-quality",
    subjectId: "cfa-financial-reporting",
    name: "Financial Reporting Quality",
    slug: "reporting-quality",
    orderIndex: 5,
    materialId: "cfa-financial-reporting-reporting-quality-m01",
    questionIds: Array.from({ length: 12 }, (_, i) => `cfa-financial-reporting-reporting-quality-q${String(i + 1).padStart(2, "0")}`),
  },
  {
    id: "cfa-corporate-issuers-working-capital",
    subjectId: "cfa-corporate-issuers",
    name: "Working Capital & Liquidity Management",
    slug: "working-capital",
    orderIndex: 5,
    materialId: "cfa-corporate-issuers-working-capital-m01",
    questionIds: Array.from({ length: 12 }, (_, i) => `cfa-corporate-issuers-working-capital-q${String(i + 1).padStart(2, "0")}`),
  },
  {
    id: "cfa-equity-residual-income-valuation",
    subjectId: "cfa-equity",
    name: "Residual Income & Private Company Valuation",
    slug: "residual-income-valuation",
    orderIndex: 5,
    materialId: "cfa-equity-residual-income-valuation-m01",
    questionIds: Array.from({ length: 12 }, (_, i) => `cfa-equity-residual-income-valuation-q${String(i + 1).padStart(2, "0")}`),
  },
  {
    id: "cfa-fixed-income-spot-forward-rates",
    subjectId: "cfa-fixed-income",
    name: "Spot, Forward & Par Rates",
    slug: "spot-forward-rates",
    orderIndex: 5,
    materialId: "cfa-fixed-income-spot-forward-rates-m01",
    questionIds: Array.from({ length: 12 }, (_, i) => `cfa-fixed-income-spot-forward-rates-q${String(i + 1).padStart(2, "0")}`),
  },
  {
    id: "cfa-derivatives-binomial-option-valuation",
    subjectId: "cfa-derivatives",
    name: "Binomial Option Valuation",
    slug: "binomial-option-valuation",
    orderIndex: 5,
    materialId: "cfa-derivatives-binomial-option-valuation-m01",
    questionIds: Array.from({ length: 12 }, (_, i) => `cfa-derivatives-binomial-option-valuation-q${String(i + 1).padStart(2, "0")}`),
  },
  {
    id: "cfa-alternative-investments-private-debt",
    subjectId: "cfa-alternative-investments",
    name: "Private Debt & Direct Lending",
    slug: "private-debt",
    orderIndex: 5,
    materialId: "cfa-alternative-investments-private-debt-m01",
    questionIds: Array.from({ length: 12 }, (_, i) => `cfa-alternative-investments-private-debt-q${String(i + 1).padStart(2, "0")}`),
  },
  {
    id: "cfa-portfolio-management-behavioral-finance",
    subjectId: "cfa-portfolio-management",
    name: "Behavioral Finance & Biases",
    slug: "behavioral-finance",
    orderIndex: 5,
    materialId: "cfa-portfolio-management-behavioral-finance-m01",
    questionIds: Array.from({ length: 12 }, (_, i) => `cfa-portfolio-management-behavioral-finance-q${String(i + 1).padStart(2, "0")}`),
  },
];

export const expansionMaterials: AuthoredMaterial[] = [
  {
    id: "cfa-ethics-independence-objectivity-m01",
    topicId: "cfa-ethics-independence-objectivity",
    title: "Independence, Objectivity & Misrepresentation",
    content: `**Standard I(B) Independence and Objectivity** requires members to use reasonable care and judgement to maintain independence and avoid anything that could compromise it.

## Key rules
- **Gifts from clients** (for past work) may be accepted but **must be disclosed** to the employer. **Gifts/benefits from third parties** seeking to influence (e.g. an issuer paying for analyst travel) should be **declined** — pay your own way; modest, non-influential items only.
- **Buy-side and sell-side** pressure (issuers, own firm's IB division) must not bias research. Firms should use **firewalls**.
- **Credit-rating agencies**: keep rating and fee-negotiation functions separate.

## Standard I(C) Misrepresentation
- No untrue statements; no guaranteeing returns on volatile investments.
- **Plagiarism** = using others' work without attribution. You may use recognized statistical/factual data (e.g. from a government source) without attribution, but not another's analysis or models.
- Misrepresenting qualifications or performance also violates I(C).

> Disclose conflicts, decline influence-seeking perks, and attribute others' work.`,
    estimatedReadTime: 2,
    orderIndex: 5,
  },
  {
    id: "cfa-quantitative-methods-probability-distributions-m01",
    topicId: "cfa-quantitative-methods-probability-distributions",
    title: "Common Probability Distributions",
    content: `## Discrete vs continuous
- **Binomial**: n independent Bernoulli trials, success prob p. Mean = **np**, variance = **np(1−p)**.
- **Uniform (continuous)**: equal density over [a,b].
- **Normal**: symmetric, fully described by **μ and σ²**. ~**68% / 95% / 99%** of observations fall within 1 / 2 / 3 σ (precisely 1.65σ → 90%, 1.96σ → 95%, 2.58σ → 99%).

## Standard normal & safety-first
- **Z = (x − μ) / σ** standardizes any normal variable.
- **Roy's safety-first ratio** = (E[Rp] − R_threshold) / σ_p. **Maximize** it; the optimal portfolio minimizes P(return < threshold). The **Sharpe ratio** is the special case where the threshold is the risk-free rate.

## Lognormal
- If ln(X) is normal, X is **lognormal** — bounded below by 0 and **right-skewed**, so it is used to model **asset prices** (which can't go negative). Continuously compounded returns are normally distributed.

| Distribution | Use |
| --- | --- |
| Binomial | # of defaults / up-moves |
| Normal | returns |
| Lognormal | prices |`,
    estimatedReadTime: 2,
    orderIndex: 5,
  },
  {
    id: "cfa-economics-currency-parity-m01",
    topicId: "cfa-economics-currency-parity",
    title: "Currency Exchange Rate Parity Conditions",
    content: `Quote convention used here: **price/base** (e.g. USD/EUR = 1.20 means 1 EUR costs 1.20 USD).

## The parity conditions
- **Covered interest rate parity (CIRP)** holds by arbitrage: the **forward** premium/discount exactly offsets the interest-rate differential. Forward ≈ Spot × (1 + i_price)/(1 + i_base). The **higher-yield currency trades at a forward discount.**
- **Uncovered interest rate parity (UIRP)**: expected spot change = interest-rate differential (no risk premium). Often fails short-term ("forward rate bias" / carry trade profits).
- **Purchasing power parity (PPP)**: **relative PPP** — the currency of the higher-inflation country **depreciates** by the inflation differential. **Absolute PPP** rests on the law of one price.
- **International Fisher effect**: nominal rate differentials reflect **expected inflation** differentials (equal real rates).

> Memory hook: CIRP is the only one enforced by arbitrage and therefore always holds; the others are equilibrium tendencies.`,
    estimatedReadTime: 2,
    orderIndex: 5,
  },
  {
    id: "cfa-financial-reporting-reporting-quality-m01",
    topicId: "cfa-financial-reporting-reporting-quality",
    title: "Financial Reporting Quality",
    content: `**Reporting quality ≠ results (earnings) quality.** High *reporting* quality = decision-useful, faithful representation. High *earnings* quality = sustainable, high-return results. You can have high reporting quality reporting low (but honest) earnings.

## Quality spectrum (high → low)
1. GAAP, decision-useful, sustainable & adequate returns
2. GAAP, decision-useful, but **low earnings quality**
3. GAAP, but **biased/aggressive choices** ("earnings management")
4. GAAP, but **earnings management** (e.g. real activities like channel stuffing)
5. **Non-compliant** accounting
6. **Fraudulent** / fictitious transactions

## Red flags & motivations
- Motivations: meet **analyst forecasts**, hit **debt covenants**, boost **management compensation**.
- Aggressive choices: **early revenue recognition**, capitalizing costs that should be expensed, lengthening depreciable lives, understating reserves/allowances.
- **Beneish M-score** and accruals ratios help detect manipulation; large **accruals** relative to cash flow signal lower earnings quality.`,
    estimatedReadTime: 2,
    orderIndex: 5,
  },
  {
    id: "cfa-corporate-issuers-working-capital-m01",
    topicId: "cfa-corporate-issuers-working-capital",
    title: "Working Capital & Liquidity Management",
    content: `## The cash conversion cycle (CCC)
**CCC = DSO + DOH − DPO**
- **DSO** (days sales outstanding) = 365 / receivables turnover
- **DOH** (days of inventory on hand) = 365 / inventory turnover
- **DPO** (days payables outstanding) = 365 / payables turnover

A **shorter CCC** ties up less cash — better liquidity. A negative CCC (e.g. some retailers) means suppliers fund operations.

## Liquidity ratios
- **Current ratio** = current assets / current liabilities
- **Quick (acid-test)** = (cash + marketable securities + receivables) / current liabilities — excludes inventory
- **Cash ratio** = (cash + marketable securities) / current liabilities

## Short-term funding & investing
- Sources: lines of credit (committed > uncommitted > revolving), **commercial paper**, factoring receivables.
- **Cost of trade credit** if forgoing a discount "2/10 net 30": (1 + 0.02/0.98)^(365/20) − 1 ≈ **44.6%** — usually worth taking the discount.
- Invest excess cash in safe, liquid instruments; measure with **money-market yields** (bond-equivalent yield for comparability).`,
    estimatedReadTime: 2,
    orderIndex: 5,
  },
  {
    id: "cfa-equity-residual-income-valuation-m01",
    topicId: "cfa-equity-residual-income-valuation",
    title: "Residual Income & Private Company Valuation",
    content: `## Residual income (RI)
**RI = Net income − (Equity charge)** = NI − (r_e × Beginning book value of equity). It is the profit *after* charging for the cost of equity.

**Value = B₀ + Σ RI_t / (1+r)^t.** With constant growth:
**V₀ = B₀ + [(ROE − r) × B₀] / (r − g)**

- RI models recognize value **earlier** than DDM/FCF and rely less on a terminal value — useful for firms that **don't pay dividends** or have unpredictable cash flows.
- Weakness: relies on **clean-surplus accounting** and book-value/accounting quality.

## Private company valuation — three approaches
1. **Income** (free cash flow / capitalized cash flow / excess earnings)
2. **Market** (guideline public companies, guideline transactions, prior transactions)
3. **Asset-based** (net asset value)

Apply a **discount for lack of marketability (DLOM)** and a **discount for lack of control** (or a **control premium** for controlling stakes). Private-company discount rates are higher — add size and company-specific risk premia.`,
    estimatedReadTime: 2,
    orderIndex: 5,
  },
  {
    id: "cfa-fixed-income-spot-forward-rates-m01",
    topicId: "cfa-fixed-income-spot-forward-rates",
    title: "Spot, Forward & Par Rates",
    content: `## Definitions
- **Spot rate** z(t): YTM of a zero-coupon bond maturing at t. Price = Σ CF_t / (1 + z_t)^t.
- **Par rate**: the coupon rate that prices a bond at par given the spot curve.
- **Forward rate** f(a,b−a): rate agreed today for a loan starting at a, ending at b.

## The no-arbitrage link
**(1 + z_b)^b = (1 + z_a)^a × (1 + f(a, b−a))^(b−a)**

Example: (1+z₂)² = (1+z₁)(1+f(1,1)). So the implied **1y1y forward** = (1+z₂)²/(1+z₁) − 1.

## Curve shapes
- **Upward-sloping** spot curve ⇒ forward rates **above** spot rates; par < spot at long end.
- A bond's **return = spot rate** only if the curve is flat and unchanged ("rolling down the curve" adds return when upward-sloping and stable).
- **Forward rates are the market's break-even** future spot rates: you profit from buying long vs. rolling short only if future spots come in **below** today's forwards.`,
    estimatedReadTime: 2,
    orderIndex: 5,
  },
  {
    id: "cfa-derivatives-binomial-option-valuation-m01",
    topicId: "cfa-derivatives-binomial-option-valuation",
    title: "Binomial Option Valuation",
    content: `## One-period binomial model
Underlying S can move **up** to S·u or **down** to S·d. Value the option by **risk-neutral pricing** (no real probabilities needed):

**Risk-neutral up-probability:** π = (1 + r − d) / (u − d)

**Option value:** c₀ = [π·c_u + (1 − π)·c_d] / (1 + r)

where c_u, c_d are the option payoffs in each state.

## Key ideas
- **No-arbitrage = replication**: a portfolio of the underlying plus borrowing/lending reproduces the option payoff; the option must cost the same (the **hedge ratio** n = (c_u − c_d)/(S·u − S·d)).
- **Real probabilities don't appear** — investors' risk preferences are irrelevant once we hedge.
- **American options**: at each node compare the continuation value with the **early-exercise** value; early exercise can matter for **American puts** and calls on dividend-paying stocks.
- Multi-period: build the tree forward, then discount payoffs back node-by-node.`,
    estimatedReadTime: 2,
    orderIndex: 5,
  },
  {
    id: "cfa-alternative-investments-private-debt-m01",
    topicId: "cfa-alternative-investments-private-debt",
    title: "Private Debt & Direct Lending",
    content: `**Private debt** = loans/bonds extended directly to companies (often mid-market) outside public markets, typically by funds rather than banks.

## Main strategies
- **Direct lending** — senior, often **floating-rate**, secured loans to private firms; income-oriented.
- **Mezzanine debt** — subordinated, higher yield, often with **equity warrants** (hybrid).
- **Venture debt** — loans to venture-backed startups, alongside VC equity.
- **Distressed debt** — buying the debt of troubled firms, sometimes to convert to control ("loan-to-own").
- **Specialty/structured** — infrastructure debt, real estate debt, fund financing.

## Risk & return characteristics
- Return drivers: **interest income** + fees (origination, prepayment) + capital gains in distressed/mezzanine.
- Investors are compensated for **illiquidity** and **credit risk**; floating rates reduce duration risk.
- Key risks: **default/credit risk**, weakening **covenants** ("cov-lite"), illiquidity, and leverage at the fund level.
- Grew rapidly post-2008 as **bank lending retrenched** under tighter capital rules.`,
    estimatedReadTime: 2,
    orderIndex: 5,
  },
  {
    id: "cfa-portfolio-management-behavioral-finance-m01",
    topicId: "cfa-portfolio-management-behavioral-finance",
    title: "Behavioral Finance & Biases",
    content: `Behavioral finance relaxes the "rational economic man" assumption. Biases are split into **cognitive errors** (faulty reasoning — can be reduced with education/data) and **emotional biases** (feeling-based — harder to correct, accommodate them).

## Cognitive errors
- **Belief perseverance**: conservatism, **confirmation**, representativeness, illusion of control, hindsight.
- **Information processing**: **anchoring**, mental accounting, framing, availability.

## Emotional biases
- **Loss aversion** (losses hurt ~2× gains → **disposition effect**: sell winners, hold losers), **overconfidence**, **self-control**, **status quo**, **endowment**, **regret aversion**.

## Market-level effects
- **Prospect theory**: value is judged vs. a reference point; people are risk-averse in gains, risk-seeking in losses.
- Anomalies: **momentum**, **bubbles/crashes**, value/size effects, **herding**.
- Advisers should **moderate** cognitive biases and **adapt to** emotional biases when building the IPS.`,
    estimatedReadTime: 2,
    orderIndex: 5,
  },
];

export const expansionQuestions: Question[] = [
  // ── Ethics: Independence, Objectivity & Misrepresentation ──
  {
    id: "cfa-ethics-independence-objectivity-q01",
    topicId: "cfa-ethics-independence-objectivity",
    text: "An analyst is invited by a company she covers to tour a remote mine, with the company paying for chartered flights and lodging. To best comply with Standard I(B), she should:",
    optionA: "Accept, because issuer-paid travel is customary",
    optionB: "Pay for her own commercial travel and lodging where practical",
    optionC: "Accept but disclose the trip in her report",
    optionD: "Decline to cover the company entirely",
    correctOption: "B",
    explanation: "To preserve independence and objectivity, members should pay for their own travel when feasible rather than accept lavish issuer-paid arrangements that could bias their analysis.",
    orderIndex: 0,
  },
  {
    id: "cfa-ethics-independence-objectivity-q02",
    topicId: "cfa-ethics-independence-objectivity",
    text: "A client gives a portfolio manager a luxury watch as thanks for strong performance last year. Under the Standards, the manager should:",
    optionA: "Decline the gift outright",
    optionB: "Accept it without any further action",
    optionC: "Accept it but disclose it to the employer",
    optionD: "Accept only if its value is under $100",
    correctOption: "C",
    explanation: "Gifts from clients for past performance are permitted but must be disclosed to the employer, since future client relationships could create partiality.",
    orderIndex: 1,
  },
  {
    id: "cfa-ethics-independence-objectivity-q03",
    topicId: "cfa-ethics-independence-objectivity",
    text: "Including a respected economist's published GDP forecast in a report without citing the source most likely violates the Standard prohibiting:",
    optionA: "Misrepresentation through plagiarism",
    optionB: "Use of material nonpublic information",
    optionC: "Failure to maintain independence",
    optionD: "Misconduct",
    correctOption: "A",
    explanation: "Using another party's analysis, forecasts, or models without attribution is plagiarism, a form of misrepresentation under Standard I(C).",
    orderIndex: 2,
  },
  {
    id: "cfa-ethics-independence-objectivity-q04",
    topicId: "cfa-ethics-independence-objectivity",
    text: "Which statement to a prospective client most clearly violates Standard I(C) Misrepresentation?",
    optionA: "\"This bond's coupon is fixed at 5%.\"",
    optionB: "\"Our equity strategy has averaged 8% over ten years, net of fees.\"",
    optionC: "\"I guarantee this equity fund will return at least 10% annually.\"",
    optionD: "\"Past performance does not guarantee future results.\"",
    correctOption: "C",
    explanation: "Guaranteeing a specific return on a risky investment is a misrepresentation; only the contractual cash flows of certain instruments (e.g., a fixed coupon) may be stated as assured.",
    orderIndex: 3,
  },
  {
    id: "cfa-ethics-independence-objectivity-q05",
    topicId: "cfa-ethics-independence-objectivity",
    text: "A sell-side analyst's firm is underwriting an IPO for a company the analyst rates. The best way to protect objectivity is to:",
    optionA: "Issue only buy recommendations during the offering period",
    optionB: "Maintain firewalls between research and investment banking",
    optionC: "Have investment banking approve the research rating",
    optionD: "Suspend coverage permanently",
    correctOption: "B",
    explanation: "Information barriers (firewalls) between research and investment banking reduce pressure on analysts to bias ratings to win or support banking business.",
    orderIndex: 4,
  },
  {
    id: "cfa-ethics-independence-objectivity-q06",
    topicId: "cfa-ethics-independence-objectivity",
    text: "Using factual macroeconomic data published by a national statistics agency without attribution is:",
    optionA: "Always a violation of the plagiarism prohibition",
    optionB: "Permitted, as recognized factual/statistical data need not be cited",
    optionC: "Permitted only with the agency's written consent",
    optionD: "A violation of the duty of loyalty to employers",
    correctOption: "B",
    explanation: "Members may use recognized factual or statistical information from sources such as government agencies without attribution; the plagiarism rule targets others' analysis and opinions.",
    orderIndex: 5,
  },
  {
    id: "cfa-ethics-independence-objectivity-q07",
    topicId: "cfa-ethics-independence-objectivity",
    text: "A credit rating agency lets the team that negotiates fees with issuers also determine the credit ratings. This most likely compromises:",
    optionA: "Fair dealing among clients",
    optionB: "Independence and objectivity of the ratings",
    optionC: "Preservation of confidentiality",
    optionD: "Suitability",
    correctOption: "B",
    explanation: "Allowing fee negotiation and rating determination to mix creates a conflict that threatens the independence and objectivity of the ratings.",
    orderIndex: 6,
  },
  {
    id: "cfa-ethics-independence-objectivity-q08",
    topicId: "cfa-ethics-independence-objectivity",
    text: "A candidate lists 'CFA Level II candidate' but has not registered for the next exam. This most likely violates the Standard on:",
    optionA: "Reference to the CFA designation / candidacy misrepresentation",
    optionB: "Independence and objectivity",
    optionC: "Priority of transactions",
    optionD: "Diligence and reasonable basis",
    correctOption: "A",
    explanation: "One may claim candidacy only when actively registered/enrolled for the next sitting; otherwise it misrepresents the candidate's status.",
    orderIndex: 7,
  },
  {
    id: "cfa-ethics-independence-objectivity-q09",
    topicId: "cfa-ethics-independence-objectivity",
    text: "An analyst accepts a modest meal and a branded pen at a company's investor day. This is most likely:",
    optionA: "A violation requiring disclosure to clients",
    optionB: "Acceptable, as token items of minimal value are unlikely to impair objectivity",
    optionC: "A violation of the prohibition on gifts from clients",
    optionD: "Permitted only if reciprocated",
    correctOption: "B",
    explanation: "Modest, token benefits that could not reasonably be expected to influence judgement are acceptable; the concern is with lavish or influence-seeking arrangements.",
    orderIndex: 8,
  },
  {
    id: "cfa-ethics-independence-objectivity-q10",
    topicId: "cfa-ethics-independence-objectivity",
    text: "A manager's firm pressures him to maintain a favorable rating on a poorly performing affiliate. Maintaining the rating against his analysis would primarily violate the duty to:",
    optionA: "Preserve confidentiality",
    optionB: "Maintain independence and objectivity",
    optionC: "Ensure fair dealing",
    optionD: "Disclose referral fees",
    correctOption: "B",
    explanation: "Allowing internal pressure to override an objective, well-founded opinion violates Standard I(B) independence and objectivity.",
    orderIndex: 9,
  },
  {
    id: "cfa-ethics-independence-objectivity-q11",
    topicId: "cfa-ethics-independence-objectivity",
    text: "Reusing your own firm's prior research reports in a new report, with the firm's permission and consistent with policy, is:",
    optionA: "Plagiarism in all cases",
    optionB: "Generally acceptable; using one's own employer's work product is not plagiarism",
    optionC: "Only acceptable if each prior author consents individually",
    optionD: "A violation of independence",
    correctOption: "B",
    explanation: "Drawing on work produced within one's own firm, per firm policy, is not plagiarism; plagiarism concerns passing off others' external work as one's own.",
    orderIndex: 10,
  },
  {
    id: "cfa-ethics-independence-objectivity-q12",
    topicId: "cfa-ethics-independence-objectivity",
    text: "An issuer offers to pay an analyst a bonus tied to a favorable report. The analyst should:",
    optionA: "Accept if disclosed to clients",
    optionB: "Decline the arrangement",
    optionC: "Accept if the report is accurate",
    optionD: "Accept but cap the bonus amount",
    correctOption: "B",
    explanation: "Compensation contingent on the content/conclusion of research is a clear threat to independence and objectivity and should be declined.",
    orderIndex: 11,
  },

  // ── Quant: Common Probability Distributions ──
  {
    id: "cfa-quantitative-methods-probability-distributions-q01",
    topicId: "cfa-quantitative-methods-probability-distributions",
    text: "For a binomial random variable with n = 20 and p = 0.3, the expected number of successes is:",
    optionA: "3",
    optionB: "6",
    optionC: "14",
    optionD: "0.3",
    correctOption: "B",
    explanation: "The mean of a binomial distribution is np = 20 × 0.3 = 6.",
    orderIndex: 0,
  },
  {
    id: "cfa-quantitative-methods-probability-distributions-q02",
    topicId: "cfa-quantitative-methods-probability-distributions",
    text: "The variance of a binomial variable with n = 20 and p = 0.3 is:",
    optionA: "6.0",
    optionB: "4.2",
    optionC: "2.05",
    optionD: "14.0",
    correctOption: "B",
    explanation: "Binomial variance = np(1 − p) = 20 × 0.3 × 0.7 = 4.2.",
    orderIndex: 1,
  },
  {
    id: "cfa-quantitative-methods-probability-distributions-q03",
    topicId: "cfa-quantitative-methods-probability-distributions",
    text: "Approximately what percentage of observations from a normal distribution lie within ±1.96 standard deviations of the mean?",
    optionA: "68%",
    optionB: "90%",
    optionC: "95%",
    optionD: "99%",
    correctOption: "C",
    explanation: "About 95% of a normal distribution lies within ±1.96σ; ±1.65σ captures 90% and ±2.58σ captures 99%.",
    orderIndex: 2,
  },
  {
    id: "cfa-quantitative-methods-probability-distributions-q04",
    topicId: "cfa-quantitative-methods-probability-distributions",
    text: "Why is the lognormal distribution often used to model asset prices?",
    optionA: "It is symmetric around zero",
    optionB: "It is bounded below by zero and right-skewed",
    optionC: "It can take negative values",
    optionD: "It has constant variance",
    correctOption: "B",
    explanation: "Prices cannot be negative; the lognormal distribution is bounded at zero and right-skewed, matching the behavior of asset prices.",
    orderIndex: 3,
  },
  {
    id: "cfa-quantitative-methods-probability-distributions-q05",
    topicId: "cfa-quantitative-methods-probability-distributions",
    text: "A portfolio has expected return 12% and standard deviation 18%. Using Roy's safety-first criterion with a threshold return of 3%, the safety-first ratio is:",
    optionA: "0.50",
    optionB: "0.83",
    optionC: "0.67",
    optionD: "1.50",
    correctOption: "A",
    explanation: "SFRatio = (12% − 3%) / 18% = 9 / 18 = 0.50. The optimal portfolio maximizes this ratio.",
    orderIndex: 4,
  },
  {
    id: "cfa-quantitative-methods-probability-distributions-q06",
    topicId: "cfa-quantitative-methods-probability-distributions",
    text: "The Sharpe ratio is a special case of the safety-first ratio when the threshold return equals the:",
    optionA: "Market return",
    optionB: "Risk-free rate",
    optionC: "Mean return",
    optionD: "Median return",
    correctOption: "B",
    explanation: "When the minimum acceptable (threshold) return is set to the risk-free rate, Roy's safety-first ratio is identical to the Sharpe ratio.",
    orderIndex: 5,
  },
  {
    id: "cfa-quantitative-methods-probability-distributions-q07",
    topicId: "cfa-quantitative-methods-probability-distributions",
    text: "A stock return is normally distributed with mean 10% and standard deviation 5%. The z-value for a 2% return is:",
    optionA: "−1.6",
    optionB: "+1.6",
    optionC: "−0.4",
    optionD: "+0.4",
    correctOption: "A",
    explanation: "z = (x − μ)/σ = (2% − 10%)/5% = −8/5 = −1.6.",
    orderIndex: 6,
  },
  {
    id: "cfa-quantitative-methods-probability-distributions-q08",
    topicId: "cfa-quantitative-methods-probability-distributions",
    text: "A key property of the continuous uniform distribution over [a, b] is that:",
    optionA: "Probability density is highest at the mean",
    optionB: "Probability density is constant across the interval",
    optionC: "It is right-skewed",
    optionD: "Its variance is zero",
    correctOption: "B",
    explanation: "The continuous uniform distribution assigns equal (constant) probability density across its interval [a, b].",
    orderIndex: 7,
  },
  {
    id: "cfa-quantitative-methods-probability-distributions-q09",
    topicId: "cfa-quantitative-methods-probability-distributions",
    text: "If continuously compounded returns are normally distributed, then the corresponding price relatives (1 + holding-period return) are:",
    optionA: "Normally distributed",
    optionB: "Lognormally distributed",
    optionC: "Uniformly distributed",
    optionD: "Binomially distributed",
    correctOption: "B",
    explanation: "When continuously compounded returns are normal, the gross return / price relative follows a lognormal distribution.",
    orderIndex: 8,
  },
  {
    id: "cfa-quantitative-methods-probability-distributions-q10",
    topicId: "cfa-quantitative-methods-probability-distributions",
    text: "A 'tracking error' constraint that limits the probability of underperforming a benchmark by more than a set amount is an application of:",
    optionA: "The central limit theorem",
    optionB: "Shortfall risk / safety-first concepts",
    optionC: "Bayes' formula",
    optionD: "The binomial distribution",
    correctOption: "B",
    explanation: "Limiting the probability of falling below a threshold (shortfall risk) is a direct application of safety-first / downside-risk thinking.",
    orderIndex: 9,
  },
  {
    id: "cfa-quantitative-methods-probability-distributions-q11",
    topicId: "cfa-quantitative-methods-probability-distributions",
    text: "Which distribution would best model the number of bonds defaulting out of 50 independent issuers, each with a 4% default probability?",
    optionA: "Normal",
    optionB: "Lognormal",
    optionC: "Binomial",
    optionD: "Continuous uniform",
    correctOption: "C",
    explanation: "A count of successes/defaults over a fixed number of independent trials with constant probability is binomial.",
    orderIndex: 10,
  },
  {
    id: "cfa-quantitative-methods-probability-distributions-q12",
    topicId: "cfa-quantitative-methods-probability-distributions",
    text: "Standardizing a normal random variable produces a distribution with:",
    optionA: "Mean 1 and standard deviation 0",
    optionB: "Mean 0 and standard deviation 1",
    optionC: "Mean 0 and variance 0",
    optionD: "Mean equal to the original mean",
    correctOption: "B",
    explanation: "The standard normal distribution, obtained via z = (x − μ)/σ, has a mean of 0 and a standard deviation (and variance) of 1.",
    orderIndex: 11,
  },

  // ── Economics: Currency Parity Conditions ──
  {
    id: "cfa-economics-currency-parity-q01",
    topicId: "cfa-economics-currency-parity",
    text: "Which parity condition is enforced by arbitrage and therefore essentially always holds?",
    optionA: "Uncovered interest rate parity",
    optionB: "Covered interest rate parity",
    optionC: "Relative purchasing power parity",
    optionD: "The international Fisher effect",
    correctOption: "B",
    explanation: "Covered interest rate parity is enforced by riskless arbitrage using forward contracts, so it holds continuously; the others are equilibrium tendencies.",
    orderIndex: 0,
  },
  {
    id: "cfa-economics-currency-parity-q02",
    topicId: "cfa-economics-currency-parity",
    text: "Under covered interest rate parity, the currency with the higher interest rate will trade at a forward:",
    optionA: "Premium",
    optionB: "Discount",
    optionC: "Rate equal to spot",
    optionD: "Rate that is indeterminate",
    correctOption: "B",
    explanation: "The higher-yielding currency trades at a forward discount, exactly offsetting its interest-rate advantage so no arbitrage profit exists.",
    orderIndex: 1,
  },
  {
    id: "cfa-economics-currency-parity-q03",
    topicId: "cfa-economics-currency-parity",
    text: "Relative purchasing power parity predicts that a country with persistently higher inflation will see its currency:",
    optionA: "Appreciate by the inflation differential",
    optionB: "Depreciate by the inflation differential",
    optionC: "Remain unchanged",
    optionD: "Appreciate by the interest differential",
    correctOption: "B",
    explanation: "Under relative PPP, the higher-inflation country's currency depreciates by approximately the inflation differential, preserving relative purchasing power.",
    orderIndex: 2,
  },
  {
    id: "cfa-economics-currency-parity-q04",
    topicId: "cfa-economics-currency-parity",
    text: "Uncovered interest rate parity differs from covered interest rate parity primarily because it:",
    optionA: "Uses forward contracts to eliminate currency risk",
    optionB: "Relies on the expected future spot rate and carries currency risk",
    optionC: "Assumes equal inflation rates",
    optionD: "Always holds in the short run",
    correctOption: "B",
    explanation: "UIRP is based on the expected future spot rate without hedging, so it carries currency risk and is not enforced by arbitrage—hence it often fails short-term.",
    orderIndex: 3,
  },
  {
    id: "cfa-economics-currency-parity-q05",
    topicId: "cfa-economics-currency-parity",
    text: "The international Fisher effect states that the difference in nominal interest rates between two countries equals the difference in their expected:",
    optionA: "Real interest rates",
    optionB: "Inflation rates",
    optionC: "GDP growth rates",
    optionD: "Current account balances",
    correctOption: "B",
    explanation: "The international Fisher effect assumes equal real rates across countries, so nominal rate differences reflect expected inflation differences.",
    orderIndex: 4,
  },
  {
    id: "cfa-economics-currency-parity-q06",
    topicId: "cfa-economics-currency-parity",
    text: "The persistent profitability of the carry trade is evidence that which condition often fails in the short run?",
    optionA: "Covered interest rate parity",
    optionB: "Uncovered interest rate parity",
    optionC: "Absolute purchasing power parity",
    optionD: "The law of one price for forwards",
    correctOption: "B",
    explanation: "Carry-trade profits (borrowing low-yield, investing high-yield currencies) imply UIRP—which predicts no expected gain—does not hold short-term.",
    orderIndex: 5,
  },
  {
    id: "cfa-economics-currency-parity-q07",
    topicId: "cfa-economics-currency-parity",
    text: "Absolute purchasing power parity is built directly on the:",
    optionA: "Law of one price",
    optionB: "Quantity theory of money",
    optionC: "Marshall-Lerner condition",
    optionD: "Fisher equation",
    correctOption: "A",
    explanation: "Absolute PPP extends the law of one price (identical goods cost the same everywhere when priced in a common currency) to national price levels.",
    orderIndex: 6,
  },
  {
    id: "cfa-economics-currency-parity-q08",
    topicId: "cfa-economics-currency-parity",
    text: "Spot USD/EUR is 1.20 and the 1-year forward is 1.176 (USD per EUR). The euro is trading at a forward:",
    optionA: "Premium, implying lower euro interest rates",
    optionB: "Discount, implying higher euro interest rates",
    optionC: "Premium, implying higher euro interest rates",
    optionD: "Discount, implying lower euro interest rates",
    correctOption: "B",
    explanation: "The euro buys fewer dollars forward (1.176 < 1.20), so it is at a forward discount—consistent with euro interest rates being higher than USD rates under CIRP.",
    orderIndex: 7,
  },
  {
    id: "cfa-economics-currency-parity-q09",
    topicId: "cfa-economics-currency-parity",
    text: "If covered interest rate parity is violated, market participants can earn a riskless profit through:",
    optionA: "Covered interest arbitrage",
    optionB: "A carry trade",
    optionC: "Triangular arbitrage only",
    optionD: "Speculation on inflation",
    correctOption: "A",
    explanation: "When CIRP fails, covered interest arbitrage (borrow one currency, convert spot, invest, and lock in the forward) earns a riskless profit, quickly restoring parity.",
    orderIndex: 8,
  },
  {
    id: "cfa-economics-currency-parity-q10",
    topicId: "cfa-economics-currency-parity",
    text: "Combining relative PPP with uncovered interest rate parity implies that real exchange rates are expected to:",
    optionA: "Rise steadily over time",
    optionB: "Remain constant",
    optionC: "Fall steadily over time",
    optionD: "Equal nominal exchange rates",
    correctOption: "B",
    explanation: "When relative PPP and UIRP both hold, expected changes in nominal rates offset inflation differentials, leaving the real exchange rate expected to be constant.",
    orderIndex: 9,
  },
  {
    id: "cfa-economics-currency-parity-q11",
    topicId: "cfa-economics-currency-parity",
    text: "Which factor is NOT a determinant emphasized by the parity conditions for exchange rates?",
    optionA: "Interest rate differentials",
    optionB: "Expected inflation differentials",
    optionC: "Corporate dividend policy",
    optionD: "Expected future spot rates",
    correctOption: "C",
    explanation: "The parity framework links exchange rates to interest rates, inflation, and expected spot rates—not to firms' dividend policies.",
    orderIndex: 10,
  },
  {
    id: "cfa-economics-currency-parity-q12",
    topicId: "cfa-economics-currency-parity",
    text: "A 'forward rate bias' refers to the empirical finding that the forward rate is a:",
    optionA: "Perfect predictor of the future spot rate",
    optionB: "Biased predictor, with high-yield currencies tending to outperform UIRP's prediction",
    optionC: "Predictor only of inflation, not exchange rates",
    optionD: "Measure of covered arbitrage profit",
    correctOption: "B",
    explanation: "The forward rate bias is the observation that forwards are biased predictors of future spot rates—high-yield currencies often do not depreciate as UIRP predicts, enabling carry profits.",
    orderIndex: 11,
  },

  // ── FRA: Financial Reporting Quality ──
  {
    id: "cfa-financial-reporting-reporting-quality-q01",
    topicId: "cfa-financial-reporting-reporting-quality",
    text: "The distinction between 'reporting quality' and 'earnings quality' is best described as:",
    optionA: "They are identical concepts",
    optionB: "Reporting quality refers to decision-usefulness of information; earnings quality refers to sustainability of results",
    optionC: "Reporting quality refers to the level of profit; earnings quality refers to disclosure",
    optionD: "Earnings quality refers to GAAP compliance only",
    correctOption: "B",
    explanation: "Reporting quality concerns the decision-usefulness and faithfulness of the information; earnings (results) quality concerns whether the reported earnings are sustainable and adequate.",
    orderIndex: 0,
  },
  {
    id: "cfa-financial-reporting-reporting-quality-q02",
    topicId: "cfa-financial-reporting-reporting-quality",
    text: "A firm can have HIGH reporting quality while having LOW earnings quality when it:",
    optionA: "Uses fraudulent transactions",
    optionB: "Faithfully reports genuinely poor, unsustainable results",
    optionC: "Capitalizes operating expenses",
    optionD: "Recognizes revenue prematurely",
    correctOption: "B",
    explanation: "High reporting quality means the information honestly represents the economics—even when the underlying earnings are low or unsustainable (low earnings quality).",
    orderIndex: 1,
  },
  {
    id: "cfa-financial-reporting-reporting-quality-q03",
    topicId: "cfa-financial-reporting-reporting-quality",
    text: "Which is an example of 'earnings management' through aggressive accounting choices rather than outright fraud?",
    optionA: "Recording fictitious sales",
    optionB: "Lengthening the estimated useful lives of depreciable assets to boost income",
    optionC: "Creating fake invoices",
    optionD: "Omitting a known liability entirely",
    correctOption: "B",
    explanation: "Stretching depreciable lives is an aggressive but within-GAAP estimate change used to manage earnings, distinct from fraudulent, non-GAAP fabrications.",
    orderIndex: 2,
  },
  {
    id: "cfa-financial-reporting-reporting-quality-q04",
    topicId: "cfa-financial-reporting-reporting-quality",
    text: "A high level of accruals relative to cash flow from operations generally signals:",
    optionA: "Higher earnings quality",
    optionB: "Lower earnings quality",
    optionC: "Higher reporting quality",
    optionD: "No information about quality",
    correctOption: "B",
    explanation: "Large accruals relative to cash flows indicate earnings rely heavily on estimates/accruals rather than cash, which is associated with lower (less persistent) earnings quality.",
    orderIndex: 3,
  },
  {
    id: "cfa-financial-reporting-reporting-quality-q05",
    topicId: "cfa-financial-reporting-reporting-quality",
    text: "Which is a common MOTIVATION for management to manipulate earnings?",
    optionA: "To increase audit fees",
    optionB: "To meet analyst forecasts or debt covenant thresholds",
    optionC: "To reduce executive compensation",
    optionD: "To lower the stock price",
    correctOption: "B",
    explanation: "Managers are often motivated to manipulate earnings to meet/beat analyst expectations, avoid breaching debt covenants, or maximize compensation tied to results.",
    orderIndex: 4,
  },
  {
    id: "cfa-financial-reporting-reporting-quality-q06",
    topicId: "cfa-financial-reporting-reporting-quality",
    text: "On the spectrum of financial reporting quality, which is the LOWEST quality?",
    optionA: "GAAP-compliant but with biased estimates",
    optionB: "GAAP-compliant with low earnings quality",
    optionC: "Fraudulent / fictitious transactions",
    optionD: "GAAP-compliant and decision-useful",
    correctOption: "C",
    explanation: "Fabricated or fraudulent transactions sit at the bottom of the quality spectrum, below merely biased-but-compliant or non-compliant-but-non-fraudulent reporting.",
    orderIndex: 5,
  },
  {
    id: "cfa-financial-reporting-reporting-quality-q07",
    topicId: "cfa-financial-reporting-reporting-quality",
    text: "Capitalizing a cost that should be expensed will, in the year incurred, tend to:",
    optionA: "Decrease net income and decrease assets",
    optionB: "Increase net income and increase assets",
    optionC: "Decrease net income and increase liabilities",
    optionD: "Have no effect on net income",
    correctOption: "B",
    explanation: "Improperly capitalizing an expense moves it to the balance sheet, raising assets and shifting the cost out of the current period—boosting current net income.",
    orderIndex: 6,
  },
  {
    id: "cfa-financial-reporting-reporting-quality-q08",
    topicId: "cfa-financial-reporting-reporting-quality",
    text: "The Beneish M-score is primarily used to:",
    optionA: "Estimate a firm's cost of capital",
    optionB: "Assess the probability of earnings manipulation",
    optionC: "Forecast dividend growth",
    optionD: "Measure liquidity risk",
    correctOption: "B",
    explanation: "The Beneish M-score combines accounting ratios into a probability score for the likelihood that a firm has manipulated its earnings.",
    orderIndex: 7,
  },
  {
    id: "cfa-financial-reporting-reporting-quality-q09",
    topicId: "cfa-financial-reporting-reporting-quality",
    text: "'Channel stuffing' (pushing excess product to distributors near period-end) is an example of:",
    optionA: "Conservative accounting",
    optionB: "Real-activities earnings management",
    optionC: "A change in accounting principle",
    optionD: "Improved earnings quality",
    correctOption: "B",
    explanation: "Channel stuffing manipulates reported results through real operating decisions (accelerating shipments), a form of real-activities earnings management.",
    orderIndex: 8,
  },
  {
    id: "cfa-financial-reporting-reporting-quality-q10",
    topicId: "cfa-financial-reporting-reporting-quality",
    text: "Understating the allowance for doubtful accounts will most likely:",
    optionA: "Decrease current-period earnings",
    optionB: "Increase current-period earnings",
    optionC: "Have no effect on earnings",
    optionD: "Increase reported liabilities",
    correctOption: "B",
    explanation: "A smaller bad-debt allowance means lower expense and higher net receivables, increasing current-period earnings—an aggressive choice that lowers earnings quality.",
    orderIndex: 9,
  },
  {
    id: "cfa-financial-reporting-reporting-quality-q11",
    topicId: "cfa-financial-reporting-reporting-quality",
    text: "Which condition from the 'fraud triangle' relates to weak internal controls or board oversight?",
    optionA: "Incentive/pressure",
    optionB: "Opportunity",
    optionC: "Rationalization",
    optionD: "Materiality",
    correctOption: "B",
    explanation: "Opportunity—often arising from weak controls or governance—is the leg of the fraud triangle that enables manipulation, alongside incentive and rationalization.",
    orderIndex: 10,
  },
  {
    id: "cfa-financial-reporting-reporting-quality-q12",
    topicId: "cfa-financial-reporting-reporting-quality",
    text: "Conservative accounting choices (e.g., expensing rather than capitalizing) are best described as:",
    optionA: "Always indicating high earnings quality",
    optionB: "A bias that can also reduce decision-usefulness, even though it understates current income",
    optionC: "A form of fraud",
    optionD: "Required under IFRS but banned under US GAAP",
    correctOption: "B",
    explanation: "Although conservatism understates current income, persistent bias in either direction reduces the faithful representation and decision-usefulness of the statements.",
    orderIndex: 11,
  },

  // ── Corporate Issuers: Working Capital & Liquidity Management ──
  {
    id: "cfa-corporate-issuers-working-capital-q01",
    topicId: "cfa-corporate-issuers-working-capital",
    text: "The cash conversion cycle is calculated as:",
    optionA: "DSO + DOH − DPO",
    optionB: "DSO − DOH + DPO",
    optionC: "DPO + DOH − DSO",
    optionD: "DSO + DPO − DOH",
    correctOption: "A",
    explanation: "Cash conversion cycle = Days Sales Outstanding + Days of Inventory on Hand − Days Payables Outstanding.",
    orderIndex: 0,
  },
  {
    id: "cfa-corporate-issuers-working-capital-q02",
    topicId: "cfa-corporate-issuers-working-capital",
    text: "All else equal, a shorter cash conversion cycle indicates:",
    optionA: "Weaker liquidity",
    optionB: "More cash tied up in operations",
    optionC: "Stronger liquidity and less financing needed",
    optionD: "Higher inventory levels",
    correctOption: "C",
    explanation: "A shorter CCC means the firm converts inputs to cash faster, tying up less cash in working capital and improving liquidity.",
    orderIndex: 1,
  },
  {
    id: "cfa-corporate-issuers-working-capital-q03",
    topicId: "cfa-corporate-issuers-working-capital",
    text: "The quick (acid-test) ratio differs from the current ratio by excluding:",
    optionA: "Cash",
    optionB: "Receivables",
    optionC: "Inventory",
    optionD: "Marketable securities",
    correctOption: "C",
    explanation: "The quick ratio excludes inventory (the least liquid current asset), focusing on cash, marketable securities, and receivables.",
    orderIndex: 2,
  },
  {
    id: "cfa-corporate-issuers-working-capital-q04",
    topicId: "cfa-corporate-issuers-working-capital",
    text: "A company with credit terms '2/10 net 30' that forgoes the discount and pays on day 30 incurs an implicit annualized cost closest to:",
    optionA: "2%",
    optionB: "24%",
    optionC: "45%",
    optionD: "73%",
    correctOption: "C",
    explanation: "Cost = (1 + 0.02/0.98)^(365/20) − 1 ≈ 44.6%, so forgoing the discount is expensive financing.",
    orderIndex: 3,
  },
  {
    id: "cfa-corporate-issuers-working-capital-q05",
    topicId: "cfa-corporate-issuers-working-capital",
    text: "Days of inventory on hand (DOH) is calculated as:",
    optionA: "365 × inventory turnover",
    optionB: "365 / inventory turnover",
    optionC: "Inventory / sales",
    optionD: "Cost of goods sold / inventory",
    correctOption: "B",
    explanation: "DOH = 365 / inventory turnover, where inventory turnover = COGS / average inventory.",
    orderIndex: 4,
  },
  {
    id: "cfa-corporate-issuers-working-capital-q06",
    topicId: "cfa-corporate-issuers-working-capital",
    text: "Which short-term funding source is generally considered the MOST reliable for a borrower?",
    optionA: "An uncommitted line of credit",
    optionB: "A committed (revolving) line of credit",
    optionC: "Commercial paper for a low-rated issuer",
    optionD: "Trade credit from a single supplier",
    correctOption: "B",
    explanation: "A committed/revolving line obligates the lender to provide funds (for a fee), making it more reliable than an uncommitted line that can be withdrawn.",
    orderIndex: 5,
  },
  {
    id: "cfa-corporate-issuers-working-capital-q07",
    topicId: "cfa-corporate-issuers-working-capital",
    text: "A negative cash conversion cycle, common at some large retailers, implies that:",
    optionA: "The firm is insolvent",
    optionB: "Suppliers effectively finance the firm's operations",
    optionC: "The firm holds excessive inventory",
    optionD: "Receivables are collected very slowly",
    correctOption: "B",
    explanation: "A negative CCC means the firm collects cash from customers before paying suppliers, so suppliers' trade credit funds operations.",
    orderIndex: 6,
  },
  {
    id: "cfa-corporate-issuers-working-capital-q08",
    topicId: "cfa-corporate-issuers-working-capital",
    text: "When managing a short-term investment portfolio for excess cash, the PRIMARY objective is typically:",
    optionA: "Maximizing yield regardless of risk",
    optionB: "Safety and liquidity of principal",
    optionC: "Maximizing duration",
    optionD: "Currency speculation",
    correctOption: "B",
    explanation: "Short-term cash management prioritizes preservation of principal and liquidity over yield, since the funds may be needed on short notice.",
    orderIndex: 7,
  },
  {
    id: "cfa-corporate-issuers-working-capital-q09",
    topicId: "cfa-corporate-issuers-working-capital",
    text: "Factoring accounts receivable involves:",
    optionA: "Borrowing against inventory",
    optionB: "Selling receivables to a third party for immediate cash",
    optionC: "Extending customer payment terms",
    optionD: "Issuing commercial paper",
    correctOption: "B",
    explanation: "Factoring is the sale of receivables (usually at a discount) to a factor in exchange for immediate cash, improving liquidity.",
    orderIndex: 8,
  },
  {
    id: "cfa-corporate-issuers-working-capital-q10",
    topicId: "cfa-corporate-issuers-working-capital",
    text: "Days payables outstanding increasing while sales are flat most likely indicates the firm is:",
    optionA: "Paying suppliers faster",
    optionB: "Stretching payments to suppliers, conserving cash",
    optionC: "Collecting receivables faster",
    optionD: "Reducing inventory",
    correctOption: "B",
    explanation: "A rising DPO means the firm takes longer to pay suppliers, which conserves cash—though excessive stretching can harm supplier relationships.",
    orderIndex: 9,
  },
  {
    id: "cfa-corporate-issuers-working-capital-q11",
    topicId: "cfa-corporate-issuers-working-capital",
    text: "The cash ratio is the most conservative liquidity measure because it includes only:",
    optionA: "Cash and marketable securities relative to current liabilities",
    optionB: "Cash, receivables, and inventory",
    optionC: "All current assets",
    optionD: "Working capital",
    correctOption: "A",
    explanation: "The cash ratio counts only cash and (highly liquid) marketable securities against current liabilities, the strictest of the common liquidity ratios.",
    orderIndex: 10,
  },
  {
    id: "cfa-corporate-issuers-working-capital-q12",
    topicId: "cfa-corporate-issuers-working-capital",
    text: "A firm reduces its DSO from 45 to 30 days while holding DOH and DPO constant. The cash conversion cycle will:",
    optionA: "Increase by 15 days",
    optionB: "Decrease by 15 days",
    optionC: "Remain unchanged",
    optionD: "Decrease by 45 days",
    correctOption: "B",
    explanation: "Since CCC = DSO + DOH − DPO, a 15-day fall in DSO with the other terms constant lowers the CCC by 15 days.",
    orderIndex: 11,
  },

  // ── Equity: Residual Income & Private Company Valuation ──
  {
    id: "cfa-equity-residual-income-valuation-q01",
    topicId: "cfa-equity-residual-income-valuation",
    text: "Residual income for a period is best defined as net income minus a charge for:",
    optionA: "The cost of debt",
    optionB: "The cost of equity capital",
    optionC: "Operating expenses",
    optionD: "Taxes",
    correctOption: "B",
    explanation: "Residual income = net income − (required return on equity × beginning book value of equity); it is income after charging for equity capital.",
    orderIndex: 0,
  },
  {
    id: "cfa-equity-residual-income-valuation-q02",
    topicId: "cfa-equity-residual-income-valuation",
    text: "A firm has beginning book value of equity of $50, net income of $8, and a required return on equity of 12%. Its residual income is:",
    optionA: "$8.00",
    optionB: "$6.00",
    optionC: "$2.00",
    optionD: "$0.96",
    correctOption: "C",
    explanation: "Equity charge = 12% × $50 = $6. Residual income = $8 − $6 = $2.",
    orderIndex: 1,
  },
  {
    id: "cfa-equity-residual-income-valuation-q03",
    topicId: "cfa-equity-residual-income-valuation",
    text: "A key advantage of the residual income model over the dividend discount model is that it:",
    optionA: "Requires no estimate of the cost of equity",
    optionB: "Recognizes value earlier and relies less on a terminal value",
    optionC: "Ignores book value entirely",
    optionD: "Works only for dividend-paying firms",
    correctOption: "B",
    explanation: "RI models capture much of the value in the current book value and near-term residual income, reducing dependence on a hard-to-estimate terminal value.",
    orderIndex: 2,
  },
  {
    id: "cfa-equity-residual-income-valuation-q04",
    topicId: "cfa-equity-residual-income-valuation",
    text: "The single-stage residual income model gives V₀ = B₀ + [(ROE − r) × B₀] / (r − g). A firm adds value above book when:",
    optionA: "ROE < r",
    optionB: "ROE = r",
    optionC: "ROE > r",
    optionD: "g > r",
    correctOption: "C",
    explanation: "Value exceeds book value only when ROE exceeds the required return r; if ROE = r, value equals book value.",
    orderIndex: 3,
  },
  {
    id: "cfa-equity-residual-income-valuation-q05",
    topicId: "cfa-equity-residual-income-valuation",
    text: "A major accounting concern when applying the residual income model is that it relies on:",
    optionA: "Cash flow forecasts only",
    optionB: "Clean-surplus accounting and book-value quality",
    optionC: "Dividend policy",
    optionD: "Market multiples",
    correctOption: "B",
    explanation: "RI models assume clean-surplus accounting (all income flows through retained earnings) and are sensitive to the quality of reported book value.",
    orderIndex: 4,
  },
  {
    id: "cfa-equity-residual-income-valuation-q06",
    topicId: "cfa-equity-residual-income-valuation",
    text: "Which is one of the three broad approaches to private company valuation?",
    optionA: "The arbitrage approach",
    optionB: "The market (guideline) approach",
    optionC: "The duration approach",
    optionD: "The parity approach",
    correctOption: "B",
    explanation: "Private company valuation uses income, market (guideline public companies/transactions), and asset-based approaches.",
    orderIndex: 5,
  },
  {
    id: "cfa-equity-residual-income-valuation-q07",
    topicId: "cfa-equity-residual-income-valuation",
    text: "A discount for lack of marketability (DLOM) is applied to private company values because:",
    optionA: "Private firms always have higher growth",
    optionB: "Private equity interests cannot be sold quickly without price concession",
    optionC: "Private firms pay higher dividends",
    optionD: "Private firms have lower tax rates",
    correctOption: "B",
    explanation: "Private interests are illiquid and hard to sell promptly, so a DLOM reduces value relative to comparable, freely traded public shares.",
    orderIndex: 6,
  },
  {
    id: "cfa-equity-residual-income-valuation-q08",
    topicId: "cfa-equity-residual-income-valuation",
    text: "When valuing a controlling interest in a private firm using guideline public companies (which trade as minority interests), an analyst would typically add a:",
    optionA: "Discount for lack of control",
    optionB: "Control premium",
    optionC: "Liquidity discount",
    optionD: "Size discount",
    correctOption: "B",
    explanation: "Public minority prices lack control; valuing a controlling stake requires adding a control premium to reflect the power to direct the firm.",
    orderIndex: 7,
  },
  {
    id: "cfa-equity-residual-income-valuation-q09",
    topicId: "cfa-equity-residual-income-valuation",
    text: "The 'excess earnings method' of private company valuation is a form of which approach?",
    optionA: "Market approach",
    optionB: "Asset-based approach",
    optionC: "Income approach",
    optionD: "Option-pricing approach",
    correctOption: "C",
    explanation: "The excess earnings method values intangible value from earnings above a fair return on tangible assets—an income-based approach.",
    orderIndex: 8,
  },
  {
    id: "cfa-equity-residual-income-valuation-q10",
    topicId: "cfa-equity-residual-income-valuation",
    text: "Discount rates for private companies are typically higher than for comparable public firms primarily because of:",
    optionA: "Lower expected growth and added size/company-specific risk premia",
    optionB: "Lower informational risk",
    optionC: "Greater liquidity",
    optionD: "Lower required returns",
    correctOption: "A",
    explanation: "Private firms warrant additional size and company-specific risk premia (and face illiquidity), raising the required rate of return used in valuation.",
    orderIndex: 9,
  },
  {
    id: "cfa-equity-residual-income-valuation-q11",
    topicId: "cfa-equity-residual-income-valuation",
    text: "In the residual income model, persistent positive residual income that is expected to fade over time is captured through a:",
    optionA: "Higher dividend payout",
    optionB: "Persistence factor that reduces future residual income toward zero",
    optionC: "Lower book value",
    optionD: "Negative beta",
    correctOption: "B",
    explanation: "A persistence factor models how quickly competitive forces erode residual income, scaling down future RI in the continuing-value term.",
    orderIndex: 10,
  },
  {
    id: "cfa-equity-residual-income-valuation-q12",
    topicId: "cfa-equity-residual-income-valuation",
    text: "The guideline transactions method values a private firm using:",
    optionA: "Multiples from acquisitions of similar companies",
    optionB: "The firm's own prior dividends",
    optionC: "The risk-free rate only",
    optionD: "Replacement cost of assets",
    correctOption: "A",
    explanation: "The guideline transactions method derives valuation multiples from prices paid in acquisitions of comparable companies.",
    orderIndex: 11,
  },

  // ── Fixed Income: Spot, Forward & Par Rates ──
  {
    id: "cfa-fixed-income-spot-forward-rates-q01",
    topicId: "cfa-fixed-income-spot-forward-rates",
    text: "A spot rate is best defined as the yield on a:",
    optionA: "Coupon bond priced at par",
    optionB: "Zero-coupon bond for a given maturity",
    optionC: "Floating-rate note",
    optionD: "Bond with embedded options",
    correctOption: "B",
    explanation: "A spot rate is the yield-to-maturity of a default-free zero-coupon bond maturing at a specific date.",
    orderIndex: 0,
  },
  {
    id: "cfa-fixed-income-spot-forward-rates-q02",
    topicId: "cfa-fixed-income-spot-forward-rates",
    text: "Given 1-year spot = 3% and 2-year spot = 4%, the implied 1-year forward rate one year from now (1y1y) is closest to:",
    optionA: "3.0%",
    optionB: "4.0%",
    optionC: "5.0%",
    optionD: "7.0%",
    correctOption: "C",
    explanation: "(1.04)² / (1.03) − 1 = 1.0816/1.03 − 1 ≈ 5.01%.",
    orderIndex: 1,
  },
  {
    id: "cfa-fixed-income-spot-forward-rates-q03",
    topicId: "cfa-fixed-income-spot-forward-rates",
    text: "The par rate for a given maturity is the coupon rate that makes a bond's price equal to:",
    optionA: "Its face (par) value",
    optionB: "Zero",
    optionC: "The forward price",
    optionD: "The spot rate",
    correctOption: "A",
    explanation: "The par rate is the coupon rate, consistent with the spot curve, that prices the bond exactly at par (100).",
    orderIndex: 2,
  },
  {
    id: "cfa-fixed-income-spot-forward-rates-q04",
    topicId: "cfa-fixed-income-spot-forward-rates",
    text: "When the spot curve is upward sloping, forward rates will be:",
    optionA: "Below spot rates",
    optionB: "Equal to spot rates",
    optionC: "Above spot rates",
    optionD: "Negative",
    correctOption: "C",
    explanation: "An upward-sloping spot curve implies forward rates lie above the corresponding spot rates.",
    orderIndex: 3,
  },
  {
    id: "cfa-fixed-income-spot-forward-rates-q05",
    topicId: "cfa-fixed-income-spot-forward-rates",
    text: "The no-arbitrage relationship between spot and forward rates for two periods is:",
    optionA: "(1+z₂)² = (1+z₁)(1+f(1,1))",
    optionB: "(1+z₂)² = (1+z₁)² + f(1,1)",
    optionC: "z₂ = z₁ + f(1,1)",
    optionD: "(1+z₂) = (1+z₁)(1+f(1,1))",
    correctOption: "A",
    explanation: "By no arbitrage, investing for two years at the 2-year spot equals investing one year at z₁ then rolling at the 1y1y forward: (1+z₂)² = (1+z₁)(1+f(1,1)).",
    orderIndex: 4,
  },
  {
    id: "cfa-fixed-income-spot-forward-rates-q06",
    topicId: "cfa-fixed-income-spot-forward-rates",
    text: "Forward rates can be interpreted as the market's:",
    optionA: "Guaranteed future spot rates",
    optionB: "Break-even future spot rates",
    optionC: "Risk-free rates only",
    optionD: "Realized historical rates",
    correctOption: "B",
    explanation: "Forward rates are break-even rates: an investor is indifferent between strategies only if future spot rates equal today's forwards.",
    orderIndex: 5,
  },
  {
    id: "cfa-fixed-income-spot-forward-rates-q07",
    topicId: "cfa-fixed-income-spot-forward-rates",
    text: "An investor expecting future spot rates to be LOWER than current forward rates would prefer to:",
    optionA: "Roll over short-term bonds",
    optionB: "Buy and hold a longer-term bond",
    optionC: "Hold only cash",
    optionD: "Short all bonds",
    correctOption: "B",
    explanation: "If realized future spots come in below today's forwards, locking in longer-term yields (buying the longer bond) outperforms rolling short-term positions.",
    orderIndex: 6,
  },
  {
    id: "cfa-fixed-income-spot-forward-rates-q08",
    topicId: "cfa-fixed-income-spot-forward-rates",
    text: "'Riding (rolling) down the yield curve' as a return-enhancing strategy works best when the curve is:",
    optionA: "Downward sloping and shifting up",
    optionB: "Upward sloping and stable",
    optionC: "Flat and volatile",
    optionD: "Inverted and steepening",
    correctOption: "B",
    explanation: "With a stable, upward-sloping curve, a bond's yield falls as it ages toward shorter maturities, producing price gains beyond its coupon.",
    orderIndex: 7,
  },
  {
    id: "cfa-fixed-income-spot-forward-rates-q09",
    topicId: "cfa-fixed-income-spot-forward-rates",
    text: "Discounting each of a bond's cash flows at its maturity-specific spot rate, rather than a single YTM, produces the bond's:",
    optionA: "Forward price",
    optionB: "Arbitrage-free (no-arbitrage) value",
    optionC: "Par value",
    optionD: "Duration",
    correctOption: "B",
    explanation: "Using the full set of spot rates to discount each cash flow yields the arbitrage-free value, preventing riskless profit from stripping/reconstitution.",
    orderIndex: 8,
  },
  {
    id: "cfa-fixed-income-spot-forward-rates-q10",
    topicId: "cfa-fixed-income-spot-forward-rates",
    text: "Deriving spot rates sequentially from coupon-bond (par) yields is known as:",
    optionA: "Bootstrapping",
    optionB: "Immunization",
    optionC: "Convexity adjustment",
    optionD: "Laddering",
    correctOption: "A",
    explanation: "Bootstrapping iteratively solves for spot rates from observed par/coupon yields, building the zero-coupon (spot) curve.",
    orderIndex: 9,
  },
  {
    id: "cfa-fixed-income-spot-forward-rates-q11",
    topicId: "cfa-fixed-income-spot-forward-rates",
    text: "If the 1-year spot is 2% and the 2-year spot is 2%, the 1y1y forward rate is closest to:",
    optionA: "0%",
    optionB: "2%",
    optionC: "4%",
    optionD: "1%",
    correctOption: "B",
    explanation: "With a flat spot curve, forward rates equal spot rates: (1.02)²/(1.02) − 1 = 2%.",
    orderIndex: 10,
  },
  {
    id: "cfa-fixed-income-spot-forward-rates-q12",
    topicId: "cfa-fixed-income-spot-forward-rates",
    text: "A bond's realized return equals its YTM only if coupons are reinvested at the YTM and the bond is held to maturity, assuming the yield curve is:",
    optionA: "Steeply upward sloping",
    optionB: "Flat and unchanged",
    optionC: "Inverted",
    optionD: "Highly volatile",
    correctOption: "B",
    explanation: "The YTM is realized only under a flat, unchanged curve with reinvestment at the YTM; otherwise reinvestment and price effects cause realized return to differ.",
    orderIndex: 11,
  },

  // ── Derivatives: Binomial Option Valuation ──
  {
    id: "cfa-derivatives-binomial-option-valuation-q01",
    topicId: "cfa-derivatives-binomial-option-valuation",
    text: "In the one-period binomial model, the risk-neutral probability of an up move is:",
    optionA: "(u − d) / (1 + r − d)",
    optionB: "(1 + r − d) / (u − d)",
    optionC: "(u − 1 − r) / (u − d)",
    optionD: "(1 + r) / (u × d)",
    correctOption: "B",
    explanation: "The risk-neutral up-probability is π = (1 + r − d) / (u − d), where u and d are the up/down factors.",
    orderIndex: 0,
  },
  {
    id: "cfa-derivatives-binomial-option-valuation-q02",
    topicId: "cfa-derivatives-binomial-option-valuation",
    text: "A defining feature of risk-neutral valuation is that the option value does NOT depend on:",
    optionA: "The risk-free rate",
    optionB: "The size of the up and down moves",
    optionC: "Investors' actual (real-world) probabilities of up/down moves",
    optionD: "The current price of the underlying",
    correctOption: "C",
    explanation: "Once the option is replicated/hedged, real-world probabilities and risk preferences are irrelevant—only the risk-neutral probabilities matter.",
    orderIndex: 1,
  },
  {
    id: "cfa-derivatives-binomial-option-valuation-q03",
    topicId: "cfa-derivatives-binomial-option-valuation",
    text: "A stock is $100; it can rise to $120 (u = 1.2) or fall to $90 (d = 0.9). With r = 5%, the risk-neutral probability of an up move is closest to:",
    optionA: "0.50",
    optionB: "0.40",
    optionC: "0.60",
    optionD: "0.33",
    correctOption: "A",
    explanation: "π = (1 + 0.05 − 0.9) / (1.2 − 0.9) = 0.15 / 0.30 = 0.50.",
    orderIndex: 2,
  },
  {
    id: "cfa-derivatives-binomial-option-valuation-q04",
    topicId: "cfa-derivatives-binomial-option-valuation",
    text: "Using the previous setup (π = 0.50, r = 5%), a one-period call with strike $100 (payoffs $20 up, $0 down) is worth closest to:",
    optionA: "$20.00",
    optionB: "$10.00",
    optionC: "$9.52",
    optionD: "$0.00",
    correctOption: "C",
    explanation: "c₀ = [0.5 × 20 + 0.5 × 0] / 1.05 = 10 / 1.05 ≈ $9.52.",
    orderIndex: 3,
  },
  {
    id: "cfa-derivatives-binomial-option-valuation-q05",
    topicId: "cfa-derivatives-binomial-option-valuation",
    text: "The binomial 'hedge ratio' for a call equals the change in option value divided by the change in:",
    optionA: "The risk-free rate",
    optionB: "The underlying's price across states",
    optionC: "Time",
    optionD: "Volatility",
    correctOption: "B",
    explanation: "The hedge ratio = (c_u − c_d) / (S·u − S·d): the number of underlying units needed to replicate the option payoff.",
    orderIndex: 4,
  },
  {
    id: "cfa-derivatives-binomial-option-valuation-q06",
    topicId: "cfa-derivatives-binomial-option-valuation",
    text: "Early exercise can add value to an American-style option most notably for:",
    optionA: "Calls on a non-dividend-paying stock",
    optionB: "Puts that are deep in the money, and calls on dividend-paying stocks",
    optionC: "All European options",
    optionD: "Options with zero time to expiry",
    correctOption: "B",
    explanation: "American puts (deep in the money) and American calls on dividend-paying stocks can be worth more than their European counterparts due to early exercise.",
    orderIndex: 5,
  },
  {
    id: "cfa-derivatives-binomial-option-valuation-q07",
    topicId: "cfa-derivatives-binomial-option-valuation",
    text: "The no-arbitrage principle in option pricing rests on the ability to:",
    optionA: "Forecast the real probability of an up move",
    optionB: "Replicate the option with the underlying and risk-free borrowing/lending",
    optionC: "Diversify away all risk",
    optionD: "Predict interest rates",
    correctOption: "B",
    explanation: "Because a portfolio of the underlying plus borrowing/lending replicates the option's payoff, the option must trade at the cost of that replicating portfolio.",
    orderIndex: 6,
  },
  {
    id: "cfa-derivatives-binomial-option-valuation-q08",
    topicId: "cfa-derivatives-binomial-option-valuation",
    text: "Holding other factors constant, increasing the spread between u and d (higher volatility) will cause a call option's value to:",
    optionA: "Decrease",
    optionB: "Increase",
    optionC: "Stay the same",
    optionD: "Become negative",
    correctOption: "B",
    explanation: "Greater dispersion in possible outcomes raises the option's value because of its asymmetric (limited downside) payoff.",
    orderIndex: 7,
  },
  {
    id: "cfa-derivatives-binomial-option-valuation-q09",
    topicId: "cfa-derivatives-binomial-option-valuation",
    text: "To value a two-period binomial option, an analyst should:",
    optionA: "Discount the final payoffs at the real expected return",
    optionB: "Work backward through the tree, discounting risk-neutral expected values node by node",
    optionC: "Use only the first-period probabilities",
    optionD: "Ignore intermediate nodes",
    correctOption: "B",
    explanation: "Multi-period binomial valuation proceeds by backward induction: compute payoffs at the final nodes, then discount risk-neutral expectations back step by step.",
    orderIndex: 8,
  },
  {
    id: "cfa-derivatives-binomial-option-valuation-q10",
    topicId: "cfa-derivatives-binomial-option-valuation",
    text: "For the risk-neutral probability to be valid (between 0 and 1), the model requires:",
    optionA: "d < 1 + r < u",
    optionB: "u < 1 + r < d",
    optionC: "u = d",
    optionD: "r < 0",
    correctOption: "A",
    explanation: "No-arbitrage requires d < (1 + r) < u; otherwise the risk-neutral probability would fall outside [0, 1] and arbitrage would exist.",
    orderIndex: 9,
  },
  {
    id: "cfa-derivatives-binomial-option-valuation-q11",
    topicId: "cfa-derivatives-binomial-option-valuation",
    text: "Using the put-call parity check, a one-period put in the earlier example (π = 0.5, r = 5%, strike $100, payoffs $0 up, $10 down) is worth closest to:",
    optionA: "$4.76",
    optionB: "$10.00",
    optionC: "$5.00",
    optionD: "$0.00",
    correctOption: "A",
    explanation: "p₀ = [0.5 × 0 + 0.5 × 10] / 1.05 = 5 / 1.05 ≈ $4.76.",
    orderIndex: 10,
  },
  {
    id: "cfa-derivatives-binomial-option-valuation-q12",
    topicId: "cfa-derivatives-binomial-option-valuation",
    text: "As the number of periods in a binomial tree increases toward infinity (with appropriate u and d), the model's option values converge to those of the:",
    optionA: "Capital asset pricing model",
    optionB: "Black-Scholes-Merton model",
    optionC: "Dividend discount model",
    optionD: "Arbitrage pricing theory",
    correctOption: "B",
    explanation: "A finely subdivided binomial tree converges to the continuous-time Black-Scholes-Merton option value.",
    orderIndex: 11,
  },

  // ── Alternative Investments: Private Debt & Direct Lending ──
  {
    id: "cfa-alternative-investments-private-debt-q01",
    topicId: "cfa-alternative-investments-private-debt",
    text: "Private debt is best described as:",
    optionA: "Publicly traded investment-grade bonds",
    optionB: "Loans or bonds extended directly to borrowers outside public markets",
    optionC: "Government treasury securities",
    optionD: "Listed equity of lending banks",
    correctOption: "B",
    explanation: "Private debt comprises directly negotiated loans/bonds to (often mid-market) borrowers, made outside public capital markets, typically by funds.",
    orderIndex: 0,
  },
  {
    id: "cfa-alternative-investments-private-debt-q02",
    topicId: "cfa-alternative-investments-private-debt",
    text: "Direct lending strategies most commonly involve loans that are:",
    optionA: "Subordinated and equity-linked",
    optionB: "Senior, secured, and often floating-rate",
    optionC: "Unsecured and fixed-rate government bonds",
    optionD: "Convertible into common shares",
    correctOption: "B",
    explanation: "Direct lending typically provides senior, secured, floating-rate loans to private companies, emphasizing current income.",
    orderIndex: 1,
  },
  {
    id: "cfa-alternative-investments-private-debt-q03",
    topicId: "cfa-alternative-investments-private-debt",
    text: "Mezzanine debt is characterized by being:",
    optionA: "Senior to all other claims",
    optionB: "Subordinated debt that often includes equity warrants",
    optionC: "Risk-free",
    optionD: "Always investment grade",
    correctOption: "B",
    explanation: "Mezzanine financing is subordinated, higher-yielding debt frequently bundled with equity warrants—a hybrid between debt and equity.",
    orderIndex: 2,
  },
  {
    id: "cfa-alternative-investments-private-debt-q04",
    topicId: "cfa-alternative-investments-private-debt",
    text: "A 'loan-to-own' approach is most associated with which private debt strategy?",
    optionA: "Venture debt",
    optionB: "Investment-grade direct lending",
    optionC: "Distressed debt investing",
    optionD: "Infrastructure debt",
    correctOption: "C",
    explanation: "Distressed-debt investors may buy a troubled firm's debt intending to convert it into a controlling equity stake through restructuring ('loan-to-own').",
    orderIndex: 3,
  },
  {
    id: "cfa-alternative-investments-private-debt-q05",
    topicId: "cfa-alternative-investments-private-debt",
    text: "The rapid post-2008 growth of private debt is largely attributed to:",
    optionA: "Banks expanding mid-market lending",
    optionB: "Tighter bank capital rules causing banks to retrench from such lending",
    optionC: "Falling investor demand for yield",
    optionD: "A ban on syndicated loans",
    correctOption: "B",
    explanation: "Stricter post-crisis capital and regulatory requirements caused banks to pull back from middle-market lending, creating space for private debt funds.",
    orderIndex: 4,
  },
  {
    id: "cfa-alternative-investments-private-debt-q06",
    topicId: "cfa-alternative-investments-private-debt",
    text: "Investors in private debt are primarily compensated for bearing:",
    optionA: "Only inflation risk",
    optionB: "Illiquidity and credit risk",
    optionC: "Currency risk only",
    optionD: "No incremental risk",
    correctOption: "B",
    explanation: "Private debt offers a yield premium chiefly to compensate for illiquidity and the credit risk of often-leveraged, non-public borrowers.",
    orderIndex: 5,
  },
  {
    id: "cfa-alternative-investments-private-debt-q07",
    topicId: "cfa-alternative-investments-private-debt",
    text: "Because direct loans are frequently floating-rate, they tend to have:",
    optionA: "High interest-rate (duration) risk",
    optionB: "Low interest-rate (duration) risk",
    optionC: "No credit risk",
    optionD: "Guaranteed returns",
    correctOption: "B",
    explanation: "Floating-rate coupons reset with reference rates, giving direct loans low duration/interest-rate risk relative to fixed-rate bonds.",
    orderIndex: 6,
  },
  {
    id: "cfa-alternative-investments-private-debt-q08",
    topicId: "cfa-alternative-investments-private-debt",
    text: "'Covenant-lite' (cov-lite) loans are a concern because they:",
    optionA: "Carry no interest",
    optionB: "Offer lenders fewer protections and early-warning triggers",
    optionC: "Are always senior secured",
    optionD: "Eliminate default risk",
    correctOption: "B",
    explanation: "Cov-lite loans weaken or remove maintenance covenants, reducing lender protections and the early warnings that covenants normally provide.",
    orderIndex: 7,
  },
  {
    id: "cfa-alternative-investments-private-debt-q09",
    topicId: "cfa-alternative-investments-private-debt",
    text: "Venture debt is most commonly extended to:",
    optionA: "Mature investment-grade corporations",
    optionB: "Venture-capital-backed startups alongside their equity investors",
    optionC: "Sovereign governments",
    optionD: "Real estate investment trusts",
    correctOption: "B",
    explanation: "Venture debt provides loans to early-stage, venture-backed companies, typically complementing their VC equity financing.",
    orderIndex: 8,
  },
  {
    id: "cfa-alternative-investments-private-debt-q10",
    topicId: "cfa-alternative-investments-private-debt",
    text: "Beyond interest income, an additional return driver for private debt funds is:",
    optionA: "Dividend imputation credits",
    optionB: "Origination and prepayment fees",
    optionC: "Index rebalancing",
    optionD: "Stock buybacks",
    correctOption: "B",
    explanation: "Private debt returns include fee income (e.g., origination and prepayment fees) on top of interest, and capital gains in distressed/mezzanine strategies.",
    orderIndex: 9,
  },
  {
    id: "cfa-alternative-investments-private-debt-q11",
    topicId: "cfa-alternative-investments-private-debt",
    text: "Compared with public high-yield bonds, private debt instruments are generally:",
    optionA: "More liquid",
    optionB: "Less liquid",
    optionC: "Free of credit risk",
    optionD: "Always lower yielding",
    correctOption: "B",
    explanation: "Private debt is less liquid than publicly traded high-yield bonds, which is a key reason it offers an illiquidity yield premium.",
    orderIndex: 10,
  },
  {
    id: "cfa-alternative-investments-private-debt-q12",
    topicId: "cfa-alternative-investments-private-debt",
    text: "Fund-level leverage in a private debt fund primarily affects:",
    optionA: "Only the management fee",
    optionB: "The amplification of both returns and risk to investors",
    optionC: "The borrowers' credit ratings",
    optionD: "Nothing material",
    correctOption: "B",
    explanation: "Leverage applied at the fund level magnifies returns to limited partners but also amplifies losses and risk, an important due-diligence consideration.",
    orderIndex: 11,
  },

  // ── Portfolio Management: Behavioral Finance & Biases ──
  {
    id: "cfa-portfolio-management-behavioral-finance-q01",
    topicId: "cfa-portfolio-management-behavioral-finance",
    text: "Behavioral biases are commonly classified into which two broad categories?",
    optionA: "Systematic and unsystematic",
    optionB: "Cognitive errors and emotional biases",
    optionC: "Liquid and illiquid",
    optionD: "Active and passive",
    correctOption: "B",
    explanation: "Behavioral finance splits biases into cognitive errors (faulty reasoning) and emotional biases (feeling-driven).",
    orderIndex: 0,
  },
  {
    id: "cfa-portfolio-management-behavioral-finance-q02",
    topicId: "cfa-portfolio-management-behavioral-finance",
    text: "The disposition effect—selling winners too early and holding losers too long—stems mainly from:",
    optionA: "Anchoring",
    optionB: "Loss aversion",
    optionC: "Confirmation bias",
    optionD: "Availability bias",
    correctOption: "B",
    explanation: "Loss aversion makes investors reluctant to realize losses, so they hold losers and sell winners—the disposition effect.",
    orderIndex: 1,
  },
  {
    id: "cfa-portfolio-management-behavioral-finance-q03",
    topicId: "cfa-portfolio-management-behavioral-finance",
    text: "An investor who seeks out only information confirming an existing view exhibits:",
    optionA: "Confirmation bias",
    optionB: "Hindsight bias",
    optionC: "Mental accounting",
    optionD: "Regret aversion",
    correctOption: "A",
    explanation: "Confirmation bias is the tendency to notice and favor evidence that supports prior beliefs while ignoring contradictory information.",
    orderIndex: 2,
  },
  {
    id: "cfa-portfolio-management-behavioral-finance-q04",
    topicId: "cfa-portfolio-management-behavioral-finance",
    text: "According to prospect theory, individuals tend to be:",
    optionA: "Risk-seeking in gains and risk-averse in losses",
    optionB: "Risk-averse in gains and risk-seeking in losses",
    optionC: "Always risk-neutral",
    optionD: "Always risk-averse",
    correctOption: "B",
    explanation: "Prospect theory finds people are risk-averse over gains but risk-seeking over losses, evaluated relative to a reference point.",
    orderIndex: 3,
  },
  {
    id: "cfa-portfolio-management-behavioral-finance-q05",
    topicId: "cfa-portfolio-management-behavioral-finance",
    text: "Cognitive errors, relative to emotional biases, are generally:",
    optionA: "Impossible to correct",
    optionB: "Easier to mitigate through education and better information",
    optionC: "Only found in institutional investors",
    optionD: "Always beneficial",
    correctOption: "B",
    explanation: "Because cognitive errors arise from faulty reasoning, they can often be reduced with education, data, and disciplined processes, unlike deeper emotional biases.",
    orderIndex: 4,
  },
  {
    id: "cfa-portfolio-management-behavioral-finance-q06",
    topicId: "cfa-portfolio-management-behavioral-finance",
    text: "Treating money differently based on its source or intended use is known as:",
    optionA: "Mental accounting",
    optionB: "Anchoring",
    optionC: "Overconfidence",
    optionD: "Herding",
    correctOption: "A",
    explanation: "Mental accounting is the bias of segregating money into separate 'accounts' and treating each differently, violating fungibility.",
    orderIndex: 5,
  },
  {
    id: "cfa-portfolio-management-behavioral-finance-q07",
    topicId: "cfa-portfolio-management-behavioral-finance",
    text: "An advisor should generally MODERATE cognitive biases but ADAPT to:",
    optionA: "Market risk",
    optionB: "Emotional biases",
    optionC: "Liquidity needs",
    optionD: "Tax constraints",
    correctOption: "B",
    explanation: "Standard guidance is to moderate (correct) cognitive errors while adapting the plan around harder-to-change emotional biases.",
    orderIndex: 6,
  },
  {
    id: "cfa-portfolio-management-behavioral-finance-q08",
    topicId: "cfa-portfolio-management-behavioral-finance",
    text: "Investors relying too heavily on an initial reference figure (e.g., a purchase price) when estimating value exhibit:",
    optionA: "Anchoring and adjustment",
    optionB: "Self-control bias",
    optionC: "Endowment bias",
    optionD: "Status quo bias",
    correctOption: "A",
    explanation: "Anchoring is the tendency to fixate on an initial value and adjust insufficiently away from it when forming new estimates.",
    orderIndex: 7,
  },
  {
    id: "cfa-portfolio-management-behavioral-finance-q09",
    topicId: "cfa-portfolio-management-behavioral-finance",
    text: "Overconfidence bias most commonly leads investors to:",
    optionA: "Hold excessive cash",
    optionB: "Trade too frequently and underdiversify",
    optionC: "Avoid all equities",
    optionD: "Over-rely on index funds",
    correctOption: "B",
    explanation: "Overconfident investors overestimate their skill/information, leading to excessive trading and insufficient diversification.",
    orderIndex: 8,
  },
  {
    id: "cfa-portfolio-management-behavioral-finance-q10",
    topicId: "cfa-portfolio-management-behavioral-finance",
    text: "Following the crowd into popular trades, even against one's own analysis, is:",
    optionA: "Herding behavior",
    optionB: "Conservatism",
    optionC: "Framing",
    optionD: "Illusion of control",
    correctOption: "A",
    explanation: "Herding is the tendency to mimic the actions of a larger group, which can contribute to bubbles and crashes.",
    orderIndex: 9,
  },
  {
    id: "cfa-portfolio-management-behavioral-finance-q11",
    topicId: "cfa-portfolio-management-behavioral-finance",
    text: "Endowment bias is best illustrated by an investor who:",
    optionA: "Demands a higher price to sell an inherited stock than they would pay to buy it",
    optionB: "Trades on insider information",
    optionC: "Diversifies across many assets",
    optionD: "Rebalances mechanically",
    correctOption: "A",
    explanation: "Endowment bias causes people to value an asset they own more highly simply because they own it, creating a gap between selling and buying prices.",
    orderIndex: 10,
  },
  {
    id: "cfa-portfolio-management-behavioral-finance-q12",
    topicId: "cfa-portfolio-management-behavioral-finance",
    text: "Market anomalies such as momentum and value effects are significant because they:",
    optionA: "Confirm strong-form market efficiency",
    optionB: "Appear to contradict fully efficient markets and may reflect behavioral factors",
    optionC: "Prove markets are completely random",
    optionD: "Eliminate the need for risk management",
    correctOption: "B",
    explanation: "Persistent anomalies challenge the efficient-market hypothesis and are often attributed (at least partly) to behavioral biases among investors.",
    orderIndex: 11,
  },
];
