// CFA Level I depth top-up (pass 7). Fifty topics held only 8 questions each;
// this adds q09–q12 to every one so all reach the 12-question standard used
// across the catalog. No new topics or materials — these attach to existing
// readings across all ten topic areas.
import type { Question } from "@jyotir/core";

export const cfaL1TopUp: Question[] = [
  // ══ Ethics & Professional Standards ══
  // Code of Ethics & Standards
  { id: "cfa-ethics-code-of-ethics-standards-q09", topicId: "cfa-ethics-code-of-ethics-standards", text: "The first of the seven Standards of Professional Conduct is:", optionA: "Professionalism", optionB: "Duties to Clients", optionC: "Integrity of Capital Markets", optionD: "Investment Analysis", correctOption: "A", explanation: "Standard I is Professionalism, covering knowledge of the law, independence, misrepresentation and misconduct.", orderIndex: 8 },
  { id: "cfa-ethics-code-of-ethics-standards-q10", topicId: "cfa-ethics-code-of-ethics-standards", text: "Under Standard I(A) Knowledge of the Law, when applicable law and the Code & Standards differ, a member must follow:", optionA: "The stricter of the two", optionB: "Local law always", optionC: "The Code & Standards always", optionD: "Whichever is easier to apply", correctOption: "A", explanation: "Members must comply with the more strict of applicable law or the Code and Standards.", orderIndex: 9 },
  { id: "cfa-ethics-code-of-ethics-standards-q11", topicId: "cfa-ethics-code-of-ethics-standards", text: "Standard I(B) requires members to maintain:", optionA: "Independence and objectivity", optionB: "Confidentiality of law", optionC: "Priority of transactions", optionD: "Record retention", correctOption: "A", explanation: "Standard I(B) Independence and Objectivity requires members to use reasonable care and judgement and resist influences that compromise it.", orderIndex: 10 },
  { id: "cfa-ethics-code-of-ethics-standards-q12", topicId: "cfa-ethics-code-of-ethics-standards", text: "The Code of Ethics requires members to place the integrity of the profession and the interests of clients:", optionA: "Above their own personal interests", optionB: "Below employer targets", optionC: "Equal to their own interests", optionD: "After regulatory interests", correctOption: "A", explanation: "Members must place the integrity of the profession and client interests above their own personal interests.", orderIndex: 11 },
  // Material Non-Public Information & Market Manipulation
  { id: "cfa-ethics-material-non-public-info-q09", topicId: "cfa-ethics-material-non-public-info", text: "Standard II(A) prohibits members from acting or causing others to act on:", optionA: "Material non-public information", optionB: "Any public information", optionC: "Analyst consensus estimates", optionD: "Historical price data", correctOption: "A", explanation: "Standard II(A) prohibits trading or causing others to trade on material non-public information.", orderIndex: 8 },
  { id: "cfa-ethics-material-non-public-info-q10", topicId: "cfa-ethics-material-non-public-info", text: "Information is 'material' if:", optionA: "Its disclosure would likely affect a security's price or a reasonable investor would want it", optionB: "It is longer than one page", optionC: "It comes from management only", optionD: "It is already widely known", correctOption: "A", explanation: "Materiality turns on whether disclosure would move the price or a reasonable investor would consider it important.", orderIndex: 9 },
  { id: "cfa-ethics-material-non-public-info-q11", topicId: "cfa-ethics-material-non-public-info", text: "The 'mosaic theory' permits an analyst to:", optionA: "Combine public and non-material non-public information to reach a conclusion", optionB: "Trade on any tip received", optionC: "Ignore public disclosures", optionD: "Share inside information with clients", correctOption: "A", explanation: "Under the mosaic theory, analysts may reach conclusions from public and non-material non-public information without violating the standard.", orderIndex: 10 },
  { id: "cfa-ethics-material-non-public-info-q12", topicId: "cfa-ethics-material-non-public-info", text: "Standard II(B) Market Manipulation prohibits:", optionA: "Practices that distort prices or artificially inflate trading volume", optionB: "Publishing independent research", optionC: "Disclosing conflicts", optionD: "Fair dealing with clients", correctOption: "A", explanation: "Market manipulation covers information-based and transaction-based practices that mislead market participants.", orderIndex: 11 },
  // Duties to Clients & Portfolio Integrity
  { id: "cfa-ethics-duties-to-clients-q09", topicId: "cfa-ethics-duties-to-clients", text: "Standard III(A) Loyalty, Prudence, and Care requires members to place:", optionA: "Clients' interests before their own and their employer's", optionB: "Employer interests first", optionC: "Their own interests first", optionD: "Regulators' interests first", correctOption: "A", explanation: "Members owe clients loyalty and must act for their benefit, placing client interests first.", orderIndex: 8 },
  { id: "cfa-ethics-duties-to-clients-q10", topicId: "cfa-ethics-duties-to-clients", text: "Standard III(B) Fair Dealing requires members to:", optionA: "Treat all clients fairly when disseminating recommendations or taking action", optionB: "Give the largest clients priority", optionC: "Favour discretionary accounts", optionD: "Disclose trades to the public first", correctOption: "A", explanation: "Fair dealing requires acting fairly and objectively with all clients when providing investment advice or taking action.", orderIndex: 9 },
  { id: "cfa-ethics-duties-to-clients-q11", topicId: "cfa-ethics-duties-to-clients", text: "Standard III(C) Suitability requires that recommendations be:", optionA: "Consistent with the client's written objectives, mandate and constraints", optionB: "The highest-returning available", optionC: "The same for every client", optionD: "Based only on the member's view", correctOption: "A", explanation: "Suitability requires matching recommendations to the client's IPS — objectives, risk tolerance and constraints.", orderIndex: 10 },
  { id: "cfa-ethics-duties-to-clients-q12", topicId: "cfa-ethics-duties-to-clients", text: "Under Standard III(E), a member may disclose confidential client information when:", optionA: "It concerns illegal activities, disclosure is required by law, or the client permits it", optionB: "A colleague asks for it", optionC: "It would help marketing", optionD: "Never, under any circumstance", correctOption: "A", explanation: "Confidentiality must be preserved except where the law requires disclosure, the client permits, or it concerns illegal client activity.", orderIndex: 11 },
  // Conflicts of Interest & Priority of Transactions
  { id: "cfa-ethics-conflicts-of-interest-q09", topicId: "cfa-ethics-conflicts-of-interest", text: "Standard VI(A) Disclosure of Conflicts requires that conflicts be:", optionA: "Disclosed prominently, in plain language, and fully", optionB: "Hidden from clients", optionC: "Disclosed only if asked", optionD: "Reported to regulators only", correctOption: "A", explanation: "Members must fully and fairly disclose all matters that could impair independence or interfere with duties.", orderIndex: 8 },
  { id: "cfa-ethics-conflicts-of-interest-q10", topicId: "cfa-ethics-conflicts-of-interest", text: "Standard VI(B) Priority of Transactions requires that transactions for clients come before those of:", optionA: "The member and the firm", optionB: "Other clients", optionC: "Charitable accounts", optionD: "Index funds", correctOption: "A", explanation: "Client transactions take priority over transactions in which a member or the firm is a beneficial owner.", orderIndex: 9 },
  { id: "cfa-ethics-conflicts-of-interest-q11", topicId: "cfa-ethics-conflicts-of-interest", text: "Standard VI(C) Referral Fees requires members to:", optionA: "Disclose referral compensation to clients and employer", optionB: "Refuse all referral fees", optionC: "Keep referral fees private", optionD: "Pay referral fees to clients", correctOption: "A", explanation: "Any consideration paid or received for recommendations must be disclosed to clients and the employer.", orderIndex: 10 },
  { id: "cfa-ethics-conflicts-of-interest-q12", topicId: "cfa-ethics-conflicts-of-interest", text: "A member who receives a bonus gift from a client for strong past performance should:", optionA: "Disclose it to the employer", optionB: "Keep it secret", optionC: "Return it always", optionD: "Share it with other clients", correctOption: "A", explanation: "Additional compensation or gifts from clients must be disclosed to the employer to manage the conflict.", orderIndex: 11 },
  // GIPS Standards & Performance Reporting
  { id: "cfa-ethics-gips-standards-q09", topicId: "cfa-ethics-gips-standards", text: "GIPS stands for:", optionA: "Global Investment Performance Standards", optionB: "General Investment Pricing System", optionC: "Global Index Performance Series", optionD: "Governed Investment Portfolio Standards", correctOption: "A", explanation: "GIPS are the Global Investment Performance Standards for fair, comparable performance reporting.", orderIndex: 8 },
  { id: "cfa-ethics-gips-standards-q10", topicId: "cfa-ethics-gips-standards", text: "GIPS compliance must be applied on a:", optionA: "Firm-wide basis", optionB: "Single-portfolio basis", optionC: "Per-client basis", optionD: "Per-strategy basis only", correctOption: "A", explanation: "A firm must apply GIPS on a firm-wide basis; it cannot claim compliance for only some composites.", orderIndex: 9 },
  { id: "cfa-ethics-gips-standards-q11", topicId: "cfa-ethics-gips-standards", text: "Under GIPS, a 'composite' is:", optionA: "An aggregation of portfolios managed to a similar strategy or mandate", optionB: "A single flagship fund", optionC: "A benchmark index", optionD: "The firm's total assets", correctOption: "A", explanation: "A composite groups all discretionary portfolios managed according to a similar investment mandate or strategy.", orderIndex: 10 },
  { id: "cfa-ethics-gips-standards-q12", topicId: "cfa-ethics-gips-standards", text: "Compliance with the GIPS standards is:", optionA: "Voluntary", optionB: "Legally mandatory worldwide", optionC: "Required only in the US", optionD: "Required for all public companies", correctOption: "A", explanation: "GIPS compliance is voluntary but widely adopted to demonstrate fair performance presentation.", orderIndex: 11 },

  // ══ Quantitative Methods ══
  // Time Value of Money
  { id: "cfa-quantitative-methods-time-value-of-money-q09", topicId: "cfa-quantitative-methods-time-value-of-money", text: "The future value of a single sum invested for n periods at rate r grows by the factor:", optionA: "(1 + r)^n", optionB: "1 + rn", optionC: "(1 − r)^n", optionD: "n / (1 + r)", correctOption: "A", explanation: "FV = PV × (1 + r)^n under compound interest.", orderIndex: 8 },
  { id: "cfa-quantitative-methods-time-value-of-money-q10", topicId: "cfa-quantitative-methods-time-value-of-money", text: "An annuity due differs from an ordinary annuity in that its payments occur at the:", optionA: "Beginning of each period", optionB: "End of each period", optionC: "Midpoint of each period", optionD: "Maturity date only", correctOption: "A", explanation: "In an annuity due, payments are made at the start of each period, so its value is higher than an ordinary annuity.", orderIndex: 9 },
  { id: "cfa-quantitative-methods-time-value-of-money-q11", topicId: "cfa-quantitative-methods-time-value-of-money", text: "The present value of a level perpetuity paying PMT with discount rate r is:", optionA: "PMT / r", optionB: "PMT × r", optionC: "PMT / (1 + r)", optionD: "PMT × (1 + r)", correctOption: "A", explanation: "A perpetuity's present value is PMT divided by the discount rate.", orderIndex: 10 },
  { id: "cfa-quantitative-methods-time-value-of-money-q12", topicId: "cfa-quantitative-methods-time-value-of-money", text: "The effective annual rate for a stated rate r compounded m times per year is:", optionA: "(1 + r/m)^m − 1", optionB: "r/m", optionC: "r × m", optionD: "(1 + r)^m", correctOption: "A", explanation: "EAR = (1 + periodic rate)^m − 1, where the periodic rate is r/m.", orderIndex: 11 },
  // Probability & Expected Value
  { id: "cfa-quantitative-methods-probability-q09", topicId: "cfa-quantitative-methods-probability", text: "For two mutually exclusive events A and B, P(A or B) equals:", optionA: "P(A) + P(B)", optionB: "P(A) × P(B)", optionC: "P(A) − P(B)", optionD: "P(A) / P(B)", correctOption: "A", explanation: "Mutually exclusive events cannot occur together, so the addition rule simplifies to P(A) + P(B).", orderIndex: 8 },
  { id: "cfa-quantitative-methods-probability-q10", topicId: "cfa-quantitative-methods-probability", text: "For two independent events, P(A and B) equals:", optionA: "P(A) × P(B)", optionB: "P(A) + P(B)", optionC: "P(A) − P(B)", optionD: "P(A | B)", correctOption: "A", explanation: "For independent events the joint probability is the product of their individual probabilities.", orderIndex: 9 },
  { id: "cfa-quantitative-methods-probability-q11", topicId: "cfa-quantitative-methods-probability", text: "Bayes' formula is used to:", optionA: "Update a prior probability given new information", optionB: "Compute a bond's duration", optionC: "Estimate a regression slope", optionD: "Find the mode of a distribution", correctOption: "A", explanation: "Bayes' formula revises a prior probability into a posterior after observing new evidence.", orderIndex: 10 },
  { id: "cfa-quantitative-methods-probability-q12", topicId: "cfa-quantitative-methods-probability", text: "The expected value of a random variable is:", optionA: "The probability-weighted average of its possible outcomes", optionB: "Its largest outcome", optionC: "Its median outcome", optionD: "Its variance", correctOption: "A", explanation: "Expected value is the sum of each outcome multiplied by its probability.", orderIndex: 11 },
  // Sampling & Statistical Inference
  { id: "cfa-quantitative-methods-statistical-inference-q09", topicId: "cfa-quantitative-methods-statistical-inference", text: "The central limit theorem states that the sampling distribution of the sample mean approaches:", optionA: "A normal distribution as sample size increases", optionB: "A uniform distribution", optionC: "The population's exact shape", optionD: "A t-distribution with 1 df", correctOption: "A", explanation: "For a large enough sample, the distribution of the sample mean is approximately normal regardless of the population.", orderIndex: 8 },
  { id: "cfa-quantitative-methods-statistical-inference-q10", topicId: "cfa-quantitative-methods-statistical-inference", text: "The standard error of the sample mean equals:", optionA: "σ / √n", optionB: "σ × n", optionC: "σ² / n", optionD: "√σ / n", correctOption: "A", explanation: "The standard error is the population (or sample) standard deviation divided by the square root of n.", orderIndex: 9 },
  { id: "cfa-quantitative-methods-statistical-inference-q11", topicId: "cfa-quantitative-methods-statistical-inference", text: "An unbiased estimator has an expected value equal to:", optionA: "The true population parameter", optionB: "Zero", optionC: "The sample size", optionD: "The standard error", correctOption: "A", explanation: "Unbiasedness means the estimator's expected value equals the parameter it estimates.", orderIndex: 10 },
  { id: "cfa-quantitative-methods-statistical-inference-q12", topicId: "cfa-quantitative-methods-statistical-inference", text: "A sampling method in which every population member has an equal chance of selection is:", optionA: "Simple random sampling", optionB: "Stratified sampling", optionC: "Judgemental sampling", optionD: "Convenience sampling", correctOption: "A", explanation: "Simple random sampling gives each element an equal probability of being chosen.", orderIndex: 11 },
  // Hypothesis Testing
  { id: "cfa-quantitative-methods-hypothesis-testing-q09", topicId: "cfa-quantitative-methods-hypothesis-testing", text: "A Type I error occurs when a researcher:", optionA: "Rejects a true null hypothesis", optionB: "Fails to reject a false null", optionC: "Accepts the alternative correctly", optionD: "Uses the wrong test statistic", correctOption: "A", explanation: "A Type I error is rejecting the null hypothesis when it is actually true (a false positive).", orderIndex: 8 },
  { id: "cfa-quantitative-methods-hypothesis-testing-q10", topicId: "cfa-quantitative-methods-hypothesis-testing", text: "The significance level (α) of a test is the probability of:", optionA: "A Type I error", optionB: "A Type II error", optionC: "A correct decision", optionD: "The power of the test", correctOption: "A", explanation: "α is the probability of making a Type I error — rejecting a true null.", orderIndex: 9 },
  { id: "cfa-quantitative-methods-hypothesis-testing-q11", topicId: "cfa-quantitative-methods-hypothesis-testing", text: "The p-value of a test is:", optionA: "The smallest significance level at which the null can be rejected", optionB: "The probability the null is true", optionC: "Always equal to 0.05", optionD: "The test's power", correctOption: "A", explanation: "The p-value is the smallest level of significance at which the null hypothesis can be rejected.", orderIndex: 10 },
  { id: "cfa-quantitative-methods-hypothesis-testing-q12", topicId: "cfa-quantitative-methods-hypothesis-testing", text: "If the test statistic falls in the rejection region, the analyst should:", optionA: "Reject the null hypothesis", optionB: "Fail to reject the null", optionC: "Increase the sample size", optionD: "Accept the null as proven", correctOption: "A", explanation: "A test statistic in the rejection region leads to rejecting the null hypothesis.", orderIndex: 11 },
  // Simple & Multiple Regression
  { id: "cfa-quantitative-methods-regression-q09", topicId: "cfa-quantitative-methods-regression", text: "In a simple linear regression, the slope coefficient measures:", optionA: "The change in the dependent variable per unit change in the independent variable", optionB: "The average of Y", optionC: "The correlation squared", optionD: "The intercept", correctOption: "A", explanation: "The slope estimates how much Y changes for a one-unit change in X.", orderIndex: 8 },
  { id: "cfa-quantitative-methods-regression-q10", topicId: "cfa-quantitative-methods-regression", text: "The coefficient of determination (R²) measures:", optionA: "The proportion of the variation in Y explained by the regression", optionB: "The slope of the line", optionC: "The residual sum of squares", optionD: "The standard error of the estimate", correctOption: "A", explanation: "R² is the fraction of total variation in the dependent variable explained by the independent variable(s).", orderIndex: 9 },
  { id: "cfa-quantitative-methods-regression-q11", topicId: "cfa-quantitative-methods-regression", text: "The assumption that the variance of the error term is constant across observations is called:", optionA: "Homoskedasticity", optionB: "Heteroskedasticity", optionC: "Autocorrelation", optionD: "Multicollinearity", correctOption: "A", explanation: "Homoskedasticity means the error variance is constant; its violation is heteroskedasticity.", orderIndex: 10 },
  { id: "cfa-quantitative-methods-regression-q12", topicId: "cfa-quantitative-methods-regression", text: "Multicollinearity in a multiple regression refers to:", optionA: "High correlation among the independent variables", optionB: "Correlated error terms", optionC: "Non-constant error variance", optionD: "A non-linear relationship", correctOption: "A", explanation: "Multicollinearity is a high correlation among two or more independent variables, inflating coefficient standard errors.", orderIndex: 11 },

  // ══ Economics ══
  // Market Structures — already the top-up subject? No, market-structures at 8. Add.
  { id: "cfa-economics-market-structures-q09", topicId: "cfa-economics-market-structures", text: "In perfect competition, firms are:", optionA: "Price takers producing identical products", optionB: "Price makers with unique products", optionC: "A single dominant seller", optionD: "Colluding oligopolists", correctOption: "A", explanation: "Perfectly competitive firms are price takers selling homogeneous products with free entry and exit.", orderIndex: 8 },
  { id: "cfa-economics-market-structures-q10", topicId: "cfa-economics-market-structures", text: "A market with a single seller and high barriers to entry is a:", optionA: "Monopoly", optionB: "Perfect competition", optionC: "Monopolistic competition", optionD: "Duopoly", correctOption: "A", explanation: "A monopoly has one seller of a product with no close substitutes and high entry barriers.", orderIndex: 9 },
  { id: "cfa-economics-market-structures-q11", topicId: "cfa-economics-market-structures", text: "The concentration of an industry is often measured by the:", optionA: "Herfindahl-Hirschman Index (HHI)", optionB: "Consumer Price Index", optionC: "Gini coefficient", optionD: "Sharpe ratio", correctOption: "A", explanation: "The HHI sums the squared market shares of firms to gauge industry concentration.", orderIndex: 10 },
  { id: "cfa-economics-market-structures-q12", topicId: "cfa-economics-market-structures", text: "A profit-maximising firm produces where:", optionA: "Marginal revenue equals marginal cost", optionB: "Price equals total cost", optionC: "Average cost is highest", optionD: "Revenue is highest", correctOption: "A", explanation: "Firms maximise profit at the output where marginal revenue equals marginal cost.", orderIndex: 11 },
  // GDP, Business Cycles & Economic Indicators
  { id: "cfa-economics-gdp-business-cycles-q09", topicId: "cfa-economics-gdp-business-cycles", text: "Under the expenditure approach, GDP equals:", optionA: "C + I + G + (X − M)", optionB: "Wages + rent + interest", optionC: "Exports − imports", optionD: "Consumption only", correctOption: "A", explanation: "GDP = consumption + investment + government spending + net exports.", orderIndex: 8 },
  { id: "cfa-economics-gdp-business-cycles-q10", topicId: "cfa-economics-gdp-business-cycles", text: "A recession is commonly defined as:", optionA: "Two consecutive quarters of declining real GDP", optionB: "One month of falling prices", optionC: "A rising stock market", optionD: "Any fall in nominal GDP", correctOption: "A", explanation: "A common rule of thumb defines a recession as two successive quarters of declining real GDP.", orderIndex: 9 },
  { id: "cfa-economics-gdp-business-cycles-q11", topicId: "cfa-economics-gdp-business-cycles", text: "Leading economic indicators are used to:", optionA: "Anticipate future economic activity", optionB: "Confirm past turning points", optionC: "Measure current output only", optionD: "Set tax rates", correctOption: "A", explanation: "Leading indicators (e.g., new orders, stock prices) tend to change before the overall economy does.", orderIndex: 10 },
  { id: "cfa-economics-gdp-business-cycles-q12", topicId: "cfa-economics-gdp-business-cycles", text: "Dividing nominal GDP by the GDP deflator (and scaling) gives:", optionA: "Real GDP", optionB: "Potential GDP", optionC: "Nominal GNP", optionD: "The unemployment rate", correctOption: "A", explanation: "Real GDP adjusts nominal GDP for price changes using the GDP deflator.", orderIndex: 11 },
  // Monetary & Fiscal Policy
  { id: "cfa-economics-monetary-fiscal-policy-q09", topicId: "cfa-economics-monetary-fiscal-policy", text: "Expansionary monetary policy typically involves:", optionA: "Lowering interest rates and increasing the money supply", optionB: "Raising reserve requirements", optionC: "Selling government bonds", optionD: "Cutting government spending", correctOption: "A", explanation: "Expansionary monetary policy eases financial conditions by lowering rates and expanding the money supply.", orderIndex: 8 },
  { id: "cfa-economics-monetary-fiscal-policy-q10", topicId: "cfa-economics-monetary-fiscal-policy", text: "A tool of contractionary fiscal policy is:", optionA: "Raising taxes or cutting government spending", optionB: "Lowering the policy rate", optionC: "Buying government securities", optionD: "Quantitative easing", correctOption: "A", explanation: "Fiscal policy works through taxes and government spending; contractionary fiscal policy raises taxes or cuts spending.", orderIndex: 9 },
  { id: "cfa-economics-monetary-fiscal-policy-q11", topicId: "cfa-economics-monetary-fiscal-policy", text: "To increase the money supply through open market operations, a central bank:", optionA: "Buys government securities", optionB: "Sells government securities", optionC: "Raises the reserve requirement", optionD: "Increases the discount rate", correctOption: "A", explanation: "Buying securities injects reserves into the banking system, expanding the money supply.", orderIndex: 10 },
  { id: "cfa-economics-monetary-fiscal-policy-q12", topicId: "cfa-economics-monetary-fiscal-policy", text: "The neutral policy interest rate is one that:", optionA: "Neither stimulates nor restrains the economy", optionB: "Is always zero", optionC: "Maximises inflation", optionD: "Equals the coupon rate on bonds", correctOption: "A", explanation: "The neutral rate is consistent with stable inflation and output at potential — neither expansionary nor contractionary.", orderIndex: 11 },
  // International Trade & Foreign Exchange
  { id: "cfa-economics-international-trade-forex-q09", topicId: "cfa-economics-international-trade-forex", text: "A country has a comparative advantage in a good when it can produce it at a lower:", optionA: "Opportunity cost", optionB: "Absolute quantity", optionC: "Selling price only", optionD: "Tax rate", correctOption: "A", explanation: "Comparative advantage rests on lower opportunity cost, not merely lower absolute cost.", orderIndex: 8 },
  { id: "cfa-economics-international-trade-forex-q10", topicId: "cfa-economics-international-trade-forex", text: "A tariff is best described as:", optionA: "A tax on imported goods", optionB: "A limit on export quantity", optionC: "A subsidy to consumers", optionD: "A currency peg", correctOption: "A", explanation: "A tariff is a tax levied on imports, raising their domestic price.", orderIndex: 9 },
  { id: "cfa-economics-international-trade-forex-q11", topicId: "cfa-economics-international-trade-forex", text: "In a direct exchange-rate quote, the rate is expressed as:", optionA: "Units of domestic currency per unit of foreign currency", optionB: "Units of foreign currency per domestic unit", optionC: "A percentage return", optionD: "The interest rate differential", correctOption: "A", explanation: "A direct quote states the price of one unit of foreign currency in domestic-currency terms.", orderIndex: 10 },
  { id: "cfa-economics-international-trade-forex-q12", topicId: "cfa-economics-international-trade-forex", text: "A quota differs from a tariff in that a quota:", optionA: "Limits the quantity of imports rather than taxing them", optionB: "Raises government tax revenue directly", optionC: "Applies only to exports", optionD: "Is a type of subsidy", correctOption: "A", explanation: "A quota caps the physical quantity of a good that may be imported, whereas a tariff taxes each unit.", orderIndex: 11 },
  // Geopolitics & Globalisation
  { id: "cfa-economics-geopolitics-globalisation-q09", topicId: "cfa-economics-geopolitics-globalisation", text: "Globalisation generally leads to:", optionA: "Greater cross-border trade and capital flows", optionB: "Reduced international trade", optionC: "Fewer multinational firms", optionD: "Higher tariffs everywhere", correctOption: "A", explanation: "Globalisation integrates economies through expanded trade, capital and labour flows.", orderIndex: 8 },
  { id: "cfa-economics-geopolitics-globalisation-q10", topicId: "cfa-economics-geopolitics-globalisation", text: "A country pursuing autarky seeks:", optionA: "Economic self-sufficiency with minimal trade", optionB: "Maximum exports", optionC: "A common currency", optionD: "Free capital flows", correctOption: "A", explanation: "Autarky is a policy of national economic self-sufficiency and non-cooperation with other economies.", orderIndex: 9 },
  { id: "cfa-economics-geopolitics-globalisation-q11", topicId: "cfa-economics-geopolitics-globalisation", text: "The risk that a government seizes foreign-owned assets is a form of:", optionA: "Political (nationalisation) risk", optionB: "Interest rate risk", optionC: "Liquidity risk", optionD: "Reinvestment risk", correctOption: "A", explanation: "Nationalisation or expropriation of assets is a political risk faced by cross-border investors.", orderIndex: 10 },
  { id: "cfa-economics-geopolitics-globalisation-q12", topicId: "cfa-economics-geopolitics-globalisation", text: "Regional trading blocs such as the EU primarily aim to:", optionA: "Reduce trade barriers among member countries", optionB: "Raise tariffs against members", optionC: "Fix all exchange rates globally", optionD: "Eliminate private capital", correctOption: "A", explanation: "Trading blocs lower or remove barriers among members to promote intra-bloc trade.", orderIndex: 11 },

  // ══ Financial Statement Analysis ══
  // Financial Ratios & Analysis
  { id: "cfa-financial-reporting-financial-ratios-analysis-q09", topicId: "cfa-financial-reporting-financial-ratios-analysis", text: "The current ratio is calculated as:", optionA: "Current assets / current liabilities", optionB: "Net income / sales", optionC: "Debt / equity", optionD: "Sales / total assets", correctOption: "A", explanation: "The current ratio, a liquidity measure, divides current assets by current liabilities.", orderIndex: 8 },
  { id: "cfa-financial-reporting-financial-ratios-analysis-q10", topicId: "cfa-financial-reporting-financial-ratios-analysis", text: "Return on equity (ROE) equals:", optionA: "Net income / average shareholders' equity", optionB: "Net income / total assets", optionC: "Gross profit / sales", optionD: "EBIT / interest", correctOption: "A", explanation: "ROE measures profit generated per unit of shareholders' equity.", orderIndex: 9 },
  { id: "cfa-financial-reporting-financial-ratios-analysis-q11", topicId: "cfa-financial-reporting-financial-ratios-analysis", text: "The three-part DuPont analysis decomposes ROE into net profit margin, asset turnover, and:", optionA: "Financial leverage", optionB: "The quick ratio", optionC: "Interest coverage", optionD: "The dividend payout", correctOption: "A", explanation: "DuPont: ROE = net profit margin × total asset turnover × financial leverage (equity multiplier).", orderIndex: 10 },
  { id: "cfa-financial-reporting-financial-ratios-analysis-q12", topicId: "cfa-financial-reporting-financial-ratios-analysis", text: "The quick (acid-test) ratio excludes which item from current assets?", optionA: "Inventory", optionB: "Cash", optionC: "Receivables", optionD: "Marketable securities", correctOption: "A", explanation: "The quick ratio excludes inventory (the least liquid current asset) from the numerator.", orderIndex: 11 },
  // Income Statement & Revenue Recognition
  { id: "cfa-financial-reporting-income-statement-q09", topicId: "cfa-financial-reporting-income-statement", text: "Under the converged revenue standard, revenue is recognised when:", optionA: "Control of the good or service transfers to the customer", optionB: "Cash is collected", optionC: "The contract is signed", optionD: "Production begins", correctOption: "A", explanation: "The five-step model recognises revenue as performance obligations are satisfied — when control transfers.", orderIndex: 8 },
  { id: "cfa-financial-reporting-income-statement-q10", topicId: "cfa-financial-reporting-income-statement", text: "Basic EPS equals:", optionA: "(Net income − preferred dividends) / weighted average common shares", optionB: "Net income / total assets", optionC: "Net income / ending shares", optionD: "Dividends / shares", correctOption: "A", explanation: "Basic EPS divides income available to common shareholders by the weighted average number of common shares.", orderIndex: 9 },
  { id: "cfa-financial-reporting-income-statement-q11", topicId: "cfa-financial-reporting-income-statement", text: "Gross profit is:", optionA: "Revenue minus cost of goods sold", optionB: "Revenue minus all expenses", optionC: "Operating income minus taxes", optionD: "Net income plus interest", correctOption: "A", explanation: "Gross profit equals revenue less the cost of goods sold.", orderIndex: 10 },
  { id: "cfa-financial-reporting-income-statement-q12", topicId: "cfa-financial-reporting-income-statement", text: "Recognising an expense in the same period as the revenue it helps generate reflects:", optionA: "The matching principle", optionB: "Conservatism", optionC: "The going-concern assumption", optionD: "Historical cost", correctOption: "A", explanation: "The matching principle recognises expenses in the period of the related revenues.", orderIndex: 11 },
  // Balance Sheet & Shareholders Equity
  { id: "cfa-financial-reporting-balance-sheet-equity-q09", topicId: "cfa-financial-reporting-balance-sheet-equity", text: "The basic accounting equation is:", optionA: "Assets = Liabilities + Equity", optionB: "Assets = Revenue − Expenses", optionC: "Equity = Assets + Liabilities", optionD: "Liabilities = Assets + Equity", correctOption: "A", explanation: "The balance sheet balances because assets are financed by liabilities plus owners' equity.", orderIndex: 8 },
  { id: "cfa-financial-reporting-balance-sheet-equity-q10", topicId: "cfa-financial-reporting-balance-sheet-equity", text: "Unrealised gains on debt securities measured at fair value through OCI are reported in:", optionA: "Other comprehensive income", optionB: "Net income", optionC: "Retained earnings directly", optionD: "Cost of goods sold", correctOption: "A", explanation: "For FVOCI (available-for-sale) debt securities, unrealised gains and losses bypass the income statement and go to OCI.", orderIndex: 9 },
  { id: "cfa-financial-reporting-balance-sheet-equity-q11", topicId: "cfa-financial-reporting-balance-sheet-equity", text: "Treasury stock is:", optionA: "A company's own repurchased shares, shown as a contra-equity item", optionB: "Government bonds held as assets", optionC: "A current liability", optionD: "Preferred stock issued", correctOption: "A", explanation: "Treasury stock is a firm's reacquired shares, reducing total shareholders' equity.", orderIndex: 10 },
  { id: "cfa-financial-reporting-balance-sheet-equity-q12", topicId: "cfa-financial-reporting-balance-sheet-equity", text: "Goodwill arises in an acquisition when the purchase price exceeds:", optionA: "The fair value of identifiable net assets acquired", optionB: "The book value of total assets", optionC: "Retained earnings", optionD: "The market capitalisation", correctOption: "A", explanation: "Goodwill is the excess of the purchase price over the fair value of identifiable net assets.", orderIndex: 11 },
  // Cash Flow Statement & FCF Analysis
  { id: "cfa-financial-reporting-cash-flow-statement-q09", topicId: "cfa-financial-reporting-cash-flow-statement", text: "Under US GAAP, interest paid is classified as a:", optionA: "Operating cash flow", optionB: "Financing cash flow", optionC: "Investing cash flow", optionD: "Non-cash item", correctOption: "A", explanation: "US GAAP requires interest paid to be reported in operating cash flows (IFRS allows operating or financing).", orderIndex: 8 },
  { id: "cfa-financial-reporting-cash-flow-statement-q10", topicId: "cfa-financial-reporting-cash-flow-statement", text: "The indirect method of preparing the cash flow statement begins with:", optionA: "Net income", optionB: "Cash receipts from customers", optionC: "Total revenue", optionD: "Ending cash balance", correctOption: "A", explanation: "The indirect method starts with net income and adjusts for non-cash items and working-capital changes.", orderIndex: 9 },
  { id: "cfa-financial-reporting-cash-flow-statement-q11", topicId: "cfa-financial-reporting-cash-flow-statement", text: "Free cash flow to the firm (FCFF) adds back to CFO the after-tax amount of:", optionA: "Interest expense", optionB: "Depreciation", optionC: "Dividends", optionD: "Taxes", correctOption: "A", explanation: "FCFF = CFO + interest×(1 − tax) − capex, adding back after-tax interest since FCFF is pre-financing.", orderIndex: 10 },
  { id: "cfa-financial-reporting-cash-flow-statement-q12", topicId: "cfa-financial-reporting-cash-flow-statement", text: "The purchase of new equipment is classified as a(n):", optionA: "Investing cash outflow", optionB: "Operating cash outflow", optionC: "Financing cash inflow", optionD: "Non-cash transaction", correctOption: "A", explanation: "Capital expenditures on long-lived assets are investing activities.", orderIndex: 11 },
  // Inventories, PP&E & Deferred Taxes
  { id: "cfa-financial-reporting-inventory-ppe-taxes-q09", topicId: "cfa-financial-reporting-inventory-ppe-taxes", text: "In a period of rising prices, the LIFO method (vs FIFO) produces:", optionA: "Higher COGS and lower net income", optionB: "Lower COGS and higher net income", optionC: "The same COGS", optionD: "Higher ending inventory", correctOption: "A", explanation: "LIFO expenses the most recent (higher) costs first, raising COGS and lowering reported income when prices rise.", orderIndex: 8 },
  { id: "cfa-financial-reporting-inventory-ppe-taxes-q10", topicId: "cfa-financial-reporting-inventory-ppe-taxes", text: "Under IFRS, inventory is carried at:", optionA: "The lower of cost and net realisable value", optionB: "Replacement cost always", optionC: "Historical cost only", optionD: "Fair value through profit or loss", correctOption: "A", explanation: "IFRS measures inventory at the lower of cost and net realisable value (LIFO is not permitted).", orderIndex: 9 },
  { id: "cfa-financial-reporting-inventory-ppe-taxes-q11", topicId: "cfa-financial-reporting-inventory-ppe-taxes", text: "A deferred tax liability generally arises when:", optionA: "Taxable income is temporarily lower than pretax accounting income", optionB: "The firm overpays taxes", optionC: "There is a permanent difference", optionD: "The tax rate is zero", correctOption: "A", explanation: "A DTL results from a temporary difference where accounting income exceeds taxable income now, reversing later.", orderIndex: 10 },
  { id: "cfa-financial-reporting-inventory-ppe-taxes-q12", topicId: "cfa-financial-reporting-inventory-ppe-taxes", text: "An accelerated depreciation method produces, relative to straight-line:", optionA: "Higher depreciation expense in the early years", optionB: "Constant expense each year", optionC: "Lower total depreciation", optionD: "No effect on net income", correctOption: "A", explanation: "Accelerated methods (e.g., double-declining balance) front-load depreciation into the early years.", orderIndex: 11 },

  // ══ Corporate Issuers ══
  // Cost of Capital
  { id: "cfa-corporate-issuers-cost-of-capital-q09", topicId: "cfa-corporate-issuers-cost-of-capital", text: "The weighted average cost of capital (WACC) weights the cost of each source of capital by its:", optionA: "Market-value proportion in the capital structure", optionB: "Book-value proportion only", optionC: "Coupon rate", optionD: "Dividend yield", correctOption: "A", explanation: "WACC uses market-value weights of debt, preferred and equity times their respective costs.", orderIndex: 8 },
  { id: "cfa-corporate-issuers-cost-of-capital-q10", topicId: "cfa-corporate-issuers-cost-of-capital", text: "The after-tax cost of debt equals the pre-tax cost of debt multiplied by:", optionA: "(1 − tax rate)", optionB: "(1 + tax rate)", optionC: "The tax rate", optionD: "The beta", correctOption: "A", explanation: "Interest is tax-deductible, so the after-tax cost of debt is rd × (1 − t).", orderIndex: 9 },
  { id: "cfa-corporate-issuers-cost-of-capital-q11", topicId: "cfa-corporate-issuers-cost-of-capital", text: "The CAPM estimates the cost of equity as:", optionA: "Risk-free rate + beta × (market risk premium)", optionB: "Dividend / price", optionC: "Risk-free rate only", optionD: "WACC minus debt cost", correctOption: "A", explanation: "CAPM: cost of equity = Rf + β(E[Rm] − Rf).", orderIndex: 10 },
  { id: "cfa-corporate-issuers-cost-of-capital-q12", topicId: "cfa-corporate-issuers-cost-of-capital", text: "A project's marginal cost of capital tends to ___ as more capital is raised.", optionA: "Increase", optionB: "Decrease", optionC: "Stay constant forever", optionD: "Fall to zero", correctOption: "A", explanation: "As a firm raises more capital, its marginal cost of capital generally rises (upward-sloping MCC schedule).", orderIndex: 11 },
  // Capital Structure & MM Theory
  { id: "cfa-corporate-issuers-capital-structure-q09", topicId: "cfa-corporate-issuers-capital-structure", text: "Modigliani-Miller Proposition I (no taxes) states that firm value is:", optionA: "Independent of the capital structure", optionB: "Maximised with all equity", optionC: "Maximised with all debt", optionD: "Equal to net income", correctOption: "A", explanation: "Under MM with no taxes, capital structure is irrelevant to firm value.", orderIndex: 8 },
  { id: "cfa-corporate-issuers-capital-structure-q10", topicId: "cfa-corporate-issuers-capital-structure", text: "With corporate taxes, MM shows firm value rises with debt because of:", optionA: "The interest tax shield", optionB: "Higher dividends", optionC: "Lower business risk", optionD: "Reduced leverage", correctOption: "A", explanation: "Tax-deductible interest creates a tax shield, so adding debt increases firm value in the MM-with-taxes model.", orderIndex: 9 },
  { id: "cfa-corporate-issuers-capital-structure-q11", topicId: "cfa-corporate-issuers-capital-structure", text: "The trade-off theory of capital structure balances the tax shield against:", optionA: "The costs of financial distress", optionB: "The dividend payout", optionC: "The cost of equity only", optionD: "Working capital needs", correctOption: "A", explanation: "The optimal structure trades off the tax benefit of debt against expected financial-distress and bankruptcy costs.", orderIndex: 10 },
  { id: "cfa-corporate-issuers-capital-structure-q12", topicId: "cfa-corporate-issuers-capital-structure", text: "Under the pecking-order theory, firms prefer to finance first with:", optionA: "Internally generated funds", optionB: "New equity", optionC: "Convertible bonds", optionD: "Preferred stock", correctOption: "A", explanation: "The pecking order is internal funds first, then debt, and new equity as a last resort.", orderIndex: 11 },
  // Dividends & Share Buybacks
  { id: "cfa-corporate-issuers-dividends-buybacks-q09", topicId: "cfa-corporate-issuers-dividends-buybacks", text: "On the ex-dividend date, a share price typically:", optionA: "Falls by approximately the dividend amount", optionB: "Rises by the dividend amount", optionC: "Is unchanged", optionD: "Doubles", correctOption: "A", explanation: "All else equal, the price drops by about the dividend on the ex-dividend date.", orderIndex: 8 },
  { id: "cfa-corporate-issuers-dividends-buybacks-q10", topicId: "cfa-corporate-issuers-dividends-buybacks", text: "A share repurchase, all else equal, tends to:", optionA: "Reduce shares outstanding and can raise EPS", optionB: "Increase shares outstanding", optionC: "Raise total equity", optionD: "Reduce the share price permanently", correctOption: "A", explanation: "Buybacks lower share count; if funded below the earnings yield they can increase EPS.", orderIndex: 9 },
  { id: "cfa-corporate-issuers-dividends-buybacks-q11", topicId: "cfa-corporate-issuers-dividends-buybacks", text: "A stock dividend:", optionA: "Increases shares outstanding but leaves total equity unchanged", optionB: "Reduces retained earnings to zero", optionC: "Pays cash to shareholders", optionD: "Increases total assets", correctOption: "A", explanation: "A stock dividend capitalises retained earnings into share capital; total equity and each holder's proportional stake are unchanged.", orderIndex: 10 },
  { id: "cfa-corporate-issuers-dividends-buybacks-q12", topicId: "cfa-corporate-issuers-dividends-buybacks", text: "The dividend payout ratio equals:", optionA: "Dividends / net income", optionB: "Dividends / share price", optionC: "Net income / dividends", optionD: "Retained earnings / assets", correctOption: "A", explanation: "The payout ratio is common dividends divided by net income.", orderIndex: 11 },
  // Corporate Governance & ESG
  { id: "cfa-corporate-issuers-corporate-governance-q09", topicId: "cfa-corporate-issuers-corporate-governance", text: "Corporate governance primarily addresses conflicts between:", optionA: "Managers and shareholders (the principal-agent problem)", optionB: "Customers and suppliers", optionC: "Auditors and regulators", optionD: "Employees and unions", correctOption: "A", explanation: "A central governance issue is the principal-agent conflict between owners (shareholders) and managers.", orderIndex: 8 },
  { id: "cfa-corporate-issuers-corporate-governance-q10", topicId: "cfa-corporate-issuers-corporate-governance", text: "In ESG analysis, the 'E' stands for:", optionA: "Environmental", optionB: "Economic", optionC: "Equity", optionD: "Efficiency", correctOption: "A", explanation: "ESG stands for Environmental, Social and Governance factors.", orderIndex: 9 },
  { id: "cfa-corporate-issuers-corporate-governance-q11", topicId: "cfa-corporate-issuers-corporate-governance", text: "A staggered (classified) board tends to:", optionA: "Entrench management and weaken shareholder control", optionB: "Strengthen shareholder rights", optionC: "Eliminate the CEO role", optionD: "Increase dividend payouts", correctOption: "A", explanation: "Because only part of a staggered board is elected each year, it makes takeovers and board change harder, entrenching management.", orderIndex: 10 },
  { id: "cfa-corporate-issuers-corporate-governance-q12", topicId: "cfa-corporate-issuers-corporate-governance", text: "Which of the following is a stakeholder in corporate governance?", optionA: "Creditors", optionB: "Only the CEO", optionC: "Only the board", optionD: "Only regulators", correctOption: "A", explanation: "Stakeholders include shareholders, creditors, employees, customers, suppliers and others affected by the firm.", orderIndex: 11 },
  // Business & Financial Leverage
  { id: "cfa-corporate-issuers-leverage-analysis-q09", topicId: "cfa-corporate-issuers-leverage-analysis", text: "The degree of operating leverage (DOL) measures the sensitivity of operating income to changes in:", optionA: "Units sold (revenue)", optionB: "Interest rates", optionC: "The tax rate", optionD: "Dividends", correctOption: "A", explanation: "DOL is the percentage change in operating income (EBIT) for a percentage change in units sold.", orderIndex: 8 },
  { id: "cfa-corporate-issuers-leverage-analysis-q10", topicId: "cfa-corporate-issuers-leverage-analysis", text: "The degree of financial leverage (DFL) measures the sensitivity of net income (EPS) to changes in:", optionA: "Operating income (EBIT)", optionB: "Sales units", optionC: "The dividend payout", optionD: "The share price", correctOption: "A", explanation: "DFL is the percentage change in EPS for a percentage change in EBIT, driven by fixed financing costs.", orderIndex: 9 },
  { id: "cfa-corporate-issuers-leverage-analysis-q11", topicId: "cfa-corporate-issuers-leverage-analysis", text: "A firm with higher fixed operating costs will generally have a:", optionA: "Higher degree of operating leverage", optionB: "Lower business risk", optionC: "Lower breakeven point", optionD: "Higher dividend payout", correctOption: "A", explanation: "Greater fixed costs magnify the effect of sales changes on operating income, raising DOL and business risk.", orderIndex: 10 },
  { id: "cfa-corporate-issuers-leverage-analysis-q12", topicId: "cfa-corporate-issuers-leverage-analysis", text: "The degree of total leverage (DTL) equals:", optionA: "DOL × DFL", optionB: "DOL + DFL", optionC: "DOL / DFL", optionD: "DFL − DOL", correctOption: "A", explanation: "Total leverage combines operating and financial leverage: DTL = DOL × DFL.", orderIndex: 11 },

  // ══ Equity Investments ══
  // Equity Valuation: DDM
  { id: "cfa-equity-equity-valuation-ddm-q09", topicId: "cfa-equity-equity-valuation-ddm", text: "The Gordon (constant) growth model values a share as:", optionA: "D₁ / (r − g)", optionB: "D₁ × (r − g)", optionC: "D₁ / (r + g)", optionD: "D₀ × r", correctOption: "A", explanation: "The Gordon growth model: value = next year's dividend ÷ (required return − growth rate).", orderIndex: 8 },
  { id: "cfa-equity-equity-valuation-ddm-q10", topicId: "cfa-equity-equity-valuation-ddm", text: "The Gordon growth model requires that the growth rate g be:", optionA: "Less than the required return r", optionB: "Greater than r", optionC: "Equal to r", optionD: "Negative", correctOption: "A", explanation: "The model only converges when g < r; otherwise the denominator is non-positive.", orderIndex: 9 },
  { id: "cfa-equity-equity-valuation-ddm-q11", topicId: "cfa-equity-equity-valuation-ddm", text: "The sustainable growth rate equals:", optionA: "Retention ratio × ROE", optionB: "Payout ratio × ROE", optionC: "ROE / dividend", optionD: "Dividend yield × r", correctOption: "A", explanation: "g = b × ROE, where b is the earnings retention ratio (1 − payout).", orderIndex: 10 },
  { id: "cfa-equity-equity-valuation-ddm-q12", topicId: "cfa-equity-equity-valuation-ddm", text: "A multistage DDM is most appropriate for a firm that is:", optionA: "Growing rapidly now but expected to settle to stable growth later", optionB: "Paying no dividends ever", optionC: "In constant growth from day one", optionD: "About to be liquidated", correctOption: "A", explanation: "Multistage models handle firms with high near-term growth that transitions to a stable long-run rate.", orderIndex: 11 },
  // Market Organisation & Efficiency
  { id: "cfa-equity-market-organisation-efficiency-q09", topicId: "cfa-equity-market-organisation-efficiency", text: "In a semi-strong-form efficient market, prices fully reflect:", optionA: "All publicly available information", optionB: "Only past prices", optionC: "All public and private information", optionD: "No information", correctOption: "A", explanation: "Semi-strong efficiency means public information is already impounded in prices, so fundamental analysis can't earn abnormal returns.", orderIndex: 8 },
  { id: "cfa-equity-market-organisation-efficiency-q10", topicId: "cfa-equity-market-organisation-efficiency", text: "A short sale involves:", optionA: "Selling borrowed securities in the hope of buying them back cheaper", optionB: "Buying on margin", optionC: "Writing a covered call", optionD: "Holding to maturity", correctOption: "A", explanation: "A short seller borrows and sells a security, aiming to profit if the price falls.", orderIndex: 9 },
  { id: "cfa-equity-market-organisation-efficiency-q11", topicId: "cfa-equity-market-organisation-efficiency", text: "A margin call is triggered when the investor's equity falls below the:", optionA: "Maintenance margin", optionB: "Initial margin", optionC: "Coupon rate", optionD: "Bid-ask spread", correctOption: "A", explanation: "If account equity drops below the maintenance margin, the broker issues a margin call for more funds.", orderIndex: 10 },
  { id: "cfa-equity-market-organisation-efficiency-q12", topicId: "cfa-equity-market-organisation-efficiency", text: "If markets are weak-form efficient, which approach cannot produce abnormal returns?", optionA: "Technical analysis", optionB: "Insider trading", optionC: "Private information use", optionD: "Fundamental analysis", correctOption: "A", explanation: "Weak-form efficiency means past prices are already reflected, so technical analysis cannot earn abnormal returns.", orderIndex: 11 },
  // Industry & Company Analysis
  { id: "cfa-equity-industry-company-analysis-q09", topicId: "cfa-equity-industry-company-analysis", text: "Porter's five forces include rivalry, threat of new entrants, threat of substitutes, and the bargaining power of buyers and:", optionA: "Suppliers", optionB: "Regulators", optionC: "Employees", optionD: "Auditors", correctOption: "A", explanation: "The fifth force is the bargaining power of suppliers.", orderIndex: 8 },
  { id: "cfa-equity-industry-company-analysis-q10", topicId: "cfa-equity-industry-company-analysis", text: "A cyclical company is one whose earnings are:", optionA: "Highly sensitive to the business cycle", optionB: "Stable regardless of the economy", optionC: "Independent of demand", optionD: "Always growing", correctOption: "A", explanation: "Cyclical firms (e.g., autos, steel) see earnings rise and fall sharply with the economic cycle.", orderIndex: 9 },
  { id: "cfa-equity-industry-company-analysis-q11", topicId: "cfa-equity-industry-company-analysis", text: "High barriers to entry in an industry tend to support:", optionA: "More sustainable margins and pricing power", optionB: "Rapid new competition", optionC: "Lower profitability", optionD: "Commoditised products", correctOption: "A", explanation: "Barriers to entry protect incumbents, supporting higher, more durable profitability.", orderIndex: 10 },
  { id: "cfa-equity-industry-company-analysis-q12", topicId: "cfa-equity-industry-company-analysis", text: "Grouping companies by their principal business activity is called:", optionA: "Industry classification", optionB: "Credit rating", optionC: "Index weighting", optionD: "Sector rotation", correctOption: "A", explanation: "Industry classification systems group firms by their main products or activities for comparison.", orderIndex: 11 },
  // DCF & Free Cash Flow Valuation
  { id: "cfa-equity-dcf-fcf-valuation-q09", topicId: "cfa-equity-dcf-fcf-valuation", text: "Free cash flow to the firm (FCFF) is the cash available to:", optionA: "All capital providers (debt and equity)", optionB: "Common shareholders only", optionC: "Preferred holders only", optionD: "Bondholders only", correctOption: "A", explanation: "FCFF is pre-financing cash flow available to all suppliers of capital.", orderIndex: 8 },
  { id: "cfa-equity-dcf-fcf-valuation-q10", topicId: "cfa-equity-dcf-fcf-valuation", text: "Free cash flow to equity (FCFE) is the cash available to:", optionA: "Common equity holders", optionB: "All capital providers", optionC: "The government", optionD: "Suppliers", correctOption: "A", explanation: "FCFE is the cash flow left for common shareholders after debt payments and reinvestment.", orderIndex: 9 },
  { id: "cfa-equity-dcf-fcf-valuation-q11", topicId: "cfa-equity-dcf-fcf-valuation", text: "In a DCF valuation, the terminal value is frequently estimated using:", optionA: "The Gordon (constant) growth model", optionB: "The current P/E only", optionC: "Book value", optionD: "The coupon rate", correctOption: "A", explanation: "A common terminal-value approach applies constant-growth (Gordon) assumptions to the final forecast cash flow.", orderIndex: 10 },
  { id: "cfa-equity-dcf-fcf-valuation-q12", topicId: "cfa-equity-dcf-fcf-valuation", text: "FCFF should be discounted at the:", optionA: "Weighted average cost of capital (WACC)", optionB: "Cost of equity", optionC: "Risk-free rate", optionD: "Coupon rate", correctOption: "A", explanation: "Because FCFF belongs to all providers of capital, it is discounted at the WACC; FCFE uses the cost of equity.", orderIndex: 11 },
  // Price Multiples & EV Analysis
  { id: "cfa-equity-price-multiples-ev-q09", topicId: "cfa-equity-price-multiples-ev", text: "The price-to-earnings (P/E) ratio equals:", optionA: "Price per share / earnings per share", optionB: "Earnings / price", optionC: "Price / sales", optionD: "Dividend / price", correctOption: "A", explanation: "The P/E ratio divides the share price by earnings per share.", orderIndex: 8 },
  { id: "cfa-equity-price-multiples-ev-q10", topicId: "cfa-equity-price-multiples-ev", text: "Enterprise value (EV) is calculated as:", optionA: "Market value of equity + debt − cash", optionB: "Market cap only", optionC: "Total assets − liabilities", optionD: "Net income × P/E", correctOption: "A", explanation: "EV adds net debt to equity value: market cap + total debt − cash and equivalents.", orderIndex: 9 },
  { id: "cfa-equity-price-multiples-ev-q11", topicId: "cfa-equity-price-multiples-ev", text: "The justified leading P/E under constant growth equals:", optionA: "Payout ratio / (r − g)", optionB: "(r − g) / payout", optionC: "1 / (r + g)", optionD: "ROE × payout", correctOption: "A", explanation: "Dividing the Gordon model by earnings gives leading P/E = payout / (r − g).", orderIndex: 10 },
  { id: "cfa-equity-price-multiples-ev-q12", topicId: "cfa-equity-price-multiples-ev", text: "EV/EBITDA is often preferred to P/E because it is:", optionA: "Independent of capital structure", optionB: "Based only on dividends", optionC: "Unaffected by operations", optionD: "Always lower", correctOption: "A", explanation: "EV/EBITDA is capital-structure neutral and can compare firms with different leverage or tax positions.", orderIndex: 11 },

  // ══ Fixed Income ══
  // Duration & Convexity
  { id: "cfa-fixed-income-duration-convexity-q09", topicId: "cfa-fixed-income-duration-convexity", text: "Modified duration measures a bond's price sensitivity to:", optionA: "A change in its yield", optionB: "A change in the coupon", optionC: "Time to the next coupon", optionD: "The credit rating", correctOption: "A", explanation: "Modified duration estimates the percentage price change for a 1% change in yield.", orderIndex: 8 },
  { id: "cfa-fixed-income-duration-convexity-q10", topicId: "cfa-fixed-income-duration-convexity", text: "All else equal, a bond with a longer maturity has a:", optionA: "Higher duration", optionB: "Lower duration", optionC: "Zero duration", optionD: "Negative duration", correctOption: "A", explanation: "Longer maturity generally raises duration and interest-rate sensitivity.", orderIndex: 9 },
  { id: "cfa-fixed-income-duration-convexity-q11", topicId: "cfa-fixed-income-duration-convexity", text: "Convexity captures the fact that the price-yield relationship of an option-free bond is:", optionA: "Curved, not linear", optionB: "Perfectly linear", optionC: "Always downward-sloping to zero", optionD: "Flat", correctOption: "A", explanation: "Duration is a linear approximation; convexity corrects for the curvature of the price-yield curve.", orderIndex: 10 },
  { id: "cfa-fixed-income-duration-convexity-q12", topicId: "cfa-fixed-income-duration-convexity", text: "A higher coupon rate, all else equal, results in a:", optionA: "Lower duration", optionB: "Higher duration", optionC: "Unchanged duration", optionD: "Negative duration", correctOption: "A", explanation: "Higher coupons return cash sooner, lowering the bond's duration.", orderIndex: 11 },
  // Bond Features & Valuation
  { id: "cfa-fixed-income-bond-features-valuation-q09", topicId: "cfa-fixed-income-bond-features-valuation", text: "The price of a bond equals the present value of its:", optionA: "Coupon payments and principal repayment", optionB: "Coupon payments only", optionC: "Face value only", optionD: "Dividends", correctOption: "A", explanation: "A bond's value is the discounted sum of its coupons and its par (principal) repayment.", orderIndex: 8 },
  { id: "cfa-fixed-income-bond-features-valuation-q10", topicId: "cfa-fixed-income-bond-features-valuation", text: "When the market yield exceeds the coupon rate, the bond trades at a:", optionA: "Discount to par", optionB: "Premium to par", optionC: "Price equal to par", optionD: "Price of zero", correctOption: "A", explanation: "If required yield > coupon, the bond's price is below par (a discount).", orderIndex: 9 },
  { id: "cfa-fixed-income-bond-features-valuation-q11", topicId: "cfa-fixed-income-bond-features-valuation", text: "Relative to an otherwise identical option-free bond, a callable bond typically has a:", optionA: "Lower price and higher yield", optionB: "Higher price and lower yield", optionC: "The same price", optionD: "Zero yield", correctOption: "A", explanation: "The call option benefits the issuer, so investors demand a higher yield (lower price).", orderIndex: 10 },
  { id: "cfa-fixed-income-bond-features-valuation-q12", topicId: "cfa-fixed-income-bond-features-valuation", text: "A zero-coupon bond is issued at:", optionA: "A discount to par, paying par at maturity", optionB: "A premium to par", optionC: "Par value with coupons", optionD: "Above par always", correctOption: "A", explanation: "Zero-coupon bonds pay no periodic interest and are issued below par, returning full par at maturity.", orderIndex: 11 },
  // Yield Measures & Term Structure
  { id: "cfa-fixed-income-yield-measures-term-structure-q09", topicId: "cfa-fixed-income-yield-measures-term-structure", text: "Yield to maturity assumes that coupons are reinvested at:", optionA: "The yield to maturity", optionB: "The coupon rate", optionC: "The risk-free rate", optionD: "Zero", correctOption: "A", explanation: "The YTM realised return assumes all coupons are reinvested at the YTM and the bond is held to maturity.", orderIndex: 8 },
  { id: "cfa-fixed-income-yield-measures-term-structure-q10", topicId: "cfa-fixed-income-yield-measures-term-structure", text: "The yield curve plots yield against:", optionA: "Time to maturity", optionB: "Credit rating", optionC: "Coupon rate", optionD: "Issue size", correctOption: "A", explanation: "The (spot/yield) curve shows yields across different maturities for similar-quality bonds.", orderIndex: 9 },
  { id: "cfa-fixed-income-yield-measures-term-structure-q11", topicId: "cfa-fixed-income-yield-measures-term-structure", text: "A normal (upward-sloping) yield curve has long-term yields that are:", optionA: "Higher than short-term yields", optionB: "Lower than short-term yields", optionC: "Equal to short-term yields", optionD: "Always negative", correctOption: "A", explanation: "A normal curve slopes upward, with longer maturities offering higher yields.", orderIndex: 10 },
  { id: "cfa-fixed-income-yield-measures-term-structure-q12", topicId: "cfa-fixed-income-yield-measures-term-structure", text: "The spread of a corporate bond over a government benchmark compensates mainly for:", optionA: "Credit and liquidity risk", optionB: "Reinvestment of coupons", optionC: "Currency risk only", optionD: "Inflation only", correctOption: "A", explanation: "The credit spread compensates investors for default (credit) and liquidity risk relative to government bonds.", orderIndex: 11 },
  // Credit Risk & Credit Analysis
  { id: "cfa-fixed-income-credit-risk-analysis-q09", topicId: "cfa-fixed-income-credit-risk-analysis", text: "Credit risk comprises default risk and:", optionA: "Credit spread (migration) risk", optionB: "Reinvestment risk", optionC: "Purchasing-power risk", optionD: "Call risk", correctOption: "A", explanation: "Credit risk includes the risk of default and the risk that spreads widen or the rating is downgraded.", orderIndex: 8 },
  { id: "cfa-fixed-income-credit-risk-analysis-q10", topicId: "cfa-fixed-income-credit-risk-analysis", text: "The 'four Cs' of credit analysis include capacity, collateral, covenants, and:", optionA: "Character", optionB: "Cash only", optionC: "Convexity", optionD: "Coupon", correctOption: "A", explanation: "The four Cs are capacity, collateral, covenants and character.", orderIndex: 9 },
  { id: "cfa-fixed-income-credit-risk-analysis-q11", topicId: "cfa-fixed-income-credit-risk-analysis", text: "A bond is considered investment grade if it is rated at least:", optionA: "BBB− / Baa3", optionB: "BB+ / Ba1", optionC: "CCC / Caa", optionD: "D", correctOption: "A", explanation: "Investment-grade bonds are rated BBB−/Baa3 or higher; below that is high-yield (speculative).", orderIndex: 10 },
  { id: "cfa-fixed-income-credit-risk-analysis-q12", topicId: "cfa-fixed-income-credit-risk-analysis", text: "Expected loss on a bond is approximately:", optionA: "Probability of default × loss given default", optionB: "Coupon × maturity", optionC: "Duration × yield", optionD: "Par − coupon", correctOption: "A", explanation: "Expected loss = probability of default × loss given default (times exposure).", orderIndex: 11 },
  // Securitisation & Asset-Backed Securities
  { id: "cfa-fixed-income-securitisation-abs-q09", topicId: "cfa-fixed-income-securitisation-abs", text: "Securitisation involves:", optionA: "Pooling assets and issuing securities backed by their cash flows", optionB: "Issuing common equity", optionC: "Buying back debt", optionD: "Paying dividends", correctOption: "A", explanation: "Securitisation pools financial assets (e.g., loans) and sells claims on their cash flows to investors.", orderIndex: 8 },
  { id: "cfa-fixed-income-securitisation-abs-q10", topicId: "cfa-fixed-income-securitisation-abs", text: "Mortgage-backed securities are particularly exposed to:", optionA: "Prepayment risk", optionB: "Currency risk", optionC: "Equity risk", optionD: "Commodity risk", correctOption: "A", explanation: "Borrowers can prepay mortgages, creating prepayment (contraction/extension) risk for MBS investors.", orderIndex: 9 },
  { id: "cfa-fixed-income-securitisation-abs-q11", topicId: "cfa-fixed-income-securitisation-abs", text: "In a securitisation, the pooled assets are typically held by a:", optionA: "Special purpose vehicle (SPV/SPE)", optionB: "Central bank", optionC: "Stock exchange", optionD: "Rating agency", correctOption: "A", explanation: "A bankruptcy-remote SPV holds the assets, isolating them from the originator's credit risk.", orderIndex: 10 },
  { id: "cfa-fixed-income-securitisation-abs-q12", topicId: "cfa-fixed-income-securitisation-abs", text: "In a tranched structure, losses are absorbed first by the:", optionA: "Most junior (equity) tranche", optionB: "Most senior tranche", optionC: "SPV sponsor", optionD: "Rating agency", correctOption: "A", explanation: "Subordination means the junior/equity tranche takes first losses, protecting senior tranches.", orderIndex: 11 },

  // ══ Derivatives ══
  // Options: Put-Call Parity
  { id: "cfa-derivatives-options-put-call-parity-q09", topicId: "cfa-derivatives-options-put-call-parity", text: "Put-call parity for European options states that a call plus the PV of the strike equals:", optionA: "A put plus the underlying asset", optionB: "Two calls", optionC: "The strike price", optionD: "A forward minus a put", correctOption: "A", explanation: "c + PV(X) = p + S₀ links the prices of European calls and puts on the same underlying and strike.", orderIndex: 8 },
  { id: "cfa-derivatives-options-put-call-parity-q10", topicId: "cfa-derivatives-options-put-call-parity", text: "A call option gives the holder the right to:", optionA: "Buy the underlying at the strike price", optionB: "Sell the underlying at the strike", optionC: "Receive a fixed coupon", optionD: "Short the underlying", correctOption: "A", explanation: "A call is the right (not obligation) to buy the underlying at the exercise (strike) price.", orderIndex: 9 },
  { id: "cfa-derivatives-options-put-call-parity-q11", topicId: "cfa-derivatives-options-put-call-parity", text: "The intrinsic value of a call option is:", optionA: "Max(0, S − X)", optionB: "Max(0, X − S)", optionC: "S + X", optionD: "The premium paid", correctOption: "A", explanation: "A call's intrinsic value is the greater of zero and the underlying price minus the strike.", orderIndex: 10 },
  { id: "cfa-derivatives-options-put-call-parity-q12", topicId: "cfa-derivatives-options-put-call-parity", text: "Deviations from put-call parity create opportunities for:", optionA: "Riskless arbitrage", optionB: "Guaranteed losses", optionC: "Dividend capture", optionD: "Higher taxes", correctOption: "A", explanation: "If parity is violated, arbitrageurs can construct a riskless profit until prices realign.", orderIndex: 11 },
  // Forwards & Futures Pricing
  { id: "cfa-derivatives-forwards-futures-q09", topicId: "cfa-derivatives-forwards-futures", text: "Compared with forwards, futures contracts are:", optionA: "Exchange-traded and standardised", optionB: "Always customised", optionC: "Free of counterparty oversight", optionD: "Non-transferable", correctOption: "A", explanation: "Futures are standardised, exchange-traded and centrally cleared, unlike customised OTC forwards.", orderIndex: 8 },
  { id: "cfa-derivatives-forwards-futures-q10", topicId: "cfa-derivatives-forwards-futures", text: "Futures positions are marked to market:", optionA: "Daily", optionB: "Only at expiry", optionC: "Monthly", optionD: "Never", correctOption: "A", explanation: "Daily settlement (marking to market) adjusts margin accounts each day, reducing counterparty risk.", orderIndex: 9 },
  { id: "cfa-derivatives-forwards-futures-q11", topicId: "cfa-derivatives-forwards-futures", text: "The party that agrees to buy the underlying in a forward contract holds the:", optionA: "Long position", optionB: "Short position", optionC: "Option to cancel", optionD: "Call option", correctOption: "A", explanation: "The buyer is long the forward; the seller is short.", orderIndex: 10 },
  { id: "cfa-derivatives-forwards-futures-q12", topicId: "cfa-derivatives-forwards-futures", text: "When the futures price is above the spot price, the market is said to be in:", optionA: "Contango", optionB: "Backwardation", optionC: "Equilibrium", optionD: "Default", correctOption: "A", explanation: "Contango is when futures trade above spot (often reflecting positive cost of carry).", orderIndex: 11 },
  // Swaps: Interest Rate & Currency
  { id: "cfa-derivatives-swaps-q09", topicId: "cfa-derivatives-swaps", text: "A plain-vanilla interest rate swap exchanges:", optionA: "Fixed-rate for floating-rate interest payments", optionB: "Two floating rates", optionC: "Principal for dividends", optionD: "Equity for debt", correctOption: "A", explanation: "In a plain-vanilla swap, one party pays fixed and receives floating (or vice versa) on a notional principal.", orderIndex: 8 },
  { id: "cfa-derivatives-swaps-q10", topicId: "cfa-derivatives-swaps", text: "A swap can be analytically viewed as:", optionA: "A series of forward contracts", optionB: "A single option", optionC: "A perpetual bond", optionD: "A stock index", correctOption: "A", explanation: "A swap is economically equivalent to a portfolio of forward contracts on successive settlement dates.", orderIndex: 9 },
  { id: "cfa-derivatives-swaps-q11", topicId: "cfa-derivatives-swaps", text: "In a currency swap, the counterparties exchange:", optionA: "Principal and interest in two different currencies", optionB: "Only floating interest", optionC: "Equity dividends", optionD: "Commodity deliveries", correctOption: "A", explanation: "Currency swaps exchange principal and interest payments denominated in different currencies.", orderIndex: 10 },
  { id: "cfa-derivatives-swaps-q12", topicId: "cfa-derivatives-swaps", text: "At initiation, the value of a plain-vanilla interest rate swap is:", optionA: "Approximately zero", optionB: "Equal to the notional", optionC: "Equal to the fixed leg", optionD: "Negative for both parties", correctOption: "A", explanation: "The fixed rate is set so the swap has zero value to both parties at inception.", orderIndex: 11 },
  // Option Strategies & Greeks
  { id: "cfa-derivatives-option-strategies-q09", topicId: "cfa-derivatives-option-strategies", text: "A protective put combines a long position in the underlying with a:", optionA: "Long put", optionB: "Short put", optionC: "Long call", optionD: "Short call", correctOption: "A", explanation: "A protective put buys a put to insure a long stock position against downside.", orderIndex: 8 },
  { id: "cfa-derivatives-option-strategies-q10", topicId: "cfa-derivatives-option-strategies", text: "A covered call combines a long position in the underlying with a:", optionA: "Short call", optionB: "Long call", optionC: "Long put", optionD: "Short put", correctOption: "A", explanation: "A covered call writes (sells) a call against stock owned, earning premium but capping upside.", orderIndex: 9 },
  { id: "cfa-derivatives-option-strategies-q11", topicId: "cfa-derivatives-option-strategies", text: "Delta measures the sensitivity of an option's price to a change in:", optionA: "The underlying asset's price", optionB: "Time to expiry", optionC: "Volatility", optionD: "The risk-free rate", correctOption: "A", explanation: "Delta is the change in option price for a small change in the underlying price.", orderIndex: 10 },
  { id: "cfa-derivatives-option-strategies-q12", topicId: "cfa-derivatives-option-strategies", text: "The maximum loss for the buyer of a call option is:", optionA: "The premium paid", optionB: "Unlimited", optionC: "The strike price", optionD: "The underlying price", correctOption: "A", explanation: "A long call's loss is limited to the premium; its upside is theoretically unlimited.", orderIndex: 11 },
  // Risk Management Applications of Derivatives
  { id: "cfa-derivatives-risk-management-applications-q09", topicId: "cfa-derivatives-risk-management-applications", text: "To hedge the downside of a long equity holding, an investor could:", optionA: "Buy put options", optionB: "Buy call options", optionC: "Write puts", optionD: "Buy more stock", correctOption: "A", explanation: "Buying puts (or selling index futures) protects a long equity position against price declines.", orderIndex: 8 },
  { id: "cfa-derivatives-risk-management-applications-q10", topicId: "cfa-derivatives-risk-management-applications", text: "A forward rate agreement (FRA) is used to manage:", optionA: "Interest rate risk", optionB: "Equity risk", optionC: "Commodity price risk", optionD: "Currency translation risk", correctOption: "A", explanation: "An FRA locks in an interest rate on a future borrowing or deposit, hedging rate risk.", orderIndex: 9 },
  { id: "cfa-derivatives-risk-management-applications-q11", topicId: "cfa-derivatives-risk-management-applications", text: "An interest rate cap protects a floating-rate borrower against:", optionA: "Rising interest rates", optionB: "Falling interest rates", optionC: "Currency depreciation", optionD: "Equity declines", correctOption: "A", explanation: "A cap pays off when rates rise above the strike, limiting a floating-rate borrower's cost.", orderIndex: 10 },
  { id: "cfa-derivatives-risk-management-applications-q12", topicId: "cfa-derivatives-risk-management-applications", text: "A key advantage of using derivatives to adjust portfolio risk is:", optionA: "Lower transaction costs and greater flexibility than trading the underlying", optionB: "The elimination of all risk", optionC: "Guaranteed profits", optionD: "No need for margin", correctOption: "A", explanation: "Derivatives let managers change exposures quickly and cheaply without trading the underlying assets.", orderIndex: 11 },

  // ══ Alternative Investments ══
  // Hedge Funds & Private Equity
  { id: "cfa-alternative-investments-hedge-funds-private-equity-q09", topicId: "cfa-alternative-investments-hedge-funds-private-equity", text: "A leveraged buyout (LBO) is a private equity strategy that acquires a company primarily using:", optionA: "A large amount of borrowed money", optionB: "Only common equity", optionC: "Government grants", optionD: "Retained earnings", correctOption: "A", explanation: "In an LBO, a firm is bought using significant debt, with the target's cash flows servicing the borrowing.", orderIndex: 8 },
  { id: "cfa-alternative-investments-hedge-funds-private-equity-q10", topicId: "cfa-alternative-investments-hedge-funds-private-equity", text: "Venture capital typically invests in companies that are:", optionA: "Early-stage and high-growth", optionB: "Large and mature", optionC: "About to be liquidated", optionD: "Government-owned", correctOption: "A", explanation: "Venture capital funds early-stage, high-growth private companies.", orderIndex: 9 },
  { id: "cfa-alternative-investments-hedge-funds-private-equity-q11", topicId: "cfa-alternative-investments-hedge-funds-private-equity", text: "A market-neutral hedge fund strategy aims to:", optionA: "Remove overall market exposure by balancing longs and shorts", optionB: "Take only long positions", optionC: "Maximise market beta", optionD: "Hold cash only", correctOption: "A", explanation: "Market-neutral funds offset long and short positions to profit from relative moves with little net market exposure.", orderIndex: 10 },
  { id: "cfa-alternative-investments-hedge-funds-private-equity-q12", topicId: "cfa-alternative-investments-hedge-funds-private-equity", text: "Private equity investments are characterised by:", optionA: "Illiquidity and long lock-up periods", optionB: "Daily liquidity", optionC: "Exchange listing", optionD: "Guaranteed returns", correctOption: "A", explanation: "PE capital is typically committed for years with limited liquidity until an exit.", orderIndex: 11 },
  // Real Estate Investments
  { id: "cfa-alternative-investments-real-estate-q09", topicId: "cfa-alternative-investments-real-estate", text: "A REIT is:", optionA: "A company or trust owning income-producing real estate that trades like a stock", optionB: "A government housing agency", optionC: "A type of mortgage", optionD: "A commodity fund", correctOption: "A", explanation: "A real estate investment trust holds property assets and is typically publicly traded, distributing most income.", orderIndex: 8 },
  { id: "cfa-alternative-investments-real-estate-q10", topicId: "cfa-alternative-investments-real-estate", text: "Under the direct capitalisation (income) approach, property value equals:", optionA: "Net operating income / capitalisation rate", optionB: "NOI × cap rate", optionC: "Rent × 10", optionD: "Cost minus depreciation", correctOption: "A", explanation: "Value = NOI ÷ cap rate under the income approach.", orderIndex: 9 },
  { id: "cfa-alternative-investments-real-estate-q11", topicId: "cfa-alternative-investments-real-estate", text: "Net operating income (NOI) is:", optionA: "Rental income minus operating expenses, before financing and taxes", optionB: "Net income after taxes", optionC: "Gross rent only", optionD: "Cash flow after debt service", correctOption: "A", explanation: "NOI is property revenue less operating expenses, excluding financing costs and taxes.", orderIndex: 10 },
  { id: "cfa-alternative-investments-real-estate-q12", topicId: "cfa-alternative-investments-real-estate", text: "A key portfolio benefit of real estate is:", optionA: "Diversification through low correlation with stocks and bonds", optionB: "Daily liquidity", optionC: "Zero maintenance cost", optionD: "Guaranteed appreciation", correctOption: "A", explanation: "Real estate historically has relatively low correlation with traditional assets, aiding diversification and income.", orderIndex: 11 },
  // Commodities & Commodity Derivatives
  { id: "cfa-alternative-investments-commodities-q09", topicId: "cfa-alternative-investments-commodities", text: "Investors most commonly gain commodity exposure through:", optionA: "Derivatives such as futures", optionB: "Physical storage of the commodity", optionC: "Corporate bonds", optionD: "Bank deposits", correctOption: "A", explanation: "Because physical storage is costly, most investors use commodity futures and related derivatives.", orderIndex: 8 },
  { id: "cfa-alternative-investments-commodities-q10", topicId: "cfa-alternative-investments-commodities", text: "The total return on a commodity futures position includes the spot return, the collateral return, and the:", optionA: "Roll return", optionB: "Dividend yield", optionC: "Coupon return", optionD: "Franking credit", correctOption: "A", explanation: "Commodity futures total return = spot (price) + collateral (risk-free) + roll return.", orderIndex: 9 },
  { id: "cfa-alternative-investments-commodities-q11", topicId: "cfa-alternative-investments-commodities", text: "A commodity futures market in backwardation has futures prices:", optionA: "Below the spot price", optionB: "Above the spot price", optionC: "Equal to spot", optionD: "At zero", correctOption: "A", explanation: "Backwardation is when futures trade below spot; contango is the opposite.", orderIndex: 10 },
  { id: "cfa-alternative-investments-commodities-q12", topicId: "cfa-alternative-investments-commodities", text: "Commodities are frequently held to hedge against:", optionA: "Inflation", optionB: "Deflation", optionC: "Currency appreciation", optionD: "Interest income", correctOption: "A", explanation: "Commodity prices often rise with inflation, giving them a role as an inflation hedge.", orderIndex: 11 },
  // Infrastructure & Other Alternatives
  { id: "cfa-alternative-investments-infrastructure-q09", topicId: "cfa-alternative-investments-infrastructure", text: "Infrastructure investments typically offer:", optionA: "Stable, long-term cash flows", optionB: "Highly volatile short-term returns", optionC: "No income", optionD: "Daily liquidity", correctOption: "A", explanation: "Infrastructure assets (toll roads, utilities) generally provide steady, long-duration cash flows.", orderIndex: 8 },
  { id: "cfa-alternative-investments-infrastructure-q10", topicId: "cfa-alternative-investments-infrastructure", text: "A 'brownfield' infrastructure investment involves:", optionA: "Existing operational assets", optionB: "New construction from scratch", optionC: "Undeveloped land only", optionD: "Distressed equities", correctOption: "A", explanation: "Brownfield refers to existing assets; greenfield refers to new construction.", orderIndex: 9 },
  { id: "cfa-alternative-investments-infrastructure-q11", topicId: "cfa-alternative-investments-infrastructure", text: "Infrastructure assets often exhibit:", optionA: "High barriers to entry and monopolistic characteristics", optionB: "Intense daily competition", optionC: "Rapid obsolescence", optionD: "No regulation", correctOption: "A", explanation: "Many infrastructure assets are natural monopolies with high entry barriers and regulated returns.", orderIndex: 10 },
  { id: "cfa-alternative-investments-infrastructure-q12", topicId: "cfa-alternative-investments-infrastructure", text: "A common way governments involve private capital in infrastructure is through a:", optionA: "Public-private partnership (PPP)", optionB: "Central bank swap", optionC: "Stock buyback", optionD: "Tax amnesty", correctOption: "A", explanation: "PPPs share the financing, risks and returns of infrastructure between government and private investors.", orderIndex: 11 },
  // Due Diligence & Performance Evaluation
  { id: "cfa-alternative-investments-due-diligence-q09", topicId: "cfa-alternative-investments-due-diligence", text: "The classic hedge fund fee structure of '2 and 20' refers to:", optionA: "A 2% management fee and 20% incentive fee", optionB: "A 2-year lock-up and 20 investors", optionC: "20% management and 2% incentive", optionD: "A 2% hurdle rate", correctOption: "A", explanation: "'2 and 20' is a 2% annual management fee plus a 20% share of profits (incentive fee).", orderIndex: 8 },
  { id: "cfa-alternative-investments-due-diligence-q10", topicId: "cfa-alternative-investments-due-diligence", text: "A hurdle rate in a private fund is:", optionA: "The minimum return that must be earned before incentive fees apply", optionB: "The management fee", optionC: "The redemption penalty", optionD: "The risk-free rate ceiling", correctOption: "A", explanation: "Incentive fees are charged only on returns above the hurdle rate.", orderIndex: 9 },
  { id: "cfa-alternative-investments-due-diligence-q11", topicId: "cfa-alternative-investments-due-diligence", text: "Survivorship bias in hedge fund index data tends to:", optionA: "Overstate historical returns", optionB: "Understate historical returns", optionC: "Have no effect", optionD: "Eliminate volatility", correctOption: "A", explanation: "Dropping failed funds from an index leaves only survivors, biasing reported returns upward.", orderIndex: 10 },
  { id: "cfa-alternative-investments-due-diligence-q12", topicId: "cfa-alternative-investments-due-diligence", text: "A high-water mark ensures that incentive fees are charged only on:", optionA: "New net profits above the previous peak value", optionB: "Gross assets each year", optionC: "The management fee base", optionD: "The hurdle rate itself", correctOption: "A", explanation: "A high-water mark prevents charging performance fees twice on the same gains after a loss is recovered.", orderIndex: 11 },

  // ══ Portfolio Management ══
  // Portfolio Risk, Return & CAPM
  { id: "cfa-portfolio-management-portfolio-risk-return-capm-q09", topicId: "cfa-portfolio-management-portfolio-risk-return-capm", text: "The CAPM expresses a security's expected return as:", optionA: "Risk-free rate + beta × (market return − risk-free rate)", optionB: "Dividend yield + growth", optionC: "Risk-free rate only", optionD: "Beta × standard deviation", correctOption: "A", explanation: "CAPM: E[R] = Rf + β(E[Rm] − Rf), pricing systematic risk via beta.", orderIndex: 8 },
  { id: "cfa-portfolio-management-portfolio-risk-return-capm-q10", topicId: "cfa-portfolio-management-portfolio-risk-return-capm", text: "Beta measures a security's:", optionA: "Systematic (market) risk", optionB: "Total risk", optionC: "Unsystematic risk", optionD: "Liquidity risk", correctOption: "A", explanation: "Beta measures sensitivity to market movements — the security's systematic (non-diversifiable) risk.", orderIndex: 9 },
  { id: "cfa-portfolio-management-portfolio-risk-return-capm-q11", topicId: "cfa-portfolio-management-portfolio-risk-return-capm", text: "The benefit of diversification is greatest when assets have:", optionA: "Low or negative correlation", optionB: "A correlation of +1", optionC: "Identical returns", optionD: "The same issuer", correctOption: "A", explanation: "Combining assets with low or negative correlation reduces portfolio risk the most.", orderIndex: 10 },
  { id: "cfa-portfolio-management-portfolio-risk-return-capm-q12", topicId: "cfa-portfolio-management-portfolio-risk-return-capm", text: "The capital market line (CML) uses which measure of risk on its x-axis?", optionA: "Total risk (standard deviation)", optionB: "Beta", optionC: "Duration", optionD: "Tracking error", correctOption: "A", explanation: "The CML plots expected return against total risk (standard deviation) for efficient portfolios; the SML uses beta.", orderIndex: 11 },
  // Investment Policy Statement & Planning
  { id: "cfa-portfolio-management-ips-planning-q09", topicId: "cfa-portfolio-management-ips-planning", text: "The two main components of an investor's objectives in an IPS are:", optionA: "Return objectives and risk tolerance", optionB: "Taxes and liquidity", optionC: "Legal and unique factors", optionD: "Time horizon and taxes", correctOption: "A", explanation: "IPS objectives cover the required/desired return and the investor's willingness and ability to bear risk.", orderIndex: 8 },
  { id: "cfa-portfolio-management-ips-planning-q10", topicId: "cfa-portfolio-management-ips-planning", text: "Which of the following is an IPS constraint?", optionA: "Liquidity needs", optionB: "Risk tolerance", optionC: "Return objective", optionD: "Expected alpha", correctOption: "A", explanation: "Constraints include liquidity, time horizon, taxes, legal/regulatory and unique circumstances.", orderIndex: 9 },
  { id: "cfa-portfolio-management-ips-planning-q11", topicId: "cfa-portfolio-management-ips-planning", text: "A young investor with stable income and a long horizon typically has:", optionA: "A higher ability to take risk", optionB: "A lower ability to take risk", optionC: "No return objective", optionD: "High liquidity needs", correctOption: "A", explanation: "A long time horizon and stable income generally raise the ability to bear investment risk.", orderIndex: 10 },
  { id: "cfa-portfolio-management-ips-planning-q12", topicId: "cfa-portfolio-management-ips-planning", text: "An investment policy statement should be reviewed:", optionA: "Periodically and whenever the client's circumstances change", optionB: "Only once at inception", optionC: "Every day", optionD: "Never after signing", correctOption: "A", explanation: "The IPS is a living document, revisited regularly and when objectives or constraints change.", orderIndex: 11 },
  // Asset Allocation & Multi-Asset Portfolios
  { id: "cfa-portfolio-management-asset-allocation-q09", topicId: "cfa-portfolio-management-asset-allocation", text: "Strategic asset allocation sets:", optionA: "Long-term target weights based on the IPS and capital market expectations", optionB: "Daily trading limits", optionC: "Individual stock picks", optionD: "The management fee", correctOption: "A", explanation: "SAA establishes long-run target asset-class weights aligned with the investor's objectives and constraints.", orderIndex: 8 },
  { id: "cfa-portfolio-management-asset-allocation-q10", topicId: "cfa-portfolio-management-asset-allocation", text: "Empirically, the largest driver of a portfolio's return variability over time is:", optionA: "The asset allocation policy", optionB: "Individual security selection", optionC: "Market timing", optionD: "Trading costs", correctOption: "A", explanation: "Studies attribute most of the variability in returns over time to the strategic asset allocation decision.", orderIndex: 9 },
  { id: "cfa-portfolio-management-asset-allocation-q11", topicId: "cfa-portfolio-management-asset-allocation", text: "Tactical asset allocation involves:", optionA: "Short-term deviations from targets to exploit perceived opportunities", optionB: "Never changing the weights", optionC: "Setting the long-run policy", optionD: "Avoiding all equities", correctOption: "A", explanation: "TAA makes temporary, deliberate shifts away from strategic weights to add value from market views.", orderIndex: 10 },
  { id: "cfa-portfolio-management-asset-allocation-q12", topicId: "cfa-portfolio-management-asset-allocation", text: "Rebalancing a portfolio back to its target weights is:", optionA: "A disciplined, often contrarian, risk-control practice", optionB: "A form of market timing", optionC: "Prohibited under an IPS", optionD: "Only for bonds", correctOption: "A", explanation: "Rebalancing sells winners and buys losers to restore target weights, controlling risk in a disciplined way.", orderIndex: 11 },
  // Performance Evaluation & Attribution
  { id: "cfa-portfolio-management-performance-evaluation-q09", topicId: "cfa-portfolio-management-performance-evaluation", text: "The Sharpe ratio measures excess return per unit of:", optionA: "Total risk (standard deviation)", optionB: "Systematic risk (beta)", optionC: "Tracking error", optionD: "Duration", correctOption: "A", explanation: "Sharpe ratio = (portfolio return − risk-free rate) ÷ standard deviation of returns.", orderIndex: 8 },
  { id: "cfa-portfolio-management-performance-evaluation-q10", topicId: "cfa-portfolio-management-performance-evaluation", text: "The Treynor ratio measures excess return per unit of:", optionA: "Systematic risk (beta)", optionB: "Total risk", optionC: "Active risk", optionD: "Liquidity risk", correctOption: "A", explanation: "The Treynor ratio divides excess return by beta, rewarding return per unit of market risk.", orderIndex: 9 },
  { id: "cfa-portfolio-management-performance-evaluation-q11", topicId: "cfa-portfolio-management-performance-evaluation", text: "Jensen's alpha measures a portfolio's return in excess of that predicted by:", optionA: "The CAPM", optionB: "The dividend discount model", optionC: "Put-call parity", optionD: "The yield curve", correctOption: "A", explanation: "Alpha is the return above the CAPM-required return given the portfolio's beta.", orderIndex: 10 },
  { id: "cfa-portfolio-management-performance-evaluation-q12", topicId: "cfa-portfolio-management-performance-evaluation", text: "The information ratio equals active return divided by:", optionA: "Active risk (tracking error)", optionB: "Total risk", optionC: "Beta", optionD: "The risk-free rate", correctOption: "A", explanation: "The information ratio is active (excess-over-benchmark) return divided by tracking error.", orderIndex: 11 },
  // Risk Management in Portfolios
  { id: "cfa-portfolio-management-risk-management-q09", topicId: "cfa-portfolio-management-risk-management", text: "Value at Risk (VaR) estimates:", optionA: "The minimum loss expected over a period at a given confidence level", optionB: "The guaranteed maximum profit", optionC: "The average annual return", optionD: "The portfolio's beta", correctOption: "A", explanation: "VaR gives the loss threshold that will not be exceeded with a specified probability over a horizon.", orderIndex: 8 },
  { id: "cfa-portfolio-management-risk-management-q10", topicId: "cfa-portfolio-management-risk-management", text: "A risk budget:", optionA: "Allocates an organisation's total risk across positions or activities", optionB: "Sets the marketing spend", optionC: "Caps management fees", optionD: "Fixes the dividend", correctOption: "A", explanation: "Risk budgeting distributes a total risk limit across the portfolio's positions or strategies.", orderIndex: 9 },
  { id: "cfa-portfolio-management-risk-management-q11", topicId: "cfa-portfolio-management-risk-management", text: "Risk that can be eliminated through diversification is:", optionA: "Unsystematic (idiosyncratic) risk", optionB: "Systematic risk", optionC: "Market risk", optionD: "Interest rate risk", correctOption: "A", explanation: "Unsystematic, security-specific risk can be diversified away; systematic (market) risk cannot.", orderIndex: 10 },
  { id: "cfa-portfolio-management-risk-management-q12", topicId: "cfa-portfolio-management-risk-management", text: "The first step in the risk management process is to:", optionA: "Establish risk governance and identify the risk tolerance", optionB: "Buy insurance", optionC: "Measure VaR", optionD: "Rebalance the portfolio", correctOption: "A", explanation: "Effective risk management begins with governance and defining the organisation's risk tolerance and objectives.", orderIndex: 11 }
];
