// CFA Level I depth expansion (pass 9). Adds high-yield learning modules for the
// remaining five topic areas — Equity, Fixed Income, Derivatives, Alternative
// Investments and Portfolio Management — including current-curriculum additions
// like Digital Assets and Fintech. Each new topic has a 2-minute study note and
// a full 12-question drill.
import type { AuthoredMaterial } from "./builder";
import type { Question, Topic } from "@jyotir/core";

export const exp9Topics: Topic[] = [
  // Equity Investments (existing max orderIndex = 5)
  { id: "cfa-equity-securities-types", subjectId: "cfa-equity", name: "Equity Securities: Types & Features", slug: "securities-types", orderIndex: 6 },
  { id: "cfa-equity-security-market-indexes", subjectId: "cfa-equity", name: "Security Market Indexes", slug: "security-market-indexes", orderIndex: 7 },
  // Fixed Income
  { id: "cfa-fixed-income-markets-instruments", subjectId: "cfa-fixed-income", name: "Fixed-Income Markets & Instruments", slug: "markets-instruments", orderIndex: 6 },
  { id: "cfa-fixed-income-interest-rate-risk-measures", subjectId: "cfa-fixed-income", name: "Interest Rate Risk Measures", slug: "interest-rate-risk-measures", orderIndex: 7 },
  // Derivatives
  { id: "cfa-derivatives-markets-instruments", subjectId: "cfa-derivatives", name: "Derivative Markets & Instruments", slug: "markets-instruments", orderIndex: 6 },
  { id: "cfa-derivatives-arbitrage-cost-of-carry", subjectId: "cfa-derivatives", name: "Arbitrage & Cost of Carry", slug: "arbitrage-cost-of-carry", orderIndex: 7 },
  // Alternative Investments
  { id: "cfa-alternative-investments-overview", subjectId: "cfa-alternative-investments", name: "Alternative Investments: Overview & Fees", slug: "overview", orderIndex: 6 },
  { id: "cfa-alternative-investments-digital-assets", subjectId: "cfa-alternative-investments", name: "Digital Assets & Tokenisation", slug: "digital-assets", orderIndex: 7 },
  // Portfolio Management
  { id: "cfa-portfolio-management-process", subjectId: "cfa-portfolio-management", name: "The Portfolio Management Process", slug: "process", orderIndex: 6 },
  { id: "cfa-portfolio-management-fintech", subjectId: "cfa-portfolio-management", name: "Fintech in Investment Management", slug: "fintech", orderIndex: 7 }
];

export const exp9Materials: AuthoredMaterial[] = [
  { id: "cfa-equity-securities-types-m01", topicId: "cfa-equity-securities-types", title: "Equity Securities: Types & Features", content: `Equity represents a **residual ownership claim** on a company's assets and income.

## Common vs preferred
| Feature | Common shares | Preferred shares |
| --- | --- | --- |
| **Voting** | Usually yes | Usually no |
| **Dividend** | Discretionary, variable | Fixed, paid before common |
| **Claim priority** | Last (residual) | Ahead of common, behind debt |

## Preferred-share variations
- **Cumulative** — unpaid (in-arrears) dividends accumulate and must be paid before common dividends; **non-cumulative** do not.
- **Participating** — may receive extra dividends beyond the fixed rate.
- **Convertible** — can convert into common shares.
- **Callable / putable** — issuer can redeem / holder can sell back.

## Other features
- **Public vs private equity** — private equity is illiquid and not exchange-listed.
- **Depository receipts (ADRs/GDRs)** let foreign shares trade on a domestic exchange in local currency.
- **Book value** is accounting equity; **market value** is the price investors pay. **ROE** (net income ÷ equity) links the two and gauges profitability.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "cfa-equity-security-market-indexes-m01", topicId: "cfa-equity-security-market-indexes", title: "Security Market Indexes", content: `A **security market index** represents the value of a group of securities, used as a **benchmark**, a market gauge, and the basis for index funds and ETFs.

## Weighting methods
| Method | How weighted | Notes |
| --- | --- | --- |
| **Price-weighted** | By share price (÷ divisor) | High-priced stocks dominate; affected by splits (e.g., Dow Jones) |
| **Market-cap-weighted** | By market capitalisation | Large caps dominate; usually **float-adjusted** (e.g., S&P 500) |
| **Equal-weighted** | Each constituent equally | Requires frequent rebalancing; tilts to small caps |
| **Fundamental-weighted** | By fundamentals (sales, book value) | Breaks the price-weight link; a value tilt |

## Return types
- A **price-return** index reflects only price changes.
- A **total-return** index also reinvests **dividends/income**, so it is higher over time.

## Maintenance
- **Rebalancing** resets weights to target; **reconstitution** changes the membership. Market-cap indexes largely rebalance themselves as prices move.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "cfa-fixed-income-markets-instruments-m01", topicId: "cfa-fixed-income-markets-instruments", title: "Fixed-Income Markets & Instruments", content: `## Issuers and sectors
Bonds are issued by **sovereign governments**, **non-sovereign** (local) governments, **quasi-government** agencies, **supranationals** (e.g., the World Bank), and **corporations** (including financial institutions).

## Money vs capital market
| Market | Maturity | Examples |
| --- | --- | --- |
| **Money market** | ≤ 1 year | Treasury bills, commercial paper, CDs, repos |
| **Capital market** | > 1 year | Government and corporate bonds |

## Primary vs secondary
- **Primary market**: new issues via **underwritten** offerings, best-efforts, **auctions** (common for government bonds), or **private placements**.
- **Secondary market**: trading of existing bonds, largely **over the counter**.

## Instruments
- **Fixed-rate** bonds pay a constant coupon; **floating-rate notes (FRNs)** pay a **reference rate + spread** that resets periodically; **zero-coupon** bonds pay only par at maturity.
- **Repurchase agreements (repos)** are short-term collateralised loans — sell a security now and agree to buy it back later at a higher price (the repo rate).`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "cfa-fixed-income-interest-rate-risk-measures-m01", topicId: "cfa-fixed-income-interest-rate-risk-measures", title: "Interest Rate Risk Measures", content: `Duration and related measures quantify a bond's price sensitivity to yield changes.

## Money duration & PVBP
- **Money (dollar) duration** = **modified duration × full price** (per 100 of par or per position). It gives the money change in price for a 1% (100 bp) yield change.
- The **price value of a basis point (PVBP / PV01)** is the money-price change for a **1 basis point** move — money duration × 0.0001.

## Effective vs analytical duration
- **Modified duration** works for option-free bonds (a fixed cash-flow schedule).
- **Effective duration** must be used for bonds with **embedded options** (callable/putable, MBS), because their cash flows change with yields.

## Key rate (partial) duration
Measures sensitivity to a change in yield at a **specific maturity point** on the curve, capturing non-parallel shifts that a single duration misses.

## Duration and the horizon
When a bond's **Macaulay duration equals the investment horizon**, price risk and reinvestment risk offset — the basis of **immunisation**. **Convexity** refines the duration estimate for larger yield moves.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "cfa-derivatives-markets-instruments-m01", topicId: "cfa-derivatives-markets-instruments", title: "Derivative Markets & Instruments", content: `A **derivative** is a financial instrument whose value derives from an **underlying** asset, rate or index.

## Two broad families
| Family | Instruments | Payoff |
| --- | --- | --- |
| **Forward commitments** | Forwards, futures, swaps | Both parties **obligated** to transact |
| **Contingent claims** | Options | Buyer has the **right, not the obligation** |

## Exchange-traded vs OTC
| | Exchange-traded | Over the counter (OTC) |
| --- | --- | --- |
| Terms | **Standardised** | **Customised** |
| Counterparty risk | Low (**central clearing**) | Higher (bilateral) |
| Examples | Futures, listed options | Forwards, swaps |

## Purposes and criticisms
- **Benefits**: risk transfer/hedging, **price discovery**, lower transaction costs, and efficient exposure with less capital.
- **Concerns**: **leverage** can magnify losses, complexity, and potential **systemic risk**.
- A **clearinghouse** guarantees performance and requires **margin**, reducing default risk on exchanges.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "cfa-derivatives-arbitrage-cost-of-carry-m01", topicId: "cfa-derivatives-arbitrage-cost-of-carry", title: "Arbitrage & Cost of Carry", content: `## Arbitrage and the law of one price
**Arbitrage** is a **riskless profit** earned with no net investment by exploiting a price discrepancy between equivalent assets. The **law of one price** says identical cash flows must have the same price; if they don't, arbitrageurs trade until prices realign. This **no-arbitrage principle** underlies all derivatives pricing.

## Replication
Any derivative's payoff can be **replicated** by a portfolio of the underlying and risk-free borrowing/lending. Because the replicating portfolio and the derivative have identical payoffs, they must have the same price.

## Cost-of-carry forward pricing
For a forward on an asset with financing cost r over time T:
\`\`\`
F₀ = S₀ × (1 + r)^T − FV(benefits) + FV(costs)
\`\`\`
- **Carry costs** (storage, insurance) **raise** the forward price.
- **Carry benefits** (dividends, coupons, convenience yield) **lower** it.
- If the observed forward deviates from this, a **cash-and-carry** (or reverse) arbitrage locks in a riskless profit — buying the cheap side and selling the expensive side.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "cfa-alternative-investments-overview-m01", topicId: "cfa-alternative-investments-overview", title: "Alternative Investments: Overview & Fees", content: `**Alternative investments** fall outside traditional stocks, bonds and cash, and include **hedge funds**, **private capital** (private equity and private debt), **real estate**, **infrastructure**, and **natural resources/commodities**.

## Common characteristics
- **Illiquidity** and long lock-ups, **less regulation** and transparency, specialised strategies, and often **low correlation** with traditional assets (diversification), but **higher fees**.

## Fee structure
- Typically **'2 and 20'** — a ~2% **management fee** plus a ~20% **incentive (performance) fee**.
- A **hurdle rate** is a minimum return before incentive fees apply.
- A **high-water mark** means performance fees are charged only on gains **above the prior peak**, so investors don't pay twice for recovering losses.

## Fund structures
- Usually **limited partnerships**: the **general partner (GP)** manages; **limited partners (LPs)** invest.
- Private funds draw down **committed capital** over time and often show a **J-curve** (early negative returns before gains). Redemptions may face **lock-ups and gates**. Thorough **due diligence** is essential.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "cfa-alternative-investments-digital-assets-m01", topicId: "cfa-alternative-investments-digital-assets", title: "Digital Assets & Tokenisation", content: `**Digital assets** are assets that exist digitally, typically recorded on a **distributed ledger (blockchain)**.

## Distributed ledger technology (DLT)
A **blockchain** is a decentralised, cryptographically secured ledger shared across a network, made trustworthy by a **consensus mechanism** (e.g., **proof of work** or **proof of stake**) and by **immutability** — records are extremely difficult to alter.

## Types of digital assets
| Asset | Description |
| --- | --- |
| **Cryptocurrencies** | Decentralised digital money (e.g., Bitcoin) with no central issuer |
| **Stablecoins** | Tokens pegged to a reference (often a fiat currency) |
| **Tokens** | Utility, security, or governance tokens created on a blockchain |
| **NFTs** | Non-fungible tokens representing unique digital items |

- **Smart contracts** are self-executing code that runs when conditions are met.
- **Tokenisation** puts claims on real assets (e.g., real estate) onto a blockchain to improve divisibility and liquidity.

## Investment forms and risks
Investors gain exposure directly (coins/tokens), or via **futures** and **funds**. Key risks: extreme **volatility**, **regulatory uncertainty**, **custody/security** (hacking, lost keys), and fraud.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "cfa-portfolio-management-process-m01", topicId: "cfa-portfolio-management-process", title: "The Portfolio Management Process", content: `Portfolio management is a continuous, three-step process:
| Step | Activities |
| --- | --- |
| **1. Planning** | Understand the client, set objectives and constraints, and write the **Investment Policy Statement (IPS)** |
| **2. Execution** | Decide **asset allocation**, then security analysis and selection; construct the portfolio |
| **3. Feedback** | **Monitor** and **rebalance**; evaluate **performance** against the benchmark |

## Types of investors
- **Individual** investors vary widely in goals and risk tolerance.
- **Institutional** investors include **pension plans** (defined benefit vs defined contribution), **endowments and foundations** (long horizons, spending needs), **insurance companies** and **banks** (liability-driven), and **sovereign wealth funds**.

## Pooled vehicles
- **Mutual funds** (open-end trade at NAV; closed-end trade on an exchange), **ETFs** (exchange-traded, usually index-tracking, tax-efficient), **separately managed accounts (SMAs)**, and **hedge/private funds**.
- **Diversification** across imperfectly correlated assets reduces risk for a given return — the core rationale for holding a portfolio rather than single securities.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "cfa-portfolio-management-fintech-m01", topicId: "cfa-portfolio-management-fintech", title: "Fintech in Investment Management", content: `**Fintech** is technology-driven innovation in financial products and services. Several strands are transforming investment management.

## Big data
Characterised by the **'three Vs' — volume, velocity, and variety**. Sources span **traditional** data (financial statements, prices) and **alternative** data (social media, satellite/sensor data, credit-card records).

## Artificial intelligence & machine learning
- **Machine learning** finds patterns in data: **supervised** learning (labelled data → prediction/classification), **unsupervised** learning (finding structure, e.g., clustering), and **deep learning** (neural networks).
- **Natural language processing (NLP)** extracts information from text (news, filings, sentiment).

## Applications and risks
- **Algorithmic and high-frequency trading** execute orders by rule at speed.
- **Robo-advisers** deliver low-cost automated advice and asset allocation.
- **Distributed ledger technology** enables faster settlement and tokenisation.
- Considerations: **data quality**, **overfitting** models to noise, privacy and model risk.`, estimatedReadTime: 2, orderIndex: 0 }
];

export const exp9Questions: Question[] = [
  // ── Equity: Securities: Types & Features ──
  { id: "cfa-equity-securities-types-q01", topicId: "cfa-equity-securities-types", text: "Common shareholders have a claim on a company's assets that is:", optionA: "Residual (after creditors and preferred)", optionB: "First priority", optionC: "Ahead of bondholders", optionD: "Fixed and guaranteed", correctOption: "A", explanation: "Common equity is the residual claim, paid after debt and preferred holders.", orderIndex: 0 },
  { id: "cfa-equity-securities-types-q02", topicId: "cfa-equity-securities-types", text: "Compared with common shares, preferred shares typically have:", optionA: "A fixed dividend and priority over common", optionB: "Full voting rights", optionC: "A residual claim only", optionD: "No dividend", correctOption: "A", explanation: "Preferred shares pay a fixed dividend ahead of common and usually carry no vote.", orderIndex: 1 },
  { id: "cfa-equity-securities-types-q03", topicId: "cfa-equity-securities-types", text: "For cumulative preferred shares, unpaid dividends:", optionA: "Accumulate and must be paid before common dividends", optionB: "Are permanently forfeited", optionC: "Convert to debt", optionD: "Reduce par value", correctOption: "A", explanation: "Cumulative preferred dividends in arrears must be paid before any common dividend.", orderIndex: 2 },
  { id: "cfa-equity-securities-types-q04", topicId: "cfa-equity-securities-types", text: "A depository receipt (e.g., an ADR) allows investors to:", optionA: "Trade foreign shares on a domestic exchange", optionB: "Buy government bonds", optionC: "Short commodities", optionD: "Avoid all currency risk", correctOption: "A", explanation: "Depository receipts represent foreign shares and trade on a local exchange in local currency.", orderIndex: 3 },
  { id: "cfa-equity-securities-types-q05", topicId: "cfa-equity-securities-types", text: "Convertible preferred shares give the holder the right to:", optionA: "Exchange them for common shares", optionB: "Demand a higher coupon", optionC: "Vote twice", optionD: "Receive principal early always", correctOption: "A", explanation: "Convertible preferred can be exchanged into a set number of common shares.", orderIndex: 4 },
  { id: "cfa-equity-securities-types-q06", topicId: "cfa-equity-securities-types", text: "Private equity, compared with public equity, is generally:", optionA: "Less liquid and not exchange-listed", optionB: "More liquid", optionC: "Traded continuously", optionD: "Risk-free", correctOption: "A", explanation: "Private equity is illiquid and not listed on public exchanges.", orderIndex: 5 },
  { id: "cfa-equity-securities-types-q07", topicId: "cfa-equity-securities-types", text: "The accounting value of shareholders' equity is called:", optionA: "Book value", optionB: "Market value", optionC: "Face value", optionD: "Intrinsic value", correctOption: "A", explanation: "Book value is equity per the balance sheet; market value is what investors pay.", orderIndex: 6 },
  { id: "cfa-equity-securities-types-q08", topicId: "cfa-equity-securities-types", text: "Return on equity (ROE) is calculated as:", optionA: "Net income / shareholders' equity", optionB: "Net income / total debt", optionC: "Dividends / price", optionD: "Sales / assets", correctOption: "A", explanation: "ROE measures profitability relative to book equity.", orderIndex: 7 },
  { id: "cfa-equity-securities-types-q09", topicId: "cfa-equity-securities-types", text: "Participating preferred shares may:", optionA: "Receive additional dividends beyond the fixed rate", optionB: "Never receive dividends", optionC: "Convert to bonds automatically", optionD: "Lose priority to common", correctOption: "A", explanation: "Participating preferred can share in extra distributions above the stated dividend.", orderIndex: 8 },
  { id: "cfa-equity-securities-types-q10", topicId: "cfa-equity-securities-types", text: "A callable preferred share can be:", optionA: "Redeemed by the issuer at a set price", optionB: "Sold back by the holder at will", optionC: "Never retired", optionD: "Converted to common only", correctOption: "A", explanation: "A call feature lets the issuer redeem the shares, typically when it is advantageous to refinance.", orderIndex: 9 },
  { id: "cfa-equity-securities-types-q11", topicId: "cfa-equity-securities-types", text: "The main advantage of equity ownership over debt is the:", optionA: "Potential to share in the company's growth and profits", optionB: "Fixed, guaranteed return", optionC: "First claim in liquidation", optionD: "Tax-deductible payments", correctOption: "A", explanation: "Equity holders participate in the upside of the firm, unlike fixed-claim debt holders.", orderIndex: 10 },
  { id: "cfa-equity-securities-types-q12", topicId: "cfa-equity-securities-types", text: "In a company liquidation, the order of claims is:", optionA: "Debt holders, then preferred, then common", optionB: "Common, then preferred, then debt", optionC: "Preferred, then debt, then common", optionD: "All paid equally", correctOption: "A", explanation: "Creditors are paid first, then preferred shareholders, with common shareholders last (residual).", orderIndex: 11 },

  // ── Equity: Security Market Indexes ──
  { id: "cfa-equity-security-market-indexes-q01", topicId: "cfa-equity-security-market-indexes", text: "In a price-weighted index, the stocks with the greatest influence are those with the:", optionA: "Highest share price", optionB: "Largest market cap", optionC: "Highest dividend", optionD: "Lowest price", correctOption: "A", explanation: "A price-weighted index (e.g., the Dow) gives higher-priced shares more influence regardless of company size.", orderIndex: 0 },
  { id: "cfa-equity-security-market-indexes-q02", topicId: "cfa-equity-security-market-indexes", text: "In a market-cap-weighted index, the largest weights belong to companies with the:", optionA: "Largest market capitalisation", optionB: "Highest share price", optionC: "Most shares outstanding only", optionD: "Highest dividend yield", correctOption: "A", explanation: "Market-cap weighting (e.g., the S&P 500) weights by total market value, so large caps dominate.", orderIndex: 1 },
  { id: "cfa-equity-security-market-indexes-q03", topicId: "cfa-equity-security-market-indexes", text: "An equal-weighted index requires:", optionA: "Frequent rebalancing to maintain equal weights", optionB: "No maintenance", optionC: "Weighting by price", optionD: "Only large caps", correctOption: "A", explanation: "Because prices drift, equal-weighted indexes must be rebalanced regularly to restore equal weights.", orderIndex: 2 },
  { id: "cfa-equity-security-market-indexes-q04", topicId: "cfa-equity-security-market-indexes", text: "A total-return index differs from a price-return index in that it:", optionA: "Reinvests dividends and other income", optionB: "Excludes the largest stocks", optionC: "Ignores price changes", optionD: "Uses only bonds", correctOption: "A", explanation: "A total-return index includes reinvested income, so it exceeds the price-return version over time.", orderIndex: 3 },
  { id: "cfa-equity-security-market-indexes-q05", topicId: "cfa-equity-security-market-indexes", text: "Most modern market-cap indexes adjust weights for:", optionA: "Free float (shares available to the public)", optionB: "Dividend yield", optionC: "Share price only", optionD: "Book value", correctOption: "A", explanation: "Float-adjusting counts only publicly tradable shares, excluding closely held stakes.", orderIndex: 4 },
  { id: "cfa-equity-security-market-indexes-q06", topicId: "cfa-equity-security-market-indexes", text: "A fundamental-weighted index weights constituents by:", optionA: "Fundamental measures such as sales or book value", optionB: "Share price", optionC: "Market cap", optionD: "Alphabetical order", correctOption: "A", explanation: "Fundamental weighting uses metrics like sales, earnings or book value, breaking the link to price.", orderIndex: 5 },
  { id: "cfa-equity-security-market-indexes-q07", topicId: "cfa-equity-security-market-indexes", text: "A stock split in a price-weighted index:", optionA: "Reduces that stock's influence and changes the divisor", optionB: "Has no effect", optionC: "Doubles the index", optionD: "Removes the stock", correctOption: "A", explanation: "A split lowers the share price, reducing its weight; the divisor is adjusted to keep the index continuous.", orderIndex: 6 },
  { id: "cfa-equity-security-market-indexes-q08", topicId: "cfa-equity-security-market-indexes", text: "Reconstitution of an index refers to:", optionA: "Changing which securities are included", optionB: "Resetting weights to target only", optionC: "Paying dividends", optionD: "Splitting shares", correctOption: "A", explanation: "Reconstitution changes index membership; rebalancing adjusts the weights of existing members.", orderIndex: 7 },
  { id: "cfa-equity-security-market-indexes-q09", topicId: "cfa-equity-security-market-indexes", text: "A primary use of a security market index is as a:", optionA: "Benchmark for portfolio performance", optionB: "Source of guaranteed returns", optionC: "Tax shelter", optionD: "Credit rating", correctOption: "A", explanation: "Indexes serve as benchmarks, market gauges, and the basis for index funds and ETFs.", orderIndex: 8 },
  { id: "cfa-equity-security-market-indexes-q10", topicId: "cfa-equity-security-market-indexes", text: "Market-cap-weighted indexes are said to be self-rebalancing because:", optionA: "Weights adjust automatically as prices change", optionB: "They never change", optionC: "They use equal weights", optionD: "Managers pick weights daily", correctOption: "A", explanation: "As prices move, market-cap weights update automatically without manual rebalancing.", orderIndex: 9 },
  { id: "cfa-equity-security-market-indexes-q11", topicId: "cfa-equity-security-market-indexes", text: "An equal-weighted index tends to tilt toward:", optionA: "Smaller-cap stocks relative to a cap-weighted index", optionB: "Only the largest stocks", optionC: "Bonds", optionD: "High-priced stocks", correctOption: "A", explanation: "Giving each stock equal weight raises the relative importance of smaller companies.", orderIndex: 10 },
  { id: "cfa-equity-security-market-indexes-q12", topicId: "cfa-equity-security-market-indexes", text: "The value of an index is best described as:", optionA: "A weighted average of its constituent securities' values", optionB: "The single highest stock price", optionC: "The total number of shares", optionD: "The risk-free rate", correctOption: "A", explanation: "An index aggregates its constituents using a defined weighting method into a single value.", orderIndex: 11 },

  // ── Fixed Income: Markets & Instruments ──
  { id: "cfa-fixed-income-markets-instruments-q01", topicId: "cfa-fixed-income-markets-instruments", text: "A bond issued by an entity such as the World Bank is classified as:", optionA: "Supranational", optionB: "Sovereign", optionC: "Corporate", optionD: "Municipal", correctOption: "A", explanation: "Supranational issuers are multinational agencies like the World Bank or the IMF.", orderIndex: 0 },
  { id: "cfa-fixed-income-markets-instruments-q02", topicId: "cfa-fixed-income-markets-instruments", text: "Money-market instruments have original maturities of:", optionA: "One year or less", optionB: "Over ten years", optionC: "Exactly five years", optionD: "No maturity", correctOption: "A", explanation: "The money market covers short-term debt maturing in one year or less (T-bills, commercial paper, CDs).", orderIndex: 1 },
  { id: "cfa-fixed-income-markets-instruments-q03", topicId: "cfa-fixed-income-markets-instruments", text: "A floating-rate note pays a coupon equal to:", optionA: "A reference rate plus a spread", optionB: "A fixed rate for life", optionC: "Zero until maturity", optionD: "The share price", correctOption: "A", explanation: "FRNs reset periodically to a reference (benchmark) rate plus a credit spread.", orderIndex: 2 },
  { id: "cfa-fixed-income-markets-instruments-q04", topicId: "cfa-fixed-income-markets-instruments", text: "Government bonds are frequently sold in the primary market through:", optionA: "Auctions", optionB: "Stock splits", optionC: "Dividend reinvestment", optionD: "Buybacks", correctOption: "A", explanation: "Sovereign issuers commonly use auctions to distribute new bonds.", orderIndex: 3 },
  { id: "cfa-fixed-income-markets-instruments-q05", topicId: "cfa-fixed-income-markets-instruments", text: "A repurchase agreement (repo) is essentially:", optionA: "A short-term collateralised loan", optionB: "An equity issue", optionC: "A perpetual bond", optionD: "A dividend payment", correctOption: "A", explanation: "In a repo, a security is sold and repurchased later at a higher price — a collateralised short-term borrowing.", orderIndex: 4 },
  { id: "cfa-fixed-income-markets-instruments-q06", topicId: "cfa-fixed-income-markets-instruments", text: "Commercial paper is best described as:", optionA: "Short-term unsecured corporate debt", optionB: "A long-term government bond", optionC: "A share of stock", optionD: "A mortgage", correctOption: "A", explanation: "Commercial paper is short-term, usually unsecured debt issued by corporations to fund working capital.", orderIndex: 5 },
  { id: "cfa-fixed-income-markets-instruments-q07", topicId: "cfa-fixed-income-markets-instruments", text: "Most secondary-market bond trading takes place:", optionA: "Over the counter (dealer markets)", optionB: "On a single central exchange", optionC: "Only at auctions", optionD: "Through IPOs", correctOption: "A", explanation: "Unlike equities, bonds trade largely OTC through dealer networks.", orderIndex: 6 },
  { id: "cfa-fixed-income-markets-instruments-q08", topicId: "cfa-fixed-income-markets-instruments", text: "A zero-coupon bond:", optionA: "Pays no periodic interest and is issued at a discount", optionB: "Pays a floating coupon", optionC: "Pays monthly dividends", optionD: "Never matures", correctOption: "A", explanation: "Zeros make no interim payments; the return comes from the discount to par.", orderIndex: 7 },
  { id: "cfa-fixed-income-markets-instruments-q09", topicId: "cfa-fixed-income-markets-instruments", text: "A quasi-government (agency) bond is issued by:", optionA: "An entity affiliated with, but not, the central government", optionB: "A private hedge fund", optionC: "A stock exchange", optionD: "A foreign household", correctOption: "A", explanation: "Quasi-government issuers are agencies or government-sponsored entities linked to, but distinct from, the sovereign.", orderIndex: 8 },
  { id: "cfa-fixed-income-markets-instruments-q10", topicId: "cfa-fixed-income-markets-instruments", text: "In an underwritten (firm-commitment) offering, the investment bank:", optionA: "Buys the entire issue and resells it, bearing the risk", optionB: "Only advises, taking no risk", optionC: "Guarantees the coupon", optionD: "Sets monetary policy", correctOption: "A", explanation: "Under a firm commitment, the underwriter purchases the whole issue and assumes the placement risk.", orderIndex: 9 },
  { id: "cfa-fixed-income-markets-instruments-q11", topicId: "cfa-fixed-income-markets-instruments", text: "A private placement bond is:", optionA: "Sold directly to a small number of investors, not the public", optionB: "Listed on every exchange", optionC: "Always a government bond", optionD: "Free of default risk", correctOption: "A", explanation: "Private placements are sold to a limited group of qualified investors without a public offering.", orderIndex: 10 },
  { id: "cfa-fixed-income-markets-instruments-q12", topicId: "cfa-fixed-income-markets-instruments", text: "The capital market, versus the money market, covers debt with maturities of:", optionA: "More than one year", optionB: "Less than one month", optionC: "Exactly 90 days", optionD: "No fixed term", correctOption: "A", explanation: "Capital-market instruments have maturities beyond one year; money-market instruments are one year or less.", orderIndex: 11 },

  // ── Fixed Income: Interest Rate Risk Measures ──
  { id: "cfa-fixed-income-interest-rate-risk-measures-q01", topicId: "cfa-fixed-income-interest-rate-risk-measures", text: "Money (dollar) duration equals:", optionA: "Modified duration × full price", optionB: "Coupon × maturity", optionC: "Yield × par", optionD: "Convexity × price", correctOption: "A", explanation: "Money duration is modified duration multiplied by the bond's full price, giving the money price change per 1% yield move.", orderIndex: 0 },
  { id: "cfa-fixed-income-interest-rate-risk-measures-q02", topicId: "cfa-fixed-income-interest-rate-risk-measures", text: "The price value of a basis point (PVBP) measures the price change for a yield move of:", optionA: "One basis point (0.01%)", optionB: "One percent", optionC: "One dollar", optionD: "One year", correctOption: "A", explanation: "PVBP (PV01) is the money-price change for a 1 basis point change in yield.", orderIndex: 1 },
  { id: "cfa-fixed-income-interest-rate-risk-measures-q03", topicId: "cfa-fixed-income-interest-rate-risk-measures", text: "For a bond with embedded options, the appropriate sensitivity measure is:", optionA: "Effective duration", optionB: "Modified duration", optionC: "Macaulay duration only", optionD: "Coupon duration", correctOption: "A", explanation: "Effective duration accounts for cash flows that change with yields, as with callable or putable bonds.", orderIndex: 2 },
  { id: "cfa-fixed-income-interest-rate-risk-measures-q04", topicId: "cfa-fixed-income-interest-rate-risk-measures", text: "Key rate (partial) duration measures sensitivity to:", optionA: "A yield change at a specific maturity on the curve", optionB: "A parallel shift only", optionC: "The coupon rate", optionD: "Credit spreads", correctOption: "A", explanation: "Key rate durations capture the effect of non-parallel shifts at particular points on the yield curve.", orderIndex: 3 },
  { id: "cfa-fixed-income-interest-rate-risk-measures-q05", topicId: "cfa-fixed-income-interest-rate-risk-measures", text: "When a bond's Macaulay duration equals the investment horizon:", optionA: "Price and reinvestment risk roughly offset (immunisation)", optionB: "The bond defaults", optionC: "Duration becomes negative", optionD: "The coupon doubles", correctOption: "A", explanation: "Matching Macaulay duration to the horizon balances price and reinvestment risk — the basis of immunisation.", orderIndex: 4 },
  { id: "cfa-fixed-income-interest-rate-risk-measures-q06", topicId: "cfa-fixed-income-interest-rate-risk-measures", text: "Convexity is used to:", optionA: "Improve the duration-based estimate for larger yield changes", optionB: "Measure credit risk", optionC: "Replace duration entirely", optionD: "Compute the coupon", correctOption: "A", explanation: "Convexity corrects the linear duration approximation, mattering more for large yield moves.", orderIndex: 5 },
  { id: "cfa-fixed-income-interest-rate-risk-measures-q07", topicId: "cfa-fixed-income-interest-rate-risk-measures", text: "A higher money duration means a bond's price is:", optionA: "More sensitive in money terms to yield changes", optionB: "Less sensitive to yields", optionC: "Immune to yields", optionD: "Fixed", correctOption: "A", explanation: "Larger money duration implies a bigger money-price change for a given yield move.", orderIndex: 6 },
  { id: "cfa-fixed-income-interest-rate-risk-measures-q08", topicId: "cfa-fixed-income-interest-rate-risk-measures", text: "PVBP is calculated as:", optionA: "Money duration × 0.0001", optionB: "Modified duration × yield", optionC: "Price × coupon", optionD: "Convexity × maturity", correctOption: "A", explanation: "PVBP scales money duration by one basis point (0.0001).", orderIndex: 7 },
  { id: "cfa-fixed-income-interest-rate-risk-measures-q09", topicId: "cfa-fixed-income-interest-rate-risk-measures", text: "Modified duration is most appropriate for a bond that is:", optionA: "Option-free with fixed cash flows", optionB: "A callable mortgage security", optionC: "A putable bond", optionD: "Convertible", correctOption: "A", explanation: "Modified duration assumes fixed cash flows, so it fits straight, option-free bonds.", orderIndex: 8 },
  { id: "cfa-fixed-income-interest-rate-risk-measures-q10", topicId: "cfa-fixed-income-interest-rate-risk-measures", text: "A portfolio's money duration is useful because it:", optionA: "Expresses interest-rate risk in currency terms", optionB: "Removes all risk", optionC: "Ignores position size", optionD: "Measures equity beta", correctOption: "A", explanation: "Money duration translates rate sensitivity into a money amount, aiding position-level risk management.", orderIndex: 9 },
  { id: "cfa-fixed-income-interest-rate-risk-measures-q11", topicId: "cfa-fixed-income-interest-rate-risk-measures", text: "Non-parallel shifts in the yield curve are best captured by:", optionA: "Key rate durations", optionB: "A single modified duration", optionC: "The coupon rate", optionD: "The current yield", correctOption: "A", explanation: "Key rate durations reveal exposure to changes at individual maturities, unlike one aggregate duration.", orderIndex: 10 },
  { id: "cfa-fixed-income-interest-rate-risk-measures-q12", topicId: "cfa-fixed-income-interest-rate-risk-measures", text: "Effective duration is estimated using:", optionA: "Price changes from up and down yield-curve shifts", optionB: "The coupon divided by price", optionC: "Only the maturity", optionD: "The credit rating", correctOption: "A", explanation: "Effective duration uses the bond's prices under small upward and downward curve shifts to gauge sensitivity.", orderIndex: 11 },

  // ── Derivatives: Markets & Instruments ──
  { id: "cfa-derivatives-markets-instruments-q01", topicId: "cfa-derivatives-markets-instruments", text: "A derivative is an instrument whose value is:", optionA: "Derived from an underlying asset, rate or index", optionB: "Fixed by the issuer", optionC: "Independent of any asset", optionD: "Equal to par always", correctOption: "A", explanation: "Derivatives derive their value from the performance of an underlying.", orderIndex: 0 },
  { id: "cfa-derivatives-markets-instruments-q02", topicId: "cfa-derivatives-markets-instruments", text: "Forwards, futures and swaps are examples of:", optionA: "Forward commitments", optionB: "Contingent claims", optionC: "Equity securities", optionD: "Money-market instruments", correctOption: "A", explanation: "Forward commitments obligate both parties to transact; options are contingent claims.", orderIndex: 1 },
  { id: "cfa-derivatives-markets-instruments-q03", topicId: "cfa-derivatives-markets-instruments", text: "An option is a contingent claim because the buyer has:", optionA: "The right, but not the obligation, to transact", optionB: "An obligation to buy", optionC: "No payoff ever", optionD: "A fixed coupon", correctOption: "A", explanation: "Option buyers may exercise if favourable but are not obligated, unlike forward-commitment holders.", orderIndex: 2 },
  { id: "cfa-derivatives-markets-instruments-q04", topicId: "cfa-derivatives-markets-instruments", text: "Exchange-traded derivatives are:", optionA: "Standardised and centrally cleared", optionB: "Fully customised", optionC: "Free of margin requirements", optionD: "Unregulated", correctOption: "A", explanation: "Exchange-traded contracts have standard terms and use central clearing, reducing counterparty risk.", orderIndex: 3 },
  { id: "cfa-derivatives-markets-instruments-q05", topicId: "cfa-derivatives-markets-instruments", text: "OTC derivatives, versus exchange-traded ones, generally have:", optionA: "More customisation but higher counterparty risk", optionB: "Standardised terms", optionC: "No counterparty risk", optionD: "Lower flexibility", correctOption: "A", explanation: "OTC contracts are tailored between two parties but carry bilateral counterparty risk.", orderIndex: 4 },
  { id: "cfa-derivatives-markets-instruments-q06", topicId: "cfa-derivatives-markets-instruments", text: "A clearinghouse in a futures market:", optionA: "Guarantees performance and requires margin", optionB: "Sets interest rates", optionC: "Issues the underlying stock", optionD: "Eliminates price movement", correctOption: "A", explanation: "The clearinghouse acts as counterparty to both sides and enforces margin, reducing default risk.", orderIndex: 5 },
  { id: "cfa-derivatives-markets-instruments-q07", topicId: "cfa-derivatives-markets-instruments", text: "A commonly cited benefit of derivatives is:", optionA: "Efficient risk transfer and price discovery", optionB: "Guaranteed profits", optionC: "Elimination of all risk", optionD: "No need for a counterparty", correctOption: "A", explanation: "Derivatives enable hedging/risk transfer, price discovery and low-cost exposure.", orderIndex: 6 },
  { id: "cfa-derivatives-markets-instruments-q08", topicId: "cfa-derivatives-markets-instruments", text: "A frequently cited criticism of derivatives is that they:", optionA: "Enable high leverage that can magnify losses", optionB: "Cannot be used to hedge", optionC: "Have no underlying", optionD: "Are always unprofitable", correctOption: "A", explanation: "The leverage embedded in derivatives can amplify losses and contribute to systemic risk.", orderIndex: 7 },
  { id: "cfa-derivatives-markets-instruments-q09", topicId: "cfa-derivatives-markets-instruments", text: "Futures differ from forwards mainly in that futures are:", optionA: "Standardised, exchange-traded and marked to market daily", optionB: "Fully customised", optionC: "Traded only OTC", optionD: "Never cleared", correctOption: "A", explanation: "Futures are standardised, exchange-listed and settled daily; forwards are customised OTC contracts.", orderIndex: 8 },
  { id: "cfa-derivatives-markets-instruments-q10", topicId: "cfa-derivatives-markets-instruments", text: "Using derivatives, an investor can gain exposure to an underlying with:", optionA: "Less capital than buying it outright", optionB: "No possibility of loss", optionC: "Guaranteed gains", optionD: "No counterparty", correctOption: "A", explanation: "Derivatives require only margin/premium, giving leveraged exposure with less upfront capital.", orderIndex: 9 },
  { id: "cfa-derivatives-markets-instruments-q11", topicId: "cfa-derivatives-markets-instruments", text: "Price discovery refers to derivatives helping to:", optionA: "Reveal expected future prices of the underlying", optionB: "Hide market information", optionC: "Fix prices permanently", optionD: "Eliminate trading", correctOption: "A", explanation: "Active derivatives markets aggregate views and reveal information about expected future prices.", orderIndex: 10 },
  { id: "cfa-derivatives-markets-instruments-q12", topicId: "cfa-derivatives-markets-instruments", text: "A swap is best classified as a:", optionA: "Forward commitment (series of forwards)", optionB: "Contingent claim", optionC: "Money-market security", optionD: "Equity index", correctOption: "A", explanation: "A swap obligates both parties to exchange cash flows and is economically a series of forward commitments.", orderIndex: 11 },

  // ── Derivatives: Arbitrage & Cost of Carry ──
  { id: "cfa-derivatives-arbitrage-cost-of-carry-q01", topicId: "cfa-derivatives-arbitrage-cost-of-carry", text: "Arbitrage is defined as:", optionA: "A riskless profit earned with no net investment", optionB: "A risky bet on prices", optionC: "A guaranteed loss", optionD: "A long-term investment", correctOption: "A", explanation: "Arbitrage exploits mispricing to earn a riskless profit with zero net investment.", orderIndex: 0 },
  { id: "cfa-derivatives-arbitrage-cost-of-carry-q02", topicId: "cfa-derivatives-arbitrage-cost-of-carry", text: "The law of one price states that:", optionA: "Assets with identical cash flows must have the same price", optionB: "All assets cost the same", optionC: "Prices never change", optionD: "Higher risk means lower price", correctOption: "A", explanation: "Identical payoffs must trade at the same price; otherwise arbitrage forces them together.", orderIndex: 1 },
  { id: "cfa-derivatives-arbitrage-cost-of-carry-q03", topicId: "cfa-derivatives-arbitrage-cost-of-carry", text: "Replication in derivatives pricing means:", optionA: "Recreating a payoff using the underlying and risk-free borrowing/lending", optionB: "Copying a competitor's fund", optionC: "Doubling the position", optionD: "Splitting the contract", correctOption: "A", explanation: "If a portfolio replicates a derivative's payoff, no-arbitrage requires they have the same price.", orderIndex: 2 },
  { id: "cfa-derivatives-arbitrage-cost-of-carry-q04", topicId: "cfa-derivatives-arbitrage-cost-of-carry", text: "In cost-of-carry pricing, carry costs such as storage:", optionA: "Increase the forward price", optionB: "Decrease the forward price", optionC: "Have no effect", optionD: "Set it to zero", correctOption: "A", explanation: "Costs of holding the asset (storage, insurance) raise the no-arbitrage forward price.", orderIndex: 3 },
  { id: "cfa-derivatives-arbitrage-cost-of-carry-q05", topicId: "cfa-derivatives-arbitrage-cost-of-carry", text: "Carry benefits such as dividends on the underlying:", optionA: "Lower the forward price", optionB: "Raise the forward price", optionC: "Have no effect", optionD: "Eliminate arbitrage", correctOption: "A", explanation: "Income received from holding the asset reduces the net cost of carry and thus the forward price.", orderIndex: 4 },
  { id: "cfa-derivatives-arbitrage-cost-of-carry-q06", topicId: "cfa-derivatives-arbitrage-cost-of-carry", text: "The no-arbitrage forward price of an asset paying no income is approximately:", optionA: "S₀ × (1 + r)^T", optionB: "S₀ / (1 + r)^T", optionC: "S₀ − r", optionD: "S₀ × r × T", correctOption: "A", explanation: "The forward equals the spot compounded at the risk-free rate over the contract's life.", orderIndex: 5 },
  { id: "cfa-derivatives-arbitrage-cost-of-carry-q07", topicId: "cfa-derivatives-arbitrage-cost-of-carry", text: "A cash-and-carry arbitrage is executed when the forward is:", optionA: "Overpriced relative to its no-arbitrage value", optionB: "Fairly priced", optionC: "Below spot only", optionD: "Equal to the coupon", correctOption: "A", explanation: "If the forward is too high, an arbitrageur buys the asset (carries it) and sells the forward for a riskless gain.", orderIndex: 6 },
  { id: "cfa-derivatives-arbitrage-cost-of-carry-q08", topicId: "cfa-derivatives-arbitrage-cost-of-carry", text: "The no-arbitrage principle is important because it:", optionA: "Underlies the pricing of all derivatives", optionB: "Guarantees high returns", optionC: "Applies only to stocks", optionD: "Ignores the underlying", correctOption: "A", explanation: "Derivatives are priced on the assumption that no riskless arbitrage profit should exist.", orderIndex: 7 },
  { id: "cfa-derivatives-arbitrage-cost-of-carry-q09", topicId: "cfa-derivatives-arbitrage-cost-of-carry", text: "If two portfolios have identical future payoffs, arbitrage ensures they have:", optionA: "The same current price", optionB: "Different prices", optionC: "Zero value", optionD: "Opposite risks", correctOption: "A", explanation: "Identical payoffs must have identical prices; any gap is arbitraged away.", orderIndex: 8 },
  { id: "cfa-derivatives-arbitrage-cost-of-carry-q10", topicId: "cfa-derivatives-arbitrage-cost-of-carry", text: "The convenience yield on a commodity behaves like a:", optionA: "Carry benefit that lowers the forward price", optionB: "Storage cost", optionC: "Financing cost", optionD: "Tax", correctOption: "A", explanation: "The convenience yield is a benefit of holding the physical commodity, reducing the net cost of carry.", orderIndex: 9 },
  { id: "cfa-derivatives-arbitrage-cost-of-carry-q11", topicId: "cfa-derivatives-arbitrage-cost-of-carry", text: "Arbitrage activity tends to:", optionA: "Push mispriced assets back toward fair value", optionB: "Widen price gaps", optionC: "Increase risk-free rates", optionD: "Eliminate all trading", correctOption: "A", explanation: "Arbitrageurs buying the cheap and selling the dear drive prices back into alignment.", orderIndex: 10 },
  { id: "cfa-derivatives-arbitrage-cost-of-carry-q12", topicId: "cfa-derivatives-arbitrage-cost-of-carry", text: "Net cost of carry equals:", optionA: "Financing and storage costs minus any income/benefits", optionB: "Only the coupon", optionC: "The spot price", optionD: "The strike price", correctOption: "A", explanation: "Net carry is the cost of holding the asset (financing + storage) less benefits (income, convenience yield).", orderIndex: 11 },

  // ── Alternatives: Overview & Fees ──
  { id: "cfa-alternative-investments-overview-q01", topicId: "cfa-alternative-investments-overview", text: "A common characteristic of alternative investments is:", optionA: "Illiquidity and limited transparency", optionB: "Daily exchange liquidity", optionC: "Heavy regulation", optionD: "Guaranteed returns", correctOption: "A", explanation: "Alternatives are typically illiquid, lightly regulated and less transparent than traditional assets.", orderIndex: 0 },
  { id: "cfa-alternative-investments-overview-q02", topicId: "cfa-alternative-investments-overview", text: "The classic '2 and 20' fee structure refers to:", optionA: "A 2% management fee plus a 20% incentive fee", optionB: "A 2-year lock-up and 20 investors", optionC: "A 20% management fee", optionD: "A 2% hurdle rate", correctOption: "A", explanation: "'2 and 20' is a 2% management fee and a 20% performance (incentive) fee.", orderIndex: 1 },
  { id: "cfa-alternative-investments-overview-q03", topicId: "cfa-alternative-investments-overview", text: "A hurdle rate in a private fund is:", optionA: "The minimum return before incentive fees are charged", optionB: "The management fee", optionC: "The redemption penalty", optionD: "The fund's benchmark index", correctOption: "A", explanation: "Incentive fees apply only to returns above the hurdle rate.", orderIndex: 2 },
  { id: "cfa-alternative-investments-overview-q04", topicId: "cfa-alternative-investments-overview", text: "A high-water mark ensures incentive fees are charged only on:", optionA: "Gains above the previous peak value", optionB: "Gross assets", optionC: "The management fee", optionD: "The hurdle rate", correctOption: "A", explanation: "The high-water mark prevents charging performance fees twice for recovering earlier losses.", orderIndex: 3 },
  { id: "cfa-alternative-investments-overview-q05", topicId: "cfa-alternative-investments-overview", text: "A frequently cited portfolio benefit of alternatives is:", optionA: "Low correlation with traditional assets (diversification)", optionB: "Zero fees", optionC: "Guaranteed liquidity", optionD: "No manager risk", correctOption: "A", explanation: "Many alternatives have low correlation with stocks and bonds, aiding diversification.", orderIndex: 4 },
  { id: "cfa-alternative-investments-overview-q06", topicId: "cfa-alternative-investments-overview", text: "Most private funds are organised as:", optionA: "Limited partnerships (GP manages, LPs invest)", optionB: "Public corporations", optionC: "Exchange-traded funds", optionD: "Money-market funds", correctOption: "A", explanation: "A general partner manages the fund while limited partners provide capital with limited liability.", orderIndex: 5 },
  { id: "cfa-alternative-investments-overview-q07", topicId: "cfa-alternative-investments-overview", text: "The 'J-curve' in private equity describes:", optionA: "Early negative returns followed by later gains", optionB: "Constant returns", optionC: "Immediate high returns", optionD: "A steady decline", correctOption: "A", explanation: "Fees and early write-downs depress initial returns, which typically improve as investments mature.", orderIndex: 6 },
  { id: "cfa-alternative-investments-overview-q08", topicId: "cfa-alternative-investments-overview", text: "Committed capital that a private fund can call over time is drawn down via:", optionA: "Capital calls", optionB: "Dividend reinvestment", optionC: "Coupon payments", optionD: "Stock splits", correctOption: "A", explanation: "GPs issue capital calls to draw committed capital from LPs as investments are made.", orderIndex: 7 },
  { id: "cfa-alternative-investments-overview-q09", topicId: "cfa-alternative-investments-overview", text: "Which is a category of alternative investment?", optionA: "Private equity", optionB: "Listed government bonds", optionC: "Publicly traded blue-chip stock", optionD: "A savings account", correctOption: "A", explanation: "Alternatives include hedge funds, private equity/debt, real estate, infrastructure and commodities.", orderIndex: 8 },
  { id: "cfa-alternative-investments-overview-q10", topicId: "cfa-alternative-investments-overview", text: "A lock-up period in a hedge fund:", optionA: "Restricts investor redemptions for a set time", optionB: "Guarantees returns", optionC: "Eliminates fees", optionD: "Sets the benchmark", correctOption: "A", explanation: "Lock-ups (and gates) limit withdrawals, giving managers time to execute illiquid strategies.", orderIndex: 9 },
  { id: "cfa-alternative-investments-overview-q11", topicId: "cfa-alternative-investments-overview", text: "Compared with traditional investments, alternatives typically charge:", optionA: "Higher fees", optionB: "No fees", optionC: "Lower fees", optionD: "Only exit fees", correctOption: "A", explanation: "Alternatives generally carry higher management and performance fees than traditional funds.", orderIndex: 10 },
  { id: "cfa-alternative-investments-overview-q12", topicId: "cfa-alternative-investments-overview", text: "Because of their complexity and illiquidity, alternatives require:", optionA: "Extensive due diligence", optionB: "No analysis", optionC: "Daily marking only", optionD: "Public disclosure of all trades", correctOption: "A", explanation: "Thorough operational and investment due diligence is essential given limited transparency.", orderIndex: 11 },

  // ── Alternatives: Digital Assets & Tokenisation ──
  { id: "cfa-alternative-investments-digital-assets-q01", topicId: "cfa-alternative-investments-digital-assets", text: "Most digital assets are recorded on a:", optionA: "Distributed ledger (blockchain)", optionB: "Central bank spreadsheet", optionC: "Single private server", optionD: "Paper register", correctOption: "A", explanation: "Digital assets are typically tracked on decentralised blockchains.", orderIndex: 0 },
  { id: "cfa-alternative-investments-digital-assets-q02", topicId: "cfa-alternative-investments-digital-assets", text: "A defining feature of a cryptocurrency such as Bitcoin is that it is:", optionA: "Decentralised with no central issuing authority", optionB: "Issued by a central bank", optionC: "Backed by gold by law", optionD: "Guaranteed by governments", correctOption: "A", explanation: "Cryptocurrencies operate on decentralised networks without a central issuer.", orderIndex: 1 },
  { id: "cfa-alternative-investments-digital-assets-q03", topicId: "cfa-alternative-investments-digital-assets", text: "The mechanism that lets a blockchain network agree on valid transactions is a:", optionA: "Consensus mechanism (e.g., proof of work)", optionB: "Central clearinghouse", optionC: "Credit rating", optionD: "Coupon schedule", correctOption: "A", explanation: "Consensus mechanisms like proof of work or proof of stake validate and secure the ledger.", orderIndex: 2 },
  { id: "cfa-alternative-investments-digital-assets-q04", topicId: "cfa-alternative-investments-digital-assets", text: "A stablecoin is a digital asset designed to:", optionA: "Maintain a stable value relative to a reference such as a fiat currency", optionB: "Maximise volatility", optionC: "Pay a fixed coupon", optionD: "Represent a unique artwork", correctOption: "A", explanation: "Stablecoins peg their value to a reference asset (often a fiat currency) to reduce volatility.", orderIndex: 3 },
  { id: "cfa-alternative-investments-digital-assets-q05", topicId: "cfa-alternative-investments-digital-assets", text: "A non-fungible token (NFT) represents:", optionA: "A unique, non-interchangeable digital item", optionB: "A fixed-income bond", optionC: "A share of stock", optionD: "A stable currency", correctOption: "A", explanation: "NFTs are unique tokens representing ownership of a specific digital (or linked physical) item.", orderIndex: 4 },
  { id: "cfa-alternative-investments-digital-assets-q06", topicId: "cfa-alternative-investments-digital-assets", text: "A smart contract is best described as:", optionA: "Self-executing code that runs when conditions are met", optionB: "A paper legal agreement", optionC: "A central bank rule", optionD: "A mutual fund prospectus", correctOption: "A", explanation: "Smart contracts automatically execute agreed terms on a blockchain when conditions are satisfied.", orderIndex: 5 },
  { id: "cfa-alternative-investments-digital-assets-q07", topicId: "cfa-alternative-investments-digital-assets", text: "Tokenisation refers to:", optionA: "Representing claims on real assets as blockchain tokens", optionB: "Printing paper certificates", optionC: "Splitting a stock", optionD: "Issuing a government bond", correctOption: "A", explanation: "Tokenisation records ownership of real assets on a blockchain to improve divisibility and liquidity.", orderIndex: 6 },
  { id: "cfa-alternative-investments-digital-assets-q08", topicId: "cfa-alternative-investments-digital-assets", text: "A key risk of investing in digital assets is:", optionA: "Extreme price volatility and regulatory uncertainty", optionB: "Guaranteed low returns", optionC: "Excessive liquidity", optionD: "Government insurance", correctOption: "A", explanation: "Digital assets face high volatility, evolving regulation, and custody/security risks.", orderIndex: 7 },
  { id: "cfa-alternative-investments-digital-assets-q09", topicId: "cfa-alternative-investments-digital-assets", text: "The immutability of a blockchain means records are:", optionA: "Extremely difficult to alter once confirmed", optionB: "Editable by anyone", optionC: "Deleted daily", optionD: "Stored centrally", correctOption: "A", explanation: "Cryptographic linking makes confirmed blockchain records very hard to change, supporting trust.", orderIndex: 8 },
  { id: "cfa-alternative-investments-digital-assets-q10", topicId: "cfa-alternative-investments-digital-assets", text: "Investors can gain exposure to cryptocurrencies through:", optionA: "Direct holdings, futures, or funds", optionB: "Only physical coins", optionC: "Only government bonds", optionD: "Bank deposits exclusively", correctOption: "A", explanation: "Exposure is available via direct ownership, listed futures, and investment funds/ETPs.", orderIndex: 9 },
  { id: "cfa-alternative-investments-digital-assets-q11", topicId: "cfa-alternative-investments-digital-assets", text: "A significant custody risk unique to digital assets is:", optionA: "Loss or theft of private keys", optionB: "Coupon default", optionC: "Dividend cuts", optionD: "Index rebalancing", correctOption: "A", explanation: "Whoever controls the private keys controls the assets; lost or stolen keys mean permanent loss.", orderIndex: 10 },
  { id: "cfa-alternative-investments-digital-assets-q12", topicId: "cfa-alternative-investments-digital-assets", text: "'Proof of stake' is an example of a:", optionA: "Consensus mechanism", optionB: "Fee structure", optionC: "Derivative contract", optionD: "Credit rating", correctOption: "A", explanation: "Proof of stake is a consensus mechanism that validates transactions based on staked holdings, an alternative to proof of work.", orderIndex: 11 },

  // ── Portfolio Management: The Process ──
  { id: "cfa-portfolio-management-process-q01", topicId: "cfa-portfolio-management-process", text: "The three steps of the portfolio management process are planning, execution and:", optionA: "Feedback", optionB: "Taxation", optionC: "Marketing", optionD: "Auditing", correctOption: "A", explanation: "The process is plan (IPS), execute (allocate and select), and feedback (monitor, rebalance, evaluate).", orderIndex: 0 },
  { id: "cfa-portfolio-management-process-q02", topicId: "cfa-portfolio-management-process", text: "The planning step culminates in the:", optionA: "Investment Policy Statement (IPS)", optionB: "Trade blotter", optionC: "Annual report", optionD: "Tax return", correctOption: "A", explanation: "Planning produces the IPS, which documents objectives and constraints.", orderIndex: 1 },
  { id: "cfa-portfolio-management-process-q03", topicId: "cfa-portfolio-management-process", text: "A defined-benefit pension plan's investment risk is borne primarily by the:", optionA: "Plan sponsor (employer)", optionB: "Employee only", optionC: "Government", optionD: "Custodian", correctOption: "A", explanation: "In a DB plan the sponsor promises defined benefits and bears the investment risk; in a DC plan the employee does.", orderIndex: 2 },
  { id: "cfa-portfolio-management-process-q04", topicId: "cfa-portfolio-management-process", text: "An open-end mutual fund trades at:", optionA: "Its net asset value (NAV)", optionB: "A premium set by the exchange", optionC: "A fixed price forever", optionD: "The coupon rate", correctOption: "A", explanation: "Open-end funds issue and redeem shares at NAV; closed-end funds trade on an exchange at market prices.", orderIndex: 3 },
  { id: "cfa-portfolio-management-process-q05", topicId: "cfa-portfolio-management-process", text: "A key advantage of ETFs is that they:", optionA: "Trade intraday on an exchange and are often tax-efficient", optionB: "Cannot be bought by individuals", optionC: "Never track an index", optionD: "Guarantee returns", correctOption: "A", explanation: "ETFs trade like stocks throughout the day, typically track indexes, and are relatively tax-efficient.", orderIndex: 4 },
  { id: "cfa-portfolio-management-process-q06", topicId: "cfa-portfolio-management-process", text: "The primary rationale for holding a diversified portfolio is to:", optionA: "Reduce risk for a given level of expected return", optionB: "Guarantee the highest return", optionC: "Avoid all taxes", optionD: "Eliminate market risk", correctOption: "A", explanation: "Diversification across imperfectly correlated assets lowers risk without necessarily sacrificing expected return.", orderIndex: 5 },
  { id: "cfa-portfolio-management-process-q07", topicId: "cfa-portfolio-management-process", text: "Endowments and foundations typically have:", optionA: "Long time horizons and ongoing spending needs", optionB: "One-year horizons", optionC: "No return objective", optionD: "Guaranteed liabilities like insurers", correctOption: "A", explanation: "Endowments/foundations invest for the long term to support perpetual spending.", orderIndex: 6 },
  { id: "cfa-portfolio-management-process-q08", topicId: "cfa-portfolio-management-process", text: "The execution step includes:", optionA: "Asset allocation and security selection", optionB: "Writing the IPS", optionC: "Only performance review", optionD: "Setting tax law", correctOption: "A", explanation: "Execution translates the plan into a portfolio via allocation and security selection.", orderIndex: 7 },
  { id: "cfa-portfolio-management-process-q09", topicId: "cfa-portfolio-management-process", text: "Insurance companies and banks are examples of investors that are largely:", optionA: "Liability-driven", optionB: "Return-only focused", optionC: "Unconstrained", optionD: "Tax-exempt endowments", correctOption: "A", explanation: "Insurers and banks manage assets against specific liabilities, shaping their risk and liquidity needs.", orderIndex: 8 },
  { id: "cfa-portfolio-management-process-q10", topicId: "cfa-portfolio-management-process", text: "The feedback step involves monitoring, rebalancing and:", optionA: "Performance evaluation", optionB: "Underwriting bonds", optionC: "Issuing shares", optionD: "Setting monetary policy", correctOption: "A", explanation: "Feedback monitors the portfolio and client, rebalances, and evaluates results versus the benchmark.", orderIndex: 9 },
  { id: "cfa-portfolio-management-process-q11", topicId: "cfa-portfolio-management-process", text: "A separately managed account (SMA) differs from a mutual fund in that the investor:", optionA: "Directly owns the underlying securities", optionB: "Owns fund shares only", optionC: "Cannot customise", optionD: "Has no manager", correctOption: "A", explanation: "In an SMA the client directly owns the securities, allowing customisation, unlike pooled fund shares.", orderIndex: 10 },
  { id: "cfa-portfolio-management-process-q12", topicId: "cfa-portfolio-management-process", text: "A defined-contribution plan differs from a defined-benefit plan in that:", optionA: "The employee bears the investment risk", optionB: "The employer guarantees the benefit", optionC: "Benefits are fixed by formula", optionD: "It cannot be invested", correctOption: "A", explanation: "In a DC plan, contributions are defined and the employee bears the investment outcome and risk.", orderIndex: 11 },

  // ── Portfolio Management: Fintech ──
  { id: "cfa-portfolio-management-fintech-q01", topicId: "cfa-portfolio-management-fintech", text: "Fintech is best described as:", optionA: "Technology-driven innovation in financial services", optionB: "A type of government bond", optionC: "A tax strategy", optionD: "A stock exchange", correctOption: "A", explanation: "Fintech refers to technological innovation applied to financial products and services.", orderIndex: 0 },
  { id: "cfa-portfolio-management-fintech-q02", topicId: "cfa-portfolio-management-fintech", text: "The 'three Vs' commonly used to characterise big data are volume, velocity and:", optionA: "Variety", optionB: "Volatility", optionC: "Value only", optionD: "Verification", correctOption: "A", explanation: "Big data is described by volume, velocity and variety.", orderIndex: 1 },
  { id: "cfa-portfolio-management-fintech-q03", topicId: "cfa-portfolio-management-fintech", text: "Machine learning that uses labelled data to make predictions is:", optionA: "Supervised learning", optionB: "Unsupervised learning", optionC: "Reinforcement only", optionD: "Manual analysis", correctOption: "A", explanation: "Supervised learning trains on labelled inputs and outputs to predict or classify.", orderIndex: 2 },
  { id: "cfa-portfolio-management-fintech-q04", topicId: "cfa-portfolio-management-fintech", text: "Unsupervised learning is typically used to:", optionA: "Find structure or clusters in unlabelled data", optionB: "Predict a known label", optionC: "Execute trades", optionD: "Set interest rates", correctOption: "A", explanation: "Unsupervised algorithms discover patterns or groupings without predefined labels.", orderIndex: 3 },
  { id: "cfa-portfolio-management-fintech-q05", topicId: "cfa-portfolio-management-fintech", text: "Natural language processing (NLP) is used in finance to:", optionA: "Extract information and sentiment from text", optionB: "Store trades", optionC: "Set margin requirements", optionD: "Print reports", correctOption: "A", explanation: "NLP analyses text such as filings, news and social media for information and sentiment.", orderIndex: 4 },
  { id: "cfa-portfolio-management-fintech-q06", topicId: "cfa-portfolio-management-fintech", text: "A robo-adviser provides:", optionA: "Automated, low-cost investment advice and allocation", optionB: "Guaranteed returns", optionC: "Only tax filing", optionD: "Physical bank branches", correctOption: "A", explanation: "Robo-advisers deliver algorithm-driven advice and portfolio management at low cost.", orderIndex: 5 },
  { id: "cfa-portfolio-management-fintech-q07", topicId: "cfa-portfolio-management-fintech", text: "Alternative data includes sources such as:", optionA: "Social media and satellite/sensor data", optionB: "Audited financial statements only", optionC: "Official GDP figures only", optionD: "Company annual reports only", correctOption: "A", explanation: "Alternative data comes from non-traditional sources like social media, sensors and transaction records.", orderIndex: 6 },
  { id: "cfa-portfolio-management-fintech-q08", topicId: "cfa-portfolio-management-fintech", text: "Algorithmic trading refers to:", optionA: "Executing orders automatically according to predefined rules", optionB: "Manual floor trading", optionC: "Long-term buy and hold only", optionD: "Central bank operations", correctOption: "A", explanation: "Algorithmic trading uses computer rules to place and manage orders, often at high speed.", orderIndex: 7 },
  { id: "cfa-portfolio-management-fintech-q09", topicId: "cfa-portfolio-management-fintech", text: "Deep learning is based on:", optionA: "Multi-layered neural networks", optionB: "Simple linear regression only", optionC: "Manual rules", optionD: "Spreadsheets", correctOption: "A", explanation: "Deep learning uses neural networks with many layers to model complex patterns.", orderIndex: 8 },
  { id: "cfa-portfolio-management-fintech-q10", topicId: "cfa-portfolio-management-fintech", text: "A key risk when applying machine learning to investing is:", optionA: "Overfitting the model to noise in the data", optionB: "Too little data always", optionC: "Guaranteed profits", optionD: "No need for validation", correctOption: "A", explanation: "Overfitting captures noise rather than signal, producing models that fail out of sample.", orderIndex: 9 },
  { id: "cfa-portfolio-management-fintech-q11", topicId: "cfa-portfolio-management-fintech", text: "Distributed ledger technology can benefit finance by:", optionA: "Enabling faster, more secure settlement and tokenisation", optionB: "Eliminating all market risk", optionC: "Guaranteeing returns", optionD: "Removing the need for data", correctOption: "A", explanation: "DLT can streamline clearing/settlement and support tokenised assets with strong security.", orderIndex: 10 },
  { id: "cfa-portfolio-management-fintech-q12", topicId: "cfa-portfolio-management-fintech", text: "High-frequency trading is a form of algorithmic trading characterised by:", optionA: "Very high speed and large order volumes", optionB: "Long holding periods", optionC: "Manual execution", optionD: "Annual rebalancing", correctOption: "A", explanation: "HFT executes many orders at extremely high speed, holding positions very briefly.", orderIndex: 11 }
];
