// CFA Level I depth expansion (pass 8). Adds high-yield learning modules that
// the six-topic-per-area base was missing, across Ethics, Quantitative Methods,
// Economics, Financial Statement Analysis and Corporate Issuers — most notably
// Capital Budgeting (NPV/IRR), a core L1 topic that was absent. Each new topic
// has a 2-minute study note and a full 12-question drill.
import type { AuthoredMaterial } from "./builder";
import type { Question, Topic } from "@jyotir/core";

export const exp8Topics: Topic[] = [
  // Ethics (existing max orderIndex = 5)
  { id: "cfa-ethics-duties-to-employers", subjectId: "cfa-ethics", name: "Duties to Employers (Standard IV)", slug: "duties-to-employers", orderIndex: 6 },
  { id: "cfa-ethics-investment-analysis-recommendations", subjectId: "cfa-ethics", name: "Investment Analysis & Recommendations (Standard V)", slug: "investment-analysis-recommendations", orderIndex: 7 },
  // Quantitative Methods
  { id: "cfa-quantitative-methods-descriptive-statistics", subjectId: "cfa-quantitative-methods", name: "Descriptive Statistics & Data", slug: "descriptive-statistics", orderIndex: 6 },
  { id: "cfa-quantitative-methods-rates-of-return", subjectId: "cfa-quantitative-methods", name: "Rates of Return: TWR & MWR", slug: "rates-of-return", orderIndex: 7 },
  // Economics
  { id: "cfa-economics-demand-supply-elasticity", subjectId: "cfa-economics", name: "Demand, Supply & Elasticity", slug: "demand-supply-elasticity", orderIndex: 6 },
  { id: "cfa-economics-aggregate-output-growth", subjectId: "cfa-economics", name: "Aggregate Output, Demand & Growth", slug: "aggregate-output-growth", orderIndex: 7 },
  // Financial Statement Analysis (subjectId cfa-financial-reporting)
  { id: "cfa-financial-reporting-standards-framework", subjectId: "cfa-financial-reporting", name: "Financial Reporting Standards (IFRS vs GAAP)", slug: "standards-framework", orderIndex: 6 },
  { id: "cfa-financial-reporting-long-term-liabilities-leases", subjectId: "cfa-financial-reporting", name: "Long-term Liabilities & Leases", slug: "long-term-liabilities-leases", orderIndex: 7 },
  // Corporate Issuers
  { id: "cfa-corporate-issuers-capital-budgeting", subjectId: "cfa-corporate-issuers", name: "Capital Budgeting: NPV & IRR", slug: "capital-budgeting", orderIndex: 6 },
  { id: "cfa-corporate-issuers-business-models", subjectId: "cfa-corporate-issuers", name: "Business Models & Structures", slug: "business-models", orderIndex: 7 }
];

export const exp8Materials: AuthoredMaterial[] = [
  { id: "cfa-ethics-duties-to-employers-m01", topicId: "cfa-ethics-duties-to-employers", title: "Duties to Employers (Standard IV)", content: `**Standard IV — Duties to Employers** governs a member's conduct toward the firm that employs them.

## The three sub-standards
| Sub-standard | Requirement |
| --- | --- |
| **IV(A) Loyalty** | Act for the employer's benefit; do not deprive it of your skills, divulge confidential information, or harm it. You may prepare to compete, but not compete while employed. |
| **IV(B) Additional Compensation Arrangements** | Do not accept gifts, benefits or compensation that competes with, or creates a conflict with, the employer's interest **without written consent** from all parties. |
| **IV(C) Responsibilities of Supervisors** | Make reasonable efforts to **prevent and detect violations** by anyone under your supervision; ensure adequate compliance procedures exist. |

## Key points
- **Loyalty** does not prohibit whistle-blowing that protects clients or the market — protecting the integrity of the market can override loyalty to the employer.
- Independent practice for compensation while employed requires employer consent.
- A supervisor who lacks the authority or tools to enforce compliance should **decline supervisory responsibility** in writing until adequate procedures are adopted.
- 'Skills and abilities' developed on the job generally belong to the member, but client lists, files and confidential data belong to the employer.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "cfa-ethics-investment-analysis-recommendations-m01", topicId: "cfa-ethics-investment-analysis-recommendations", title: "Investment Analysis & Recommendations (Standard V)", content: `**Standard V — Investment Analysis, Recommendations, and Actions** governs the research and advice members provide.

## The three sub-standards
| Sub-standard | Requirement |
| --- | --- |
| **V(A) Diligence and Reasonable Basis** | Exercise diligence, independence and thoroughness; have a **reasonable and adequate basis**, supported by research, for any analysis, recommendation or action. |
| **V(B) Communication with Clients & Prospects** | **Distinguish fact from opinion**, disclose the basic format and general principles of the investment process, and identify limitations and risks. |
| **V(C) Record Retention** | Keep records supporting analyses, recommendations and actions. Absent a regulatory requirement, CFA Institute recommends a **7-year** minimum. |

## Key points
- When relying on a third party's (or group) research, a member must make **reasonable efforts to verify** its soundness.
- Members must communicate significant **changes** in risk characteristics and identify which factors are material.
- Records are the property of the **firm**; a member cannot take them to a new employer.
- 'Reasonable basis' scales with the significance of the recommendation and the sophistication of the client.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "cfa-quantitative-methods-descriptive-statistics-m01", topicId: "cfa-quantitative-methods-descriptive-statistics", title: "Descriptive Statistics & Data", content: `**Descriptive statistics** summarise a data set's central tendency, dispersion and shape.

## Central tendency
- **Arithmetic mean** — the simple average; sensitive to outliers.
- **Median** — the middle value; robust to outliers.
- **Mode** — the most frequent value.
- **Geometric mean** — used for compound growth/returns; always **≤ arithmetic mean**.
- **Harmonic mean** — used for averaging ratios (e.g., cost averaging).

## Dispersion
- **Range, mean absolute deviation, variance, standard deviation.**
- **Coefficient of variation (CV) = σ / mean** — risk per unit of return; **lower is better**.

## Shape
| Feature | Description |
| --- | --- |
| **Positive (right) skew** | Long right tail; **mean > median > mode** |
| **Negative (left) skew** | Long left tail; **mean < median < mode** |
| **Kurtosis** | 'Peakedness'/tails. **Leptokurtic** (excess > 0) has fat tails; **platykurtic** (< 0) thin tails; normal is **mesokurtic** (excess = 0) |

- **Quantiles** (quartiles, deciles, percentiles) divide data into equal parts.
- **Chebyshev's inequality**: at least 1 − 1/k² of observations lie within k standard deviations of the mean.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "cfa-quantitative-methods-rates-of-return-m01", topicId: "cfa-quantitative-methods-rates-of-return", title: "Rates of Return: TWR & MWR", content: `## Holding period return
\`\`\`
HPR = (P_end − P_begin + income) / P_begin
\`\`\`

## Money-weighted vs time-weighted return
| Measure | Definition | Sensitive to cash-flow timing? |
| --- | --- | --- |
| **Money-weighted return (MWR)** | The **IRR** of all portfolio cash flows | **Yes** — reflects the investor's timing/size of contributions |
| **Time-weighted return (TWR)** | The **geometric mean** of sub-period returns | **No** — neutral to external flows |

- The **TWR** is preferred for evaluating a **manager**, because the manager usually does not control the timing of client deposits and withdrawals.
- The **MWR** better reflects the **investor's** actual experience.

## Mean returns
- **Geometric mean return** measures compound growth; it is **≤ the arithmetic mean** (equal only when all returns are identical).
- **Arithmetic mean** is the best estimate of a single-period expected return.

## Adjustments
- **Gross vs net** (before/after fees), **pre-tax vs after-tax**, and **nominal vs real** (adjusted for inflation) returns. A **leveraged** return magnifies both gains and losses.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "cfa-economics-demand-supply-elasticity-m01", topicId: "cfa-economics-demand-supply-elasticity", title: "Demand, Supply & Elasticity", content: `The **law of demand** says quantity demanded falls as price rises (downward-sloping demand); the **law of supply** says quantity supplied rises with price. **Equilibrium** is where the two curves intersect.

## Price elasticity of demand
\`\`\`
E_d = (% change in quantity demanded) / (% change in price)
\`\`\`
| |E_d| | Interpretation |
| --- | --- |
| **> 1** | Elastic (quantity very responsive) |
| **< 1** | Inelastic (quantity insensitive) |
| **= 1** | Unit elastic |

Demand is **more elastic** when there are close substitutes, the good is a luxury, it is a large share of the budget, and over a **longer time horizon**.

## Other elasticities
- **Income elasticity**: positive for **normal** goods, negative for **inferior** goods.
- **Cross-price elasticity**: positive for **substitutes**, negative for **complements**.

## Surplus
- **Consumer surplus** = value to buyers − price paid; **producer surplus** = price received − cost. Total surplus is maximised at the competitive equilibrium.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "cfa-economics-aggregate-output-growth-m01", topicId: "cfa-economics-aggregate-output-growth", title: "Aggregate Output, Demand & Growth", content: `## Aggregate demand and supply
- **Aggregate demand (AD)** = C + I + G + (X − M); it slopes downward in price-level/output space.
- **Short-run aggregate supply (SRAS)** slopes upward; **long-run aggregate supply (LRAS)** is vertical at **potential GDP** (full employment).
- Shifts in AD or AS move the economy's equilibrium output and price level.

## The business cycle
Phases: **expansion → peak → contraction (recession) → trough**, and back. Inflation tends to build near peaks; unemployment rises in contractions.

## Sources of economic growth
Output is described by a **production function** using **labour, capital, and technology**:
- **Capital deepening** — more capital per worker (subject to diminishing returns).
- **Total factor productivity (TFP)** — technological progress and efficiency; the main driver of sustained per-capita growth.

## Key measures
- **Real vs nominal GDP** (deflated by the GDP deflator).
- **Potential GDP** — the sustainable, non-inflationary level of output.
- The **Solow (neoclassical) model** shows economies converging to a steady state where only technology raises long-run per-capita output.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "cfa-financial-reporting-standards-framework-m01", topicId: "cfa-financial-reporting-standards-framework", title: "Financial Reporting Standards (IFRS vs GAAP)", content: `Financial reporting aims to give **useful information** to capital providers. The two dominant frameworks are **IFRS** (set by the **IASB**) and **US GAAP** (set by the **FASB**).

## Qualitative characteristics (IFRS Conceptual Framework)
| Fundamental | Enhancing |
| --- | --- |
| **Relevance**, **Faithful representation** | Comparability, Verifiability, Timeliness, Understandability |

- **Constraints**: cost (benefit vs cost) and materiality.
- Underlying assumptions: **accrual basis** and **going concern**.

## Elements
Assets, liabilities, equity, income, and expenses.

## Selected IFRS vs US GAAP differences
| Item | IFRS | US GAAP |
| --- | --- | --- |
| **Inventory (LIFO)** | Prohibited | Permitted |
| **Inventory write-down reversal** | Allowed | Prohibited |
| **Development costs** | Capitalise if criteria met | Generally expensed |
| **Revaluation of PP&E** | Allowed (revaluation model) | Not allowed |

- IFRS is more **principles-based**; US GAAP is more **rules-based**. Both are moving toward convergence in key areas (e.g., revenue recognition, leases).`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "cfa-financial-reporting-long-term-liabilities-leases-m01", topicId: "cfa-financial-reporting-long-term-liabilities-leases", title: "Long-term Liabilities & Leases", content: `## Bonds payable
A bond is issued at **par, a premium, or a discount** depending on how its coupon compares with the market rate at issuance:
| Coupon vs market rate | Issued at |
| --- | --- |
| Coupon > market | **Premium** |
| Coupon = market | **Par** |
| Coupon < market | **Discount** |

- Interest expense is recognised using the **effective interest method**: interest expense = carrying value × market yield at issuance.
- For a **discount** bond the carrying value rises toward par over time; for a **premium** bond it falls toward par.

## Leases
- A **finance (capital) lease** transfers substantially all the risks and rewards of ownership; the lessee records a **right-of-use asset** and a **lease liability**.
- Under **IFRS 16**, lessees recognise nearly **all** leases on the balance sheet (a single model), removing most operating-lease off-balance-sheet treatment.
- An **operating lease** (under US GAAP for lessees) still records a right-of-use asset and liability but expenses a single straight-line lease cost.
- Covenants restrict the borrower to protect lenders; breaching them can trigger default.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "cfa-corporate-issuers-capital-budgeting-m01", topicId: "cfa-corporate-issuers-capital-budgeting", title: "Capital Budgeting: NPV & IRR", content: `**Capital budgeting** evaluates long-term investment projects. Analysts use **incremental after-tax cash flows**, ignore **sunk costs**, and include **opportunity costs** and **externalities**.

## Decision rules
| Method | Rule | Notes |
| --- | --- | --- |
| **Net Present Value (NPV)** | Accept if **NPV > 0** | PV of cash flows − initial outlay; adds value directly |
| **Internal Rate of Return (IRR)** | Accept if **IRR > required return** | The rate that makes NPV = 0 |
| **Payback period** | Shorter is better | Ignores the time value of money and cash flows after payback |
| **Discounted payback** | Shorter is better | Uses discounted cash flows but still ignores later flows |
| **Profitability index (PI)** | Accept if **PI > 1** | PI = PV of future cash flows / initial outlay = 1 + NPV/outlay |

## NPV vs IRR
- For **independent** projects, NPV and IRR give the same accept/reject decision.
- For **mutually exclusive** projects they can conflict (due to scale or timing). **Always prefer NPV** — it assumes reinvestment at the cost of capital and measures value added, whereas IRR assumes reinvestment at the IRR and can give multiple or misleading answers.
- A project's NPV equals the theoretical increase in shareholder wealth.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "cfa-corporate-issuers-business-models-m01", topicId: "cfa-corporate-issuers-business-models", title: "Business Models & Structures", content: `## Business model
A **business model** describes how a firm creates and captures value: **who** the customers are, **what** is offered, **how** it is delivered (channels), and the **pricing/revenue** approach. Examples: **subscription**, **freemium**, **razor-and-blades**, **licensing**, and platform/network models.

## Legal structures
| Form | Liability | Life / features |
| --- | --- | --- |
| **Sole proprietorship** | Unlimited personal liability | Simplest; owner and firm are one |
| **Partnership** | Partners liable (general) | Shared ownership; limited partners have limited liability |
| **Corporation** | **Limited liability** for shareholders | Separate legal entity, perpetual life, easier capital raising, but potential double taxation |

## Stakeholders
A firm balances **shareholders** (owners) with other **stakeholders** — creditors, employees, customers, suppliers, government and the community. Corporate governance manages the conflicts among them.

## Company types
- **Growth** companies reinvest heavily; **defensive** companies have stable demand across the cycle; **cyclical** companies' fortunes swing with the economy. Understanding the model clarifies a firm's revenue durability, cost structure and competitive position.`, estimatedReadTime: 2, orderIndex: 0 }
];

export const exp8Questions: Question[] = [
  // ── Ethics: Duties to Employers (Standard IV) ──
  { id: "cfa-ethics-duties-to-employers-q01", topicId: "cfa-ethics-duties-to-employers", text: "Standard IV(A) Loyalty requires members to:", optionA: "Act for the benefit of their employer and not deprive it of their skills", optionB: "Always prioritise personal profit", optionC: "Share confidential files with competitors", optionD: "Ignore employer interests", correctOption: "A", explanation: "Loyalty requires acting for the employer's benefit and not harming it or divulging confidential information.", orderIndex: 0 },
  { id: "cfa-ethics-duties-to-employers-q02", topicId: "cfa-ethics-duties-to-employers", text: "Under Standard IV(B), a member may accept outside compensation that competes with the employer only if:", optionA: "Written consent is obtained from all parties", optionB: "It is kept secret", optionC: "It is under a certain amount", optionD: "The client approves verbally", correctOption: "A", explanation: "Additional compensation arrangements require written consent from all parties involved.", orderIndex: 1 },
  { id: "cfa-ethics-duties-to-employers-q03", topicId: "cfa-ethics-duties-to-employers", text: "Standard IV(C) Responsibilities of Supervisors requires a member to:", optionA: "Make reasonable efforts to prevent and detect violations by subordinates", optionB: "Personally execute all trades", optionC: "Guarantee no violations ever occur", optionD: "Avoid all supervisory roles", correctOption: "A", explanation: "Supervisors must take reasonable steps, including adequate compliance systems, to prevent and detect violations.", orderIndex: 2 },
  { id: "cfa-ethics-duties-to-employers-q04", topicId: "cfa-ethics-duties-to-employers", text: "Whistle-blowing that protects the integrity of the market:", optionA: "Can override the duty of loyalty to the employer", optionB: "Always violates Standard IV(A)", optionC: "Is never permitted", optionD: "Requires client payment", correctOption: "A", explanation: "Loyalty does not require concealing wrongdoing; protecting clients and the market can justify whistle-blowing.", orderIndex: 3 },
  { id: "cfa-ethics-duties-to-employers-q05", topicId: "cfa-ethics-duties-to-employers", text: "While still employed, a member who wishes to start a competing business may:", optionA: "Make preparations but not compete until employment ends", optionB: "Solicit the employer's clients immediately", optionC: "Take client files home", optionD: "Use employer resources freely", correctOption: "A", explanation: "Members may prepare to compete but must not actually compete with, or misappropriate from, the employer while employed.", orderIndex: 4 },
  { id: "cfa-ethics-duties-to-employers-q06", topicId: "cfa-ethics-duties-to-employers", text: "A supervisor who lacks adequate compliance procedures should:", optionA: "Decline supervisory responsibility in writing until systems are adopted", optionB: "Proceed and hope for the best", optionC: "Delegate all responsibility informally", optionD: "Resign immediately", correctOption: "A", explanation: "If a supervisor cannot discharge the duty, they should decline in writing until adequate procedures are in place.", orderIndex: 5 },
  { id: "cfa-ethics-duties-to-employers-q07", topicId: "cfa-ethics-duties-to-employers", text: "Which of the following generally belongs to the employer, not the departing member?", optionA: "Client lists and files", optionB: "The member's general skills", optionC: "The member's professional knowledge", optionD: "The member's experience", correctOption: "A", explanation: "Client lists, records and confidential data are employer property; a member's skills and experience are their own.", orderIndex: 6 },
  { id: "cfa-ethics-duties-to-employers-q08", topicId: "cfa-ethics-duties-to-employers", text: "Standard IV covers a member's duties to their:", optionA: "Employer", optionB: "Regulator", optionC: "Family", optionD: "Competitors", correctOption: "A", explanation: "Standard IV — Duties to Employers — addresses loyalty, additional compensation and supervisory responsibilities.", orderIndex: 7 },
  { id: "cfa-ethics-duties-to-employers-q09", topicId: "cfa-ethics-duties-to-employers", text: "Independent practice for compensation during employment requires:", optionA: "The employer's consent", optionB: "No disclosure", optionC: "A regulator's licence only", optionD: "Client anonymity", correctOption: "A", explanation: "Undertaking independent, compensated practice that could conflict with the employer requires the employer's consent.", orderIndex: 8 },
  { id: "cfa-ethics-duties-to-employers-q10", topicId: "cfa-ethics-duties-to-employers", text: "A gift from a client to a member for future performance is best treated under Standard IV(B) by:", optionA: "Disclosing it and obtaining written consent", optionB: "Accepting it quietly", optionC: "Refusing to inform anyone", optionD: "Returning it without disclosure", correctOption: "A", explanation: "Compensation arrangements that may create a conflict require disclosure and written consent from all parties.", orderIndex: 9 },
  { id: "cfa-ethics-duties-to-employers-q11", topicId: "cfa-ethics-duties-to-employers", text: "The primary purpose of Standard IV(C) is to:", optionA: "Ensure those under supervision comply with laws and the Code", optionB: "Increase trading volume", optionC: "Maximise the supervisor's pay", optionD: "Avoid record-keeping", correctOption: "A", explanation: "Supervisors are responsible for guiding and monitoring subordinates to comply with applicable rules and the Code.", orderIndex: 10 },
  { id: "cfa-ethics-duties-to-employers-q12", topicId: "cfa-ethics-duties-to-employers", text: "Divulging an employer's confidential business information to outsiders violates:", optionA: "Standard IV(A) Loyalty", optionB: "Standard VI(C) Referral Fees", optionC: "GIPS", optionD: "Standard II(B)", correctOption: "A", explanation: "Disclosing confidential employer information breaches the duty of loyalty under Standard IV(A).", orderIndex: 11 },

  // ── Ethics: Investment Analysis & Recommendations (Standard V) ──
  { id: "cfa-ethics-investment-analysis-recommendations-q01", topicId: "cfa-ethics-investment-analysis-recommendations", text: "Standard V(A) Diligence and Reasonable Basis requires that recommendations be:", optionA: "Supported by appropriate research and a reasonable basis", optionB: "Based on rumours", optionC: "Identical for all clients", optionD: "Made without analysis", correctOption: "A", explanation: "Members must have a reasonable and adequate basis, supported by research and investigation, for their recommendations.", orderIndex: 0 },
  { id: "cfa-ethics-investment-analysis-recommendations-q02", topicId: "cfa-ethics-investment-analysis-recommendations", text: "Standard V(B) Communication with Clients requires members to:", optionA: "Distinguish fact from opinion and disclose the investment process", optionB: "Hide all risks", optionC: "Guarantee returns", optionD: "Present opinions as facts", correctOption: "A", explanation: "Members must separate fact from opinion and disclose the basic process, limitations and risks of their analysis.", orderIndex: 1 },
  { id: "cfa-ethics-investment-analysis-recommendations-q03", topicId: "cfa-ethics-investment-analysis-recommendations", text: "In the absence of regulatory requirements, CFA Institute recommends retaining supporting records for at least:", optionA: "7 years", optionB: "1 year", optionC: "3 months", optionD: "30 years", correctOption: "A", explanation: "Standard V(C) Record Retention recommends keeping records for a minimum of seven years absent other requirements.", orderIndex: 2 },
  { id: "cfa-ethics-investment-analysis-recommendations-q04", topicId: "cfa-ethics-investment-analysis-recommendations", text: "When relying on third-party research, a member must:", optionA: "Make reasonable efforts to verify its soundness", optionB: "Accept it without question", optionC: "Never use it", optionD: "Claim it as original work", correctOption: "A", explanation: "Members using others' research should take reasonable steps to confirm it has a sound basis.", orderIndex: 3 },
  { id: "cfa-ethics-investment-analysis-recommendations-q05", topicId: "cfa-ethics-investment-analysis-recommendations", text: "Investment records that support a member's analysis are the property of the:", optionA: "Firm (employer)", optionB: "Member personally", optionC: "Client only", optionD: "Regulator", correctOption: "A", explanation: "Supporting records belong to the firm; a departing member may not take them.", orderIndex: 4 },
  { id: "cfa-ethics-investment-analysis-recommendations-q06", topicId: "cfa-ethics-investment-analysis-recommendations", text: "A member presenting a projection as a certainty would violate:", optionA: "Standard V(B) Communication with Clients", optionB: "Standard III(A)", optionC: "GIPS", optionD: "Standard IV(A)", correctOption: "A", explanation: "Presenting opinion or projection as fact breaches the requirement to distinguish fact from opinion.", orderIndex: 5 },
  { id: "cfa-ethics-investment-analysis-recommendations-q07", topicId: "cfa-ethics-investment-analysis-recommendations", text: "The level of diligence required under V(A) should be:", optionA: "Proportionate to the significance of the recommendation", optionB: "The same regardless of context", optionC: "Minimal for large clients", optionD: "Skipped for repeat clients", correctOption: "A", explanation: "Reasonable basis scales with the importance of the recommendation and the client's reliance on it.", orderIndex: 6 },
  { id: "cfa-ethics-investment-analysis-recommendations-q08", topicId: "cfa-ethics-investment-analysis-recommendations", text: "Standard V(B) also requires members to identify:", optionA: "The limitations and risks inherent in an investment", optionB: "Only the upside", optionC: "The employer's profit", optionD: "Competitors' fees", correctOption: "A", explanation: "Members must disclose material limitations and risks so clients can judge the analysis.", orderIndex: 7 },
  { id: "cfa-ethics-investment-analysis-recommendations-q09", topicId: "cfa-ethics-investment-analysis-recommendations", text: "Which factors in a report are members required to highlight?", optionA: "Those material to the investment decision", optionB: "Every trivial detail equally", optionC: "None, to keep it short", optionD: "Only positive factors", correctOption: "A", explanation: "Members should identify which factors are material to the analysis and decision.", orderIndex: 8 },
  { id: "cfa-ethics-investment-analysis-recommendations-q10", topicId: "cfa-ethics-investment-analysis-recommendations", text: "Standard V(C) Record Retention primarily supports:", optionA: "The reasonable basis for recommendations and actions", optionB: "Marketing campaigns", optionC: "Tax evasion", optionD: "Higher fees", correctOption: "A", explanation: "Retained records document the analysis and reasonable basis behind recommendations and actions.", orderIndex: 9 },
  { id: "cfa-ethics-investment-analysis-recommendations-q11", topicId: "cfa-ethics-investment-analysis-recommendations", text: "A member develops a quantitative model; under V(B) they should disclose:", optionA: "The basic principles and known limitations of the process", optionB: "The full proprietary code to everyone", optionC: "Nothing about the method", optionD: "Only the fee", correctOption: "A", explanation: "Members should communicate the general principles and limitations of their process without necessarily revealing proprietary details.", orderIndex: 10 },
  { id: "cfa-ethics-investment-analysis-recommendations-q12", topicId: "cfa-ethics-investment-analysis-recommendations", text: "Standard V as a whole governs:", optionA: "Investment analysis, recommendations and actions", optionB: "Duties to employers", optionC: "Conflicts of interest", optionD: "GIPS compliance", correctOption: "A", explanation: "Standard V covers diligence, communication with clients, and record retention for analysis and recommendations.", orderIndex: 11 },

  // ── Quant: Descriptive Statistics & Data ──
  { id: "cfa-quantitative-methods-descriptive-statistics-q01", topicId: "cfa-quantitative-methods-descriptive-statistics", text: "The measure of central tendency most affected by extreme outliers is the:", optionA: "Arithmetic mean", optionB: "Median", optionC: "Mode", optionD: "Range", correctOption: "A", explanation: "The arithmetic mean uses every observation, so it is sensitive to outliers; the median is more robust.", orderIndex: 0 },
  { id: "cfa-quantitative-methods-descriptive-statistics-q02", topicId: "cfa-quantitative-methods-descriptive-statistics", text: "The best measure of the compound rate of growth over multiple periods is the:", optionA: "Geometric mean", optionB: "Arithmetic mean", optionC: "Mode", optionD: "Range", correctOption: "A", explanation: "The geometric mean captures compounding and is appropriate for average growth/return rates.", orderIndex: 1 },
  { id: "cfa-quantitative-methods-descriptive-statistics-q03", topicId: "cfa-quantitative-methods-descriptive-statistics", text: "For a data set, the geometric mean is always:", optionA: "Less than or equal to the arithmetic mean", optionB: "Greater than the arithmetic mean", optionC: "Equal to the mode", optionD: "Equal to the range", correctOption: "A", explanation: "The geometric mean is less than or equal to the arithmetic mean, with equality only when all values are identical.", orderIndex: 2 },
  { id: "cfa-quantitative-methods-descriptive-statistics-q04", topicId: "cfa-quantitative-methods-descriptive-statistics", text: "The coefficient of variation (CV) is calculated as:", optionA: "Standard deviation / mean", optionB: "Mean / standard deviation", optionC: "Variance / mean", optionD: "Range / median", correctOption: "A", explanation: "CV = σ/mean measures risk per unit of return; a lower CV is preferred.", orderIndex: 3 },
  { id: "cfa-quantitative-methods-descriptive-statistics-q05", topicId: "cfa-quantitative-methods-descriptive-statistics", text: "In a positively (right) skewed distribution, the typical ordering is:", optionA: "Mean > median > mode", optionB: "Mean < median < mode", optionC: "Mean = median = mode", optionD: "Median > mean > mode", correctOption: "A", explanation: "A long right tail pulls the mean above the median and mode.", orderIndex: 4 },
  { id: "cfa-quantitative-methods-descriptive-statistics-q06", topicId: "cfa-quantitative-methods-descriptive-statistics", text: "A distribution with fatter tails than the normal distribution is described as:", optionA: "Leptokurtic", optionB: "Platykurtic", optionC: "Mesokurtic", optionD: "Symmetric", correctOption: "A", explanation: "Leptokurtic distributions have positive excess kurtosis — more peaked with fatter tails than normal.", orderIndex: 5 },
  { id: "cfa-quantitative-methods-descriptive-statistics-q07", topicId: "cfa-quantitative-methods-descriptive-statistics", text: "The excess kurtosis of a normal distribution is:", optionA: "0", optionB: "3", optionC: "1", optionD: "Undefined", correctOption: "A", explanation: "Kurtosis of the normal distribution is 3, so its excess kurtosis (kurtosis − 3) is 0.", orderIndex: 6 },
  { id: "cfa-quantitative-methods-descriptive-statistics-q08", topicId: "cfa-quantitative-methods-descriptive-statistics", text: "Values that divide a distribution into four equal parts are:", optionA: "Quartiles", optionB: "Deciles", optionC: "Percentiles", optionD: "Modes", correctOption: "A", explanation: "Quartiles split ranked data into four equal parts; deciles into ten and percentiles into a hundred.", orderIndex: 7 },
  { id: "cfa-quantitative-methods-descriptive-statistics-q09", topicId: "cfa-quantitative-methods-descriptive-statistics", text: "The harmonic mean is most appropriate for:", optionA: "Averaging ratios such as cost per share when investing a fixed amount", optionB: "Measuring skewness", optionC: "Compound growth", optionD: "Counting outliers", correctOption: "A", explanation: "The harmonic mean suits averaging rates/ratios, e.g., dollar-cost-averaging purchase prices.", orderIndex: 8 },
  { id: "cfa-quantitative-methods-descriptive-statistics-q10", topicId: "cfa-quantitative-methods-descriptive-statistics", text: "Chebyshev's inequality states that at least 1 − 1/k² of observations lie within:", optionA: "k standard deviations of the mean", optionB: "k means of the median", optionC: "One range of the mode", optionD: "The interquartile range", correctOption: "A", explanation: "Chebyshev's inequality bounds the proportion of data within k standard deviations of the mean for any distribution.", orderIndex: 9 },
  { id: "cfa-quantitative-methods-descriptive-statistics-q11", topicId: "cfa-quantitative-methods-descriptive-statistics", text: "Which measure of dispersion is in the same units as the data and most commonly used?", optionA: "Standard deviation", optionB: "Variance", optionC: "Skewness", optionD: "Kurtosis", correctOption: "A", explanation: "Standard deviation, the square root of variance, is expressed in the data's own units.", orderIndex: 10 },
  { id: "cfa-quantitative-methods-descriptive-statistics-q12", topicId: "cfa-quantitative-methods-descriptive-statistics", text: "In a negatively (left) skewed distribution, the mean is:", optionA: "Less than the median", optionB: "Greater than the median", optionC: "Equal to the mode", optionD: "Equal to the range", correctOption: "A", explanation: "A long left tail pulls the mean below the median (mean < median < mode).", orderIndex: 11 },

  // ── Quant: Rates of Return: TWR & MWR ──
  { id: "cfa-quantitative-methods-rates-of-return-q01", topicId: "cfa-quantitative-methods-rates-of-return", text: "The money-weighted rate of return is equivalent to the:", optionA: "Internal rate of return of the portfolio's cash flows", optionB: "Geometric mean of sub-period returns", optionC: "Arithmetic mean return", optionD: "Risk-free rate", correctOption: "A", explanation: "The MWR is the IRR that sets the present value of all cash flows (in and out) to zero.", orderIndex: 0 },
  { id: "cfa-quantitative-methods-rates-of-return-q02", topicId: "cfa-quantitative-methods-rates-of-return", text: "The time-weighted rate of return is preferred for evaluating a manager because it:", optionA: "Is not affected by the timing of client cash flows", optionB: "Rewards good deposit timing", optionC: "Ignores compounding", optionD: "Equals the arithmetic mean", correctOption: "A", explanation: "TWR removes the distorting effect of client deposits/withdrawals the manager does not control.", orderIndex: 1 },
  { id: "cfa-quantitative-methods-rates-of-return-q03", topicId: "cfa-quantitative-methods-rates-of-return", text: "The holding period return equals:", optionA: "(Ending value − beginning value + income) / beginning value", optionB: "Ending value / income", optionC: "Income − beginning value", optionD: "Beginning value / ending value", correctOption: "A", explanation: "HPR combines price change and income relative to the beginning value.", orderIndex: 2 },
  { id: "cfa-quantitative-methods-rates-of-return-q04", topicId: "cfa-quantitative-methods-rates-of-return", text: "The money-weighted return is most sensitive to:", optionA: "The size and timing of external cash flows", optionB: "The number of holdings", optionC: "The benchmark used", optionD: "The custodian", correctOption: "A", explanation: "Because it is an IRR, the MWR is heavily influenced by when and how much cash is added or withdrawn.", orderIndex: 3 },
  { id: "cfa-quantitative-methods-rates-of-return-q05", topicId: "cfa-quantitative-methods-rates-of-return", text: "The time-weighted return over multiple sub-periods is computed as the:", optionA: "Geometric mean of the sub-period returns", optionB: "Simple sum of returns", optionC: "Arithmetic mean of returns", optionD: "Largest sub-period return", correctOption: "A", explanation: "TWR chains sub-period returns geometrically: (1+r₁)(1+r₂)…−1.", orderIndex: 4 },
  { id: "cfa-quantitative-methods-rates-of-return-q06", topicId: "cfa-quantitative-methods-rates-of-return", text: "A return adjusted for inflation is called a:", optionA: "Real return", optionB: "Nominal return", optionC: "Gross return", optionD: "Leveraged return", correctOption: "A", explanation: "The real return strips out inflation from the nominal return.", orderIndex: 5 },
  { id: "cfa-quantitative-methods-rates-of-return-q07", topicId: "cfa-quantitative-methods-rates-of-return", text: "A gross return differs from a net return in that the net return is:", optionA: "After deducting management and administrative fees", optionB: "Before all fees", optionC: "Before taxes only", optionD: "Always higher", correctOption: "A", explanation: "Net return subtracts fees (and sometimes other costs) from the gross return.", orderIndex: 6 },
  { id: "cfa-quantitative-methods-rates-of-return-q08", topicId: "cfa-quantitative-methods-rates-of-return", text: "When there are no external cash flows during the period, the money-weighted and time-weighted returns are:", optionA: "Equal", optionB: "Always different", optionC: "Both zero", optionD: "Negatively related", correctOption: "A", explanation: "Without interim cash flows, the two return measures coincide.", orderIndex: 7 },
  { id: "cfa-quantitative-methods-rates-of-return-q09", topicId: "cfa-quantitative-methods-rates-of-return", text: "The best single-period expected-return estimate is usually the:", optionA: "Arithmetic mean return", optionB: "Geometric mean return", optionC: "Harmonic mean", optionD: "Median return", correctOption: "A", explanation: "The arithmetic mean is the unbiased estimate of a single-period expected return; the geometric mean measures realized compound growth.", orderIndex: 8 },
  { id: "cfa-quantitative-methods-rates-of-return-q10", topicId: "cfa-quantitative-methods-rates-of-return", text: "A leveraged return, compared with the unleveraged return, tends to:", optionA: "Magnify both gains and losses", optionB: "Reduce risk", optionC: "Eliminate volatility", optionD: "Equal the risk-free rate", correctOption: "A", explanation: "Leverage amplifies the portfolio's returns in both directions.", orderIndex: 9 },
  { id: "cfa-quantitative-methods-rates-of-return-q11", topicId: "cfa-quantitative-methods-rates-of-return", text: "If large deposits were made just before a strong market rally, the money-weighted return will be ___ the time-weighted return.", optionA: "Higher than", optionB: "Lower than", optionC: "Equal to", optionD: "Unrelated to", correctOption: "A", explanation: "Good timing of contributions boosts the MWR relative to the flow-neutral TWR.", orderIndex: 10 },
  { id: "cfa-quantitative-methods-rates-of-return-q12", topicId: "cfa-quantitative-methods-rates-of-return", text: "The measure that best reflects the actual return earned by the investor is the:", optionA: "Money-weighted return", optionB: "Time-weighted return", optionC: "Benchmark return", optionD: "Gross return", correctOption: "A", explanation: "The MWR reflects the investor's actual experience given the timing of their cash flows.", orderIndex: 11 },

  // ── Economics: Demand, Supply & Elasticity ──
  { id: "cfa-economics-demand-supply-elasticity-q01", topicId: "cfa-economics-demand-supply-elasticity", text: "The law of demand states that, all else equal, as price rises the quantity demanded:", optionA: "Falls", optionB: "Rises", optionC: "Stays constant", optionD: "Becomes infinite", correctOption: "A", explanation: "The demand curve slopes downward: higher prices reduce quantity demanded.", orderIndex: 0 },
  { id: "cfa-economics-demand-supply-elasticity-q02", topicId: "cfa-economics-demand-supply-elasticity", text: "Market equilibrium occurs where:", optionA: "Quantity demanded equals quantity supplied", optionB: "Demand is zero", optionC: "Price is highest", optionD: "Supply is vertical", correctOption: "A", explanation: "Equilibrium is the price and quantity at which the demand and supply curves intersect.", orderIndex: 1 },
  { id: "cfa-economics-demand-supply-elasticity-q03", topicId: "cfa-economics-demand-supply-elasticity", text: "If the price elasticity of demand is greater than 1 in absolute value, demand is:", optionA: "Elastic", optionB: "Inelastic", optionC: "Unit elastic", optionD: "Perfectly inelastic", correctOption: "A", explanation: "An elasticity above 1 means quantity is relatively responsive to price — elastic demand.", orderIndex: 2 },
  { id: "cfa-economics-demand-supply-elasticity-q04", topicId: "cfa-economics-demand-supply-elasticity", text: "Demand for a good tends to be more elastic when:", optionA: "Close substitutes are available", optionB: "It is a necessity", optionC: "It is a tiny share of the budget", optionD: "There is little time to adjust", correctOption: "A", explanation: "Availability of substitutes, luxury status, a large budget share and longer time horizons all raise elasticity.", orderIndex: 3 },
  { id: "cfa-economics-demand-supply-elasticity-q05", topicId: "cfa-economics-demand-supply-elasticity", text: "A good with a negative income elasticity of demand is:", optionA: "An inferior good", optionB: "A normal good", optionC: "A luxury good", optionD: "A Giffen good only", correctOption: "A", explanation: "For inferior goods, demand falls as income rises, giving a negative income elasticity.", orderIndex: 4 },
  { id: "cfa-economics-demand-supply-elasticity-q06", topicId: "cfa-economics-demand-supply-elasticity", text: "Two goods with a positive cross-price elasticity of demand are:", optionA: "Substitutes", optionB: "Complements", optionC: "Inferior goods", optionD: "Unrelated", correctOption: "A", explanation: "A positive cross elasticity means a rise in one good's price increases demand for the other — they are substitutes.", orderIndex: 5 },
  { id: "cfa-economics-demand-supply-elasticity-q07", topicId: "cfa-economics-demand-supply-elasticity", text: "Complementary goods have a cross-price elasticity that is:", optionA: "Negative", optionB: "Positive", optionC: "Zero", optionD: "Greater than 1", correctOption: "A", explanation: "For complements, a higher price of one reduces demand for the other, giving a negative cross elasticity.", orderIndex: 6 },
  { id: "cfa-economics-demand-supply-elasticity-q08", topicId: "cfa-economics-demand-supply-elasticity", text: "If demand is inelastic, a price increase will cause total revenue to:", optionA: "Rise", optionB: "Fall", optionC: "Stay the same", optionD: "Become zero", correctOption: "A", explanation: "With inelastic demand, quantity falls less than proportionately, so total revenue rises when price increases.", orderIndex: 7 },
  { id: "cfa-economics-demand-supply-elasticity-q09", topicId: "cfa-economics-demand-supply-elasticity", text: "Consumer surplus is:", optionA: "The value buyers place on a good above the price they pay", optionB: "The producer's profit", optionC: "The tax revenue", optionD: "The total cost of production", correctOption: "A", explanation: "Consumer surplus is the difference between buyers' willingness to pay and the actual price.", orderIndex: 8 },
  { id: "cfa-economics-demand-supply-elasticity-q10", topicId: "cfa-economics-demand-supply-elasticity", text: "Producer surplus is:", optionA: "The price received minus the producer's cost", optionB: "Total revenue", optionC: "Consumer willingness to pay", optionD: "Government subsidy", correctOption: "A", explanation: "Producer surplus is the difference between the price received and the minimum the producer would accept.", orderIndex: 9 },
  { id: "cfa-economics-demand-supply-elasticity-q11", topicId: "cfa-economics-demand-supply-elasticity", text: "Price elasticity of demand is calculated as:", optionA: "% change in quantity demanded / % change in price", optionB: "% change in price / % change in income", optionC: "Quantity / price", optionD: "Price × quantity", correctOption: "A", explanation: "Own-price elasticity is the percentage change in quantity demanded divided by the percentage change in price.", orderIndex: 10 },
  { id: "cfa-economics-demand-supply-elasticity-q12", topicId: "cfa-economics-demand-supply-elasticity", text: "A binding price ceiling set below equilibrium typically causes:", optionA: "A shortage", optionB: "A surplus", optionC: "No effect", optionD: "Higher supply", correctOption: "A", explanation: "A price ceiling below equilibrium raises quantity demanded above quantity supplied, creating a shortage.", orderIndex: 11 },

  // ── Economics: Aggregate Output, Demand & Growth ──
  { id: "cfa-economics-aggregate-output-growth-q01", topicId: "cfa-economics-aggregate-output-growth", text: "The long-run aggregate supply (LRAS) curve is:", optionA: "Vertical at potential GDP", optionB: "Horizontal", optionC: "Downward sloping", optionD: "Upward sloping without limit", correctOption: "A", explanation: "In the long run, output is at potential (full-employment) GDP regardless of the price level, so LRAS is vertical.", orderIndex: 0 },
  { id: "cfa-economics-aggregate-output-growth-q02", topicId: "cfa-economics-aggregate-output-growth", text: "The main driver of sustained growth in output per capita is:", optionA: "Total factor productivity (technology)", optionB: "Population growth alone", optionC: "Inflation", optionD: "Government deficits", correctOption: "A", explanation: "Because capital deepening faces diminishing returns, long-run per-capita growth is driven mainly by technological progress (TFP).", orderIndex: 1 },
  { id: "cfa-economics-aggregate-output-growth-q03", topicId: "cfa-economics-aggregate-output-growth", text: "The order of business cycle phases is:", optionA: "Expansion, peak, contraction, trough", optionB: "Peak, trough, expansion, contraction", optionC: "Trough, contraction, peak, expansion", optionD: "Contraction, expansion, peak, trough", correctOption: "A", explanation: "The cycle runs expansion → peak → contraction → trough, then repeats.", orderIndex: 2 },
  { id: "cfa-economics-aggregate-output-growth-q04", topicId: "cfa-economics-aggregate-output-growth", text: "Aggregate demand consists of:", optionA: "Consumption, investment, government spending and net exports", optionB: "Only consumer spending", optionC: "Exports minus imports only", optionD: "Wages plus profits", correctOption: "A", explanation: "AD = C + I + G + (X − M), mirroring the expenditure approach to GDP.", orderIndex: 3 },
  { id: "cfa-economics-aggregate-output-growth-q05", topicId: "cfa-economics-aggregate-output-growth", text: "Potential GDP is best described as:", optionA: "The economy's sustainable, non-inflationary level of output", optionB: "The highest GDP ever recorded", optionC: "Nominal GDP", optionD: "GDP during a recession", correctOption: "A", explanation: "Potential GDP is the output an economy can sustain at full employment without accelerating inflation.", orderIndex: 4 },
  { id: "cfa-economics-aggregate-output-growth-q06", topicId: "cfa-economics-aggregate-output-growth", text: "Capital deepening (more capital per worker) is subject to:", optionA: "Diminishing marginal returns", optionB: "Constant returns forever", optionC: "Increasing returns without limit", optionD: "Negative output", correctOption: "A", explanation: "Adding capital per worker raises output but at a declining rate — diminishing marginal returns.", orderIndex: 5 },
  { id: "cfa-economics-aggregate-output-growth-q07", topicId: "cfa-economics-aggregate-output-growth", text: "In the Solow (neoclassical) growth model, long-run per-capita growth is ultimately driven by:", optionA: "Technological progress", optionB: "Higher savings alone", optionC: "Population growth", optionD: "Government spending", correctOption: "A", explanation: "At the steady state, only technological progress raises long-run output per capita.", orderIndex: 6 },
  { id: "cfa-economics-aggregate-output-growth-q08", topicId: "cfa-economics-aggregate-output-growth", text: "A rightward shift in aggregate demand, all else equal, tends to:", optionA: "Increase output and the price level in the short run", optionB: "Reduce output", optionC: "Have no effect", optionD: "Lower prices", correctOption: "A", explanation: "Higher AD raises both real output and the price level along an upward-sloping short-run supply curve.", orderIndex: 7 },
  { id: "cfa-economics-aggregate-output-growth-q09", topicId: "cfa-economics-aggregate-output-growth", text: "Real GDP differs from nominal GDP in that real GDP:", optionA: "Is adjusted for changes in the price level", optionB: "Uses current prices", optionC: "Excludes services", optionD: "Includes only exports", correctOption: "A", explanation: "Real GDP holds prices constant (via a base year/deflator) to isolate changes in output.", orderIndex: 8 },
  { id: "cfa-economics-aggregate-output-growth-q10", topicId: "cfa-economics-aggregate-output-growth", text: "Unemployment typically ___ during the contraction phase of the business cycle.", optionA: "Rises", optionB: "Falls", optionC: "Stays flat", optionD: "Disappears", correctOption: "A", explanation: "As output falls in a contraction, firms cut jobs and unemployment rises.", orderIndex: 9 },
  { id: "cfa-economics-aggregate-output-growth-q11", topicId: "cfa-economics-aggregate-output-growth", text: "The production function relates output to inputs of:", optionA: "Labour, capital and technology", optionB: "Only labour", optionC: "Interest rates", optionD: "Tax rates", correctOption: "A", explanation: "Output is produced from labour and capital, scaled by the level of technology/productivity.", orderIndex: 10 },
  { id: "cfa-economics-aggregate-output-growth-q12", topicId: "cfa-economics-aggregate-output-growth", text: "When short-run equilibrium output is below potential GDP, the economy has a:", optionA: "Recessionary gap", optionB: "Inflationary gap", optionC: "Trade surplus", optionD: "Budget surplus", correctOption: "A", explanation: "Output below potential is a recessionary (deflationary) gap, associated with higher unemployment.", orderIndex: 11 },

  // ── FSA: Financial Reporting Standards (IFRS vs GAAP) ──
  { id: "cfa-financial-reporting-standards-framework-q01", topicId: "cfa-financial-reporting-standards-framework", text: "IFRS standards are set by the:", optionA: "IASB", optionB: "FASB", optionC: "SEC", optionD: "PCAOB", correctOption: "A", explanation: "The International Accounting Standards Board (IASB) sets IFRS; the FASB sets US GAAP.", orderIndex: 0 },
  { id: "cfa-financial-reporting-standards-framework-q02", topicId: "cfa-financial-reporting-standards-framework", text: "The two fundamental qualitative characteristics of useful financial information are relevance and:", optionA: "Faithful representation", optionB: "Comparability", optionC: "Timeliness", optionD: "Verifiability", correctOption: "A", explanation: "Relevance and faithful representation are fundamental; comparability, verifiability, timeliness and understandability are enhancing.", orderIndex: 1 },
  { id: "cfa-financial-reporting-standards-framework-q03", topicId: "cfa-financial-reporting-standards-framework", text: "The use of LIFO for inventory is:", optionA: "Permitted under US GAAP but prohibited under IFRS", optionB: "Permitted under IFRS but not US GAAP", optionC: "Prohibited under both", optionD: "Required under both", correctOption: "A", explanation: "US GAAP allows LIFO; IFRS does not permit it.", orderIndex: 2 },
  { id: "cfa-financial-reporting-standards-framework-q04", topicId: "cfa-financial-reporting-standards-framework", text: "Under IFRS, development costs meeting specified criteria are:", optionA: "Capitalised", optionB: "Always expensed", optionC: "Ignored", optionD: "Treated as revenue", correctOption: "A", explanation: "IFRS allows capitalising development costs when technical and commercial feasibility criteria are met; US GAAP generally expenses them.", orderIndex: 3 },
  { id: "cfa-financial-reporting-standards-framework-q05", topicId: "cfa-financial-reporting-standards-framework", text: "Revaluation of property, plant and equipment to fair value is:", optionA: "Allowed under IFRS but not US GAAP", optionB: "Allowed under US GAAP but not IFRS", optionC: "Prohibited under both", optionD: "Required under both", correctOption: "A", explanation: "IFRS permits the revaluation model for PP&E; US GAAP requires historical cost.", orderIndex: 4 },
  { id: "cfa-financial-reporting-standards-framework-q06", topicId: "cfa-financial-reporting-standards-framework", text: "The assumption that a company will continue operating for the foreseeable future is the:", optionA: "Going-concern assumption", optionB: "Accrual assumption", optionC: "Matching principle", optionD: "Materiality constraint", correctOption: "A", explanation: "The going-concern assumption presumes the entity will continue in operation.", orderIndex: 5 },
  { id: "cfa-financial-reporting-standards-framework-q07", topicId: "cfa-financial-reporting-standards-framework", text: "Recognising revenues and expenses when earned/incurred rather than when cash moves reflects:", optionA: "Accrual accounting", optionB: "Cash accounting", optionC: "Tax accounting", optionD: "Fund accounting", correctOption: "A", explanation: "Accrual accounting records transactions when the economic event occurs, not when cash changes hands.", orderIndex: 6 },
  { id: "cfa-financial-reporting-standards-framework-q08", topicId: "cfa-financial-reporting-standards-framework", text: "Which is an enhancing qualitative characteristic of financial information?", optionA: "Comparability", optionB: "Relevance", optionC: "Faithful representation", optionD: "Materiality", correctOption: "A", explanation: "Comparability (with verifiability, timeliness, understandability) is enhancing; relevance and faithful representation are fundamental.", orderIndex: 7 },
  { id: "cfa-financial-reporting-standards-framework-q09", topicId: "cfa-financial-reporting-standards-framework", text: "US GAAP is best described as more:", optionA: "Rules-based", optionB: "Principles-based", optionC: "Cash-based", optionD: "Tax-based", correctOption: "A", explanation: "US GAAP is relatively rules-based, whereas IFRS is more principles-based.", orderIndex: 8 },
  { id: "cfa-financial-reporting-standards-framework-q10", topicId: "cfa-financial-reporting-standards-framework", text: "The five elements of financial statements include assets, liabilities, equity, income and:", optionA: "Expenses", optionB: "Dividends", optionC: "Cash flows", optionD: "Taxes", correctOption: "A", explanation: "The elements are assets, liabilities, equity, income and expenses.", orderIndex: 9 },
  { id: "cfa-financial-reporting-standards-framework-q11", topicId: "cfa-financial-reporting-standards-framework", text: "Under IFRS, the reversal of a prior inventory write-down is:", optionA: "Permitted (up to the original cost)", optionB: "Prohibited", optionC: "Required annually", optionD: "Recorded as revenue", correctOption: "A", explanation: "IFRS allows reversing inventory write-downs when value recovers; US GAAP prohibits reversal.", orderIndex: 10 },
  { id: "cfa-financial-reporting-standards-framework-q12", topicId: "cfa-financial-reporting-standards-framework", text: "A constraint on financial reporting that weighs benefits against the effort to produce information is:", optionA: "The cost constraint", optionB: "Relevance", optionC: "Comparability", optionD: "Going concern", correctOption: "A", explanation: "The cost constraint recognises that the benefits of information should justify the cost of providing it.", orderIndex: 11 },

  // ── FSA: Long-term Liabilities & Leases ──
  { id: "cfa-financial-reporting-long-term-liabilities-leases-q01", topicId: "cfa-financial-reporting-long-term-liabilities-leases", text: "A bond whose coupon rate is below the market rate at issuance is issued at a:", optionA: "Discount", optionB: "Premium", optionC: "Par", optionD: "Zero value", correctOption: "A", explanation: "When the coupon is below the market yield, investors pay less than par — a discount.", orderIndex: 0 },
  { id: "cfa-financial-reporting-long-term-liabilities-leases-q02", topicId: "cfa-financial-reporting-long-term-liabilities-leases", text: "Under the effective interest method, interest expense equals:", optionA: "The carrying value times the market yield at issuance", optionB: "The coupon payment always", optionC: "Face value times coupon rate", optionD: "Zero", correctOption: "A", explanation: "Interest expense = beginning carrying (book) value × the market interest rate at issuance.", orderIndex: 1 },
  { id: "cfa-financial-reporting-long-term-liabilities-leases-q03", topicId: "cfa-financial-reporting-long-term-liabilities-leases", text: "For a bond issued at a discount, the carrying value over time:", optionA: "Increases toward par", optionB: "Decreases toward zero", optionC: "Stays constant", optionD: "Falls below zero", correctOption: "A", explanation: "Discount amortisation raises the carrying value each period until it reaches par at maturity.", orderIndex: 2 },
  { id: "cfa-financial-reporting-long-term-liabilities-leases-q04", topicId: "cfa-financial-reporting-long-term-liabilities-leases", text: "A lease that transfers substantially all the risks and rewards of ownership is a:", optionA: "Finance (capital) lease", optionB: "Operating lease", optionC: "Short-term rental", optionD: "Sublease only", correctOption: "A", explanation: "A finance lease effectively transfers ownership risks and rewards, so the lessee records an asset and liability.", orderIndex: 3 },
  { id: "cfa-financial-reporting-long-term-liabilities-leases-q05", topicId: "cfa-financial-reporting-long-term-liabilities-leases", text: "Under IFRS 16, a lessee recognises for most leases a:", optionA: "Right-of-use asset and a lease liability", optionB: "Only an expense, off balance sheet", optionC: "Revenue item", optionD: "Contra-equity account", correctOption: "A", explanation: "IFRS 16 uses a single lessee model: nearly all leases appear on the balance sheet as a right-of-use asset and lease liability.", orderIndex: 4 },
  { id: "cfa-financial-reporting-long-term-liabilities-leases-q06", topicId: "cfa-financial-reporting-long-term-liabilities-leases", text: "A bond issued at a premium has a coupon rate that is:", optionA: "Above the market rate at issuance", optionB: "Below the market rate", optionC: "Equal to the market rate", optionD: "Zero", correctOption: "A", explanation: "A coupon above the market yield makes the bond worth more than par — a premium.", orderIndex: 5 },
  { id: "cfa-financial-reporting-long-term-liabilities-leases-q07", topicId: "cfa-financial-reporting-long-term-liabilities-leases", text: "Loan covenants primarily serve to:", optionA: "Protect lenders by restricting the borrower's actions", optionB: "Increase the coupon rate", optionC: "Guarantee equity returns", optionD: "Eliminate default risk entirely", correctOption: "A", explanation: "Covenants restrict borrower behaviour (e.g., additional debt, dividends) to protect creditors.", orderIndex: 6 },
  { id: "cfa-financial-reporting-long-term-liabilities-leases-q08", topicId: "cfa-financial-reporting-long-term-liabilities-leases", text: "For a premium bond, interest expense under the effective interest method is:", optionA: "Less than the coupon payment", optionB: "More than the coupon payment", optionC: "Equal to the face value", optionD: "Zero", correctOption: "A", explanation: "For a premium bond, the market yield is below the coupon, so interest expense is less than the cash coupon paid.", orderIndex: 7 },
  { id: "cfa-financial-reporting-long-term-liabilities-leases-q09", topicId: "cfa-financial-reporting-long-term-liabilities-leases", text: "Compared with a finance lease, an operating lease (US GAAP lessee) reports:", optionA: "A single straight-line lease expense", optionB: "Separate interest and amortisation with higher early expense", optionC: "No income-statement effect", optionD: "Revenue recognition", correctOption: "A", explanation: "US GAAP operating leases record a right-of-use asset/liability but expense a single straight-line lease cost.", orderIndex: 8 },
  { id: "cfa-financial-reporting-long-term-liabilities-leases-q10", topicId: "cfa-financial-reporting-long-term-liabilities-leases", text: "At maturity, the carrying value of any bond equals its:", optionA: "Face (par) value", optionB: "Issue price", optionC: "Market price at issuance", optionD: "Zero", correctOption: "A", explanation: "Premiums and discounts fully amortise, so carrying value converges to par at maturity.", orderIndex: 9 },
  { id: "cfa-financial-reporting-long-term-liabilities-leases-q11", topicId: "cfa-financial-reporting-long-term-liabilities-leases", text: "A key motivation for structuring a lease as 'operating' historically was to:", optionA: "Keep the obligation off the balance sheet", optionB: "Raise reported debt", optionC: "Increase taxes", optionD: "Reduce cash flow", correctOption: "A", explanation: "Older rules let operating leases stay off-balance-sheet; new standards (IFRS 16) largely removed this.", orderIndex: 10 },
  { id: "cfa-financial-reporting-long-term-liabilities-leases-q12", topicId: "cfa-financial-reporting-long-term-liabilities-leases", text: "The amount at which a bond liability is reported on the balance sheet is its:", optionA: "Carrying (book) value", optionB: "Face value always", optionC: "Coupon rate", optionD: "Yield to maturity", correctOption: "A", explanation: "Bonds payable are reported at carrying value — face value adjusted for unamortised premium or discount.", orderIndex: 11 },

  // ── Corporate Issuers: Capital Budgeting (NPV & IRR) ──
  { id: "cfa-corporate-issuers-capital-budgeting-q01", topicId: "cfa-corporate-issuers-capital-budgeting", text: "A project should be accepted under the NPV rule if its NPV is:", optionA: "Greater than zero", optionB: "Less than zero", optionC: "Equal to the IRR", optionD: "Equal to the payback period", correctOption: "A", explanation: "A positive NPV means the project adds value, so it should be accepted.", orderIndex: 0 },
  { id: "cfa-corporate-issuers-capital-budgeting-q02", topicId: "cfa-corporate-issuers-capital-budgeting", text: "The internal rate of return (IRR) is the discount rate that makes a project's:", optionA: "NPV equal to zero", optionB: "Payback equal to one year", optionC: "Profitability index equal to zero", optionD: "Cash flows negative", correctOption: "A", explanation: "The IRR is the rate at which the present value of inflows equals the initial outlay (NPV = 0).", orderIndex: 1 },
  { id: "cfa-corporate-issuers-capital-budgeting-q03", topicId: "cfa-corporate-issuers-capital-budgeting", text: "Under the IRR rule, an independent project is accepted if the IRR is:", optionA: "Greater than the required rate of return", optionB: "Less than zero", optionC: "Equal to the payback", optionD: "Below the risk-free rate", correctOption: "A", explanation: "Accept if IRR exceeds the hurdle (required) rate of return.", orderIndex: 2 },
  { id: "cfa-corporate-issuers-capital-budgeting-q04", topicId: "cfa-corporate-issuers-capital-budgeting", text: "When NPV and IRR conflict for two mutually exclusive projects, an analyst should rely on:", optionA: "NPV", optionB: "IRR", optionC: "Payback period", optionD: "Discounted payback", correctOption: "A", explanation: "NPV is theoretically superior; it measures value added and assumes reinvestment at the cost of capital.", orderIndex: 3 },
  { id: "cfa-corporate-issuers-capital-budgeting-q05", topicId: "cfa-corporate-issuers-capital-budgeting", text: "A major weakness of the payback period method is that it:", optionA: "Ignores the time value of money and cash flows after payback", optionB: "Requires a discount rate", optionC: "Always rejects good projects", optionD: "Overstates NPV", correctOption: "A", explanation: "Payback ignores the time value of money and any cash flows occurring after the payback point.", orderIndex: 4 },
  { id: "cfa-corporate-issuers-capital-budgeting-q06", topicId: "cfa-corporate-issuers-capital-budgeting", text: "The profitability index (PI) equals:", optionA: "PV of future cash flows / initial investment", optionB: "NPV × IRR", optionC: "Payback / IRR", optionD: "Initial investment / NPV", correctOption: "A", explanation: "PI = PV of future cash flows ÷ initial outlay = 1 + NPV/outlay; accept if PI > 1.", orderIndex: 5 },
  { id: "cfa-corporate-issuers-capital-budgeting-q07", topicId: "cfa-corporate-issuers-capital-budgeting", text: "In capital budgeting, sunk costs should be:", optionA: "Ignored", optionB: "Included as outflows", optionC: "Added to NPV", optionD: "Treated as revenue", correctOption: "A", explanation: "Sunk costs are already incurred and irrelevant to the incremental decision, so they are excluded.", orderIndex: 6 },
  { id: "cfa-corporate-issuers-capital-budgeting-q08", topicId: "cfa-corporate-issuers-capital-budgeting", text: "The opportunity cost of using a resource the firm already owns should be:", optionA: "Included in the project's cash flows", optionB: "Ignored as sunk", optionC: "Added to NPV twice", optionD: "Treated as financing", correctOption: "A", explanation: "Opportunity costs represent forgone alternatives and must be included in incremental cash flows.", orderIndex: 7 },
  { id: "cfa-corporate-issuers-capital-budgeting-q09", topicId: "cfa-corporate-issuers-capital-budgeting", text: "The NPV of a project represents the:", optionA: "Expected increase in shareholder wealth", optionB: "Payback period in years", optionC: "The IRR", optionD: "The firm's total assets", correctOption: "A", explanation: "A project's NPV is the theoretical addition to the value of the firm and to shareholder wealth.", orderIndex: 8 },
  { id: "cfa-corporate-issuers-capital-budgeting-q10", topicId: "cfa-corporate-issuers-capital-budgeting", text: "The IRR rule can be unreliable when a project has:", optionA: "Non-conventional cash flows (multiple sign changes)", optionB: "A single outflow then inflows", optionC: "Only positive cash flows", optionD: "A zero discount rate", correctOption: "A", explanation: "Non-conventional cash-flow patterns can produce multiple IRRs, making the IRR rule ambiguous.", orderIndex: 9 },
  { id: "cfa-corporate-issuers-capital-budgeting-q11", topicId: "cfa-corporate-issuers-capital-budgeting", text: "The discounted payback period improves on the payback period by:", optionA: "Accounting for the time value of money", optionB: "Ignoring cash flows entirely", optionC: "Using undiscounted flows", optionD: "Adding the IRR", correctOption: "A", explanation: "Discounted payback uses discounted cash flows, though it still ignores flows after the payback point.", orderIndex: 10 },
  { id: "cfa-corporate-issuers-capital-budgeting-q12", topicId: "cfa-corporate-issuers-capital-budgeting", text: "Analysts evaluate projects using ___ cash flows.", optionA: "Incremental after-tax", optionB: "Total historical", optionC: "Pre-tax accounting", optionD: "Sunk", correctOption: "A", explanation: "Capital budgeting uses incremental, after-tax cash flows attributable to the project.", orderIndex: 11 },

  // ── Corporate Issuers: Business Models & Structures ──
  { id: "cfa-corporate-issuers-business-models-q01", topicId: "cfa-corporate-issuers-business-models", text: "A key advantage of the corporate form of organisation is:", optionA: "Limited liability for shareholders", optionB: "Unlimited owner liability", optionC: "A finite one-year life", optionD: "Inability to raise capital", correctOption: "A", explanation: "Corporations give shareholders limited liability and have perpetual life, easing capital raising.", orderIndex: 0 },
  { id: "cfa-corporate-issuers-business-models-q02", topicId: "cfa-corporate-issuers-business-models", text: "A business model describes primarily how a firm:", optionA: "Creates and captures value", optionB: "Files its taxes", optionC: "Sets its share price", optionD: "Chooses its auditor", correctOption: "A", explanation: "A business model explains who the customers are, what is offered, how it is delivered, and how value is captured.", orderIndex: 1 },
  { id: "cfa-corporate-issuers-business-models-q03", topicId: "cfa-corporate-issuers-business-models", text: "In a sole proprietorship, the owner has:", optionA: "Unlimited personal liability", optionB: "Limited liability", optionC: "No liability", optionD: "Perpetual succession", correctOption: "A", explanation: "A sole proprietor is personally liable for all business obligations.", orderIndex: 2 },
  { id: "cfa-corporate-issuers-business-models-q04", topicId: "cfa-corporate-issuers-business-models", text: "A 'razor-and-blades' model earns most profit from:", optionA: "Recurring consumable sales after a low-priced base product", optionB: "A single upfront sale", optionC: "Advertising only", optionD: "Government grants", correctOption: "A", explanation: "The base product is sold cheaply to drive ongoing sales of higher-margin consumables.", orderIndex: 3 },
  { id: "cfa-corporate-issuers-business-models-q05", topicId: "cfa-corporate-issuers-business-models", text: "A subscription business model generates revenue through:", optionA: "Recurring periodic payments for ongoing access", optionB: "One-time product sales only", optionC: "Barter", optionD: "Donations", correctOption: "A", explanation: "Subscriptions produce predictable recurring revenue for continued access to a product or service.", orderIndex: 4 },
  { id: "cfa-corporate-issuers-business-models-q06", topicId: "cfa-corporate-issuers-business-models", text: "A defensive company is one whose demand is:", optionA: "Relatively stable across the business cycle", optionB: "Highly cyclical", optionC: "Zero in recessions", optionD: "Dependent on exports only", correctOption: "A", explanation: "Defensive (non-cyclical) firms, such as utilities and staples, have steady demand regardless of the cycle.", orderIndex: 5 },
  { id: "cfa-corporate-issuers-business-models-q07", topicId: "cfa-corporate-issuers-business-models", text: "In a limited partnership, limited partners have:", optionA: "Liability limited to their investment", optionB: "Unlimited liability", optionC: "Full management control", optionD: "No ownership stake", correctOption: "A", explanation: "Limited partners' liability is capped at their capital contribution; general partners have unlimited liability.", orderIndex: 6 },
  { id: "cfa-corporate-issuers-business-models-q08", topicId: "cfa-corporate-issuers-business-models", text: "A potential drawback of the corporate form is:", optionA: "Double taxation of profits and dividends", optionB: "Unlimited liability", optionC: "A one-year life", optionD: "Difficulty raising equity", correctOption: "A", explanation: "Corporate profits may be taxed at the entity level and again as shareholder dividends — double taxation.", orderIndex: 7 },
  { id: "cfa-corporate-issuers-business-models-q09", topicId: "cfa-corporate-issuers-business-models", text: "A freemium model offers:", optionA: "A basic service free while charging for premium features", optionB: "Everything free forever", optionC: "Only paid access", optionD: "Products by barter", correctOption: "A", explanation: "Freemium gives a free tier to attract users and monetises upgraded, premium features.", orderIndex: 8 },
  { id: "cfa-corporate-issuers-business-models-q10", topicId: "cfa-corporate-issuers-business-models", text: "Beyond shareholders, a company's stakeholders include:", optionA: "Employees, creditors, customers and suppliers", optionB: "Only the CEO", optionC: "Only regulators", optionD: "Only competitors", correctOption: "A", explanation: "Stakeholders are all parties affected by the firm — employees, creditors, customers, suppliers, government and community.", orderIndex: 9 },
  { id: "cfa-corporate-issuers-business-models-q11", topicId: "cfa-corporate-issuers-business-models", text: "A growth company is typically characterised by:", optionA: "Heavy reinvestment and low or no dividends", optionB: "High, stable dividend payouts", optionC: "Declining revenue", optionD: "No reinvestment", correctOption: "A", explanation: "Growth firms reinvest earnings to fund expansion, so they usually pay little or no dividend.", orderIndex: 10 },
  { id: "cfa-corporate-issuers-business-models-q12", topicId: "cfa-corporate-issuers-business-models", text: "A platform (network) business model creates value primarily by:", optionA: "Connecting groups of users who benefit from each other", optionB: "Manufacturing physical goods", optionC: "Holding inventory", optionD: "Paying dividends", correctOption: "A", explanation: "Platform models create value through network effects by connecting complementary user groups (e.g., buyers and sellers).", orderIndex: 11 }
];
