// FRM depth expansion — question-density top-up. Raises the highest-yield FRM
// Part I and Part II topics from 12 to 16 questions each (q13–q16, orderIndex
// 12–15). No new topics or study notes.
import type { Question } from "@jyotir/core";

export const frmDepthQuestions: Question[] = [
  // ── Part I: Foundations — Risk Management & CAPM ──
  { id: "frm-foundations-risk-management-capm-q13", topicId: "frm-foundations-risk-management-capm", text: "In the CAPM, the expected return equals the risk-free rate plus:", optionA: "Beta times the market risk premium", optionB: "The dividend yield", optionC: "Total volatility", optionD: "The inflation rate", correctOption: "A", explanation: "CAPM: E(R) = Rf + β(E(Rm) − Rf).", orderIndex: 12 },
  { id: "frm-foundations-risk-management-capm-q14", topicId: "frm-foundations-risk-management-capm", text: "The Security Market Line plots expected return against:", optionA: "Beta (systematic risk)", optionB: "Total risk", optionC: "Time", optionD: "The dividend yield", correctOption: "A", explanation: "The SML relates expected return to systematic risk (beta).", orderIndex: 13 },
  { id: "frm-foundations-risk-management-capm-q15", topicId: "frm-foundations-risk-management-capm", text: "Under CAPM, diversifiable (unsystematic) risk earns:", optionA: "No risk premium", optionB: "The largest premium", optionC: "A guaranteed return", optionD: "The market premium", correctOption: "A", explanation: "Only systematic risk is priced; unsystematic risk can be diversified away.", orderIndex: 14 },
  { id: "frm-foundations-risk-management-capm-q16", topicId: "frm-foundations-risk-management-capm", text: "A stock with a beta of 1.5 is expected to be ____ the market.", optionA: "More volatile than", optionB: "Less volatile than", optionC: "Uncorrelated with", optionD: "Identical to", correctOption: "A", explanation: "A beta above 1 means the stock amplifies market moves — more volatile.", orderIndex: 15 },

  // ── Part I: Quant — Volatility, EWMA & GARCH ──
  { id: "frm-quantitative-analysis-volatility-ewma-garch-q13", topicId: "frm-quantitative-analysis-volatility-ewma-garch", text: "EWMA gives more weight to:", optionA: "Recent observations", optionB: "The oldest observations", optionC: "All observations equally", optionD: "Future observations", correctOption: "A", explanation: "The exponentially weighted moving average weights recent data more heavily.", orderIndex: 12 },
  { id: "frm-quantitative-analysis-volatility-ewma-garch-q14", topicId: "frm-quantitative-analysis-volatility-ewma-garch", text: "In EWMA, a higher decay factor λ means volatility reacts:", optionA: "More slowly to new shocks", optionB: "Instantly", optionC: "Randomly", optionD: "Never", correctOption: "A", explanation: "A larger λ puts more weight on the past, so volatility responds more slowly.", orderIndex: 13 },
  { id: "frm-quantitative-analysis-volatility-ewma-garch-q15", topicId: "frm-quantitative-analysis-volatility-ewma-garch", text: "GARCH(1,1) models exhibit volatility:", optionA: "Mean reversion", optionB: "Constant variance", optionC: "No clustering", optionD: "Zero persistence", correctOption: "A", explanation: "GARCH(1,1) reverts to a long-run average variance, unlike EWMA.", orderIndex: 14 },
  { id: "frm-quantitative-analysis-volatility-ewma-garch-q16", topicId: "frm-quantitative-analysis-volatility-ewma-garch", text: "Volatility clustering means large moves tend to be:", optionA: "Followed by large moves", optionB: "Followed by calm always", optionC: "Independent", optionD: "Impossible", correctOption: "A", explanation: "Clustering: periods of high volatility persist, which GARCH captures.", orderIndex: 15 },

  // ── Part I: Markets — Futures, Forwards & Hedging ──
  { id: "frm-financial-markets-futures-forwards-hedging-q13", topicId: "frm-financial-markets-futures-forwards-hedging", text: "The optimal hedge ratio equals the correlation times:", optionA: "The ratio of spot to futures volatility", optionB: "The coupon", optionC: "The dividend yield", optionD: "Beta only", correctOption: "A", explanation: "Optimal hedge ratio = ρ × (σ_spot / σ_futures).", orderIndex: 12 },
  { id: "frm-financial-markets-futures-forwards-hedging-q14", topicId: "frm-financial-markets-futures-forwards-hedging", text: "Futures are marked to market:", optionA: "Daily", optionB: "At maturity only", optionC: "Never", optionD: "Annually", correctOption: "A", explanation: "Futures settle gains/losses daily through margin, unlike forwards.", orderIndex: 13 },
  { id: "frm-financial-markets-futures-forwards-hedging-q15", topicId: "frm-financial-markets-futures-forwards-hedging", text: "A long hedge is used to protect against a:", optionA: "Rising price of a future purchase", optionB: "Falling price of a holding", optionC: "Currency appreciation only", optionD: "Coupon cut", correctOption: "A", explanation: "A long hedge (buying futures) locks in the cost of a future purchase.", orderIndex: 14 },
  { id: "frm-financial-markets-futures-forwards-hedging-q16", topicId: "frm-financial-markets-futures-forwards-hedging", text: "The number of futures contracts to hedge depends on the hedge ratio and the:", optionA: "Size of the exposure relative to contract size", optionB: "Coupon", optionC: "Dividend", optionD: "Tax rate", correctOption: "A", explanation: "Contracts = hedge ratio × (exposure value / futures contract value).", orderIndex: 15 },

  // ── Part I: Valuation — Value at Risk ──
  { id: "frm-valuation-risk-models-value-at-risk-q13", topicId: "frm-valuation-risk-models-value-at-risk", text: "A 1-day 99% VaR of $1m means losses exceed $1m on about:", optionA: "1 day in 100", optionB: "99 days in 100", optionC: "Every day", optionD: "Never", correctOption: "A", explanation: "99% VaR is breached roughly 1% of the time — 1 day in 100.", orderIndex: 12 },
  { id: "frm-valuation-risk-models-value-at-risk-q14", topicId: "frm-valuation-risk-models-value-at-risk", text: "A key weakness of VaR is that it says nothing about:", optionA: "The size of losses beyond the threshold", optionB: "The confidence level", optionC: "The holding period", optionD: "The mean return", correctOption: "A", explanation: "VaR gives a threshold but not the magnitude of losses in the tail.", orderIndex: 13 },
  { id: "frm-valuation-risk-models-value-at-risk-q15", topicId: "frm-valuation-risk-models-value-at-risk", text: "To scale 1-day VaR to 10-day VaR (i.i.d. normal), multiply by:", optionA: "√10", optionB: "10", optionC: "100", optionD: "1/10", correctOption: "A", explanation: "Under the square-root-of-time rule, VaR scales with √T.", orderIndex: 14 },
  { id: "frm-valuation-risk-models-value-at-risk-q16", topicId: "frm-valuation-risk-models-value-at-risk", text: "VaR can violate which property of a coherent risk measure?", optionA: "Subadditivity", optionB: "Monotonicity", optionC: "Positive homogeneity", optionD: "Translation invariance", correctOption: "A", explanation: "VaR is not generally subadditive, so it may not be coherent (unlike ES).", orderIndex: 15 },

  // ── Part I: Markets — Options & Black-Scholes ──
  { id: "frm-financial-markets-options-pricing-q13", topicId: "frm-financial-markets-options-pricing", text: "Put–call parity relates a call, a put, the stock, and:", optionA: "A risk-free bond (PV of strike)", optionB: "A dividend", optionC: "The coupon", optionD: "Beta", correctOption: "A", explanation: "c + PV(X) = p + S is put–call parity.", orderIndex: 12 },
  { id: "frm-financial-markets-options-pricing-q14", topicId: "frm-financial-markets-options-pricing", text: "Higher volatility increases the value of:", optionA: "Both calls and puts", optionB: "Only calls", optionC: "Only puts", optionD: "Neither", correctOption: "A", explanation: "Greater volatility raises the value of both call and put options.", orderIndex: 13 },
  { id: "frm-financial-markets-options-pricing-q15", topicId: "frm-financial-markets-options-pricing", text: "Delta measures option-price sensitivity to the:", optionA: "Underlying price", optionB: "Volatility", optionC: "Time", optionD: "Interest rate", correctOption: "A", explanation: "Delta is ∂(option price)/∂(underlying price).", orderIndex: 14 },
  { id: "frm-financial-markets-options-pricing-q16", topicId: "frm-financial-markets-options-pricing", text: "Black–Scholes assumes the underlying follows:", optionA: "Geometric Brownian motion", optionB: "A random Poisson jump only", optionC: "A straight line", optionD: "Mean reversion to zero", correctOption: "A", explanation: "BSM assumes lognormal prices via geometric Brownian motion.", orderIndex: 15 },

  // ── Part I: Valuation — Bond Valuation & Duration ──
  { id: "frm-valuation-risk-models-bond-valuation-q13", topicId: "frm-valuation-risk-models-bond-valuation", text: "A bond's price and its yield are related:", optionA: "Inversely", optionB: "Directly", optionC: "Not at all", optionD: "Only at par", correctOption: "A", explanation: "Bond prices fall when yields rise and vice versa — an inverse relationship.", orderIndex: 12 },
  { id: "frm-valuation-risk-models-bond-valuation-q14", topicId: "frm-valuation-risk-models-bond-valuation", text: "Macaulay duration is the weighted-average time to receive the bond's:", optionA: "Cash flows", optionB: "Coupons only", optionC: "Principal only", optionD: "Dividends", correctOption: "A", explanation: "Macaulay duration weights the timing of all cash flows by present value.", orderIndex: 13 },
  { id: "frm-valuation-risk-models-bond-valuation-q15", topicId: "frm-valuation-risk-models-bond-valuation", text: "A zero-coupon bond's duration equals its:", optionA: "Time to maturity", optionB: "Coupon rate", optionC: "Yield", optionD: "Half its maturity", correctOption: "A", explanation: "With a single cash flow at maturity, a zero's duration equals its maturity.", orderIndex: 14 },
  { id: "frm-valuation-risk-models-bond-valuation-q16", topicId: "frm-valuation-risk-models-bond-valuation", text: "Higher coupon bonds, all else equal, have ____ duration.", optionA: "Lower", optionB: "Higher", optionC: "Zero", optionD: "Infinite", correctOption: "A", explanation: "Larger coupons return value sooner, lowering duration.", orderIndex: 15 },

  // ── Part II: Market Risk — VaR Methods & Backtesting ──
  { id: "frm-market-risk-var-methods-backtesting-q13", topicId: "frm-market-risk-var-methods-backtesting", text: "Backtesting VaR compares the number of ____ to the expected count.", optionA: "Exceptions (breaches)", optionB: "Coupons", optionC: "Dividends", optionD: "Trades", correctOption: "A", explanation: "Backtesting counts VaR exceptions and compares them to the expected rate.", orderIndex: 12 },
  { id: "frm-market-risk-var-methods-backtesting-q14", topicId: "frm-market-risk-var-methods-backtesting", text: "The Basel traffic-light approach classifies backtests into green, yellow and:", optionA: "Red zones", optionB: "Blue zones", optionC: "Black zones", optionD: "Grey zones", correctOption: "A", explanation: "Basel uses green/yellow/red zones based on the number of exceptions.", orderIndex: 13 },
  { id: "frm-market-risk-var-methods-backtesting-q15", topicId: "frm-market-risk-var-methods-backtesting", text: "Too many VaR exceptions suggest the model:", optionA: "Understates risk", optionB: "Overstates risk", optionC: "Is perfect", optionD: "Is coherent", correctOption: "A", explanation: "Excess breaches indicate the model underestimates risk.", orderIndex: 14 },
  { id: "frm-market-risk-var-methods-backtesting-q16", topicId: "frm-market-risk-var-methods-backtesting", text: "The Monte Carlo VaR method relies on:", optionA: "Simulating many random scenarios", optionB: "One historical path", optionC: "A normal assumption only", optionD: "No data", correctOption: "A", explanation: "Monte Carlo VaR generates many simulated scenarios to build the loss distribution.", orderIndex: 15 },

  // ── Part II: Market Risk — Expected Shortfall ──
  { id: "frm-market-risk-expected-shortfall-q13", topicId: "frm-market-risk-expected-shortfall", text: "Expected shortfall is the average loss:", optionA: "Beyond the VaR threshold", optionB: "Below the mean", optionC: "On a typical day", optionD: "In the best case", correctOption: "A", explanation: "ES (conditional VaR) is the expected loss given the VaR level is exceeded.", orderIndex: 12 },
  { id: "frm-market-risk-expected-shortfall-q14", topicId: "frm-market-risk-expected-shortfall", text: "Expected shortfall is always ____ VaR at the same confidence level.", optionA: "Greater than or equal to", optionB: "Less than", optionC: "Equal to only", optionD: "Unrelated to", correctOption: "A", explanation: "ES averages tail losses, so it is at least as large as VaR.", orderIndex: 13 },
  { id: "frm-market-risk-expected-shortfall-q15", topicId: "frm-market-risk-expected-shortfall", text: "A key advantage of ES over VaR is that ES is:", optionA: "Subadditive (coherent)", optionB: "Always smaller", optionC: "Model-free", optionD: "Data-free", correctOption: "A", explanation: "ES satisfies subadditivity, making it a coherent risk measure.", orderIndex: 14 },
  { id: "frm-market-risk-expected-shortfall-q16", topicId: "frm-market-risk-expected-shortfall", text: "FRTB adopted ES at a confidence level of:", optionA: "97.5%", optionB: "99%", optionC: "95%", optionD: "90%", correctOption: "A", explanation: "FRTB uses Expected Shortfall at 97.5% for internal models.", orderIndex: 15 },

  // ── Part II: Credit Risk — Default Probability & Credit VaR ──
  { id: "frm-credit-risk-default-probability-credit-var-q13", topicId: "frm-credit-risk-default-probability-credit-var", text: "Expected loss equals PD times LGD times:", optionA: "EAD", optionB: "Duration", optionC: "The coupon", optionD: "Beta", correctOption: "A", explanation: "Expected loss = PD × LGD × EAD.", orderIndex: 12 },
  { id: "frm-credit-risk-default-probability-credit-var-q14", topicId: "frm-credit-risk-default-probability-credit-var", text: "Credit VaR captures the ____ credit loss at a confidence level.", optionA: "Unexpected", optionB: "Expected only", optionC: "Zero", optionD: "Average", correctOption: "A", explanation: "Credit VaR measures unexpected loss beyond the expected loss.", orderIndex: 13 },
  { id: "frm-credit-risk-default-probability-credit-var-q15", topicId: "frm-credit-risk-default-probability-credit-var", text: "Recovery rate equals one minus the:", optionA: "Loss given default", optionB: "Probability of default", optionC: "Exposure at default", optionD: "Coupon", correctOption: "A", explanation: "Recovery rate = 1 − LGD.", orderIndex: 14 },
  { id: "frm-credit-risk-default-probability-credit-var-q16", topicId: "frm-credit-risk-default-probability-credit-var", text: "A cumulative default probability over multiple years generally:", optionA: "Increases with the horizon", optionB: "Decreases with the horizon", optionC: "Stays constant", optionD: "Is always zero", correctOption: "A", explanation: "The longer the horizon, the higher the cumulative chance of default.", orderIndex: 15 },

  // ── Part II: Credit Risk — Merton Model ──
  { id: "frm-credit-risk-merton-model-q13", topicId: "frm-credit-risk-merton-model", text: "In the Merton model, a firm defaults when asset value falls below:", optionA: "The face value of debt", optionB: "The coupon", optionC: "Zero always", optionD: "The dividend", correctOption: "A", explanation: "Default occurs at maturity if assets are worth less than the debt owed.", orderIndex: 12 },
  { id: "frm-credit-risk-merton-model-q14", topicId: "frm-credit-risk-merton-model", text: "The Merton model treats equity as a:", optionA: "Call option on the firm's assets", optionB: "Risk-free bond", optionC: "Put on debt", optionD: "Forward contract", correctOption: "A", explanation: "Equity holders have a call on the assets with strike equal to the debt.", orderIndex: 13 },
  { id: "frm-credit-risk-merton-model-q15", topicId: "frm-credit-risk-merton-model", text: "Distance to default measures the number of standard deviations to the:", optionA: "Default point", optionB: "Coupon date", optionC: "Dividend", optionD: "Par value", correctOption: "A", explanation: "Distance to default is the gap between asset value and the default threshold in σ units.", orderIndex: 14 },
  { id: "frm-credit-risk-merton-model-q16", topicId: "frm-credit-risk-merton-model", text: "In Merton's framework, risky debt equals risk-free debt minus a:", optionA: "Put option on the assets", optionB: "Call on equity", optionC: "Coupon", optionD: "Dividend", correctOption: "A", explanation: "Holding risky debt equals a risk-free bond minus a put on the firm's assets.", orderIndex: 15 },

  // ── Part II: Operational — Basel Accords & RAROC ──
  { id: "frm-operational-risk-basel-accords-raroc-q13", topicId: "frm-operational-risk-basel-accords-raroc", text: "Basel III introduced a minimum ____ ratio as a non-risk-based backstop.", optionA: "Leverage", optionB: "Dividend", optionC: "Coupon", optionD: "P/E", correctOption: "A", explanation: "The leverage ratio (Tier 1 capital / exposure) is a non-risk-based backstop.", orderIndex: 12 },
  { id: "frm-operational-risk-basel-accords-raroc-q14", topicId: "frm-operational-risk-basel-accords-raroc", text: "The minimum total capital ratio under Basel is:", optionA: "8% of risk-weighted assets", optionB: "2%", optionC: "20%", optionD: "50%", correctOption: "A", explanation: "Basel requires a minimum total capital of 8% of risk-weighted assets.", orderIndex: 13 },
  { id: "frm-operational-risk-basel-accords-raroc-q15", topicId: "frm-operational-risk-basel-accords-raroc", text: "RAROC divides risk-adjusted return by:", optionA: "Economic capital", optionB: "Revenue", optionC: "Total assets", optionD: "Headcount", correctOption: "A", explanation: "RAROC = risk-adjusted return / economic capital.", orderIndex: 14 },
  { id: "frm-operational-risk-basel-accords-raroc-q16", topicId: "frm-operational-risk-basel-accords-raroc", text: "Basel III added a countercyclical capital buffer to:", optionA: "Build capital in booms for use in downturns", optionB: "Lower capital always", optionC: "Pay dividends", optionD: "Raise coupons", correctOption: "A", explanation: "The countercyclical buffer accumulates capital in good times to absorb later stress.", orderIndex: 15 },

  // ── Part II: Liquidity — Liquidity Risk Management ──
  { id: "frm-liquidity-risk-liquidity-risk-management-q13", topicId: "frm-liquidity-risk-liquidity-risk-management", text: "Funding liquidity risk is the risk of being unable to:", optionA: "Meet obligations as they fall due", optionB: "Sell a bond at a fair price", optionC: "Earn a dividend", optionD: "Lower a coupon", correctOption: "A", explanation: "Funding liquidity risk is the inability to meet cash obligations on time.", orderIndex: 12 },
  { id: "frm-liquidity-risk-liquidity-risk-management-q14", topicId: "frm-liquidity-risk-liquidity-risk-management", text: "Market (asset) liquidity risk is the risk that an asset cannot be sold:", optionA: "Quickly without a large price concession", optionB: "At any time", optionC: "With a dividend", optionD: "Above par", correctOption: "A", explanation: "Market liquidity risk is difficulty selling without moving the price.", orderIndex: 13 },
  { id: "frm-liquidity-risk-liquidity-risk-management-q15", topicId: "frm-liquidity-risk-liquidity-risk-management", text: "The bid-ask spread is a measure of:", optionA: "Market liquidity", optionB: "Credit risk", optionC: "Duration", optionD: "Convexity", correctOption: "A", explanation: "A wider bid-ask spread indicates lower market liquidity.", orderIndex: 14 },
  { id: "frm-liquidity-risk-liquidity-risk-management-q16", topicId: "frm-liquidity-risk-liquidity-risk-management", text: "A liquidity buffer is typically held in:", optionA: "High-quality liquid assets", optionB: "Illiquid private equity", optionC: "Real estate", optionD: "Distressed debt", correctOption: "A", explanation: "Buffers use HQLA that can be sold or pledged quickly in stress.", orderIndex: 15 }
];
