// FRM expansion 7 — depth top-up. Adds four more questions (q09–q12) to each
// reading that previously had only eight, bringing every FRM topic to the
// 12-question density used across the rest of the catalog. No new topics or
// materials — these attach to existing readings.
import type { Question } from "@jyotir/core";

export const expansionQuestions: Question[] = [
  // ── Foundations: CAPM ──
  { id: "frm-foundations-risk-management-capm-q09", topicId: "frm-foundations-risk-management-capm", text: "In the CAPM, the only priced (rewarded) risk is:", optionA: "Total volatility", optionB: "Systematic (market) risk", optionC: "Idiosyncratic risk", optionD: "Liquidity risk", correctOption: "B", explanation: "CAPM rewards only non-diversifiable systematic risk measured by beta; idiosyncratic risk is diversified away.", orderIndex: 8 },
  { id: "frm-foundations-risk-management-capm-q10", topicId: "frm-foundations-risk-management-capm", text: "The security market line (SML) plots expected return against:", optionA: "Standard deviation", optionB: "Beta", optionC: "Variance", optionD: "Tracking error", correctOption: "B", explanation: "The SML expresses the linear relationship between expected return and beta under the CAPM.", orderIndex: 9 },
  { id: "frm-foundations-risk-management-capm-q11", topicId: "frm-foundations-risk-management-capm", text: "A stock plotting above the SML is best described as:", optionA: "Overvalued", optionB: "Undervalued (offers excess return for its beta)", optionC: "Fairly valued", optionD: "Risk-free", correctOption: "B", explanation: "Above the SML the asset offers more return than its beta requires, indicating it is underpriced.", orderIndex: 10 },
  { id: "frm-foundations-risk-management-capm-q12", topicId: "frm-foundations-risk-management-capm", text: "The Sharpe ratio measures excess return per unit of:", optionA: "Beta", optionB: "Total risk (standard deviation)", optionC: "Systematic risk", optionD: "Tracking error", correctOption: "B", explanation: "The Sharpe ratio divides excess return by total volatility, unlike the Treynor ratio which uses beta.", orderIndex: 11 },

  // ── Foundations: Risk Types Taxonomy ──
  { id: "frm-foundations-risk-types-taxonomy-q09", topicId: "frm-foundations-risk-types-taxonomy", text: "Market, credit, liquidity, and operational risk are examples of:", optionA: "The major financial-risk categories", optionB: "Non-financial regulation", optionC: "Accounting standards", optionD: "Tax categories", correctOption: "A", explanation: "These are the core risk-type categories a firm's framework must identify and manage.", orderIndex: 8 },
  { id: "frm-foundations-risk-types-taxonomy-q10", topicId: "frm-foundations-risk-types-taxonomy", text: "The risk that a counterparty fails to meet an obligation is:", optionA: "Market risk", optionB: "Credit risk", optionC: "Operational risk", optionD: "Reputational risk", correctOption: "B", explanation: "Credit (default) risk is the risk of loss from a counterparty failing to perform.", orderIndex: 9 },
  { id: "frm-foundations-risk-types-taxonomy-q11", topicId: "frm-foundations-risk-types-taxonomy", text: "Losses from failed internal processes, people, or systems are classified as:", optionA: "Operational risk", optionB: "Market risk", optionC: "Credit risk", optionD: "Liquidity risk", correctOption: "A", explanation: "Operational risk covers failures of processes, people, systems, and external events.", orderIndex: 10 },
  { id: "frm-foundations-risk-types-taxonomy-q12", topicId: "frm-foundations-risk-types-taxonomy", text: "Business and reputational risks are best described as:", optionA: "Always quantifiable like market risk", optionB: "Harder-to-quantify risks affecting strategy and franchise value", optionC: "Forms of credit risk", optionD: "Irrelevant to risk management", correctOption: "B", explanation: "Business/strategic and reputational risks affect long-run viability but are difficult to quantify precisely.", orderIndex: 11 },

  // ── Foundations: Corporate Governance ──
  { id: "frm-foundations-corporate-governance-q09", topicId: "frm-foundations-corporate-governance", text: "The board's risk committee is primarily responsible for:", optionA: "Day-to-day trading", optionB: "Overseeing the risk framework and tolerance", optionC: "Marketing", optionD: "External audit fees", correctOption: "B", explanation: "The board (often via a risk committee) sets and oversees risk appetite and the governance framework.", orderIndex: 8 },
  { id: "frm-foundations-corporate-governance-q10", topicId: "frm-foundations-corporate-governance", text: "A key principle of sound governance is separation between:", optionA: "Risk-taking and risk-control functions", optionB: "Marketing and sales", optionC: "IT and HR", optionD: "Audit and tax", correctOption: "A", explanation: "Independent risk control from the front office prevents conflicts and unchecked risk-taking.", orderIndex: 9 },
  { id: "frm-foundations-corporate-governance-q11", topicId: "frm-foundations-corporate-governance", text: "The Chief Risk Officer (CRO) should ideally report to:", optionA: "The head trader", optionB: "The board/CEO with independence from business lines", optionC: "Sales", optionD: "The external auditor", correctOption: "B", explanation: "An independent CRO reporting to the board/CEO preserves objectivity over business units.", orderIndex: 10 },
  { id: "frm-foundations-corporate-governance-q12", topicId: "frm-foundations-corporate-governance", text: "Aligning management incentives with long-term risk is achieved partly through:", optionA: "Deferred, clawback-eligible compensation", optionB: "Immediate cash-only bonuses", optionC: "Removing all oversight", optionD: "Higher leverage", correctOption: "A", explanation: "Deferral and clawbacks discourage short-term risk-taking that harms the firm later.", orderIndex: 11 },

  // ── Foundations: ERP & Risk Appetite ──
  { id: "frm-foundations-erp-risk-appetite-q09", topicId: "frm-foundations-erp-risk-appetite", text: "A risk appetite statement defines:", optionA: "The amount and type of risk the firm is willing to take", optionB: "The marketing budget", optionC: "Quarterly earnings", optionD: "The dividend policy", correctOption: "A", explanation: "Risk appetite articulates the level and kinds of risk acceptable in pursuit of objectives.", orderIndex: 8 },
  { id: "frm-foundations-erp-risk-appetite-q10", topicId: "frm-foundations-erp-risk-appetite", text: "Enterprise risk management (ERM) is characterized by:", optionA: "Siloed, department-by-department risk", optionB: "An integrated, firm-wide view of risk", optionC: "Ignoring correlations", optionD: "Only market risk", correctOption: "B", explanation: "ERM takes a holistic, enterprise-wide approach aggregating risks against the firm's appetite.", orderIndex: 9 },
  { id: "frm-foundations-erp-risk-appetite-q11", topicId: "frm-foundations-erp-risk-appetite", text: "Risk capacity differs from risk appetite in that capacity is:", optionA: "The maximum risk the firm can bear before distress", optionB: "Always equal to appetite", optionC: "A marketing metric", optionD: "Lower than appetite", correctOption: "A", explanation: "Capacity is the absolute maximum a firm can absorb; appetite is the chosen level within that capacity.", orderIndex: 10 },
  { id: "frm-foundations-erp-risk-appetite-q12", topicId: "frm-foundations-erp-risk-appetite", text: "Risk limits translate appetite into:", optionA: "Operational constraints on desks and exposures", optionB: "Marketing targets", optionC: "Tax filings", optionD: "Audit schedules", correctOption: "A", explanation: "Limits cascade the firm's appetite down to actionable constraints on positions and activities.", orderIndex: 11 },

  // ── Foundations: Financial Disasters ──
  { id: "frm-foundations-financial-disasters-q09", topicId: "frm-foundations-financial-disasters", text: "The collapse of LTCM (1998) primarily illustrates the dangers of:", optionA: "Excessive leverage and liquidity/model risk", optionB: "Too little leverage", optionC: "Avoiding derivatives", optionD: "Overdiversification", correctOption: "A", explanation: "LTCM's huge leverage and convergence bets failed when liquidity dried up and correlations spiked.", orderIndex: 8 },
  { id: "frm-foundations-financial-disasters-q10", topicId: "frm-foundations-financial-disasters", text: "The Barings Bank failure (1995) is a classic case of:", optionA: "Weak operational controls and rogue trading", optionB: "Sovereign default", optionC: "Inflation risk", optionD: "Currency pegs", correctOption: "A", explanation: "Nick Leeson's unchecked, concealed positions reflected a breakdown in operational controls and segregation of duties.", orderIndex: 9 },
  { id: "frm-foundations-financial-disasters-q11", topicId: "frm-foundations-financial-disasters", text: "The 2007–09 crisis highlighted the systemic danger of:", optionA: "Subprime securitization, leverage, and funding liquidity", optionB: "Low housing prices", optionC: "Strong capital buffers", optionD: "Conservative lending", correctOption: "A", explanation: "Leveraged exposure to subprime-backed securities plus funding-liquidity runs propagated systemic losses.", orderIndex: 10 },
  { id: "frm-foundations-financial-disasters-q12", topicId: "frm-foundations-financial-disasters", text: "A common lesson across financial disasters is the need for:", optionA: "Independent risk oversight and stress testing of tail events", optionB: "More leverage", optionC: "Less disclosure", optionD: "Ignoring liquidity", correctOption: "A", explanation: "Recurring themes include weak oversight, underestimating tail/liquidity risk, and poor incentives.", orderIndex: 11 },

  // ── Quant: Volatility (EWMA/GARCH) ──
  { id: "frm-quantitative-analysis-volatility-ewma-garch-q09", topicId: "frm-quantitative-analysis-volatility-ewma-garch", text: "EWMA gives more weight to:", optionA: "Older observations", optionB: "More recent observations", optionC: "All observations equally", optionD: "The mean only", correctOption: "B", explanation: "Exponentially weighted moving average places greater weight on recent data via the decay factor λ.", orderIndex: 8 },
  { id: "frm-quantitative-analysis-volatility-ewma-garch-q10", topicId: "frm-quantitative-analysis-volatility-ewma-garch", text: "A higher λ (lambda) in EWMA implies:", optionA: "Faster reaction to new data", optionB: "Slower decay and smoother, more persistent volatility", optionC: "No weighting", optionD: "Random weights", correctOption: "B", explanation: "A λ near 1 decays slowly, giving smoother volatility that reacts less abruptly to shocks.", orderIndex: 9 },
  { id: "frm-quantitative-analysis-volatility-ewma-garch-q11", topicId: "frm-quantitative-analysis-volatility-ewma-garch", text: "GARCH(1,1) adds which feature versus EWMA?", optionA: "Mean reversion to a long-run variance", optionB: "No persistence", optionC: "Equal weights", optionD: "No recent data", correctOption: "A", explanation: "GARCH(1,1) includes a constant term producing mean reversion to a long-run average variance; EWMA does not.", orderIndex: 10 },
  { id: "frm-quantitative-analysis-volatility-ewma-garch-q12", topicId: "frm-quantitative-analysis-volatility-ewma-garch", text: "In GARCH(1,1), the sum of the ARCH and GARCH coefficients (α+β) measures:", optionA: "Volatility persistence", optionB: "The mean return", optionC: "Skewness", optionD: "The risk-free rate", correctOption: "A", explanation: "α+β close to 1 indicates highly persistent volatility (slow mean reversion); it must be < 1 for stationarity.", orderIndex: 11 },

  // ── Quant: Probability Distributions ──
  { id: "frm-quantitative-analysis-probability-distributions-q09", topicId: "frm-quantitative-analysis-probability-distributions", text: "The binomial distribution models:", optionA: "Number of successes in n independent trials", optionB: "Continuous returns", optionC: "Time between events", optionD: "Infinite outcomes", correctOption: "A", explanation: "The binomial counts successes across n independent Bernoulli trials with fixed probability p.", orderIndex: 8 },
  { id: "frm-quantitative-analysis-probability-distributions-q10", topicId: "frm-quantitative-analysis-probability-distributions", text: "A distribution with positive excess kurtosis is:", optionA: "Thin-tailed", optionB: "Fat-tailed (leptokurtic)", optionC: "Always symmetric", optionD: "Uniform", correctOption: "B", explanation: "Positive excess kurtosis means fatter tails than the normal, implying more extreme outcomes.", orderIndex: 9 },
  { id: "frm-quantitative-analysis-probability-distributions-q11", topicId: "frm-quantitative-analysis-probability-distributions", text: "Negative skewness implies:", optionA: "A longer left tail (large losses more likely than symmetric)", optionB: "A longer right tail", optionC: "No tail", optionD: "Zero variance", correctOption: "A", explanation: "Negative skew has a longer left tail, a concern in risk because of larger-than-normal losses.", orderIndex: 10 },
  { id: "frm-quantitative-analysis-probability-distributions-q12", topicId: "frm-quantitative-analysis-probability-distributions", text: "The Student's t-distribution is often preferred for returns because it:", optionA: "Has fatter tails than the normal", optionB: "Has no variance", optionC: "Is always skewed", optionD: "Ignores extreme events", correctOption: "A", explanation: "The t-distribution's fatter tails better capture the frequency of extreme financial returns.", orderIndex: 11 },

  // ── Quant: Statistical Inference ──
  { id: "frm-quantitative-analysis-statistical-inference-q09", topicId: "frm-quantitative-analysis-statistical-inference", text: "A Type I error in hypothesis testing is:", optionA: "Rejecting a true null hypothesis", optionB: "Accepting a true null", optionC: "A data error", optionD: "Failing to reject a false null", correctOption: "A", explanation: "Type I (false positive) is rejecting a null that is actually true; its probability is the significance level α.", orderIndex: 8 },
  { id: "frm-quantitative-analysis-statistical-inference-q10", topicId: "frm-quantitative-analysis-statistical-inference", text: "The p-value is:", optionA: "The probability of the observed (or more extreme) result if the null is true", optionB: "The probability the null is true", optionC: "The sample mean", optionD: "The variance", correctOption: "A", explanation: "A small p-value means the data would be unlikely under the null, supporting rejection.", orderIndex: 9 },
  { id: "frm-quantitative-analysis-statistical-inference-q11", topicId: "frm-quantitative-analysis-statistical-inference", text: "A 95% confidence interval that excludes zero suggests the parameter is:", optionA: "Statistically significant at the 5% level", optionB: "Always zero", optionC: "Insignificant", optionD: "Negative", correctOption: "A", explanation: "If zero lies outside the 95% interval, the estimate is significant at the 5% level.", orderIndex: 10 },
  { id: "frm-quantitative-analysis-statistical-inference-q12", topicId: "frm-quantitative-analysis-statistical-inference", text: "The power of a test is:", optionA: "1 minus the probability of a Type II error", optionB: "The significance level", optionC: "The sample size", optionD: "The mean", correctOption: "A", explanation: "Power = 1 − β, the probability of correctly rejecting a false null hypothesis.", orderIndex: 11 },

  // ── Quant: Regression ──
  { id: "frm-quantitative-analysis-regression-q09", topicId: "frm-quantitative-analysis-regression", text: "R-squared in a regression measures:", optionA: "The fraction of variance in Y explained by the model", optionB: "The slope", optionC: "The intercept", optionD: "The residual mean", correctOption: "A", explanation: "R² is the proportion of the dependent variable's variance explained by the regressors.", orderIndex: 8 },
  { id: "frm-quantitative-analysis-regression-q10", topicId: "frm-quantitative-analysis-regression", text: "Heteroskedasticity refers to:", optionA: "Non-constant variance of the error term", optionB: "Correlated regressors", optionC: "A perfect fit", optionD: "Zero mean errors", correctOption: "A", explanation: "Heteroskedasticity is error variance that changes across observations, biasing standard errors.", orderIndex: 9 },
  { id: "frm-quantitative-analysis-regression-q11", topicId: "frm-quantitative-analysis-regression", text: "Multicollinearity among independent variables tends to:", optionA: "Inflate coefficient standard errors", optionB: "Lower R²", optionC: "Remove all variance", optionD: "Guarantee causation", correctOption: "A", explanation: "High correlation among regressors makes individual coefficients imprecise (large standard errors).", orderIndex: 10 },
  { id: "frm-quantitative-analysis-regression-q12", topicId: "frm-quantitative-analysis-regression", text: "Adjusted R-squared differs from R-squared by:", optionA: "Penalizing the addition of explanatory variables", optionB: "Always being larger", optionC: "Ignoring the sample", optionD: "Measuring the slope", correctOption: "A", explanation: "Adjusted R² penalizes extra regressors, so it can fall when an added variable adds little explanatory power.", orderIndex: 11 },

  // ── Quant: Monte Carlo ──
  { id: "frm-quantitative-analysis-monte-carlo-q09", topicId: "frm-quantitative-analysis-monte-carlo", text: "Monte Carlo simulation estimates risk by:", optionA: "Generating many random scenarios from an assumed model", optionB: "Using only historical data", optionC: "Assuming normality always", optionD: "A single deterministic path", correctOption: "A", explanation: "Monte Carlo draws many random paths from a specified stochastic process to build an outcome distribution.", orderIndex: 8 },
  { id: "frm-quantitative-analysis-monte-carlo-q10", topicId: "frm-quantitative-analysis-monte-carlo", text: "The standard error of a Monte Carlo estimate falls in proportion to:", optionA: "1/√N (square root of simulations)", optionB: "1/N²", optionC: "N", optionD: "The mean", correctOption: "A", explanation: "Monte Carlo accuracy improves with the square root of the number of trials, so 4× trials halve the error.", orderIndex: 9 },
  { id: "frm-quantitative-analysis-monte-carlo-q11", topicId: "frm-quantitative-analysis-monte-carlo", text: "Variance-reduction techniques (e.g., antithetic variates) are used to:", optionA: "Improve accuracy for a given number of simulations", optionB: "Increase model risk", optionC: "Add bias", optionD: "Slow convergence", correctOption: "A", explanation: "Techniques like antithetic and control variates reduce sampling variance, improving efficiency.", orderIndex: 10 },
  { id: "frm-quantitative-analysis-monte-carlo-q12", topicId: "frm-quantitative-analysis-monte-carlo", text: "A key drawback of Monte Carlo VaR is:", optionA: "It is computationally intensive and model-dependent", optionB: "It cannot handle options", optionC: "It needs no assumptions", optionD: "It is always exact", correctOption: "A", explanation: "Monte Carlo is flexible but slow and only as good as the assumed model (model risk).", orderIndex: 11 },

  // ── Markets: Futures/Forwards & Hedging ──
  { id: "frm-financial-markets-futures-forwards-hedging-q09", topicId: "frm-financial-markets-futures-forwards-hedging", text: "Compared with forwards, futures contracts are:", optionA: "Standardized and exchange-traded with daily margining", optionB: "Always customized", optionC: "Free of margin", optionD: "Bilateral only", correctOption: "A", explanation: "Futures are standardized, cleared, and marked-to-market daily; forwards are customized OTC contracts.", orderIndex: 8 },
  { id: "frm-financial-markets-futures-forwards-hedging-q10", topicId: "frm-financial-markets-futures-forwards-hedging", text: "The minimum-variance hedge ratio equals:", optionA: "The correlation times the ratio of spot to futures volatility", optionB: "Always 1.0", optionC: "The risk-free rate", optionD: "The coupon", correctOption: "A", explanation: "h* = ρ × (σ_spot/σ_futures), minimizing the variance of the hedged position.", orderIndex: 9 },
  { id: "frm-financial-markets-futures-forwards-hedging-q11", topicId: "frm-financial-markets-futures-forwards-hedging", text: "Basis risk in a futures hedge arises because:", optionA: "Spot and futures prices may not move together perfectly", optionB: "Margin is posted", optionC: "Contracts expire", optionD: "Rates are zero", correctOption: "A", explanation: "Basis = spot − futures; its variability leaves residual risk in an otherwise hedged position.", orderIndex: 10 },
  { id: "frm-financial-markets-futures-forwards-hedging-q12", topicId: "frm-financial-markets-futures-forwards-hedging", text: "Contango describes a market where futures prices are:", optionA: "Above the current spot price", optionB: "Below spot", optionC: "Equal to spot", optionD: "Negative", correctOption: "A", explanation: "Contango is an upward-sloping futures curve (futures above spot); backwardation is the reverse.", orderIndex: 11 },

  // ── Markets: Options Pricing ──
  { id: "frm-financial-markets-options-pricing-q09", topicId: "frm-financial-markets-options-pricing", text: "Put-call parity relates the prices of a call, a put, the underlying, and:", optionA: "A risk-free bond (PV of the strike)", optionB: "A dividend index", optionC: "A currency forward", optionD: "A swap", correctOption: "A", explanation: "Put-call parity: C + PV(K) = P + S, linking the two options, the stock, and a bond.", orderIndex: 8 },
  { id: "frm-financial-markets-options-pricing-q10", topicId: "frm-financial-markets-options-pricing", text: "An increase in volatility raises the value of:", optionA: "Both calls and puts", optionB: "Only calls", optionC: "Only puts", optionD: "Neither", correctOption: "A", explanation: "Higher volatility increases the value of both calls and puts (positive vega).", orderIndex: 9 },
  { id: "frm-financial-markets-options-pricing-q11", topicId: "frm-financial-markets-options-pricing", text: "The delta of a deep in-the-money call approaches:", optionA: "1.0", optionB: "0.0", optionC: "−1.0", optionD: "0.5", correctOption: "A", explanation: "A deep ITM call behaves like the underlying, so its delta tends toward 1.0.", orderIndex: 10 },
  { id: "frm-financial-markets-options-pricing-q12", topicId: "frm-financial-markets-options-pricing", text: "Gamma is largest for options that are:", optionA: "At-the-money near expiration", optionB: "Deep in-the-money", optionC: "Deep out-of-the-money", optionD: "Long-dated", correctOption: "A", explanation: "Gamma peaks for at-the-money options close to expiry, where delta changes most rapidly.", orderIndex: 11 },

  // ── Markets: Swaps ──
  { id: "frm-financial-markets-swaps-q09", topicId: "frm-financial-markets-swaps", text: "In a plain-vanilla interest-rate swap, the parties exchange:", optionA: "Fixed for floating interest payments", optionB: "Principal amounts only", optionC: "Equity for bonds", optionD: "Currencies", correctOption: "A", explanation: "A vanilla IRS swaps fixed-rate for floating-rate cash flows on a notional principal.", orderIndex: 8 },
  { id: "frm-financial-markets-swaps-q10", topicId: "frm-financial-markets-swaps", text: "At inception, the value of a par interest-rate swap is approximately:", optionA: "Zero", optionB: "The notional", optionC: "The fixed coupon", optionD: "Negative", correctOption: "A", explanation: "A par swap is priced so the fixed and floating legs have equal value, giving zero initial value.", orderIndex: 9 },
  { id: "frm-financial-markets-swaps-q11", topicId: "frm-financial-markets-swaps", text: "A currency swap differs from an interest-rate swap by exchanging:", optionA: "Principal and interest in two different currencies", optionB: "Only fixed rates", optionC: "Equity returns", optionD: "Nothing", correctOption: "A", explanation: "Currency swaps exchange principal and interest in two currencies, typically including principal exchange.", orderIndex: 10 },
  { id: "frm-financial-markets-swaps-q12", topicId: "frm-financial-markets-swaps", text: "Swap counterparty credit exposure is largest:", optionA: "During the life of the swap as rates move (mid-life peak)", optionB: "Only at inception", optionC: "Never", optionD: "Only on the notional at maturity", correctOption: "A", explanation: "Expected exposure on an IRS typically peaks mid-life, balancing rate diffusion against remaining payments.", orderIndex: 11 },

  // ── Markets: Fixed-Income Products ──
  { id: "frm-financial-markets-fixed-income-products-q09", topicId: "frm-financial-markets-fixed-income-products", text: "The price of a bond and its yield are:", optionA: "Inversely related", optionB: "Directly related", optionC: "Unrelated", optionD: "Always equal", correctOption: "A", explanation: "Bond prices fall as yields rise and vice versa — the fundamental inverse relationship.", orderIndex: 8 },
  { id: "frm-financial-markets-fixed-income-products-q10", topicId: "frm-financial-markets-fixed-income-products", text: "A callable bond is least attractive to investors when rates:", optionA: "Fall (issuer likely to call)", optionB: "Rise", optionC: "Stay flat", optionD: "Are negative", correctOption: "A", explanation: "Falling rates make the issuer's call option valuable, capping the bondholder's upside.", orderIndex: 9 },
  { id: "frm-financial-markets-fixed-income-products-q11", topicId: "frm-financial-markets-fixed-income-products", text: "The credit spread on a corporate bond compensates for:", optionA: "Default and liquidity risk over Treasuries", optionB: "Inflation only", optionC: "Currency risk", optionD: "Nothing", correctOption: "A", explanation: "The spread above the risk-free rate compensates for default risk, recovery uncertainty, and liquidity.", orderIndex: 10 },
  { id: "frm-financial-markets-fixed-income-products-q12", topicId: "frm-financial-markets-fixed-income-products", text: "A floating-rate note has low interest-rate duration because its coupon:", optionA: "Resets periodically with market rates", optionB: "Is fixed for life", optionC: "Never pays", optionD: "Equals the principal", correctOption: "A", explanation: "Because the coupon resets to current rates, an FRN's price is relatively insensitive to rate changes.", orderIndex: 11 },

  // ── Markets: Credit Products ──
  { id: "frm-financial-markets-credit-products-q09", topicId: "frm-financial-markets-credit-products", text: "A credit default swap (CDS) buyer:", optionA: "Pays a premium for protection against a reference default", optionB: "Receives a premium", optionC: "Owns the bond", optionD: "Takes no risk", correctOption: "A", explanation: "The protection buyer pays periodic premiums and receives compensation if a credit event occurs.", orderIndex: 8 },
  { id: "frm-financial-markets-credit-products-q10", topicId: "frm-financial-markets-credit-products", text: "Widening CDS spreads indicate:", optionA: "Deteriorating perceived credit quality", optionB: "Improving credit", optionC: "Lower default risk", optionD: "No change", correctOption: "A", explanation: "Higher CDS spreads mean the market demands more for default protection, signaling worse credit.", orderIndex: 9 },
  { id: "frm-financial-markets-credit-products-q11", topicId: "frm-financial-markets-credit-products", text: "In a collateralized debt obligation (CDO), the equity (first-loss) tranche:", optionA: "Absorbs initial losses but offers the highest yield", optionB: "Is the safest", optionC: "Has no risk", optionD: "Is senior", correctOption: "A", explanation: "The equity tranche takes the first losses in exchange for the highest potential return.", orderIndex: 10 },
  { id: "frm-financial-markets-credit-products-q12", topicId: "frm-financial-markets-credit-products", text: "The recovery rate in credit modeling is:", optionA: "The fraction of exposure recovered after default", optionB: "The default probability", optionC: "The coupon", optionD: "The spread", correctOption: "A", explanation: "Recovery rate = 1 − loss given default; it scales the loss when a default occurs.", orderIndex: 11 },

  // ── Valuation: Value at Risk ──
  { id: "frm-valuation-risk-models-value-at-risk-q09", topicId: "frm-valuation-risk-models-value-at-risk", text: "A 99% one-day VaR of $5m means:", optionA: "Losses should exceed $5m on ~1% of days", optionB: "Losses never exceed $5m", optionC: "Average loss is $5m", optionD: "Gains are $5m", correctOption: "A", explanation: "VaR is a quantile of the loss distribution; here losses exceed $5m about 1% of the time.", orderIndex: 8 },
  { id: "frm-valuation-risk-models-value-at-risk-q10", topicId: "frm-valuation-risk-models-value-at-risk", text: "VaR is criticized for not being a coherent risk measure because it lacks:", optionA: "Subadditivity in general", optionB: "Monotonicity", optionC: "A confidence level", optionD: "A time horizon", correctOption: "A", explanation: "VaR can violate subadditivity (diversification), so it is not generally coherent — expected shortfall is.", orderIndex: 9 },
  { id: "frm-valuation-risk-models-value-at-risk-q11", topicId: "frm-valuation-risk-models-value-at-risk", text: "Scaling one-day VaR to a 10-day horizon (i.i.d. normal) uses a factor of:", optionA: "√10", optionB: "10", optionC: "100", optionD: "1", correctOption: "A", explanation: "Under the square-root-of-time rule, multiply by √T, so √10 for ten days.", orderIndex: 10 },
  { id: "frm-valuation-risk-models-value-at-risk-q12", topicId: "frm-valuation-risk-models-value-at-risk", text: "The main weakness of VaR relative to expected shortfall is that VaR:", optionA: "Ignores the size of losses beyond the threshold", optionB: "Cannot be computed", optionC: "Overstates risk", optionD: "Has no horizon", correctOption: "A", explanation: "VaR says nothing about tail severity past the cutoff, which expected shortfall (CVaR) captures.", orderIndex: 11 },

  // ── Valuation: Bond Valuation ──
  { id: "frm-valuation-risk-models-bond-valuation-q09", topicId: "frm-valuation-risk-models-bond-valuation", text: "Modified duration approximates the percentage price change for a:", optionA: "1% (100bp) change in yield", optionB: "1% change in coupon", optionC: "Change in rating", optionD: "Change in maturity", correctOption: "A", explanation: "Modified duration estimates the percent price change per unit (100bp) change in yield.", orderIndex: 8 },
  { id: "frm-valuation-risk-models-bond-valuation-q10", topicId: "frm-valuation-risk-models-bond-valuation", text: "Convexity adjustment improves duration estimates because price-yield is:", optionA: "Curved, not linear", optionB: "Perfectly linear", optionC: "Flat", optionD: "Vertical", correctOption: "A", explanation: "Duration is a linear approximation; convexity corrects for the curvature of the price-yield relationship.", orderIndex: 9 },
  { id: "frm-valuation-risk-models-bond-valuation-q11", topicId: "frm-valuation-risk-models-bond-valuation", text: "A bond's DV01 (dollar value of a basis point) measures:", optionA: "Price change for a 1bp yield move", optionB: "The coupon", optionC: "The yield", optionD: "The maturity", correctOption: "A", explanation: "DV01 is the dollar change in price for a one-basis-point change in yield, a key hedging measure.", orderIndex: 10 },
  { id: "frm-valuation-risk-models-bond-valuation-q12", topicId: "frm-valuation-risk-models-bond-valuation", text: "Higher convexity is beneficial to a bondholder because it:", optionA: "Gains more when rates fall and loses less when they rise", optionB: "Reduces coupons", optionC: "Increases default risk", optionD: "Lowers price always", correctOption: "A", explanation: "Positive convexity produces asymmetric, favorable price responses to yield changes.", orderIndex: 11 },

  // ── Valuation: Option Valuation ──
  { id: "frm-valuation-risk-models-option-valuation-q09", topicId: "frm-valuation-risk-models-option-valuation", text: "The Black-Scholes-Merton model assumes the underlying follows:", optionA: "Geometric Brownian motion with constant volatility", optionB: "A jump process only", optionC: "A linear trend", optionD: "No randomness", correctOption: "A", explanation: "BSM assumes lognormal prices (GBM) with constant volatility and continuous trading.", orderIndex: 8 },
  { id: "frm-valuation-risk-models-option-valuation-q10", topicId: "frm-valuation-risk-models-option-valuation", text: "The binomial option model values an option by:", optionA: "Risk-neutral discounting over a price tree", optionB: "Historical averaging", optionC: "Ignoring volatility", optionD: "Using only the strike", correctOption: "A", explanation: "The binomial tree uses risk-neutral probabilities and backward induction to value the option.", orderIndex: 9 },
  { id: "frm-valuation-risk-models-option-valuation-q11", topicId: "frm-valuation-risk-models-option-valuation", text: "Implied volatility is the volatility that:", optionA: "Makes the model price equal the market price", optionB: "Equals historical volatility", optionC: "Is always zero", optionD: "Ignores the option price", correctOption: "A", explanation: "Implied volatility is backed out of observed option prices via the pricing model.", orderIndex: 10 },
  { id: "frm-valuation-risk-models-option-valuation-q12", topicId: "frm-valuation-risk-models-option-valuation", text: "American options can be worth more than European options because they allow:", optionA: "Early exercise", optionB: "Lower strikes", optionC: "No premium", optionD: "Infinite maturity", correctOption: "A", explanation: "The early-exercise right gives American options value at least equal to otherwise identical Europeans.", orderIndex: 11 },

  // ── Valuation: Stress Testing ──
  { id: "frm-valuation-risk-models-stress-testing-q09", topicId: "frm-valuation-risk-models-stress-testing", text: "Stress testing complements VaR by examining:", optionA: "Severe but plausible scenarios beyond normal conditions", optionB: "Only average outcomes", optionC: "Daily P&L only", optionD: "Marketing data", correctOption: "A", explanation: "Stress tests assess losses under extreme scenarios that standard VaR may understate.", orderIndex: 8 },
  { id: "frm-valuation-risk-models-stress-testing-q10", topicId: "frm-valuation-risk-models-stress-testing", text: "A historical scenario stress test uses:", optionA: "Actual past crisis episodes (e.g., 2008)", optionB: "Hypothetical only", optionC: "Random noise", optionD: "Average returns", correctOption: "A", explanation: "Historical scenarios replay real stress events to gauge portfolio impact.", orderIndex: 9 },
  { id: "frm-valuation-risk-models-stress-testing-q11", topicId: "frm-valuation-risk-models-stress-testing", text: "Reverse stress testing starts from:", optionA: "A defined failure outcome and works back to scenarios that cause it", optionB: "The base case", optionC: "Average returns", optionD: "A single asset", correctOption: "A", explanation: "Reverse stress testing identifies the scenarios that would render the firm unviable.", orderIndex: 10 },
  { id: "frm-valuation-risk-models-stress-testing-q12", topicId: "frm-valuation-risk-models-stress-testing", text: "A limitation of stress testing is that it:", optionA: "Depends on the scenarios chosen and may miss unforeseen risks", optionB: "Always predicts the future", optionC: "Requires no judgment", optionD: "Replaces all risk models", correctOption: "A", explanation: "Results are only as good as the imagined scenarios; novel shocks can be overlooked.", orderIndex: 11 },

  // ── Valuation: Model Risk ──
  { id: "frm-valuation-risk-models-model-risk-q09", topicId: "frm-valuation-risk-models-model-risk", text: "Model risk arises primarily from:", optionA: "Incorrect assumptions, errors, or misuse of a model", optionB: "Market moves only", optionC: "Counterparty default", optionD: "Liquidity", correctOption: "A", explanation: "Model risk is loss from flawed model specification, implementation errors, or inappropriate application.", orderIndex: 8 },
  { id: "frm-valuation-risk-models-model-risk-q10", topicId: "frm-valuation-risk-models-model-risk", text: "Model validation should be performed by:", optionA: "An independent team separate from the developers", optionB: "The model developers alone", optionC: "Sales", optionD: "No one", correctOption: "A", explanation: "Independent validation provides effective challenge and reduces conflicts of interest.", orderIndex: 9 },
  { id: "frm-valuation-risk-models-model-risk-q11", topicId: "frm-valuation-risk-models-model-risk", text: "Calibrating a model to too few data points raises the risk of:", optionA: "Overfitting", optionB: "Underfitting only", optionC: "No risk", optionD: "Lower model risk", correctOption: "A", explanation: "Overfitting captures noise rather than signal, producing poor out-of-sample performance.", orderIndex: 10 },
  { id: "frm-valuation-risk-models-model-risk-q12", topicId: "frm-valuation-risk-models-model-risk", text: "A common control for model risk is:", optionA: "Benchmarking against alternative models and ongoing monitoring", optionB: "Hiding the model", optionC: "Removing documentation", optionD: "Ignoring outputs", correctOption: "A", explanation: "Comparing outputs to alternative approaches and monitoring performance helps catch model failures.", orderIndex: 11 },

  // ── Market Risk: VaR Methods & Backtesting ──
  { id: "frm-market-risk-var-methods-backtesting-q09", topicId: "frm-market-risk-var-methods-backtesting", text: "Backtesting compares VaR forecasts to:", optionA: "Actual realized P&L exceptions", optionB: "Marketing forecasts", optionC: "Accounting accruals", optionD: "Dividend yields", correctOption: "A", explanation: "Backtesting counts how often losses exceed VaR to check the model's accuracy.", orderIndex: 8 },
  { id: "frm-market-risk-var-methods-backtesting-q10", topicId: "frm-market-risk-var-methods-backtesting", text: "Under Basel's traffic-light approach, too many VaR exceptions place a bank in the:", optionA: "Red zone (higher multiplier/penalty)", optionB: "Green zone", optionC: "Blue zone", optionD: "No zone", correctOption: "A", explanation: "Excessive exceptions move a bank into the red zone, raising its capital multiplier.", orderIndex: 9 },
  { id: "frm-market-risk-var-methods-backtesting-q11", topicId: "frm-market-risk-var-methods-backtesting", text: "Kupiec's POF (proportion of failures) test evaluates whether the:", optionA: "Number of exceptions matches the VaR confidence level", optionB: "Mean return is zero", optionC: "Variance is constant", optionD: "Spread is wide", correctOption: "A", explanation: "The Kupiec test checks if the observed exception rate is statistically consistent with the chosen quantile.", orderIndex: 10 },
  { id: "frm-market-risk-var-methods-backtesting-q12", topicId: "frm-market-risk-var-methods-backtesting", text: "Conditional coverage tests (e.g., Christoffersen) add a check for:", optionA: "Independence/clustering of exceptions over time", optionB: "Correct mean", optionC: "Skewness", optionD: "Liquidity", correctOption: "A", explanation: "Beyond the count, they test whether exceptions cluster, indicating the model misses changing volatility.", orderIndex: 11 },

  // ── Market Risk: Parametric VaR ──
  { id: "frm-market-risk-parametric-var-q09", topicId: "frm-market-risk-parametric-var", text: "Parametric (delta-normal) VaR assumes returns are:", optionA: "Normally distributed", optionB: "Fat-tailed", optionC: "Uniform", optionD: "Bimodal", correctOption: "A", explanation: "The delta-normal method assumes normal returns, enabling a closed-form VaR from volatility.", orderIndex: 8 },
  { id: "frm-market-risk-parametric-var-q10", topicId: "frm-market-risk-parametric-var", text: "For a 99% confidence level, parametric VaR uses a z-multiplier of approximately:", optionA: "2.33", optionB: "1.65", optionC: "1.00", optionD: "3.00", correctOption: "A", explanation: "The 99% one-tailed normal quantile is about 2.33 standard deviations.", orderIndex: 9 },
  { id: "frm-market-risk-parametric-var-q11", topicId: "frm-market-risk-parametric-var", text: "A weakness of delta-normal VaR for options portfolios is that it:", optionA: "Poorly captures non-linear (gamma) payoffs", optionB: "Is too slow", optionC: "Needs no volatility", optionD: "Ignores the mean only", correctOption: "A", explanation: "The linear delta approximation misrepresents the curved payoffs of options.", orderIndex: 10 },
  { id: "frm-market-risk-parametric-var-q12", topicId: "frm-market-risk-parametric-var", text: "Parametric VaR for a portfolio requires estimating the:", optionA: "Variance-covariance matrix of risk factors", optionB: "Coupon schedule", optionC: "Dividend dates", optionD: "Credit ratings", correctOption: "A", explanation: "Portfolio delta-normal VaR uses the covariance matrix to aggregate factor risks.", orderIndex: 11 },

  // ── Market Risk: Historical Simulation ──
  { id: "frm-market-risk-historical-simulation-q09", topicId: "frm-market-risk-historical-simulation", text: "Historical simulation VaR is computed by:", optionA: "Applying past return scenarios to the current portfolio", optionB: "Assuming normality", optionC: "Drawing from a model", optionD: "Using only the latest return", correctOption: "A", explanation: "It revalues today's portfolio under each historical return scenario to form a P&L distribution.", orderIndex: 8 },
  { id: "frm-market-risk-historical-simulation-q10", topicId: "frm-market-risk-historical-simulation", text: "A key advantage of historical simulation is that it:", optionA: "Makes no distributional assumption and captures fat tails in the data", optionB: "Requires no data", optionC: "Is always forward-looking", optionD: "Ignores correlations", correctOption: "A", explanation: "By using actual history it naturally reflects observed tails and correlations without assuming normality.", orderIndex: 9 },
  { id: "frm-market-risk-historical-simulation-q11", topicId: "frm-market-risk-historical-simulation", text: "A drawback of historical simulation is that it:", optionA: "Assumes the future resembles the chosen historical window", optionB: "Requires a covariance matrix", optionC: "Cannot handle options", optionD: "Has no quantile", correctOption: "A", explanation: "Results depend on the look-back period and may miss risks absent from that window.", orderIndex: 10 },
  { id: "frm-market-risk-historical-simulation-q12", topicId: "frm-market-risk-historical-simulation", text: "Age-weighting historical simulation gives more weight to:", optionA: "More recent observations", optionB: "Older observations", optionC: "All equally", optionD: "The mean", correctOption: "A", explanation: "Age-weighting (BRW) emphasizes recent data so the estimate adapts faster to current conditions.", orderIndex: 11 },

  // ── Market Risk: Expected Shortfall ──
  { id: "frm-market-risk-expected-shortfall-q09", topicId: "frm-market-risk-expected-shortfall", text: "Expected shortfall (ES) is the:", optionA: "Average loss given the loss exceeds VaR", optionB: "Most likely loss", optionC: "Smallest loss", optionD: "Mean return", correctOption: "A", explanation: "ES (CVaR) averages the losses in the tail beyond the VaR threshold.", orderIndex: 8 },
  { id: "frm-market-risk-expected-shortfall-q10", topicId: "frm-market-risk-expected-shortfall", text: "Unlike VaR, expected shortfall is always:", optionA: "Subadditive (a coherent risk measure)", optionB: "Larger than the notional", optionC: "Negative", optionD: "Equal to VaR", correctOption: "A", explanation: "ES satisfies subadditivity and the other coherence axioms that VaR can violate.", orderIndex: 9 },
  { id: "frm-market-risk-expected-shortfall-q11", topicId: "frm-market-risk-expected-shortfall", text: "Basel's FRTB framework replaced VaR with expected shortfall to better capture:", optionA: "Tail risk", optionB: "Liquidity only", optionC: "Coupon income", optionD: "Operational loss", correctOption: "A", explanation: "FRTB adopted ES at 97.5% to more fully reflect tail risk in market-risk capital.", orderIndex: 10 },
  { id: "frm-market-risk-expected-shortfall-q12", topicId: "frm-market-risk-expected-shortfall", text: "Relative to a 99% VaR, the 97.5% ES is designed to be:", optionA: "Comparable in stringency while capturing tail severity", optionB: "Far smaller always", optionC: "Unrelated", optionD: "Always zero", correctOption: "A", explanation: "Basel chose 97.5% ES to roughly match 99% VaR for normal distributions while adding tail sensitivity.", orderIndex: 11 },

  // ── Market Risk: Regulatory Capital ──
  { id: "frm-market-risk-regulatory-capital-q09", topicId: "frm-market-risk-regulatory-capital", text: "FRTB distinguishes capital charges using the:", optionA: "Standardized and internal-models approaches", optionB: "Tax and audit approaches", optionC: "Cash and accrual methods", optionD: "Long and short methods", correctOption: "A", explanation: "FRTB offers a sensitivities-based standardized approach and an internal models approach (IMA).", orderIndex: 8 },
  { id: "frm-market-risk-regulatory-capital-q10", topicId: "frm-market-risk-regulatory-capital", text: "A central FRTB concept is the boundary between the:", optionA: "Trading book and banking book", optionB: "Front and back office", optionC: "Equity and debt", optionD: "Retail and wholesale", correctOption: "A", explanation: "FRTB tightened the trading/banking book boundary to limit regulatory arbitrage.", orderIndex: 9 },
  { id: "frm-market-risk-regulatory-capital-q11", topicId: "frm-market-risk-regulatory-capital", text: "Under the IMA, risk factors that lack sufficient market data are treated as:", optionA: "Non-modellable risk factors (NMRFs) with add-on charges", optionB: "Risk-free", optionC: "Zero capital", optionD: "Banking-book items", correctOption: "A", explanation: "NMRFs cannot be modeled with enough data and attract additional stressed capital add-ons.", orderIndex: 10 },
  { id: "frm-market-risk-regulatory-capital-q12", topicId: "frm-market-risk-regulatory-capital", text: "Market-risk capital aims to ensure banks can absorb losses during:", optionA: "Periods of significant market stress", optionB: "Normal days only", optionC: "Marketing campaigns", optionD: "Audits", correctOption: "A", explanation: "Capital requirements (including a stressed ES component) buffer losses in stressed markets.", orderIndex: 11 },

  // ── Credit Risk: Default Probability & Credit VaR ──
  { id: "frm-credit-risk-default-probability-credit-var-q09", topicId: "frm-credit-risk-default-probability-credit-var", text: "Expected loss (EL) equals:", optionA: "PD × LGD × EAD", optionB: "PD + LGD + EAD", optionC: "PD − LGD", optionD: "EAD / PD", correctOption: "A", explanation: "Expected loss is the product of probability of default, loss given default, and exposure at default.", orderIndex: 8 },
  { id: "frm-credit-risk-default-probability-credit-var-q10", topicId: "frm-credit-risk-default-probability-credit-var", text: "Credit VaR represents:", optionA: "Unexpected loss beyond expected loss at a confidence level", optionB: "Expected loss only", optionC: "The coupon", optionD: "The spread", correctOption: "A", explanation: "Credit VaR is the loss quantile in excess of expected loss, covered by economic capital.", orderIndex: 9 },
  { id: "frm-credit-risk-default-probability-credit-var-q11", topicId: "frm-credit-risk-default-probability-credit-var", text: "Loss given default (LGD) equals:", optionA: "1 minus the recovery rate", optionB: "The default probability", optionC: "The exposure", optionD: "The spread", correctOption: "A", explanation: "LGD is the fraction of exposure lost after recoveries, i.e., 1 − recovery rate.", orderIndex: 10 },
  { id: "frm-credit-risk-default-probability-credit-var-q12", topicId: "frm-credit-risk-default-probability-credit-var", text: "Default correlation among borrowers increases a portfolio's:", optionA: "Unexpected loss / tail risk", optionB: "Expected loss only", optionC: "Recovery rate", optionD: "Coupon", correctOption: "A", explanation: "Higher default correlation fattens the loss tail, raising unexpected loss and required capital.", orderIndex: 11 },

  // ── Credit Risk: Credit Derivatives ──
  { id: "frm-credit-risk-credit-derivatives-q09", topicId: "frm-credit-risk-credit-derivatives", text: "A single-name CDS transfers the credit risk of:", optionA: "One reference entity", optionB: "An entire index", optionC: "The whole market", optionD: "A currency", correctOption: "A", explanation: "Single-name CDS reference one issuer; index CDS (e.g., CDX, iTraxx) cover portfolios.", orderIndex: 8 },
  { id: "frm-credit-risk-credit-derivatives-q10", topicId: "frm-credit-risk-credit-derivatives", text: "A credit event triggering a CDS typically includes:", optionA: "Bankruptcy, failure to pay, or restructuring", optionB: "A dividend cut", optionC: "A stock split", optionD: "An audit", correctOption: "A", explanation: "ISDA-defined credit events include bankruptcy, failure to pay, and (sometimes) restructuring.", orderIndex: 9 },
  { id: "frm-credit-risk-credit-derivatives-q11", topicId: "frm-credit-risk-credit-derivatives", text: "A total return swap transfers:", optionA: "Both market and credit risk of the reference asset", optionB: "Only interest-rate risk", optionC: "No risk", optionD: "Only currency risk", correctOption: "A", explanation: "A TRS passes the total return (price plus income), transferring market and credit exposure.", orderIndex: 10 },
  { id: "frm-credit-risk-credit-derivatives-q12", topicId: "frm-credit-risk-credit-derivatives", text: "Buying CDS protection while holding the bond creates a position that is:", optionA: "Hedged against default (a negative-basis trade if cheap)", optionB: "Doubly exposed to default", optionC: "Equity-like", optionD: "Risk-free of rates", correctOption: "A", explanation: "Long bond plus long CDS hedges default risk; when CDS is cheap relative to the spread it is a negative-basis trade.", orderIndex: 11 },

  // ── Credit Risk: Securitisation ──
  { id: "frm-credit-risk-securitisation-q09", topicId: "frm-credit-risk-securitisation", text: "Securitization pools assets and issues:", optionA: "Tranched securities with different risk/return", optionB: "A single equity share", optionC: "Government bonds", optionD: "Currency forwards", correctOption: "A", explanation: "Cash flows from the pool are sliced into tranches with differing seniority and risk.", orderIndex: 8 },
  { id: "frm-credit-risk-securitisation-q10", topicId: "frm-credit-risk-securitisation", text: "Credit enhancement via subordination means senior tranches are protected by:", optionA: "Junior tranches absorbing first losses", optionB: "Government guarantees always", optionC: "Higher coupons", optionD: "Longer maturities", correctOption: "A", explanation: "Subordinated tranches take initial losses, enhancing the credit quality of senior tranches.", orderIndex: 9 },
  { id: "frm-credit-risk-securitisation-q11", topicId: "frm-credit-risk-securitisation", text: "The 2007–09 crisis exposed securitization weaknesses such as:", optionA: "Poor underwriting and over-reliance on ratings", optionB: "Too much transparency", optionC: "Excess capital", optionD: "Low leverage", correctOption: "A", explanation: "Weak originator incentives, opaque structures, and rating over-reliance amplified losses.", orderIndex: 10 },
  { id: "frm-credit-risk-securitisation-q12", topicId: "frm-credit-risk-securitisation", text: "Risk retention ('skin in the game') rules require originators to:", optionA: "Hold a portion of the securitized exposure", optionB: "Sell everything", optionC: "Guarantee returns", optionD: "Avoid disclosure", correctOption: "A", explanation: "Retention aligns originator incentives by keeping them exposed to the pool's performance.", orderIndex: 11 },

  // ── Credit Risk: Counterparty Credit Risk ──
  { id: "frm-credit-risk-counterparty-credit-risk-q09", topicId: "frm-credit-risk-counterparty-credit-risk", text: "Counterparty credit risk in derivatives is the risk that:", optionA: "The counterparty defaults before settling an in-the-money contract", optionB: "Rates fall", optionC: "Equity rises", optionD: "Inflation increases", correctOption: "A", explanation: "CCR is the risk a counterparty defaults when the contract has positive value to the bank.", orderIndex: 8 },
  { id: "frm-credit-risk-counterparty-credit-risk-q10", topicId: "frm-credit-risk-counterparty-credit-risk", text: "Credit valuation adjustment (CVA) represents:", optionA: "The market value of counterparty default risk", optionB: "The coupon", optionC: "The funding cost", optionD: "The notional", correctOption: "A", explanation: "CVA is the price adjustment for expected loss from counterparty default over the trade's life.", orderIndex: 9 },
  { id: "frm-credit-risk-counterparty-credit-risk-q11", topicId: "frm-credit-risk-counterparty-credit-risk", text: "Wrong-way risk occurs when exposure to a counterparty:", optionA: "Rises as the counterparty's credit quality falls", optionB: "Falls as credit improves", optionC: "Is constant", optionD: "Is zero", correctOption: "A", explanation: "Wrong-way risk is adverse dependence: exposure increases just as the counterparty becomes more likely to default.", orderIndex: 10 },
  { id: "frm-credit-risk-counterparty-credit-risk-q12", topicId: "frm-credit-risk-counterparty-credit-risk", text: "Netting agreements reduce counterparty exposure by:", optionA: "Offsetting positive and negative mark-to-market across trades", optionB: "Adding exposures", optionC: "Removing collateral", optionD: "Increasing notional", correctOption: "A", explanation: "Close-out netting nets offsetting exposures, lowering the amount at risk on default.", orderIndex: 11 },

  // ── Credit Risk: Regulatory Capital ──
  { id: "frm-credit-risk-regulatory-capital-q09", topicId: "frm-credit-risk-regulatory-capital", text: "Basel's credit-risk capital can be computed using the standardized or:", optionA: "Internal ratings-based (IRB) approach", optionB: "Marketing approach", optionC: "Cash approach", optionD: "Audit approach", correctOption: "A", explanation: "Banks may use the standardized approach or, with approval, the foundation/advanced IRB approaches.", orderIndex: 8 },
  { id: "frm-credit-risk-regulatory-capital-q10", topicId: "frm-credit-risk-regulatory-capital", text: "Under advanced IRB, banks estimate their own:", optionA: "PD, LGD, and EAD", optionB: "Tax rates", optionC: "Dividend policy", optionD: "Marketing spend", correctOption: "A", explanation: "Advanced IRB lets qualifying banks model PD, LGD, and EAD inputs to the capital formula.", orderIndex: 9 },
  { id: "frm-credit-risk-regulatory-capital-q11", topicId: "frm-credit-risk-regulatory-capital", text: "Regulatory credit capital is meant to cover:", optionA: "Unexpected loss (with provisions covering expected loss)", optionB: "Expected loss only", optionC: "Coupons", optionD: "Operating costs", correctOption: "A", explanation: "Capital absorbs unexpected losses, while expected loss is covered by provisions/pricing.", orderIndex: 10 },
  { id: "frm-credit-risk-regulatory-capital-q12", topicId: "frm-credit-risk-regulatory-capital", text: "The Basel output floor limits how far IRB capital can fall below the:", optionA: "Standardized-approach capital", optionB: "Market value", optionC: "Notional", optionD: "Coupon", correctOption: "A", explanation: "The output floor caps the benefit of internal models relative to the standardized approach.", orderIndex: 11 },

  // ── Operational Risk: Basel Accords & RAROC ──
  { id: "frm-operational-risk-basel-accords-raroc-q09", topicId: "frm-operational-risk-basel-accords-raroc", text: "RAROC is best described as:", optionA: "Risk-adjusted return on capital", optionB: "Return on assets", optionC: "A liquidity ratio", optionD: "A coupon rate", correctOption: "A", explanation: "RAROC divides risk-adjusted return by economic capital to compare activities on a risk basis.", orderIndex: 8 },
  { id: "frm-operational-risk-basel-accords-raroc-q10", topicId: "frm-operational-risk-basel-accords-raroc", text: "Basel's current operational-risk capital uses the:", optionA: "Standardized Approach (SMA) based on a business indicator", optionB: "Internal VaR only", optionC: "Market-risk model", optionD: "No methodology", correctOption: "A", explanation: "Basel III replaced earlier approaches with the Standardized Measurement Approach driven by a business indicator and loss history.", orderIndex: 9 },
  { id: "frm-operational-risk-basel-accords-raroc-q11", topicId: "frm-operational-risk-basel-accords-raroc", text: "A project is value-adding under RAROC when its RAROC exceeds the:", optionA: "Hurdle rate (cost of equity capital)", optionB: "Risk-free rate only", optionC: "Coupon", optionD: "Inflation rate", correctOption: "A", explanation: "If risk-adjusted return on capital beats the firm's hurdle (cost of capital), the activity creates value.", orderIndex: 10 },
  { id: "frm-operational-risk-basel-accords-raroc-q12", topicId: "frm-operational-risk-basel-accords-raroc", text: "Economic capital differs from regulatory capital in that it is:", optionA: "The bank's own estimate of capital needed for its risks", optionB: "Set only by regulators", optionC: "Always larger", optionD: "Ignored internally", correctOption: "A", explanation: "Economic capital is the institution's internal assessment, which may differ from the regulatory minimum.", orderIndex: 11 },

  // ── Operational Risk: Loss Distribution ──
  { id: "frm-operational-risk-loss-distribution-q09", topicId: "frm-operational-risk-loss-distribution", text: "The loss distribution approach (LDA) models operational losses by combining:", optionA: "Frequency and severity distributions", optionB: "Only frequency", optionC: "Only severity", optionD: "Market returns", correctOption: "A", explanation: "LDA convolves a frequency distribution (e.g., Poisson) with a severity distribution to get aggregate loss.", orderIndex: 8 },
  { id: "frm-operational-risk-loss-distribution-q10", topicId: "frm-operational-risk-loss-distribution", text: "Operational loss frequency is commonly modeled with a:", optionA: "Poisson distribution", optionB: "Normal distribution", optionC: "Uniform distribution", optionD: "Binomial of returns", correctOption: "A", explanation: "The number of loss events per period is often modeled as Poisson.", orderIndex: 9 },
  { id: "frm-operational-risk-loss-distribution-q11", topicId: "frm-operational-risk-loss-distribution", text: "Operational loss severity distributions are typically:", optionA: "Heavy-tailed (e.g., lognormal, Pareto)", optionB: "Thin-tailed normal", optionC: "Symmetric", optionD: "Bounded above", correctOption: "A", explanation: "Severity is fat-tailed, capturing rare but very large losses; lognormal or Pareto fits are common.", orderIndex: 10 },
  { id: "frm-operational-risk-loss-distribution-q12", topicId: "frm-operational-risk-loss-distribution", text: "Operational risk capital under LDA is often the:", optionA: "99.9% quantile of the aggregate annual loss distribution", optionB: "Mean loss", optionC: "Median", optionD: "Minimum loss", correctOption: "A", explanation: "Regulatory op-risk capital targeted a 99.9% one-year quantile of aggregate losses.", orderIndex: 11 },

  // ── Operational Risk: Key Risk Indicators ──
  { id: "frm-operational-risk-key-risk-indicators-q09", topicId: "frm-operational-risk-key-risk-indicators", text: "Key risk indicators (KRIs) are:", optionA: "Leading metrics that signal rising operational risk", optionB: "Lagging accounting figures", optionC: "Market prices", optionD: "Coupon rates", correctOption: "A", explanation: "KRIs are forward-looking metrics (e.g., failed trades, staff turnover) that warn of increasing risk.", orderIndex: 8 },
  { id: "frm-operational-risk-key-risk-indicators-q10", topicId: "frm-operational-risk-key-risk-indicators", text: "An effective KRI should be:", optionA: "Measurable, relevant, and have defined thresholds", optionB: "Vague and unmeasured", optionC: "Unrelated to risk", optionD: "Secret", correctOption: "A", explanation: "Good KRIs are quantifiable, tied to a real risk, and trigger action at set thresholds.", orderIndex: 9 },
  { id: "frm-operational-risk-key-risk-indicators-q11", topicId: "frm-operational-risk-key-risk-indicators", text: "A risk and control self-assessment (RCSA) is used to:", optionA: "Identify risks and evaluate control effectiveness", optionB: "Price options", optionC: "Set coupons", optionD: "Measure VaR", correctOption: "A", explanation: "RCSA is a bottom-up process where units assess their risks and the strength of mitigating controls.", orderIndex: 10 },
  { id: "frm-operational-risk-key-risk-indicators-q12", topicId: "frm-operational-risk-key-risk-indicators", text: "Combining internal loss data with external data and scenarios helps address:", optionA: "Gaps from rare, unseen tail events", optionB: "Market risk", optionC: "Interest-rate risk", optionD: "Currency risk", correctOption: "A", explanation: "External data and scenario analysis supplement limited internal history on rare large losses.", orderIndex: 11 },

  // ── Operational Risk: Cyber & Technology Risk ──
  { id: "frm-operational-risk-cyber-technology-risk-q09", topicId: "frm-operational-risk-cyber-technology-risk", text: "Cyber risk is a subset of:", optionA: "Operational risk", optionB: "Market risk", optionC: "Credit risk", optionD: "Liquidity risk", correctOption: "A", explanation: "Cyber/technology failures and attacks fall under operational risk.", orderIndex: 8 },
  { id: "frm-operational-risk-cyber-technology-risk-q10", topicId: "frm-operational-risk-cyber-technology-risk", text: "The CIA triad in information security stands for:", optionA: "Confidentiality, Integrity, Availability", optionB: "Credit, Interest, Assets", optionC: "Capital, Income, Audit", optionD: "Cash, Inventory, Accounts", correctOption: "A", explanation: "Information-security objectives are confidentiality, integrity, and availability of data and systems.", orderIndex: 9 },
  { id: "frm-operational-risk-cyber-technology-risk-q11", topicId: "frm-operational-risk-cyber-technology-risk", text: "Defense in depth refers to:", optionA: "Multiple layered security controls", optionB: "A single firewall", optionC: "No controls", optionD: "Outsourcing all risk", correctOption: "A", explanation: "Layered, redundant controls reduce the chance that a single failure leads to compromise.", orderIndex: 10 },
  { id: "frm-operational-risk-cyber-technology-risk-q12", topicId: "frm-operational-risk-cyber-technology-risk", text: "Third-party/vendor cyber risk is significant because:", optionA: "Attackers can breach a firm via its suppliers (supply-chain risk)", optionB: "Vendors never fail", optionC: "It is uninsurable only", optionD: "It is irrelevant", correctOption: "A", explanation: "Interconnected vendors expand the attack surface; supply-chain compromises are a growing threat.", orderIndex: 11 },

  // ── Operational Risk: Business Continuity ──
  { id: "frm-operational-risk-business-continuity-q09", topicId: "frm-operational-risk-business-continuity", text: "A business continuity plan (BCP) aims to:", optionA: "Maintain or restore critical operations after a disruption", optionB: "Increase trading profits", optionC: "Price derivatives", optionD: "Lower taxes", correctOption: "A", explanation: "BCP ensures essential functions continue or recover quickly following a disruptive event.", orderIndex: 8 },
  { id: "frm-operational-risk-business-continuity-q10", topicId: "frm-operational-risk-business-continuity", text: "The recovery time objective (RTO) specifies:", optionA: "The maximum acceptable downtime for a process", optionB: "The data backup size", optionC: "The coupon", optionD: "The VaR", correctOption: "A", explanation: "RTO is the target time within which a function must be restored after an outage.", orderIndex: 9 },
  { id: "frm-operational-risk-business-continuity-q11", topicId: "frm-operational-risk-business-continuity", text: "The recovery point objective (RPO) defines the:", optionA: "Maximum tolerable data loss (age of recoverable data)", optionB: "Downtime allowed", optionC: "Profit target", optionD: "Credit limit", correctOption: "A", explanation: "RPO sets how much recent data loss is acceptable, driving backup frequency.", orderIndex: 10 },
  { id: "frm-operational-risk-business-continuity-q12", topicId: "frm-operational-risk-business-continuity", text: "A business impact analysis (BIA) is used to:", optionA: "Identify critical functions and the impact of their disruption", optionB: "Price options", optionC: "Set dividends", optionD: "Measure beta", correctOption: "A", explanation: "A BIA prioritizes processes by the consequences of disruption, informing continuity planning.", orderIndex: 11 },

  // ── Liquidity Risk: Liquidity Risk Management ──
  { id: "frm-liquidity-risk-liquidity-risk-management-q09", topicId: "frm-liquidity-risk-liquidity-risk-management", text: "Liquidity risk has two main forms:", optionA: "Funding liquidity and market (asset) liquidity", optionB: "Credit and market", optionC: "Operational and legal", optionD: "Tax and audit", correctOption: "A", explanation: "Funding liquidity is the ability to meet obligations; market liquidity is the ability to sell without large price impact.", orderIndex: 8 },
  { id: "frm-liquidity-risk-liquidity-risk-management-q10", topicId: "frm-liquidity-risk-liquidity-risk-management", text: "A liquidity coverage ratio (LCR) ensures a bank holds enough:", optionA: "High-quality liquid assets to survive a 30-day stress", optionB: "Equity capital", optionC: "Long-term funding", optionD: "Derivatives", correctOption: "A", explanation: "The LCR requires HQLA to cover net cash outflows over a 30-day stress scenario.", orderIndex: 9 },
  { id: "frm-liquidity-risk-liquidity-risk-management-q11", topicId: "frm-liquidity-risk-liquidity-risk-management", text: "The net stable funding ratio (NSFR) addresses:", optionA: "Longer-term structural funding stability (1 year)", optionB: "30-day liquidity", optionC: "Market risk", optionD: "Credit risk", correctOption: "A", explanation: "The NSFR promotes stable funding of assets over a one-year horizon, complementing the LCR.", orderIndex: 10 },
  { id: "frm-liquidity-risk-liquidity-risk-management-q12", topicId: "frm-liquidity-risk-liquidity-risk-management", text: "Maturity transformation by banks creates liquidity risk because they:", optionA: "Fund long-term assets with short-term liabilities", optionB: "Hold only cash", optionC: "Match all maturities", optionD: "Avoid deposits", correctOption: "A", explanation: "Borrowing short and lending long exposes banks to runs and rollover risk.", orderIndex: 11 },

  // ── Liquidity Risk: Funding Liquidity ──
  { id: "frm-liquidity-risk-funding-liquidity-q09", topicId: "frm-liquidity-risk-funding-liquidity", text: "Funding liquidity risk is the risk that a firm:", optionA: "Cannot meet cash obligations as they fall due", optionB: "Loses money on trades", optionC: "Has too much cash", optionD: "Faces rating upgrades", correctOption: "A", explanation: "Funding liquidity risk is the inability to settle obligations without incurring unacceptable cost.", orderIndex: 8 },
  { id: "frm-liquidity-risk-funding-liquidity-q10", topicId: "frm-liquidity-risk-funding-liquidity", text: "Diversifying funding sources reduces:", optionA: "Concentration/rollover risk", optionB: "Market risk only", optionC: "Credit spread", optionD: "Coupon", correctOption: "A", explanation: "Relying on varied, stable funding lowers the risk that one source dries up at once.", orderIndex: 9 },
  { id: "frm-liquidity-risk-funding-liquidity-q11", topicId: "frm-liquidity-risk-funding-liquidity", text: "A contingency funding plan (CFP) specifies:", optionA: "Actions and sources to meet liquidity needs under stress", optionB: "The dividend policy", optionC: "Tax strategy", optionD: "Marketing", correctOption: "A", explanation: "A CFP pre-defines how the firm will raise liquidity during a crisis.", orderIndex: 10 },
  { id: "frm-liquidity-risk-funding-liquidity-q12", topicId: "frm-liquidity-risk-funding-liquidity", text: "Short-term wholesale funding is risky because it can:", optionA: "Be withdrawn quickly in stress (runnable)", optionB: "Never be withdrawn", optionC: "Lower leverage", optionD: "Eliminate risk", correctOption: "A", explanation: "Wholesale funding is flight-prone, making heavy reliance on it a key vulnerability.", orderIndex: 11 },

  // ── Liquidity Risk: Market Liquidity ──
  { id: "frm-liquidity-risk-market-liquidity-q09", topicId: "frm-liquidity-risk-market-liquidity", text: "Market liquidity risk refers to the risk of:", optionA: "Being unable to sell an asset without a large price concession", optionB: "Default", optionC: "Rate changes", optionD: "Currency moves", correctOption: "A", explanation: "Market (asset) liquidity risk is the cost/impact of trading out of a position quickly.", orderIndex: 8 },
  { id: "frm-liquidity-risk-market-liquidity-q10", topicId: "frm-liquidity-risk-market-liquidity", text: "The bid-ask spread is a common measure of:", optionA: "Market liquidity (tighter = more liquid)", optionB: "Credit risk", optionC: "Duration", optionD: "Beta", correctOption: "A", explanation: "Narrow bid-ask spreads indicate liquid markets; wide spreads signal illiquidity.", orderIndex: 9 },
  { id: "frm-liquidity-risk-market-liquidity-q11", topicId: "frm-liquidity-risk-market-liquidity", text: "Market depth describes:", optionA: "The volume tradable without moving the price much", optionB: "The coupon", optionC: "The default rate", optionD: "The maturity", correctOption: "A", explanation: "Depth is the quantity available near the prevailing price; deep markets absorb large trades.", orderIndex: 10 },
  { id: "frm-liquidity-risk-market-liquidity-q12", topicId: "frm-liquidity-risk-market-liquidity", text: "Liquidity tends to evaporate when:", optionA: "Markets are stressed and everyone sells at once", optionB: "Markets are calm", optionC: "Volumes are high", optionD: "Spreads are tight", correctOption: "A", explanation: "Liquidity is pro-cyclical, drying up exactly when it is most needed in a crisis.", orderIndex: 11 },

  // ── Liquidity Risk: Stress Testing ──
  { id: "frm-liquidity-risk-stress-testing-q09", topicId: "frm-liquidity-risk-stress-testing", text: "Liquidity stress testing projects cash flows under:", optionA: "Adverse funding and market scenarios", optionB: "Only base case", optionC: "Marketing plans", optionD: "Audit schedules", correctOption: "A", explanation: "It models survival horizons given deposit run-off, drawdowns, and frozen markets.", orderIndex: 8 },
  { id: "frm-liquidity-risk-stress-testing-q10", topicId: "frm-liquidity-risk-stress-testing", text: "A liquidity 'survival horizon' is the time a firm can:", optionA: "Meet obligations under stress without new funding", optionB: "Earn profits", optionC: "Pay dividends", optionD: "Avoid taxes", correctOption: "A", explanation: "The survival period measures how long liquid resources last in a stress before action is needed.", orderIndex: 9 },
  { id: "frm-liquidity-risk-stress-testing-q11", topicId: "frm-liquidity-risk-stress-testing", text: "A liquidity buffer of HQLA is held to:", optionA: "Bridge cash shortfalls during stress", optionB: "Increase leverage", optionC: "Boost trading P&L", optionD: "Lower capital", correctOption: "A", explanation: "High-quality liquid assets can be monetized quickly to cover outflows in a crisis.", orderIndex: 10 },
  { id: "frm-liquidity-risk-stress-testing-q12", topicId: "frm-liquidity-risk-stress-testing", text: "Combined (idiosyncratic plus market-wide) scenarios are used because:", optionA: "A firm may face its own and systemic stress simultaneously", optionB: "Only firm stress matters", optionC: "Only market stress matters", optionD: "Stress never combines", correctOption: "A", explanation: "Severe events often pair a firm-specific shock with market-wide turmoil, so both are tested together.", orderIndex: 11 },

  // ── Liquidity Risk: ALM ──
  { id: "frm-liquidity-risk-alm-q09", topicId: "frm-liquidity-risk-alm", text: "Asset-liability management (ALM) primarily manages the:", optionA: "Mismatch between asset and liability cash flows/rates", optionB: "Marketing budget", optionC: "Equity research", optionD: "Tax filing", correctOption: "A", explanation: "ALM coordinates the maturity and rate profiles of assets and liabilities to manage rate and liquidity risk.", orderIndex: 8 },
  { id: "frm-liquidity-risk-alm-q10", topicId: "frm-liquidity-risk-alm", text: "A positive duration gap (assets longer than liabilities) means net worth falls when rates:", optionA: "Rise", optionB: "Fall", optionC: "Stay flat", optionD: "Are zero", correctOption: "A", explanation: "If assets have longer duration than liabilities, rising rates reduce equity value.", orderIndex: 9 },
  { id: "frm-liquidity-risk-alm-q11", topicId: "frm-liquidity-risk-alm", text: "Repricing (gap) analysis classifies assets and liabilities by:", optionA: "Time buckets when their rates reset", optionB: "Credit rating", optionC: "Currency only", optionD: "Coupon size", correctOption: "A", explanation: "Gap analysis groups items by repricing date to assess net interest income sensitivity.", orderIndex: 10 },
  { id: "frm-liquidity-risk-alm-q12", topicId: "frm-liquidity-risk-alm", text: "Banks may hedge interest-rate gaps in the banking book using:", optionA: "Interest-rate swaps", optionB: "Equity options", optionC: "Commodity futures", optionD: "CDS", correctOption: "A", explanation: "Swaps adjust the duration gap, aligning the rate sensitivity of assets and liabilities.", orderIndex: 11 },

  // ── Investment Risk: Portfolio Risk & Budgeting ──
  { id: "frm-investment-risk-portfolio-risk-budgeting-q09", topicId: "frm-investment-risk-portfolio-risk-budgeting", text: "Risk budgeting allocates a portfolio's:", optionA: "Total risk across positions or strategies", optionB: "Marketing spend", optionC: "Tax liability", optionD: "Coupon income", correctOption: "A", explanation: "Risk budgeting distributes the overall risk limit to where it is expected to be best rewarded.", orderIndex: 8 },
  { id: "frm-investment-risk-portfolio-risk-budgeting-q10", topicId: "frm-investment-risk-portfolio-risk-budgeting", text: "Marginal VaR measures the change in portfolio VaR from a:", optionA: "Small change in a position", optionB: "Change in the risk-free rate", optionC: "Dividend cut", optionD: "Rating change", correctOption: "A", explanation: "Marginal VaR is the sensitivity of total VaR to a marginal increase in a holding.", orderIndex: 9 },
  { id: "frm-investment-risk-portfolio-risk-budgeting-q11", topicId: "frm-investment-risk-portfolio-risk-budgeting", text: "Component VaR sums across positions to equal the:", optionA: "Total portfolio VaR", optionB: "Sum of standalone VaRs", optionC: "Mean return", optionD: "Tracking error", correctOption: "A", explanation: "Component VaR decomposes total VaR into additive contributions, unlike standalone VaRs which ignore diversification.", orderIndex: 10 },
  { id: "frm-investment-risk-portfolio-risk-budgeting-q12", topicId: "frm-investment-risk-portfolio-risk-budgeting", text: "Diversification reduces portfolio VaR when assets are:", optionA: "Less than perfectly correlated", optionB: "Perfectly correlated", optionC: "Identical", optionD: "Risk-free", correctOption: "A", explanation: "Imperfect correlation makes total VaR less than the sum of standalone VaRs, the diversification benefit.", orderIndex: 11 },

  // ── Investment Risk: Hedge Fund Risk ──
  { id: "frm-investment-risk-hedge-fund-risk-q09", topicId: "frm-investment-risk-hedge-fund-risk", text: "Hedge fund returns often exhibit:", optionA: "Negative skew and fat tails", optionB: "Perfect normality", optionC: "No risk", optionD: "Symmetric thin tails", correctOption: "A", explanation: "Many strategies show option-like, negatively skewed, fat-tailed returns that volatility alone understates.", orderIndex: 8 },
  { id: "frm-investment-risk-hedge-fund-risk-q10", topicId: "frm-investment-risk-hedge-fund-risk", text: "Reported hedge fund volatility may be understated due to:", optionA: "Smoothed/illiquid pricing and survivorship/backfill bias", optionB: "Daily mark-to-market", optionC: "Full transparency", optionD: "No fees", correctOption: "A", explanation: "Stale pricing and database biases flatter measured risk and returns.", orderIndex: 9 },
  { id: "frm-investment-risk-hedge-fund-risk-q11", topicId: "frm-investment-risk-hedge-fund-risk", text: "Liquidity risk in hedge funds is heightened by:", optionA: "Lock-ups, gates, and redemption restrictions", optionB: "Daily liquidity", optionC: "Government guarantees", optionD: "No leverage", correctOption: "A", explanation: "Redemption limits can trap investors precisely when they want to exit.", orderIndex: 10 },
  { id: "frm-investment-risk-hedge-fund-risk-q12", topicId: "frm-investment-risk-hedge-fund-risk", text: "Operational due diligence on hedge funds is important because:", optionA: "Many failures stem from operational/fraud issues, not markets", optionB: "Operations never fail", optionC: "Only returns matter", optionD: "It lowers fees", correctOption: "A", explanation: "A large share of hedge fund losses trace to operational weaknesses or fraud, making ODD essential.", orderIndex: 11 },

  // ── Investment Risk: Pension Risk ──
  { id: "frm-investment-risk-pension-risk-q09", topicId: "frm-investment-risk-pension-risk", text: "A defined-benefit pension's funded status is:", optionA: "Plan assets minus the present value of liabilities", optionB: "Assets plus liabilities", optionC: "Contributions only", optionD: "The discount rate", correctOption: "A", explanation: "Funded status (surplus/deficit) is assets less the PV of promised benefits.", orderIndex: 8 },
  { id: "frm-investment-risk-pension-risk-q10", topicId: "frm-investment-risk-pension-risk", text: "Pension liabilities are most sensitive to changes in the:", optionA: "Discount rate (and longevity)", optionB: "Equity market only", optionC: "Currency", optionD: "Commodity prices", correctOption: "A", explanation: "Long-duration liabilities rise as discount rates fall; longevity assumptions also matter.", orderIndex: 9 },
  { id: "frm-investment-risk-pension-risk-q11", topicId: "frm-investment-risk-pension-risk", text: "Liability-driven investing (LDI) aims to:", optionA: "Match asset sensitivities to the liabilities", optionB: "Maximize equity returns", optionC: "Ignore liabilities", optionD: "Hold only cash", correctOption: "A", explanation: "LDI hedges the interest-rate (and inflation) sensitivity of liabilities to stabilize funded status.", orderIndex: 10 },
  { id: "frm-investment-risk-pension-risk-q12", topicId: "frm-investment-risk-pension-risk", text: "A pension's surplus risk is the volatility of:", optionA: "Assets minus liabilities", optionB: "Assets only", optionC: "Contributions", optionD: "The coupon", correctOption: "A", explanation: "Surplus risk focuses on the volatility of the net position, not assets in isolation.", orderIndex: 11 },

  // ── Investment Risk: Factor Models ──
  { id: "frm-investment-risk-factor-models-q09", topicId: "frm-investment-risk-factor-models", text: "A multifactor model explains returns using:", optionA: "Multiple systematic risk factors", optionB: "Only the market factor", optionC: "No factors", optionD: "Idiosyncratic risk only", correctOption: "A", explanation: "Multifactor models (e.g., Fama-French) attribute returns to several systematic factors beyond the market.", orderIndex: 8 },
  { id: "frm-investment-risk-factor-models-q10", topicId: "frm-investment-risk-factor-models", text: "The Fama-French model adds which factors to the market?", optionA: "Size and value", optionB: "Liquidity and credit", optionC: "Inflation and growth", optionD: "Currency and commodity", correctOption: "A", explanation: "The three-factor model adds SMB (size) and HML (value) to the market factor.", orderIndex: 9 },
  { id: "frm-investment-risk-factor-models-q11", topicId: "frm-investment-risk-factor-models", text: "Factor models help risk management by enabling:", optionA: "Decomposition of portfolio risk into factor exposures", optionB: "Guaranteed returns", optionC: "Removal of all risk", optionD: "Ignoring correlations", correctOption: "A", explanation: "They attribute and aggregate risk via common factor exposures, aiding hedging and budgeting.", orderIndex: 10 },
  { id: "frm-investment-risk-factor-models-q12", topicId: "frm-investment-risk-factor-models", text: "The momentum factor captures the tendency of:", optionA: "Recent winners to keep outperforming short-term", optionB: "Returns to mean-revert instantly", optionC: "All stocks to move together", optionD: "Bonds to outperform", correctOption: "A", explanation: "Momentum is the empirical persistence of recent relative performance over intermediate horizons.", orderIndex: 11 },

  // ── Investment Risk: ESG ──
  { id: "frm-investment-risk-esg-q09", topicId: "frm-investment-risk-esg", text: "ESG integration in risk management treats environmental, social, and governance factors as:", optionA: "Sources of financial risk and opportunity", optionB: "Purely ethical with no financial impact", optionC: "Irrelevant", optionD: "Accounting rules", correctOption: "A", explanation: "ESG integration considers material ESG issues as drivers of long-term financial risk and return.", orderIndex: 8 },
  { id: "frm-investment-risk-esg-q10", topicId: "frm-investment-risk-esg", text: "Climate transition risk refers to losses from:", optionA: "Policy, technology, and market shifts to a low-carbon economy", optionB: "Physical weather damage only", optionC: "Interest rates", optionD: "Currency moves", correctOption: "A", explanation: "Transition risk arises from the move to a low-carbon economy (carbon pricing, stranded assets), distinct from physical risk.", orderIndex: 9 },
  { id: "frm-investment-risk-esg-q11", topicId: "frm-investment-risk-esg", text: "'Greenwashing' is the risk that a product is:", optionA: "Marketed as more sustainable than it really is", optionB: "Too transparent", optionC: "Government guaranteed", optionD: "Risk-free", correctOption: "A", explanation: "Greenwashing misrepresents ESG credentials, creating reputational and regulatory risk.", orderIndex: 10 },
  { id: "frm-investment-risk-esg-q12", topicId: "frm-investment-risk-esg", text: "A challenge in ESG risk analysis is:", optionA: "Inconsistent data and divergent ratings across providers", optionB: "Too much standardization", optionC: "No available data ever", optionD: "Perfect comparability", correctOption: "A", explanation: "ESG metrics and ratings vary widely by methodology, complicating comparison and integration.", orderIndex: 11 },

  // ── Current Issues: Basel III/IV & Emerging Risks ──
  { id: "frm-current-issues-basel-iii-iv-emerging-risks-q09", topicId: "frm-current-issues-basel-iii-iv-emerging-risks", text: "A core aim of Basel III was to strengthen:", optionA: "Bank capital quality and liquidity standards", optionB: "Marketing rules", optionC: "Tax collection", optionD: "Dividend policy", correctOption: "A", explanation: "Basel III raised the quantity/quality of capital and introduced the LCR and NSFR liquidity standards.", orderIndex: 8 },
  { id: "frm-current-issues-basel-iii-iv-emerging-risks-q10", topicId: "frm-current-issues-basel-iii-iv-emerging-risks", text: "The Basel III leverage ratio is a backstop based on:", optionA: "Capital relative to total (non-risk-weighted) exposure", optionB: "Risk-weighted assets only", optionC: "Deposits", optionD: "Market cap", correctOption: "A", explanation: "The leverage ratio constrains capital against total exposure, independent of risk weights.", orderIndex: 9 },
  { id: "frm-current-issues-basel-iii-iv-emerging-risks-q11", topicId: "frm-current-issues-basel-iii-iv-emerging-risks", text: "The countercyclical capital buffer is designed to:", optionA: "Build capital in booms for release in downturns", optionB: "Lower capital in booms", optionC: "Fix capital permanently", optionD: "Remove buffers", correctOption: "A", explanation: "It accumulates extra capital during credit expansions to be drawn down in stress, dampening cyclicality.", orderIndex: 10 },
  { id: "frm-current-issues-basel-iii-iv-emerging-risks-q12", topicId: "frm-current-issues-basel-iii-iv-emerging-risks", text: "The 'Basel III endgame' (Basel IV) output floor limits reliance on:", optionA: "Internal models versus standardized approaches", optionB: "External ratings only", optionC: "Market prices", optionD: "Deposits", correctOption: "A", explanation: "The output floor caps how much internal models can reduce capital below the standardized calculation.", orderIndex: 11 },

  // ── Current Issues: Climate Risk ──
  { id: "frm-current-issues-climate-risk-q09", topicId: "frm-current-issues-climate-risk", text: "Physical climate risk includes losses from:", optionA: "Acute events (floods, storms) and chronic shifts", optionB: "Carbon taxes only", optionC: "Interest rates", optionD: "Currency moves", correctOption: "A", explanation: "Physical risk covers acute weather events and chronic changes like sea-level rise affecting assets.", orderIndex: 8 },
  { id: "frm-current-issues-climate-risk-q10", topicId: "frm-current-issues-climate-risk", text: "Climate scenario analysis (e.g., NGFS scenarios) is used to:", optionA: "Assess long-horizon climate impacts on portfolios", optionB: "Price daily VaR", optionC: "Set coupons", optionD: "Measure liquidity", correctOption: "A", explanation: "Forward-looking climate scenarios gauge transition and physical impacts over long horizons.", orderIndex: 9 },
  { id: "frm-current-issues-climate-risk-q11", topicId: "frm-current-issues-climate-risk", text: "'Stranded assets' are assets that:", optionA: "Lose value due to the low-carbon transition", optionB: "Gain value from rate cuts", optionC: "Are risk-free", optionD: "Pay high coupons", correctOption: "A", explanation: "Fossil-fuel and high-carbon assets may become uneconomic (stranded) as policy and technology shift.", orderIndex: 10 },
  { id: "frm-current-issues-climate-risk-q12", topicId: "frm-current-issues-climate-risk", text: "The TCFD framework promotes disclosure of:", optionA: "Climate-related governance, strategy, risks, and metrics", optionB: "Only carbon offsets", optionC: "Marketing data", optionD: "Tax positions", correctOption: "A", explanation: "The TCFD recommends consistent disclosures across governance, strategy, risk management, and metrics/targets.", orderIndex: 11 },

  // ── Current Issues: Digital Assets ──
  { id: "frm-current-issues-digital-assets-q09", topicId: "frm-current-issues-digital-assets", text: "A stablecoin aims to:", optionA: "Maintain a stable value, often pegged to a fiat currency", optionB: "Maximize volatility", optionC: "Pay a fixed coupon", optionD: "Track equities", correctOption: "A", explanation: "Stablecoins seek price stability via fiat, crypto, or algorithmic backing; reserve quality is a key risk.", orderIndex: 8 },
  { id: "frm-current-issues-digital-assets-q10", topicId: "frm-current-issues-digital-assets", text: "A major risk of crypto assets for institutions is:", optionA: "Extreme volatility, custody, and operational/cyber risk", optionB: "Guaranteed returns", optionC: "Low volatility", optionD: "Government insurance", correctOption: "A", explanation: "Crypto carries high price volatility plus custody, smart-contract, and cyber risks.", orderIndex: 9 },
  { id: "frm-current-issues-digital-assets-q11", topicId: "frm-current-issues-digital-assets", text: "Decentralized finance (DeFi) introduces risk from:", optionA: "Smart-contract bugs and lack of intermediary safeguards", optionB: "Too much regulation", optionC: "Central clearing", optionD: "Deposit insurance", correctOption: "A", explanation: "DeFi protocols can suffer code exploits and offer none of the protections of regulated intermediaries.", orderIndex: 10 },
  { id: "frm-current-issues-digital-assets-q12", topicId: "frm-current-issues-digital-assets", text: "A central bank digital currency (CBDC) is:", optionA: "A digital form of sovereign (central bank) money", optionB: "A private stablecoin", optionC: "A corporate bond", optionD: "An equity", correctOption: "A", explanation: "A CBDC is central-bank-issued digital money, distinct from private crypto or stablecoins.", orderIndex: 11 },

  // ── Current Issues: AI & Machine Learning ──
  { id: "frm-current-issues-ai-machine-learning-q09", topicId: "frm-current-issues-ai-machine-learning", text: "A key model-risk concern with machine-learning models is:", optionA: "Lack of interpretability ('black box')", optionB: "Too much transparency", optionC: "No data needed", optionD: "Guaranteed accuracy", correctOption: "A", explanation: "Complex ML models can be opaque, complicating validation, governance, and accountability.", orderIndex: 8 },
  { id: "frm-current-issues-ai-machine-learning-q10", topicId: "frm-current-issues-ai-machine-learning", text: "Overfitting in machine learning means the model:", optionA: "Fits noise in training data and generalizes poorly", optionB: "Is too simple", optionC: "Ignores the data", optionD: "Always generalizes well", correctOption: "A", explanation: "Overfit models memorize training noise and perform poorly out-of-sample.", orderIndex: 9 },
  { id: "frm-current-issues-ai-machine-learning-q11", topicId: "frm-current-issues-ai-machine-learning", text: "Bias in training data can cause an ML model to produce:", optionA: "Unfair or discriminatory and reputationally risky outputs", optionB: "Perfectly fair results", optionC: "No predictions", optionD: "Lower model risk", correctOption: "A", explanation: "Biased data can lead to discriminatory decisions, raising fairness, legal, and reputational risk.", orderIndex: 10 },
  { id: "frm-current-issues-ai-machine-learning-q12", topicId: "frm-current-issues-ai-machine-learning", text: "Sound ML governance requires:", optionA: "Explainability, validation, monitoring, and human oversight", optionB: "No documentation", optionC: "Removing all controls", optionD: "Ignoring drift", correctOption: "A", explanation: "ML model risk is managed through interpretability tools, independent validation, monitoring for drift, and human oversight.", orderIndex: 11 },

  // ── Current Issues: Systemic Risk ──
  { id: "frm-current-issues-systemic-risk-q09", topicId: "frm-current-issues-systemic-risk", text: "Systemic risk is the risk that:", optionA: "Failure of one institution cascades through the financial system", optionB: "A single stock falls", optionC: "Rates rise once", optionD: "A coupon is missed", correctOption: "A", explanation: "Systemic risk is the threat that distress spreads via interconnections, threatening the whole system.", orderIndex: 8 },
  { id: "frm-current-issues-systemic-risk-q10", topicId: "frm-current-issues-systemic-risk", text: "Globally systemically important banks (G-SIBs) face:", optionA: "Additional capital surcharges", optionB: "Lower capital requirements", optionC: "No regulation", optionD: "Tax exemptions", correctOption: "A", explanation: "G-SIBs carry capital surcharges scaled to their systemic importance to reduce failure probability.", orderIndex: 9 },
  { id: "frm-current-issues-systemic-risk-q11", topicId: "frm-current-issues-systemic-risk", text: "Interconnectedness raises systemic risk through:", optionA: "Contagion via counterparty and funding linkages", optionB: "Diversification only", optionC: "Lower leverage", optionD: "Isolated balance sheets", correctOption: "A", explanation: "Dense counterparty and funding links transmit shocks, amplifying contagion across institutions.", orderIndex: 10 },
  { id: "frm-current-issues-systemic-risk-q12", topicId: "frm-current-issues-systemic-risk", text: "Macroprudential policy aims to:", optionA: "Reduce system-wide risk, not just individual firm risk", optionB: "Maximize bank profits", optionC: "Ignore the system", optionD: "Set monetary policy only", correctOption: "A", explanation: "Macroprudential tools (buffers, limits) target system-wide stability beyond firm-level microprudential rules.", orderIndex: 11 }
];
