// FRM expansion 6 — one additional high-yield reading per area (12 questions
// each), filling syllabus gaps not covered by exp-1..5.
import type { Question } from "@jyotir/core";
import type { AuthoredMaterial } from "./builder";

export const expansionTopics = [
  {
    id: "frm-foundations-apt-multifactor",
    subjectId: "frm-foundations",
    name: "APT & Multifactor Models",
    slug: "apt-multifactor",
    orderIndex: 5,
    materialId: "frm-foundations-apt-multifactor-m01",
    questionIds: Array.from({ length: 12 }, (_, i) => `frm-foundations-apt-multifactor-q${String(i + 1).padStart(2, "0")}`),
  },
  {
    id: "frm-quantitative-analysis-time-series",
    subjectId: "frm-quantitative-analysis",
    name: "Time Series: AR, MA & Stationarity",
    slug: "time-series",
    orderIndex: 5,
    materialId: "frm-quantitative-analysis-time-series-m01",
    questionIds: Array.from({ length: 12 }, (_, i) => `frm-quantitative-analysis-time-series-q${String(i + 1).padStart(2, "0")}`),
  },
  {
    id: "frm-financial-markets-market-structure",
    subjectId: "frm-financial-markets",
    name: "Exchanges, OTC Markets & Central Clearing",
    slug: "market-structure",
    orderIndex: 5,
    materialId: "frm-financial-markets-market-structure-m01",
    questionIds: Array.from({ length: 12 }, (_, i) => `frm-financial-markets-market-structure-q${String(i + 1).padStart(2, "0")}`),
  },
  {
    id: "frm-valuation-risk-models-volatility-smiles",
    subjectId: "frm-valuation-risk-models",
    name: "Volatility Smiles & Surfaces",
    slug: "volatility-smiles",
    orderIndex: 5,
    materialId: "frm-valuation-risk-models-volatility-smiles-m01",
    questionIds: Array.from({ length: 12 }, (_, i) => `frm-valuation-risk-models-volatility-smiles-q${String(i + 1).padStart(2, "0")}`),
  },
  {
    id: "frm-market-risk-risk-factor-mapping",
    subjectId: "frm-market-risk",
    name: "Mapping Portfolios to Risk Factors",
    slug: "risk-factor-mapping",
    orderIndex: 5,
    materialId: "frm-market-risk-risk-factor-mapping-m01",
    questionIds: Array.from({ length: 12 }, (_, i) => `frm-market-risk-risk-factor-mapping-q${String(i + 1).padStart(2, "0")}`),
  },
  {
    id: "frm-credit-risk-merton-model",
    subjectId: "frm-credit-risk",
    name: "Merton Model & Distance to Default",
    slug: "merton-model",
    orderIndex: 5,
    materialId: "frm-credit-risk-merton-model-m01",
    questionIds: Array.from({ length: 12 }, (_, i) => `frm-credit-risk-merton-model-q${String(i + 1).padStart(2, "0")}`),
  },
  {
    id: "frm-operational-risk-scenario-analysis-op",
    subjectId: "frm-operational-risk",
    name: "External Loss Data & Scenario Analysis",
    slug: "scenario-analysis-op",
    orderIndex: 5,
    materialId: "frm-operational-risk-scenario-analysis-op-m01",
    questionIds: Array.from({ length: 12 }, (_, i) => `frm-operational-risk-scenario-analysis-op-q${String(i + 1).padStart(2, "0")}`),
  },
  {
    id: "frm-liquidity-risk-lvar",
    subjectId: "frm-liquidity-risk",
    name: "Liquidity-Adjusted VaR (LVaR)",
    slug: "lvar",
    orderIndex: 5,
    materialId: "frm-liquidity-risk-lvar-m01",
    questionIds: Array.from({ length: 12 }, (_, i) => `frm-liquidity-risk-lvar-q${String(i + 1).padStart(2, "0")}`),
  },
  {
    id: "frm-investment-risk-performance-measurement",
    subjectId: "frm-investment-risk",
    name: "Performance Measurement: Sharpe, Sortino & Information Ratio",
    slug: "performance-measurement",
    orderIndex: 5,
    materialId: "frm-investment-risk-performance-measurement-m01",
    questionIds: Array.from({ length: 12 }, (_, i) => `frm-investment-risk-performance-measurement-q${String(i + 1).padStart(2, "0")}`),
  },
  {
    id: "frm-current-issues-libor-transition",
    subjectId: "frm-current-issues",
    name: "Reference Rate Reform: LIBOR to SOFR",
    slug: "libor-transition",
    orderIndex: 5,
    materialId: "frm-current-issues-libor-transition-m01",
    questionIds: Array.from({ length: 12 }, (_, i) => `frm-current-issues-libor-transition-q${String(i + 1).padStart(2, "0")}`),
  },
];

export const expansionMaterials: AuthoredMaterial[] = [
  {
    id: "frm-foundations-apt-multifactor-m01",
    topicId: "frm-foundations-apt-multifactor",
    title: "APT & Multifactor Models",
    content: `**Arbitrage Pricing Theory (APT)** explains expected return as a linear function of **multiple systematic risk factors**, not just the single market factor of the CAPM.

**E[R_i] = R_f + β_{i,1}·RP_1 + β_{i,2}·RP_2 + … + β_{i,k}·RP_k**

- Each **β** is the asset's sensitivity (factor loading) to a factor; each **RP** is that factor's risk premium.
- APT rests on **no-arbitrage**, not on the mean-variance / market-portfolio assumptions of CAPM.
- APT does **not** specify the factors. Common macro factors: inflation surprises, GDP/industrial production, term-structure (slope) shifts, credit spreads.

## Multifactor models
- **Macroeconomic** factor models use economic surprises; **fundamental** models (e.g. Fama-French) use firm characteristics (size SMB, value HML, plus market and momentum).
- Used for **return attribution**, **risk decomposition**, and **hedging** specific factor exposures.

> APT generalizes CAPM: CAPM is the special one-factor case where the only priced factor is the market.`,
    estimatedReadTime: 2,
    orderIndex: 5,
  },
  {
    id: "frm-quantitative-analysis-time-series-m01",
    topicId: "frm-quantitative-analysis-time-series",
    title: "Time Series: AR, MA & Stationarity",
    content: `## Stationarity
A **covariance-stationary** series has constant **mean**, constant **variance**, and an autocovariance that depends only on the lag. Most modeling requires it; non-stationary series are often **differenced** first.

## Building blocks
- **AR(p)** — autoregressive: x_t depends on its own past values. An **AR(1)** x_t = c + φ·x_{t−1} + ε_t is stationary iff **|φ| < 1**; its mean reverts to c/(1−φ).
- **MA(q)** — moving average: x_t is a function of current and past **shocks** (ε terms).
- **ARMA(p,q)** combines both; **ARIMA** adds differencing (the "I") for non-stationary data.

## Diagnostics
- A **unit root** (φ = 1, a random walk) means non-stationarity; test with the **(Augmented) Dickey-Fuller** test.
- Choose lag order with **AIC/BIC** (lower is better); check residuals are **white noise** (no remaining autocorrelation, e.g. Ljung-Box).
- **Seasonality** is handled with seasonal lags/differencing.`,
    estimatedReadTime: 2,
    orderIndex: 5,
  },
  {
    id: "frm-financial-markets-market-structure-m01",
    topicId: "frm-financial-markets-market-structure",
    title: "Exchanges, OTC Markets & Central Clearing",
    content: `## Exchange-traded vs OTC
| | Exchange (futures) | OTC (forwards/swaps) |
| --- | --- | --- |
| Terms | Standardized | Customized |
| Counterparty | **Clearinghouse (CCP)** | Bilateral |
| Credit risk | Minimal (margin) | Counterparty risk |
| Liquidity | High | Variable |

## Central counterparties (CCPs)
After 2008, regulators pushed standardized OTC derivatives into **central clearing**. The CCP becomes **buyer to every seller and seller to every buyer** (novation), and manages risk via:
- **Initial margin** (covers potential future exposure) and **variation margin** (daily mark-to-market).
- A **default waterfall**: defaulter's margin → defaulter's default-fund contribution → CCP "skin in the game" → mutualized default fund → assessments.
- **Multilateral netting**, which sharply reduces gross exposures.

## Trade-offs
CCPs concentrate risk (a CCP failure is systemic) and require robust margining and a **guarantee fund**. Non-cleared OTC trades face bilateral margin rules and **CVA** charges.`,
    estimatedReadTime: 2,
    orderIndex: 5,
  },
  {
    id: "frm-valuation-risk-models-volatility-smiles-m01",
    topicId: "frm-valuation-risk-models-volatility-smiles",
    title: "Volatility Smiles & Surfaces",
    content: `Black-Scholes assumes a **single, constant volatility** for all strikes. In reality, implied volatilities **vary by strike and maturity** — evidence the lognormal assumption is imperfect.

## Shapes
- **Volatility smile**: implied vol higher for deep ITM/OTM options than at-the-money — common in **currency** options (fat tails, jumps in both directions).
- **Volatility skew (smirk)**: implied vol higher for **low strikes** (OTM puts) than high strikes — typical of **equity** options, reflecting crash fear and leverage effects.
- **Volatility surface**: implied vol plotted across both strike and maturity; traders interpolate it to price exotics.

## Interpretation
- A smile implies the **risk-neutral distribution has fatter tails** than lognormal.
- An equity skew implies a distribution **left-skewed** (heavier downside).
- Smiles tend to **flatten as maturity lengthens**.
- Implied vol from the smile is the market's forward-looking volatility; using a single ATM vol misprices wing options.`,
    estimatedReadTime: 2,
    orderIndex: 5,
  },
  {
    id: "frm-market-risk-risk-factor-mapping-m01",
    topicId: "frm-market-risk-risk-factor-mapping",
    title: "Mapping Portfolios to Risk Factors",
    content: `**Risk mapping** decomposes positions into a manageable set of standardized **risk factors** so VaR can be computed across a large portfolio.

## Approaches for fixed income
- **Principal (notional) mapping**: map a bond to a single zero at its maturity — crude.
- **Duration mapping**: map to the zero whose maturity matches the bond's **duration**.
- **Cash-flow mapping**: split each cash flow onto adjacent standard vertices, **preserving market value and risk (variance)** — the most accurate.

## Other instruments
- **Forwards/FX forwards**: decompose into spot, foreign bill, and domestic bill positions.
- **Options**: map via **delta** (linear/delta-normal) plus **gamma/vega** for non-linearity; delta-normal VaR understates risk for options.

## Why map?
- Reduces dimensionality, lets you build a **factor covariance matrix**, and isolates **diversified vs undiversified** (component) VaR.
- Trade-off: mapping introduces **basis/specific risk** not captured by the chosen factors.`,
    estimatedReadTime: 2,
    orderIndex: 5,
  },
  {
    id: "frm-credit-risk-merton-model-m01",
    topicId: "frm-credit-risk-merton-model",
    title: "Merton Model & Distance to Default",
    content: `The **Merton (structural) model** treats a firm's **equity as a call option on its assets**, struck at the face value of debt (K), maturing when the debt is due.

- **Default** occurs if asset value V_T < K at maturity. Equity holders exercise (repay debt) only if assets exceed debt.
- Equity value = call on assets; **risky debt = risk-free debt − a put** on the assets (the put is the value of the default option to shareholders).

## Distance to default (DD)
**DD = [ln(V₀/K) + (μ − ½σ²)T] / (σ√T)**

- Higher DD ⇒ lower default probability. In the model, **PD = N(−DD)**.
- Drivers: more **leverage** (K↑) and higher **asset volatility** (σ↑) raise PD; more equity cushion lowers it.

## Strengths & limits
- Strength: links default to **market-based** firm value and volatility (basis for **KMV/Moody's EDF**).
- Limits: assets aren't directly observable; assumes default only at maturity and a simple capital structure; underestimates short-horizon spreads.`,
    estimatedReadTime: 2,
    orderIndex: 5,
  },
  {
    id: "frm-operational-risk-scenario-analysis-op-m01",
    topicId: "frm-operational-risk-scenario-analysis-op",
    title: "External Loss Data & Scenario Analysis",
    content: `Operational risk capital (AMA-style) blends **four elements**: internal loss data, **external loss data**, **scenario analysis**, and business-environment/internal-control factors (BEICFs).

## External loss data
- Sources: **consortium** data (e.g. ORX, member banks pool losses) and **public/vendor** databases (news-based).
- Vital for the **tail** — rare, severe events a single firm hasn't experienced.
- Must be **scaled** to the firm's size/business mix and corrected for **reporting bias** (public data over-weights very large, public losses; thresholds truncate small losses).

## Scenario analysis
- Structured **expert workshops** estimate frequency and severity of plausible severe events (e.g. rogue trader, major cyber breach).
- Strength: forward-looking, captures risks **absent from history**.
- Weakness: **subjective**, prone to behavioral biases (anchoring, availability); needs governance and challenge.

## Combining
Fit a **loss distribution** (frequency × severity), use internal+external data for the body and scenarios for the tail, then derive op-risk capital at a high confidence level (e.g. 99.9%).`,
    estimatedReadTime: 2,
    orderIndex: 5,
  },
  {
    id: "frm-liquidity-risk-lvar-m01",
    topicId: "frm-liquidity-risk-lvar",
    title: "Liquidity-Adjusted VaR (LVaR)",
    content: `Standard VaR ignores the cost of **liquidating** a position. **Liquidity-adjusted VaR (LVaR)** adds that cost.

## Bid-ask (exogenous) spread approach
**LVaR = VaR + ½ × P × spread**, where spread = (ask − bid)/mid and P is the position value. The ½ converts the round-trip spread into a one-way liquidation cost. With **uncertain spreads**, add a multiple of the spread's volatility: ½·P·(μ_spread + k·σ_spread).

## Endogenous (price-impact) liquidity
Large positions move the price. **Optimal execution** spreads trading over time, trading off:
- **Market-impact cost** (trade fast) vs **price-risk cost** (trade slow, more exposure).
- The **liquidation horizon** lengthens VaR: a longer holding period scales VaR by ≈ √(horizon).

## Key ideas
- Liquidity risk has **two parts**: bid-ask (transaction cost) and market impact (depth).
- Liquidity dries up in stress — spreads widen exactly when VaR is largest, so LVaR add-ons should be **stressed**.`,
    estimatedReadTime: 2,
    orderIndex: 5,
  },
  {
    id: "frm-investment-risk-performance-measurement-m01",
    topicId: "frm-investment-risk-performance-measurement",
    title: "Performance Measurement: Sharpe, Sortino & Information Ratio",
    content: `Risk-adjusted performance ratios standardize return per unit of risk.

| Ratio | Numerator | Denominator (risk) |
| --- | --- | --- |
| **Sharpe** | R_p − R_f | Total volatility σ_p |
| **Sortino** | R_p − R_target | **Downside** deviation |
| **Treynor** | R_p − R_f | **Beta** (systematic risk) |
| **Information ratio** | R_p − R_benchmark (active return) | **Tracking error** |

## Notes
- **Sharpe** uses total risk — best for an investor's whole portfolio. **Treynor** uses beta — best for a well-diversified sub-portfolio.
- **Sortino** penalizes only downside volatility, fitting asymmetric/loss-averse mandates.
- **Information ratio** measures skill at generating active return per unit of active risk; **IR = IC × √breadth** (fundamental law of active management).
- **Jensen's alpha** = R_p − [R_f + β(R_m − R_f)]: return above CAPM-required.
- Sharpe and IR are **not** robust when returns are highly non-normal (option-like payoffs) — they ignore skew/kurtosis.`,
    estimatedReadTime: 2,
    orderIndex: 5,
  },
  {
    id: "frm-current-issues-libor-transition-m01",
    topicId: "frm-current-issues-libor-transition",
    title: "Reference Rate Reform: LIBOR to SOFR",
    content: `**LIBOR** (London Interbank Offered Rate) was a **survey-based**, unsecured term rate. After manipulation scandals and the collapse of underlying interbank lending, it was **discontinued** (USD LIBOR ceased mid-2023).

## Replacement: risk-free rates (RFRs)
- USD: **SOFR** (Secured Overnight Financing Rate) — based on actual **overnight Treasury repo** transactions; others: SONIA (GBP), €STR (EUR), TONA (JPY).
- RFRs are **secured/near-risk-free, overnight, backward-looking, transaction-based** — versus LIBOR's unsecured, term, forward-looking, judgement-based nature.

## Key differences & challenges
- LIBOR embedded a **bank credit/term premium**; SOFR does not — so a **credit-spread adjustment** is added for legacy contracts (ISDA fallbacks).
- Overnight RFRs are **compounded in arrears** to make a term rate, so the period rate is known only near the end — operational change for loans.
- **Fallback language** and repapering of trillions in legacy contracts created **legal/basis risk**; term SOFR (forward-looking) emerged for some cash products.

> Theme: move from judgement-based to **transaction-based**, more robust benchmarks.`,
    estimatedReadTime: 2,
    orderIndex: 5,
  },
];

export const expansionQuestions: Question[] = [
  // ── Foundations: APT & Multifactor Models ──
  {
    id: "frm-foundations-apt-multifactor-q01",
    topicId: "frm-foundations-apt-multifactor",
    text: "Arbitrage Pricing Theory (APT) differs from the CAPM primarily because APT:",
    optionA: "Requires the market portfolio to be mean-variance efficient",
    optionB: "Allows expected return to depend on multiple systematic risk factors",
    optionC: "Assumes all investors hold only the risk-free asset",
    optionD: "Ignores systematic risk entirely",
    correctOption: "B",
    explanation: "APT expresses expected return as a linear function of several systematic factors, generalizing the single-factor CAPM.",
    orderIndex: 0,
  },
  {
    id: "frm-foundations-apt-multifactor-q02",
    topicId: "frm-foundations-apt-multifactor",
    text: "APT is fundamentally based on which principle?",
    optionA: "Mean-variance optimization",
    optionB: "No-arbitrage",
    optionC: "Purchasing power parity",
    optionD: "The efficient market hypothesis in strong form",
    correctOption: "B",
    explanation: "APT rests on the absence of arbitrage opportunities rather than the restrictive assumptions underlying the CAPM.",
    orderIndex: 1,
  },
  {
    id: "frm-foundations-apt-multifactor-q03",
    topicId: "frm-foundations-apt-multifactor",
    text: "In an APT model, a 'factor loading' (beta) represents the asset's:",
    optionA: "Total volatility",
    optionB: "Sensitivity to a particular systematic factor",
    optionC: "Idiosyncratic risk",
    optionD: "Expected return",
    correctOption: "B",
    explanation: "Each factor loading measures how sensitive the asset's return is to movements in the associated systematic risk factor.",
    orderIndex: 2,
  },
  {
    id: "frm-foundations-apt-multifactor-q04",
    topicId: "frm-foundations-apt-multifactor",
    text: "A notable limitation of APT relative to the CAPM is that APT:",
    optionA: "Cannot price any assets",
    optionB: "Does not specify what the relevant factors are",
    optionC: "Requires a single factor only",
    optionD: "Assumes no systematic risk",
    correctOption: "B",
    explanation: "APT does not identify the factors or their number; they must be determined empirically or by theory.",
    orderIndex: 3,
  },
  {
    id: "frm-foundations-apt-multifactor-q05",
    topicId: "frm-foundations-apt-multifactor",
    text: "The CAPM can be viewed as a special case of APT in which:",
    optionA: "There are no factors",
    optionB: "The only priced factor is the market portfolio",
    optionC: "All betas equal zero",
    optionD: "Returns are risk-free",
    correctOption: "B",
    explanation: "When the single priced systematic factor is the market excess return, APT reduces to the CAPM.",
    orderIndex: 4,
  },
  {
    id: "frm-foundations-apt-multifactor-q06",
    topicId: "frm-foundations-apt-multifactor",
    text: "The Fama-French three-factor model adds which two factors to the market factor?",
    optionA: "Momentum and liquidity",
    optionB: "Size (SMB) and value (HML)",
    optionC: "Inflation and GDP",
    optionD: "Credit and term spreads",
    correctOption: "B",
    explanation: "The Fama-French three-factor model augments the market factor with size (small minus big) and value (high minus low book-to-market).",
    orderIndex: 5,
  },
  {
    id: "frm-foundations-apt-multifactor-q07",
    topicId: "frm-foundations-apt-multifactor",
    text: "A multifactor model used to attribute a fund's return to its exposures is performing:",
    optionA: "Return (performance) attribution",
    optionB: "Covered interest arbitrage",
    optionC: "Duration matching",
    optionD: "Scenario analysis",
    correctOption: "A",
    explanation: "Decomposing realized returns into factor exposures times factor returns is performance/return attribution.",
    orderIndex: 6,
  },
  {
    id: "frm-foundations-apt-multifactor-q08",
    topicId: "frm-foundations-apt-multifactor",
    text: "Which is a commonly cited MACROECONOMIC factor in multifactor return models?",
    optionA: "Book-to-market ratio",
    optionB: "Firm market capitalization",
    optionC: "Unexpected changes in inflation",
    optionD: "Dividend payout ratio",
    correctOption: "C",
    explanation: "Macroeconomic factor models use economic surprises such as unexpected inflation, GDP/production, term-structure shifts, and credit spreads.",
    orderIndex: 7,
  },
  {
    id: "frm-foundations-apt-multifactor-q09",
    topicId: "frm-foundations-apt-multifactor",
    text: "Under APT, an asset's expected return in excess of the risk-free rate equals the sum of its:",
    optionA: "Idiosyncratic variances",
    optionB: "Factor sensitivities each multiplied by the corresponding factor risk premium",
    optionC: "Historical average returns",
    optionD: "Dividends",
    correctOption: "B",
    explanation: "Expected excess return = Σ (factor beta × factor risk premium) across the systematic factors.",
    orderIndex: 8,
  },
  {
    id: "frm-foundations-apt-multifactor-q10",
    topicId: "frm-foundations-apt-multifactor",
    text: "If an asset has betas of 0.5 to factor 1 (premium 4%) and 1.5 to factor 2 (premium 2%), with R_f = 3%, its APT expected return is:",
    optionA: "8%",
    optionB: "9%",
    optionC: "11%",
    optionD: "5%",
    correctOption: "A",
    explanation: "E[R] = 3% + 0.5×4% + 1.5×2% = 3% + 2% + 3% = 8%.",
    orderIndex: 9,
  },
  {
    id: "frm-foundations-apt-multifactor-q11",
    topicId: "frm-foundations-apt-multifactor",
    text: "Fundamental factor models (e.g., Fama-French) typically define factors using:",
    optionA: "Macroeconomic surprises",
    optionB: "Firm characteristics such as size and value",
    optionC: "Central bank policy rates",
    optionD: "Currency exchange rates",
    correctOption: "B",
    explanation: "Fundamental factor models build factors from observable firm attributes (size, value, momentum, profitability, etc.).",
    orderIndex: 10,
  },
  {
    id: "frm-foundations-apt-multifactor-q12",
    topicId: "frm-foundations-apt-multifactor",
    text: "A risk manager wanting to hedge a portfolio's exposure to a single factor while keeping others would use a multifactor model to:",
    optionA: "Eliminate all returns",
    optionB: "Isolate and offset that factor's beta",
    optionC: "Maximize idiosyncratic risk",
    optionD: "Remove the risk-free rate",
    correctOption: "B",
    explanation: "Multifactor models let a manager identify the target factor's loading and take an offsetting position to neutralize just that exposure.",
    orderIndex: 11,
  },

  // ── Quant: Time Series ──
  {
    id: "frm-quantitative-analysis-time-series-q01",
    topicId: "frm-quantitative-analysis-time-series",
    text: "A covariance-stationary time series has:",
    optionA: "A mean and variance that change over time",
    optionB: "Constant mean, constant variance, and autocovariance depending only on lag",
    optionC: "Zero autocorrelation at all lags",
    optionD: "A unit root",
    correctOption: "B",
    explanation: "Covariance stationarity requires a constant mean and variance and an autocovariance that depends only on the lag between observations.",
    orderIndex: 0,
  },
  {
    id: "frm-quantitative-analysis-time-series-q02",
    topicId: "frm-quantitative-analysis-time-series",
    text: "An AR(1) process x_t = c + φ·x_{t−1} + ε_t is covariance-stationary if:",
    optionA: "|φ| < 1",
    optionB: "φ = 1",
    optionC: "φ > 1",
    optionD: "c = 0",
    correctOption: "A",
    explanation: "Stationarity of an AR(1) requires the autoregressive coefficient to satisfy |φ| < 1; at φ = 1 it becomes a non-stationary random walk.",
    orderIndex: 1,
  },
  {
    id: "frm-quantitative-analysis-time-series-q03",
    topicId: "frm-quantitative-analysis-time-series",
    text: "A random walk is an example of a process that:",
    optionA: "Is covariance-stationary",
    optionB: "Has a unit root and is non-stationary",
    optionC: "Always mean-reverts quickly",
    optionD: "Has zero variance",
    correctOption: "B",
    explanation: "A random walk has a unit root (φ = 1); its variance grows without bound over time, so it is non-stationary.",
    orderIndex: 2,
  },
  {
    id: "frm-quantitative-analysis-time-series-q04",
    topicId: "frm-quantitative-analysis-time-series",
    text: "The Augmented Dickey-Fuller test is used to test for:",
    optionA: "Heteroskedasticity",
    optionB: "A unit root (non-stationarity)",
    optionC: "Normality of residuals",
    optionD: "Multicollinearity",
    correctOption: "B",
    explanation: "The (Augmented) Dickey-Fuller test checks the null hypothesis that a series contains a unit root, i.e., is non-stationary.",
    orderIndex: 3,
  },
  {
    id: "frm-quantitative-analysis-time-series-q05",
    topicId: "frm-quantitative-analysis-time-series",
    text: "In a moving average MA(q) model, the current value is a function of:",
    optionA: "Past values of the variable itself",
    optionB: "Current and past random shocks (error terms)",
    optionC: "Future expected values",
    optionD: "The deterministic trend only",
    correctOption: "B",
    explanation: "An MA(q) process expresses the current observation as a linear combination of the current and q past error (shock) terms.",
    orderIndex: 4,
  },
  {
    id: "frm-quantitative-analysis-time-series-q06",
    topicId: "frm-quantitative-analysis-time-series",
    text: "A common way to make a non-stationary series with a unit root stationary is to:",
    optionA: "Square the series",
    optionB: "Take first differences",
    optionC: "Add a constant",
    optionD: "Multiply by its lag",
    correctOption: "B",
    explanation: "Differencing (e.g., first differences) typically removes a unit root and yields a stationary series—the 'I' (integrated) step in ARIMA.",
    orderIndex: 5,
  },
  {
    id: "frm-quantitative-analysis-time-series-q07",
    topicId: "frm-quantitative-analysis-time-series",
    text: "For an AR(1) with c = 2 and φ = 0.6, the long-run (unconditional) mean is:",
    optionA: "2.0",
    optionB: "3.3",
    optionC: "5.0",
    optionD: "1.2",
    correctOption: "C",
    explanation: "The mean of a stationary AR(1) is c/(1 − φ) = 2 / (1 − 0.6) = 2/0.4 = 5.",
    orderIndex: 6,
  },
  {
    id: "frm-quantitative-analysis-time-series-q08",
    topicId: "frm-quantitative-analysis-time-series",
    text: "Lower values of the Akaike (AIC) or Bayesian (BIC) information criteria indicate:",
    optionA: "A worse model fit/parsimony trade-off",
    optionB: "A preferred model balancing fit and complexity",
    optionC: "Non-stationarity",
    optionD: "Perfect forecasts",
    correctOption: "B",
    explanation: "AIC/BIC penalize complexity; lower values indicate a better balance of fit and parsimony, guiding lag-order selection.",
    orderIndex: 7,
  },
  {
    id: "frm-quantitative-analysis-time-series-q09",
    topicId: "frm-quantitative-analysis-time-series",
    text: "After fitting a time-series model, residuals should ideally resemble:",
    optionA: "A strong upward trend",
    optionB: "White noise with no remaining autocorrelation",
    optionC: "A random walk",
    optionD: "A perfect sine wave",
    correctOption: "B",
    explanation: "Well-specified models leave residuals that are white noise—no significant remaining autocorrelation (checked with tests like Ljung-Box).",
    orderIndex: 8,
  },
  {
    id: "frm-quantitative-analysis-time-series-q10",
    topicId: "frm-quantitative-analysis-time-series",
    text: "An ARMA(p, q) model combines:",
    optionA: "Autoregressive and moving-average components",
    optionB: "Two moving-average components",
    optionC: "A unit root and a trend",
    optionD: "GARCH and EWMA",
    correctOption: "A",
    explanation: "ARMA(p, q) blends an autoregressive part (AR, order p) with a moving-average part (MA, order q).",
    orderIndex: 9,
  },
  {
    id: "frm-quantitative-analysis-time-series-q11",
    topicId: "frm-quantitative-analysis-time-series",
    text: "The 'I' in an ARIMA model refers to:",
    optionA: "Integration order, i.e., the number of times the series is differenced",
    optionB: "The intercept",
    optionC: "The information ratio",
    optionD: "Instrumental variables",
    correctOption: "A",
    explanation: "ARIMA's 'I' denotes the degree of integration—how many times the series is differenced to achieve stationarity.",
    orderIndex: 10,
  },
  {
    id: "frm-quantitative-analysis-time-series-q12",
    topicId: "frm-quantitative-analysis-time-series",
    text: "Regressing two independent non-stationary series can produce a 'spurious regression', characterized by:",
    optionA: "A low R² and insignificant coefficients",
    optionB: "A high R² and significant coefficients despite no true relationship",
    optionC: "Perfectly stationary residuals",
    optionD: "Zero estimated slope",
    correctOption: "B",
    explanation: "Spurious regression yields a deceptively high R² and significant t-stats between unrelated trending (non-stationary) series; differencing or cointegration analysis is needed.",
    orderIndex: 11,
  },

  // ── Financial Markets: Exchanges, OTC & Central Clearing ──
  {
    id: "frm-financial-markets-market-structure-q01",
    topicId: "frm-financial-markets-market-structure",
    text: "Compared with OTC forwards, exchange-traded futures are:",
    optionA: "Customized and bilaterally cleared",
    optionB: "Standardized and cleared through a central counterparty",
    optionC: "Free of margin requirements",
    optionD: "Subject to higher counterparty credit risk",
    correctOption: "B",
    explanation: "Futures are standardized contracts cleared by a central counterparty (clearinghouse), which sharply reduces counterparty credit risk via margining.",
    orderIndex: 0,
  },
  {
    id: "frm-financial-markets-market-structure-q02",
    topicId: "frm-financial-markets-market-structure",
    text: "Through 'novation', a central counterparty (CCP):",
    optionA: "Eliminates all market risk",
    optionB: "Becomes the buyer to every seller and the seller to every buyer",
    optionC: "Guarantees a profit to members",
    optionD: "Removes the need for margin",
    correctOption: "B",
    explanation: "Novation interposes the CCP between the original parties, making it counterparty to both sides of each cleared trade.",
    orderIndex: 1,
  },
  {
    id: "frm-financial-markets-market-structure-q03",
    topicId: "frm-financial-markets-market-structure",
    text: "Initial margin posted to a CCP is designed primarily to cover:",
    optionA: "Daily realized mark-to-market gains and losses",
    optionB: "Potential future exposure over the close-out period",
    optionC: "The clearing fee",
    optionD: "Dividends owed",
    correctOption: "B",
    explanation: "Initial margin covers potential future exposure—the possible adverse move during the time needed to close out a defaulter's positions—while variation margin settles daily P&L.",
    orderIndex: 2,
  },
  {
    id: "frm-financial-markets-market-structure-q04",
    topicId: "frm-financial-markets-market-structure",
    text: "Variation margin is exchanged to reflect:",
    optionA: "Potential future exposure",
    optionB: "Daily changes in the mark-to-market value of positions",
    optionC: "The default fund contribution",
    optionD: "The CCP's capital",
    correctOption: "B",
    explanation: "Variation margin transfers the daily mark-to-market gains/losses between counterparties, keeping current exposure near zero.",
    orderIndex: 3,
  },
  {
    id: "frm-financial-markets-market-structure-q05",
    topicId: "frm-financial-markets-market-structure",
    text: "In a CCP default waterfall, which resource is typically used FIRST when a member defaults?",
    optionA: "The mutualized default fund of non-defaulting members",
    optionB: "The CCP's own capital ('skin in the game')",
    optionC: "The defaulting member's own margin and default-fund contribution",
    optionD: "Central bank funding",
    correctOption: "C",
    explanation: "The defaulter's own posted margin and default-fund contribution are consumed first, before the CCP's capital and the mutualized fund.",
    orderIndex: 4,
  },
  {
    id: "frm-financial-markets-market-structure-q06",
    topicId: "frm-financial-markets-market-structure",
    text: "A key benefit of central clearing is multilateral netting, which:",
    optionA: "Increases gross exposures",
    optionB: "Reduces total counterparty exposures across members",
    optionC: "Eliminates market risk",
    optionD: "Removes the need for a default fund",
    correctOption: "B",
    explanation: "By netting offsetting positions across all members, a CCP greatly reduces aggregate counterparty exposures compared with bilateral trading.",
    orderIndex: 5,
  },
  {
    id: "frm-financial-markets-market-structure-q07",
    topicId: "frm-financial-markets-market-structure",
    text: "A frequently cited drawback of mandatory central clearing is that CCPs:",
    optionA: "Have no risk management",
    optionB: "Concentrate risk, making a CCP failure potentially systemic",
    optionC: "Increase customization of contracts",
    optionD: "Remove the need for any margin",
    correctOption: "B",
    explanation: "Clearing concentrates exposures in a few CCPs, so a CCP failure could be a systemic event—hence stringent margin and default-fund requirements.",
    orderIndex: 6,
  },
  {
    id: "frm-financial-markets-market-structure-q08",
    topicId: "frm-financial-markets-market-structure",
    text: "Non-centrally-cleared OTC derivatives generally require dealers to compute a ____ to reflect counterparty default risk.",
    optionA: "Credit valuation adjustment (CVA)",
    optionB: "Sharpe ratio",
    optionC: "Duration",
    optionD: "Tracking error",
    correctOption: "A",
    explanation: "Bilateral OTC trades carry counterparty risk, captured via a credit valuation adjustment (CVA) to the derivative's value.",
    orderIndex: 7,
  },
  {
    id: "frm-financial-markets-market-structure-q09",
    topicId: "frm-financial-markets-market-structure",
    text: "The push toward central clearing of standardized OTC derivatives accelerated after:",
    optionA: "The dot-com bust of 2000",
    optionB: "The 2007-2009 global financial crisis",
    optionC: "The 2020 oil price collapse",
    optionD: "The introduction of the euro",
    correctOption: "B",
    explanation: "Post-2008 reforms (e.g., Dodd-Frank, EMIR) mandated central clearing of standardized OTC derivatives to reduce systemic counterparty risk.",
    orderIndex: 8,
  },
  {
    id: "frm-financial-markets-market-structure-q10",
    topicId: "frm-financial-markets-market-structure",
    text: "Relative to exchange-traded contracts, OTC contracts offer the advantage of:",
    optionA: "Greater standardization",
    optionB: "Customization of terms to the counterparties' needs",
    optionC: "Zero counterparty risk",
    optionD: "Daily settlement through a clearinghouse",
    correctOption: "B",
    explanation: "OTC contracts can be tailored (notional, maturity, underlying) to specific hedging needs, unlike standardized exchange contracts.",
    orderIndex: 9,
  },
  {
    id: "frm-financial-markets-market-structure-q11",
    topicId: "frm-financial-markets-market-structure",
    text: "The CCP 'guarantee fund' (default fund) is primarily funded by:",
    optionA: "Taxpayers",
    optionB: "Contributions from clearing members",
    optionC: "The central bank",
    optionD: "Retail investors",
    correctOption: "B",
    explanation: "Clearing members contribute to a mutualized default (guarantee) fund that can absorb losses exceeding a defaulter's own resources.",
    orderIndex: 10,
  },
  {
    id: "frm-financial-markets-market-structure-q12",
    topicId: "frm-financial-markets-market-structure",
    text: "'Wrong-way risk' in a bilateral OTC trade arises when:",
    optionA: "Exposure to a counterparty rises as that counterparty's credit quality deteriorates",
    optionB: "Margin is posted daily",
    optionC: "The trade is centrally cleared",
    optionD: "Volatility is constant",
    correctOption: "A",
    explanation: "Wrong-way risk is the adverse correlation where exposure increases just as the counterparty becomes more likely to default.",
    orderIndex: 11,
  },

  // ── Valuation/Risk Models: Volatility Smiles ──
  {
    id: "frm-valuation-risk-models-volatility-smiles-q01",
    topicId: "frm-valuation-risk-models-volatility-smiles",
    text: "The existence of a volatility smile indicates that the Black-Scholes assumption of:",
    optionA: "Constant volatility across strikes does not hold in practice",
    optionB: "A risk-free rate is incorrect",
    optionC: "European exercise is invalid",
    optionD: "Zero dividends is required",
    correctOption: "A",
    explanation: "A smile shows implied volatility varies with strike, contradicting Black-Scholes' single constant-volatility assumption.",
    orderIndex: 0,
  },
  {
    id: "frm-valuation-risk-models-volatility-smiles-q02",
    topicId: "frm-valuation-risk-models-volatility-smiles",
    text: "Equity index options typically exhibit a volatility 'skew' in which implied volatility is:",
    optionA: "Higher for high-strike (OTM call) options",
    optionB: "Higher for low-strike (OTM put) options",
    optionC: "Identical across all strikes",
    optionD: "Zero at the money",
    correctOption: "B",
    explanation: "Equity options show a skew/smirk with higher implied vol at low strikes, reflecting crash fear and the leverage effect.",
    orderIndex: 1,
  },
  {
    id: "frm-valuation-risk-models-volatility-smiles-q03",
    topicId: "frm-valuation-risk-models-volatility-smiles",
    text: "A symmetric volatility smile (high IV at both wings) is most characteristic of which market?",
    optionA: "Equity index options",
    optionB: "Currency (FX) options",
    optionC: "Single-stock options only",
    optionD: "Zero-coupon bonds",
    correctOption: "B",
    explanation: "FX options often show a roughly symmetric smile because large moves are plausible in both directions, implying fat tails on both sides.",
    orderIndex: 2,
  },
  {
    id: "frm-valuation-risk-models-volatility-smiles-q04",
    topicId: "frm-valuation-risk-models-volatility-smiles",
    text: "A volatility smile implies that the market's risk-neutral distribution of the underlying has:",
    optionA: "Thinner tails than the lognormal",
    optionB: "Fatter tails than the lognormal",
    optionC: "Zero variance",
    optionD: "No skewness or kurtosis",
    correctOption: "B",
    explanation: "Higher implied vols in the wings price greater probability of extreme moves, implying fatter tails than the Black-Scholes lognormal.",
    orderIndex: 3,
  },
  {
    id: "frm-valuation-risk-models-volatility-smiles-q05",
    topicId: "frm-valuation-risk-models-volatility-smiles",
    text: "A volatility surface plots implied volatility against:",
    optionA: "Strike and time to maturity",
    optionB: "Delta and gamma",
    optionC: "Price and volume",
    optionD: "Interest rate and dividend yield",
    correctOption: "A",
    explanation: "The volatility surface shows implied volatility as a function of both strike (moneyness) and maturity.",
    orderIndex: 4,
  },
  {
    id: "frm-valuation-risk-models-volatility-smiles-q06",
    topicId: "frm-valuation-risk-models-volatility-smiles",
    text: "The equity volatility skew is often attributed to the 'leverage effect', whereby a fall in equity price:",
    optionA: "Decreases the firm's leverage and volatility",
    optionB: "Increases the firm's leverage and thus volatility",
    optionC: "Has no effect on volatility",
    optionD: "Increases dividends",
    correctOption: "B",
    explanation: "As equity prices fall, financial leverage rises, raising equity volatility—contributing to higher implied vol at lower strikes.",
    orderIndex: 5,
  },
  {
    id: "frm-valuation-risk-models-volatility-smiles-q07",
    topicId: "frm-valuation-risk-models-volatility-smiles",
    text: "Volatility smiles tend to become ____ as option maturity increases.",
    optionA: "Steeper",
    optionB: "Flatter",
    optionC: "Inverted",
    optionD: "Undefined",
    correctOption: "B",
    explanation: "Smiles generally flatten with longer maturities, as relative differences in implied vol across strikes diminish.",
    orderIndex: 6,
  },
  {
    id: "frm-valuation-risk-models-volatility-smiles-q08",
    topicId: "frm-valuation-risk-models-volatility-smiles",
    text: "Pricing a deep out-of-the-money option with a single at-the-money implied volatility would most likely:",
    optionA: "Correctly price the option",
    optionB: "Misprice it because the smile assigns wings a different volatility",
    optionC: "Always overprice it",
    optionD: "Eliminate the need for the smile",
    correctOption: "B",
    explanation: "Because the smile gives wing strikes different implied vols, using a flat ATM vol misprices OTM/ITM options.",
    orderIndex: 7,
  },
  {
    id: "frm-valuation-risk-models-volatility-smiles-q09",
    topicId: "frm-valuation-risk-models-volatility-smiles",
    text: "Empirically, the appearance of pronounced equity volatility skews became prominent after:",
    optionA: "The 1987 stock market crash",
    optionB: "The introduction of the euro",
    optionC: "The 2000 dot-com peak only",
    optionD: "There has never been a skew",
    correctOption: "A",
    explanation: "Persistent equity skews emerged after the 1987 crash heightened market awareness of large downside moves.",
    orderIndex: 8,
  },
  {
    id: "frm-valuation-risk-models-volatility-smiles-q10",
    topicId: "frm-valuation-risk-models-volatility-smiles",
    text: "Jumps and stochastic volatility in the underlying help explain volatility smiles because they create:",
    optionA: "A perfectly lognormal distribution",
    optionB: "Heavier tails and skewness not captured by constant-volatility Black-Scholes",
    optionC: "Zero implied volatility",
    optionD: "Negative option prices",
    correctOption: "B",
    explanation: "Jump and stochastic-volatility dynamics produce fat tails/skew, generating the implied-volatility patterns observed as smiles/skews.",
    orderIndex: 9,
  },
  {
    id: "frm-valuation-risk-models-volatility-smiles-q11",
    topicId: "frm-valuation-risk-models-volatility-smiles",
    text: "Implied volatility extracted from the smile is best described as:",
    optionA: "A backward-looking historical estimate",
    optionB: "The market's forward-looking volatility expectation embedded in option prices",
    optionC: "Always equal to realized volatility",
    optionD: "Independent of option prices",
    correctOption: "B",
    explanation: "Implied volatility is derived from current option prices and reflects the market's forward-looking volatility expectation.",
    orderIndex: 10,
  },
  {
    id: "frm-valuation-risk-models-volatility-smiles-q12",
    topicId: "frm-valuation-risk-models-volatility-smiles",
    text: "A trader observing a steep put skew in equity options would infer the market is pricing in:",
    optionA: "A high probability of large upside moves",
    optionB: "A high probability of large downside moves",
    optionC: "No directional bias",
    optionD: "Zero volatility",
    correctOption: "B",
    explanation: "A steep put (low-strike) skew indicates elevated demand/pricing for downside protection, i.e., greater perceived crash risk.",
    orderIndex: 11,
  },

  // ── Market Risk: Risk Factor Mapping ──
  {
    id: "frm-market-risk-risk-factor-mapping-q01",
    topicId: "frm-market-risk-risk-factor-mapping",
    text: "The primary purpose of mapping positions to risk factors is to:",
    optionA: "Increase the number of instruments tracked",
    optionB: "Reduce dimensionality so VaR can be computed across a large portfolio",
    optionC: "Eliminate market risk",
    optionD: "Avoid using a covariance matrix",
    correctOption: "B",
    explanation: "Risk mapping expresses many positions in terms of a manageable set of standardized factors, enabling tractable portfolio VaR.",
    orderIndex: 0,
  },
  {
    id: "frm-market-risk-risk-factor-mapping-q02",
    topicId: "frm-market-risk-risk-factor-mapping",
    text: "Which fixed-income mapping method is generally the MOST accurate?",
    optionA: "Principal (notional) mapping",
    optionB: "Duration mapping",
    optionC: "Cash-flow mapping",
    optionD: "Random mapping",
    correctOption: "C",
    explanation: "Cash-flow mapping allocates each cash flow to adjacent vertices while preserving market value and risk, making it the most accurate of the three.",
    orderIndex: 1,
  },
  {
    id: "frm-market-risk-risk-factor-mapping-q03",
    topicId: "frm-market-risk-risk-factor-mapping",
    text: "Principal mapping of a coupon bond to a single zero-coupon position at its maturity is considered:",
    optionA: "The most precise method",
    optionB: "A crude approximation that ignores intermediate cash flows",
    optionC: "Equivalent to cash-flow mapping",
    optionD: "Only valid for zero-coupon bonds",
    correctOption: "B",
    explanation: "Principal mapping ignores the bond's coupons, mapping only the notional at final maturity—a crude approach.",
    orderIndex: 2,
  },
  {
    id: "frm-market-risk-risk-factor-mapping-q04",
    topicId: "frm-market-risk-risk-factor-mapping",
    text: "Duration mapping represents a bond by a single zero-coupon bond whose maturity equals the bond's:",
    optionA: "Coupon rate",
    optionB: "Duration",
    optionC: "Yield to maturity",
    optionD: "Face value",
    correctOption: "B",
    explanation: "Duration mapping uses one zero whose maturity matches the bond's duration to approximate its interest-rate sensitivity.",
    orderIndex: 3,
  },
  {
    id: "frm-market-risk-risk-factor-mapping-q05",
    topicId: "frm-market-risk-risk-factor-mapping",
    text: "For options, delta-normal (linear) VaR tends to:",
    optionA: "Perfectly capture option risk",
    optionB: "Understate risk because it ignores non-linearity (gamma)",
    optionC: "Overstate risk for all options",
    optionD: "Be unaffected by the underlying's volatility",
    correctOption: "B",
    explanation: "The delta-normal method linearizes the option, missing the convexity (gamma) of payoffs and so typically understating risk.",
    orderIndex: 4,
  },
  {
    id: "frm-market-risk-risk-factor-mapping-q06",
    topicId: "frm-market-risk-risk-factor-mapping",
    text: "A foreign-currency forward can be mapped (decomposed) into:",
    optionA: "A single equity position",
    optionB: "Spot FX plus a foreign and a domestic interest-rate (bill) position",
    optionC: "Only a commodity position",
    optionD: "A credit default swap",
    correctOption: "B",
    explanation: "An FX forward decomposes into a spot FX exposure and offsetting domestic and foreign money-market (bill) positions.",
    orderIndex: 5,
  },
  {
    id: "frm-market-risk-risk-factor-mapping-q07",
    topicId: "frm-market-risk-risk-factor-mapping",
    text: "A drawback of risk-factor mapping is that it can introduce:",
    optionA: "Lower computational efficiency",
    optionB: "Basis/specific risk not captured by the chosen factors",
    optionC: "Perfect hedging",
    optionD: "Elimination of all model risk",
    correctOption: "B",
    explanation: "Reducing positions to standard factors leaves residual basis or specific risk that the selected factors do not represent.",
    orderIndex: 6,
  },
  {
    id: "frm-market-risk-risk-factor-mapping-q08",
    topicId: "frm-market-risk-risk-factor-mapping",
    text: "Component (or marginal) VaR obtained after mapping is useful because it:",
    optionA: "Sums to more than total VaR",
    optionB: "Attributes total portfolio VaR to individual positions/factors",
    optionC: "Ignores diversification",
    optionD: "Equals undiversified VaR",
    correctOption: "B",
    explanation: "Component VaR decomposes diversified portfolio VaR into additive contributions from each position or factor.",
    orderIndex: 7,
  },
  {
    id: "frm-market-risk-risk-factor-mapping-q09",
    topicId: "frm-market-risk-risk-factor-mapping",
    text: "Cash-flow mapping splits a cash flow falling between two standard vertices so as to preserve the position's:",
    optionA: "Coupon rate only",
    optionB: "Market value and risk (variance)",
    optionC: "Credit rating",
    optionD: "Maturity exactly",
    correctOption: "B",
    explanation: "Cash-flow mapping allocates the flow across adjacent vertices to keep both present value and risk (variance) unchanged.",
    orderIndex: 8,
  },
  {
    id: "frm-market-risk-risk-factor-mapping-q10",
    topicId: "frm-market-risk-risk-factor-mapping",
    text: "Mapping is a prerequisite for building which key input to parametric VaR?",
    optionA: "The factor covariance (correlation) matrix",
    optionB: "The income statement",
    optionC: "A binomial tree",
    optionD: "A credit migration matrix",
    correctOption: "A",
    explanation: "Once positions are expressed as factor exposures, a factor covariance matrix combines them to compute diversified parametric VaR.",
    orderIndex: 9,
  },
  {
    id: "frm-market-risk-risk-factor-mapping-q11",
    topicId: "frm-market-risk-risk-factor-mapping",
    text: "For an option position, capturing risk more accurately than delta-normal requires adding:",
    optionA: "Only the risk-free rate",
    optionB: "Gamma and vega adjustments",
    optionC: "The dividend yield only",
    optionD: "The coupon",
    correctOption: "B",
    explanation: "Incorporating gamma (convexity) and vega (volatility sensitivity) improves on the linear delta-normal approximation for options.",
    orderIndex: 10,
  },
  {
    id: "frm-market-risk-risk-factor-mapping-q12",
    topicId: "frm-market-risk-risk-factor-mapping",
    text: "A trade-off in choosing the number of risk factors is that more factors:",
    optionA: "Always reduce accuracy",
    optionB: "Improve accuracy but increase estimation burden and noise",
    optionC: "Eliminate basis risk completely with no cost",
    optionD: "Reduce computational load",
    correctOption: "B",
    explanation: "Adding factors can capture more risk but raises the burden of estimating a larger covariance matrix and introduces more estimation noise.",
    orderIndex: 11,
  },

  // ── Credit Risk: Merton Model ──
  {
    id: "frm-credit-risk-merton-model-q01",
    topicId: "frm-credit-risk-merton-model",
    text: "In the Merton model, a firm's equity is modeled as a:",
    optionA: "Put option on the firm's assets",
    optionB: "Call option on the firm's assets struck at the face value of debt",
    optionC: "Risk-free bond",
    optionD: "Forward contract on debt",
    correctOption: "B",
    explanation: "Equity holders receive assets minus debt if assets exceed debt at maturity, so equity is a call option on firm assets with strike equal to the debt's face value.",
    orderIndex: 0,
  },
  {
    id: "frm-credit-risk-merton-model-q02",
    topicId: "frm-credit-risk-merton-model",
    text: "Under the Merton model, default occurs when, at debt maturity:",
    optionA: "Asset value exceeds the face value of debt",
    optionB: "Asset value falls below the face value of debt",
    optionC: "Equity volatility is zero",
    optionD: "The risk-free rate rises",
    correctOption: "B",
    explanation: "Default is triggered if the firm's asset value at maturity is below the face value of its debt, so debt cannot be fully repaid.",
    orderIndex: 1,
  },
  {
    id: "frm-credit-risk-merton-model-q03",
    topicId: "frm-credit-risk-merton-model",
    text: "Risky corporate debt in the Merton framework can be expressed as:",
    optionA: "Risk-free debt plus a call on assets",
    optionB: "Risk-free debt minus a put on the firm's assets",
    optionC: "Equity plus a forward",
    optionD: "A risk-free bond only",
    correctOption: "B",
    explanation: "Holding risky debt equals holding risk-free debt and being short a put on the assets (the shareholders' option to default).",
    orderIndex: 2,
  },
  {
    id: "frm-credit-risk-merton-model-q04",
    topicId: "frm-credit-risk-merton-model",
    text: "All else equal, an increase in the firm's asset volatility will:",
    optionA: "Decrease the probability of default",
    optionB: "Increase the probability of default and the value of equity's default option",
    optionC: "Have no effect on default probability",
    optionD: "Eliminate credit risk",
    correctOption: "B",
    explanation: "Higher asset volatility raises the chance assets fall below debt, increasing default probability and the value of the embedded default option to equity.",
    orderIndex: 3,
  },
  {
    id: "frm-credit-risk-merton-model-q05",
    topicId: "frm-credit-risk-merton-model",
    text: "Distance to default (DD) measures the number of standard deviations the firm's asset value is from the:",
    optionA: "Risk-free rate",
    optionB: "Default threshold (debt level)",
    optionC: "Equity market index",
    optionD: "Dividend payment",
    correctOption: "B",
    explanation: "DD expresses how many standard deviations of asset value separate the expected asset value from the default point (debt level).",
    orderIndex: 4,
  },
  {
    id: "frm-credit-risk-merton-model-q06",
    topicId: "frm-credit-risk-merton-model",
    text: "A higher distance to default implies:",
    optionA: "A higher probability of default",
    optionB: "A lower probability of default",
    optionC: "Zero recovery",
    optionD: "Higher leverage",
    correctOption: "B",
    explanation: "The greater the distance to default, the lower the modeled probability of default (PD = N(−DD)).",
    orderIndex: 5,
  },
  {
    id: "frm-credit-risk-merton-model-q07",
    topicId: "frm-credit-risk-merton-model",
    text: "Increasing a firm's leverage (higher face value of debt) will, in the Merton model:",
    optionA: "Lower the distance to default",
    optionB: "Raise the distance to default",
    optionC: "Leave default probability unchanged",
    optionD: "Eliminate equity value",
    correctOption: "A",
    explanation: "More debt raises the default threshold, reducing the distance to default and increasing default probability.",
    orderIndex: 6,
  },
  {
    id: "frm-credit-risk-merton-model-q08",
    topicId: "frm-credit-risk-merton-model",
    text: "A practical challenge in applying the Merton model is that:",
    optionA: "Equity prices are never observable",
    optionB: "The firm's asset value and asset volatility are not directly observable",
    optionC: "Debt has no face value",
    optionD: "Volatility does not affect option values",
    correctOption: "B",
    explanation: "Asset value and asset volatility must be inferred (e.g., from equity value and equity volatility) because they are not directly observable.",
    orderIndex: 7,
  },
  {
    id: "frm-credit-risk-merton-model-q09",
    topicId: "frm-credit-risk-merton-model",
    text: "The commercial KMV/Moody's 'expected default frequency' (EDF) model is built on the:",
    optionA: "Reduced-form (intensity) approach",
    optionB: "Merton structural approach",
    optionC: "CAPM",
    optionD: "Pure historical average default rates",
    correctOption: "B",
    explanation: "KMV/Moody's EDF is a structural model derived from Merton's framework, mapping distance to default to empirical default frequencies.",
    orderIndex: 8,
  },
  {
    id: "frm-credit-risk-merton-model-q10",
    topicId: "frm-credit-risk-merton-model",
    text: "A criticism of the basic Merton model is that it assumes default can occur:",
    optionA: "At any time before maturity",
    optionB: "Only at the debt's maturity date",
    optionC: "Never",
    optionD: "Only when equity is zero for a year",
    correctOption: "B",
    explanation: "The basic Merton model permits default only at the single debt-maturity date; first-passage/structural extensions allow default before maturity.",
    orderIndex: 9,
  },
  {
    id: "frm-credit-risk-merton-model-q11",
    topicId: "frm-credit-risk-merton-model",
    text: "The Merton model tends to underestimate credit spreads for:",
    optionA: "Very long maturities",
    optionB: "Very short maturities",
    optionC: "Risk-free bonds",
    optionD: "All maturities equally",
    correctOption: "B",
    explanation: "Because near-term default is nearly impossible when assets currently exceed debt, the basic model produces unrealistically low short-maturity spreads.",
    orderIndex: 10,
  },
  {
    id: "frm-credit-risk-merton-model-q12",
    topicId: "frm-credit-risk-merton-model",
    text: "A key advantage of the Merton (structural) approach is that it:",
    optionA: "Requires no assumptions about asset dynamics",
    optionB: "Links default to market-based measures of firm value and volatility",
    optionC: "Ignores leverage",
    optionD: "Uses only accounting book values",
    correctOption: "B",
    explanation: "The structural approach ties default risk to forward-looking, market-based asset value and volatility rather than backward-looking accounting data alone.",
    orderIndex: 11,
  },

  // ── Operational Risk: External Loss Data & Scenario Analysis ──
  {
    id: "frm-operational-risk-scenario-analysis-op-q01",
    topicId: "frm-operational-risk-scenario-analysis-op",
    text: "A primary reason banks supplement internal operational loss data with external loss data is to:",
    optionA: "Reduce the number of risk categories",
    optionB: "Capture rare, severe tail events the firm has not itself experienced",
    optionC: "Avoid scenario analysis",
    optionD: "Lower the confidence level used",
    correctOption: "B",
    explanation: "External data provides information on infrequent, high-severity events absent from a single firm's own history, improving tail estimation.",
    orderIndex: 0,
  },
  {
    id: "frm-operational-risk-scenario-analysis-op-q02",
    topicId: "frm-operational-risk-scenario-analysis-op",
    text: "Consortium operational loss databases (e.g., ORX) are characterized by:",
    optionA: "Public news reports only",
    optionB: "Member banks pooling their internal losses",
    optionC: "Regulator-published fines only",
    optionD: "Simulated data",
    correctOption: "B",
    explanation: "Consortium databases aggregate anonymized internal loss data contributed by member institutions.",
    orderIndex: 1,
  },
  {
    id: "frm-operational-risk-scenario-analysis-op-q03",
    topicId: "frm-operational-risk-scenario-analysis-op",
    text: "Publicly sourced (news-based) external loss data suffers from a notable bias because it:",
    optionA: "Includes too many small losses",
    optionB: "Over-represents very large, newsworthy losses (reporting bias)",
    optionC: "Is always perfectly scaled",
    optionD: "Excludes all large losses",
    correctOption: "B",
    explanation: "Public data is subject to reporting bias—only large, attention-grabbing losses get reported—so it skews toward severe events.",
    orderIndex: 2,
  },
  {
    id: "frm-operational-risk-scenario-analysis-op-q04",
    topicId: "frm-operational-risk-scenario-analysis-op",
    text: "Before combining external loss data with internal data, the external data should be:",
    optionA: "Used unadjusted",
    optionB: "Scaled to the firm's size and business mix",
    optionC: "Discarded",
    optionD: "Converted into market risk factors",
    correctOption: "B",
    explanation: "External losses must be scaled/adjusted to reflect the firm's scale and activities, and corrected for collection thresholds and biases.",
    orderIndex: 3,
  },
  {
    id: "frm-operational-risk-scenario-analysis-op-q05",
    topicId: "frm-operational-risk-scenario-analysis-op",
    text: "A key strength of scenario analysis for operational risk is that it is:",
    optionA: "Purely objective and data-driven",
    optionB: "Forward-looking and can capture risks absent from historical data",
    optionC: "Free of behavioral bias",
    optionD: "Independent of expert judgment",
    correctOption: "B",
    explanation: "Scenario analysis is forward-looking and can incorporate plausible severe events that have never occurred in the firm's history.",
    orderIndex: 4,
  },
  {
    id: "frm-operational-risk-scenario-analysis-op-q06",
    topicId: "frm-operational-risk-scenario-analysis-op",
    text: "A major weakness of scenario analysis is that estimates are:",
    optionA: "Always too conservative",
    optionB: "Subjective and prone to behavioral biases such as anchoring and availability",
    optionC: "Based solely on market prices",
    optionD: "Impossible to govern",
    correctOption: "B",
    explanation: "Because scenarios rely on expert judgment, they are subjective and susceptible to biases like anchoring and availability, requiring strong governance and challenge.",
    orderIndex: 5,
  },
  {
    id: "frm-operational-risk-scenario-analysis-op-q07",
    topicId: "frm-operational-risk-scenario-analysis-op",
    text: "An operational risk loss distribution is typically constructed by combining a:",
    optionA: "Frequency distribution and a severity distribution",
    optionB: "Duration and a convexity measure",
    optionC: "Spot and a forward curve",
    optionD: "Beta and an alpha",
    correctOption: "A",
    explanation: "The loss distribution approach convolves a frequency (number of events) distribution with a severity (loss size) distribution to estimate aggregate losses.",
    orderIndex: 6,
  },
  {
    id: "frm-operational-risk-scenario-analysis-op-q08",
    topicId: "frm-operational-risk-scenario-analysis-op",
    text: "AMA-style operational risk frameworks blend internal data, external data, scenario analysis, and:",
    optionA: "Business-environment and internal-control factors (BEICFs)",
    optionB: "Equity market betas",
    optionC: "Interest-rate term structures",
    optionD: "Currency parity conditions",
    correctOption: "A",
    explanation: "The four AMA elements are internal loss data, external loss data, scenario analysis, and business-environment & internal-control factors (BEICFs).",
    orderIndex: 7,
  },
  {
    id: "frm-operational-risk-scenario-analysis-op-q09",
    topicId: "frm-operational-risk-scenario-analysis-op",
    text: "Operational risk economic capital is usually estimated at a very high confidence level, such as:",
    optionA: "50%",
    optionB: "90%",
    optionC: "99.9%",
    optionD: "75%",
    correctOption: "C",
    explanation: "Operational risk capital is typically derived at a high confidence level (e.g., 99.9% over one year) to cover extreme tail losses.",
    orderIndex: 8,
  },
  {
    id: "frm-operational-risk-scenario-analysis-op-q10",
    topicId: "frm-operational-risk-scenario-analysis-op",
    text: "When building the aggregate loss distribution, scenario analysis is most valuable for modeling the:",
    optionA: "Body (frequent small losses)",
    optionB: "Tail (rare severe losses)",
    optionC: "Risk-free rate",
    optionD: "Mean of small losses only",
    correctOption: "B",
    explanation: "Internal data populates the body of frequent losses, while scenarios (and external data) inform the sparse tail of severe events.",
    orderIndex: 9,
  },
  {
    id: "frm-operational-risk-scenario-analysis-op-q11",
    topicId: "frm-operational-risk-scenario-analysis-op",
    text: "A collection 'threshold' in loss data means that:",
    optionA: "All losses of every size are recorded",
    optionB: "Losses below a minimum amount are not recorded, truncating the data",
    optionC: "Only losses above the 99th percentile count",
    optionD: "Data is recorded only annually",
    correctOption: "B",
    explanation: "Loss databases often record only losses above a minimum threshold, truncating small losses—an effect that must be accounted for when fitting distributions.",
    orderIndex: 10,
  },
  {
    id: "frm-operational-risk-scenario-analysis-op-q12",
    topicId: "frm-operational-risk-scenario-analysis-op",
    text: "Good governance of scenario analysis includes:",
    optionA: "Accepting all expert estimates without review",
    optionB: "Independent challenge and documentation of assumptions",
    optionC: "Using only a single expert's view",
    optionD: "Excluding senior management entirely",
    correctOption: "B",
    explanation: "Robust scenario processes require independent challenge, documented assumptions, and oversight to mitigate the subjectivity and bias of expert estimates.",
    orderIndex: 11,
  },

  // ── Liquidity Risk: Liquidity-Adjusted VaR ──
  {
    id: "frm-liquidity-risk-lvar-q01",
    topicId: "frm-liquidity-risk-lvar",
    text: "Liquidity-adjusted VaR (LVaR) improves on standard VaR by incorporating:",
    optionA: "The credit rating of the issuer",
    optionB: "The cost of liquidating the position",
    optionC: "The risk-free rate only",
    optionD: "Dividend payments",
    correctOption: "B",
    explanation: "LVaR augments market VaR with the cost of exiting a position, which standard VaR ignores.",
    orderIndex: 0,
  },
  {
    id: "frm-liquidity-risk-lvar-q02",
    topicId: "frm-liquidity-risk-lvar",
    text: "Using the constant bid-ask spread approach, the liquidity cost add-on for a position of value P with proportional spread s is:",
    optionA: "P × s",
    optionB: "½ × P × s",
    optionC: "2 × P × s",
    optionD: "P / s",
    correctOption: "B",
    explanation: "The one-way liquidation cost is half the round-trip spread: ½ × P × s, which is added to VaR.",
    orderIndex: 1,
  },
  {
    id: "frm-liquidity-risk-lvar-q03",
    topicId: "frm-liquidity-risk-lvar",
    text: "Liquidity risk in LVaR is commonly decomposed into which two components?",
    optionA: "Credit and operational",
    optionB: "Bid-ask (transaction cost) and market-impact (price impact)",
    optionC: "Duration and convexity",
    optionD: "Systematic and idiosyncratic",
    correctOption: "B",
    explanation: "LVaR distinguishes exogenous bid-ask spread costs from endogenous market-impact costs of large trades.",
    orderIndex: 2,
  },
  {
    id: "frm-liquidity-risk-lvar-q04",
    topicId: "frm-liquidity-risk-lvar",
    text: "The 'endogenous' component of liquidity risk refers to the fact that:",
    optionA: "Spreads are always constant",
    optionB: "Large trades move the market price against the trader",
    optionC: "Liquidity never changes",
    optionD: "Only small trades have costs",
    correctOption: "B",
    explanation: "Endogenous (price-impact) liquidity risk arises because executing a large position pushes the price adversely, beyond the quoted spread.",
    orderIndex: 3,
  },
  {
    id: "frm-liquidity-risk-lvar-q05",
    topicId: "frm-liquidity-risk-lvar",
    text: "Accounting for uncertain (volatile) bid-ask spreads in LVaR involves adding a multiple of the spread's:",
    optionA: "Mean only",
    optionB: "Standard deviation (volatility)",
    optionC: "Median",
    optionD: "Skewness",
    correctOption: "B",
    explanation: "With stochastic spreads, the add-on uses ½·P·(mean spread + k·spread volatility), where k reflects the confidence level.",
    orderIndex: 4,
  },
  {
    id: "frm-liquidity-risk-lvar-q06",
    topicId: "frm-liquidity-risk-lvar",
    text: "Lengthening the assumed liquidation horizon scales market VaR approximately by:",
    optionA: "The horizon itself",
    optionB: "The square root of the horizon",
    optionC: "The square of the horizon",
    optionD: "Zero",
    correctOption: "B",
    explanation: "Under the square-root-of-time rule, VaR scales with the square root of the holding/liquidation horizon.",
    orderIndex: 5,
  },
  {
    id: "frm-liquidity-risk-lvar-q07",
    topicId: "frm-liquidity-risk-lvar",
    text: "Optimal execution strategies balance market-impact cost against:",
    optionA: "Dividend risk",
    optionB: "Price risk from holding the position longer",
    optionC: "Credit migration",
    optionD: "Inflation",
    correctOption: "B",
    explanation: "Trading quickly raises market-impact costs; trading slowly raises exposure to price moves—optimal execution balances the two.",
    orderIndex: 6,
  },
  {
    id: "frm-liquidity-risk-lvar-q08",
    topicId: "frm-liquidity-risk-lvar",
    text: "A position worth $10 million has a proportional bid-ask spread of 0.4%. The bid-ask liquidity cost add-on is:",
    optionA: "$40,000",
    optionB: "$20,000",
    optionC: "$4,000",
    optionD: "$80,000",
    correctOption: "B",
    explanation: "½ × $10,000,000 × 0.004 = $20,000.",
    orderIndex: 7,
  },
  {
    id: "frm-liquidity-risk-lvar-q09",
    topicId: "frm-liquidity-risk-lvar",
    text: "Liquidity add-ons should be stressed because, in market turmoil, bid-ask spreads tend to:",
    optionA: "Narrow sharply",
    optionB: "Widen sharply, often when VaR is also high",
    optionC: "Stay constant",
    optionD: "Become negative",
    correctOption: "B",
    explanation: "Liquidity evaporates in stress: spreads widen exactly when market losses (VaR) are largest, so LVaR add-ons should reflect stressed conditions.",
    orderIndex: 8,
  },
  {
    id: "frm-liquidity-risk-lvar-q10",
    topicId: "frm-liquidity-risk-lvar",
    text: "The exogenous spread cost component is independent of:",
    optionA: "The quoted bid-ask spread",
    optionB: "The size of the trader's own position",
    optionC: "The mid price",
    optionD: "The position value",
    correctOption: "B",
    explanation: "Exogenous (bid-ask) cost depends on market-quoted spreads, not on the trader's own position size; position size drives the endogenous (impact) component.",
    orderIndex: 9,
  },
  {
    id: "frm-liquidity-risk-lvar-q11",
    topicId: "frm-liquidity-risk-lvar",
    text: "Adding a positive liquidity cost to market VaR means LVaR is always:",
    optionA: "Less than market VaR",
    optionB: "Greater than or equal to market VaR",
    optionC: "Equal to zero",
    optionD: "Independent of VaR",
    correctOption: "B",
    explanation: "Because the liquidity cost add-on is non-negative, LVaR is at least as large as the underlying market VaR.",
    orderIndex: 10,
  },
  {
    id: "frm-liquidity-risk-lvar-q12",
    topicId: "frm-liquidity-risk-lvar",
    text: "A highly liquid, large-cap equity position relative to an illiquid small-cap one will generally have a:",
    optionA: "Larger liquidity cost add-on",
    optionB: "Smaller liquidity cost add-on",
    optionC: "Identical liquidity cost add-on",
    optionD: "Negative liquidity cost add-on",
    correctOption: "B",
    explanation: "Liquid positions have tighter spreads and less price impact, so their liquidity cost add-on is smaller than for illiquid positions.",
    orderIndex: 11,
  },

  // ── Investment Risk: Performance Measurement ──
  {
    id: "frm-investment-risk-performance-measurement-q01",
    topicId: "frm-investment-risk-performance-measurement",
    text: "The Sharpe ratio measures excess return per unit of:",
    optionA: "Beta",
    optionB: "Total volatility (standard deviation)",
    optionC: "Downside deviation",
    optionD: "Tracking error",
    correctOption: "B",
    explanation: "The Sharpe ratio is (portfolio return − risk-free rate) divided by the portfolio's total standard deviation.",
    orderIndex: 0,
  },
  {
    id: "frm-investment-risk-performance-measurement-q02",
    topicId: "frm-investment-risk-performance-measurement",
    text: "The Treynor ratio differs from the Sharpe ratio by using which risk measure in the denominator?",
    optionA: "Beta (systematic risk)",
    optionB: "Total volatility",
    optionC: "Downside deviation",
    optionD: "Value at risk",
    correctOption: "A",
    explanation: "The Treynor ratio divides excess return by beta, making it appropriate for evaluating a well-diversified sub-portfolio.",
    orderIndex: 1,
  },
  {
    id: "frm-investment-risk-performance-measurement-q03",
    topicId: "frm-investment-risk-performance-measurement",
    text: "The Sortino ratio improves on the Sharpe ratio for asymmetric return profiles by penalizing only:",
    optionA: "Upside volatility",
    optionB: "Downside (below-target) deviation",
    optionC: "Systematic risk",
    optionD: "Tracking error",
    correctOption: "B",
    explanation: "The Sortino ratio uses downside deviation relative to a target return, so it does not penalize favorable upside volatility.",
    orderIndex: 2,
  },
  {
    id: "frm-investment-risk-performance-measurement-q04",
    topicId: "frm-investment-risk-performance-measurement",
    text: "The information ratio is defined as active return divided by:",
    optionA: "Beta",
    optionB: "Tracking error (active risk)",
    optionC: "Total volatility",
    optionD: "The risk-free rate",
    correctOption: "B",
    explanation: "The information ratio = (portfolio return − benchmark return) / tracking error, measuring active return per unit of active risk.",
    orderIndex: 3,
  },
  {
    id: "frm-investment-risk-performance-measurement-q05",
    topicId: "frm-investment-risk-performance-measurement",
    text: "Jensen's alpha measures a portfolio's return in excess of that predicted by:",
    optionA: "The dividend discount model",
    optionB: "The CAPM (given the portfolio's beta)",
    optionC: "Purchasing power parity",
    optionD: "The Sortino target",
    correctOption: "B",
    explanation: "Jensen's alpha = portfolio return − [R_f + β(R_m − R_f)], the excess over the CAPM-required return.",
    orderIndex: 4,
  },
  {
    id: "frm-investment-risk-performance-measurement-q06",
    topicId: "frm-investment-risk-performance-measurement",
    text: "A portfolio returns 11% with volatility 20%; the risk-free rate is 3%. Its Sharpe ratio is:",
    optionA: "0.55",
    optionB: "0.40",
    optionC: "0.70",
    optionD: "0.80",
    correctOption: "B",
    explanation: "Sharpe = (11% − 3%) / 20% = 8 / 20 = 0.40.",
    orderIndex: 5,
  },
  {
    id: "frm-investment-risk-performance-measurement-q07",
    topicId: "frm-investment-risk-performance-measurement",
    text: "The Sharpe ratio is the preferred measure when evaluating:",
    optionA: "A single security within a larger portfolio",
    optionB: "An investor's entire (total) portfolio",
    optionC: "Only fixed-income securities",
    optionD: "Active managers versus a benchmark",
    correctOption: "B",
    explanation: "Because it uses total risk, the Sharpe ratio is most appropriate for an investor's overall portfolio where total volatility matters.",
    orderIndex: 6,
  },
  {
    id: "frm-investment-risk-performance-measurement-q08",
    topicId: "frm-investment-risk-performance-measurement",
    text: "According to the fundamental law of active management, the information ratio is approximately equal to the information coefficient times the:",
    optionA: "Square root of breadth (number of independent bets)",
    optionB: "Risk-free rate",
    optionC: "Portfolio beta",
    optionD: "Tracking error squared",
    correctOption: "A",
    explanation: "IR ≈ IC × √breadth: skill (information coefficient) scaled by the square root of the number of independent investment decisions.",
    orderIndex: 7,
  },
  {
    id: "frm-investment-risk-performance-measurement-q09",
    topicId: "frm-investment-risk-performance-measurement",
    text: "A limitation of the Sharpe and information ratios is that they:",
    optionA: "Cannot be computed from returns",
    optionB: "May be misleading for strategies with highly non-normal (option-like) returns",
    optionC: "Require beta estimation",
    optionD: "Ignore the risk-free rate",
    correctOption: "B",
    explanation: "These ratios use volatility and ignore skew/kurtosis, so they can mislead for option-like or otherwise non-normal return distributions.",
    orderIndex: 8,
  },
  {
    id: "frm-investment-risk-performance-measurement-q10",
    topicId: "frm-investment-risk-performance-measurement",
    text: "Two portfolios have the same Sharpe ratio, but Portfolio A has positive skew and Portfolio B negative skew. A loss-averse investor should generally prefer:",
    optionA: "Portfolio B",
    optionB: "Portfolio A",
    optionC: "Neither; they are identical",
    optionD: "Whichever has higher beta",
    correctOption: "B",
    explanation: "Positive skew implies more upside and limited downside, which a loss-averse investor prefers—an effect the Sharpe ratio alone misses.",
    orderIndex: 9,
  },
  {
    id: "frm-investment-risk-performance-measurement-q11",
    topicId: "frm-investment-risk-performance-measurement",
    text: "Which ratio is MOST appropriate for ranking a diversified sub-portfolio whose unsystematic risk is largely diversified away in the overall fund?",
    optionA: "Sharpe ratio",
    optionB: "Treynor ratio",
    optionC: "Sortino ratio",
    optionD: "Calmar ratio",
    correctOption: "B",
    explanation: "When idiosyncratic risk is diversified away, systematic risk (beta) is the relevant measure, making the Treynor ratio appropriate.",
    orderIndex: 10,
  },
  {
    id: "frm-investment-risk-performance-measurement-q12",
    topicId: "frm-investment-risk-performance-measurement",
    text: "An information ratio of 0.5 is generally interpreted as indicating:",
    optionA: "Poor active management",
    optionB: "Good active management skill",
    optionC: "Guaranteed outperformance",
    optionD: "Zero active risk",
    correctOption: "B",
    explanation: "An IR around 0.5 is considered good (and ~1.0 exceptional), reflecting solid active return per unit of active risk.",
    orderIndex: 11,
  },

  // ── Current Issues: LIBOR to SOFR ──
  {
    id: "frm-current-issues-libor-transition-q01",
    topicId: "frm-current-issues-libor-transition",
    text: "A key reason LIBOR was discontinued is that it:",
    optionA: "Was fully transaction-based",
    optionB: "Relied on bank survey submissions and was vulnerable to manipulation",
    optionC: "Had too many underlying transactions",
    optionD: "Was set by central banks",
    correctOption: "B",
    explanation: "LIBOR was a survey/judgement-based rate with shrinking underlying interbank lending, making it unreliable and susceptible to manipulation.",
    orderIndex: 0,
  },
  {
    id: "frm-current-issues-libor-transition-q02",
    topicId: "frm-current-issues-libor-transition",
    text: "SOFR, the USD replacement rate, is based on:",
    optionA: "Unsecured interbank lending",
    optionB: "Overnight Treasury repurchase (repo) transactions",
    optionC: "Survey submissions",
    optionD: "Corporate bond yields",
    correctOption: "B",
    explanation: "SOFR (Secured Overnight Financing Rate) is derived from actual overnight Treasury repo transactions, making it transaction-based and near-risk-free.",
    orderIndex: 1,
  },
  {
    id: "frm-current-issues-libor-transition-q03",
    topicId: "frm-current-issues-libor-transition",
    text: "Compared with LIBOR, SOFR is best described as:",
    optionA: "Unsecured, term, and forward-looking",
    optionB: "Secured, overnight, and backward-looking",
    optionC: "Survey-based and judgmental",
    optionD: "A long-term bond yield",
    correctOption: "B",
    explanation: "SOFR is a secured, overnight, transaction-based rate that is naturally backward-looking, unlike LIBOR's unsecured forward-looking term structure.",
    orderIndex: 2,
  },
  {
    id: "frm-current-issues-libor-transition-q04",
    topicId: "frm-current-issues-libor-transition",
    text: "Because SOFR lacks the bank credit premium embedded in LIBOR, legacy contracts use a:",
    optionA: "Credit-spread adjustment",
    optionB: "Currency conversion factor",
    optionC: "Dividend adjustment",
    optionD: "Beta adjustment",
    correctOption: "A",
    explanation: "Fallback provisions add a credit-spread adjustment to SOFR so that converted legacy contracts remain economically comparable to LIBOR.",
    orderIndex: 3,
  },
  {
    id: "frm-current-issues-libor-transition-q05",
    topicId: "frm-current-issues-libor-transition",
    text: "Constructing a term rate from an overnight RFR like SOFR is commonly done by:",
    optionA: "Surveying banks",
    optionB: "Compounding the overnight rate in arrears",
    optionC: "Using the dividend yield",
    optionD: "Taking a simple historical average of bond yields",
    correctOption: "B",
    explanation: "Term rates are built by compounding the overnight RFR in arrears over the interest period, so the rate is known near period-end.",
    orderIndex: 4,
  },
  {
    id: "frm-current-issues-libor-transition-q06",
    topicId: "frm-current-issues-libor-transition",
    text: "A practical operational challenge of 'in-arrears' SOFR is that the payment amount is:",
    optionA: "Known at the start of the period",
    optionB: "Known only near the end of the interest period",
    optionC: "Fixed for the life of the loan",
    optionD: "Set by a survey",
    correctOption: "B",
    explanation: "Compounding in arrears means the period's interest is not known until shortly before payment, a change from LIBOR's set-in-advance convention.",
    orderIndex: 5,
  },
  {
    id: "frm-current-issues-libor-transition-q07",
    topicId: "frm-current-issues-libor-transition",
    text: "USD LIBOR's principal panel settings ceased publication around:",
    optionA: "Mid-2023",
    optionB: "2008",
    optionC: "2030",
    optionD: "2015",
    correctOption: "A",
    explanation: "The most widely used USD LIBOR settings ceased after June 2023, completing the transition for new and most legacy contracts.",
    orderIndex: 6,
  },
  {
    id: "frm-current-issues-libor-transition-q08",
    topicId: "frm-current-issues-libor-transition",
    text: "ISDA fallback language for derivatives was important because it:",
    optionA: "Increased LIBOR submissions",
    optionB: "Provided a standardized method to convert legacy contracts to RFRs",
    optionC: "Eliminated all interest payments",
    optionD: "Banned the use of SOFR",
    correctOption: "B",
    explanation: "ISDA fallbacks standardized how outstanding LIBOR derivatives transition to RFRs plus a spread adjustment, reducing legal uncertainty.",
    orderIndex: 7,
  },
  {
    id: "frm-current-issues-libor-transition-q09",
    topicId: "frm-current-issues-libor-transition",
    text: "A major risk during the LIBOR transition was 'basis risk', arising because:",
    optionA: "All rates moved identically",
    optionB: "Assets and liabilities could reference different benchmarks during the switch",
    optionC: "There were no derivatives",
    optionD: "SOFR was a term rate from the start",
    correctOption: "B",
    explanation: "Mismatches between instruments referencing LIBOR versus SOFR (or different fallbacks) created basis risk during the transition.",
    orderIndex: 8,
  },
  {
    id: "frm-current-issues-libor-transition-q10",
    topicId: "frm-current-issues-libor-transition",
    text: "Term SOFR (a forward-looking rate) was developed primarily to serve:",
    optionA: "Only derivatives dealers",
    optionB: "Cash products (e.g., business loans) that benefit from a rate known in advance",
    optionC: "Central bank operations",
    optionD: "Equity index funds",
    correctOption: "B",
    explanation: "Forward-looking Term SOFR addresses cash-market needs (like loans) where borrowers prefer knowing the rate at the start of the period.",
    orderIndex: 9,
  },
  {
    id: "frm-current-issues-libor-transition-q11",
    topicId: "frm-current-issues-libor-transition",
    text: "The overarching theme of reference rate reform is the move toward benchmarks that are:",
    optionA: "More judgment-based",
    optionB: "Anchored in observable, robust transaction data",
    optionC: "Set by individual bank panels",
    optionD: "Based on long-term forecasts",
    correctOption: "B",
    explanation: "Reform shifted benchmarks from judgment-based submissions to rates anchored in deep, observable transaction markets, improving robustness.",
    orderIndex: 10,
  },
  {
    id: "frm-current-issues-libor-transition-q12",
    topicId: "frm-current-issues-libor-transition",
    text: "Which is an example of an alternative risk-free rate adopted outside the US?",
    optionA: "SONIA (GBP)",
    optionB: "EURIBOR survey rate",
    optionC: "US prime rate",
    optionD: "The federal funds target only",
    correctOption: "A",
    explanation: "SONIA (GBP), €STR (EUR), and TONA (JPY) are the overnight near-risk-free rates adopted in their respective jurisdictions alongside SOFR in the US.",
    orderIndex: 11,
  },
];
