// FRM depth expansion — question-density top-up. Raises the highest-yield FRM
// Part I and Part II topics from 12 to 16 questions each (q13–q16, orderIndex
// 12–15). No new topics or study notes.
import type { Question } from "@jyotir/core";

export const frmDepthQuestions: Question[] = [
  // ── Part I: Foundations — Risk Management & CAPM ──
  { id: "frm-foundations-risk-management-capm-q13", topicId: "frm-foundations-risk-management-capm", text: "In the CAPM, the expected return equals the risk-free rate plus:", optionA: "Beta times the market risk premium", optionB: "The dividend yield", optionC: "Total volatility", optionD: "The inflation rate", correctOption: "A", explanation: "CAPM: E(R) = Rf + β(E(Rm) − Rf).", orderIndex: 12 },
  { id: "frm-foundations-risk-management-capm-q14", topicId: "frm-foundations-risk-management-capm", text: "The Security Market Line plots expected return against:", optionA: "Beta (systematic risk)", optionB: "Total risk", optionC: "Time", optionD: "The dividend yield", correctOption: "A", explanation: "The SML relates expected return to systematic risk (beta).", orderIndex: 13 },
  { id: "frm-foundations-risk-management-capm-q15", topicId: "frm-foundations-risk-management-capm", text: "Under CAPM, diversifiable (unsystematic) risk earns:", optionA: "No risk premium", optionB: "The largest premium", optionC: "A guaranteed return", optionD: "The market premium", correctOption: "A", explanation: "Only systematic risk is priced; unsystematic risk can be diversified away.", orderIndex: 14 },
  { id: "frm-foundations-risk-management-capm-q16", topicId: "frm-foundations-risk-management-capm", text: "A stock with a beta of 1.5 is expected to be ____ the market.", optionA: "More volatile than", optionB: "Less volatile than", optionC: "Uncorrelated with", optionD: "Identical to", correctOption: "A", explanation: "A beta above 1 means the stock amplifies market moves — more volatile.", orderIndex: 15 },

  // ── Part I: Quant — Volatility, EWMA & GARCH ──
  { id: "frm-quantitative-analysis-volatility-ewma-garch-q13", topicId: "frm-quantitative-analysis-volatility-ewma-garch", text: "EWMA gives more weight to:", optionA: "Recent observations", optionB: "The oldest observations", optionC: "All observations equally", optionD: "Future observations", correctOption: "A", explanation: "The exponentially weighted moving average weights recent data more heavily.", orderIndex: 12 },
  { id: "frm-quantitative-analysis-volatility-ewma-garch-q14", topicId: "frm-quantitative-analysis-volatility-ewma-garch", text: "In EWMA, a higher decay factor λ means volatility reacts:", optionA: "More slowly to new shocks", optionB: "Instantly", optionC: "Randomly", optionD: "Never", correctOption: "A", explanation: "A larger λ puts more weight on the past, so volatility responds more slowly.", orderIndex: 13 },
  { id: "frm-quantitative-analysis-volatility-ewma-garch-q15", topicId: "frm-quantitative-analysis-volatility-ewma-garch", text: "GARCH(1,1) models exhibit volatility:", optionA: "Mean reversion", optionB: "Constant variance", optionC: "No clustering", optionD: "Zero persistence", correctOption: "A", explanation: "GARCH(1,1) reverts to a long-run average variance, unlike EWMA.", orderIndex: 14 },
  { id: "frm-quantitative-analysis-volatility-ewma-garch-q16", topicId: "frm-quantitative-analysis-volatility-ewma-garch", text: "Volatility clustering means large moves tend to be:", optionA: "Followed by large moves", optionB: "Followed by calm always", optionC: "Independent", optionD: "Impossible", correctOption: "A", explanation: "Clustering: periods of high volatility persist, which GARCH captures.", orderIndex: 15 },

  // ── Part I: Markets — Futures, Forwards & Hedging ──
  { id: "frm-financial-markets-futures-forwards-hedging-q13", topicId: "frm-financial-markets-futures-forwards-hedging", text: "The optimal hedge ratio equals the correlation times:", optionA: "The ratio of spot to futures volatility", optionB: "The coupon", optionC: "The dividend yield", optionD: "Beta only", correctOption: "A", explanation: "Optimal hedge ratio = ρ × (σ_spot / σ_futures).", orderIndex: 12 },
  { id: "frm-financial-markets-futures-forwards-hedging-q14", topicId: "frm-financial-markets-futures-forwards-hedging", text: "Futures are marked to market:", optionA: "Daily", optionB: "At maturity only", optionC: "Never", optionD: "Annually", correctOption: "A", explanation: "Futures settle gains/losses daily through margin, unlike forwards.", orderIndex: 13 },
  { id: "frm-financial-markets-futures-forwards-hedging-q15", topicId: "frm-financial-markets-futures-forwards-hedging", text: "A long hedge is used to protect against a:", optionA: "Rising price of a future purchase", optionB: "Falling price of a holding", optionC: "Currency appreciation only", optionD: "Coupon cut", correctOption: "A", explanation: "A long hedge (buying futures) locks in the cost of a future purchase.", orderIndex: 14 },
  { id: "frm-financial-markets-futures-forwards-hedging-q16", topicId: "frm-financial-markets-futures-forwards-hedging", text: "The number of futures contracts to hedge depends on the hedge ratio and the:", optionA: "Size of the exposure relative to contract size", optionB: "Coupon", optionC: "Dividend", optionD: "Tax rate", correctOption: "A", explanation: "Contracts = hedge ratio × (exposure value / futures contract value).", orderIndex: 15 },

  // ── Part I: Valuation — Value at Risk ──
  { id: "frm-valuation-risk-models-value-at-risk-q13", topicId: "frm-valuation-risk-models-value-at-risk", text: "A 1-day 99% VaR of $1m means losses exceed $1m on about:", optionA: "1 day in 100", optionB: "99 days in 100", optionC: "Every day", optionD: "Never", correctOption: "A", explanation: "99% VaR is breached roughly 1% of the time — 1 day in 100.", orderIndex: 12 },
  { id: "frm-valuation-risk-models-value-at-risk-q14", topicId: "frm-valuation-risk-models-value-at-risk", text: "A key weakness of VaR is that it says nothing about:", optionA: "The size of losses beyond the threshold", optionB: "The confidence level", optionC: "The holding period", optionD: "The mean return", correctOption: "A", explanation: "VaR gives a threshold but not the magnitude of losses in the tail.", orderIndex: 13 },
  { id: "frm-valuation-risk-models-value-at-risk-q15", topicId: "frm-valuation-risk-models-value-at-risk", text: "To scale 1-day VaR to 10-day VaR (i.i.d. normal), multiply by:", optionA: "√10", optionB: "10", optionC: "100", optionD: "1/10", correctOption: "A", explanation: "Under the square-root-of-time rule, VaR scales with √T.", orderIndex: 14 },
  { id: "frm-valuation-risk-models-value-at-risk-q16", topicId: "frm-valuation-risk-models-value-at-risk", text: "VaR can violate which property of a coherent risk measure?", optionA: "Subadditivity", optionB: "Monotonicity", optionC: "Positive homogeneity", optionD: "Translation invariance", correctOption: "A", explanation: "VaR is not generally subadditive, so it may not be coherent (unlike ES).", orderIndex: 15 },

  // ── Part I: Markets — Options & Black-Scholes ──
  { id: "frm-financial-markets-options-pricing-q13", topicId: "frm-financial-markets-options-pricing", text: "Put–call parity relates a call, a put, the stock, and:", optionA: "A risk-free bond (PV of strike)", optionB: "A dividend", optionC: "The coupon", optionD: "Beta", correctOption: "A", explanation: "c + PV(X) = p + S is put–call parity.", orderIndex: 12 },
  { id: "frm-financial-markets-options-pricing-q14", topicId: "frm-financial-markets-options-pricing", text: "Higher volatility increases the value of:", optionA: "Both calls and puts", optionB: "Only calls", optionC: "Only puts", optionD: "Neither", correctOption: "A", explanation: "Greater volatility raises the value of both call and put options.", orderIndex: 13 },
  { id: "frm-financial-markets-options-pricing-q15", topicId: "frm-financial-markets-options-pricing", text: "Delta measures option-price sensitivity to the:", optionA: "Underlying price", optionB: "Volatility", optionC: "Time", optionD: "Interest rate", correctOption: "A", explanation: "Delta is ∂(option price)/∂(underlying price).", orderIndex: 14 },
  { id: "frm-financial-markets-options-pricing-q16", topicId: "frm-financial-markets-options-pricing", text: "Black–Scholes assumes the underlying follows:", optionA: "Geometric Brownian motion", optionB: "A random Poisson jump only", optionC: "A straight line", optionD: "Mean reversion to zero", correctOption: "A", explanation: "BSM assumes lognormal prices via geometric Brownian motion.", orderIndex: 15 },

  // ── Part I: Valuation — Bond Valuation & Duration ──
  { id: "frm-valuation-risk-models-bond-valuation-q13", topicId: "frm-valuation-risk-models-bond-valuation", text: "A bond's price and its yield are related:", optionA: "Inversely", optionB: "Directly", optionC: "Not at all", optionD: "Only at par", correctOption: "A", explanation: "Bond prices fall when yields rise and vice versa — an inverse relationship.", orderIndex: 12 },
  { id: "frm-valuation-risk-models-bond-valuation-q14", topicId: "frm-valuation-risk-models-bond-valuation", text: "Macaulay duration is the weighted-average time to receive the bond's:", optionA: "Cash flows", optionB: "Coupons only", optionC: "Principal only", optionD: "Dividends", correctOption: "A", explanation: "Macaulay duration weights the timing of all cash flows by present value.", orderIndex: 13 },
  { id: "frm-valuation-risk-models-bond-valuation-q15", topicId: "frm-valuation-risk-models-bond-valuation", text: "A zero-coupon bond's duration equals its:", optionA: "Time to maturity", optionB: "Coupon rate", optionC: "Yield", optionD: "Half its maturity", correctOption: "A", explanation: "With a single cash flow at maturity, a zero's duration equals its maturity.", orderIndex: 14 },
  { id: "frm-valuation-risk-models-bond-valuation-q16", topicId: "frm-valuation-risk-models-bond-valuation", text: "Higher coupon bonds, all else equal, have ____ duration.", optionA: "Lower", optionB: "Higher", optionC: "Zero", optionD: "Infinite", correctOption: "A", explanation: "Larger coupons return value sooner, lowering duration.", orderIndex: 15 },

  // ── Part II: Market Risk — VaR Methods & Backtesting ──
  { id: "frm-market-risk-var-methods-backtesting-q13", topicId: "frm-market-risk-var-methods-backtesting", text: "Backtesting VaR compares the number of ____ to the expected count.", optionA: "Exceptions (breaches)", optionB: "Coupons", optionC: "Dividends", optionD: "Trades", correctOption: "A", explanation: "Backtesting counts VaR exceptions and compares them to the expected rate.", orderIndex: 12 },
  { id: "frm-market-risk-var-methods-backtesting-q14", topicId: "frm-market-risk-var-methods-backtesting", text: "The Basel traffic-light approach classifies backtests into green, yellow and:", optionA: "Red zones", optionB: "Blue zones", optionC: "Black zones", optionD: "Grey zones", correctOption: "A", explanation: "Basel uses green/yellow/red zones based on the number of exceptions.", orderIndex: 13 },
  { id: "frm-market-risk-var-methods-backtesting-q15", topicId: "frm-market-risk-var-methods-backtesting", text: "Too many VaR exceptions suggest the model:", optionA: "Understates risk", optionB: "Overstates risk", optionC: "Is perfect", optionD: "Is coherent", correctOption: "A", explanation: "Excess breaches indicate the model underestimates risk.", orderIndex: 14 },
  { id: "frm-market-risk-var-methods-backtesting-q16", topicId: "frm-market-risk-var-methods-backtesting", text: "The Monte Carlo VaR method relies on:", optionA: "Simulating many random scenarios", optionB: "One historical path", optionC: "A normal assumption only", optionD: "No data", correctOption: "A", explanation: "Monte Carlo VaR generates many simulated scenarios to build the loss distribution.", orderIndex: 15 },

  // ── Part II: Market Risk — Expected Shortfall ──
  { id: "frm-market-risk-expected-shortfall-q13", topicId: "frm-market-risk-expected-shortfall", text: "Expected shortfall is the average loss:", optionA: "Beyond the VaR threshold", optionB: "Below the mean", optionC: "On a typical day", optionD: "In the best case", correctOption: "A", explanation: "ES (conditional VaR) is the expected loss given the VaR level is exceeded.", orderIndex: 12 },
  { id: "frm-market-risk-expected-shortfall-q14", topicId: "frm-market-risk-expected-shortfall", text: "Expected shortfall is always ____ VaR at the same confidence level.", optionA: "Greater than or equal to", optionB: "Less than", optionC: "Equal to only", optionD: "Unrelated to", correctOption: "A", explanation: "ES averages tail losses, so it is at least as large as VaR.", orderIndex: 13 },
  { id: "frm-market-risk-expected-shortfall-q15", topicId: "frm-market-risk-expected-shortfall", text: "A key advantage of ES over VaR is that ES is:", optionA: "Subadditive (coherent)", optionB: "Always smaller", optionC: "Model-free", optionD: "Data-free", correctOption: "A", explanation: "ES satisfies subadditivity, making it a coherent risk measure.", orderIndex: 14 },
  { id: "frm-market-risk-expected-shortfall-q16", topicId: "frm-market-risk-expected-shortfall", text: "FRTB adopted ES at a confidence level of:", optionA: "97.5%", optionB: "99%", optionC: "95%", optionD: "90%", correctOption: "A", explanation: "FRTB uses Expected Shortfall at 97.5% for internal models.", orderIndex: 15 },

  // ── Part II: Credit Risk — Default Probability & Credit VaR ──
  { id: "frm-credit-risk-default-probability-credit-var-q13", topicId: "frm-credit-risk-default-probability-credit-var", text: "Expected loss equals PD times LGD times:", optionA: "EAD", optionB: "Duration", optionC: "The coupon", optionD: "Beta", correctOption: "A", explanation: "Expected loss = PD × LGD × EAD.", orderIndex: 12 },
  { id: "frm-credit-risk-default-probability-credit-var-q14", topicId: "frm-credit-risk-default-probability-credit-var", text: "Credit VaR captures the ____ credit loss at a confidence level.", optionA: "Unexpected", optionB: "Expected only", optionC: "Zero", optionD: "Average", correctOption: "A", explanation: "Credit VaR measures unexpected loss beyond the expected loss.", orderIndex: 13 },
  { id: "frm-credit-risk-default-probability-credit-var-q15", topicId: "frm-credit-risk-default-probability-credit-var", text: "Recovery rate equals one minus the:", optionA: "Loss given default", optionB: "Probability of default", optionC: "Exposure at default", optionD: "Coupon", correctOption: "A", explanation: "Recovery rate = 1 − LGD.", orderIndex: 14 },
  { id: "frm-credit-risk-default-probability-credit-var-q16", topicId: "frm-credit-risk-default-probability-credit-var", text: "A cumulative default probability over multiple years generally:", optionA: "Increases with the horizon", optionB: "Decreases with the horizon", optionC: "Stays constant", optionD: "Is always zero", correctOption: "A", explanation: "The longer the horizon, the higher the cumulative chance of default.", orderIndex: 15 },

  // ── Part II: Credit Risk — Merton Model ──
  { id: "frm-credit-risk-merton-model-q13", topicId: "frm-credit-risk-merton-model", text: "In the Merton model, a firm defaults when asset value falls below:", optionA: "The face value of debt", optionB: "The coupon", optionC: "Zero always", optionD: "The dividend", correctOption: "A", explanation: "Default occurs at maturity if assets are worth less than the debt owed.", orderIndex: 12 },
  { id: "frm-credit-risk-merton-model-q14", topicId: "frm-credit-risk-merton-model", text: "The Merton model treats equity as a:", optionA: "Call option on the firm's assets", optionB: "Risk-free bond", optionC: "Put on debt", optionD: "Forward contract", correctOption: "A", explanation: "Equity holders have a call on the assets with strike equal to the debt.", orderIndex: 13 },
  { id: "frm-credit-risk-merton-model-q15", topicId: "frm-credit-risk-merton-model", text: "Distance to default measures the number of standard deviations to the:", optionA: "Default point", optionB: "Coupon date", optionC: "Dividend", optionD: "Par value", correctOption: "A", explanation: "Distance to default is the gap between asset value and the default threshold in σ units.", orderIndex: 14 },
  { id: "frm-credit-risk-merton-model-q16", topicId: "frm-credit-risk-merton-model", text: "In Merton's framework, risky debt equals risk-free debt minus a:", optionA: "Put option on the assets", optionB: "Call on equity", optionC: "Coupon", optionD: "Dividend", correctOption: "A", explanation: "Holding risky debt equals a risk-free bond minus a put on the firm's assets.", orderIndex: 15 },

  // ── Part II: Operational — Basel Accords & RAROC ──
  { id: "frm-operational-risk-basel-accords-raroc-q13", topicId: "frm-operational-risk-basel-accords-raroc", text: "Basel III introduced a minimum ____ ratio as a non-risk-based backstop.", optionA: "Leverage", optionB: "Dividend", optionC: "Coupon", optionD: "P/E", correctOption: "A", explanation: "The leverage ratio (Tier 1 capital / exposure) is a non-risk-based backstop.", orderIndex: 12 },
  { id: "frm-operational-risk-basel-accords-raroc-q14", topicId: "frm-operational-risk-basel-accords-raroc", text: "The minimum total capital ratio under Basel is:", optionA: "8% of risk-weighted assets", optionB: "2%", optionC: "20%", optionD: "50%", correctOption: "A", explanation: "Basel requires a minimum total capital of 8% of risk-weighted assets.", orderIndex: 13 },
  { id: "frm-operational-risk-basel-accords-raroc-q15", topicId: "frm-operational-risk-basel-accords-raroc", text: "RAROC divides risk-adjusted return by:", optionA: "Economic capital", optionB: "Revenue", optionC: "Total assets", optionD: "Headcount", correctOption: "A", explanation: "RAROC = risk-adjusted return / economic capital.", orderIndex: 14 },
  { id: "frm-operational-risk-basel-accords-raroc-q16", topicId: "frm-operational-risk-basel-accords-raroc", text: "Basel III added a countercyclical capital buffer to:", optionA: "Build capital in booms for use in downturns", optionB: "Lower capital always", optionC: "Pay dividends", optionD: "Raise coupons", correctOption: "A", explanation: "The countercyclical buffer accumulates capital in good times to absorb later stress.", orderIndex: 15 },

  // ── Part II: Liquidity — Liquidity Risk Management ──
  { id: "frm-liquidity-risk-liquidity-risk-management-q13", topicId: "frm-liquidity-risk-liquidity-risk-management", text: "Funding liquidity risk is the risk of being unable to:", optionA: "Meet obligations as they fall due", optionB: "Sell a bond at a fair price", optionC: "Earn a dividend", optionD: "Lower a coupon", correctOption: "A", explanation: "Funding liquidity risk is the inability to meet cash obligations on time.", orderIndex: 12 },
  { id: "frm-liquidity-risk-liquidity-risk-management-q14", topicId: "frm-liquidity-risk-liquidity-risk-management", text: "Market (asset) liquidity risk is the risk that an asset cannot be sold:", optionA: "Quickly without a large price concession", optionB: "At any time", optionC: "With a dividend", optionD: "Above par", correctOption: "A", explanation: "Market liquidity risk is difficulty selling without moving the price.", orderIndex: 13 },
  { id: "frm-liquidity-risk-liquidity-risk-management-q15", topicId: "frm-liquidity-risk-liquidity-risk-management", text: "The bid-ask spread is a measure of:", optionA: "Market liquidity", optionB: "Credit risk", optionC: "Duration", optionD: "Convexity", correctOption: "A", explanation: "A wider bid-ask spread indicates lower market liquidity.", orderIndex: 14 },
  { id: "frm-liquidity-risk-liquidity-risk-management-q16", topicId: "frm-liquidity-risk-liquidity-risk-management", text: "A liquidity buffer is typically held in:", optionA: "High-quality liquid assets", optionB: "Illiquid private equity", optionC: "Real estate", optionD: "Distressed debt", correctOption: "A", explanation: "Buffers use HQLA that can be sold or pledged quickly in stress.", orderIndex: 15 },

  // ── Part I: Quant — Monte Carlo Simulation & Copulas ──
  { id: "frm-quantitative-analysis-monte-carlo-q13", topicId: "frm-quantitative-analysis-monte-carlo", text: "Monte Carlo simulation estimates outcomes by:", optionA: "Generating many random scenarios", optionB: "Using one historical path", optionC: "Solving a single equation", optionD: "Ignoring randomness", correctOption: "A", explanation: "Monte Carlo draws many random paths to map the distribution of outcomes.", orderIndex: 12 },
  { id: "frm-quantitative-analysis-monte-carlo-q14", topicId: "frm-quantitative-analysis-monte-carlo", text: "The standard error of a Monte Carlo estimate decreases with:", optionA: "The square root of the number of simulations", optionB: "Fewer simulations", optionC: "Higher volatility", optionD: "The coupon", correctOption: "A", explanation: "Monte Carlo error falls in proportion to 1/√N as simulations increase.", orderIndex: 13 },
  { id: "frm-quantitative-analysis-monte-carlo-q15", topicId: "frm-quantitative-analysis-monte-carlo", text: "Variance reduction techniques (e.g., antithetic variates) aim to:", optionA: "Improve accuracy for fewer simulations", optionB: "Increase randomness", optionC: "Remove the mean", optionD: "Add bias", correctOption: "A", explanation: "Variance reduction improves estimate precision without more simulations.", orderIndex: 14 },
  { id: "frm-quantitative-analysis-monte-carlo-q16", topicId: "frm-quantitative-analysis-monte-carlo", text: "A copula is used in Monte Carlo to model the ____ between variables.", optionA: "Dependence structure", optionB: "Mean only", optionC: "Coupon", optionD: "Duration", correctOption: "A", explanation: "Copulas capture the dependence structure separate from the marginals.", orderIndex: 15 },

  // ── Part I: Quant — Linear & Non-Linear Regression ──
  { id: "frm-quantitative-analysis-regression-q13", topicId: "frm-quantitative-analysis-regression", text: "In simple linear regression, the slope coefficient measures the:", optionA: "Change in Y per unit change in X", optionB: "Mean of Y", optionC: "Variance of X", optionD: "Intercept", correctOption: "A", explanation: "The slope is the expected change in the dependent variable per unit of the regressor.", orderIndex: 12 },
  { id: "frm-quantitative-analysis-regression-q14", topicId: "frm-quantitative-analysis-regression", text: "R² measures the proportion of variance in Y explained by:", optionA: "The regression model", optionB: "The residuals", optionC: "The intercept only", optionD: "Random noise", correctOption: "A", explanation: "R² is the fraction of the dependent variable's variance explained by the regressors.", orderIndex: 13 },
  { id: "frm-quantitative-analysis-regression-q15", topicId: "frm-quantitative-analysis-regression", text: "Ordinary least squares minimises the sum of squared:", optionA: "Residuals", optionB: "Coefficients", optionC: "Regressors", optionD: "Means", correctOption: "A", explanation: "OLS chooses coefficients that minimise the sum of squared residuals.", orderIndex: 14 },
  { id: "frm-quantitative-analysis-regression-q16", topicId: "frm-quantitative-analysis-regression", text: "Heteroskedasticity refers to residuals with:", optionA: "Non-constant variance", optionB: "Zero mean", optionC: "Perfect correlation", optionD: "Constant variance", correctOption: "A", explanation: "Heteroskedasticity is error variance that changes across observations.", orderIndex: 15 },

  // ── Part I: Markets — Swaps & Interest Rate Products ──
  { id: "frm-financial-markets-swaps-q13", topicId: "frm-financial-markets-swaps", text: "A plain-vanilla interest rate swap exchanges fixed payments for:", optionA: "Floating payments", optionB: "Equity returns", optionC: "Commodity prices", optionD: "Currency", correctOption: "A", explanation: "A vanilla IRS swaps a fixed rate for a floating rate on a notional.", orderIndex: 12 },
  { id: "frm-financial-markets-swaps-q14", topicId: "frm-financial-markets-swaps", text: "At initiation, the value of a par swap is:", optionA: "Zero", optionB: "The notional", optionC: "The fixed rate", optionD: "Positive to the payer", correctOption: "A", explanation: "A swap is priced at par so its initial value is zero.", orderIndex: 13 },
  { id: "frm-financial-markets-swaps-q15", topicId: "frm-financial-markets-swaps", text: "A swap can be decomposed into a portfolio of:", optionA: "Forward rate agreements", optionB: "Equities", optionC: "Options only", optionD: "Commodities", correctOption: "A", explanation: "An interest rate swap is equivalent to a series of FRAs/forwards.", orderIndex: 14 },
  { id: "frm-financial-markets-swaps-q16", topicId: "frm-financial-markets-swaps", text: "A currency swap exchanges principal and interest in:", optionA: "Two different currencies", optionB: "One currency", optionC: "Equities", optionD: "Commodities", correctOption: "A", explanation: "Currency swaps exchange cash flows denominated in two currencies.", orderIndex: 15 },

  // ── Part I: Markets — Fixed Income & Bond Markets ──
  { id: "frm-financial-markets-fixed-income-products-q13", topicId: "frm-financial-markets-fixed-income-products", text: "A bond's yield to maturity is the discount rate that makes the present value of cash flows equal to its:", optionA: "Price", optionB: "Face value always", optionC: "Coupon", optionD: "Duration", correctOption: "A", explanation: "YTM equates the present value of the bond's cash flows to its market price.", orderIndex: 12 },
  { id: "frm-financial-markets-fixed-income-products-q14", topicId: "frm-financial-markets-fixed-income-products", text: "A bond trading below its face value is priced at a:", optionA: "Discount", optionB: "Premium", optionC: "Par", optionD: "Coupon", correctOption: "A", explanation: "A price below par is a discount, occurring when the coupon is below the market yield.", orderIndex: 13 },
  { id: "frm-financial-markets-fixed-income-products-q15", topicId: "frm-financial-markets-fixed-income-products", text: "The spread of a corporate bond over a government bond compensates mainly for:", optionA: "Credit risk", optionB: "Currency risk", optionC: "Storage cost", optionD: "Dividend risk", correctOption: "A", explanation: "The credit spread compensates investors for default (and liquidity) risk.", orderIndex: 14 },
  { id: "frm-financial-markets-fixed-income-products-q16", topicId: "frm-financial-markets-fixed-income-products", text: "A steep, upward-sloping yield curve generally reflects expectations of:", optionA: "Rising future rates/growth", optionB: "Falling rates", optionC: "Zero inflation", optionD: "Default", correctOption: "A", explanation: "An upward-sloping curve typically signals expected higher rates and growth.", orderIndex: 15 },

  // ── Part I: Valuation — Option Valuation & Greeks ──
  { id: "frm-valuation-risk-models-option-valuation-q13", topicId: "frm-valuation-risk-models-option-valuation", text: "Gamma measures the rate of change of:", optionA: "Delta with respect to the underlying", optionB: "Vega with respect to time", optionC: "Price with respect to volatility", optionD: "Theta with respect to rates", correctOption: "A", explanation: "Gamma is the sensitivity of delta to changes in the underlying price.", orderIndex: 12 },
  { id: "frm-valuation-risk-models-option-valuation-q14", topicId: "frm-valuation-risk-models-option-valuation", text: "Theta generally represents the effect on option value of:", optionA: "Time decay", optionB: "The underlying price", optionC: "A dividend", optionD: "A rating change", correctOption: "A", explanation: "Theta measures the loss of option value as time passes.", orderIndex: 13 },
  { id: "frm-valuation-risk-models-option-valuation-q15", topicId: "frm-valuation-risk-models-option-valuation", text: "A delta-neutral portfolio is insensitive to small changes in the:", optionA: "Underlying price", optionB: "Volatility", optionC: "Interest rate", optionD: "Time", correctOption: "A", explanation: "Delta hedging removes first-order sensitivity to the underlying's price.", orderIndex: 14 },
  { id: "frm-valuation-risk-models-option-valuation-q16", topicId: "frm-valuation-risk-models-option-valuation", text: "Vega is highest for options that are:", optionA: "At the money", optionB: "Deep in the money", optionC: "Deep out of the money", optionD: "Expired", correctOption: "A", explanation: "Vega peaks for at-the-money options with time remaining.", orderIndex: 15 },

  // ── Part I: Valuation — Stress Testing & Scenario Analysis ──
  { id: "frm-valuation-risk-models-stress-testing-q13", topicId: "frm-valuation-risk-models-stress-testing", text: "Stress testing evaluates losses under:", optionA: "Severe but plausible scenarios", optionB: "Average conditions only", optionC: "No change", optionD: "Guaranteed gains", correctOption: "A", explanation: "Stress tests apply severe-but-plausible shocks to gauge resilience.", orderIndex: 12 },
  { id: "frm-valuation-risk-models-stress-testing-q14", topicId: "frm-valuation-risk-models-stress-testing", text: "Stress testing complements VaR by capturing:", optionA: "Extreme tail events", optionB: "Only average losses", optionC: "Coupons", optionD: "Dividends", correctOption: "A", explanation: "Stress testing addresses tail events that VaR may understate.", orderIndex: 13 },
  { id: "frm-valuation-risk-models-stress-testing-q15", topicId: "frm-valuation-risk-models-stress-testing", text: "A historical scenario replays events such as:", optionA: "The 2008 crisis", optionB: "A normal trading day", optionC: "A dividend date", optionD: "A coupon reset", correctOption: "A", explanation: "Historical scenarios apply real past crises to the current portfolio.", orderIndex: 14 },
  { id: "frm-valuation-risk-models-stress-testing-q16", topicId: "frm-valuation-risk-models-stress-testing", text: "Reverse stress testing starts from a defined failure and identifies:", optionA: "Scenarios that could cause it", optionB: "The coupon", optionC: "The dividend", optionD: "The mean return", correctOption: "A", explanation: "Reverse stress testing works backward from failure to plausible causes.", orderIndex: 15 },

  // ── Part II: Market Risk — Parametric VaR & Normal Distribution ──
  { id: "frm-market-risk-parametric-var-q13", topicId: "frm-market-risk-parametric-var", text: "Parametric (variance-covariance) VaR assumes returns are:", optionA: "Normally distributed", optionB: "Uniformly distributed", optionC: "Always positive", optionD: "Constant", correctOption: "A", explanation: "The parametric method typically assumes a normal return distribution.", orderIndex: 12 },
  { id: "frm-market-risk-parametric-var-q14", topicId: "frm-market-risk-parametric-var", text: "For a 99% one-tailed VaR, the normal z-multiplier is about:", optionA: "2.33", optionB: "1.65", optionC: "1.96", optionD: "3.09", correctOption: "A", explanation: "The 99% one-tailed z-score is approximately 2.33.", orderIndex: 13 },
  { id: "frm-market-risk-parametric-var-q15", topicId: "frm-market-risk-parametric-var", text: "For a 95% one-tailed VaR, the normal z-multiplier is about:", optionA: "1.65", optionB: "2.33", optionC: "1.96", optionD: "1.28", correctOption: "A", explanation: "The 95% one-tailed z-score is approximately 1.65.", orderIndex: 14 },
  { id: "frm-market-risk-parametric-var-q16", topicId: "frm-market-risk-parametric-var", text: "A weakness of parametric VaR is that it underestimates risk when returns have:", optionA: "Fat tails", optionB: "Zero mean", optionC: "Low volatility", optionD: "A normal shape", correctOption: "A", explanation: "The normal assumption understates tail risk when real returns are fat-tailed.", orderIndex: 15 },

  // ── Part II: Market Risk — Historical Simulation ──
  { id: "frm-market-risk-historical-simulation-q13", topicId: "frm-market-risk-historical-simulation", text: "Historical simulation VaR uses:", optionA: "Actual past return distributions", optionB: "A normal assumption", optionC: "A single scenario", optionD: "No data", correctOption: "A", explanation: "Historical simulation applies the empirical distribution of past returns.", orderIndex: 12 },
  { id: "frm-market-risk-historical-simulation-q14", topicId: "frm-market-risk-historical-simulation", text: "An advantage of historical simulation is that it makes no assumption about the:", optionA: "Distribution's shape", optionB: "Portfolio value", optionC: "Confidence level", optionD: "Holding period", correctOption: "A", explanation: "It is non-parametric, capturing fat tails and skew in the actual data.", orderIndex: 13 },
  { id: "frm-market-risk-historical-simulation-q15", topicId: "frm-market-risk-historical-simulation", text: "A drawback of historical simulation is that it relies on the assumption that:", optionA: "The past represents the future", optionB: "Returns are normal", optionC: "Volatility is zero", optionD: "There is no data", correctOption: "A", explanation: "It assumes the historical window is representative of future risk.", orderIndex: 14 },
  { id: "frm-market-risk-historical-simulation-q16", topicId: "frm-market-risk-historical-simulation", text: "A short historical window may fail to capture:", optionA: "Rare extreme events", optionB: "The mean", optionC: "The coupon", optionD: "The dividend", correctOption: "A", explanation: "Too short a window can omit crises, understating tail risk.", orderIndex: 15 },

  // ── Part II: Credit Risk — Credit Default Swaps & Derivatives ──
  { id: "frm-credit-risk-credit-derivatives-q13", topicId: "frm-credit-risk-credit-derivatives", text: "A credit default swap (CDS) transfers:", optionA: "Credit risk from buyer to seller", optionB: "Interest-rate risk", optionC: "Currency risk", optionD: "Equity risk", correctOption: "A", explanation: "A CDS lets the protection buyer transfer default risk to the seller.", orderIndex: 12 },
  { id: "frm-credit-risk-credit-derivatives-q14", topicId: "frm-credit-risk-credit-derivatives", text: "The CDS buyer pays a periodic:", optionA: "Premium (spread)", optionB: "Dividend", optionC: "Coupon on the reference bond", optionD: "Principal", correctOption: "A", explanation: "The protection buyer pays a periodic CDS spread to the seller.", orderIndex: 13 },
  { id: "frm-credit-risk-credit-derivatives-q15", topicId: "frm-credit-risk-credit-derivatives", text: "A widening CDS spread indicates the reference entity's credit risk has:", optionA: "Increased", optionB: "Decreased", optionC: "Vanished", optionD: "Been hedged", correctOption: "A", explanation: "A wider CDS spread reflects higher perceived default risk.", orderIndex: 14 },
  { id: "frm-credit-risk-credit-derivatives-q16", topicId: "frm-credit-risk-credit-derivatives", text: "On a credit event, a cash-settled CDS pays the buyer:", optionA: "Par minus the recovery value", optionB: "Full par always", optionC: "The premium back", optionD: "Nothing", correctOption: "A", explanation: "Cash settlement pays (1 − recovery) × notional, i.e., par minus recovery.", orderIndex: 15 },

  // ── Part II: Credit Risk — Counterparty Credit Risk & CVA ──
  { id: "frm-credit-risk-counterparty-credit-risk-q13", topicId: "frm-credit-risk-counterparty-credit-risk", text: "Counterparty credit risk is the risk that a derivatives counterparty:", optionA: "Defaults before settlement", optionB: "Pays early", optionC: "Raises a dividend", optionD: "Lowers a coupon", correctOption: "A", explanation: "CCR is the risk the counterparty defaults with a positive exposure outstanding.", orderIndex: 12 },
  { id: "frm-credit-risk-counterparty-credit-risk-q14", topicId: "frm-credit-risk-counterparty-credit-risk", text: "CVA is an adjustment to a derivative's value for:", optionA: "Counterparty default risk", optionB: "Interest rates only", optionC: "Currency", optionD: "Storage cost", correctOption: "A", explanation: "The credit valuation adjustment prices expected counterparty default loss.", orderIndex: 13 },
  { id: "frm-credit-risk-counterparty-credit-risk-q15", topicId: "frm-credit-risk-counterparty-credit-risk", text: "Potential future exposure (PFE) estimates exposure at a:", optionA: "Future date and confidence level", optionB: "Single past date", optionC: "Zero horizon", optionD: "Coupon date only", correctOption: "A", explanation: "PFE is the exposure at a future point estimated at a chosen confidence level.", orderIndex: 14 },
  { id: "frm-credit-risk-counterparty-credit-risk-q16", topicId: "frm-credit-risk-counterparty-credit-risk", text: "Central clearing through a CCP reduces counterparty risk via:", optionA: "Netting and margining", optionB: "Higher coupons", optionC: "Dividends", optionD: "Longer maturities", correctOption: "A", explanation: "A CCP nets exposures and collects margin, reducing bilateral counterparty risk.", orderIndex: 15 },

  // ── Part II: Operational — Loss Distribution Approach ──
  { id: "frm-operational-risk-loss-distribution-q13", topicId: "frm-operational-risk-loss-distribution", text: "The loss distribution approach combines the frequency and ____ of operational losses.", optionA: "Severity", optionB: "Coupon", optionC: "Duration", optionD: "Dividend", correctOption: "A", explanation: "LDA convolves loss frequency and severity distributions.", orderIndex: 12 },
  { id: "frm-operational-risk-loss-distribution-q14", topicId: "frm-operational-risk-loss-distribution", text: "Loss frequency is often modelled with a ____ distribution.", optionA: "Poisson", optionB: "Normal", optionC: "Uniform", optionD: "Binomial only", correctOption: "A", explanation: "The number of loss events is commonly modelled as Poisson.", orderIndex: 13 },
  { id: "frm-operational-risk-loss-distribution-q15", topicId: "frm-operational-risk-loss-distribution", text: "Loss severity is typically modelled with a ____ distribution.", optionA: "Lognormal (heavy-tailed)", optionB: "Symmetric normal", optionC: "Uniform", optionD: "Bernoulli", correctOption: "A", explanation: "Severity is fat-tailed, often modelled as lognormal or another heavy-tailed law.", orderIndex: 14 },
  { id: "frm-operational-risk-loss-distribution-q16", topicId: "frm-operational-risk-loss-distribution", text: "Operational-risk capital under LDA is often a high quantile of the:", optionA: "Aggregate loss distribution", optionB: "Coupon schedule", optionC: "Yield curve", optionD: "Dividend stream", correctOption: "A", explanation: "Capital is a high percentile (e.g., 99.9%) of the aggregate loss distribution.", orderIndex: 15 },

  // ── Part II: Liquidity — Funding Liquidity Risk & Metrics ──
  { id: "frm-liquidity-risk-funding-liquidity-q13", topicId: "frm-liquidity-risk-funding-liquidity", text: "Funding liquidity risk is the inability to:", optionA: "Meet obligations without excessive cost", optionB: "Sell an asset", optionC: "Earn a dividend", optionD: "Raise a coupon", correctOption: "A", explanation: "Funding liquidity risk is the risk of not meeting cash needs affordably.", orderIndex: 12 },
  { id: "frm-liquidity-risk-funding-liquidity-q14", topicId: "frm-liquidity-risk-funding-liquidity", text: "Over-reliance on short-term wholesale funding creates:", optionA: "Rollover (funding) risk", optionB: "Lower risk", optionC: "Guaranteed liquidity", optionD: "A dividend", correctOption: "A", explanation: "Short-term funding must be rolled over, creating rollover/funding risk.", orderIndex: 13 },
  { id: "frm-liquidity-risk-funding-liquidity-q15", topicId: "frm-liquidity-risk-funding-liquidity", text: "A funding liquidity gap analysis compares expected cash inflows and:", optionA: "Outflows over time", optionB: "Coupons only", optionC: "Dividends", optionD: "Equity", correctOption: "A", explanation: "Liquidity gap analysis maps inflows against outflows across time buckets.", orderIndex: 14 },
  { id: "frm-liquidity-risk-funding-liquidity-q16", topicId: "frm-liquidity-risk-funding-liquidity", text: "Diversifying funding sources reduces:", optionA: "Concentration/rollover risk", optionB: "Returns", optionC: "Diversification", optionD: "Coupons", correctOption: "A", explanation: "Spreading funding across sources, tenors and currencies lowers concentration risk.", orderIndex: 15 }
];
