// GATE (CS) depth expansion — question-density top-up. Raises the highest-yield
// GATE topics from 12 to 16 questions each (q13–q16, orderIndex 12–15). No new
// topics or study notes.
import type { Question } from "@jyotir/core";

export const gateDepthQuestions: Question[] = [
  // ── Core CS: Data Structures — Complexity & Trees ──
  { id: "gate-core-cs-data-structures-complexity-trees-q13", topicId: "gate-core-cs-data-structures-complexity-trees", text: "The worst-case time to search a balanced binary search tree with n nodes is:", optionA: "O(log n)", optionB: "O(n)", optionC: "O(n log n)", optionD: "O(1)", correctOption: "A", explanation: "A balanced BST has height O(log n), so search takes O(log n).", orderIndex: 12 },
  { id: "gate-core-cs-data-structures-complexity-trees-q14", topicId: "gate-core-cs-data-structures-complexity-trees", text: "A complete binary tree with n nodes has a height of:", optionA: "O(log n)", optionB: "O(n)", optionC: "O(n²)", optionD: "O(1)", correctOption: "A", explanation: "A complete binary tree is balanced, giving height ⌊log₂n⌋.", orderIndex: 13 },
  { id: "gate-core-cs-data-structures-complexity-trees-q15", topicId: "gate-core-cs-data-structures-complexity-trees", text: "An in-order traversal of a binary search tree visits nodes in:", optionA: "Sorted (ascending) order", optionB: "Reverse order", optionC: "Random order", optionD: "Level order", correctOption: "A", explanation: "In-order traversal of a BST yields keys in ascending sorted order.", orderIndex: 14 },
  { id: "gate-core-cs-data-structures-complexity-trees-q16", topicId: "gate-core-cs-data-structures-complexity-trees", text: "In the worst case, an unbalanced BST search degrades to:", optionA: "O(n)", optionB: "O(log n)", optionC: "O(1)", optionD: "O(n log n)", correctOption: "A", explanation: "A skewed BST behaves like a linked list, so search is O(n).", orderIndex: 15 },

  // ── Core CS: Algorithms — Sorting & Complexity ──
  { id: "gate-core-cs-algorithms-sorting-complexity-q13", topicId: "gate-core-cs-algorithms-sorting-complexity", text: "The average-case time complexity of quicksort is:", optionA: "O(n log n)", optionB: "O(n²)", optionC: "O(n)", optionD: "O(log n)", correctOption: "A", explanation: "Quicksort averages O(n log n), though its worst case is O(n²).", orderIndex: 12 },
  { id: "gate-core-cs-algorithms-sorting-complexity-q14", topicId: "gate-core-cs-algorithms-sorting-complexity", text: "Merge sort has a worst-case time complexity of:", optionA: "O(n log n)", optionB: "O(n²)", optionC: "O(n)", optionD: "O(log n)", correctOption: "A", explanation: "Merge sort is O(n log n) in all cases.", orderIndex: 13 },
  { id: "gate-core-cs-algorithms-sorting-complexity-q15", topicId: "gate-core-cs-algorithms-sorting-complexity", text: "The lower bound for comparison-based sorting is:", optionA: "Ω(n log n)", optionB: "Ω(n)", optionC: "Ω(log n)", optionD: "Ω(1)", correctOption: "A", explanation: "Any comparison sort needs at least Ω(n log n) comparisons.", orderIndex: 14 },
  { id: "gate-core-cs-algorithms-sorting-complexity-q16", topicId: "gate-core-cs-algorithms-sorting-complexity", text: "Which sorting algorithm is NOT comparison-based?", optionA: "Counting sort", optionB: "Quicksort", optionC: "Merge sort", optionD: "Heapsort", correctOption: "A", explanation: "Counting sort uses key values as indices, not comparisons, achieving O(n+k).", orderIndex: 15 },

  // ── Core CS: Operating Systems ──
  { id: "gate-core-cs-operating-systems-q13", topicId: "gate-core-cs-operating-systems", text: "A deadlock requires all four Coffman conditions, including circular wait and:", optionA: "Mutual exclusion", optionB: "Preemption", optionC: "Aging", optionD: "Paging", correctOption: "A", explanation: "The four conditions are mutual exclusion, hold and wait, no preemption and circular wait.", orderIndex: 12 },
  { id: "gate-core-cs-operating-systems-q14", topicId: "gate-core-cs-operating-systems", text: "Which scheduling algorithm gives the minimum average waiting time?", optionA: "Shortest Job First", optionB: "FCFS", optionC: "Round Robin", optionD: "Priority", correctOption: "A", explanation: "SJF is optimal for minimizing average waiting time.", orderIndex: 13 },
  { id: "gate-core-cs-operating-systems-q15", topicId: "gate-core-cs-operating-systems", text: "The Banker's algorithm is used for deadlock:", optionA: "Avoidance", optionB: "Detection only", optionC: "Prevention", optionD: "Recovery", correctOption: "A", explanation: "The Banker's algorithm avoids deadlock by keeping the system in a safe state.", orderIndex: 14 },
  { id: "gate-core-cs-operating-systems-q16", topicId: "gate-core-cs-operating-systems", text: "Belady's anomaly can occur under which page-replacement policy?", optionA: "FIFO", optionB: "LRU", optionC: "Optimal", optionD: "LFU with stack property", correctOption: "A", explanation: "FIFO can show Belady's anomaly; stack algorithms like LRU cannot.", orderIndex: 15 },

  // ── Core CS: DBMS & SQL ──
  { id: "gate-core-cs-dbms-sql-q13", topicId: "gate-core-cs-dbms-sql", text: "A relation is in BCNF if, for every functional dependency X→Y:", optionA: "X is a superkey", optionB: "Y is atomic", optionC: "X is a single attribute", optionD: "Y is a candidate key", correctOption: "A", explanation: "BCNF requires the left side of every FD to be a superkey.", orderIndex: 12 },
  { id: "gate-core-cs-dbms-sql-q14", topicId: "gate-core-cs-dbms-sql", text: "A schedule is conflict-serializable if and only if its precedence graph is:", optionA: "Acyclic", optionB: "Complete", optionC: "Connected", optionD: "Bipartite", correctOption: "A", explanation: "Conflict serializability holds exactly when the precedence graph is acyclic.", orderIndex: 13 },
  { id: "gate-core-cs-dbms-sql-q15", topicId: "gate-core-cs-dbms-sql", text: "The SQL clause used to filter groups after aggregation is:", optionA: "HAVING", optionB: "WHERE", optionC: "GROUP BY", optionD: "ORDER BY", correctOption: "A", explanation: "HAVING filters aggregated groups; WHERE filters rows before grouping.", orderIndex: 14 },
  { id: "gate-core-cs-dbms-sql-q16", topicId: "gate-core-cs-dbms-sql", text: "2NF removes which kind of dependency?", optionA: "Partial dependency on part of a candidate key", optionB: "Transitive dependency", optionC: "Multivalued dependency", optionD: "Join dependency", correctOption: "A", explanation: "2NF eliminates partial dependencies of non-prime attributes on a key.", orderIndex: 15 },

  // ── Core CS: Computer Networks ──
  { id: "gate-core-cs-computer-networks-q13", topicId: "gate-core-cs-computer-networks", text: "How many layers does the OSI model have?", optionA: "7", optionB: "4", optionC: "5", optionD: "3", correctOption: "A", explanation: "The OSI reference model has 7 layers; TCP/IP has 4.", orderIndex: 12 },
  { id: "gate-core-cs-computer-networks-q14", topicId: "gate-core-cs-computer-networks", text: "Which protocol is connection-oriented and reliable?", optionA: "TCP", optionB: "UDP", optionC: "IP", optionD: "ICMP", correctOption: "A", explanation: "TCP is reliable and connection-oriented; UDP is neither.", orderIndex: 13 },
  { id: "gate-core-cs-computer-networks-q15", topicId: "gate-core-cs-computer-networks", text: "How many usable host addresses does a /24 subnet provide?", optionA: "254", optionB: "256", optionC: "252", optionD: "128", correctOption: "A", explanation: "2^(32−24) − 2 = 256 − 2 = 254 usable hosts.", orderIndex: 14 },
  { id: "gate-core-cs-computer-networks-q16", topicId: "gate-core-cs-computer-networks", text: "Which protocol resolves an IP address to a MAC address?", optionA: "ARP", optionB: "DNS", optionC: "DHCP", optionD: "ICMP", correctOption: "A", explanation: "ARP maps IP addresses to MAC (link-layer) addresses.", orderIndex: 15 },

  // ── Core CS: Theory of Computation ──
  { id: "gate-core-cs-theory-of-computation-q13", topicId: "gate-core-cs-theory-of-computation", text: "A DFA and an NFA recognise:", optionA: "Exactly the same class of languages", optionB: "Different classes", optionC: "Context-free languages", optionD: "Recursive languages only", correctOption: "A", explanation: "Every NFA has an equivalent DFA, so both accept the regular languages.", orderIndex: 12 },
  { id: "gate-core-cs-theory-of-computation-q14", topicId: "gate-core-cs-theory-of-computation", text: "The language { aⁿbⁿ : n ≥ 0 } is:", optionA: "Context-free but not regular", optionB: "Regular", optionC: "Finite", optionD: "Not context-free", correctOption: "A", explanation: "It needs a stack to count, so it is context-free but not regular.", orderIndex: 13 },
  { id: "gate-core-cs-theory-of-computation-q15", topicId: "gate-core-cs-theory-of-computation", text: "The pumping lemma is used to prove a language is:", optionA: "Not regular (or not context-free)", optionB: "Regular", optionC: "Finite", optionD: "Decidable", correctOption: "A", explanation: "The pumping lemma proves non-regularity (or non-context-freeness).", orderIndex: 14 },
  { id: "gate-core-cs-theory-of-computation-q16", topicId: "gate-core-cs-theory-of-computation", text: "Context-free languages are recognised by:", optionA: "Pushdown automata", optionB: "Finite automata", optionC: "Combinational circuits", optionD: "Linear-bounded automata", correctOption: "A", explanation: "A pushdown automaton's stack lets it recognise context-free languages.", orderIndex: 15 },

  // ── Engineering Mathematics: Linear Algebra ──
  { id: "gate-engineering-mathematics-linear-algebra-q13", topicId: "gate-engineering-mathematics-linear-algebra", text: "A square matrix is invertible if and only if its determinant is:", optionA: "Non-zero", optionB: "Zero", optionC: "Positive", optionD: "An integer", correctOption: "A", explanation: "A matrix is invertible exactly when its determinant is non-zero.", orderIndex: 12 },
  { id: "gate-engineering-mathematics-linear-algebra-q14", topicId: "gate-engineering-mathematics-linear-algebra", text: "The eigenvalues of a triangular matrix are its:", optionA: "Diagonal entries", optionB: "Row sums", optionC: "Column sums", optionD: "Determinant", correctOption: "A", explanation: "For a triangular matrix, the eigenvalues are the diagonal elements.", orderIndex: 13 },
  { id: "gate-engineering-mathematics-linear-algebra-q15", topicId: "gate-engineering-mathematics-linear-algebra", text: "The rank of a matrix equals the number of:", optionA: "Linearly independent rows (or columns)", optionB: "Total entries", optionC: "Zero rows", optionD: "Diagonal entries", correctOption: "A", explanation: "Rank is the maximum number of linearly independent rows or columns.", orderIndex: 14 },
  { id: "gate-engineering-mathematics-linear-algebra-q16", topicId: "gate-engineering-mathematics-linear-algebra", text: "The sum of the eigenvalues of a matrix equals its:", optionA: "Trace", optionB: "Determinant", optionC: "Rank", optionD: "Norm", correctOption: "A", explanation: "The sum of eigenvalues equals the trace (sum of diagonal entries).", orderIndex: 15 },

  // ── General Aptitude: Quantitative Aptitude ──
  { id: "gate-general-aptitude-quantitative-aptitude-q13", topicId: "gate-general-aptitude-quantitative-aptitude", text: "If a shirt costing 800 is sold at a 15% profit, the selling price is:", optionA: "920", optionB: "680", optionC: "915", optionD: "880", correctOption: "A", explanation: "SP = 800 × 1.15 = 920.", orderIndex: 12 },
  { id: "gate-general-aptitude-quantitative-aptitude-q14", topicId: "gate-general-aptitude-quantitative-aptitude", text: "The average of the first 10 natural numbers is:", optionA: "5.5", optionB: "5", optionC: "10", optionD: "55", correctOption: "A", explanation: "Sum = 55, average = 55/10 = 5.5.", orderIndex: 13 },
  { id: "gate-general-aptitude-quantitative-aptitude-q15", topicId: "gate-general-aptitude-quantitative-aptitude", text: "A train 120 m long travelling at 36 km/h crosses a pole in:", optionA: "12 seconds", optionB: "10 seconds", optionC: "6 seconds", optionD: "15 seconds", correctOption: "A", explanation: "36 km/h = 10 m/s; time = 120/10 = 12 s.", orderIndex: 14 },
  { id: "gate-general-aptitude-quantitative-aptitude-q16", topicId: "gate-general-aptitude-quantitative-aptitude", text: "What is 25% of 240?", optionA: "60", optionB: "48", optionC: "65", optionD: "50", correctOption: "A", explanation: "25% of 240 = 0.25 × 240 = 60.", orderIndex: 15 }
];
