// GATE (CS) depth top-up (pass 1). Every existing GATE topic held only 8
// questions; this adds q09–q12 to each so all reach the 12-question standard
// used across the catalog. No new topics or materials.
import type { Question } from "@jyotir/core";

export const gateTopUp: Question[] = [
  // ══ Engineering Mathematics ══
  // Linear Algebra
  { id: "gate-engineering-mathematics-linear-algebra-q09", topicId: "gate-engineering-mathematics-linear-algebra", text: "The determinant of an n×n identity matrix is:", optionA: "1", optionB: "0", optionC: "n", optionD: "n²", correctOption: "A", explanation: "The identity matrix has 1s on the diagonal and 0s elsewhere, so its determinant is 1.", orderIndex: 8 },
  { id: "gate-engineering-mathematics-linear-algebra-q10", topicId: "gate-engineering-mathematics-linear-algebra", text: "A square matrix is singular (non-invertible) when its determinant is:", optionA: "0", optionB: "1", optionC: "positive", optionD: "negative", correctOption: "A", explanation: "A matrix is singular exactly when its determinant equals 0.", orderIndex: 9 },
  { id: "gate-engineering-mathematics-linear-algebra-q11", topicId: "gate-engineering-mathematics-linear-algebra", text: "The eigenvalues of a triangular matrix are:", optionA: "Its diagonal entries", optionB: "Always zero", optionC: "Its row sums", optionD: "Its column sums", correctOption: "A", explanation: "For a triangular matrix, the eigenvalues are exactly the entries on the main diagonal.", orderIndex: 10 },
  { id: "gate-engineering-mathematics-linear-algebra-q12", topicId: "gate-engineering-mathematics-linear-algebra", text: "The rank of a matrix equals the number of:", optionA: "Linearly independent rows (or columns)", optionB: "Total entries", optionC: "Zero rows", optionD: "Columns only", correctOption: "A", explanation: "Rank is the maximum number of linearly independent rows, equal to that of the columns.", orderIndex: 11 },
  // Probability
  { id: "gate-engineering-mathematics-probability-q09", topicId: "gate-engineering-mathematics-probability", text: "The probability of an impossible event is:", optionA: "0", optionB: "1", optionC: "0.5", optionD: "Undefined", correctOption: "A", explanation: "An impossible event never occurs, so its probability is 0.", orderIndex: 8 },
  { id: "gate-engineering-mathematics-probability-q10", topicId: "gate-engineering-mathematics-probability", text: "For a fair six-sided die, the probability of rolling an even number is:", optionA: "1/2", optionB: "1/3", optionC: "1/6", optionD: "2/3", correctOption: "A", explanation: "Three of the six faces (2, 4, 6) are even, so the probability is 3/6 = 1/2.", orderIndex: 9 },
  { id: "gate-engineering-mathematics-probability-q11", topicId: "gate-engineering-mathematics-probability", text: "For two independent events A and B, P(A ∩ B) equals:", optionA: "P(A) × P(B)", optionB: "P(A) + P(B)", optionC: "P(A) − P(B)", optionD: "P(A) / P(B)", correctOption: "A", explanation: "Independence means the joint probability is the product of the individual probabilities.", orderIndex: 10 },
  { id: "gate-engineering-mathematics-probability-q12", topicId: "gate-engineering-mathematics-probability", text: "The sum of the probabilities of all outcomes in a sample space is:", optionA: "1", optionB: "0", optionC: "Depends on the count", optionD: "Infinity", correctOption: "A", explanation: "Probabilities over a complete sample space always sum to 1.", orderIndex: 11 },
  // Calculus
  { id: "gate-engineering-mathematics-calculus-q09", topicId: "gate-engineering-mathematics-calculus", text: "The derivative of xⁿ with respect to x is:", optionA: "n·xⁿ⁻¹", optionB: "xⁿ⁺¹/(n+1)", optionC: "n·xⁿ", optionD: "xⁿ⁻¹", correctOption: "A", explanation: "By the power rule, d/dx(xⁿ) = n·xⁿ⁻¹.", orderIndex: 8 },
  { id: "gate-engineering-mathematics-calculus-q10", topicId: "gate-engineering-mathematics-calculus", text: "The integral ∫(1/x) dx equals:", optionA: "ln|x| + C", optionB: "1/x² + C", optionC: "−1/x² + C", optionD: "x + C", correctOption: "A", explanation: "The antiderivative of 1/x is the natural logarithm ln|x| (plus a constant).", orderIndex: 9 },
  { id: "gate-engineering-mathematics-calculus-q11", topicId: "gate-engineering-mathematics-calculus", text: "The derivative of sin x is:", optionA: "cos x", optionB: "−cos x", optionC: "−sin x", optionD: "tan x", correctOption: "A", explanation: "d/dx(sin x) = cos x.", orderIndex: 10 },
  { id: "gate-engineering-mathematics-calculus-q12", topicId: "gate-engineering-mathematics-calculus", text: "At a local maximum of a differentiable function, the first derivative is:", optionA: "Zero", optionB: "Positive", optionC: "Negative", optionD: "Infinite", correctOption: "A", explanation: "At interior extrema of a differentiable function the first derivative is 0.", orderIndex: 11 },
  // Differential Equations
  { id: "gate-engineering-mathematics-differential-equations-q09", topicId: "gate-engineering-mathematics-differential-equations", text: "The order of a differential equation is:", optionA: "The highest-order derivative present", optionB: "The power of the highest derivative", optionC: "The number of terms", optionD: "The number of variables", correctOption: "A", explanation: "Order is defined by the highest derivative appearing in the equation.", orderIndex: 8 },
  { id: "gate-engineering-mathematics-differential-equations-q10", topicId: "gate-engineering-mathematics-differential-equations", text: "The general solution of dy/dx = ky is:", optionA: "y = Ceᵏˣ", optionB: "y = kx + C", optionC: "y = C/x", optionD: "y = k·ln x", correctOption: "A", explanation: "Separating variables gives exponential growth/decay: y = Ceᵏˣ.", orderIndex: 9 },
  { id: "gate-engineering-mathematics-differential-equations-q11", topicId: "gate-engineering-mathematics-differential-equations", text: "An equation of the form dy/dx + P(x)y = Q(x) is a:", optionA: "First-order linear differential equation", optionB: "Second-order equation", optionC: "Nonlinear equation", optionD: "Partial differential equation", correctOption: "A", explanation: "This standard form is a first-order linear ODE, solved with an integrating factor.", orderIndex: 10 },
  { id: "gate-engineering-mathematics-differential-equations-q12", topicId: "gate-engineering-mathematics-differential-equations", text: "The degree of the differential equation (d²y/dx²) + (dy/dx)³ = 0 is:", optionA: "1", optionB: "2", optionC: "3", optionD: "0", correctOption: "A", explanation: "Degree is the power of the highest-order derivative (d²y/dx²), which appears to the first power.", orderIndex: 11 },
  // Discrete Mathematics: Sets & Relations
  { id: "gate-engineering-mathematics-sets-relations-q09", topicId: "gate-engineering-mathematics-sets-relations", text: "A relation that is reflexive, symmetric, and transitive is an:", optionA: "Equivalence relation", optionB: "Partial order", optionC: "Total order", optionD: "Function", correctOption: "A", explanation: "Reflexive + symmetric + transitive defines an equivalence relation.", orderIndex: 8 },
  { id: "gate-engineering-mathematics-sets-relations-q10", topicId: "gate-engineering-mathematics-sets-relations", text: "The number of subsets of a set with n elements is:", optionA: "2ⁿ", optionB: "n²", optionC: "n!", optionD: "2n", correctOption: "A", explanation: "Each element is either in or out of a subset, giving 2ⁿ subsets.", orderIndex: 9 },
  { id: "gate-engineering-mathematics-sets-relations-q11", topicId: "gate-engineering-mathematics-sets-relations", text: "The identity A ∪ (B ∩ C) = (A ∪ B) ∩ (A ∪ C) is the:", optionA: "Distributive law", optionB: "Associative law", optionC: "Commutative law", optionD: "Idempotent law", correctOption: "A", explanation: "Union distributes over intersection — the distributive law of set algebra.", orderIndex: 10 },
  { id: "gate-engineering-mathematics-sets-relations-q12", topicId: "gate-engineering-mathematics-sets-relations", text: "A relation that is reflexive, antisymmetric, and transitive is a:", optionA: "Partial order", optionB: "Equivalence relation", optionC: "Bijection", optionD: "Symmetric relation", correctOption: "A", explanation: "Reflexive + antisymmetric + transitive defines a partial order.", orderIndex: 11 },
  // Graph Theory
  { id: "gate-engineering-mathematics-graph-theory-q09", topicId: "gate-engineering-mathematics-graph-theory", text: "The sum of the degrees of all vertices in a graph equals:", optionA: "Twice the number of edges", optionB: "The number of edges", optionC: "The number of vertices", optionD: "Half the number of edges", correctOption: "A", explanation: "Each edge contributes to two vertex degrees — the handshaking lemma.", orderIndex: 8 },
  { id: "gate-engineering-mathematics-graph-theory-q10", topicId: "gate-engineering-mathematics-graph-theory", text: "A tree with n vertices has exactly:", optionA: "n − 1 edges", optionB: "n edges", optionC: "n + 1 edges", optionD: "2n edges", correctOption: "A", explanation: "A tree is connected and acyclic, forcing exactly n − 1 edges.", orderIndex: 9 },
  { id: "gate-engineering-mathematics-graph-theory-q11", topicId: "gate-engineering-mathematics-graph-theory", text: "The complete graph Kₙ has how many edges?", optionA: "n(n − 1)/2", optionB: "n²", optionC: "n − 1", optionD: "2n", correctOption: "A", explanation: "Each pair of the n vertices is joined once: C(n,2) = n(n−1)/2 edges.", orderIndex: 10 },
  { id: "gate-engineering-mathematics-graph-theory-q12", topicId: "gate-engineering-mathematics-graph-theory", text: "A graph is bipartite if and only if it contains no:", optionA: "Odd-length cycle", optionB: "Even-length cycle", optionC: "Vertex of degree 2", optionD: "Bridge", correctOption: "A", explanation: "A graph is bipartite exactly when it has no cycles of odd length.", orderIndex: 11 },
  // Combinatorics
  { id: "gate-engineering-mathematics-combinatorics-q09", topicId: "gate-engineering-mathematics-combinatorics", text: "The number of permutations of n distinct objects is:", optionA: "n!", optionB: "2ⁿ", optionC: "n²", optionD: "n(n−1)/2", correctOption: "A", explanation: "There are n! ways to arrange n distinct objects in order.", orderIndex: 8 },
  { id: "gate-engineering-mathematics-combinatorics-q10", topicId: "gate-engineering-mathematics-combinatorics", text: "The number of ways to choose r items from n, C(n, r), equals:", optionA: "n! / (r!(n − r)!)", optionB: "n! / r!", optionC: "nʳ", optionD: "n! × r!", correctOption: "A", explanation: "Combinations count unordered selections: C(n,r) = n!/(r!(n−r)!).", orderIndex: 9 },
  { id: "gate-engineering-mathematics-combinatorics-q11", topicId: "gate-engineering-mathematics-combinatorics", text: "The value of C(5, 2) is:", optionA: "10", optionB: "20", optionC: "25", optionD: "120", correctOption: "A", explanation: "C(5,2) = 5!/(2!·3!) = 10.", orderIndex: 10 },
  { id: "gate-engineering-mathematics-combinatorics-q12", topicId: "gate-engineering-mathematics-combinatorics", text: "By the pigeonhole principle, placing n + 1 items into n boxes guarantees that:", optionA: "At least one box holds two or more items", optionB: "Every box is empty", optionC: "Each box holds one item", optionD: "One box is always empty", correctOption: "A", explanation: "With more items than boxes, some box must contain at least two items.", orderIndex: 11 },
  // Numerical Methods
  { id: "gate-engineering-mathematics-numerical-methods-q09", topicId: "gate-engineering-mathematics-numerical-methods", text: "The Newton-Raphson method is used to find:", optionA: "Roots of an equation", optionB: "Definite integrals", optionC: "Matrix eigenvalues", optionD: "Derivatives", correctOption: "A", explanation: "Newton-Raphson iteratively approximates the roots of f(x) = 0.", orderIndex: 8 },
  { id: "gate-engineering-mathematics-numerical-methods-q10", topicId: "gate-engineering-mathematics-numerical-methods", text: "The trapezoidal rule is a technique for:", optionA: "Numerical integration", optionB: "Root finding", optionC: "Solving linear systems", optionD: "Interpolation only", correctOption: "A", explanation: "The trapezoidal rule approximates a definite integral by summing trapezoids.", orderIndex: 9 },
  { id: "gate-engineering-mathematics-numerical-methods-q11", topicId: "gate-engineering-mathematics-numerical-methods", text: "Near a simple root, the Newton-Raphson method converges:", optionA: "Quadratically", optionB: "Linearly", optionC: "Not at all", optionD: "Cubically", correctOption: "A", explanation: "Newton-Raphson exhibits quadratic convergence near a simple root.", orderIndex: 10 },
  { id: "gate-engineering-mathematics-numerical-methods-q12", topicId: "gate-engineering-mathematics-numerical-methods", text: "The bisection method requires that the function values at the two endpoints have:", optionA: "Opposite signs", optionB: "The same sign", optionC: "Zero derivative", optionD: "Equal magnitude", correctOption: "A", explanation: "A sign change over the interval guarantees a root lies within (intermediate value theorem).", orderIndex: 11 },

  // ══ General Aptitude ══
  // Ratio & Logical Puzzles
  { id: "gate-general-aptitude-ratio-logical-puzzles-q09", topicId: "gate-general-aptitude-ratio-logical-puzzles", text: "If A:B = 2:3 and B:C = 4:5, then A:C equals:", optionA: "8:15", optionB: "2:5", optionC: "8:5", optionD: "6:5", correctOption: "A", explanation: "A:B = 8:12 and B:C = 12:15, so A:C = 8:15.", orderIndex: 8 },
  { id: "gate-general-aptitude-ratio-logical-puzzles-q10", topicId: "gate-general-aptitude-ratio-logical-puzzles", text: "All Bloops are Razzies and all Razzies are Lazzies. Therefore all Bloops are:", optionA: "Lazzies", optionB: "Not Lazzies", optionC: "Only Razzies", optionD: "Undetermined", correctOption: "A", explanation: "Chaining the two universals gives: all Bloops are Lazzies.", orderIndex: 9 },
  { id: "gate-general-aptitude-ratio-logical-puzzles-q11", topicId: "gate-general-aptitude-ratio-logical-puzzles", text: "If 3 pencils cost ₹6, then 7 pencils cost:", optionA: "₹14", optionB: "₹12", optionC: "₹18", optionD: "₹21", correctOption: "A", explanation: "Each pencil costs ₹2, so 7 pencils cost ₹14.", orderIndex: 10 },
  { id: "gate-general-aptitude-ratio-logical-puzzles-q12", topicId: "gate-general-aptitude-ratio-logical-puzzles", text: "Dividing 200 in the ratio 3:2, the larger part is:", optionA: "120", optionB: "80", optionC: "100", optionD: "150", correctOption: "A", explanation: "Larger part = 200 × 3/5 = 120.", orderIndex: 11 },
  // Quantitative Aptitude
  { id: "gate-general-aptitude-quantitative-aptitude-q09", topicId: "gate-general-aptitude-quantitative-aptitude", text: "15% of 200 is:", optionA: "30", optionB: "25", optionC: "35", optionD: "20", correctOption: "A", explanation: "15% of 200 = 0.15 × 200 = 30.", orderIndex: 8 },
  { id: "gate-general-aptitude-quantitative-aptitude-q10", topicId: "gate-general-aptitude-quantitative-aptitude", text: "The average of 5, 10 and 15 is:", optionA: "10", optionB: "12", optionC: "15", optionD: "7.5", correctOption: "A", explanation: "(5 + 10 + 15)/3 = 30/3 = 10.", orderIndex: 9 },
  { id: "gate-general-aptitude-quantitative-aptitude-q11", topicId: "gate-general-aptitude-quantitative-aptitude", text: "A shirt costs ₹800 after a 20% discount. Its original price was:", optionA: "₹1000", optionB: "₹960", optionC: "₹1020", optionD: "₹840", correctOption: "A", explanation: "800 = 0.8 × original, so original = 800/0.8 = ₹1000.", orderIndex: 10 },
  { id: "gate-general-aptitude-quantitative-aptitude-q12", topicId: "gate-general-aptitude-quantitative-aptitude", text: "The square root of 144 is:", optionA: "12", optionB: "14", optionC: "16", optionD: "10", correctOption: "A", explanation: "12 × 12 = 144, so √144 = 12.", orderIndex: 11 },
  // Verbal Ability
  { id: "gate-general-aptitude-verbal-ability-q09", topicId: "gate-general-aptitude-verbal-ability", text: "Choose the synonym of 'ABUNDANT':", optionA: "Plentiful", optionB: "Scarce", optionC: "Empty", optionD: "Rare", correctOption: "A", explanation: "'Abundant' means existing in large quantity — plentiful.", orderIndex: 8 },
  { id: "gate-general-aptitude-verbal-ability-q10", topicId: "gate-general-aptitude-verbal-ability", text: "Choose the antonym of 'EXPAND':", optionA: "Contract", optionB: "Enlarge", optionC: "Grow", optionD: "Widen", correctOption: "A", explanation: "'Contract' is the opposite of 'expand'.", orderIndex: 9 },
  { id: "gate-general-aptitude-verbal-ability-q11", topicId: "gate-general-aptitude-verbal-ability", text: "Choose the correctly spelt word:", optionA: "Necessary", optionB: "Neccessary", optionC: "Necesary", optionD: "Neccesary", correctOption: "A", explanation: "The correct spelling is 'necessary' (one c, two s).", orderIndex: 10 },
  { id: "gate-general-aptitude-verbal-ability-q12", topicId: "gate-general-aptitude-verbal-ability", text: "Fill in the blank: 'He is good ___ chess.'", optionA: "at", optionB: "in", optionC: "on", optionD: "with", correctOption: "A", explanation: "The correct collocation is 'good at' an activity.", orderIndex: 11 },
  // Data Interpretation
  { id: "gate-general-aptitude-data-interpretation-q09", topicId: "gate-general-aptitude-data-interpretation", text: "In a pie chart, a sector representing 25% corresponds to:", optionA: "90°", optionB: "72°", optionC: "60°", optionD: "45°", correctOption: "A", explanation: "A full circle is 360°, so 25% of 360° = 90°.", orderIndex: 8 },
  { id: "gate-general-aptitude-data-interpretation-q10", topicId: "gate-general-aptitude-data-interpretation", text: "If sales rise from 50 to 75, the percentage increase is:", optionA: "50%", optionB: "25%", optionC: "33%", optionD: "75%", correctOption: "A", explanation: "Increase = 25 on 50 = 25/50 × 100 = 50%.", orderIndex: 9 },
  { id: "gate-general-aptitude-data-interpretation-q11", topicId: "gate-general-aptitude-data-interpretation", text: "The average of 20, 40 and 60 is:", optionA: "40", optionB: "30", optionC: "50", optionD: "45", correctOption: "A", explanation: "(20 + 40 + 60)/3 = 120/3 = 40.", orderIndex: 10 },
  { id: "gate-general-aptitude-data-interpretation-q12", topicId: "gate-general-aptitude-data-interpretation", text: "10% of 500 is:", optionA: "50", optionB: "5", optionC: "100", optionD: "25", correctOption: "A", explanation: "10% of 500 = 0.10 × 500 = 50.", orderIndex: 11 },
  // Logical Reasoning & Series
  { id: "gate-general-aptitude-logical-reasoning-series-q09", topicId: "gate-general-aptitude-logical-reasoning-series", text: "Find the next term: 2, 4, 8, 16, ?", optionA: "32", optionB: "24", optionC: "20", optionD: "18", correctOption: "A", explanation: "Each term doubles: 16 × 2 = 32.", orderIndex: 8 },
  { id: "gate-general-aptitude-logical-reasoning-series-q10", topicId: "gate-general-aptitude-logical-reasoning-series", text: "Find the next term: 1, 4, 9, 16, ?", optionA: "25", optionB: "20", optionC: "24", optionD: "36", correctOption: "A", explanation: "These are perfect squares: 5² = 25.", orderIndex: 9 },
  { id: "gate-general-aptitude-logical-reasoning-series-q11", topicId: "gate-general-aptitude-logical-reasoning-series", text: "Find the odd one out: 2, 3, 5, 9.", optionA: "9", optionB: "2", optionC: "3", optionD: "5", correctOption: "A", explanation: "2, 3 and 5 are prime; 9 is not.", orderIndex: 10 },
  { id: "gate-general-aptitude-logical-reasoning-series-q12", topicId: "gate-general-aptitude-logical-reasoning-series", text: "If CAT is coded as DBU (each letter +1), then DOG is coded as:", optionA: "EPH", optionB: "CPF", optionC: "EPG", optionD: "DPH", correctOption: "A", explanation: "Shifting each letter forward by one: D→E, O→P, G→H = EPH.", orderIndex: 11 },

  // ══ Core CS ══
  // Data Structures — Complexity & Trees
  { id: "gate-core-cs-data-structures-complexity-trees-q09", topicId: "gate-core-cs-data-structures-complexity-trees", text: "The time complexity to search a balanced binary search tree is:", optionA: "O(log n)", optionB: "O(n)", optionC: "O(1)", optionD: "O(n²)", correctOption: "A", explanation: "A balanced BST has height O(log n), so search is O(log n).", orderIndex: 8 },
  { id: "gate-core-cs-data-structures-complexity-trees-q10", topicId: "gate-core-cs-data-structures-complexity-trees", text: "The maximum number of nodes at level k of a binary tree (root at level 0) is:", optionA: "2ᵏ", optionB: "2k", optionC: "k²", optionD: "2ᵏ − 1", correctOption: "A", explanation: "Each level can double the nodes, giving at most 2ᵏ nodes at level k.", orderIndex: 9 },
  { id: "gate-core-cs-data-structures-complexity-trees-q11", topicId: "gate-core-cs-data-structures-complexity-trees", text: "In-order traversal of a binary search tree visits the nodes in:", optionA: "Ascending sorted order", optionB: "Descending order", optionC: "Random order", optionD: "Level order", correctOption: "A", explanation: "In-order traversal of a BST yields keys in ascending sorted order.", orderIndex: 10 },
  { id: "gate-core-cs-data-structures-complexity-trees-q12", topicId: "gate-core-cs-data-structures-complexity-trees", text: "The height of a complete binary tree with n nodes is:", optionA: "O(log n)", optionB: "O(n)", optionC: "O(n log n)", optionD: "O(1)", correctOption: "A", explanation: "A complete binary tree is balanced, so its height is ⌊log₂ n⌋ = O(log n).", orderIndex: 11 },
  // Algorithms: Sorting & Complexity
  { id: "gate-core-cs-algorithms-sorting-complexity-q09", topicId: "gate-core-cs-algorithms-sorting-complexity", text: "The worst-case time complexity of Merge Sort is:", optionA: "O(n log n)", optionB: "O(n²)", optionC: "O(n)", optionD: "O(log n)", correctOption: "A", explanation: "Merge Sort always divides and merges in O(n log n), even in the worst case.", orderIndex: 8 },
  { id: "gate-core-cs-algorithms-sorting-complexity-q10", topicId: "gate-core-cs-algorithms-sorting-complexity", text: "The worst-case time complexity of Quick Sort is:", optionA: "O(n²)", optionB: "O(n log n)", optionC: "O(n)", optionD: "O(log n)", correctOption: "A", explanation: "With poor pivots (e.g., already-sorted input) Quick Sort degrades to O(n²).", orderIndex: 9 },
  { id: "gate-core-cs-algorithms-sorting-complexity-q11", topicId: "gate-core-cs-algorithms-sorting-complexity", text: "Which sorting algorithm is stable and guarantees O(n log n) in the worst case?", optionA: "Merge Sort", optionB: "Quick Sort", optionC: "Bubble Sort", optionD: "Selection Sort", correctOption: "A", explanation: "Merge Sort is stable with a guaranteed O(n log n) worst case.", orderIndex: 10 },
  { id: "gate-core-cs-algorithms-sorting-complexity-q12", topicId: "gate-core-cs-algorithms-sorting-complexity", text: "Binary search on a sorted array of n elements has time complexity:", optionA: "O(log n)", optionB: "O(n)", optionC: "O(1)", optionD: "O(n log n)", correctOption: "A", explanation: "Binary search halves the search space each step, giving O(log n).", orderIndex: 11 },
  // Greedy & Dynamic Programming
  { id: "gate-core-cs-greedy-dynamic-programming-q09", topicId: "gate-core-cs-greedy-dynamic-programming", text: "Dijkstra's shortest-path algorithm (non-negative weights) is an example of a:", optionA: "Greedy algorithm", optionB: "Divide-and-conquer algorithm", optionC: "Backtracking algorithm", optionD: "Brute-force algorithm", correctOption: "A", explanation: "Dijkstra greedily selects the nearest unvisited vertex at each step.", orderIndex: 8 },
  { id: "gate-core-cs-greedy-dynamic-programming-q10", topicId: "gate-core-cs-greedy-dynamic-programming", text: "Dynamic programming is efficient when a problem has overlapping subproblems and:", optionA: "Optimal substructure", optionB: "No structure", optionC: "Only one solution", optionD: "Random inputs", correctOption: "A", explanation: "DP requires optimal substructure plus overlapping subproblems to reuse solutions.", orderIndex: 9 },
  { id: "gate-core-cs-greedy-dynamic-programming-q11", topicId: "gate-core-cs-greedy-dynamic-programming", text: "The 0/1 knapsack problem is typically solved using:", optionA: "Dynamic programming", optionB: "A greedy algorithm (optimally)", optionC: "Binary search", optionD: "Hashing", correctOption: "A", explanation: "0/1 knapsack needs DP; the plain greedy approach is not optimal for it.", orderIndex: 10 },
  { id: "gate-core-cs-greedy-dynamic-programming-q12", topicId: "gate-core-cs-greedy-dynamic-programming", text: "For a greedy algorithm to yield an optimal solution, the problem must have the:", optionA: "Greedy-choice property", optionB: "Overlapping subproblems only", optionC: "NP-completeness", optionD: "Random structure", correctOption: "A", explanation: "The greedy-choice property (plus optimal substructure) makes locally optimal choices globally optimal.", orderIndex: 11 },
  // Operating Systems
  { id: "gate-core-cs-operating-systems-q09", topicId: "gate-core-cs-operating-systems", text: "A situation where two processes each wait indefinitely for a resource held by the other is:", optionA: "Deadlock", optionB: "Starvation", optionC: "Thrashing", optionD: "Preemption", correctOption: "A", explanation: "Deadlock is a circular wait where each process holds a resource the other needs.", orderIndex: 8 },
  { id: "gate-core-cs-operating-systems-q10", topicId: "gate-core-cs-operating-systems", text: "The scheduling policy that gives each process a fixed time quantum in turn is:", optionA: "Round-robin", optionB: "First-come first-served", optionC: "Shortest job first", optionD: "Priority (non-preemptive)", correctOption: "A", explanation: "Round-robin cycles through processes, giving each a small time slice.", orderIndex: 9 },
  { id: "gate-core-cs-operating-systems-q11", topicId: "gate-core-cs-operating-systems", text: "Virtual memory is most commonly implemented using:", optionA: "Paging", optionB: "Spooling", optionC: "Caching only", optionD: "Compression", correctOption: "A", explanation: "Paging maps virtual pages to physical frames, enabling virtual memory.", orderIndex: 10 },
  { id: "gate-core-cs-operating-systems-q12", topicId: "gate-core-cs-operating-systems", text: "A semaphore is primarily used for:", optionA: "Process synchronization", optionB: "Memory allocation", optionC: "Disk scheduling", optionD: "File compression", correctOption: "A", explanation: "Semaphores coordinate access to shared resources, preventing race conditions.", orderIndex: 11 },
  // DBMS & SQL
  { id: "gate-core-cs-dbms-sql-q09", topicId: "gate-core-cs-dbms-sql", text: "The SQL command that removes a table and its structure entirely is:", optionA: "DROP TABLE", optionB: "DELETE", optionC: "TRUNCATE", optionD: "REMOVE", correctOption: "A", explanation: "DROP TABLE deletes the table definition and all its data.", orderIndex: 8 },
  { id: "gate-core-cs-dbms-sql-q10", topicId: "gate-core-cs-dbms-sql", text: "The attribute chosen to uniquely identify each row of a table is the:", optionA: "Primary key", optionB: "Foreign key", optionC: "Candidate index", optionD: "Check constraint", correctOption: "A", explanation: "The primary key uniquely identifies rows and cannot be null.", orderIndex: 9 },
  { id: "gate-core-cs-dbms-sql-q11", topicId: "gate-core-cs-dbms-sql", text: "The normal form that eliminates partial functional dependencies is:", optionA: "Second Normal Form (2NF)", optionB: "First Normal Form (1NF)", optionC: "BCNF", optionD: "Fourth Normal Form", correctOption: "A", explanation: "2NF removes partial dependencies of non-key attributes on part of a composite key.", orderIndex: 10 },
  { id: "gate-core-cs-dbms-sql-q12", topicId: "gate-core-cs-dbms-sql", text: "The SQL clause used to filter grouped rows is:", optionA: "HAVING", optionB: "WHERE", optionC: "GROUP BY", optionD: "ORDER BY", correctOption: "A", explanation: "HAVING filters groups after aggregation, whereas WHERE filters individual rows.", orderIndex: 11 },
  // Computer Networks
  { id: "gate-core-cs-computer-networks-q09", topicId: "gate-core-cs-computer-networks", text: "The transport-layer protocol that provides reliable, connection-oriented delivery is:", optionA: "TCP", optionB: "UDP", optionC: "IP", optionD: "ICMP", correctOption: "A", explanation: "TCP provides reliable, ordered, connection-oriented byte streams.", orderIndex: 8 },
  { id: "gate-core-cs-computer-networks-q10", topicId: "gate-core-cs-computer-networks", text: "An IPv4 address is how many bits long?", optionA: "32", optionB: "64", optionC: "128", optionD: "16", correctOption: "A", explanation: "IPv4 addresses are 32 bits (four 8-bit octets).", orderIndex: 9 },
  { id: "gate-core-cs-computer-networks-q11", topicId: "gate-core-cs-computer-networks", text: "Routing is the responsibility of which OSI layer?", optionA: "Network layer", optionB: "Transport layer", optionC: "Data-link layer", optionD: "Application layer", correctOption: "A", explanation: "The network layer (layer 3) handles logical addressing and routing.", orderIndex: 10 },
  { id: "gate-core-cs-computer-networks-q12", topicId: "gate-core-cs-computer-networks", text: "DNS is the system that translates domain names into:", optionA: "IP addresses", optionB: "MAC addresses", optionC: "Port numbers", optionD: "Passwords", correctOption: "A", explanation: "The Domain Name System resolves human-readable names to IP addresses.", orderIndex: 11 },
  // Theory of Computation
  { id: "gate-core-cs-theory-of-computation-q09", topicId: "gate-core-cs-theory-of-computation", text: "A language accepted by a finite automaton is:", optionA: "Regular", optionB: "Context-free but not regular", optionC: "Undecidable", optionD: "Context-sensitive only", correctOption: "A", explanation: "Finite automata accept exactly the regular languages.", orderIndex: 8 },
  { id: "gate-core-cs-theory-of-computation-q10", topicId: "gate-core-cs-theory-of-computation", text: "The pumping lemma is commonly used to prove that a language is:", optionA: "Not regular", optionB: "Regular", optionC: "Finite", optionD: "Decidable", correctOption: "A", explanation: "The pumping lemma gives a property of regular languages; violating it proves non-regularity.", orderIndex: 9 },
  { id: "gate-core-cs-theory-of-computation-q11", topicId: "gate-core-cs-theory-of-computation", text: "A pushdown automaton recognizes the class of:", optionA: "Context-free languages", optionB: "Regular languages only", optionC: "Recursively enumerable languages", optionD: "Finite languages only", correctOption: "A", explanation: "A PDA (finite control plus a stack) recognizes the context-free languages.", orderIndex: 10 },
  { id: "gate-core-cs-theory-of-computation-q12", topicId: "gate-core-cs-theory-of-computation", text: "The halting problem is:", optionA: "Undecidable", optionB: "Decidable in polynomial time", optionC: "Regular", optionD: "Context-free", correctOption: "A", explanation: "Turing proved that no algorithm can decide whether an arbitrary program halts.", orderIndex: 11 },
  // Compiler Design
  { id: "gate-core-cs-compiler-design-q09", topicId: "gate-core-cs-compiler-design", text: "The compiler phase that checks grammatical (syntactic) structure is:", optionA: "Syntax analysis (parsing)", optionB: "Lexical analysis", optionC: "Code generation", optionD: "Optimization", correctOption: "A", explanation: "The parser (syntax analysis) verifies the token stream against the grammar.", orderIndex: 8 },
  { id: "gate-core-cs-compiler-design-q10", topicId: "gate-core-cs-compiler-design", text: "The output of lexical analysis is a stream of:", optionA: "Tokens", optionB: "Machine code", optionC: "Parse trees", optionD: "Registers", correctOption: "A", explanation: "The lexer converts source characters into tokens for the parser.", orderIndex: 9 },
  { id: "gate-core-cs-compiler-design-q11", topicId: "gate-core-cs-compiler-design", text: "A symbol table primarily stores:", optionA: "Identifiers and their attributes", optionB: "Machine instructions", optionC: "Disk blocks", optionD: "Network routes", correctOption: "A", explanation: "The symbol table records identifiers (variables, functions) and their properties.", orderIndex: 10 },
  { id: "gate-core-cs-compiler-design-q12", topicId: "gate-core-cs-compiler-design", text: "Type checking is performed during which compiler phase?", optionA: "Semantic analysis", optionB: "Lexical analysis", optionC: "Parsing", optionD: "Linking", correctOption: "A", explanation: "Semantic analysis enforces type rules and other meaning-related constraints.", orderIndex: 11 },
  // Computer Organization & Architecture
  { id: "gate-core-cs-computer-organization-architecture-q09", topicId: "gate-core-cs-computer-organization-architecture", text: "The component that performs arithmetic and logic operations is the:", optionA: "ALU", optionB: "Control unit", optionC: "Register file", optionD: "Cache", correctOption: "A", explanation: "The Arithmetic Logic Unit executes arithmetic and logical operations.", orderIndex: 8 },
  { id: "gate-core-cs-computer-organization-architecture-q10", topicId: "gate-core-cs-computer-organization-architecture", text: "The fastest storage in the memory hierarchy is:", optionA: "CPU registers", optionB: "Main memory", optionC: "SSD", optionD: "Hard disk", correctOption: "A", explanation: "Registers inside the CPU are the fastest (and smallest) storage.", orderIndex: 9 },
  { id: "gate-core-cs-computer-organization-architecture-q11", topicId: "gate-core-cs-computer-organization-architecture", text: "A pipeline stall caused by an instruction needing a result not yet available is a:", optionA: "Data hazard", optionB: "Structural hazard", optionC: "Control hazard", optionD: "Cache miss", correctOption: "A", explanation: "A data hazard arises from a dependency on a result still in the pipeline.", orderIndex: 10 },
  { id: "gate-core-cs-computer-organization-architecture-q12", topicId: "gate-core-cs-computer-organization-architecture", text: "The number of address lines needed to address 1 KB of memory is:", optionA: "10", optionB: "8", optionC: "12", optionD: "16", correctOption: "A", explanation: "1 KB = 1024 = 2¹⁰ locations, requiring 10 address lines.", orderIndex: 11 },
  // Digital Logic
  { id: "gate-core-cs-digital-logic-q09", topicId: "gate-core-cs-digital-logic", text: "The Boolean expression A + A' evaluates to:", optionA: "1", optionB: "0", optionC: "A", optionD: "A'", correctOption: "A", explanation: "A variable OR its complement is always 1 (complement law).", orderIndex: 8 },
  { id: "gate-core-cs-digital-logic-q10", topicId: "gate-core-cs-digital-logic", text: "Which pair of gates is functionally complete (universal)?", optionA: "NAND and NOR", optionB: "AND and OR", optionC: "XOR and XNOR", optionD: "Buffer and NOT", correctOption: "A", explanation: "Any Boolean function can be built from only NAND gates or only NOR gates.", orderIndex: 9 },
  { id: "gate-core-cs-digital-logic-q11", topicId: "gate-core-cs-digital-logic", text: "The 2's complement of a binary number is found by:", optionA: "Inverting the bits and adding 1", optionB: "Adding 1 only", optionC: "Inverting the bits only", optionD: "Shifting left", correctOption: "A", explanation: "2's complement = 1's complement (bit inversion) plus 1.", orderIndex: 10 },
  { id: "gate-core-cs-digital-logic-q12", topicId: "gate-core-cs-digital-logic", text: "A multiplexer with n selection lines can choose among how many inputs?", optionA: "2ⁿ", optionB: "n", optionC: "2n", optionD: "n²", correctOption: "A", explanation: "n select lines address 2ⁿ distinct data inputs.", orderIndex: 11 },
  // Programming & Recursion in C
  { id: "gate-core-cs-programming-recursion-c-q09", topicId: "gate-core-cs-programming-recursion-c", text: "In C, the operator used to access the value stored at a pointer is:", optionA: "* (dereference)", optionB: "& (address-of)", optionC: "-> only", optionD: "%", correctOption: "A", explanation: "The unary * operator dereferences a pointer to access the pointed-to value.", orderIndex: 8 },
  { id: "gate-core-cs-programming-recursion-c-q10", topicId: "gate-core-cs-programming-recursion-c", text: "Every correct recursive function must have a:", optionA: "Base case", optionB: "Global variable", optionC: "Loop", optionD: "Pointer", correctOption: "A", explanation: "A base case stops the recursion; without it the recursion never terminates.", orderIndex: 9 },
  { id: "gate-core-cs-programming-recursion-c-q11", topicId: "gate-core-cs-programming-recursion-c", text: "In C, when an array is passed to a function, it is effectively passed by:", optionA: "Reference (a pointer to the first element)", optionB: "Value (a full copy)", optionC: "Name", optionD: "Constant only", correctOption: "A", explanation: "An array argument decays to a pointer to its first element, so changes are visible to the caller.", orderIndex: 10 },
  { id: "gate-core-cs-programming-recursion-c-q12", topicId: "gate-core-cs-programming-recursion-c", text: "The address-of operator in C is:", optionA: "&", optionB: "*", optionC: "@", optionD: "#", correctOption: "A", explanation: "The & operator yields the memory address of a variable.", orderIndex: 11 },
  // Software Engineering
  { id: "gate-core-cs-software-engineering-q09", topicId: "gate-core-cs-software-engineering", text: "The software process model with strictly sequential phases is the:", optionA: "Waterfall model", optionB: "Spiral model", optionC: "Agile model", optionD: "Prototype model", correctOption: "A", explanation: "The Waterfall model flows through phases in a fixed sequence without overlap.", orderIndex: 8 },
  { id: "gate-core-cs-software-engineering-q10", topicId: "gate-core-cs-software-engineering", text: "The iterative, risk-driven software process model is the:", optionA: "Spiral model", optionB: "Waterfall model", optionC: "V-model", optionD: "Big-bang model", correctOption: "A", explanation: "The Spiral model repeats phases in risk-driven iterations.", orderIndex: 9 },
  { id: "gate-core-cs-software-engineering-q11", topicId: "gate-core-cs-software-engineering", text: "Checking whether the software meets the user's actual needs is called:", optionA: "Validation", optionB: "Verification", optionC: "Compilation", optionD: "Integration", correctOption: "A", explanation: "Validation asks 'are we building the right product?'; verification asks 'are we building it right?'.", orderIndex: 10 },
  { id: "gate-core-cs-software-engineering-q12", topicId: "gate-core-cs-software-engineering", text: "Good modular design aims for:", optionA: "Low coupling and high cohesion", optionB: "High coupling and low cohesion", optionC: "High coupling and high cohesion", optionD: "Low coupling and low cohesion", correctOption: "A", explanation: "Modules should be internally focused (high cohesion) and loosely interdependent (low coupling).", orderIndex: 11 },
  // Computer Graphics Basics
  { id: "gate-core-cs-computer-graphics-basics-q09", topicId: "gate-core-cs-computer-graphics-basics", text: "The smallest addressable element of a raster display is a:", optionA: "Pixel", optionB: "Vector", optionC: "Vertex", optionD: "Frame", correctOption: "A", explanation: "A pixel (picture element) is the smallest addressable point on a raster screen.", orderIndex: 8 },
  { id: "gate-core-cs-computer-graphics-basics-q10", topicId: "gate-core-cs-computer-graphics-basics", text: "Bresenham's algorithm is used to draw:", optionA: "Lines", optionB: "Text", optionC: "Shadows", optionD: "Colors", correctOption: "A", explanation: "Bresenham's line algorithm rasterizes straight lines using only integer arithmetic.", orderIndex: 9 },
  { id: "gate-core-cs-computer-graphics-basics-q11", topicId: "gate-core-cs-computer-graphics-basics", text: "Removing the portions of objects that lie outside a viewing window is called:", optionA: "Clipping", optionB: "Shading", optionC: "Rendering", optionD: "Rasterizing", correctOption: "A", explanation: "Clipping discards geometry outside the defined view region.", orderIndex: 10 },
  { id: "gate-core-cs-computer-graphics-basics-q12", topicId: "gate-core-cs-computer-graphics-basics", text: "The 2D transformation that changes an object's size is:", optionA: "Scaling", optionB: "Translation", optionC: "Rotation", optionD: "Reflection", correctOption: "A", explanation: "Scaling multiplies coordinates by factors to enlarge or shrink an object.", orderIndex: 11 },
  // Artificial Intelligence & ML Basics
  { id: "gate-core-cs-artificial-intelligence-ml-basics-q09", topicId: "gate-core-cs-artificial-intelligence-ml-basics", text: "A search strategy that explores the deepest unexplored node first is:", optionA: "Depth-first search", optionB: "Breadth-first search", optionC: "Uniform-cost search", optionD: "Greedy best-first only", correctOption: "A", explanation: "DFS pursues one branch as deep as possible before backtracking.", orderIndex: 8 },
  { id: "gate-core-cs-artificial-intelligence-ml-basics-q10", topicId: "gate-core-cs-artificial-intelligence-ml-basics", text: "A* search evaluates nodes using the path cost g(n) plus:", optionA: "A heuristic estimate h(n)", optionB: "A random value", optionC: "The depth only", optionD: "Zero", correctOption: "A", explanation: "A* uses f(n) = g(n) + h(n), combining actual cost and a heuristic to the goal.", orderIndex: 9 },
  { id: "gate-core-cs-artificial-intelligence-ml-basics-q11", topicId: "gate-core-cs-artificial-intelligence-ml-basics", text: "Supervised machine learning is trained on:", optionA: "Labeled data", optionB: "Unlabeled data", optionC: "No data", optionD: "Only images", correctOption: "A", explanation: "Supervised learning uses input-output labeled examples to learn a mapping.", orderIndex: 10 },
  { id: "gate-core-cs-artificial-intelligence-ml-basics-q12", topicId: "gate-core-cs-artificial-intelligence-ml-basics", text: "Overfitting occurs when a model:", optionA: "Fits the training data too closely and generalizes poorly", optionB: "Is too simple", optionC: "Uses too little data", optionD: "Has no parameters", correctOption: "A", explanation: "An overfit model memorizes training noise and performs poorly on new data.", orderIndex: 11 },
  // Information Security & Cryptography
  { id: "gate-core-cs-information-security-cryptography-q09", topicId: "gate-core-cs-information-security-cryptography", text: "RSA is an example of:", optionA: "Asymmetric (public-key) cryptography", optionB: "Symmetric-key cryptography", optionC: "A hash function", optionD: "A block cipher mode", correctOption: "A", explanation: "RSA uses a public/private key pair — asymmetric cryptography.", orderIndex: 8 },
  { id: "gate-core-cs-information-security-cryptography-q10", topicId: "gate-core-cs-information-security-cryptography", text: "A cryptographic hash function produces a fixed-size output called a:", optionA: "Digest (hash)", optionB: "Ciphertext key", optionC: "Salt only", optionD: "Nonce", correctOption: "A", explanation: "A hash maps arbitrary input to a fixed-length digest.", orderIndex: 9 },
  { id: "gate-core-cs-information-security-cryptography-q11", topicId: "gate-core-cs-information-security-cryptography", text: "Symmetric-key encryption uses:", optionA: "The same key for encryption and decryption", optionB: "A public and a private key", optionC: "No key", optionD: "Two different public keys", correctOption: "A", explanation: "Symmetric encryption shares one secret key for both operations.", orderIndex: 10 },
  { id: "gate-core-cs-information-security-cryptography-q12", topicId: "gate-core-cs-information-security-cryptography", text: "A digital signature primarily provides:", optionA: "Authentication and integrity (non-repudiation)", optionB: "Only confidentiality", optionC: "Faster encryption", optionD: "Data compression", correctOption: "A", explanation: "Digital signatures verify the sender and that the message is unaltered, supporting non-repudiation.", orderIndex: 11 },

  // ══ Programming & DS ══
  // C Programming & Pointers
  { id: "gate-programming-ds-c-programming-pointers-q09", topicId: "gate-programming-ds-c-programming-pointers", text: "A pointer variable stores:", optionA: "A memory address", optionB: "A floating-point value", optionC: "A character only", optionD: "A function body", correctOption: "A", explanation: "A pointer holds the address of another variable in memory.", orderIndex: 8 },
  { id: "gate-programming-ds-c-programming-pointers-q10", topicId: "gate-programming-ds-c-programming-pointers", text: "In C, the & operator returns:", optionA: "The address of a variable", optionB: "The value at an address", optionC: "The bitwise OR", optionD: "The size in bytes", correctOption: "A", explanation: "The address-of operator & yields a variable's memory address.", orderIndex: 9 },
  { id: "gate-programming-ds-c-programming-pointers-q11", topicId: "gate-programming-ds-c-programming-pointers", text: "A NULL pointer:", optionA: "Points to no valid memory location", optionB: "Points to address 1", optionC: "Is always dereferenceable", optionD: "Stores a random value", correctOption: "A", explanation: "A NULL pointer represents 'points to nothing' and must not be dereferenced.", orderIndex: 10 },
  { id: "gate-programming-ds-c-programming-pointers-q12", topicId: "gate-programming-ds-c-programming-pointers", text: "Dereferencing a pointer p with *p gives:", optionA: "The value stored at the address in p", optionB: "The address of p", optionC: "The size of p", optionD: "A copy of the pointer", correctOption: "A", explanation: "*p accesses the value located at the address held by p.", orderIndex: 11 },
  // Recursion & Backtracking
  { id: "gate-programming-ds-recursion-backtracking-q09", topicId: "gate-programming-ds-recursion-backtracking", text: "Backtracking is a natural technique for solving:", optionA: "The N-Queens problem", optionB: "Binary search", optionC: "Matrix multiplication", optionD: "Hashing", correctOption: "A", explanation: "Backtracking explores partial solutions and abandons those that cannot succeed, as in N-Queens.", orderIndex: 8 },
  { id: "gate-programming-ds-recursion-backtracking-q10", topicId: "gate-programming-ds-recursion-backtracking", text: "Any recursive algorithm can, in principle, be rewritten as an:", optionA: "Iterative algorithm using an explicit stack", optionB: "Constant-time algorithm", optionC: "Sorting algorithm", optionD: "Hashing algorithm", correctOption: "A", explanation: "Recursion can be simulated iteratively with an explicit stack.", orderIndex: 9 },
  { id: "gate-programming-ds-recursion-backtracking-q11", topicId: "gate-programming-ds-recursion-backtracking", text: "The base case of the recursive factorial function is:", optionA: "factorial(0) = 1", optionB: "factorial(0) = 0", optionC: "factorial(1) = 0", optionD: "factorial(n) = n", correctOption: "A", explanation: "By definition 0! = 1, which stops the recursion.", orderIndex: 10 },
  { id: "gate-programming-ds-recursion-backtracking-q12", topicId: "gate-programming-ds-recursion-backtracking", text: "Recursion implicitly uses which data structure?", optionA: "The call stack", optionB: "A queue", optionC: "A hash table", optionD: "A heap", correctOption: "A", explanation: "Each recursive call is stored on the program's call stack.", orderIndex: 11 },
  // Linked Lists, Stacks & Queues
  { id: "gate-programming-ds-linked-lists-stacks-queues-q09", topicId: "gate-programming-ds-linked-lists-stacks-queues", text: "A stack follows which principle?", optionA: "LIFO (Last-In, First-Out)", optionB: "FIFO (First-In, First-Out)", optionC: "Random access", optionD: "Priority order", correctOption: "A", explanation: "The last element pushed onto a stack is the first popped off — LIFO.", orderIndex: 8 },
  { id: "gate-programming-ds-linked-lists-stacks-queues-q10", topicId: "gate-programming-ds-linked-lists-stacks-queues", text: "A queue follows which principle?", optionA: "FIFO (First-In, First-Out)", optionB: "LIFO", optionC: "Sorted order", optionD: "Random", correctOption: "A", explanation: "The first element enqueued is the first dequeued — FIFO.", orderIndex: 9 },
  { id: "gate-programming-ds-linked-lists-stacks-queues-q11", topicId: "gate-programming-ds-linked-lists-stacks-queues", text: "Inserting a node at the head of a singly linked list takes:", optionA: "O(1) time", optionB: "O(n) time", optionC: "O(log n) time", optionD: "O(n²) time", correctOption: "A", explanation: "Head insertion only rewires a couple of pointers — constant time.", orderIndex: 10 },
  { id: "gate-programming-ds-linked-lists-stacks-queues-q12", topicId: "gate-programming-ds-linked-lists-stacks-queues", text: "The operation that removes the top element of a stack is:", optionA: "pop", optionB: "push", optionC: "enqueue", optionD: "peek", correctOption: "A", explanation: "pop removes and returns the top element; push adds one.", orderIndex: 11 },
  // Hashing & Heaps
  { id: "gate-programming-ds-hashing-heaps-q09", topicId: "gate-programming-ds-hashing-heaps", text: "The average-case time complexity of search in a hash table is:", optionA: "O(1)", optionB: "O(n)", optionC: "O(log n)", optionD: "O(n log n)", correctOption: "A", explanation: "With a good hash function and load factor, lookups are expected O(1).", orderIndex: 8 },
  { id: "gate-programming-ds-hashing-heaps-q10", topicId: "gate-programming-ds-hashing-heaps", text: "In a min-heap, each parent node is:", optionA: "Less than or equal to its children", optionB: "Greater than its children", optionC: "Equal to the root always", optionD: "Unordered", correctOption: "A", explanation: "The min-heap property keeps each parent ≤ its children, so the minimum is at the root.", orderIndex: 9 },
  { id: "gate-programming-ds-hashing-heaps-q11", topicId: "gate-programming-ds-hashing-heaps", text: "When two distinct keys hash to the same index, it is called a:", optionA: "Collision", optionB: "Rehash", optionC: "Overflow bit", optionD: "Probe miss", correctOption: "A", explanation: "A collision occurs when different keys map to the same bucket.", orderIndex: 10 },
  { id: "gate-programming-ds-hashing-heaps-q12", topicId: "gate-programming-ds-hashing-heaps", text: "Extracting the minimum from a binary min-heap of n elements takes:", optionA: "O(log n)", optionB: "O(1)", optionC: "O(n)", optionD: "O(n log n)", correctOption: "A", explanation: "After removing the root, re-heapifying (sift-down) costs O(log n).", orderIndex: 11 },
  // Graph Algorithms (BFS/DFS)
  { id: "gate-programming-ds-graph-algorithms-bfs-dfs-q09", topicId: "gate-programming-ds-graph-algorithms-bfs-dfs", text: "Breadth-first search uses which data structure?", optionA: "A queue", optionB: "A stack", optionC: "A heap", optionD: "A hash table", correctOption: "A", explanation: "BFS uses a FIFO queue to explore vertices level by level.", orderIndex: 8 },
  { id: "gate-programming-ds-graph-algorithms-bfs-dfs-q10", topicId: "gate-programming-ds-graph-algorithms-bfs-dfs", text: "Depth-first search is naturally implemented with:", optionA: "A stack (or recursion)", optionB: "A queue", optionC: "A priority queue", optionD: "A hash map", correctOption: "A", explanation: "DFS uses a stack, explicitly or via the recursion call stack.", orderIndex: 9 },
  { id: "gate-programming-ds-graph-algorithms-bfs-dfs-q11", topicId: "gate-programming-ds-graph-algorithms-bfs-dfs", text: "BFS from a source finds shortest paths in an:", optionA: "Unweighted graph", optionB: "Weighted graph with negatives", optionC: "Any weighted graph", optionD: "Directed acyclic graph only", correctOption: "A", explanation: "BFS gives shortest paths by edge count, valid for unweighted graphs.", orderIndex: 10 },
  { id: "gate-programming-ds-graph-algorithms-bfs-dfs-q12", topicId: "gate-programming-ds-graph-algorithms-bfs-dfs", text: "The time complexity of BFS or DFS on a graph with V vertices and E edges is:", optionA: "O(V + E)", optionB: "O(V²)", optionC: "O(E log V)", optionD: "O(V·E)", correctOption: "A", explanation: "Each vertex and edge is processed a constant number of times, giving O(V + E).", orderIndex: 11 },
  // Dynamic Programming
  { id: "gate-programming-ds-dynamic-programming-q09", topicId: "gate-programming-ds-dynamic-programming", text: "The two key properties enabling dynamic programming are optimal substructure and:", optionA: "Overlapping subproblems", optionB: "Random access", optionC: "Sorted input", optionD: "Constant space", correctOption: "A", explanation: "DP reuses solutions to overlapping subproblems that combine into an optimal whole.", orderIndex: 8 },
  { id: "gate-programming-ds-dynamic-programming-q10", topicId: "gate-programming-ds-dynamic-programming", text: "Storing the results of subproblems to avoid recomputation is called:", optionA: "Memoization", optionB: "Recursion", optionC: "Hashing", optionD: "Backtracking", correctOption: "A", explanation: "Memoization caches subproblem results for reuse in top-down DP.", orderIndex: 9 },
  { id: "gate-programming-ds-dynamic-programming-q11", topicId: "gate-programming-ds-dynamic-programming", text: "Computing the nth Fibonacci number with dynamic programming takes:", optionA: "O(n) time", optionB: "O(2ⁿ) time", optionC: "O(log n) time", optionD: "O(n²) time", correctOption: "A", explanation: "DP computes each Fibonacci value once, in linear O(n) time.", orderIndex: 10 },
  { id: "gate-programming-ds-dynamic-programming-q12", topicId: "gate-programming-ds-dynamic-programming", text: "The Longest Common Subsequence (LCS) problem is solved efficiently by:", optionA: "Dynamic programming", optionB: "A greedy algorithm", optionC: "Binary search", optionD: "Hashing", correctOption: "A", explanation: "LCS uses a DP table over prefixes of the two sequences.", orderIndex: 11 },

  // ══ Computer Organization ══
  // Number Systems & Boolean Algebra
  { id: "gate-computer-organization-number-systems-boolean-algebra-q09", topicId: "gate-computer-organization-number-systems-boolean-algebra", text: "The binary number 1010 equals in decimal:", optionA: "10", optionB: "8", optionC: "12", optionD: "6", correctOption: "A", explanation: "1010₂ = 8 + 0 + 2 + 0 = 10.", orderIndex: 8 },
  { id: "gate-computer-organization-number-systems-boolean-algebra-q10", topicId: "gate-computer-organization-number-systems-boolean-algebra", text: "The hexadecimal digit F equals in decimal:", optionA: "15", optionB: "16", optionC: "14", optionD: "10", correctOption: "A", explanation: "Hex digits run 0–F, where F = 15.", orderIndex: 9 },
  { id: "gate-computer-organization-number-systems-boolean-algebra-q11", topicId: "gate-computer-organization-number-systems-boolean-algebra", text: "By De Morgan's law, (A·B)' equals:", optionA: "A' + B'", optionB: "A' · B'", optionC: "A + B", optionD: "A · B", correctOption: "A", explanation: "De Morgan: the complement of a product is the sum of the complements.", orderIndex: 10 },
  { id: "gate-computer-organization-number-systems-boolean-algebra-q12", topicId: "gate-computer-organization-number-systems-boolean-algebra", text: "The decimal number 8 in binary is:", optionA: "1000", optionB: "0100", optionC: "1100", optionD: "0010", correctOption: "A", explanation: "8 = 2³, which is 1000 in binary.", orderIndex: 11 },
  // CPU & Instruction Pipelining
  { id: "gate-computer-organization-cpu-instruction-pipelining-q09", topicId: "gate-computer-organization-cpu-instruction-pipelining", text: "Pipelining primarily improves a processor's:", optionA: "Instruction throughput", optionB: "Clock voltage", optionC: "Memory size", optionD: "Cache size", correctOption: "A", explanation: "Overlapping instruction stages raises throughput (instructions completed per unit time).", orderIndex: 8 },
  { id: "gate-computer-organization-cpu-instruction-pipelining-q10", topicId: "gate-computer-organization-cpu-instruction-pipelining", text: "A branch instruction can cause which type of pipeline hazard?", optionA: "Control hazard", optionB: "Structural hazard", optionC: "Data hazard", optionD: "No hazard", correctOption: "A", explanation: "Branches create control hazards because the next instruction address is uncertain.", orderIndex: 9 },
  { id: "gate-computer-organization-cpu-instruction-pipelining-q11", topicId: "gate-computer-organization-cpu-instruction-pipelining", text: "The ideal speedup of a k-stage pipeline (no stalls) is:", optionA: "k times", optionB: "2 times", optionC: "k² times", optionD: "log k times", correctOption: "A", explanation: "In the ideal case a k-stage pipeline can approach a k-fold speedup.", orderIndex: 10 },
  { id: "gate-computer-organization-cpu-instruction-pipelining-q12", topicId: "gate-computer-organization-cpu-instruction-pipelining", text: "The pipeline stage that retrieves the instruction from memory is the:", optionA: "Instruction fetch (IF) stage", optionB: "Execute stage", optionC: "Write-back stage", optionD: "Decode stage", correctOption: "A", explanation: "The IF stage fetches the instruction pointed to by the program counter.", orderIndex: 11 },
  // Cache & Memory Hierarchy
  { id: "gate-computer-organization-cache-memory-hierarchy-q09", topicId: "gate-computer-organization-cache-memory-hierarchy", text: "A cache hit occurs when:", optionA: "The requested data is found in the cache", optionB: "The cache is full", optionC: "Data is written to disk", optionD: "The TLB is flushed", correctOption: "A", explanation: "A hit means the needed data is already present in the cache.", orderIndex: 8 },
  { id: "gate-computer-organization-cache-memory-hierarchy-q10", topicId: "gate-computer-organization-cache-memory-hierarchy", text: "The tendency to re-access recently used data soon is called:", optionA: "Temporal locality", optionB: "Spatial locality", optionC: "Fragmentation", optionD: "Thrashing", correctOption: "A", explanation: "Temporal locality: recently accessed items are likely to be accessed again soon.", orderIndex: 9 },
  { id: "gate-computer-organization-cache-memory-hierarchy-q11", topicId: "gate-computer-organization-cache-memory-hierarchy", text: "In direct-mapped cache, a memory block maps to:", optionA: "Exactly one cache line", optionB: "Any cache line", optionC: "Two cache lines", optionD: "No cache line", correctOption: "A", explanation: "Direct mapping assigns each block to a single predetermined cache line.", orderIndex: 10 },
  { id: "gate-computer-organization-cache-memory-hierarchy-q12", topicId: "gate-computer-organization-cache-memory-hierarchy", text: "Compared with main memory, cache memory is:", optionA: "Faster but smaller", optionB: "Slower but larger", optionC: "Slower and smaller", optionD: "Identical in speed", correctOption: "A", explanation: "Cache trades capacity for speed — it is faster and smaller than main memory.", orderIndex: 11 },
  // I/O & Interrupts
  { id: "gate-computer-organization-io-interrupts-q09", topicId: "gate-computer-organization-io-interrupts", text: "An interrupt is a signal that:", optionA: "Temporarily halts the CPU to service an event", optionB: "Speeds up the clock", optionC: "Erases memory", optionD: "Increases cache size", correctOption: "A", explanation: "An interrupt diverts the CPU to handle an event, then resumes the interrupted work.", orderIndex: 8 },
  { id: "gate-computer-organization-io-interrupts-q10", topicId: "gate-computer-organization-io-interrupts", text: "Direct Memory Access (DMA) allows I/O devices to:", optionA: "Transfer data to memory without CPU intervention", optionB: "Run the operating system", optionC: "Increase clock speed", optionD: "Replace the cache", correctOption: "A", explanation: "DMA moves data between device and memory directly, freeing the CPU.", orderIndex: 9 },
  { id: "gate-computer-organization-io-interrupts-q11", topicId: "gate-computer-organization-io-interrupts", text: "Compared with interrupt-driven I/O, polling is generally:", optionA: "Less efficient (the CPU wastes cycles checking)", optionB: "Always faster", optionC: "Free of CPU use", optionD: "Interrupt-based", correctOption: "A", explanation: "Polling repeatedly checks device status, wasting CPU cycles that interrupts avoid.", orderIndex: 10 },
  { id: "gate-computer-organization-io-interrupts-q12", topicId: "gate-computer-organization-io-interrupts", text: "The routine executed in response to an interrupt is the:", optionA: "Interrupt service routine (ISR)", optionB: "Boot loader", optionC: "Scheduler", optionD: "Compiler", correctOption: "A", explanation: "The ISR (interrupt handler) runs to service the interrupting event.", orderIndex: 11 },

  // ══ Discrete Mathematics ══
  // Propositional & Predicate Logic
  { id: "gate-discrete-math-propositional-predicate-logic-q09", topicId: "gate-discrete-math-propositional-predicate-logic", text: "The implication P → Q is false only when:", optionA: "P is true and Q is false", optionB: "P is false and Q is true", optionC: "Both are true", optionD: "Both are false", correctOption: "A", explanation: "An implication fails exactly when the antecedent is true but the consequent is false.", orderIndex: 8 },
  { id: "gate-discrete-math-propositional-predicate-logic-q10", topicId: "gate-discrete-math-propositional-predicate-logic", text: "The negation of '∀x P(x)' is:", optionA: "∃x ¬P(x)", optionB: "∀x ¬P(x)", optionC: "∃x P(x)", optionD: "¬∃x P(x)", correctOption: "A", explanation: "Negating a universal gives an existential of the negation: ∃x ¬P(x).", orderIndex: 9 },
  { id: "gate-discrete-math-propositional-predicate-logic-q11", topicId: "gate-discrete-math-propositional-predicate-logic", text: "The expression P ∨ ¬P is a:", optionA: "Tautology", optionB: "Contradiction", optionC: "Contingency", optionD: "Predicate", correctOption: "A", explanation: "P OR NOT P is always true — a tautology (law of excluded middle).", orderIndex: 10 },
  { id: "gate-discrete-math-propositional-predicate-logic-q12", topicId: "gate-discrete-math-propositional-predicate-logic", text: "The contrapositive of P → Q is:", optionA: "¬Q → ¬P", optionB: "Q → P", optionC: "¬P → ¬Q", optionD: "P → ¬Q", correctOption: "A", explanation: "The contrapositive ¬Q → ¬P is logically equivalent to P → Q.", orderIndex: 11 },
  // Set Theory & Relations
  { id: "gate-discrete-math-set-theory-relations-q09", topicId: "gate-discrete-math-set-theory-relations", text: "The power set of a set with 3 elements has how many elements?", optionA: "8", optionB: "6", optionC: "3", optionD: "9", correctOption: "A", explanation: "The power set has 2³ = 8 subsets.", orderIndex: 8 },
  { id: "gate-discrete-math-set-theory-relations-q10", topicId: "gate-discrete-math-set-theory-relations", text: "The identity A ∩ (B ∪ C) = (A ∩ B) ∪ (A ∩ C) is the:", optionA: "Distributive law", optionB: "Commutative law", optionC: "Associative law", optionD: "De Morgan's law", correctOption: "A", explanation: "Intersection distributes over union — a distributive law.", orderIndex: 9 },
  { id: "gate-discrete-math-set-theory-relations-q11", topicId: "gate-discrete-math-set-theory-relations", text: "Two sets that share no common elements are:", optionA: "Disjoint", optionB: "Equal", optionC: "Subsets", optionD: "Universal", correctOption: "A", explanation: "Sets with empty intersection are disjoint.", orderIndex: 10 },
  { id: "gate-discrete-math-set-theory-relations-q12", topicId: "gate-discrete-math-set-theory-relations", text: "If |A| = 3 and |B| = 4, the cardinality of A × B is:", optionA: "12", optionB: "7", optionC: "9", optionD: "16", correctOption: "A", explanation: "The Cartesian product has |A| × |B| = 3 × 4 = 12 ordered pairs.", orderIndex: 11 },
  // Group Theory & Algebra
  { id: "gate-discrete-math-group-theory-algebra-q09", topicId: "gate-discrete-math-group-theory-algebra", text: "The four axioms a group must satisfy are closure, associativity, identity, and:", optionA: "Existence of inverses", optionB: "Commutativity", optionC: "Distributivity", optionD: "Density", correctOption: "A", explanation: "A group needs closure, associativity, an identity element, and inverses for every element.", orderIndex: 8 },
  { id: "gate-discrete-math-group-theory-algebra-q10", topicId: "gate-discrete-math-group-theory-algebra", text: "A group whose operation is commutative is called:", optionA: "Abelian", optionB: "Cyclic only", optionC: "Trivial", optionD: "Simple", correctOption: "A", explanation: "An abelian (commutative) group satisfies a·b = b·a for all elements.", orderIndex: 9 },
  { id: "gate-discrete-math-group-theory-algebra-q11", topicId: "gate-discrete-math-group-theory-algebra", text: "The identity element of the group of integers under addition is:", optionA: "0", optionB: "1", optionC: "−1", optionD: "None", correctOption: "A", explanation: "Adding 0 leaves any integer unchanged, so 0 is the additive identity.", orderIndex: 10 },
  { id: "gate-discrete-math-group-theory-algebra-q12", topicId: "gate-discrete-math-group-theory-algebra", text: "The order of a finite group is:", optionA: "The number of its elements", optionB: "Its largest element", optionC: "The identity element", optionD: "The number of subgroups", correctOption: "A", explanation: "A group's order is its cardinality — the count of its elements.", orderIndex: 11 },
  // Counting & Recurrences
  { id: "gate-discrete-math-counting-recurrences-q09", topicId: "gate-discrete-math-counting-recurrences", text: "The number of ways to arrange n distinct objects in a row is:", optionA: "n!", optionB: "2ⁿ", optionC: "n²", optionD: "n", correctOption: "A", explanation: "There are n! orderings (permutations) of n distinct objects.", orderIndex: 8 },
  { id: "gate-discrete-math-counting-recurrences-q10", topicId: "gate-discrete-math-counting-recurrences", text: "The recurrence relation for the Fibonacci sequence is F(n) =:", optionA: "F(n−1) + F(n−2)", optionB: "F(n−1) × F(n−2)", optionC: "2·F(n−1)", optionD: "F(n−1) + n", correctOption: "A", explanation: "Each Fibonacci number is the sum of the two preceding ones.", orderIndex: 9 },
  { id: "gate-discrete-math-counting-recurrences-q11", topicId: "gate-discrete-math-counting-recurrences", text: "By the Master Theorem, the recurrence T(n) = 2T(n/2) + O(n) solves to:", optionA: "O(n log n)", optionB: "O(n)", optionC: "O(n²)", optionD: "O(log n)", correctOption: "A", explanation: "This is the classic Merge Sort recurrence, giving Θ(n log n).", orderIndex: 10 },
  { id: "gate-discrete-math-counting-recurrences-q12", topicId: "gate-discrete-math-counting-recurrences", text: "By the addition (sum) rule, if a task can be done in m ways OR n mutually exclusive ways, the total is:", optionA: "m + n", optionB: "m × n", optionC: "m − n", optionD: "mⁿ", correctOption: "A", explanation: "For mutually exclusive alternatives the counts add: m + n.", orderIndex: 11 }
];
