// GATE (CS) depth expansion — question-density top-up. Raises the highest-yield
// GATE topics from 12 to 16 questions each (q13–q16, orderIndex 12–15). No new
// topics or study notes.
import type { Question } from "@jyotir/core";

export const gateDepthQuestions: Question[] = [
  // ── Core CS: Data Structures — Complexity & Trees ──
  { id: "gate-core-cs-data-structures-complexity-trees-q13", topicId: "gate-core-cs-data-structures-complexity-trees", text: "The worst-case time to search a balanced binary search tree with n nodes is:", optionA: "O(log n)", optionB: "O(n)", optionC: "O(n log n)", optionD: "O(1)", correctOption: "A", explanation: "A balanced BST has height O(log n), so search takes O(log n).", orderIndex: 12 },
  { id: "gate-core-cs-data-structures-complexity-trees-q14", topicId: "gate-core-cs-data-structures-complexity-trees", text: "A complete binary tree with n nodes has a height of:", optionA: "O(log n)", optionB: "O(n)", optionC: "O(n²)", optionD: "O(1)", correctOption: "A", explanation: "A complete binary tree is balanced, giving height ⌊log₂n⌋.", orderIndex: 13 },
  { id: "gate-core-cs-data-structures-complexity-trees-q15", topicId: "gate-core-cs-data-structures-complexity-trees", text: "An in-order traversal of a binary search tree visits nodes in:", optionA: "Sorted (ascending) order", optionB: "Reverse order", optionC: "Random order", optionD: "Level order", correctOption: "A", explanation: "In-order traversal of a BST yields keys in ascending sorted order.", orderIndex: 14 },
  { id: "gate-core-cs-data-structures-complexity-trees-q16", topicId: "gate-core-cs-data-structures-complexity-trees", text: "In the worst case, an unbalanced BST search degrades to:", optionA: "O(n)", optionB: "O(log n)", optionC: "O(1)", optionD: "O(n log n)", correctOption: "A", explanation: "A skewed BST behaves like a linked list, so search is O(n).", orderIndex: 15 },

  // ── Core CS: Algorithms — Sorting & Complexity ──
  { id: "gate-core-cs-algorithms-sorting-complexity-q13", topicId: "gate-core-cs-algorithms-sorting-complexity", text: "The average-case time complexity of quicksort is:", optionA: "O(n log n)", optionB: "O(n²)", optionC: "O(n)", optionD: "O(log n)", correctOption: "A", explanation: "Quicksort averages O(n log n), though its worst case is O(n²).", orderIndex: 12 },
  { id: "gate-core-cs-algorithms-sorting-complexity-q14", topicId: "gate-core-cs-algorithms-sorting-complexity", text: "Merge sort has a worst-case time complexity of:", optionA: "O(n log n)", optionB: "O(n²)", optionC: "O(n)", optionD: "O(log n)", correctOption: "A", explanation: "Merge sort is O(n log n) in all cases.", orderIndex: 13 },
  { id: "gate-core-cs-algorithms-sorting-complexity-q15", topicId: "gate-core-cs-algorithms-sorting-complexity", text: "The lower bound for comparison-based sorting is:", optionA: "Ω(n log n)", optionB: "Ω(n)", optionC: "Ω(log n)", optionD: "Ω(1)", correctOption: "A", explanation: "Any comparison sort needs at least Ω(n log n) comparisons.", orderIndex: 14 },
  { id: "gate-core-cs-algorithms-sorting-complexity-q16", topicId: "gate-core-cs-algorithms-sorting-complexity", text: "Which sorting algorithm is NOT comparison-based?", optionA: "Counting sort", optionB: "Quicksort", optionC: "Merge sort", optionD: "Heapsort", correctOption: "A", explanation: "Counting sort uses key values as indices, not comparisons, achieving O(n+k).", orderIndex: 15 },

  // ── Core CS: Operating Systems ──
  { id: "gate-core-cs-operating-systems-q13", topicId: "gate-core-cs-operating-systems", text: "A deadlock requires all four Coffman conditions, including circular wait and:", optionA: "Mutual exclusion", optionB: "Preemption", optionC: "Aging", optionD: "Paging", correctOption: "A", explanation: "The four conditions are mutual exclusion, hold and wait, no preemption and circular wait.", orderIndex: 12 },
  { id: "gate-core-cs-operating-systems-q14", topicId: "gate-core-cs-operating-systems", text: "Which scheduling algorithm gives the minimum average waiting time?", optionA: "Shortest Job First", optionB: "FCFS", optionC: "Round Robin", optionD: "Priority", correctOption: "A", explanation: "SJF is optimal for minimizing average waiting time.", orderIndex: 13 },

  // ── Core CS: DBMS & SQL ──
  { id: "gate-core-cs-dbms-sql-q15", topicId: "gate-core-cs-dbms-sql", text: "The SQL clause used to filter groups after aggregation is:", optionA: "HAVING", optionB: "WHERE", optionC: "GROUP BY", optionD: "ORDER BY", correctOption: "A", explanation: "HAVING filters aggregated groups; WHERE filters rows before grouping.", orderIndex: 14 },

  // ── Core CS: Computer Networks ──
  { id: "gate-core-cs-computer-networks-q13", topicId: "gate-core-cs-computer-networks", text: "How many layers does the OSI model have?", optionA: "7", optionB: "4", optionC: "5", optionD: "3", correctOption: "A", explanation: "The OSI reference model has 7 layers; TCP/IP has 4.", orderIndex: 12 },
  { id: "gate-core-cs-computer-networks-q14", topicId: "gate-core-cs-computer-networks", text: "Which protocol is connection-oriented and reliable?", optionA: "TCP", optionB: "UDP", optionC: "IP", optionD: "ICMP", correctOption: "A", explanation: "TCP is reliable and connection-oriented; UDP is neither.", orderIndex: 13 },
  { id: "gate-core-cs-computer-networks-q15", topicId: "gate-core-cs-computer-networks", text: "How many usable host addresses does a /24 subnet provide?", optionA: "254", optionB: "256", optionC: "252", optionD: "128", correctOption: "A", explanation: "2^(32−24) − 2 = 256 − 2 = 254 usable hosts.", orderIndex: 14 },
  { id: "gate-core-cs-computer-networks-q16", topicId: "gate-core-cs-computer-networks", text: "Which protocol resolves an IP address to a MAC address?", optionA: "ARP", optionB: "DNS", optionC: "DHCP", optionD: "ICMP", correctOption: "A", explanation: "ARP maps IP addresses to MAC (link-layer) addresses.", orderIndex: 15 },

  // ── Core CS: Theory of Computation ──
  { id: "gate-core-cs-theory-of-computation-q13", topicId: "gate-core-cs-theory-of-computation", text: "A DFA and an NFA recognise:", optionA: "Exactly the same class of languages", optionB: "Different classes", optionC: "Context-free languages", optionD: "Recursive languages only", correctOption: "A", explanation: "Every NFA has an equivalent DFA, so both accept the regular languages.", orderIndex: 12 },
  { id: "gate-core-cs-theory-of-computation-q14", topicId: "gate-core-cs-theory-of-computation", text: "The language { aⁿbⁿ : n ≥ 0 } is:", optionA: "Context-free but not regular", optionB: "Regular", optionC: "Finite", optionD: "Not context-free", correctOption: "A", explanation: "It needs a stack to count, so it is context-free but not regular.", orderIndex: 13 },
  { id: "gate-core-cs-theory-of-computation-q15", topicId: "gate-core-cs-theory-of-computation", text: "The pumping lemma is used to prove a language is:", optionA: "Not regular (or not context-free)", optionB: "Regular", optionC: "Finite", optionD: "Decidable", correctOption: "A", explanation: "The pumping lemma proves non-regularity (or non-context-freeness).", orderIndex: 14 },

  // ── Engineering Mathematics: Linear Algebra ──
  { id: "gate-engineering-mathematics-linear-algebra-q13", topicId: "gate-engineering-mathematics-linear-algebra", text: "A square matrix is invertible if and only if its determinant is:", optionA: "Non-zero", optionB: "Zero", optionC: "Positive", optionD: "An integer", correctOption: "A", explanation: "A matrix is invertible exactly when its determinant is non-zero.", orderIndex: 12 },
  { id: "gate-engineering-mathematics-linear-algebra-q14", topicId: "gate-engineering-mathematics-linear-algebra", text: "The eigenvalues of a triangular matrix are its:", optionA: "Diagonal entries", optionB: "Row sums", optionC: "Column sums", optionD: "Determinant", correctOption: "A", explanation: "For a triangular matrix, the eigenvalues are the diagonal elements.", orderIndex: 13 },
  { id: "gate-engineering-mathematics-linear-algebra-q15", topicId: "gate-engineering-mathematics-linear-algebra", text: "The rank of a matrix equals the number of:", optionA: "Linearly independent rows (or columns)", optionB: "Total entries", optionC: "Zero rows", optionD: "Diagonal entries", correctOption: "A", explanation: "Rank is the maximum number of linearly independent rows or columns.", orderIndex: 14 },

  // ── General Aptitude: Quantitative Aptitude ──
  { id: "gate-general-aptitude-quantitative-aptitude-q13", topicId: "gate-general-aptitude-quantitative-aptitude", text: "If a shirt costing 800 is sold at a 15% profit, the selling price is:", optionA: "920", optionB: "680", optionC: "915", optionD: "880", correctOption: "A", explanation: "SP = 800 × 1.15 = 920.", orderIndex: 12 },
  { id: "gate-general-aptitude-quantitative-aptitude-q14", topicId: "gate-general-aptitude-quantitative-aptitude", text: "The average of the first 10 natural numbers is:", optionA: "5.5", optionB: "5", optionC: "10", optionD: "55", correctOption: "A", explanation: "Sum = 55, average = 55/10 = 5.5.", orderIndex: 13 },
  { id: "gate-general-aptitude-quantitative-aptitude-q15", topicId: "gate-general-aptitude-quantitative-aptitude", text: "A train 120 m long travelling at 36 km/h crosses a pole in:", optionA: "12 seconds", optionB: "10 seconds", optionC: "6 seconds", optionD: "15 seconds", correctOption: "A", explanation: "36 km/h = 10 m/s; time = 120/10 = 12 s.", orderIndex: 14 },
  { id: "gate-general-aptitude-quantitative-aptitude-q16", topicId: "gate-general-aptitude-quantitative-aptitude", text: "What is 25% of 240?", optionA: "60", optionB: "48", optionC: "65", optionD: "50", correctOption: "A", explanation: "25% of 240 = 0.25 × 240 = 60.", orderIndex: 15 },

  // ── Core CS: Compiler Design ──
  { id: "gate-core-cs-compiler-design-q13", topicId: "gate-core-cs-compiler-design", text: "The phase of a compiler that groups tokens into grammatical structures is:", optionA: "Syntax analysis (parsing)", optionB: "Lexical analysis", optionC: "Code generation", optionD: "Optimization", correctOption: "A", explanation: "The parser (syntax analysis) builds the parse tree from tokens.", orderIndex: 12 },
  { id: "gate-core-cs-compiler-design-q14", topicId: "gate-core-cs-compiler-design", text: "Lexical analysis produces a stream of:", optionA: "Tokens", optionB: "Machine code", optionC: "Parse trees", optionD: "Three-address code", correctOption: "A", explanation: "The lexical analyzer (scanner) converts source characters into tokens.", orderIndex: 13 },
  { id: "gate-core-cs-compiler-design-q15", topicId: "gate-core-cs-compiler-design", text: "LR parsers are ____ parsers.", optionA: "Bottom-up", optionB: "Top-down", optionC: "Recursive-descent", optionD: "Predictive", correctOption: "A", explanation: "LR (and SLR/LALR) parsers work bottom-up.", orderIndex: 14 },
  { id: "gate-core-cs-compiler-design-q16", topicId: "gate-core-cs-compiler-design", text: "A left-recursive grammar must be modified before using which parser?", optionA: "Top-down (LL) parser", optionB: "LR parser", optionC: "LALR parser", optionD: "Bottom-up parser", correctOption: "A", explanation: "LL/top-down parsers cannot handle left recursion; it must be removed.", orderIndex: 15 },

  // ── Core CS: Digital Logic ──
  { id: "gate-core-cs-digital-logic-q13", topicId: "gate-core-cs-digital-logic", text: "A NAND gate is functionally complete because it can build:", optionA: "Any logic function", optionB: "Only AND", optionC: "Only OR", optionD: "Nothing", correctOption: "A", explanation: "NAND (and NOR) are universal gates that can implement any Boolean function.", orderIndex: 12 },
  { id: "gate-core-cs-digital-logic-q14", topicId: "gate-core-cs-digital-logic", text: "How many select lines does an 8-to-1 multiplexer need?", optionA: "3", optionB: "8", optionC: "2", optionD: "4", correctOption: "A", explanation: "A 2ⁿ-to-1 mux needs n select lines; 8 = 2³ needs 3.", orderIndex: 13 },
  { id: "gate-core-cs-digital-logic-q15", topicId: "gate-core-cs-digital-logic", text: "A flip-flop stores how many bits?", optionA: "1", optionB: "2", optionC: "4", optionD: "8", correctOption: "A", explanation: "A flip-flop is a 1-bit memory element.", orderIndex: 14 },
  { id: "gate-core-cs-digital-logic-q16", topicId: "gate-core-cs-digital-logic", text: "In 2's complement, the range of an n-bit signed number is:", optionA: "−2^(n−1) to 2^(n−1) − 1", optionB: "0 to 2ⁿ", optionC: "−2ⁿ to 2ⁿ", optionD: "−2ⁿ to 0", correctOption: "A", explanation: "n-bit two's complement spans −2^(n−1) to 2^(n−1) − 1.", orderIndex: 15 },

  // ── Core CS: Computer Organization & Architecture ──
  { id: "gate-core-cs-computer-organization-architecture-q13", topicId: "gate-core-cs-computer-organization-architecture", text: "An n-stage pipeline ideally provides a speedup of up to:", optionA: "n", optionB: "n²", optionC: "log n", optionD: "2n", correctOption: "A", explanation: "An ideal n-stage pipeline gives up to an n-fold speedup.", orderIndex: 12 },
  { id: "gate-core-cs-computer-organization-architecture-q14", topicId: "gate-core-cs-computer-organization-architecture", text: "With n address lines, how many memory locations can be addressed?", optionA: "2ⁿ", optionB: "n", optionC: "2n", optionD: "n²", correctOption: "A", explanation: "n address lines address 2ⁿ locations.", orderIndex: 13 },
  { id: "gate-core-cs-computer-organization-architecture-q15", topicId: "gate-core-cs-computer-organization-architecture", text: "A cache 'hit ratio' is the fraction of accesses:", optionA: "Found in the cache", optionB: "That miss", optionC: "Written to disk", optionD: "To registers", correctOption: "A", explanation: "The hit ratio is the proportion of memory accesses served by the cache.", orderIndex: 14 },
  { id: "gate-core-cs-computer-organization-architecture-q16", topicId: "gate-core-cs-computer-organization-architecture", text: "A data hazard in a pipeline arises when an instruction depends on the result of a:", optionA: "Previous incomplete instruction", optionB: "Future instruction", optionC: "Cache miss only", optionD: "Branch only", correctOption: "A", explanation: "Data hazards occur when an instruction needs data not yet produced by an earlier one.", orderIndex: 15 },

  // ── Core CS: Programming & Recursion in C ──
  { id: "gate-core-cs-programming-recursion-c-q13", topicId: "gate-core-cs-programming-recursion-c", text: "A recursive function must have a:", optionA: "Base case", optionB: "Global variable", optionC: "Pointer", optionD: "Loop", correctOption: "A", explanation: "A base case stops the recursion; without it the recursion is infinite.", orderIndex: 12 },
  { id: "gate-core-cs-programming-recursion-c-q14", topicId: "gate-core-cs-programming-recursion-c", text: "In C, parameters are passed by default using:", optionA: "Call by value", optionB: "Call by reference", optionC: "Call by name", optionD: "Call by need", correctOption: "A", explanation: "C passes arguments by value; references are simulated with pointers.", orderIndex: 13 },
  { id: "gate-core-cs-programming-recursion-c-q15", topicId: "gate-core-cs-programming-recursion-c", text: "Recursive calls use which data structure internally?", optionA: "Stack (call stack)", optionB: "Queue", optionC: "Heap only", optionD: "Tree", correctOption: "A", explanation: "Function activation records are stored on the call stack.", orderIndex: 14 },
  { id: "gate-core-cs-programming-recursion-c-q16", topicId: "gate-core-cs-programming-recursion-c", text: "A pointer in C stores a:", optionA: "Memory address", optionB: "Value only", optionC: "Function name", optionD: "Data type", correctOption: "A", explanation: "A pointer holds the memory address of another variable.", orderIndex: 15 },

  // ── Engineering Mathematics: Probability ──
  { id: "gate-engineering-mathematics-probability-q13", topicId: "gate-engineering-mathematics-probability", text: "For independent events A and B, P(A ∩ B) equals:", optionA: "P(A)·P(B)", optionB: "P(A) + P(B)", optionC: "P(A) − P(B)", optionD: "P(A)/P(B)", correctOption: "A", explanation: "Independent events multiply: P(A ∩ B) = P(A)P(B).", orderIndex: 12 },
  { id: "gate-engineering-mathematics-probability-q14", topicId: "gate-engineering-mathematics-probability", text: "The expected value of a fair six-sided die is:", optionA: "3.5", optionB: "3", optionC: "6", optionD: "4", correctOption: "A", explanation: "E[X] = (1+2+3+4+5+6)/6 = 3.5.", orderIndex: 13 },
  { id: "gate-engineering-mathematics-probability-q15", topicId: "gate-engineering-mathematics-probability", text: "The mean of a binomial distribution B(n, p) is:", optionA: "np", optionB: "np(1−p)", optionC: "p/n", optionD: "n/p", correctOption: "A", explanation: "The binomial mean is np.", orderIndex: 14 },
  { id: "gate-engineering-mathematics-probability-q16", topicId: "gate-engineering-mathematics-probability", text: "The probability of getting at least one head in two fair coin tosses is:", optionA: "3/4", optionB: "1/2", optionC: "1/4", optionD: "1", correctOption: "A", explanation: "P(at least one head) = 1 − P(no heads) = 1 − 1/4 = 3/4.", orderIndex: 15 },

  // ── Engineering Mathematics: Calculus ──
  { id: "gate-engineering-mathematics-calculus-q14", topicId: "gate-engineering-mathematics-calculus", text: "The value of ∫ 1/x dx is:", optionA: "ln|x| + C", optionB: "x²/2 + C", optionC: "−1/x² + C", optionD: "1/x + C", correctOption: "A", explanation: "The integral of 1/x is ln|x| + C.", orderIndex: 13 },
  { id: "gate-engineering-mathematics-calculus-q15", topicId: "gate-engineering-mathematics-calculus", text: "The limit of (sin x)/x as x → 0 is:", optionA: "1", optionB: "0", optionC: "∞", optionD: "Undefined", correctOption: "A", explanation: "The standard limit lim_{x→0}(sin x)/x = 1.", orderIndex: 14 },
  { id: "gate-engineering-mathematics-calculus-q16", topicId: "gate-engineering-mathematics-calculus", text: "At a local maximum of a smooth function, the first derivative is:", optionA: "Zero", optionB: "Positive", optionC: "Negative", optionD: "Undefined", correctOption: "A", explanation: "At a smooth local extremum the first derivative equals zero.", orderIndex: 15 },

  // ── General Aptitude: Data Interpretation ──
  { id: "gate-general-aptitude-data-interpretation-q13", topicId: "gate-general-aptitude-data-interpretation", text: "In a pie chart, a sector of 90° represents what fraction of the total?", optionA: "1/4", optionB: "1/2", optionC: "1/3", optionD: "1/8", correctOption: "A", explanation: "90°/360° = 1/4 of the total.", orderIndex: 12 },
  { id: "gate-general-aptitude-data-interpretation-q14", topicId: "gate-general-aptitude-data-interpretation", text: "If sales rose from 200 to 260, the percentage growth is:", optionA: "30%", optionB: "26%", optionC: "60%", optionD: "13%", correctOption: "A", explanation: "Growth = 60/200 × 100 = 30%.", orderIndex: 13 },
  { id: "gate-general-aptitude-data-interpretation-q15", topicId: "gate-general-aptitude-data-interpretation", text: "The average of 10, 20, 30 and 40 is:", optionA: "25", optionB: "30", optionC: "20", optionD: "100", correctOption: "A", explanation: "Sum is 100; divide by 4 items to get 25.", orderIndex: 14 },
  { id: "gate-general-aptitude-data-interpretation-q16", topicId: "gate-general-aptitude-data-interpretation", text: "A sector of 45° in a pie chart corresponds to what percentage?", optionA: "12.5%", optionB: "25%", optionC: "45%", optionD: "10%", correctOption: "A", explanation: "45/360 × 100 = 12.5%.", orderIndex: 15 },

  // ── Programming & DS: Dynamic Programming ──
  { id: "gate-programming-ds-dynamic-programming-q13", topicId: "gate-programming-ds-dynamic-programming", text: "Dynamic programming solves problems with overlapping subproblems and:", optionA: "Optimal substructure", optionB: "No structure", optionC: "Randomization", optionD: "Only greedy choices", correctOption: "A", explanation: "DP applies when a problem has overlapping subproblems and optimal substructure.", orderIndex: 12 },
  { id: "gate-programming-ds-dynamic-programming-q14", topicId: "gate-programming-ds-dynamic-programming", text: "Storing subproblem results to avoid recomputation is called:", optionA: "Memoization", optionB: "Recursion", optionC: "Backtracking", optionD: "Hashing", correctOption: "A", explanation: "Memoization caches computed subproblem results.", orderIndex: 13 },
  { id: "gate-programming-ds-dynamic-programming-q15", topicId: "gate-programming-ds-dynamic-programming", text: "The 0/1 knapsack problem is typically solved using:", optionA: "Dynamic programming", optionB: "A greedy algorithm always", optionC: "Binary search", optionD: "DFS only", correctOption: "A", explanation: "The 0/1 knapsack has optimal substructure and is solved with DP.", orderIndex: 14 },
  { id: "gate-programming-ds-dynamic-programming-q16", topicId: "gate-programming-ds-dynamic-programming", text: "The time complexity of the standard DP for the longest common subsequence of strings of length m and n is:", optionA: "O(mn)", optionB: "O(m + n)", optionC: "O(2^n)", optionD: "O(log mn)", correctOption: "A", explanation: "The LCS DP fills an m×n table, giving O(mn) time.", orderIndex: 15 }
];
