// JEE Main depth top-up. Adds four more questions (q09–q12) to every existing
// JEE Main reading so each reaches the 12-question standard used across the
// catalog. No new topics or materials — these attach to existing readings.
import type { Question } from "@jyotir/core";

export const mainTopUpQuestions: Question[] = [
  // ── Physics ──
  // Kinematics 1D
  { id: "jee-physics-kinematics-1d-q09", topicId: "jee-physics-kinematics-1d", text: "The area under a velocity–time graph represents:", optionA: "Acceleration", optionB: "Displacement", optionC: "Jerk", optionD: "Force", correctOption: "B", explanation: "The area under a v–t graph gives the displacement.", orderIndex: 8 },
  { id: "jee-physics-kinematics-1d-q10", topicId: "jee-physics-kinematics-1d", text: "For a body under constant acceleration, v² = u² + 2as is the:", optionA: "First equation of motion", optionB: "Third equation of motion", optionC: "Second equation", optionD: "Continuity equation", correctOption: "B", explanation: "v² = u² + 2as is the third equation of motion (independent of time).", orderIndex: 9 },
  { id: "jee-physics-kinematics-1d-q11", topicId: "jee-physics-kinematics-1d", text: "The slope of a position–time graph gives:", optionA: "Velocity", optionB: "Acceleration", optionC: "Distance", optionD: "Force", correctOption: "A", explanation: "The slope of an x–t graph is the velocity.", orderIndex: 10 },
  { id: "jee-physics-kinematics-1d-q12", topicId: "jee-physics-kinematics-1d", text: "A body dropped from rest falls a distance in the first second proportional to:", optionA: "g/2", optionB: "g", optionC: "2g", optionD: "g²", correctOption: "A", explanation: "s = ½gt²; for t = 1 s, s = g/2.", orderIndex: 11 },
  // Rotational motion
  { id: "jee-physics-rotational-motion-q09", topicId: "jee-physics-rotational-motion", text: "The moment of inertia of a solid disc about its central axis is:", optionA: "½MR²", optionB: "MR²", optionC: "(2/5)MR²", optionD: "(1/3)MR²", correctOption: "A", explanation: "A uniform disc has I = ½MR² about its central axis.", orderIndex: 8 },
  { id: "jee-physics-rotational-motion-q10", topicId: "jee-physics-rotational-motion", text: "Angular momentum is conserved when the net external torque is:", optionA: "Zero", optionB: "Maximum", optionC: "Constant nonzero", optionD: "Negative", correctOption: "A", explanation: "L is conserved in the absence of a net external torque.", orderIndex: 9 },
  { id: "jee-physics-rotational-motion-q11", topicId: "jee-physics-rotational-motion", text: "For rolling without slipping, the condition is:", optionA: "v = ωR", optionB: "v = ω/R", optionC: "v = ωR²", optionD: "v = R/ω", correctOption: "A", explanation: "Rolling without slipping requires v = ωR.", orderIndex: 10 },
  { id: "jee-physics-rotational-motion-q12", topicId: "jee-physics-rotational-motion", text: "The radius of gyration k is defined by:", optionA: "I = Mk²", optionB: "I = Mk", optionC: "k = MR", optionD: "I = k/M", correctOption: "A", explanation: "The radius of gyration satisfies I = Mk².", orderIndex: 11 },
  // Laws of motion
  { id: "jee-physics-laws-of-motion-q09", topicId: "jee-physics-laws-of-motion", text: "Impulse equals the change in:", optionA: "Momentum", optionB: "Kinetic energy", optionC: "Velocity only", optionD: "Force", correctOption: "A", explanation: "Impulse = ∫F dt = change in momentum.", orderIndex: 8 },
  { id: "jee-physics-laws-of-motion-q10", topicId: "jee-physics-laws-of-motion", text: "Limiting static friction equals:", optionA: "μ_s N", optionB: "μ_k N", optionC: "zero", optionD: "mg always", correctOption: "A", explanation: "Maximum static friction is μ_s N, usually greater than kinetic friction.", orderIndex: 9 },
  { id: "jee-physics-laws-of-motion-q11", topicId: "jee-physics-laws-of-motion", text: "In a frame accelerating with acceleration a, the pseudo-force on mass m is:", optionA: "ma opposite to a", optionB: "ma along a", optionC: "zero", optionD: "mg", correctOption: "A", explanation: "A pseudo-force of magnitude ma acts opposite to the frame's acceleration.", orderIndex: 10 },
  { id: "jee-physics-laws-of-motion-q12", topicId: "jee-physics-laws-of-motion", text: "The maximum speed of a car on a level circular road of radius r depends on:", optionA: "√(μrg)", optionB: "μrg", optionC: "rg", optionD: "μg/r", correctOption: "A", explanation: "Friction provides centripetal force, so v_max = √(μrg).", orderIndex: 11 },
  // Work energy power
  { id: "jee-physics-work-energy-power-q09", topicId: "jee-physics-work-energy-power", text: "The work–energy theorem states net work equals change in:", optionA: "Kinetic energy", optionB: "Potential energy", optionC: "Momentum", optionD: "Power", correctOption: "A", explanation: "Net work done equals the change in kinetic energy.", orderIndex: 8 },
  { id: "jee-physics-work-energy-power-q10", topicId: "jee-physics-work-energy-power", text: "The SI unit of power is the:", optionA: "Watt", optionB: "Joule", optionC: "Newton", optionD: "Pascal", correctOption: "A", explanation: "Power is measured in watts (1 W = 1 J/s).", orderIndex: 9 },
  { id: "jee-physics-work-energy-power-q11", topicId: "jee-physics-work-energy-power", text: "A conservative force is one for which the work done in a closed loop is:", optionA: "Zero", optionB: "Maximum", optionC: "Negative", optionD: "Path-dependent", correctOption: "A", explanation: "For a conservative force, work over any closed path is zero.", orderIndex: 10 },
  { id: "jee-physics-work-energy-power-q12", topicId: "jee-physics-work-energy-power", text: "The power delivered by a force F to a body moving with velocity v is:", optionA: "F·v", optionB: "F/v", optionC: "F + v", optionD: "Fv²", correctOption: "A", explanation: "Instantaneous power P = F·v (dot product).", orderIndex: 11 },
  // Gravitation
  { id: "jee-physics-gravitation-q09", topicId: "jee-physics-gravitation", text: "The escape velocity from Earth is about:", optionA: "11.2 km/s", optionB: "7.9 km/s", optionC: "3 km/s", optionD: "1 km/s", correctOption: "A", explanation: "Earth's escape velocity is approximately 11.2 km/s.", orderIndex: 8 },
  { id: "jee-physics-gravitation-q10", topicId: "jee-physics-gravitation", text: "The orbital velocity of a satellite close to Earth's surface is about:", optionA: "7.9 km/s", optionB: "11.2 km/s", optionC: "1 km/s", optionD: "30 km/s", correctOption: "A", explanation: "Low-orbit satellites move at about 7.9 km/s (first cosmic velocity).", orderIndex: 9 },
  { id: "jee-physics-gravitation-q11", topicId: "jee-physics-gravitation", text: "Kepler's third law states T² is proportional to:", optionA: "r³", optionB: "r²", optionC: "r", optionD: "1/r", correctOption: "A", explanation: "The square of the orbital period is proportional to the cube of the semi-major axis.", orderIndex: 10 },
  { id: "jee-physics-gravitation-q12", topicId: "jee-physics-gravitation", text: "The value of g at a height h above the surface (h << R) changes approximately by a factor:", optionA: "(1 − 2h/R)", optionB: "(1 + 2h/R)", optionC: "(1 − h/R)", optionD: "(1 + h/R)", correctOption: "A", explanation: "g at height h is g(1 − 2h/R) to first order for small h.", orderIndex: 11 },
  // SHM & Waves
  { id: "jee-physics-shm-waves-q09", topicId: "jee-physics-shm-waves", text: "The time period of a simple pendulum is:", optionA: "2π√(L/g)", optionB: "2π√(g/L)", optionC: "2π√(m/k)", optionD: "2πLg", correctOption: "A", explanation: "For a simple pendulum, T = 2π√(L/g).", orderIndex: 8 },
  { id: "jee-physics-shm-waves-q10", topicId: "jee-physics-shm-waves", text: "The time period of a mass–spring system is:", optionA: "2π√(m/k)", optionB: "2π√(k/m)", optionC: "2π√(L/g)", optionD: "2πmk", correctOption: "A", explanation: "For a spring of constant k and mass m, T = 2π√(m/k).", orderIndex: 9 },
  { id: "jee-physics-shm-waves-q11", topicId: "jee-physics-shm-waves", text: "Beats are produced by superposition of two waves of slightly different:", optionA: "Frequencies", optionB: "Amplitudes", optionC: "Directions", optionD: "Phases only", correctOption: "A", explanation: "Beats arise from two waves of nearly equal but different frequencies.", orderIndex: 10 },
  { id: "jee-physics-shm-waves-q12", topicId: "jee-physics-shm-waves", text: "In a stationary wave, the distance between two consecutive nodes is:", optionA: "λ/2", optionB: "λ", optionC: "λ/4", optionD: "2λ", correctOption: "A", explanation: "Consecutive nodes (or antinodes) are separated by half a wavelength.", orderIndex: 11 },
  // Electrostatics
  { id: "jee-physics-electrostatics-q09", topicId: "jee-physics-electrostatics", text: "The electric field inside a conductor in electrostatic equilibrium is:", optionA: "Zero", optionB: "Maximum", optionC: "Uniform nonzero", optionD: "Infinite", correctOption: "A", explanation: "The field inside a conductor is zero at equilibrium.", orderIndex: 8 },
  { id: "jee-physics-electrostatics-q10", topicId: "jee-physics-electrostatics", text: "The energy stored in a capacitor is:", optionA: "½CV²", optionB: "CV", optionC: "½C²V", optionD: "CV²", correctOption: "A", explanation: "Energy = ½CV² = ½QV = Q²/2C.", orderIndex: 9 },
  { id: "jee-physics-electrostatics-q11", topicId: "jee-physics-electrostatics", text: "Inserting a dielectric of constant K increases capacitance by a factor:", optionA: "K", optionB: "1/K", optionC: "K²", optionD: "√K", correctOption: "A", explanation: "A dielectric raises capacitance to KC₀.", orderIndex: 10 },
  { id: "jee-physics-electrostatics-q12", topicId: "jee-physics-electrostatics", text: "Electric field due to an infinite charged plane sheet is:", optionA: "σ/2ε₀ (independent of distance)", optionB: "σ/ε₀", optionC: "kQ/r²", optionD: "zero", correctOption: "A", explanation: "An infinite sheet gives a uniform field σ/2ε₀.", orderIndex: 11 },
  // Current electricity
  { id: "jee-physics-current-electricity-q09", topicId: "jee-physics-current-electricity", text: "Kirchhoff's junction rule is based on conservation of:", optionA: "Charge", optionB: "Energy", optionC: "Momentum", optionD: "Mass", correctOption: "A", explanation: "The junction (current) rule expresses charge conservation.", orderIndex: 8 },
  { id: "jee-physics-current-electricity-q10", topicId: "jee-physics-current-electricity", text: "The power dissipated in a resistor R carrying current I is:", optionA: "I²R", optionB: "IR", optionC: "I/R", optionD: "R/I²", correctOption: "A", explanation: "Power P = I²R = V²/R = VI (Joule heating).", orderIndex: 9 },
  { id: "jee-physics-current-electricity-q11", topicId: "jee-physics-current-electricity", text: "Resistances in parallel combine as:", optionA: "1/R = 1/R₁ + 1/R₂", optionB: "R = R₁ + R₂", optionC: "R = R₁R₂", optionD: "R = R₁ − R₂", correctOption: "A", explanation: "For parallel resistors, the reciprocals add.", orderIndex: 10 },
  { id: "jee-physics-current-electricity-q12", topicId: "jee-physics-current-electricity", text: "The drift velocity of electrons in a conductor is proportional to the:", optionA: "Applied electric field", optionB: "Square of the field", optionC: "Resistance", optionD: "Temperature only", correctOption: "A", explanation: "Drift velocity v_d = (eE/m)τ is proportional to the applied field.", orderIndex: 11 },
  // Magnetism & EMI
  { id: "jee-physics-magnetism-emi-q09", topicId: "jee-physics-magnetism-emi", text: "The force on a current-carrying conductor of length L in a field B is:", optionA: "BIL sinθ", optionB: "BIL²", optionC: "B/IL", optionD: "IL/B", correctOption: "A", explanation: "F = BIL sinθ, maximal when the current is perpendicular to B.", orderIndex: 8 },
  { id: "jee-physics-magnetism-emi-q10", topicId: "jee-physics-magnetism-emi", text: "Faraday's law gives the induced EMF as the rate of change of:", optionA: "Magnetic flux", optionB: "Charge", optionC: "Current", optionD: "Resistance", correctOption: "A", explanation: "Induced EMF = −dΦ/dt.", orderIndex: 9 },
  { id: "jee-physics-magnetism-emi-q11", topicId: "jee-physics-magnetism-emi", text: "The magnetic field at the centre of a circular current loop of radius r is proportional to:", optionA: "I/r", optionB: "I/r²", optionC: "Ir", optionD: "I²/r", correctOption: "A", explanation: "B = μ₀I/2r at the centre, proportional to I/r.", orderIndex: 10 },
  { id: "jee-physics-magnetism-emi-q12", topicId: "jee-physics-magnetism-emi", text: "Lenz's law is a consequence of conservation of:", optionA: "Energy", optionB: "Charge", optionC: "Momentum", optionD: "Mass", correctOption: "A", explanation: "Lenz's law (opposing the flux change) ensures energy conservation.", orderIndex: 11 },
  // Optics
  { id: "jee-physics-optics-q09", topicId: "jee-physics-optics", text: "The power of a lens is measured in:", optionA: "Dioptre", optionB: "Watt", optionC: "Newton", optionD: "Joule", correctOption: "A", explanation: "Lens power P = 1/f (in metres) is measured in dioptres.", orderIndex: 8 },
  { id: "jee-physics-optics-q10", topicId: "jee-physics-optics", text: "In Young's double-slit, the fringe width is:", optionA: "λD/d", optionB: "λd/D", optionC: "dD/λ", optionD: "λ/dD", correctOption: "A", explanation: "Fringe width β = λD/d.", orderIndex: 9 },
  { id: "jee-physics-optics-q11", topicId: "jee-physics-optics", text: "Total internal reflection occurs when the angle of incidence exceeds the:", optionA: "Critical angle", optionB: "Brewster angle", optionC: "Polarising angle", optionD: "45° always", correctOption: "A", explanation: "Beyond the critical angle, light undergoes total internal reflection.", orderIndex: 10 },
  { id: "jee-physics-optics-q12", topicId: "jee-physics-optics", text: "The refractive index of a medium equals:", optionA: "c/v (speed in vacuum / speed in medium)", optionB: "v/c", optionC: "frequency ratio", optionD: "wavelength product", correctOption: "A", explanation: "μ = c/v, the ratio of the speed of light in vacuum to that in the medium.", orderIndex: 11 },
  // Modern physics
  { id: "jee-physics-modern-physics-q09", topicId: "jee-physics-modern-physics", text: "The photoelectric equation gives KE_max as:", optionA: "hν − φ", optionB: "hν + φ", optionC: "φ − hν", optionD: "hν", correctOption: "A", explanation: "Einstein's equation: KE_max = hν − φ.", orderIndex: 8 },
  { id: "jee-physics-modern-physics-q10", topicId: "jee-physics-modern-physics", text: "The de Broglie wavelength is:", optionA: "h/p", optionB: "hp", optionC: "p/h", optionD: "h/p²", correctOption: "A", explanation: "λ = h/p relates wavelength to momentum.", orderIndex: 9 },
  { id: "jee-physics-modern-physics-q11", topicId: "jee-physics-modern-physics", text: "The energy of the nth hydrogen level is proportional to:", optionA: "−1/n²", optionB: "−n²", optionC: "−1/n", optionD: "−n", correctOption: "A", explanation: "The Bohr energy level is Eₙ = −13.6/n² eV, so it scales as −1/n².", orderIndex: 10 },
  { id: "jee-physics-modern-physics-q12", topicId: "jee-physics-modern-physics", text: "The half-life of a radioactive sample with decay constant λ is:", optionA: "0.693/λ", optionB: "λ/0.693", optionC: "1/λ²", optionD: "λ²", correctOption: "A", explanation: "Half-life t½ = ln2/λ = 0.693/λ.", orderIndex: 11 },
  // Thermodynamics (physics)
  { id: "jee-physics-thermodynamics-q09", topicId: "jee-physics-thermodynamics", text: "The first law of thermodynamics is:", optionA: "ΔU = Q − W", optionB: "Q = ΔU × W", optionC: "W = QΔU", optionD: "ΔU = QW", correctOption: "A", explanation: "ΔU = Q − W (W is work done by the gas).", orderIndex: 8 },
  { id: "jee-physics-thermodynamics-q10", topicId: "jee-physics-thermodynamics", text: "In an adiabatic process:", optionA: "Q = 0", optionB: "ΔU = 0", optionC: "W = 0", optionD: "T = constant", correctOption: "A", explanation: "No heat is exchanged in an adiabatic process (Q = 0).", orderIndex: 9 },
  { id: "jee-physics-thermodynamics-q11", topicId: "jee-physics-thermodynamics", text: "Carnot efficiency between temperatures T_h and T_c is:", optionA: "1 − T_c/T_h", optionB: "T_c/T_h", optionC: "1 − T_h/T_c", optionD: "T_h/T_c", correctOption: "A", explanation: "η = 1 − T_c/T_h with temperatures in kelvin.", orderIndex: 10 },
  { id: "jee-physics-thermodynamics-q12", topicId: "jee-physics-thermodynamics", text: "For an isothermal process of an ideal gas:", optionA: "ΔU = 0", optionB: "Q = 0", optionC: "W = 0", optionD: "T doubles", correctOption: "A", explanation: "At constant temperature, ΔU = 0 for an ideal gas, so Q = W.", orderIndex: 11 },
  // Units & dimensions
  { id: "jee-physics-units-dimensions-q09", topicId: "jee-physics-units-dimensions", text: "The dimensional formula of force is:", optionA: "MLT⁻²", optionB: "ML²T⁻²", optionC: "MLT⁻¹", optionD: "ML⁻¹T⁻²", correctOption: "A", explanation: "Force = mass × acceleration = MLT⁻².", orderIndex: 8 },
  { id: "jee-physics-units-dimensions-q10", topicId: "jee-physics-units-dimensions", text: "The number of SI base units is:", optionA: "7", optionB: "5", optionC: "9", optionD: "3", correctOption: "A", explanation: "The SI system has seven base units.", orderIndex: 9 },
  { id: "jee-physics-units-dimensions-q11", topicId: "jee-physics-units-dimensions", text: "The dimensional formula of energy is:", optionA: "ML²T⁻²", optionB: "MLT⁻²", optionC: "ML²T⁻¹", optionD: "MLT⁻¹", correctOption: "A", explanation: "Energy = force × distance = ML²T⁻².", orderIndex: 10 },
  { id: "jee-physics-units-dimensions-q12", topicId: "jee-physics-units-dimensions", text: "A dimensionless physical quantity is:", optionA: "Strain", optionB: "Force", optionC: "Velocity", optionD: "Momentum", correctOption: "A", explanation: "Strain is a ratio of lengths and is dimensionless.", orderIndex: 11 },
  // Fluid mechanics
  { id: "jee-physics-fluid-mechanics-q09", topicId: "jee-physics-fluid-mechanics", text: "Bernoulli's theorem is based on conservation of:", optionA: "Energy", optionB: "Charge", optionC: "Momentum", optionD: "Mass only", correctOption: "A", explanation: "Bernoulli's equation is a statement of energy conservation for streamline flow.", orderIndex: 8 },
  { id: "jee-physics-fluid-mechanics-q10", topicId: "jee-physics-fluid-mechanics", text: "The buoyant force on a submerged body equals the weight of:", optionA: "The fluid displaced", optionB: "The body", optionC: "The container", optionD: "Air above", correctOption: "A", explanation: "Archimedes' principle: buoyant force = weight of displaced fluid.", orderIndex: 9 },
  { id: "jee-physics-fluid-mechanics-q11", topicId: "jee-physics-fluid-mechanics", text: "The equation of continuity (Av = constant) expresses conservation of:", optionA: "Mass", optionB: "Energy", optionC: "Momentum", optionD: "Charge", correctOption: "A", explanation: "Continuity A₁v₁ = A₂v₂ reflects mass conservation for incompressible flow.", orderIndex: 10 },
  { id: "jee-physics-fluid-mechanics-q12", topicId: "jee-physics-fluid-mechanics", text: "Stokes' law gives the viscous drag on a sphere as:", optionA: "6πηrv", optionB: "πr²v", optionC: "ρgh", optionD: "½ρv²", correctOption: "A", explanation: "Stokes' law: F = 6πηrv.", orderIndex: 11 },
  // Thermal properties
  { id: "jee-physics-thermal-properties-q09", topicId: "jee-physics-thermal-properties", text: "The coefficient of volume expansion γ relates to linear α by:", optionA: "γ = 3α", optionB: "γ = α", optionC: "γ = 2α", optionD: "γ = α/3", correctOption: "A", explanation: "For isotropic solids, γ = 3α.", orderIndex: 8 },
  { id: "jee-physics-thermal-properties-q10", topicId: "jee-physics-thermal-properties", text: "Heat transfer requiring no medium is:", optionA: "Radiation", optionB: "Conduction", optionC: "Convection", optionD: "Diffusion", correctOption: "A", explanation: "Radiation transfers heat via electromagnetic waves and needs no medium.", orderIndex: 9 },
  { id: "jee-physics-thermal-properties-q11", topicId: "jee-physics-thermal-properties", text: "The Stefan–Boltzmann law states radiated power is proportional to:", optionA: "T⁴", optionB: "T", optionC: "T²", optionD: "1/T", correctOption: "A", explanation: "A body radiates power proportional to T⁴.", orderIndex: 10 },
  { id: "jee-physics-thermal-properties-q12", topicId: "jee-physics-thermal-properties", text: "Latent heat is associated with a:", optionA: "Phase change at constant temperature", optionB: "Temperature rise", optionC: "Pressure change only", optionD: "Volume change only", correctOption: "A", explanation: "Latent heat accompanies phase changes with no change in temperature.", orderIndex: 11 },
  // Kinetic theory
  { id: "jee-physics-kinetic-theory-q09", topicId: "jee-physics-kinetic-theory", text: "The average kinetic energy of a gas molecule is proportional to:", optionA: "Absolute temperature", optionB: "Pressure", optionC: "Volume", optionD: "Molar mass", correctOption: "A", explanation: "Average KE = (3/2)kT, proportional to absolute temperature.", orderIndex: 8 },
  { id: "jee-physics-kinetic-theory-q10", topicId: "jee-physics-kinetic-theory", text: "The rms speed of gas molecules is proportional to:", optionA: "√T", optionB: "T", optionC: "T²", optionD: "1/T", correctOption: "A", explanation: "v_rms = √(3RT/M) ∝ √T.", orderIndex: 9 },
  { id: "jee-physics-kinetic-theory-q11", topicId: "jee-physics-kinetic-theory", text: "For a monatomic gas, the ratio of specific heats γ is:", optionA: "5/3", optionB: "7/5", optionC: "4/3", optionD: "1", correctOption: "A", explanation: "A monatomic gas (3 degrees of freedom) has γ = 5/3.", orderIndex: 10 },
  { id: "jee-physics-kinetic-theory-q12", topicId: "jee-physics-kinetic-theory", text: "Each degree of freedom contributes an average energy of:", optionA: "½kT", optionB: "kT", optionC: "(3/2)kT", optionD: "2kT", correctOption: "A", explanation: "Equipartition assigns ½kT per degree of freedom.", orderIndex: 11 },
  // Elasticity & surface tension
  { id: "jee-physics-elasticity-surface-tension-q09", topicId: "jee-physics-elasticity-surface-tension", text: "Young's modulus is the ratio of:", optionA: "Longitudinal stress to longitudinal strain", optionB: "Volume stress to volume strain", optionC: "Shear stress to shear strain", optionD: "Force to area only", correctOption: "A", explanation: "Y = longitudinal stress/strain, measuring stiffness in length.", orderIndex: 8 },
  { id: "jee-physics-elasticity-surface-tension-q10", topicId: "jee-physics-elasticity-surface-tension", text: "Within the elastic limit, stress is proportional to strain — this is:", optionA: "Hooke's law", optionB: "Pascal's law", optionC: "Bernoulli's theorem", optionD: "Stokes' law", correctOption: "A", explanation: "Hooke's law: stress ∝ strain within the elastic limit.", orderIndex: 9 },
  { id: "jee-physics-elasticity-surface-tension-q11", topicId: "jee-physics-elasticity-surface-tension", text: "Capillary rise of liquid in a tube is due to:", optionA: "Surface tension", optionB: "Viscosity", optionC: "Gravity only", optionD: "Pressure only", correctOption: "A", explanation: "Surface tension and adhesion cause capillary rise.", orderIndex: 10 },
  { id: "jee-physics-elasticity-surface-tension-q12", topicId: "jee-physics-elasticity-surface-tension", text: "Surface tension of a liquid ______ with increasing temperature.", optionA: "Decreases", optionB: "Increases", optionC: "Stays constant", optionD: "Becomes infinite", correctOption: "A", explanation: "Higher temperature weakens intermolecular forces, lowering surface tension.", orderIndex: 11 },
  // Centre of mass & collisions
  { id: "jee-physics-centre-of-mass-collisions-q09", topicId: "jee-physics-centre-of-mass-collisions", text: "In an elastic collision, both momentum and ______ are conserved.", optionA: "Kinetic energy", optionB: "Temperature", optionC: "Charge", optionD: "Volume", correctOption: "A", explanation: "Elastic collisions conserve both momentum and kinetic energy.", orderIndex: 8 },
  { id: "jee-physics-centre-of-mass-collisions-q10", topicId: "jee-physics-centre-of-mass-collisions", text: "The coefficient of restitution for a perfectly elastic collision is:", optionA: "1", optionB: "0", optionC: "0.5", optionD: "infinite", correctOption: "A", explanation: "e = 1 for perfectly elastic; e = 0 for perfectly inelastic collisions.", orderIndex: 9 },
  { id: "jee-physics-centre-of-mass-collisions-q11", topicId: "jee-physics-centre-of-mass-collisions", text: "With no external force, the velocity of the centre of mass:", optionA: "Remains constant", optionB: "Increases", optionC: "Becomes zero", optionD: "Depends on internal forces", correctOption: "A", explanation: "Internal forces cancel; COM velocity is constant with no external force.", orderIndex: 10 },
  { id: "jee-physics-centre-of-mass-collisions-q12", topicId: "jee-physics-centre-of-mass-collisions", text: "In a perfectly inelastic collision, the colliding bodies:", optionA: "Stick together, losing KE", optionB: "Bounce off elastically", optionC: "Conserve KE", optionD: "Gain KE", correctOption: "A", explanation: "In a perfectly inelastic collision, bodies move together and KE is not conserved.", orderIndex: 11 },
  // EM waves
  { id: "jee-physics-electromagnetic-waves-q09", topicId: "jee-physics-electromagnetic-waves", text: "Electromagnetic waves travel in vacuum at:", optionA: "3 × 10⁸ m/s", optionB: "3 × 10⁶ m/s", optionC: "340 m/s", optionD: "1500 m/s", correctOption: "A", explanation: "EM waves travel at c ≈ 3 × 10⁸ m/s in vacuum.", orderIndex: 8 },
  { id: "jee-physics-electromagnetic-waves-q10", topicId: "jee-physics-electromagnetic-waves", text: "In an EM wave, E and B are:", optionA: "Mutually perpendicular and perpendicular to propagation", optionB: "Parallel", optionC: "Along propagation", optionD: "Static", correctOption: "A", explanation: "E and B are perpendicular to each other and to the propagation direction.", orderIndex: 9 },
  { id: "jee-physics-electromagnetic-waves-q11", topicId: "jee-physics-electromagnetic-waves", text: "Which has the highest frequency?", optionA: "Gamma rays", optionB: "Radio waves", optionC: "Infrared", optionD: "Visible light", correctOption: "A", explanation: "Gamma rays have the highest frequency in the EM spectrum.", orderIndex: 10 },
  { id: "jee-physics-electromagnetic-waves-q12", topicId: "jee-physics-electromagnetic-waves", text: "EM waves were predicted theoretically by:", optionA: "Maxwell", optionB: "Newton", optionC: "Bohr", optionD: "Faraday alone", correctOption: "A", explanation: "Maxwell predicted EM waves; Hertz demonstrated them.", orderIndex: 11 },
  // Semiconductors
  { id: "jee-physics-semiconductors-q09", topicId: "jee-physics-semiconductors", text: "Doping silicon with a pentavalent impurity gives a(n):", optionA: "n-type semiconductor", optionB: "p-type semiconductor", optionC: "Insulator", optionD: "Conductor", correctOption: "A", explanation: "Pentavalent (donor) doping adds free electrons, making it n-type.", orderIndex: 8 },
  { id: "jee-physics-semiconductors-q10", topicId: "jee-physics-semiconductors", text: "A p–n junction conducts easily when it is:", optionA: "Forward biased", optionB: "Reverse biased", optionC: "Unbiased", optionD: "At 0 K", correctOption: "A", explanation: "Forward bias narrows the depletion region, allowing current.", orderIndex: 9 },
  { id: "jee-physics-semiconductors-q11", topicId: "jee-physics-semiconductors", text: "In a p-type semiconductor, the majority carriers are:", optionA: "Holes", optionB: "Electrons", optionC: "Protons", optionD: "Neutrons", correctOption: "A", explanation: "Trivalent (acceptor) doping creates holes as majority carriers.", orderIndex: 10 },
  { id: "jee-physics-semiconductors-q12", topicId: "jee-physics-semiconductors", text: "A diode primarily acts as a:", optionA: "Rectifier", optionB: "Amplifier", optionC: "Oscillator", optionD: "Capacitor", correctOption: "A", explanation: "A diode conducts one way, rectifying AC into DC.", orderIndex: 11 },
  // Communication systems
  { id: "jee-physics-communication-systems-q09", topicId: "jee-physics-communication-systems", text: "The process of superimposing a signal on a high-frequency carrier is:", optionA: "Modulation", optionB: "Demodulation", optionC: "Amplification", optionD: "Rectification", correctOption: "A", explanation: "Modulation encodes the message onto a carrier for transmission.", orderIndex: 8 },
  { id: "jee-physics-communication-systems-q10", topicId: "jee-physics-communication-systems", text: "In AM, which property of the carrier is varied?", optionA: "Amplitude", optionB: "Frequency", optionC: "Phase", optionD: "Speed", correctOption: "A", explanation: "Amplitude modulation varies the carrier's amplitude with the message signal.", orderIndex: 9 },
  { id: "jee-physics-communication-systems-q11", topicId: "jee-physics-communication-systems", text: "Sky-wave propagation relies on reflection by the:", optionA: "Ionosphere", optionB: "Troposphere", optionC: "Ground", optionD: "Ocean", correctOption: "A", explanation: "Sky waves reflect off the ionosphere for long-distance radio communication.", orderIndex: 10 },
  { id: "jee-physics-communication-systems-q12", topicId: "jee-physics-communication-systems", text: "The range of a TV transmitting antenna of height h is proportional to:", optionA: "√h", optionB: "h", optionC: "h²", optionD: "1/h", correctOption: "A", explanation: "Line-of-sight range ≈ √(2Rh), proportional to √h.", orderIndex: 11 },

  // ── Chemistry ──
  // Chemical bonding
  { id: "jee-chemistry-chemical-bonding-q09", topicId: "jee-chemistry-chemical-bonding", text: "The shape of a molecule is predicted by:", optionA: "VSEPR theory", optionB: "Kinetic theory", optionC: "Raoult's law", optionD: "Ohm's law", correctOption: "A", explanation: "VSEPR predicts geometry from electron-pair repulsions.", orderIndex: 8 },
  { id: "jee-chemistry-chemical-bonding-q10", topicId: "jee-chemistry-chemical-bonding", text: "The hybridisation of carbon in methane is:", optionA: "sp³", optionB: "sp²", optionC: "sp", optionD: "sp³d", correctOption: "A", explanation: "Carbon in CH₄ is sp³ hybridised (tetrahedral).", orderIndex: 9 },
  { id: "jee-chemistry-chemical-bonding-q11", topicId: "jee-chemistry-chemical-bonding", text: "According to MOT, the bond order of O₂ is:", optionA: "2", optionB: "3", optionC: "1", optionD: "2.5", correctOption: "A", explanation: "O₂ has bond order (8−4)/2 = 2 and is paramagnetic.", orderIndex: 10 },
  { id: "jee-chemistry-chemical-bonding-q12", topicId: "jee-chemistry-chemical-bonding", text: "Hydrogen bonding is strongest when H is bonded to:", optionA: "F, O, or N", optionB: "Carbon", optionC: "Sulphur", optionD: "Chlorine only", correctOption: "A", explanation: "H bonded to small, highly electronegative F/O/N gives strong hydrogen bonds.", orderIndex: 11 },
  // Atomic structure
  { id: "jee-chemistry-atomic-structure-q09", topicId: "jee-chemistry-atomic-structure", text: "The maximum number of electrons in a shell is:", optionA: "2n²", optionB: "n²", optionC: "2n", optionD: "n", correctOption: "A", explanation: "A shell of principal quantum number n holds up to 2n² electrons.", orderIndex: 8 },
  { id: "jee-chemistry-atomic-structure-q10", topicId: "jee-chemistry-atomic-structure", text: "No two electrons can have all four quantum numbers identical — this is the:", optionA: "Pauli exclusion principle", optionB: "Hund's rule", optionC: "Aufbau principle", optionD: "Heisenberg principle", correctOption: "A", explanation: "The Pauli exclusion principle forbids identical sets of quantum numbers.", orderIndex: 9 },
  { id: "jee-chemistry-atomic-structure-q11", topicId: "jee-chemistry-atomic-structure", text: "The shape of an orbital is given by the ______ quantum number.", optionA: "Azimuthal (l)", optionB: "Principal (n)", optionC: "Magnetic (m)", optionD: "Spin (s)", correctOption: "A", explanation: "The azimuthal quantum number l determines orbital shape.", orderIndex: 10 },
  { id: "jee-chemistry-atomic-structure-q12", topicId: "jee-chemistry-atomic-structure", text: "Heisenberg's uncertainty principle limits simultaneous knowledge of position and:", optionA: "Momentum", optionB: "Charge", optionC: "Mass", optionD: "Spin", correctOption: "A", explanation: "Position and momentum cannot both be known exactly at once.", orderIndex: 11 },
  // Periodicity
  { id: "jee-chemistry-periodicity-q09", topicId: "jee-chemistry-periodicity", text: "Across a period, atomic radius generally:", optionA: "Decreases", optionB: "Increases", optionC: "Stays constant", optionD: "Doubles", correctOption: "A", explanation: "Increasing nuclear charge pulls electrons closer across a period.", orderIndex: 8 },
  { id: "jee-chemistry-periodicity-q10", topicId: "jee-chemistry-periodicity", text: "Down a group, ionisation energy generally:", optionA: "Decreases", optionB: "Increases", optionC: "Stays constant", optionD: "Becomes zero", correctOption: "A", explanation: "Larger size and shielding lower ionisation energy down a group.", orderIndex: 9 },
  { id: "jee-chemistry-periodicity-q11", topicId: "jee-chemistry-periodicity", text: "The most electronegative element is:", optionA: "Fluorine", optionB: "Oxygen", optionC: "Chlorine", optionD: "Nitrogen", correctOption: "A", explanation: "Fluorine is the most electronegative element.", orderIndex: 10 },
  { id: "jee-chemistry-periodicity-q12", topicId: "jee-chemistry-periodicity", text: "The modern periodic law bases periodicity on atomic:", optionA: "Number", optionB: "Mass", optionC: "Radius", optionD: "Volume", correctOption: "A", explanation: "Moseley's modern periodic law uses atomic number.", orderIndex: 11 },
  // Mole concept
  { id: "jee-chemistry-mole-concept-q09", topicId: "jee-chemistry-mole-concept", text: "One mole of any substance contains:", optionA: "6.022 × 10²³ particles", optionB: "3.011 × 10²³ particles", optionC: "22.4 particles", optionD: "1000 particles", correctOption: "A", explanation: "A mole contains Avogadro's number, 6.022 × 10²³ particles.", orderIndex: 8 },
  { id: "jee-chemistry-mole-concept-q10", topicId: "jee-chemistry-mole-concept", text: "The volume of one mole of an ideal gas at STP is:", optionA: "22.4 L", optionB: "1 L", optionC: "11.2 L", optionD: "24 L", correctOption: "A", explanation: "One mole of ideal gas occupies 22.4 L at STP.", orderIndex: 9 },
  { id: "jee-chemistry-mole-concept-q11", topicId: "jee-chemistry-mole-concept", text: "The reactant completely consumed in a reaction is the:", optionA: "Limiting reagent", optionB: "Excess reagent", optionC: "Catalyst", optionD: "Product", correctOption: "A", explanation: "The limiting reagent is used up first and limits the product amount.", orderIndex: 10 },
  { id: "jee-chemistry-mole-concept-q12", topicId: "jee-chemistry-mole-concept", text: "Molarity is defined as moles of solute per:", optionA: "Litre of solution", optionB: "Kilogram of solvent", optionC: "Mole of solution", optionD: "Gram of solute", correctOption: "A", explanation: "Molarity = moles of solute per litre of solution.", orderIndex: 11 },
  // Equilibrium
  { id: "jee-chemistry-equilibrium-q09", topicId: "jee-chemistry-equilibrium", text: "Increasing pressure shifts a gaseous equilibrium toward:", optionA: "Fewer moles of gas", optionB: "More moles of gas", optionC: "Reactants always", optionD: "No change", correctOption: "A", explanation: "By Le Chatelier, higher pressure favours fewer gas molecules.", orderIndex: 8 },
  { id: "jee-chemistry-equilibrium-q10", topicId: "jee-chemistry-equilibrium", text: "At half-equivalence in a weak-acid titration, pH equals:", optionA: "pKa", optionB: "7", optionC: "pKw", optionD: "0", correctOption: "A", explanation: "When [acid] = [salt], the Henderson–Hasselbalch log term is zero, so pH = pKa.", orderIndex: 9 },
  { id: "jee-chemistry-equilibrium-q11", topicId: "jee-chemistry-equilibrium", text: "Kp and Kc are related by:", optionA: "Kp = Kc(RT)^Δn", optionB: "Kp = Kc/RT", optionC: "Kp = Kc + RT", optionD: "Kp = Kc(RT)^−Δn", correctOption: "A", explanation: "Kp = Kc(RT)^Δn, where Δn is the change in gas moles.", orderIndex: 10 },
  { id: "jee-chemistry-equilibrium-q12", topicId: "jee-chemistry-equilibrium", text: "A Brønsted–Lowry acid is a:", optionA: "Proton donor", optionB: "Proton acceptor", optionC: "Electron donor", optionD: "OH⁻ donor", correctOption: "A", explanation: "A Brønsted–Lowry acid donates a proton (H⁺).", orderIndex: 11 },
  // Thermodynamics (chem)
  { id: "jee-chemistry-thermodynamics-q09", topicId: "jee-chemistry-thermodynamics", text: "A reaction is spontaneous when ΔG is:", optionA: "Negative", optionB: "Positive", optionC: "Zero", optionD: "Infinite", correctOption: "A", explanation: "Spontaneity requires ΔG = ΔH − TΔS < 0.", orderIndex: 8 },
  { id: "jee-chemistry-thermodynamics-q10", topicId: "jee-chemistry-thermodynamics", text: "At equilibrium, ΔG equals:", optionA: "Zero", optionB: "Negative", optionC: "Positive", optionD: "Infinite", correctOption: "A", explanation: "At equilibrium ΔG = 0 and ΔG° = −RT ln K.", orderIndex: 9 },
  { id: "jee-chemistry-thermodynamics-q11", topicId: "jee-chemistry-thermodynamics", text: "Entropy is a measure of:", optionA: "Disorder/randomness", optionB: "Energy content only", optionC: "Temperature", optionD: "Pressure", correctOption: "A", explanation: "Entropy (S) measures the disorder of a system.", orderIndex: 10 },
  { id: "jee-chemistry-thermodynamics-q12", topicId: "jee-chemistry-thermodynamics", text: "An exothermic reaction has ΔH that is:", optionA: "Negative", optionB: "Positive", optionC: "Zero", optionD: "Undefined", correctOption: "A", explanation: "Exothermic reactions release heat, so ΔH < 0.", orderIndex: 11 },
  // GOC
  { id: "jee-chemistry-goc-q09", topicId: "jee-chemistry-goc", text: "A nucleophile is a species that is:", optionA: "Electron-rich (donates electrons)", optionB: "Electron-deficient", optionC: "Always neutral", optionD: "A strong acid", correctOption: "A", explanation: "A nucleophile donates an electron pair to an electrophilic centre.", orderIndex: 8 },
  { id: "jee-chemistry-goc-q10", topicId: "jee-chemistry-goc", text: "Carbocation stability order is:", optionA: "3° > 2° > 1°", optionB: "1° > 2° > 3°", optionC: "All equal", optionD: "2° > 3° > 1°", correctOption: "A", explanation: "Tertiary carbocations are most stable (hyperconjugation, inductive effects).", orderIndex: 9 },
  { id: "jee-chemistry-goc-q11", topicId: "jee-chemistry-goc", text: "Resonance structures differ only in the position of:", optionA: "Electrons", optionB: "Atoms", optionC: "Nuclei", optionD: "Molecular mass", correctOption: "A", explanation: "Resonance structures differ only in electron distribution.", orderIndex: 10 },
  { id: "jee-chemistry-goc-q12", topicId: "jee-chemistry-goc", text: "The +I (inductive) effect refers to a group that:", optionA: "Donates electron density through sigma bonds", optionB: "Withdraws electrons", optionC: "Forms pi bonds", optionD: "Breaks bonds", correctOption: "A", explanation: "An electron-donating group exhibits a +I effect.", orderIndex: 11 },
  // Hydrocarbons
  { id: "jee-chemistry-hydrocarbons-q09", topicId: "jee-chemistry-hydrocarbons", text: "The general formula of alkanes is:", optionA: "CnH2n+2", optionB: "CnH2n", optionC: "CnH2n-2", optionD: "CnHn", correctOption: "A", explanation: "Saturated alkanes have the formula CnH2n+2.", orderIndex: 8 },
  { id: "jee-chemistry-hydrocarbons-q10", topicId: "jee-chemistry-hydrocarbons", text: "Alkenes characteristically undergo:", optionA: "Electrophilic addition", optionB: "Nucleophilic substitution", optionC: "Free-radical substitution only", optionD: "No reaction", correctOption: "A", explanation: "The C=C bond undergoes electrophilic addition.", orderIndex: 9 },
  { id: "jee-chemistry-hydrocarbons-q11", topicId: "jee-chemistry-hydrocarbons", text: "Benzene is stabilised by:", optionA: "Aromatic delocalisation (resonance)", optionB: "Ring strain", optionC: "Sp³ hybridisation", optionD: "Weak bonds", correctOption: "A", explanation: "Benzene is aromatic with delocalised π electrons (Hückel's 4n+2).", orderIndex: 10 },
  { id: "jee-chemistry-hydrocarbons-q12", topicId: "jee-chemistry-hydrocarbons", text: "Markovnikov's rule applies to the addition of HX to:", optionA: "Unsymmetrical alkenes", optionB: "Alkanes", optionC: "Aromatic rings", optionD: "Alcohols", correctOption: "A", explanation: "Markovnikov's rule predicts the major product for HX addition to unsymmetrical alkenes.", orderIndex: 11 },
  // Coordination compounds
  { id: "jee-chemistry-coordination-compounds-q09", topicId: "jee-chemistry-coordination-compounds", text: "The number of donor atoms bonded to the metal is the:", optionA: "Coordination number", optionB: "Oxidation state", optionC: "Atomic number", optionD: "Valency only", correctOption: "A", explanation: "The coordination number counts donor atoms directly bonded to the metal.", orderIndex: 8 },
  { id: "jee-chemistry-coordination-compounds-q10", topicId: "jee-chemistry-coordination-compounds", text: "A strong-field ligand like CN⁻ produces a complex that is:", optionA: "Low-spin", optionB: "High-spin", optionC: "Colourless always", optionD: "Tetrahedral always", correctOption: "A", explanation: "Strong-field ligands cause large Δ, pairing electrons for a low-spin complex.", orderIndex: 9 },
  { id: "jee-chemistry-coordination-compounds-q11", topicId: "jee-chemistry-coordination-compounds", text: "EDTA is a ligand of denticity:", optionA: "Hexadentate", optionB: "Monodentate", optionC: "Bidentate", optionD: "Tridentate", correctOption: "A", explanation: "EDTA binds through six donor atoms.", orderIndex: 10 },
  { id: "jee-chemistry-coordination-compounds-q12", topicId: "jee-chemistry-coordination-compounds", text: "The colour of transition-metal complexes arises from:", optionA: "d–d transitions", optionB: "Nuclear transitions", optionC: "s–s transitions", optionD: "Ionic bonds", correctOption: "A", explanation: "d–d electronic transitions across the split give the observed colours.", orderIndex: 11 },
  // Electrochemistry
  { id: "jee-chemistry-electrochemistry-q09", topicId: "jee-chemistry-electrochemistry", text: "In a galvanic cell, oxidation occurs at the:", optionA: "Anode", optionB: "Cathode", optionC: "Salt bridge", optionD: "Both electrodes", correctOption: "A", explanation: "Oxidation occurs at the anode; reduction at the cathode.", orderIndex: 8 },
  { id: "jee-chemistry-electrochemistry-q10", topicId: "jee-chemistry-electrochemistry", text: "The Nernst equation at 298 K uses the term:", optionA: "(0.059/n) log Q", optionB: "(0.059 × n) Q", optionC: "nRT only", optionD: "log P only", correctOption: "A", explanation: "E = E° − (0.059/n) log Q at 298 K.", orderIndex: 9 },
  { id: "jee-chemistry-electrochemistry-q11", topicId: "jee-chemistry-electrochemistry", text: "One faraday equals about:", optionA: "96,500 C", optionB: "22,400 C", optionC: "6,022 C", optionD: "1,000 C", correctOption: "A", explanation: "One faraday is the charge of a mole of electrons, ~96,500 C.", orderIndex: 10 },
  { id: "jee-chemistry-electrochemistry-q12", topicId: "jee-chemistry-electrochemistry", text: "E°cell for a spontaneous cell is:", optionA: "Positive", optionB: "Negative", optionC: "Zero", optionD: "Infinite", correctOption: "A", explanation: "A positive E°cell means ΔG° < 0 (spontaneous).", orderIndex: 11 },
  // States of matter
  { id: "jee-chemistry-states-of-matter-q09", topicId: "jee-chemistry-states-of-matter", text: "The ideal gas equation is:", optionA: "PV = nRT", optionB: "PV = RT/n", optionC: "P/V = nRT", optionD: "PVT = nR", correctOption: "A", explanation: "The ideal gas law: PV = nRT.", orderIndex: 8 },
  { id: "jee-chemistry-states-of-matter-q10", topicId: "jee-chemistry-states-of-matter", text: "Real gases deviate most from ideal behaviour at:", optionA: "Low temperature and high pressure", optionB: "High temperature and low pressure", optionC: "STP", optionD: "Zero pressure", correctOption: "A", explanation: "Deviations are largest at low T and high P.", orderIndex: 9 },
  { id: "jee-chemistry-states-of-matter-q11", topicId: "jee-chemistry-states-of-matter", text: "A gas can be liquefied only below its:", optionA: "Critical temperature", optionB: "Boiling point", optionC: "Melting point", optionD: "Triple point", correctOption: "A", explanation: "Above the critical temperature no pressure can liquefy a gas.", orderIndex: 10 },
  { id: "jee-chemistry-states-of-matter-q12", topicId: "jee-chemistry-states-of-matter", text: "Graham's law states the rate of diffusion is inversely proportional to:", optionA: "√(molar mass)", optionB: "Temperature", optionC: "Volume", optionD: "Pressure", correctOption: "A", explanation: "Rate ∝ 1/√M; lighter gases diffuse faster.", orderIndex: 11 },
  // Redox reactions
  { id: "jee-chemistry-redox-reactions-q09", topicId: "jee-chemistry-redox-reactions", text: "Oxidation is:", optionA: "Loss of electrons", optionB: "Gain of electrons", optionC: "Gain of protons", optionD: "Loss of neutrons", correctOption: "A", explanation: "Oxidation is loss of electrons (increase in oxidation number).", orderIndex: 8 },
  { id: "jee-chemistry-redox-reactions-q10", topicId: "jee-chemistry-redox-reactions", text: "A reducing agent is itself:", optionA: "Oxidised", optionB: "Reduced", optionC: "Unchanged", optionD: "Precipitated", correctOption: "A", explanation: "A reducing agent donates electrons and is oxidised.", orderIndex: 9 },
  { id: "jee-chemistry-redox-reactions-q11", topicId: "jee-chemistry-redox-reactions", text: "The oxidation number of Mn in KMnO₄ is:", optionA: "+7", optionB: "+2", optionC: "+4", optionD: "+6", correctOption: "A", explanation: "K(+1) + Mn + 4O(−2) = 0 gives Mn = +7.", orderIndex: 10 },
  { id: "jee-chemistry-redox-reactions-q12", topicId: "jee-chemistry-redox-reactions", text: "A reaction where the same element is oxidised and reduced is:", optionA: "Disproportionation", optionB: "Combination", optionC: "Displacement", optionD: "Neutralisation", correctOption: "A", explanation: "Disproportionation involves simultaneous oxidation and reduction of one element.", orderIndex: 11 },
  // Solutions
  { id: "jee-chemistry-solutions-q09", topicId: "jee-chemistry-solutions", text: "Colligative properties depend on the:", optionA: "Number of solute particles", optionB: "Nature of solute", optionC: "Colour", optionD: "Solute mass only", correctOption: "A", explanation: "Colligative properties depend on the number of solute particles.", orderIndex: 8 },
  { id: "jee-chemistry-solutions-q10", topicId: "jee-chemistry-solutions", text: "Raoult's law relates vapour pressure of a component to its:", optionA: "Mole fraction", optionB: "Mass", optionC: "Density", optionD: "Volume", correctOption: "A", explanation: "A component's partial vapour pressure ∝ its mole fraction.", orderIndex: 9 },
  { id: "jee-chemistry-solutions-q11", topicId: "jee-chemistry-solutions", text: "Osmotic pressure is given by:", optionA: "π = CRT", optionB: "π = PV", optionC: "π = nF", optionD: "π = mRT/V²", correctOption: "A", explanation: "Osmotic pressure π = CRT.", orderIndex: 10 },
  { id: "jee-chemistry-solutions-q12", topicId: "jee-chemistry-solutions", text: "The van 't Hoff factor for NaCl (fully dissociated) is about:", optionA: "2", optionB: "1", optionC: "3", optionD: "0.5", correctOption: "A", explanation: "NaCl → Na⁺ + Cl⁻ gives two particles, so i ≈ 2.", orderIndex: 11 },
  // Chemical kinetics
  { id: "jee-chemistry-chemical-kinetics-q09", topicId: "jee-chemistry-chemical-kinetics", text: "The half-life of a first-order reaction is:", optionA: "Independent of concentration", optionB: "Proportional to concentration", optionC: "Inversely proportional to k²", optionD: "Always 1 second", correctOption: "A", explanation: "For first order, t½ = 0.693/k, independent of concentration.", orderIndex: 8 },
  { id: "jee-chemistry-chemical-kinetics-q10", topicId: "jee-chemistry-chemical-kinetics", text: "The Arrhenius equation is:", optionA: "k = A e^(−Ea/RT)", optionB: "k = A e^(Ea/RT)", optionC: "k = Ea/RT", optionD: "k = A/RT", correctOption: "A", explanation: "The Arrhenius equation is k = A·e^(−Ea/RT), linking rate to temperature.", orderIndex: 9 },
  { id: "jee-chemistry-chemical-kinetics-q11", topicId: "jee-chemistry-chemical-kinetics", text: "A catalyst increases the rate by:", optionA: "Lowering the activation energy", optionB: "Raising the activation energy", optionC: "Increasing temperature", optionD: "Shifting equilibrium", correctOption: "A", explanation: "A catalyst provides a lower-Ea pathway.", orderIndex: 10 },
  { id: "jee-chemistry-chemical-kinetics-q12", topicId: "jee-chemistry-chemical-kinetics", text: "The order of a reaction is determined:", optionA: "Experimentally from the rate law", optionB: "From stoichiometry always", optionC: "From molar mass", optionD: "Always as 1", correctOption: "A", explanation: "Order is found experimentally, not from the balanced equation.", orderIndex: 11 },
  // Surface chemistry
  { id: "jee-chemistry-surface-chemistry-q09", topicId: "jee-chemistry-surface-chemistry", text: "Adsorption is the accumulation of a substance at a:", optionA: "Surface", optionB: "Bulk", optionC: "Gas phase only", optionD: "Solution only", correctOption: "A", explanation: "Adsorption concentrates molecules at a surface.", orderIndex: 8 },
  { id: "jee-chemistry-surface-chemistry-q10", topicId: "jee-chemistry-surface-chemistry", text: "The scattering of light by colloidal particles is the:", optionA: "Tyndall effect", optionB: "Brownian motion", optionC: "Raman effect", optionD: "Photoelectric effect", correctOption: "A", explanation: "The Tyndall effect is scattering of light by colloids.", orderIndex: 9 },
  { id: "jee-chemistry-surface-chemistry-q11", topicId: "jee-chemistry-surface-chemistry", text: "The Hardy–Schulze rule says coagulating power increases with ion:", optionA: "Charge", optionB: "Colour", optionC: "Size only", optionD: "Mass only", correctOption: "A", explanation: "Higher ionic charge gives greater coagulating power.", orderIndex: 10 },
  { id: "jee-chemistry-surface-chemistry-q12", topicId: "jee-chemistry-surface-chemistry", text: "Physisorption involves:", optionA: "Weak van der Waals forces (reversible)", optionB: "Strong chemical bonds", optionC: "High specificity", optionD: "High activation energy", correctOption: "A", explanation: "Physisorption is weak, reversible van der Waals adsorption.", orderIndex: 11 },
  // s-block
  { id: "jee-chemistry-s-block-q09", topicId: "jee-chemistry-s-block", text: "Alkali metals are strong:", optionA: "Reducing agents", optionB: "Oxidising agents", optionC: "Acids", optionD: "Bases only", correctOption: "A", explanation: "Alkali metals readily lose an electron, acting as strong reducing agents.", orderIndex: 8 },
  { id: "jee-chemistry-s-block-q10", topicId: "jee-chemistry-s-block", text: "The flame colour of sodium is:", optionA: "Yellow", optionB: "Lilac", optionC: "Brick-red", optionD: "Green", correctOption: "A", explanation: "Sodium gives a golden-yellow flame.", orderIndex: 9 },
  { id: "jee-chemistry-s-block-q11", topicId: "jee-chemistry-s-block", text: "Washing soda is:", optionA: "Na₂CO₃·10H₂O", optionB: "NaHCO₃", optionC: "NaOH", optionD: "NaCl", correctOption: "A", explanation: "Washing soda is hydrated sodium carbonate.", orderIndex: 10 },
  { id: "jee-chemistry-s-block-q12", topicId: "jee-chemistry-s-block", text: "Lithium shows a diagonal relationship with:", optionA: "Magnesium", optionB: "Sodium", optionC: "Beryllium", optionD: "Calcium", correctOption: "A", explanation: "Li–Mg show a diagonal relationship (similar charge/size ratio).", orderIndex: 11 },
  // p-block
  { id: "jee-chemistry-p-block-q09", topicId: "jee-chemistry-p-block", text: "The most reactive halogen is:", optionA: "Fluorine", optionB: "Iodine", optionC: "Bromine", optionD: "Chlorine", correctOption: "A", explanation: "Fluorine is the most reactive halogen and strongest oxidiser.", orderIndex: 8 },
  { id: "jee-chemistry-p-block-q10", topicId: "jee-chemistry-p-block", text: "The inert pair effect stabilises which oxidation state down a group?", optionA: "Lower", optionB: "Higher", optionC: "Zero", optionD: "Negative only", correctOption: "A", explanation: "The inert pair effect favours lower oxidation states down a group.", orderIndex: 9 },
  { id: "jee-chemistry-p-block-q11", topicId: "jee-chemistry-p-block", text: "Catenation is strongest in which element?", optionA: "Carbon", optionB: "Silicon", optionC: "Lead", optionD: "Tin", correctOption: "A", explanation: "Carbon shows the strongest catenation (self-linking).", orderIndex: 10 },
  { id: "jee-chemistry-p-block-q12", topicId: "jee-chemistry-p-block", text: "Noble gases are unreactive due to their:", optionA: "Complete octet", optionB: "Single valence electron", optionC: "High reactivity", optionD: "Unpaired electrons", correctOption: "A", explanation: "A full valence shell makes noble gases very stable.", orderIndex: 11 },
  // d-f block
  { id: "jee-chemistry-d-f-block-q09", topicId: "jee-chemistry-d-f-block", text: "Transition metals show variable oxidation states because of close energies of:", optionA: "ns and (n−1)d electrons", optionB: "1s and 2s", optionC: "p and f", optionD: "Nuclear shells", correctOption: "A", explanation: "Similar ns and (n−1)d energies allow variable oxidation states.", orderIndex: 8 },
  { id: "jee-chemistry-d-f-block-q10", topicId: "jee-chemistry-d-f-block", text: "The lanthanoid contraction is the steady decrease in size across the:", optionA: "4f series", optionB: "3d series", optionC: "5d series", optionD: "2p series", correctOption: "A", explanation: "The lanthanoid contraction occurs across the 4f (lanthanoid) series.", orderIndex: 9 },
  { id: "jee-chemistry-d-f-block-q11", topicId: "jee-chemistry-d-f-block", text: "The oxidation state of Cr in K₂Cr₂O₇ is:", optionA: "+6", optionB: "+3", optionC: "+2", optionD: "+7", correctOption: "A", explanation: "In dichromate, chromium is +6.", orderIndex: 10 },
  { id: "jee-chemistry-d-f-block-q12", topicId: "jee-chemistry-d-f-block", text: "Paramagnetism in transition-metal ions is due to:", optionA: "Unpaired d-electrons", optionB: "Paired electrons", optionC: "No electrons", optionD: "Protons", correctOption: "A", explanation: "Unpaired d-electrons make many transition-metal ions paramagnetic.", orderIndex: 11 },
  // Haloalkanes & haloarenes
  { id: "jee-chemistry-haloalkanes-haloarenes-q09", topicId: "jee-chemistry-haloalkanes-haloarenes", text: "An SN2 reaction proceeds with:", optionA: "Inversion of configuration", optionB: "Retention", optionC: "Racemisation", optionD: "No stereochemistry", correctOption: "A", explanation: "SN2 involves backside attack, causing inversion (Walden).", orderIndex: 8 },
  { id: "jee-chemistry-haloalkanes-haloarenes-q10", topicId: "jee-chemistry-haloalkanes-haloarenes", text: "SN1 reactions are fastest with which halide?", optionA: "Tertiary", optionB: "Primary", optionC: "Methyl", optionD: "Vinyl", correctOption: "A", explanation: "Tertiary halides form the most stable carbocation, favouring SN1.", orderIndex: 9 },
  { id: "jee-chemistry-haloalkanes-haloarenes-q11", topicId: "jee-chemistry-haloalkanes-haloarenes", text: "Haloarenes are less reactive to substitution due to:", optionA: "Partial double-bond character of the C–X bond", optionB: "Weak C–X bond", optionC: "High ring reactivity", optionD: "Absence of halogen", correctOption: "A", explanation: "Resonance gives the C–X bond partial double-bond character, reducing reactivity.", orderIndex: 10 },
  { id: "jee-chemistry-haloalkanes-haloarenes-q12", topicId: "jee-chemistry-haloalkanes-haloarenes", text: "Polar aprotic solvents favour which mechanism?", optionA: "SN2", optionB: "SN1", optionC: "E1", optionD: "Free radical", correctOption: "A", explanation: "Polar aprotic solvents enhance nucleophilicity, favouring SN2.", orderIndex: 11 },
  // Alcohols, phenols, ethers
  { id: "jee-chemistry-alcohols-phenols-ethers-q09", topicId: "jee-chemistry-alcohols-phenols-ethers", text: "Phenol is more acidic than ethanol because the phenoxide ion is:", optionA: "Resonance-stabilised", optionB: "Destabilised", optionC: "Neutral", optionD: "A strong base", correctOption: "A", explanation: "Resonance delocalises the negative charge, stabilising phenoxide.", orderIndex: 8 },
  { id: "jee-chemistry-alcohols-phenols-ethers-q10", topicId: "jee-chemistry-alcohols-phenols-ethers", text: "Oxidation of a primary alcohol first gives:", optionA: "An aldehyde", optionB: "A ketone", optionC: "An ether", optionD: "An ester", correctOption: "A", explanation: "Primary alcohols oxidise to aldehydes, then to carboxylic acids.", orderIndex: 9 },
  { id: "jee-chemistry-alcohols-phenols-ethers-q11", topicId: "jee-chemistry-alcohols-phenols-ethers", text: "The Williamson synthesis prepares ethers from an alkyl halide and:", optionA: "An alkoxide", optionB: "An acid", optionC: "A ketone", optionD: "An amine", correctOption: "A", explanation: "Williamson synthesis reacts an alkyl halide with a sodium alkoxide (SN2).", orderIndex: 10 },
  { id: "jee-chemistry-alcohols-phenols-ethers-q12", topicId: "jee-chemistry-alcohols-phenols-ethers", text: "Oxidation of a secondary alcohol gives a:", optionA: "Ketone", optionB: "Aldehyde", optionC: "Carboxylic acid", optionD: "Ester", correctOption: "A", explanation: "Secondary alcohols oxidise to ketones.", orderIndex: 11 },
  // Aldehydes, ketones, acids
  { id: "jee-chemistry-aldehydes-ketones-acids-q09", topicId: "jee-chemistry-aldehydes-ketones-acids", text: "The characteristic reaction of the carbonyl group is:", optionA: "Nucleophilic addition", optionB: "Electrophilic substitution", optionC: "Free-radical addition", optionD: "Elimination", correctOption: "A", explanation: "Aldehydes and ketones undergo nucleophilic addition at the C=O.", orderIndex: 8 },
  { id: "jee-chemistry-aldehydes-ketones-acids-q10", topicId: "jee-chemistry-aldehydes-ketones-acids", text: "Tollens' reagent gives a silver mirror with:", optionA: "Aldehydes", optionB: "Ketones", optionC: "Ethers", optionD: "Alkanes", correctOption: "A", explanation: "Aldehydes reduce Tollens' reagent to a silver mirror; ketones do not.", orderIndex: 9 },
  { id: "jee-chemistry-aldehydes-ketones-acids-q11", topicId: "jee-chemistry-aldehydes-ketones-acids", text: "Carbonyl compounds with an α-hydrogen undergo the:", optionA: "Aldol condensation", optionB: "Friedel–Crafts reaction", optionC: "Wurtz reaction", optionD: "Kolbe reaction", correctOption: "A", explanation: "α-Hydrogen carbonyl compounds undergo the aldol condensation.", orderIndex: 10 },
  { id: "jee-chemistry-aldehydes-ketones-acids-q12", topicId: "jee-chemistry-aldehydes-ketones-acids", text: "Carboxylic acids are acidic because the carboxylate ion is:", optionA: "Resonance-stabilised over two oxygens", optionB: "Non-resonating", optionC: "Positively charged", optionD: "A strong base", correctOption: "A", explanation: "Resonance over two equivalent oxygens stabilises the carboxylate.", orderIndex: 11 },
  // Amines
  { id: "jee-chemistry-amines-q09", topicId: "jee-chemistry-amines", text: "Amines are organic derivatives of:", optionA: "Ammonia", optionB: "Water", optionC: "Methane", optionD: "Benzene", correctOption: "A", explanation: "Amines are derived by replacing H atoms of NH₃ with alkyl/aryl groups.", orderIndex: 8 },
  { id: "jee-chemistry-amines-q10", topicId: "jee-chemistry-amines", text: "Aniline is less basic than aliphatic amines because its lone pair is:", optionA: "Delocalised into the ring", optionB: "Absent", optionC: "On oxygen", optionD: "Strongly localised", correctOption: "A", explanation: "In aniline the N lone pair delocalises into the ring, lowering basicity.", orderIndex: 9 },
  { id: "jee-chemistry-amines-q11", topicId: "jee-chemistry-amines", text: "The Gabriel synthesis gives only:", optionA: "Primary amines", optionB: "Secondary amines", optionC: "Tertiary amines", optionD: "Aromatic amines", correctOption: "A", explanation: "Gabriel synthesis produces pure primary aliphatic amines.", orderIndex: 10 },
  { id: "jee-chemistry-amines-q12", topicId: "jee-chemistry-amines", text: "Diazonium salts form when aniline reacts with nitrous acid at:", optionA: "0–5 °C", optionB: "100 °C", optionC: "room temperature", optionD: "−50 °C", correctOption: "A", explanation: "Aryl diazonium salts form at low temperature (0–5 °C).", orderIndex: 11 },
  // Biomolecules & polymers
  { id: "jee-chemistry-biomolecules-polymers-q09", topicId: "jee-chemistry-biomolecules-polymers", text: "The bond joining two amino acids is the:", optionA: "Peptide bond", optionB: "Glycosidic bond", optionC: "Ester bond", optionD: "Phosphodiester bond", correctOption: "A", explanation: "Amino acids link through peptide bonds to form proteins.", orderIndex: 8 },
  { id: "jee-chemistry-biomolecules-polymers-q10", topicId: "jee-chemistry-biomolecules-polymers", text: "Nylon-6,6 is an example of a:", optionA: "Condensation polymer", optionB: "Addition polymer", optionC: "Natural rubber", optionD: "Protein", correctOption: "A", explanation: "Nylon-6,6 forms by condensation polymerisation.", orderIndex: 9 },
  { id: "jee-chemistry-biomolecules-polymers-q11", topicId: "jee-chemistry-biomolecules-polymers", text: "Starch and cellulose are polymers of:", optionA: "Glucose", optionB: "Amino acids", optionC: "Fatty acids", optionD: "Nucleotides", correctOption: "A", explanation: "Both are polysaccharides made of glucose units.", orderIndex: 10 },
  { id: "jee-chemistry-biomolecules-polymers-q12", topicId: "jee-chemistry-biomolecules-polymers", text: "Polythene is an example of a(n):", optionA: "Addition polymer", optionB: "Condensation polymer", optionC: "Natural polymer", optionD: "Protein", correctOption: "A", explanation: "Polythene forms by addition polymerisation of ethene.", orderIndex: 11 },
  // Metallurgy
  { id: "jee-chemistry-metallurgy-q09", topicId: "jee-chemistry-metallurgy", text: "Concentration of a sulphide ore is done by:", optionA: "Froth flotation", optionB: "Calcination", optionC: "Electrolysis", optionD: "Distillation", correctOption: "A", explanation: "Froth flotation concentrates sulphide ores.", orderIndex: 8 },
  { id: "jee-chemistry-metallurgy-q10", topicId: "jee-chemistry-metallurgy", text: "Roasting heats an ore in:", optionA: "Excess air", optionB: "Absence of air", optionC: "Water", optionD: "Vacuum", correctOption: "A", explanation: "Roasting (for sulphides) heats the ore in excess air to form the oxide.", orderIndex: 9 },
  { id: "jee-chemistry-metallurgy-q11", topicId: "jee-chemistry-metallurgy", text: "Very reactive metals like aluminium are extracted by:", optionA: "Electrolysis", optionB: "Carbon reduction", optionC: "Roasting only", optionD: "Distillation", correctOption: "A", explanation: "Reactive metals are extracted by electrolysis (e.g., Hall–Héroult for Al).", orderIndex: 10 },
  { id: "jee-chemistry-metallurgy-q12", topicId: "jee-chemistry-metallurgy", text: "Zone refining is used to purify:", optionA: "Silicon and germanium", optionB: "Sodium", optionC: "Aluminium", optionD: "Iron", correctOption: "A", explanation: "Zone refining purifies semiconductors like Si and Ge.", orderIndex: 11 },
  // Environmental chemistry
  { id: "jee-chemistry-environmental-chemistry-q09", topicId: "jee-chemistry-environmental-chemistry", text: "Acid rain is mainly caused by oxides of:", optionA: "Sulphur and nitrogen", optionB: "Carbon only", optionC: "Sodium", optionD: "Silicon", correctOption: "A", explanation: "SO₂ and NOx form sulphuric and nitric acids in acid rain.", orderIndex: 8 },
  { id: "jee-chemistry-environmental-chemistry-q10", topicId: "jee-chemistry-environmental-chemistry", text: "The main greenhouse gas is:", optionA: "Carbon dioxide", optionB: "Oxygen", optionC: "Nitrogen", optionD: "Argon", correctOption: "A", explanation: "CO₂ is the principal greenhouse gas.", orderIndex: 9 },
  { id: "jee-chemistry-environmental-chemistry-q11", topicId: "jee-chemistry-environmental-chemistry", text: "Ozone depletion is chiefly caused by:", optionA: "CFCs", optionB: "CO₂", optionC: "O₂", optionD: "Methane only", correctOption: "A", explanation: "CFCs release chlorine radicals that destroy ozone.", orderIndex: 10 },
  { id: "jee-chemistry-environmental-chemistry-q12", topicId: "jee-chemistry-environmental-chemistry", text: "High BOD of water indicates:", optionA: "High organic pollution", optionB: "Clean water", optionC: "High oxygen", optionD: "Low bacteria", correctOption: "A", explanation: "A high BOD reflects more organic waste and greater pollution.", orderIndex: 11 },

  // ── Mathematics ──
  // Quadratic equations
  { id: "jee-mathematics-quadratic-equations-q09", topicId: "jee-mathematics-quadratic-equations", text: "For ax² + bx + c = 0, the sum of roots is:", optionA: "−b/a", optionB: "b/a", optionC: "c/a", optionD: "−c/a", correctOption: "A", explanation: "Sum of roots = −b/a; product = c/a.", orderIndex: 8 },
  { id: "jee-mathematics-quadratic-equations-q10", topicId: "jee-mathematics-quadratic-equations", text: "The roots are real and distinct when the discriminant is:", optionA: "Greater than zero", optionB: "Zero", optionC: "Less than zero", optionD: "Equal to a", correctOption: "A", explanation: "D = b² − 4ac > 0 gives two distinct real roots.", orderIndex: 9 },
  { id: "jee-mathematics-quadratic-equations-q11", topicId: "jee-mathematics-quadratic-equations", text: "The product of the roots of ax² + bx + c = 0 is:", optionA: "c/a", optionB: "−b/a", optionC: "b/a", optionD: "−c/a", correctOption: "A", explanation: "Product of roots = c/a.", orderIndex: 10 },
  { id: "jee-mathematics-quadratic-equations-q12", topicId: "jee-mathematics-quadratic-equations", text: "If the discriminant is zero, the roots are:", optionA: "Real and equal", optionB: "Complex", optionC: "Distinct real", optionD: "Irrational", correctOption: "A", explanation: "D = 0 gives two equal real roots.", orderIndex: 11 },
  // Complex numbers
  { id: "jee-mathematics-complex-numbers-q09", topicId: "jee-mathematics-complex-numbers", text: "The value of i² is:", optionA: "−1", optionB: "1", optionC: "i", optionD: "0", correctOption: "A", explanation: "By definition, i² = −1.", orderIndex: 8 },
  { id: "jee-mathematics-complex-numbers-q10", topicId: "jee-mathematics-complex-numbers", text: "For complex numbers, |z₁z₂| equals:", optionA: "|z₁||z₂|", optionB: "|z₁| + |z₂|", optionC: "|z₁| − |z₂|", optionD: "|z₁|/|z₂|", correctOption: "A", explanation: "The modulus of a product is the product of the moduli.", orderIndex: 9 },
  { id: "jee-mathematics-complex-numbers-q11", topicId: "jee-mathematics-complex-numbers", text: "The sum of the cube roots of unity (1 + ω + ω²) is:", optionA: "0", optionB: "1", optionC: "3", optionD: "ω", correctOption: "A", explanation: "The three cube roots of unity sum to zero.", orderIndex: 10 },
  { id: "jee-mathematics-complex-numbers-q12", topicId: "jee-mathematics-complex-numbers", text: "Euler's formula states e^(iθ) equals:", optionA: "cos θ + i sin θ", optionB: "cos θ − i sin θ", optionC: "sin θ + i cos θ", optionD: "1 + iθ", correctOption: "A", explanation: "Euler's formula: e^(iθ) = cos θ + i sin θ.", orderIndex: 11 },
  // Sequences & series
  { id: "jee-mathematics-sequences-series-q09", topicId: "jee-mathematics-sequences-series", text: "The sum of the first n terms of an AP is:", optionA: "n/2·[2a + (n−1)d]", optionB: "a + (n−1)d", optionC: "n·a·d", optionD: "a·rⁿ", correctOption: "A", explanation: "AP sum Sₙ = n/2·[2a + (n−1)d].", orderIndex: 8 },
  { id: "jee-mathematics-sequences-series-q10", topicId: "jee-mathematics-sequences-series", text: "The sum to infinity of a GP with |r| < 1 is:", optionA: "a/(1 − r)", optionB: "a(1 − r)", optionC: "a·rⁿ", optionD: "a/r", correctOption: "A", explanation: "For |r| < 1, the infinite GP sum is a/(1 − r).", orderIndex: 9 },
  { id: "jee-mathematics-sequences-series-q11", topicId: "jee-mathematics-sequences-series", text: "The sum of the first n natural numbers is:", optionA: "n(n+1)/2", optionB: "n²", optionC: "n(n+1)(2n+1)/6", optionD: "n(n−1)/2", correctOption: "A", explanation: "1 + 2 + … + n = n(n+1)/2.", orderIndex: 10 },
  { id: "jee-mathematics-sequences-series-q12", topicId: "jee-mathematics-sequences-series", text: "The nth term of an AP is:", optionA: "a + (n−1)d", optionB: "a·rⁿ⁻¹", optionC: "a + nd", optionD: "a/(n−1)", correctOption: "A", explanation: "The nth term of an AP is aₙ = a + (n−1)d.", orderIndex: 11 },
  // Permutations & combinations
  { id: "jee-mathematics-permutations-combinations-q09", topicId: "jee-mathematics-permutations-combinations", text: "The number of ways to arrange n distinct objects is:", optionA: "n!", optionB: "2ⁿ", optionC: "n²", optionD: "nⁿ", correctOption: "A", explanation: "n distinct objects can be arranged in n! ways.", orderIndex: 8 },
  { id: "jee-mathematics-permutations-combinations-q10", topicId: "jee-mathematics-permutations-combinations", text: "The identity nCr = nC(n−r) holds because:", optionA: "Choosing r equals leaving out n−r", optionB: "Coefficients are 1", optionC: "r = n", optionD: "The sum is 2ⁿ", correctOption: "A", explanation: "Selecting r objects is the same as excluding the other n−r.", orderIndex: 9 },
  { id: "jee-mathematics-permutations-combinations-q11", topicId: "jee-mathematics-permutations-combinations", text: "The value of nP0 is:", optionA: "1", optionB: "0", optionC: "n", optionD: "n!", correctOption: "A", explanation: "nP0 = 1 (one way to arrange zero objects).", orderIndex: 10 },
  { id: "jee-mathematics-permutations-combinations-q12", topicId: "jee-mathematics-permutations-combinations", text: "nCr is related to nPr by:", optionA: "nCr = nPr / r!", optionB: "nCr = nPr × r!", optionC: "nCr = nPr", optionD: "nCr = r!/nPr", correctOption: "A", explanation: "nCr = nPr/r! since order does not matter in combinations.", orderIndex: 11 },
  // Binomial theorem
  { id: "jee-mathematics-binomial-theorem-q09", topicId: "jee-mathematics-binomial-theorem", text: "The general term of (1 + x)ⁿ is:", optionA: "nCr xʳ", optionB: "nCr x^(n−r)", optionC: "xʳ", optionD: "nCr", correctOption: "A", explanation: "The (r+1)th term of (1+x)ⁿ is nCr xʳ.", orderIndex: 8 },
  { id: "jee-mathematics-binomial-theorem-q10", topicId: "jee-mathematics-binomial-theorem", text: "The sum of the binomial coefficients in (1+x)ⁿ is:", optionA: "2ⁿ", optionB: "n²", optionC: "n!", optionD: "2n", correctOption: "A", explanation: "Putting x = 1 gives the coefficient sum 2ⁿ.", orderIndex: 9 },
  { id: "jee-mathematics-binomial-theorem-q11", topicId: "jee-mathematics-binomial-theorem", text: "The number of terms in (a + b)ⁿ is:", optionA: "n + 1", optionB: "n", optionC: "2n", optionD: "n − 1", correctOption: "A", explanation: "There are n + 1 terms in the expansion of (a+b)ⁿ.", orderIndex: 10 },
  { id: "jee-mathematics-binomial-theorem-q12", topicId: "jee-mathematics-binomial-theorem", text: "For even n, the middle term of (a+b)ⁿ is the:", optionA: "(n/2 + 1)th term", optionB: "(n/2)th term", optionC: "(n+1)th term", optionD: "First term", correctOption: "A", explanation: "For even n, the single middle term is the (n/2 + 1)th.", orderIndex: 11 },
  // Matrices & determinants
  { id: "jee-mathematics-matrices-determinants-q09", topicId: "jee-mathematics-matrices-determinants", text: "A matrix has an inverse if and only if its determinant is:", optionA: "Non-zero", optionB: "Zero", optionC: "Positive only", optionD: "Equal to 1", correctOption: "A", explanation: "A matrix is invertible iff its determinant ≠ 0.", orderIndex: 8 },
  { id: "jee-mathematics-matrices-determinants-q10", topicId: "jee-mathematics-matrices-determinants", text: "A matrix with determinant zero is called:", optionA: "Singular", optionB: "Identity", optionC: "Orthogonal", optionD: "Symmetric", correctOption: "A", explanation: "A singular matrix has determinant zero and no inverse.", orderIndex: 9 },
  { id: "jee-mathematics-matrices-determinants-q11", topicId: "jee-mathematics-matrices-determinants", text: "The determinant of the product |AB| equals:", optionA: "|A||B|", optionB: "|A| + |B|", optionC: "|A|/|B|", optionD: "|A| − |B|", correctOption: "A", explanation: "det(AB) = det(A)·det(B).", orderIndex: 10 },
  { id: "jee-mathematics-matrices-determinants-q12", topicId: "jee-mathematics-matrices-determinants", text: "For a square matrix A, (Aᵀ)ᵀ equals:", optionA: "A", optionB: "Aᵀ", optionC: "A⁻¹", optionD: "The identity", correctOption: "A", explanation: "Transposing twice returns the original matrix.", orderIndex: 11 },
  // Straight lines & circles
  { id: "jee-mathematics-straight-lines-circles-q09", topicId: "jee-mathematics-straight-lines-circles", text: "The slope of a line making angle θ with the x-axis is:", optionA: "tan θ", optionB: "sin θ", optionC: "cos θ", optionD: "cot θ", correctOption: "A", explanation: "The slope m = tan θ.", orderIndex: 8 },
  { id: "jee-mathematics-straight-lines-circles-q10", topicId: "jee-mathematics-straight-lines-circles", text: "Two lines are perpendicular when the product of their slopes is:", optionA: "−1", optionB: "1", optionC: "0", optionD: "∞", correctOption: "A", explanation: "Perpendicular lines have m₁·m₂ = −1.", orderIndex: 9 },
  { id: "jee-mathematics-straight-lines-circles-q11", topicId: "jee-mathematics-straight-lines-circles", text: "The equation of a circle of radius r centred at the origin is:", optionA: "x² + y² = r²", optionB: "x² − y² = r²", optionC: "x + y = r", optionD: "xy = r²", correctOption: "A", explanation: "A circle centred at origin: x² + y² = r².", orderIndex: 10 },
  { id: "jee-mathematics-straight-lines-circles-q12", topicId: "jee-mathematics-straight-lines-circles", text: "Two lines are parallel when their slopes are:", optionA: "Equal", optionB: "Negative reciprocals", optionC: "Zero", optionD: "Product −1", correctOption: "A", explanation: "Parallel lines have equal slopes.", orderIndex: 11 },
  // Limits & continuity
  { id: "jee-mathematics-limits-continuity-q09", topicId: "jee-mathematics-limits-continuity", text: "The value of lim(x→0) (sin x)/x is:", optionA: "1", optionB: "0", optionC: "∞", optionD: "undefined", correctOption: "A", explanation: "This standard limit equals 1.", orderIndex: 8 },
  { id: "jee-mathematics-limits-continuity-q10", topicId: "jee-mathematics-limits-continuity", text: "A differentiable function is necessarily:", optionA: "Continuous", optionB: "Discontinuous", optionC: "Constant", optionD: "Zero", correctOption: "A", explanation: "Differentiability implies continuity.", orderIndex: 9 },
  { id: "jee-mathematics-limits-continuity-q11", topicId: "jee-mathematics-limits-continuity", text: "The limit lim(n→∞)(1 + 1/n)ⁿ equals:", optionA: "e", optionB: "1", optionC: "0", optionD: "∞", correctOption: "A", explanation: "This is the definition of e.", orderIndex: 10 },
  { id: "jee-mathematics-limits-continuity-q12", topicId: "jee-mathematics-limits-continuity", text: "The function f(x) = |x| is not differentiable at:", optionA: "x = 0", optionB: "x = 1", optionC: "all points", optionD: "no point", correctOption: "A", explanation: "|x| has a corner at x = 0, so it is not differentiable there.", orderIndex: 11 },
  // Integration
  { id: "jee-mathematics-integration-q09", topicId: "jee-mathematics-integration", text: "∫ xⁿ dx (n ≠ −1) equals:", optionA: "x^(n+1)/(n+1) + C", optionB: "nxⁿ⁻¹", optionC: "xⁿ", optionD: "ln x", correctOption: "A", explanation: "The power rule of integration gives x^(n+1)/(n+1) + C.", orderIndex: 8 },
  { id: "jee-mathematics-integration-q10", topicId: "jee-mathematics-integration", text: "∫ (1/x) dx equals:", optionA: "ln|x| + C", optionB: "x²/2", optionC: "−1/x²", optionD: "1", correctOption: "A", explanation: "∫(1/x)dx = ln|x| + C.", orderIndex: 9 },
  { id: "jee-mathematics-integration-q11", topicId: "jee-mathematics-integration", text: "For an odd function, ∫ from −a to a equals:", optionA: "0", optionB: "2∫ from 0 to a", optionC: "a²", optionD: "f(a)", correctOption: "A", explanation: "The integral of an odd function over a symmetric interval is zero.", orderIndex: 10 },
  { id: "jee-mathematics-integration-q12", topicId: "jee-mathematics-integration", text: "∫ eˣ dx equals:", optionA: "eˣ + C", optionB: "x eˣ", optionC: "eˣ/x", optionD: "ln x", correctOption: "A", explanation: "The integral of eˣ is eˣ + C.", orderIndex: 11 },
  // Vectors & 3D
  { id: "jee-mathematics-vectors-3d-q09", topicId: "jee-mathematics-vectors-3d", text: "The dot product a·b equals:", optionA: "|a||b| cos θ", optionB: "|a||b| sin θ", optionC: "|a| + |b|", optionD: "|a×b|", correctOption: "A", explanation: "The scalar product a·b = |a||b|cos θ.", orderIndex: 8 },
  { id: "jee-mathematics-vectors-3d-q10", topicId: "jee-mathematics-vectors-3d", text: "Two nonzero vectors are perpendicular when their dot product is:", optionA: "0", optionB: "1", optionC: "|a||b|", optionD: "Negative", correctOption: "A", explanation: "a·b = 0 means the vectors are perpendicular.", orderIndex: 9 },
  { id: "jee-mathematics-vectors-3d-q11", topicId: "jee-mathematics-vectors-3d", text: "The magnitude |a×b| gives the:", optionA: "Area of the parallelogram formed by a and b", optionB: "Volume of a cube", optionC: "Length of a", optionD: "Dot product", correctOption: "A", explanation: "|a×b| = |a||b|sin θ is the parallelogram area.", orderIndex: 10 },
  { id: "jee-mathematics-vectors-3d-q12", topicId: "jee-mathematics-vectors-3d", text: "Three vectors are coplanar when their scalar triple product is:", optionA: "0", optionB: "1", optionC: "Positive", optionD: "Negative", correctOption: "A", explanation: "A zero scalar triple product means the vectors are coplanar.", orderIndex: 11 },
  // Probability
  { id: "jee-mathematics-probability-q09", topicId: "jee-mathematics-probability", text: "For two events, P(A∪B) equals:", optionA: "P(A) + P(B) − P(A∩B)", optionB: "P(A) + P(B)", optionC: "P(A)P(B)", optionD: "P(A) − P(B)", correctOption: "A", explanation: "The addition rule subtracts the overlap.", orderIndex: 8 },
  { id: "jee-mathematics-probability-q10", topicId: "jee-mathematics-probability", text: "Events A and B are independent when P(A∩B) equals:", optionA: "P(A)P(B)", optionB: "0", optionC: "P(A) + P(B)", optionD: "1", correctOption: "A", explanation: "Independence means P(A∩B) = P(A)P(B).", orderIndex: 9 },
  { id: "jee-mathematics-probability-q11", topicId: "jee-mathematics-probability", text: "The conditional probability P(A|B) equals:", optionA: "P(A∩B)/P(B)", optionB: "P(A)P(B)", optionC: "P(A∪B)/P(A)", optionD: "P(B)/P(A)", correctOption: "A", explanation: "P(A|B) = P(A∩B)/P(B).", orderIndex: 10 },
  { id: "jee-mathematics-probability-q12", topicId: "jee-mathematics-probability", text: "For mutually exclusive events, P(A∩B) equals:", optionA: "0", optionB: "P(A)P(B)", optionC: "P(A)+P(B)", optionD: "1", correctOption: "A", explanation: "Mutually exclusive events cannot co-occur, so P(A∩B) = 0.", orderIndex: 11 },
  // Sets, relations & functions
  { id: "jee-mathematics-sets-relations-functions-q09", topicId: "jee-mathematics-sets-relations-functions", text: "The number of subsets of a set with n elements is:", optionA: "2ⁿ", optionB: "n²", optionC: "n!", optionD: "2n", correctOption: "A", explanation: "A set of n elements has 2ⁿ subsets.", orderIndex: 8 },
  { id: "jee-mathematics-sets-relations-functions-q10", topicId: "jee-mathematics-sets-relations-functions", text: "A function that is both one-one and onto is called:", optionA: "Bijective", optionB: "Injective only", optionC: "Surjective only", optionD: "Constant", correctOption: "A", explanation: "A bijection is both injective (one-one) and surjective (onto).", orderIndex: 9 },
  { id: "jee-mathematics-sets-relations-functions-q11", topicId: "jee-mathematics-sets-relations-functions", text: "An equivalence relation is reflexive, symmetric, and:", optionA: "Transitive", optionB: "Antisymmetric", optionC: "Irreflexive", optionD: "Bijective", correctOption: "A", explanation: "An equivalence relation is reflexive, symmetric, and transitive.", orderIndex: 10 },
  { id: "jee-mathematics-sets-relations-functions-q12", topicId: "jee-mathematics-sets-relations-functions", text: "For sets, n(A∪B) equals:", optionA: "n(A) + n(B) − n(A∩B)", optionB: "n(A) + n(B)", optionC: "n(A)n(B)", optionD: "n(A) − n(B)", correctOption: "A", explanation: "The inclusion–exclusion principle for two sets.", orderIndex: 11 },
  // Trigonometric identities
  { id: "jee-mathematics-trigonometric-identities-q09", topicId: "jee-mathematics-trigonometric-identities", text: "The identity sin²θ + cos²θ equals:", optionA: "1", optionB: "0", optionC: "2", optionD: "tan²θ", correctOption: "A", explanation: "The fundamental Pythagorean identity: sin²θ + cos²θ = 1.", orderIndex: 8 },
  { id: "jee-mathematics-trigonometric-identities-q10", topicId: "jee-mathematics-trigonometric-identities", text: "sin 2θ equals:", optionA: "2 sin θ cos θ", optionB: "cos²θ − sin²θ", optionC: "2 cos²θ", optionD: "1 − 2sin²θ", correctOption: "A", explanation: "The double-angle formula: sin 2θ = 2 sin θ cos θ.", orderIndex: 9 },
  { id: "jee-mathematics-trigonometric-identities-q11", topicId: "jee-mathematics-trigonometric-identities", text: "The value of cos 0° is:", optionA: "1", optionB: "0", optionC: "−1", optionD: "1/2", correctOption: "A", explanation: "cos 0° = 1, its maximum value on the unit circle.", orderIndex: 10 },
  { id: "jee-mathematics-trigonometric-identities-q12", topicId: "jee-mathematics-trigonometric-identities", text: "1 + tan²θ equals:", optionA: "sec²θ", optionB: "cosec²θ", optionC: "cot²θ", optionD: "1", correctOption: "A", explanation: "The identity 1 + tan²θ = sec²θ.", orderIndex: 11 },
  // Inverse trigonometry
  { id: "jee-mathematics-inverse-trigonometry-q09", topicId: "jee-mathematics-inverse-trigonometry", text: "The principal value range of sin⁻¹x is:", optionA: "[−π/2, π/2]", optionB: "[0, π]", optionC: "[−π, π]", optionD: "[0, 2π]", correctOption: "A", explanation: "sin⁻¹x has principal range [−π/2, π/2].", orderIndex: 8 },
  { id: "jee-mathematics-inverse-trigonometry-q10", topicId: "jee-mathematics-inverse-trigonometry", text: "The principal value range of cos⁻¹x is:", optionA: "[0, π]", optionB: "[−π/2, π/2]", optionC: "[−π, π]", optionD: "[0, 2π]", correctOption: "A", explanation: "cos⁻¹x has principal range [0, π].", orderIndex: 9 },
  { id: "jee-mathematics-inverse-trigonometry-q11", topicId: "jee-mathematics-inverse-trigonometry", text: "The value of sin⁻¹(1) is:", optionA: "π/2", optionB: "0", optionC: "π", optionD: "−π/2", correctOption: "A", explanation: "sin(π/2) = 1, so sin⁻¹(1) = π/2.", orderIndex: 10 },
  { id: "jee-mathematics-inverse-trigonometry-q12", topicId: "jee-mathematics-inverse-trigonometry", text: "sin⁻¹x + cos⁻¹x equals:", optionA: "π/2", optionB: "π", optionC: "0", optionD: "1", correctOption: "A", explanation: "The identity sin⁻¹x + cos⁻¹x = π/2.", orderIndex: 11 },
  // Conic sections
  { id: "jee-mathematics-conic-sections-q09", topicId: "jee-mathematics-conic-sections", text: "The eccentricity of a parabola is:", optionA: "1", optionB: "0", optionC: "less than 1", optionD: "greater than 1", correctOption: "A", explanation: "A parabola has eccentricity e = 1.", orderIndex: 8 },
  { id: "jee-mathematics-conic-sections-q10", topicId: "jee-mathematics-conic-sections", text: "For the parabola y² = 4ax, the focus is at:", optionA: "(a, 0)", optionB: "(0, a)", optionC: "(−a, 0)", optionD: "(0, −a)", correctOption: "A", explanation: "y² = 4ax has focus (a, 0).", orderIndex: 9 },
  { id: "jee-mathematics-conic-sections-q11", topicId: "jee-mathematics-conic-sections", text: "An ellipse has eccentricity:", optionA: "0 < e < 1", optionB: "e = 1", optionC: "e > 1", optionD: "e = 0 only", correctOption: "A", explanation: "An ellipse has eccentricity between 0 and 1.", orderIndex: 10 },
  { id: "jee-mathematics-conic-sections-q12", topicId: "jee-mathematics-conic-sections", text: "A conic with e > 1 is a:", optionA: "Hyperbola", optionB: "Parabola", optionC: "Ellipse", optionD: "Circle", correctOption: "A", explanation: "Eccentricity greater than 1 defines a hyperbola.", orderIndex: 11 },
  // Differential equations
  { id: "jee-mathematics-differential-equations-q09", topicId: "jee-mathematics-differential-equations", text: "The order of a differential equation is the:", optionA: "Highest-order derivative present", optionB: "Power of the highest derivative", optionC: "Number of terms", optionD: "Degree of the polynomial", correctOption: "A", explanation: "Order is the highest derivative appearing.", orderIndex: 8 },
  { id: "jee-mathematics-differential-equations-q10", topicId: "jee-mathematics-differential-equations", text: "The solution of dy/dx = ky is:", optionA: "y = Ce^(kx)", optionB: "y = kx + C", optionC: "y = C/x", optionD: "y = kx²", correctOption: "A", explanation: "dy/dx = ky gives exponential y = Ce^(kx).", orderIndex: 9 },
  { id: "jee-mathematics-differential-equations-q11", topicId: "jee-mathematics-differential-equations", text: "A first-order linear equation uses the integrating factor:", optionA: "e^(∫P dx)", optionB: "e^(∫Q dx)", optionC: "∫P dx", optionD: "e^(−x)", correctOption: "A", explanation: "The integrating factor is e^(∫P dx).", orderIndex: 10 },
  { id: "jee-mathematics-differential-equations-q12", topicId: "jee-mathematics-differential-equations", text: "The number of arbitrary constants in the general solution equals the:", optionA: "Order", optionB: "Degree", optionC: "Number of variables", optionD: "Always one", correctOption: "A", explanation: "A general solution has as many constants as the order.", orderIndex: 11 },
  // Application of derivatives
  { id: "jee-mathematics-application-of-derivatives-q09", topicId: "jee-mathematics-application-of-derivatives", text: "At a local maximum of a differentiable function, the first derivative is:", optionA: "Zero", optionB: "Maximum", optionC: "Infinite", optionD: "Negative always", correctOption: "A", explanation: "At a local extremum, f'(x) = 0 (a critical point).", orderIndex: 8 },
  { id: "jee-mathematics-application-of-derivatives-q10", topicId: "jee-mathematics-application-of-derivatives", text: "A function is increasing on an interval where its derivative is:", optionA: "Positive", optionB: "Negative", optionC: "Zero", optionD: "Undefined", correctOption: "A", explanation: "f'(x) > 0 implies the function is increasing.", orderIndex: 9 },
  { id: "jee-mathematics-application-of-derivatives-q11", topicId: "jee-mathematics-application-of-derivatives", text: "The second-derivative test identifies a local minimum when f''(x) is:", optionA: "Positive", optionB: "Negative", optionC: "Zero", optionD: "Infinite", correctOption: "A", explanation: "f''(x) > 0 at a critical point indicates a local minimum.", orderIndex: 10 },
  { id: "jee-mathematics-application-of-derivatives-q12", topicId: "jee-mathematics-application-of-derivatives", text: "The derivative dy/dx represents the ______ of the tangent to the curve.", optionA: "Slope", optionB: "Area", optionC: "Length", optionD: "Curvature only", correctOption: "A", explanation: "dy/dx gives the slope of the tangent to the curve.", orderIndex: 11 },
  // Area under curves
  { id: "jee-mathematics-area-under-curves-q09", topicId: "jee-mathematics-area-under-curves", text: "The area under y = f(x) from a to b (f ≥ 0) is:", optionA: "∫ from a to b of y dx", optionB: "∫ y² dx", optionC: "f(b) − f(a)", optionD: "dy/dx", correctOption: "A", explanation: "The definite integral ∫_a^b y dx gives the area under the curve.", orderIndex: 8 },
  { id: "jee-mathematics-area-under-curves-q10", topicId: "jee-mathematics-area-under-curves", text: "The value of ∫ from 0 to 1 of x dx is:", optionA: "1/2", optionB: "1", optionC: "2", optionD: "0", correctOption: "A", explanation: "∫₀¹ x dx = [x²/2]₀¹ = 1/2.", orderIndex: 9 },
  { id: "jee-mathematics-area-under-curves-q11", topicId: "jee-mathematics-area-under-curves", text: "The area between two curves is found by integrating the:", optionA: "Difference of the functions", optionB: "Product of the functions", optionC: "Sum of the functions", optionD: "Ratio of the functions", correctOption: "A", explanation: "Area between curves = ∫ (upper − lower) dx.", orderIndex: 10 },
  { id: "jee-mathematics-area-under-curves-q12", topicId: "jee-mathematics-area-under-curves", text: "The value of ∫ from 0 to π of sin x dx is:", optionA: "2", optionB: "0", optionC: "1", optionD: "π", correctOption: "A", explanation: "∫₀^π sin x dx = [−cos x]₀^π = 2.", orderIndex: 11 },
  // Statistics & reasoning
  { id: "jee-mathematics-statistics-reasoning-q09", topicId: "jee-mathematics-statistics-reasoning", text: "The mean of n observations is their sum divided by:", optionA: "n", optionB: "n − 1", optionC: "n + 1", optionD: "n²", correctOption: "A", explanation: "The arithmetic mean is the sum of observations divided by n.", orderIndex: 8 },
  { id: "jee-mathematics-statistics-reasoning-q10", topicId: "jee-mathematics-statistics-reasoning", text: "The measure of spread that is the square of the standard deviation is the:", optionA: "Variance", optionB: "Mean", optionC: "Median", optionD: "Mode", correctOption: "A", explanation: "Variance is the square of the standard deviation.", orderIndex: 9 },
  { id: "jee-mathematics-statistics-reasoning-q11", topicId: "jee-mathematics-statistics-reasoning", text: "The negation of 'p and q' (De Morgan) is:", optionA: "not p or not q", optionB: "not p and not q", optionC: "p or q", optionD: "p and not q", correctOption: "A", explanation: "By De Morgan's law, ¬(p ∧ q) = ¬p ∨ ¬q.", orderIndex: 10 },
  { id: "jee-mathematics-statistics-reasoning-q12", topicId: "jee-mathematics-statistics-reasoning", text: "The most frequently occurring value in a data set is the:", optionA: "Mode", optionB: "Mean", optionC: "Median", optionD: "Range", correctOption: "A", explanation: "The mode is the value that appears most often.", orderIndex: 11 },
  // Heights & distances
  { id: "jee-mathematics-heights-distances-q09", topicId: "jee-mathematics-heights-distances", text: "The angle of elevation is measured from the horizontal:", optionA: "Upward to the object", optionB: "Downward", optionC: "Along the ground", optionD: "Vertically only", correctOption: "A", explanation: "The angle of elevation is measured upward from the horizontal to the object.", orderIndex: 8 },
  { id: "jee-mathematics-heights-distances-q10", topicId: "jee-mathematics-heights-distances", text: "If the angle of elevation of a tower's top from a point is 45°, the height equals the:", optionA: "Horizontal distance", optionB: "Twice the distance", optionC: "Half the distance", optionD: "Zero", correctOption: "A", explanation: "tan 45° = 1, so height = horizontal distance.", orderIndex: 9 },
  { id: "jee-mathematics-heights-distances-q11", topicId: "jee-mathematics-heights-distances", text: "The angle of depression from a height to a point on the ground is measured from the:", optionA: "Horizontal downward", optionB: "Vertical", optionC: "Ground up", optionD: "Object itself", correctOption: "A", explanation: "The angle of depression is measured downward from the horizontal.", orderIndex: 10 },
  { id: "jee-mathematics-heights-distances-q12", topicId: "jee-mathematics-heights-distances", text: "In a right triangle, tan θ equals:", optionA: "opposite/adjacent", optionB: "adjacent/opposite", optionC: "opposite/hypotenuse", optionD: "adjacent/hypotenuse", correctOption: "A", explanation: "tan θ = opposite/adjacent.", orderIndex: 11 }
];
