// JEE Advanced depth expansion — question-density top-up. Raises the highest-
// yield JEE Advanced topics from 12 to 16 questions each (q13–q16, orderIndex
// 12–15), spread across Physics, Chemistry and Mathematics. No new topics.
import type { Question } from "@jyotir/core";

export const advDepthQuestions: Question[] = [
  // ── Physics: Rotational Dynamics & Rigid Bodies ──
  { id: "jee-adv-phy-rotational-dynamics-q13", topicId: "jee-adv-phy-rotational-dynamics", text: "The moment of inertia of a solid sphere about its diameter is:", optionA: "(2/5)MR²", optionB: "(2/3)MR²", optionC: "MR²", optionD: "½MR²", correctOption: "A", explanation: "A solid sphere has I = (2/5)MR² about a diameter.", orderIndex: 12 },
  { id: "jee-adv-phy-rotational-dynamics-q14", topicId: "jee-adv-phy-rotational-dynamics", text: "For a body rolling without slipping, the fraction of kinetic energy that is rotational for a solid sphere is:", optionA: "2/7", optionB: "5/7", optionC: "1/2", optionD: "1/3", correctOption: "A", explanation: "Rotational KE fraction = I/(I+MR²) = (2/5)/(7/5) = 2/7.", orderIndex: 13 },
  { id: "jee-adv-phy-rotational-dynamics-q15", topicId: "jee-adv-phy-rotational-dynamics", text: "Which body rolls down an incline fastest (smallest I/MR²)?", optionA: "Solid sphere", optionB: "Hollow sphere", optionC: "Ring", optionD: "Hollow cylinder", correctOption: "A", explanation: "The solid sphere has the smallest I/MR², so it accelerates fastest.", orderIndex: 14 },
  { id: "jee-adv-phy-rotational-dynamics-q16", topicId: "jee-adv-phy-rotational-dynamics", text: "The parallel-axis theorem states that I = I_cm +", optionA: "Md²", optionB: "MR²", optionC: "½Md²", optionD: "Md²/2", correctOption: "A", explanation: "I = I_cm + Md² for an axis a distance d from the centre of mass.", orderIndex: 15 },

  // ── Physics: Electromagnetic Induction & AC ──
  { id: "jee-adv-phy-electromagnetic-induction-q13", topicId: "jee-adv-phy-electromagnetic-induction", text: "Faraday's law states that the induced EMF equals the negative rate of change of:", optionA: "Magnetic flux", optionB: "Electric field", optionC: "Charge", optionD: "Current", correctOption: "A", explanation: "EMF = −dΦ_B/dt, the rate of change of magnetic flux.", orderIndex: 12 },
  { id: "jee-adv-phy-electromagnetic-induction-q14", topicId: "jee-adv-phy-electromagnetic-induction", text: "Lenz's law is a consequence of the conservation of:", optionA: "Energy", optionB: "Charge", optionC: "Momentum", optionD: "Mass", correctOption: "A", explanation: "The induced current opposes the change, conserving energy.", orderIndex: 13 },
  { id: "jee-adv-phy-electromagnetic-induction-q15", topicId: "jee-adv-phy-electromagnetic-induction", text: "In a series LCR circuit at resonance, the impedance equals:", optionA: "R (a minimum)", optionB: "X_L", optionC: "X_C", optionD: "Zero", correctOption: "A", explanation: "At resonance X_L = X_C, so Z = R is minimum and current is maximum.", orderIndex: 14 },
  { id: "jee-adv-phy-electromagnetic-induction-q16", topicId: "jee-adv-phy-electromagnetic-induction", text: "The energy stored in an inductor carrying current I is:", optionA: "½LI²", optionB: "LI²", optionC: "½L²I", optionD: "LI", correctOption: "A", explanation: "Magnetic energy stored in an inductor is U = ½LI².", orderIndex: 15 },

  // ── Physics: Modern Physics: Photoelectric & Atomic ──
  { id: "jee-adv-phy-modern-physics-q13", topicId: "jee-adv-phy-modern-physics", text: "The maximum kinetic energy of a photoelectron equals hν minus the:", optionA: "Work function", optionB: "Rest energy", optionC: "Binding energy of the nucleus", optionD: "Kinetic energy of the photon", correctOption: "A", explanation: "Einstein's equation: KE_max = hν − φ (the work function).", orderIndex: 12 },
  { id: "jee-adv-phy-modern-physics-q14", topicId: "jee-adv-phy-modern-physics", text: "The de Broglie wavelength of a particle of momentum p is:", optionA: "h/p", optionB: "p/h", optionC: "hp", optionD: "h/p²", correctOption: "A", explanation: "λ = h/p, the de Broglie relation.", orderIndex: 13 },
  { id: "jee-adv-phy-modern-physics-q15", topicId: "jee-adv-phy-modern-physics", text: "The energy of the nth hydrogen level is proportional to:", optionA: "−1/n²", optionB: "−n²", optionC: "−1/n", optionD: "−n", correctOption: "A", explanation: "The Bohr energy level is Eₙ = −13.6/n² eV, scaling as −1/n².", orderIndex: 14 },
  { id: "jee-adv-phy-modern-physics-q16", topicId: "jee-adv-phy-modern-physics", text: "The stopping potential in the photoelectric effect depends on the light's:", optionA: "Frequency", optionB: "Intensity", optionC: "Polarisation", optionD: "Phase", correctOption: "A", explanation: "Stopping potential depends on frequency, not intensity.", orderIndex: 15 },

  // ── Physics: Wave Optics: Interference & Diffraction ──
  { id: "jee-adv-phy-wave-optics-q13", topicId: "jee-adv-phy-wave-optics", text: "In Young's double-slit experiment, the fringe width is proportional to the:", optionA: "Wavelength", optionB: "Slit width", optionC: "Frequency", optionD: "Intensity", correctOption: "A", explanation: "Fringe width β = λD/d, proportional to wavelength.", orderIndex: 12 },
  { id: "jee-adv-phy-wave-optics-q14", topicId: "jee-adv-phy-wave-optics", text: "Constructive interference occurs when the path difference is:", optionA: "An integer multiple of λ", optionB: "A half-integer multiple of λ", optionC: "λ/4", optionD: "Zero only", correctOption: "A", explanation: "Constructive interference needs path difference = nλ.", orderIndex: 13 },
  { id: "jee-adv-phy-wave-optics-q15", topicId: "jee-adv-phy-wave-optics", text: "The condition for the first minimum in single-slit diffraction is a sin θ =", optionA: "λ", optionB: "λ/2", optionC: "2λ", optionD: "0", correctOption: "A", explanation: "The first diffraction minimum occurs at a sin θ = λ.", orderIndex: 14 },
  { id: "jee-adv-phy-wave-optics-q16", topicId: "jee-adv-phy-wave-optics", text: "Light waves can interfere observably only if the sources are:", optionA: "Coherent", optionB: "Incoherent", optionC: "Of different frequency", optionD: "Unpolarised only", correctOption: "A", explanation: "A stable interference pattern requires coherent sources (constant phase difference).", orderIndex: 15 },

  // ── Chemistry: Organic Reaction Mechanisms ──
  { id: "jee-adv-chem-organic-mechanisms-q13", topicId: "jee-adv-chem-organic-mechanisms", text: "An SN1 reaction proceeds through a ____ intermediate.", optionA: "Carbocation", optionB: "Carbanion", optionC: "Free radical", optionD: "Carbene", correctOption: "A", explanation: "SN1 forms a carbocation in the rate-determining step.", orderIndex: 12 },
  { id: "jee-adv-chem-organic-mechanisms-q14", topicId: "jee-adv-chem-organic-mechanisms", text: "The rate of an SN2 reaction depends on:", optionA: "Both substrate and nucleophile concentrations", optionB: "Only the substrate", optionC: "Only the nucleophile", optionD: "Neither", correctOption: "A", explanation: "SN2 is bimolecular — rate depends on both substrate and nucleophile.", orderIndex: 13 },
  { id: "jee-adv-chem-organic-mechanisms-q15", topicId: "jee-adv-chem-organic-mechanisms", text: "SN2 reactions proceed with ____ of configuration.", optionA: "Inversion", optionB: "Retention", optionC: "Racemisation", optionD: "No change", correctOption: "A", explanation: "The backside attack in SN2 inverts the stereocentre (Walden inversion).", orderIndex: 14 },
  { id: "jee-adv-chem-organic-mechanisms-q16", topicId: "jee-adv-chem-organic-mechanisms", text: "Markovnikov's rule predicts that in HX addition to an alkene, H adds to the carbon with:", optionA: "More hydrogens", optionB: "Fewer hydrogens", optionC: "A halogen", optionD: "A double bond only", correctOption: "A", explanation: "H adds to the carbon with more H's, forming the more stable carbocation.", orderIndex: 15 },

  // ── Chemistry: Chemical Thermodynamics & Equilibrium ──
  { id: "jee-adv-chem-thermo-equilibrium-q13", topicId: "jee-adv-chem-thermo-equilibrium", text: "For a spontaneous process at constant T and P, the Gibbs free energy change is:", optionA: "Negative", optionB: "Positive", optionC: "Zero", optionD: "Infinite", correctOption: "A", explanation: "ΔG < 0 indicates a spontaneous process.", orderIndex: 12 },
  { id: "jee-adv-chem-thermo-equilibrium-q14", topicId: "jee-adv-chem-thermo-equilibrium", text: "At equilibrium, ΔG equals:", optionA: "Zero", optionB: "Negative", optionC: "Positive", optionD: "ΔH", correctOption: "A", explanation: "At equilibrium the Gibbs free energy change is zero.", orderIndex: 13 },
  { id: "jee-adv-chem-thermo-equilibrium-q15", topicId: "jee-adv-chem-thermo-equilibrium", text: "The relationship ΔG° = −RT ln K shows that a large K corresponds to a:", optionA: "Large negative ΔG°", optionB: "Large positive ΔG°", optionC: "Zero ΔG°", optionD: "Zero K only", correctOption: "A", explanation: "A large equilibrium constant means a strongly negative standard free-energy change.", orderIndex: 14 },
  { id: "jee-adv-chem-thermo-equilibrium-q16", topicId: "jee-adv-chem-thermo-equilibrium", text: "According to Le Chatelier's principle, increasing pressure shifts an equilibrium toward the side with:", optionA: "Fewer moles of gas", optionB: "More moles of gas", optionC: "More solids", optionD: "Higher temperature", correctOption: "A", explanation: "Higher pressure favours the side with fewer gas moles.", orderIndex: 15 },

  // ── Chemistry: Coordination Compounds & CFT ──
  { id: "jee-adv-chem-coordination-q13", topicId: "jee-adv-chem-coordination", text: "The coordination number of the metal in [Co(NH₃)₆]³⁺ is:", optionA: "6", optionB: "3", optionC: "4", optionD: "2", correctOption: "A", explanation: "Six ammonia ligands give a coordination number of 6.", orderIndex: 12 },
  { id: "jee-adv-chem-coordination-q14", topicId: "jee-adv-chem-coordination", text: "A strong-field ligand generally produces a ____ complex.", optionA: "Low-spin", optionB: "High-spin", optionC: "Colourless", optionD: "Non-magnetic always", correctOption: "A", explanation: "Strong-field ligands cause large splitting, favouring electron pairing (low spin).", orderIndex: 13 },
  { id: "jee-adv-chem-coordination-q15", topicId: "jee-adv-chem-coordination", text: "In an octahedral field, the d-orbitals split into t₂g and:", optionA: "e_g", optionB: "a₁g", optionC: "t₁u", optionD: "s and p", correctOption: "A", explanation: "Octahedral crystal field splits d-orbitals into lower t₂g and higher e_g sets.", orderIndex: 14 },
  { id: "jee-adv-chem-coordination-q16", topicId: "jee-adv-chem-coordination", text: "EDTA is a ____ ligand.", optionA: "Hexadentate", optionB: "Monodentate", optionC: "Bidentate", optionD: "Ambidentate", correctOption: "A", explanation: "EDTA binds through six donor sites, making it hexadentate.", orderIndex: 15 },

  // ── Chemistry: Electrochemistry & the Nernst Equation ──
  { id: "jee-adv-chem-electrochemistry-q13", topicId: "jee-adv-chem-electrochemistry", text: "In a galvanic cell, oxidation occurs at the:", optionA: "Anode", optionB: "Cathode", optionC: "Salt bridge", optionD: "Electrolyte", correctOption: "A", explanation: "Oxidation always occurs at the anode; reduction at the cathode.", orderIndex: 12 },
  { id: "jee-adv-chem-electrochemistry-q14", topicId: "jee-adv-chem-electrochemistry", text: "The Nernst equation relates cell potential to the:", optionA: "Reaction quotient Q", optionB: "Coupon", optionC: "Bond order", optionD: "Molar mass", correctOption: "A", explanation: "E = E° − (RT/nF) ln Q relates potential to the reaction quotient.", orderIndex: 13 },
  { id: "jee-adv-chem-electrochemistry-q15", topicId: "jee-adv-chem-electrochemistry", text: "The standard free-energy change relates to the cell potential by ΔG° =", optionA: "−nFE°", optionB: "nFE°", optionC: "−RT ln E°", optionD: "nF/E°", correctOption: "A", explanation: "ΔG° = −nFE°, linking free energy and standard cell potential.", orderIndex: 14 },
  { id: "jee-adv-chem-electrochemistry-q16", topicId: "jee-adv-chem-electrochemistry", text: "According to Faraday's first law, the mass deposited is proportional to the:", optionA: "Charge passed", optionB: "Voltage only", optionC: "Time squared", optionD: "Resistance", correctOption: "A", explanation: "Mass deposited is proportional to the total charge (Q = It) passed.", orderIndex: 15 },

  // ── Mathematics: Definite Integrals & Applications ──
  { id: "jee-adv-math-definite-integrals-q13", topicId: "jee-adv-math-definite-integrals", text: "The value of ∫₀^(π/2) sin x dx is:", optionA: "1", optionB: "0", optionC: "π/2", optionD: "2", correctOption: "A", explanation: "[−cos x]₀^(π/2) = 0 − (−1) = 1.", orderIndex: 12 },
  { id: "jee-adv-math-definite-integrals-q14", topicId: "jee-adv-math-definite-integrals", text: "The property ∫₀^a f(x) dx = ∫₀^a f(a−x) dx is a:", optionA: "King property of definite integrals", optionB: "Product rule", optionC: "Chain rule", optionD: "Quotient rule", correctOption: "A", explanation: "This is the 'king' reflection property used to simplify definite integrals.", orderIndex: 13 },
  { id: "jee-adv-math-definite-integrals-q15", topicId: "jee-adv-math-definite-integrals", text: "For an odd function f, ∫₋a^a f(x) dx equals:", optionA: "0", optionB: "2∫₀^a f(x) dx", optionC: "a²", optionD: "1", correctOption: "A", explanation: "The integral of an odd function over a symmetric interval is zero.", orderIndex: 14 },
  { id: "jee-adv-math-definite-integrals-q16", topicId: "jee-adv-math-definite-integrals", text: "The area under y = f(x) from a to b is given by:", optionA: "∫ₐ^b f(x) dx", optionB: "f(b) − f(a)", optionC: "f'(x)", optionD: "The average of f", correctOption: "A", explanation: "The definite integral gives the (signed) area under the curve.", orderIndex: 15 },

  // ── Mathematics: Probability & Bayes' Theorem ──
  { id: "jee-adv-math-probability-q13", topicId: "jee-adv-math-probability", text: "For independent events A and B, P(A ∩ B) equals:", optionA: "P(A)·P(B)", optionB: "P(A) + P(B)", optionC: "P(A) − P(B)", optionD: "P(A)/P(B)", correctOption: "A", explanation: "Independent events multiply: P(A ∩ B) = P(A)P(B).", orderIndex: 12 },
  { id: "jee-adv-math-probability-q14", topicId: "jee-adv-math-probability", text: "Bayes' theorem gives P(A|B) = P(B|A)·P(A) /", optionA: "P(B)", optionB: "P(A)", optionC: "P(B|A)", optionD: "1", correctOption: "A", explanation: "The denominator is the total probability of the evidence, P(B).", orderIndex: 13 },
  { id: "jee-adv-math-probability-q15", topicId: "jee-adv-math-probability", text: "For mutually exclusive events, P(A ∪ B) equals:", optionA: "P(A) + P(B)", optionB: "P(A)·P(B)", optionC: "P(A) − P(B)", optionD: "0", correctOption: "A", explanation: "Mutually exclusive events cannot co-occur, so probabilities add.", orderIndex: 14 },
  { id: "jee-adv-math-probability-q16", topicId: "jee-adv-math-probability", text: "The mean (expected value) of a binomial distribution B(n, p) is:", optionA: "np", optionB: "np(1−p)", optionC: "p/n", optionD: "n/p", correctOption: "A", explanation: "The mean of a binomial distribution is np.", orderIndex: 15 },

  // ── Mathematics: Conic Sections & Coordinate Geometry ──
  { id: "jee-adv-math-conics-q13", topicId: "jee-adv-math-conics", text: "The eccentricity of a parabola is:", optionA: "1", optionB: "0", optionC: "Between 0 and 1", optionD: "Greater than 1", correctOption: "A", explanation: "A parabola has eccentricity exactly 1.", orderIndex: 12 },
  { id: "jee-adv-math-conics-q14", topicId: "jee-adv-math-conics", text: "For the ellipse x²/a² + y²/b² = 1 (a > b), the eccentricity is:", optionA: "√(1 − b²/a²)", optionB: "√(1 + b²/a²)", optionC: "b/a", optionD: "a/b", correctOption: "A", explanation: "e = √(1 − b²/a²) for an ellipse with a > b.", orderIndex: 13 },
  { id: "jee-adv-math-conics-q15", topicId: "jee-adv-math-conics", text: "The length of the latus rectum of y² = 4ax is:", optionA: "4a", optionB: "2a", optionC: "a", optionD: "8a", correctOption: "A", explanation: "For y² = 4ax the latus rectum has length 4a.", orderIndex: 14 },
  { id: "jee-adv-math-conics-q16", topicId: "jee-adv-math-conics", text: "The eccentricity of a hyperbola is:", optionA: "Greater than 1", optionB: "Equal to 1", optionC: "Less than 1", optionD: "Zero", correctOption: "A", explanation: "A hyperbola always has eccentricity greater than 1.", orderIndex: 15 },

  // ── Mathematics: Complex Numbers & Roots of Unity ──
  { id: "jee-adv-math-complex-numbers-q13", topicId: "jee-adv-math-complex-numbers", text: "The modulus of the complex number 3 + 4i is:", optionA: "5", optionB: "7", optionC: "12", optionD: "1", correctOption: "A", explanation: "|3 + 4i| = √(3² + 4²) = √25 = 5.", orderIndex: 12 },
  { id: "jee-adv-math-complex-numbers-q14", topicId: "jee-adv-math-complex-numbers", text: "The value of i² is:", optionA: "−1", optionB: "1", optionC: "i", optionD: "0", correctOption: "A", explanation: "By definition of the imaginary unit, i² = −1.", orderIndex: 13 },
  { id: "jee-adv-math-complex-numbers-q15", topicId: "jee-adv-math-complex-numbers", text: "The sum of the n nth roots of unity is:", optionA: "0", optionB: "1", optionC: "n", optionD: "−1", correctOption: "A", explanation: "The n nth roots of unity sum to zero for n > 1.", orderIndex: 14 },
  { id: "jee-adv-math-complex-numbers-q16", topicId: "jee-adv-math-complex-numbers", text: "By De Moivre's theorem, (cos θ + i sin θ)ⁿ equals:", optionA: "cos nθ + i sin nθ", optionB: "cos θ + i sin nθ", optionC: "n cos θ", optionD: "cos(θ/n)", correctOption: "A", explanation: "De Moivre's theorem: (cos θ + i sin θ)ⁿ = cos nθ + i sin nθ.", orderIndex: 15 },

  // ── Physics: Centre of Mass, Momentum & Collisions ──
  { id: "jee-adv-phy-com-collisions-q13", topicId: "jee-adv-phy-com-collisions", text: "In a perfectly elastic collision, which quantities are conserved?", optionA: "Both momentum and kinetic energy", optionB: "Only momentum", optionC: "Only kinetic energy", optionD: "Neither", correctOption: "A", explanation: "Elastic collisions conserve both momentum and kinetic energy.", orderIndex: 12 },
  { id: "jee-adv-phy-com-collisions-q14", topicId: "jee-adv-phy-com-collisions", text: "In a perfectly inelastic collision, the colliding bodies:", optionA: "Move together after impact", optionB: "Bounce apart elastically", optionC: "Gain kinetic energy", optionD: "Conserve kinetic energy", correctOption: "A", explanation: "In a perfectly inelastic collision the bodies stick and move with a common velocity.", orderIndex: 13 },
  { id: "jee-adv-phy-com-collisions-q15", topicId: "jee-adv-phy-com-collisions", text: "The coefficient of restitution for a perfectly elastic collision is:", optionA: "1", optionB: "0", optionC: "0.5", optionD: "Infinite", correctOption: "A", explanation: "e = 1 for a perfectly elastic collision; e = 0 for perfectly inelastic.", orderIndex: 14 },
  { id: "jee-adv-phy-com-collisions-q16", topicId: "jee-adv-phy-com-collisions", text: "In the absence of external forces, the velocity of the centre of mass:", optionA: "Remains constant", optionB: "Increases", optionC: "Decreases to zero", optionD: "Reverses", correctOption: "A", explanation: "With no net external force, the centre of mass moves at constant velocity.", orderIndex: 15 },

  // ── Physics: Gauss's Law & Electrostatic Potential ──
  { id: "jee-adv-phy-gauss-law-q13", topicId: "jee-adv-phy-gauss-law", text: "Gauss's law states that the electric flux through a closed surface equals the enclosed charge divided by:", optionA: "ε₀", optionB: "μ₀", optionC: "4π", optionD: "c", correctOption: "A", explanation: "Φ = q_enclosed/ε₀ by Gauss's law.", orderIndex: 12 },
  { id: "jee-adv-phy-gauss-law-q14", topicId: "jee-adv-phy-gauss-law", text: "The electric field due to an infinite charged plane sheet is:", optionA: "σ/2ε₀ and uniform", optionB: "kQ/r²", optionC: "Zero", optionD: "σ/ε₀", correctOption: "A", explanation: "An infinite sheet produces a uniform field of magnitude σ/2ε₀ on each side.", orderIndex: 13 },
  { id: "jee-adv-phy-gauss-law-q15", topicId: "jee-adv-phy-gauss-law", text: "The electric field inside a uniformly charged conducting shell is:", optionA: "Zero", optionB: "kQ/r²", optionC: "kQ/R²", optionD: "Uniform and non-zero", correctOption: "A", explanation: "Inside a conductor's cavity with no enclosed charge, the field is zero.", orderIndex: 14 },
  { id: "jee-adv-phy-gauss-law-q16", topicId: "jee-adv-phy-gauss-law", text: "The relationship between electric field and potential is E =", optionA: "−dV/dr", optionB: "dV/dr", optionC: "V·r", optionD: "V/r²", correctOption: "A", explanation: "The field is the negative gradient of potential, E = −dV/dr.", orderIndex: 15 },

  // ── Physics: SHM & Superposition of Waves ──
  { id: "jee-adv-phy-shm-waves-q13", topicId: "jee-adv-phy-shm-waves", text: "In simple harmonic motion, the acceleration is proportional to and directed:", optionA: "Opposite to the displacement", optionB: "Along the displacement", optionC: "Perpendicular to it", optionD: "Constant", correctOption: "A", explanation: "In SHM, a = −ω²x — restoring, opposite to displacement.", orderIndex: 12 },
  { id: "jee-adv-phy-shm-waves-q14", topicId: "jee-adv-phy-shm-waves", text: "The time period of a simple pendulum of length L is:", optionA: "2π√(L/g)", optionB: "2π√(g/L)", optionC: "2π√(Lg)", optionD: "2πL/g", correctOption: "A", explanation: "T = 2π√(L/g) for small oscillations.", orderIndex: 13 },
  { id: "jee-adv-phy-shm-waves-q15", topicId: "jee-adv-phy-shm-waves", text: "The total mechanical energy of an SHM oscillator is proportional to the square of the:", optionA: "Amplitude", optionB: "Period", optionC: "Phase", optionD: "Mass only", correctOption: "A", explanation: "Energy E = ½mω²A² is proportional to amplitude squared.", orderIndex: 14 },
  { id: "jee-adv-phy-shm-waves-q16", topicId: "jee-adv-phy-shm-waves", text: "Beats are produced by the superposition of two waves of slightly different:", optionA: "Frequencies", optionB: "Amplitudes", optionC: "Phases only", optionD: "Directions", correctOption: "A", explanation: "Beats arise from two waves with slightly different frequencies.", orderIndex: 15 },

  // ── Physics: Transient Circuits & EM Induction ──
  { id: "jee-adv-phy-transient-circuits-q13", topicId: "jee-adv-phy-transient-circuits", text: "The time constant of an RC circuit is:", optionA: "RC", optionB: "R/C", optionC: "C/R", optionD: "1/RC", correctOption: "A", explanation: "The charging/discharging time constant is τ = RC.", orderIndex: 12 },
  { id: "jee-adv-phy-transient-circuits-q14", topicId: "jee-adv-phy-transient-circuits", text: "The time constant of an RL circuit is:", optionA: "L/R", optionB: "R/L", optionC: "LR", optionD: "1/LR", correctOption: "A", explanation: "For an RL circuit the time constant is τ = L/R.", orderIndex: 13 },
  { id: "jee-adv-phy-transient-circuits-q15", topicId: "jee-adv-phy-transient-circuits", text: "After one time constant, a charging capacitor reaches about what fraction of full charge?", optionA: "63%", optionB: "37%", optionC: "50%", optionD: "100%", correctOption: "A", explanation: "Q = Q₀(1 − e⁻¹) ≈ 0.63 Q₀ after one time constant.", orderIndex: 14 },
  { id: "jee-adv-phy-transient-circuits-q16", topicId: "jee-adv-phy-transient-circuits", text: "The energy stored in a charged capacitor is:", optionA: "½CV²", optionB: "CV²", optionC: "½C²V", optionD: "QV²", correctOption: "A", explanation: "Stored energy U = ½CV² = ½QV = Q²/2C.", orderIndex: 15 },

  // ── Chemistry: Stereochemistry & Isomerism ──
  { id: "jee-adv-chem-stereochemistry-q13", topicId: "jee-adv-chem-stereochemistry", text: "A carbon bonded to four different groups is called:", optionA: "A chiral (asymmetric) centre", optionB: "A carbanion", optionC: "A carbocation", optionD: "Achiral", correctOption: "A", explanation: "A carbon with four different substituents is a chiral stereocentre.", orderIndex: 12 },
  { id: "jee-adv-chem-stereochemistry-q14", topicId: "jee-adv-chem-stereochemistry", text: "Enantiomers are stereoisomers that are:", optionA: "Non-superimposable mirror images", optionB: "Identical", optionC: "Structural isomers", optionD: "Superimposable", correctOption: "A", explanation: "Enantiomers are non-superimposable mirror images of each other.", orderIndex: 13 },
  { id: "jee-adv-chem-stereochemistry-q15", topicId: "jee-adv-chem-stereochemistry", text: "A racemic mixture contains equal amounts of two enantiomers and is:", optionA: "Optically inactive", optionB: "Strongly dextrorotatory", optionC: "Strongly levorotatory", optionD: "A single compound", correctOption: "A", explanation: "Equal enantiomers cancel each other's rotation, so the mixture is optically inactive.", orderIndex: 14 },
  { id: "jee-adv-chem-stereochemistry-q16", topicId: "jee-adv-chem-stereochemistry", text: "The maximum number of stereoisomers for a molecule with n stereocentres is:", optionA: "2ⁿ", optionB: "n²", optionC: "2n", optionD: "n!", correctOption: "A", explanation: "A molecule with n chiral centres has at most 2ⁿ stereoisomers.", orderIndex: 15 },

  // ── Chemistry: Chemical Kinetics & Mechanisms ──
  { id: "jee-adv-chem-kinetics-q13", topicId: "jee-adv-chem-kinetics", text: "For a first-order reaction, the half-life is:", optionA: "Independent of initial concentration", optionB: "Proportional to concentration", optionC: "Inversely proportional to concentration", optionD: "Zero", correctOption: "A", explanation: "A first-order half-life t½ = 0.693/k is independent of the initial concentration.", orderIndex: 12 },
  { id: "jee-adv-chem-kinetics-q14", topicId: "jee-adv-chem-kinetics", text: "The Arrhenius equation relates the rate constant to:", optionA: "Temperature and activation energy", optionB: "Pressure only", optionC: "Volume", optionD: "Concentration only", correctOption: "A", explanation: "k = A·e^(−Ea/RT) links k to temperature and activation energy.", orderIndex: 13 },
  { id: "jee-adv-chem-kinetics-q15", topicId: "jee-adv-chem-kinetics", text: "A catalyst increases the reaction rate by:", optionA: "Lowering the activation energy", optionB: "Raising the activation energy", optionC: "Changing ΔH", optionD: "Shifting the equilibrium", correctOption: "A", explanation: "A catalyst provides an alternative pathway with lower activation energy.", orderIndex: 14 },
  { id: "jee-adv-chem-kinetics-q16", topicId: "jee-adv-chem-kinetics", text: "The order of a reaction is determined by:", optionA: "The rate law (experimentally)", optionB: "The balanced equation always", optionC: "The molar mass", optionD: "The temperature", correctOption: "A", explanation: "Reaction order comes from the experimentally determined rate law, not stoichiometry.", orderIndex: 15 },

  // ── Chemistry: Atomic Structure & Quantum Numbers ──
  { id: "jee-adv-chem-atomic-structure-q13", topicId: "jee-adv-chem-atomic-structure", text: "The maximum number of electrons in a shell with principal quantum number n is:", optionA: "2n²", optionB: "n²", optionC: "2n", optionD: "n", correctOption: "A", explanation: "A shell holds a maximum of 2n² electrons.", orderIndex: 12 },
  { id: "jee-adv-chem-atomic-structure-q14", topicId: "jee-adv-chem-atomic-structure", text: "The Pauli exclusion principle states that no two electrons can have the same:", optionA: "Set of four quantum numbers", optionB: "Energy ever", optionC: "Spin ever", optionD: "Orbital shape", correctOption: "A", explanation: "No two electrons in an atom share all four quantum numbers.", orderIndex: 13 },
  { id: "jee-adv-chem-atomic-structure-q15", topicId: "jee-adv-chem-atomic-structure", text: "Hund's rule states that electrons fill degenerate orbitals:", optionA: "Singly first, with parallel spins", optionB: "In pairs first", optionC: "Randomly", optionD: "Only after pairing", correctOption: "A", explanation: "Degenerate orbitals are singly occupied with parallel spins before pairing.", orderIndex: 14 },
  { id: "jee-adv-chem-atomic-structure-q16", topicId: "jee-adv-chem-atomic-structure", text: "The azimuthal quantum number l determines the orbital's:", optionA: "Shape", optionB: "Size only", optionC: "Orientation only", optionD: "Spin", correctOption: "A", explanation: "The azimuthal (angular momentum) quantum number l defines orbital shape.", orderIndex: 15 },

  // ── Chemistry: Ionic Equilibrium: Buffers & Solubility ──
  { id: "jee-adv-chem-ionic-equilibrium-q13", topicId: "jee-adv-chem-ionic-equilibrium", text: "The pH of a neutral aqueous solution at 25°C is:", optionA: "7", optionB: "0", optionC: "14", optionD: "1", correctOption: "A", explanation: "At 25°C neutral water has [H⁺] = 10⁻⁷ M, so pH = 7.", orderIndex: 12 },
  { id: "jee-adv-chem-ionic-equilibrium-q14", topicId: "jee-adv-chem-ionic-equilibrium", text: "The Henderson–Hasselbalch equation relates pH to pKa and the ratio of:", optionA: "Conjugate base to acid", optionB: "Acid to water", optionC: "Salt to solvent", optionD: "Cation to anion", correctOption: "A", explanation: "pH = pKa + log([A⁻]/[HA]).", orderIndex: 13 },
  { id: "jee-adv-chem-ionic-equilibrium-q15", topicId: "jee-adv-chem-ionic-equilibrium", text: "A buffer solution resists changes in pH when small amounts of ____ are added.", optionA: "Acid or base", optionB: "Water only", optionC: "Salt only", optionD: "Nothing", correctOption: "A", explanation: "Buffers resist pH change on adding small amounts of acid or base.", orderIndex: 14 },
  { id: "jee-adv-chem-ionic-equilibrium-q16", topicId: "jee-adv-chem-ionic-equilibrium", text: "The solubility product Ksp applies to:", optionA: "Sparingly soluble salts", optionB: "Highly soluble salts", optionC: "Gases only", optionD: "Pure water", correctOption: "A", explanation: "Ksp describes the equilibrium of a sparingly soluble ionic salt with its ions.", orderIndex: 15 },

  // ── Mathematics: Limits, Continuity & Differentiability ──
  { id: "jee-adv-math-limits-continuity-q13", topicId: "jee-adv-math-limits-continuity", text: "The limit of (sin x)/x as x → 0 is:", optionA: "1", optionB: "0", optionC: "∞", optionD: "Undefined", correctOption: "A", explanation: "The standard limit lim_{x→0} (sin x)/x = 1.", orderIndex: 12 },
  { id: "jee-adv-math-limits-continuity-q14", topicId: "jee-adv-math-limits-continuity", text: "A function is continuous at x = a if the limit equals:", optionA: "f(a)", optionB: "0", optionC: "f'(a)", optionD: "Infinity", correctOption: "A", explanation: "Continuity requires lim_{x→a} f(x) = f(a).", orderIndex: 13 },
  { id: "jee-adv-math-limits-continuity-q15", topicId: "jee-adv-math-limits-continuity", text: "Differentiability of a function at a point implies:", optionA: "Continuity at that point", optionB: "Discontinuity", optionC: "A vertical tangent", optionD: "Nothing", correctOption: "A", explanation: "If a function is differentiable at a point, it is continuous there.", orderIndex: 14 },
  { id: "jee-adv-math-limits-continuity-q16", topicId: "jee-adv-math-limits-continuity", text: "L'Hôpital's rule applies to limits of the indeterminate form:", optionA: "0/0 or ∞/∞", optionB: "1 + 1", optionC: "2/3", optionD: "A finite number", correctOption: "A", explanation: "L'Hôpital's rule handles 0/0 and ∞/∞ indeterminate forms.", orderIndex: 15 },

  // ── Mathematics: Differential Equations ──
  { id: "jee-adv-math-differential-equations-q13", topicId: "jee-adv-math-differential-equations", text: "The order of a differential equation is the order of its:", optionA: "Highest derivative", optionB: "Lowest derivative", optionC: "Constant term", optionD: "Degree only", correctOption: "A", explanation: "The order is the highest derivative appearing in the equation.", orderIndex: 12 },
  { id: "jee-adv-math-differential-equations-q14", topicId: "jee-adv-math-differential-equations", text: "The equation dy/dx = ky has the general solution:", optionA: "y = Ce^(kx)", optionB: "y = kx + C", optionC: "y = C/x", optionD: "y = ln(kx)", correctOption: "A", explanation: "Separating variables gives the exponential solution y = Ce^(kx).", orderIndex: 13 },
  { id: "jee-adv-math-differential-equations-q15", topicId: "jee-adv-math-differential-equations", text: "A first-order linear ODE dy/dx + Py = Q is solved using an:", optionA: "Integrating factor", optionB: "Partial fraction", optionC: "Binomial expansion", optionD: "Substitution only", correctOption: "A", explanation: "The integrating factor e^(∫P dx) solves a first-order linear ODE.", orderIndex: 14 },
  { id: "jee-adv-math-differential-equations-q16", topicId: "jee-adv-math-differential-equations", text: "A differential equation is separable if it can be written as:", optionA: "f(y)dy = g(x)dx", optionB: "y = mx + c", optionC: "ax² + bx + c = 0", optionD: "A matrix equation", correctOption: "A", explanation: "Separable equations put y-terms on one side and x-terms on the other.", orderIndex: 15 },

  // ── Mathematics: Vectors & 3D Geometry ──
  { id: "jee-adv-math-vectors-3d-q13", topicId: "jee-adv-math-vectors-3d", text: "The dot product of two perpendicular vectors is:", optionA: "0", optionB: "1", optionC: "Their magnitudes' product", optionD: "Undefined", correctOption: "A", explanation: "Perpendicular vectors have a dot product of zero (cos 90° = 0).", orderIndex: 12 },
  { id: "jee-adv-math-vectors-3d-q14", topicId: "jee-adv-math-vectors-3d", text: "The cross product of two parallel vectors is:", optionA: "The zero vector", optionB: "A unit vector", optionC: "Their dot product", optionD: "Undefined", correctOption: "A", explanation: "Parallel vectors have sin 0° = 0, so their cross product is the zero vector.", orderIndex: 13 },
  { id: "jee-adv-math-vectors-3d-q15", topicId: "jee-adv-math-vectors-3d", text: "The magnitude of a × b equals |a||b| times:", optionA: "sin θ", optionB: "cos θ", optionC: "tan θ", optionD: "1", correctOption: "A", explanation: "|a × b| = |a||b| sin θ, where θ is the angle between them.", orderIndex: 14 },
  { id: "jee-adv-math-vectors-3d-q16", topicId: "jee-adv-math-vectors-3d", text: "The scalar triple product a·(b × c) gives the volume of a:", optionA: "Parallelepiped", optionB: "Sphere", optionC: "Cone", optionD: "Cylinder", correctOption: "A", explanation: "The scalar triple product equals the volume of the parallelepiped formed by the vectors.", orderIndex: 15 },

  // ── Mathematics: Application of Derivatives ──
  { id: "jee-adv-math-application-derivatives-q13", topicId: "jee-adv-math-application-derivatives", text: "At a local maximum of a smooth function, the first derivative is:", optionA: "Zero (with f'' < 0)", optionB: "Positive", optionC: "Undefined always", optionD: "Equal to f", correctOption: "A", explanation: "At a smooth local maximum f' = 0 and f'' < 0.", orderIndex: 12 },
  { id: "jee-adv-math-application-derivatives-q14", topicId: "jee-adv-math-application-derivatives", text: "A function is increasing on an interval where its derivative is:", optionA: "Positive", optionB: "Negative", optionC: "Zero", optionD: "Undefined", correctOption: "A", explanation: "A positive derivative means the function is increasing there.", orderIndex: 13 },
  { id: "jee-adv-math-application-derivatives-q15", topicId: "jee-adv-math-application-derivatives", text: "The point where the concavity of a curve changes is called a:", optionA: "Point of inflection", optionB: "Maximum", optionC: "Minimum", optionD: "Root", correctOption: "A", explanation: "A point of inflection is where the second derivative changes sign (concavity changes).", orderIndex: 14 },
  { id: "jee-adv-math-application-derivatives-q16", topicId: "jee-adv-math-application-derivatives", text: "If dy/dx = 3 at a point and dx/dt = 2, then dy/dt equals:", optionA: "6", optionB: "1.5", optionC: "5", optionD: "3", correctOption: "A", explanation: "By the chain rule dy/dt = (dy/dx)(dx/dt) = 3 × 2 = 6.", orderIndex: 15 }
];
