// JEE Main depth expansion (pass 3) — question density top-up. Raises the
// twelve highest-weightage JEE Main topics from 12 to 16 questions each
// (q13–q16, orderIndex 12–15), adding harder, exam-representative items on the
// core scoring areas of each subject. No new topics or study notes.
import type { Question } from "@jyotir/core";

export const mainDepthQuestions: Question[] = [
  // ── Physics: Electrostatics ──
  { id: "jee-physics-electrostatics-q13", topicId: "jee-physics-electrostatics", text: "The electric field just outside a charged conductor of surface charge density σ is:", optionA: "σ/ε₀", optionB: "σ/2ε₀", optionC: "2σ/ε₀", optionD: "σε₀", correctOption: "A", explanation: "Just outside a conductor the field is σ/ε₀, directed normal to the surface.", orderIndex: 12 },
  { id: "jee-physics-electrostatics-q14", topicId: "jee-physics-electrostatics", text: "The potential energy of a dipole of moment p in a field E, at angle θ, is:", optionA: "−pE·cos θ", optionB: "pE·sin θ", optionC: "pE·cos θ", optionD: "−pE·sin θ", correctOption: "A", explanation: "U = −p·E = −pE cos θ, minimum when the dipole aligns with the field.", orderIndex: 13 },
  { id: "jee-physics-electrostatics-q15", topicId: "jee-physics-electrostatics", text: "Inside a hollow charged conducting sphere, the electric field is:", optionA: "Zero", optionB: "kQ/r²", optionC: "kQ/R²", optionD: "Uniform and non-zero", correctOption: "A", explanation: "By Gauss's law the field inside a hollow conductor's cavity is zero.", orderIndex: 14 },
  { id: "jee-physics-electrostatics-q16", topicId: "jee-physics-electrostatics", text: "The work done in moving a charge along an equipotential surface is:", optionA: "Zero", optionB: "qV", optionC: "qE·d", optionD: "Maximum", correctOption: "A", explanation: "No work is done moving a charge on an equipotential (ΔV = 0).", orderIndex: 15 },

  // ── Physics: Current Electricity ──
  { id: "jee-physics-current-electricity-q13", topicId: "jee-physics-current-electricity", text: "In the Wheatstone bridge balance condition, P/Q equals:", optionA: "R/S", optionB: "S/R", optionC: "PQ", optionD: "R·S", correctOption: "A", explanation: "The bridge is balanced when P/Q = R/S and no current flows through the galvanometer.", orderIndex: 12 },
  { id: "jee-physics-current-electricity-q14", topicId: "jee-physics-current-electricity", text: "The drift velocity of electrons is related to current I by I =", optionA: "n e A v_d", optionB: "n e v_d / A", optionC: "e A v_d", optionD: "n A v_d", correctOption: "A", explanation: "I = n·e·A·v_d, where n is number density and v_d the drift velocity.", orderIndex: 13 },
  { id: "jee-physics-current-electricity-q15", topicId: "jee-physics-current-electricity", text: "Maximum power is transferred from a cell of internal resistance r to a load R when:", optionA: "R = r", optionB: "R = 2r", optionC: "R = 0", optionD: "R → ∞", correctOption: "A", explanation: "Maximum power transfer occurs when the load equals the internal resistance.", orderIndex: 14 },
  { id: "jee-physics-current-electricity-q16", topicId: "jee-physics-current-electricity", text: "The temperature coefficient of resistance for a metal is:", optionA: "Positive", optionB: "Negative", optionC: "Zero", optionD: "Always one", correctOption: "A", explanation: "Metals have positive temperature coefficients — resistance rises with temperature.", orderIndex: 15 },

  // ── Physics: Modern Physics ──
  { id: "jee-physics-modern-physics-q13", topicId: "jee-physics-modern-physics", text: "The de Broglie wavelength of a particle of momentum p is:", optionA: "h/p", optionB: "p/h", optionC: "hp", optionD: "h/p²", correctOption: "A", explanation: "λ = h/p, the de Broglie relation for matter waves.", orderIndex: 12 },
  { id: "jee-physics-modern-physics-q14", topicId: "jee-physics-modern-physics", text: "In the photoelectric effect, the stopping potential depends on the light's:", optionA: "Frequency", optionB: "Intensity", optionC: "Polarisation", optionD: "Phase", correctOption: "A", explanation: "Stopping potential depends on frequency, not intensity (Einstein's relation).", orderIndex: 13 },
  { id: "jee-physics-modern-physics-q15", topicId: "jee-physics-modern-physics", text: "The radius of the nth Bohr orbit is proportional to:", optionA: "n²", optionB: "1/n²", optionC: "n", optionD: "1/n", correctOption: "A", explanation: "The Bohr radius rₙ ∝ n², so orbits grow with n².", orderIndex: 14 },
  { id: "jee-physics-modern-physics-q16", topicId: "jee-physics-modern-physics", text: "The work function of a metal is the minimum energy to:", optionA: "Eject an electron from the surface", optionB: "Ionise the nucleus", optionC: "Melt the metal", optionD: "Excite an electron to n=2", correctOption: "A", explanation: "The work function is the least energy needed to free a surface electron.", orderIndex: 15 },

  // ── Physics: Rotational Motion ──
  { id: "jee-physics-rotational-motion-q13", topicId: "jee-physics-rotational-motion", text: "The moment of inertia of a solid sphere about a diameter is:", optionA: "(2/5)MR²", optionB: "(2/3)MR²", optionC: "MR²", optionD: "½MR²", correctOption: "A", explanation: "A solid sphere has I = (2/5)MR² about a diameter.", orderIndex: 12 },
  { id: "jee-physics-rotational-motion-q14", topicId: "jee-physics-rotational-motion", text: "Angular momentum is conserved when the net external:", optionA: "Torque is zero", optionB: "Force is zero", optionC: "Power is zero", optionD: "Energy is zero", correctOption: "A", explanation: "Zero net external torque conserves angular momentum.", orderIndex: 13 },
  { id: "jee-physics-rotational-motion-q15", topicId: "jee-physics-rotational-motion", text: "For a body rolling without slipping, the velocity of the point of contact is:", optionA: "Zero", optionB: "v", optionC: "2v", optionD: "ωR/2", correctOption: "A", explanation: "In rolling without slipping the contact point is instantaneously at rest.", orderIndex: 14 },
  { id: "jee-physics-rotational-motion-q16", topicId: "jee-physics-rotational-motion", text: "The parallel-axis theorem states I =", optionA: "I_cm + Md²", optionB: "I_cm − Md²", optionC: "I_cm/d²", optionD: "Md² − I_cm", correctOption: "A", explanation: "I = I_cm + Md², shifting the axis a distance d from the centre of mass.", orderIndex: 15 },

  // ── Chemistry: Chemical Bonding ──
  { id: "jee-chemistry-chemical-bonding-q14", topicId: "jee-chemistry-chemical-bonding", text: "According to VSEPR, water is bent because oxygen has:", optionA: "Two lone pairs", optionB: "No lone pairs", optionC: "Four bond pairs", optionD: "sp hybridisation", correctOption: "A", explanation: "Two lone pairs on sp³ oxygen compress the H–O–H angle to a bent shape.", orderIndex: 13 },
  { id: "jee-chemistry-chemical-bonding-q15", topicId: "jee-chemistry-chemical-bonding", text: "The bond order of the O₂ molecule from molecular orbital theory is:", optionA: "2", optionB: "1", optionC: "3", optionD: "0", correctOption: "A", explanation: "O₂ has bond order (8−4)/2 = 2 and is paramagnetic.", orderIndex: 14 },
  { id: "jee-chemistry-chemical-bonding-q16", topicId: "jee-chemistry-chemical-bonding", text: "Hydrogen bonding is strongest when hydrogen is bonded to:", optionA: "F, O or N", optionB: "C or S", optionC: "Cl or Br", optionD: "P or Si", correctOption: "A", explanation: "The small, highly electronegative F, O and N form the strongest H-bonds.", orderIndex: 15 },

  // ── Chemistry: Mole Concept & Stoichiometry ──
  { id: "jee-chemistry-mole-concept-q13", topicId: "jee-chemistry-mole-concept", text: "The number of molecules in 1 mole of any substance is:", optionA: "6.022 × 10²³", optionB: "3.011 × 10²³", optionC: "1.204 × 10²⁴", optionD: "6.022 × 10²²", correctOption: "A", explanation: "Avogadro's number is 6.022 × 10²³ per mole.", orderIndex: 12 },
  { id: "jee-chemistry-mole-concept-q14", topicId: "jee-chemistry-mole-concept", text: "The volume occupied by 1 mole of an ideal gas at STP is:", optionA: "22.4 L", optionB: "11.2 L", optionC: "24.4 L", optionD: "1 L", correctOption: "A", explanation: "One mole of an ideal gas occupies 22.4 L at STP.", orderIndex: 13 },
  { id: "jee-chemistry-mole-concept-q15", topicId: "jee-chemistry-mole-concept", text: "The reactant that is consumed first and limits product formation is called the:", optionA: "Limiting reagent", optionB: "Excess reagent", optionC: "Catalyst", optionD: "Spectator", correctOption: "A", explanation: "The limiting reagent runs out first and determines the maximum yield.", orderIndex: 14 },
  { id: "jee-chemistry-mole-concept-q16", topicId: "jee-chemistry-mole-concept", text: "The number of moles in 36 g of water (molar mass 18 g/mol) is:", optionA: "2", optionB: "1", optionC: "0.5", optionD: "4", correctOption: "A", explanation: "moles = mass/molar mass = 36/18 = 2.", orderIndex: 15 },

  // ── Chemistry: GOC (Basics of Organic Chemistry) ──
  { id: "jee-chemistry-goc-q13", topicId: "jee-chemistry-goc", text: "A carbocation is stabilised most by:", optionA: "+I and hyperconjugation from alkyl groups", optionB: "Electron-withdrawing groups", optionC: "Adjacent halogens", optionD: "A neighbouring nitro group", correctOption: "A", explanation: "Electron-donating alkyl groups stabilise carbocations by +I and hyperconjugation.", orderIndex: 12 },
  { id: "jee-chemistry-goc-q14", topicId: "jee-chemistry-goc", text: "The order of stability of carbocations is:", optionA: "3° > 2° > 1° > methyl", optionB: "Methyl > 1° > 2° > 3°", optionC: "1° > 2° > 3°", optionD: "All equal", correctOption: "A", explanation: "More alkyl substitution stabilises the positive charge: 3° > 2° > 1° > methyl.", orderIndex: 13 },
  { id: "jee-chemistry-goc-q15", topicId: "jee-chemistry-goc", text: "Resonance results in:", optionA: "Delocalisation of electrons over the molecule", optionB: "Breaking of sigma bonds", optionC: "Change of molecular formula", optionD: "Loss of aromaticity", correctOption: "A", explanation: "Resonance delocalises π/lone-pair electrons, lowering the molecule's energy.", orderIndex: 14 },
  { id: "jee-chemistry-goc-q16", topicId: "jee-chemistry-goc", text: "The inductive effect operates through:", optionA: "Sigma bonds", optionB: "Pi bonds only", optionC: "Space (through no bonds)", optionD: "Hydrogen bonds", correctOption: "A", explanation: "The inductive effect is transmitted through the sigma-bond framework.", orderIndex: 15 },

  // ── Chemistry: Coordination Compounds ──
  { id: "jee-chemistry-coordination-compounds-q13", topicId: "jee-chemistry-coordination-compounds", text: "The oxidation state of iron in [Fe(CN)₆]³⁻ is:", optionA: "+3", optionB: "+2", optionC: "+6", optionD: "0", correctOption: "A", explanation: "With six CN⁻ (−1 each) and overall −3, iron is +3.", orderIndex: 12 },
  { id: "jee-chemistry-coordination-compounds-q14", topicId: "jee-chemistry-coordination-compounds", text: "According to crystal field theory, a strong-field ligand causes:", optionA: "Large splitting and low-spin complexes", optionB: "Small splitting", optionC: "No splitting", optionD: "Always high spin", correctOption: "A", explanation: "Strong-field ligands give large Δ, favouring electron pairing (low spin).", orderIndex: 13 },
  { id: "jee-chemistry-coordination-compounds-q15", topicId: "jee-chemistry-coordination-compounds", text: "The coordination number of the central metal in [Co(NH₃)₆]³⁺ is:", optionA: "6", optionB: "3", optionC: "4", optionD: "2", correctOption: "A", explanation: "Six NH₃ ligands give a coordination number of 6.", orderIndex: 14 },
  { id: "jee-chemistry-coordination-compounds-q16", topicId: "jee-chemistry-coordination-compounds", text: "EDTA is classified as which type of ligand?", optionA: "Hexadentate", optionB: "Monodentate", optionC: "Bidentate", optionD: "Ambidentate", correctOption: "A", explanation: "EDTA binds through six donor sites, making it hexadentate.", orderIndex: 15 },

  // ── Mathematics: Application of Derivatives ──
  { id: "jee-mathematics-application-of-derivatives-q13", topicId: "jee-mathematics-application-of-derivatives", text: "At a point of local maximum of f, the first derivative f′ is:", optionA: "Zero (with f″ < 0)", optionB: "Positive", optionC: "Undefined always", optionD: "Equal to f", correctOption: "A", explanation: "At a smooth local maximum f′ = 0 and f″ < 0.", orderIndex: 12 },
  { id: "jee-mathematics-application-of-derivatives-q14", topicId: "jee-mathematics-application-of-derivatives", text: "The slope of the tangent to y = f(x) at a point equals:", optionA: "f′ at that point", optionB: "f at that point", optionC: "The integral of f", optionD: "1/f′", correctOption: "A", explanation: "The tangent's slope is the derivative f′ at the point.", orderIndex: 13 },
  { id: "jee-mathematics-application-of-derivatives-q15", topicId: "jee-mathematics-application-of-derivatives", text: "A function is increasing on an interval where:", optionA: "f′(x) > 0", optionB: "f′(x) < 0", optionC: "f″(x) = 0", optionD: "f(x) > 0", correctOption: "A", explanation: "A positive derivative means the function increases there.", orderIndex: 14 },
  { id: "jee-mathematics-application-of-derivatives-q16", topicId: "jee-mathematics-application-of-derivatives", text: "If dy/dx = 3 at a point and dx/dt = 2, then dy/dt equals:", optionA: "6", optionB: "1.5", optionC: "5", optionD: "3", correctOption: "A", explanation: "By the chain rule dy/dt = (dy/dx)(dx/dt) = 3 × 2 = 6.", orderIndex: 15 },

  // ── Mathematics: Integration ──
  { id: "jee-mathematics-integration-q13", topicId: "jee-mathematics-integration", text: "∫ 1/x dx equals:", optionA: "ln|x| + C", optionB: "x²/2 + C", optionC: "−1/x² + C", optionD: "1/x + C", correctOption: "A", explanation: "The integral of 1/x is the natural logarithm ln|x| + C.", orderIndex: 12 },
  { id: "jee-mathematics-integration-q14", topicId: "jee-mathematics-integration", text: "∫₀^(π/2) sin x dx equals:", optionA: "1", optionB: "0", optionC: "π/2", optionD: "2", correctOption: "A", explanation: "[−cos x]₀^(π/2) = −0 − (−1) = 1.", orderIndex: 13 },
  { id: "jee-mathematics-integration-q15", topicId: "jee-mathematics-integration", text: "The method of integration by parts is based on the formula ∫u dv =", optionA: "uv − ∫v du", optionB: "uv + ∫v du", optionC: "∫v du − uv", optionD: "u/v − ∫v du", correctOption: "A", explanation: "Integration by parts: ∫u dv = uv − ∫v du.", orderIndex: 14 },
  { id: "jee-mathematics-integration-q16", topicId: "jee-mathematics-integration", text: "∫ eˣ dx equals:", optionA: "eˣ + C", optionB: "x eˣ + C", optionC: "eˣ/x + C", optionD: "ln x + C", correctOption: "A", explanation: "The exponential function is its own integral: ∫eˣ dx = eˣ + C.", orderIndex: 15 },

  // ── Mathematics: Conic Sections ──
  { id: "jee-mathematics-conic-sections-q13", topicId: "jee-mathematics-conic-sections", text: "The eccentricity of a parabola is:", optionA: "1", optionB: "0", optionC: "Between 0 and 1", optionD: "Greater than 1", correctOption: "A", explanation: "A parabola has eccentricity exactly 1.", orderIndex: 12 },
  { id: "jee-mathematics-conic-sections-q14", topicId: "jee-mathematics-conic-sections", text: "For the ellipse x²/a² + y²/b² = 1 (a > b), the eccentricity is:", optionA: "√(1 − b²/a²)", optionB: "√(1 + b²/a²)", optionC: "b/a", optionD: "a/b", correctOption: "A", explanation: "e = √(1 − b²/a²) for an ellipse with a > b.", orderIndex: 13 },
  { id: "jee-mathematics-conic-sections-q15", topicId: "jee-mathematics-conic-sections", text: "The length of the latus rectum of the parabola y² = 4ax is:", optionA: "4a", optionB: "2a", optionC: "a", optionD: "8a", correctOption: "A", explanation: "For y² = 4ax the latus rectum has length 4a.", orderIndex: 14 },
  { id: "jee-mathematics-conic-sections-q16", topicId: "jee-mathematics-conic-sections", text: "The eccentricity of a hyperbola is:", optionA: "Greater than 1", optionB: "Equal to 1", optionC: "Less than 1", optionD: "Zero", correctOption: "A", explanation: "A hyperbola always has eccentricity greater than 1.", orderIndex: 15 },

  // ── Mathematics: Matrices & Determinants ──
  { id: "jee-mathematics-matrices-determinants-q13", topicId: "jee-mathematics-matrices-determinants", text: "A square matrix A is invertible if and only if its determinant is:", optionA: "Non-zero", optionB: "Zero", optionC: "Positive", optionD: "An integer", correctOption: "A", explanation: "A matrix is invertible exactly when det(A) ≠ 0.", orderIndex: 12 },
  { id: "jee-mathematics-matrices-determinants-q14", topicId: "jee-mathematics-matrices-determinants", text: "For square matrices, det(AB) equals:", optionA: "det(A)·det(B)", optionB: "det(A) + det(B)", optionC: "det(A)/det(B)", optionD: "det(A) − det(B)", correctOption: "A", explanation: "The determinant is multiplicative: det(AB) = det(A)·det(B).", orderIndex: 13 },
  { id: "jee-mathematics-matrices-determinants-q15", topicId: "jee-mathematics-matrices-determinants", text: "The inverse of a matrix A is given by:", optionA: "adj(A)/det(A)", optionB: "det(A)·adj(A)", optionC: "Aᵀ", optionD: "adj(A)·det(A)", correctOption: "A", explanation: "A⁻¹ = adj(A)/det(A), valid when det(A) ≠ 0.", orderIndex: 14 },
  { id: "jee-mathematics-matrices-determinants-q16", topicId: "jee-mathematics-matrices-determinants", text: "If every element of one row of a determinant is multiplied by k, the determinant is:", optionA: "Multiplied by k", optionB: "Unchanged", optionC: "Multiplied by k²", optionD: "Set to zero", correctOption: "A", explanation: "Scaling one row by k scales the determinant by k.", orderIndex: 15 }
];
