import { defineBundle } from "./builder";
import { advTopics, advMaterials, advQuestions } from "./jee-adv-exp";
import { adv2Topics, adv2Materials, adv2Questions } from "./jee-adv-exp2";

// JEE Advanced — the IIT-level track. Shares the Main syllabus but tests it
// with tougher, multi-concept questions on the highest-yield chapters. Its own
// id namespace (jee-adv-*) so it coexists with JEE Main as a separate level.
export const jeeAdvanced = defineBundle({
  exam: {
    id: "jee-adv",
    slug: "jee-adv",
    name: "JEE Advanced",
    tagline: "Deeper Physics · Chemistry · Maths for the IIT cutoff",
    orderIndex: 2,
    family: "jee",
    familyName: "JEE",
    familyTagline: "Joint Entrance Exam — pick your level",
    levelLabel: "Advanced"
  },
  subjects: [
    { id: "jee-adv-physics", examId: "jee-adv", name: "Physics", slug: "physics", orderIndex: 0 },
    { id: "jee-adv-chemistry", examId: "jee-adv", name: "Chemistry", slug: "chemistry", orderIndex: 1 },
    { id: "jee-adv-mathematics", examId: "jee-adv", name: "Mathematics", slug: "mathematics", orderIndex: 2 }
  ],
  topics: [
    // Physics
    { id: "jee-adv-phy-rotational-dynamics", subjectId: "jee-adv-physics", name: "Rotational Dynamics & Rigid Bodies", slug: "rotational-dynamics", orderIndex: 0 },
    { id: "jee-adv-phy-shm-waves", subjectId: "jee-adv-physics", name: "SHM & Superposition of Waves", slug: "shm-waves", orderIndex: 1 },
    { id: "jee-adv-phy-gauss-law", subjectId: "jee-adv-physics", name: "Gauss's Law & Electrostatic Potential", slug: "gauss-law", orderIndex: 2 },
    { id: "jee-adv-phy-transient-circuits", subjectId: "jee-adv-physics", name: "Transient Circuits & Electromagnetic Induction", slug: "transient-circuits", orderIndex: 3 },
    { id: "jee-adv-phy-wave-optics", subjectId: "jee-adv-physics", name: "Wave Optics: Interference & Diffraction", slug: "wave-optics", orderIndex: 4 },
    { id: "jee-adv-phy-thermodynamics", subjectId: "jee-adv-physics", name: "Thermodynamics & Kinetic Theory", slug: "thermodynamics", orderIndex: 5 },
    { id: "jee-adv-phy-modern-physics", subjectId: "jee-adv-physics", name: "Modern Physics: Photoelectric & Atomic", slug: "modern-physics", orderIndex: 6 },
    { id: "jee-adv-phy-com-collisions", subjectId: "jee-adv-physics", name: "Centre of Mass, Momentum & Collisions", slug: "com-collisions", orderIndex: 7 },
    // Chemistry
    { id: "jee-adv-chem-mot", subjectId: "jee-adv-chemistry", name: "Chemical Bonding & Molecular Orbital Theory", slug: "mot", orderIndex: 0 },
    { id: "jee-adv-chem-thermo-equilibrium", subjectId: "jee-adv-chemistry", name: "Chemical Thermodynamics & Equilibrium", slug: "thermo-equilibrium", orderIndex: 1 },
    { id: "jee-adv-chem-electrochemistry", subjectId: "jee-adv-chemistry", name: "Electrochemistry & the Nernst Equation", slug: "electrochemistry", orderIndex: 2 },
    { id: "jee-adv-chem-kinetics", subjectId: "jee-adv-chemistry", name: "Chemical Kinetics & Mechanisms", slug: "kinetics", orderIndex: 3 },
    { id: "jee-adv-chem-coordination", subjectId: "jee-adv-chemistry", name: "Coordination Compounds & Crystal Field Theory", slug: "coordination", orderIndex: 4 },
    { id: "jee-adv-chem-organic-mechanisms", subjectId: "jee-adv-chemistry", name: "Organic Reaction Mechanisms", slug: "organic-mechanisms", orderIndex: 5 },
    { id: "jee-adv-chem-stereochemistry", subjectId: "jee-adv-chemistry", name: "Stereochemistry & Isomerism", slug: "stereochemistry", orderIndex: 6 },
    { id: "jee-adv-chem-ionic-equilibrium", subjectId: "jee-adv-chemistry", name: "Ionic Equilibrium: Buffers & Solubility", slug: "ionic-equilibrium", orderIndex: 7 },
    // Mathematics
    { id: "jee-adv-math-limits-continuity", subjectId: "jee-adv-mathematics", name: "Limits, Continuity & Differentiability", slug: "limits-continuity", orderIndex: 0 },
    { id: "jee-adv-math-definite-integrals", subjectId: "jee-adv-mathematics", name: "Definite Integrals & Applications", slug: "definite-integrals", orderIndex: 1 },
    { id: "jee-adv-math-differential-equations", subjectId: "jee-adv-mathematics", name: "Differential Equations", slug: "differential-equations", orderIndex: 2 },
    { id: "jee-adv-math-conics", subjectId: "jee-adv-mathematics", name: "Conic Sections & Coordinate Geometry", slug: "conics", orderIndex: 3 },
    { id: "jee-adv-math-complex-numbers", subjectId: "jee-adv-mathematics", name: "Complex Numbers & Roots of Unity", slug: "complex-numbers", orderIndex: 4 },
    { id: "jee-adv-math-probability", subjectId: "jee-adv-mathematics", name: "Probability & Bayes' Theorem", slug: "probability", orderIndex: 5 },
    { id: "jee-adv-math-vectors-3d", subjectId: "jee-adv-mathematics", name: "Vectors & 3D Geometry", slug: "vectors-3d", orderIndex: 6 },
    { id: "jee-adv-math-binomial-series", subjectId: "jee-adv-mathematics", name: "Binomial Theorem, Sequences & Series", slug: "binomial-series", orderIndex: 7 },
    ...advTopics,
    ...adv2Topics
  ],
  materials: [
    { id: "jee-adv-phy-rotational-dynamics-m01", topicId: "jee-adv-phy-rotational-dynamics", title: "Rotational Dynamics", content: `**Torque** τ = Iα rotates a rigid body; **moment of inertia** I depends on mass distribution (solid sphere (2/5)MR², solid cylinder/disc ½MR², ring MR²). Use the **parallel-axis theorem** I = I_cm + Md². For **rolling without slipping** v = ωR and friction is static (does no work). In rolling, KE splits as translational + rotational; the rotational fraction is I/(I+MR²). Bodies with smaller I/MR² (e.g., a solid sphere) accelerate fastest down an incline. **Angular momentum** L = Iω is conserved when net external torque is zero — the basis of the spinning-skater effect.`, estimatedReadTime: 2, orderIndex: 0 },
    { id: "jee-adv-phy-shm-waves-m01", topicId: "jee-adv-phy-shm-waves", title: "SHM & Waves", content: `In **SHM**, a = −ω²x, so acceleration is proportional and opposite to displacement; velocity is maximum at the mean position and zero at the extremes. Total energy ∝ (amplitude)² and stays constant, trading between KE and PE. A **transverse wave on a string** travels at v = √(T/μ). For a **closed organ pipe** the fundamental wavelength is 4L (only odd harmonics); an open pipe gives 2L. **Beats** occur at frequency |f₁ − f₂|. Two perpendicular SHMs of equal frequency with a π/2 phase difference trace a circle (Lissajous figure).`, estimatedReadTime: 2, orderIndex: 1 },
    { id: "jee-adv-phy-gauss-law-m01", topicId: "jee-adv-phy-gauss-law", title: "Gauss's Law", content: `**Gauss's law**: Φ = q_enclosed/ε₀. Key fields: infinite **line charge** E ∝ 1/r; infinite **sheet** E = σ/2ε₀ (independent of distance); just outside a **conductor** E = σ/ε₀. Inside a **conductor** (and a hollow charged shell) E = 0 and the potential is constant. Inside a **uniformly charged non-conducting sphere**, E ∝ r (grows linearly to the surface) then falls as 1/r² outside. Choose Gaussian surfaces matching the symmetry (spherical, cylindrical, or pillbox) to evaluate the field quickly.`, estimatedReadTime: 2, orderIndex: 2 },
    { id: "jee-adv-phy-transient-circuits-m01", topicId: "jee-adv-phy-transient-circuits", title: "Transient Circuits & EMI", content: `In an **RC circuit** the charging/discharging time constant is τ = RC; charge reaches (1 − 1/e) of final in one τ. In an **LR circuit** the current grows with time constant L/R. An **inductor** opposes changes in current (open circuit at t = 0, wire at steady state), storing energy ½LI²; a **capacitor** blocks steady DC (open circuit at steady state), storing ½CV². **Faraday's law**: emf = −dΦ/dt; for an inductor emf = −L dI/dt. **Lenz's law** sets the sign: induced current opposes the change in flux that produced it.`, estimatedReadTime: 2, orderIndex: 3 },
    { id: "jee-adv-phy-wave-optics-m01", topicId: "jee-adv-phy-wave-optics", title: "Wave Optics", content: `In **Young's double slit**, fringe width β = λD/d; bright fringes at path difference nλ, dark at (n+½)λ. Immersing the setup in a medium of index μ shrinks λ (and β) by μ. **Coherent sources** (fixed phase relation) are required for a stable pattern. **Single-slit diffraction** has its first minimum at a·sinθ = λ. **Thin films** add an extra λ/2 path from reflection at a denser medium. Combined intensity I = I₁ + I₂ + 2√(I₁I₂)cosφ, maximal when φ = 0. Resolving power rises with aperture size.`, estimatedReadTime: 2, orderIndex: 4 },
    { id: "jee-adv-phy-thermodynamics-m01", topicId: "jee-adv-phy-thermodynamics", title: "Thermodynamics & Kinetic Theory", content: `**First law**: ΔU = Q − W. For an **ideal gas**, U depends only on temperature. Process shortcuts: **isothermal** ΔU = 0; **adiabatic** Q = 0 (PVγ = const); **isochoric** W = 0. Molar heat capacities obey **Cp − Cv = R**, with γ = Cp/Cv = 5/3 (monatomic), 7/5 (diatomic). Kinetic theory gives rms speed v_rms = √(3RT/M) ∝ √T, and equipartition assigns ½kT per degree of freedom. A **Carnot engine** has the maximum efficiency 1 − T_c/T_h between two reservoirs.`, estimatedReadTime: 2, orderIndex: 5 },
    { id: "jee-adv-phy-modern-physics-m01", topicId: "jee-adv-phy-modern-physics", title: "Modern Physics", content: `**Photoelectric effect**: KE_max = hν − φ; the stopping potential depends on frequency, not intensity, and there is a threshold frequency. **de Broglie**: λ = h/p relates matter waves to momentum. **Bohr model**: angular momentum is quantized (mvr = nh/2π) and hydrogen energy levels are Eₙ = −13.6/n² eV. Line spectra arise from transitions between levels. In **nuclei**, binding energy per nucleon peaks near iron, driving fusion (light nuclei) and fission (heavy nuclei). **Radioactive decay** follows N = N₀e^(−λt) with half-life t½ = ln2/λ.`, estimatedReadTime: 2, orderIndex: 6 },
    { id: "jee-adv-phy-com-collisions-m01", topicId: "jee-adv-phy-com-collisions", title: "Momentum & Collisions", content: `The **centre of mass** moves as though all mass were concentrated there under the net external force; with no external force its velocity is constant. **Momentum** is conserved in every collision. In an **elastic** collision KE is also conserved — for equal masses (one at rest) the velocities simply exchange. In a **perfectly inelastic** collision the bodies stick and KE is lost (momentum still conserved). The **coefficient of restitution** e = (relative speed of separation)/(relative speed of approach): e = 1 elastic, e = 0 perfectly inelastic. **Impulse** = ∫F dt = change in momentum.`, estimatedReadTime: 2, orderIndex: 7 },
    { id: "jee-adv-chem-mot-m01", topicId: "jee-adv-chem-mot", title: "Molecular Orbital Theory", content: `**MOT** combines atomic orbitals into bonding and antibonding molecular orbitals. **Bond order** = (N_bonding − N_antibonding)/2 predicts stability: N₂ = 3, O₂ = 2, F₂ = 1; He₂ = 0 (does not exist). MOT succeeds where VBT fails by explaining the **paramagnetism of O₂** (two unpaired electrons in π* orbitals). Adding/removing electrons shifts bond order: O₂⁺ = 2.5, O₂⁻ (superoxide) = 1.5, O₂²⁻ (peroxide) = 1. Bond length falls and bond energy rises as bond order increases. For lighter elements (up to N₂) the σ2p lies above the π2p due to s–p mixing.`, estimatedReadTime: 2, orderIndex: 0 },
    { id: "jee-adv-chem-thermo-equilibrium-m01", topicId: "jee-adv-chem-thermo-equilibrium", title: "Thermodynamics & Equilibrium", content: `Spontaneity is governed by **ΔG = ΔH − TΔS** (spontaneous when ΔG < 0). At equilibrium ΔG = 0 and **ΔG° = −RT ln K**. Relate constants by **Kp = Kc(RT)^Δn**. **Le Chatelier's principle**: raising pressure shifts toward fewer gas moles; for an exothermic reaction raising T lowers K; adding an inert gas at constant volume causes no shift. A **catalyst** speeds both directions equally, changing the rate but not K or the equilibrium position. Entropy rises when gas moles increase or a solid/liquid becomes gas.`, estimatedReadTime: 2, orderIndex: 1 },
    { id: "jee-adv-chem-electrochemistry-m01", topicId: "jee-adv-chem-electrochemistry", title: "Electrochemistry", content: `In a galvanic cell **oxidation occurs at the anode**, reduction at the cathode, and **E°cell = E°cathode − E°anode** (both as reduction potentials). The **standard hydrogen electrode** is the 0 V reference. The **Nernst equation** E = E° − (0.059/n)log Q (at 298 K) gives concentration dependence. A more positive reduction potential means a stronger oxidizing agent. **Faraday's laws**: mass deposited ∝ It, with moles = It/(nF). **Kohlrausch's law** gives limiting molar conductivity as the sum of independent ionic contributions. A spontaneous cell has E°cell > 0 and ΔG° = −nFE°cell < 0.`, estimatedReadTime: 2, orderIndex: 2 },
    { id: "jee-adv-chem-kinetics-m01", topicId: "jee-adv-chem-kinetics", title: "Chemical Kinetics", content: `Rate = k[A]^m[B]^n; the **order** is m + n (found experimentally, not from stoichiometry). **First-order** reactions have a concentration-independent half-life (t½ = 0.693/k) and k in s⁻¹; **zero-order** rate is independent of concentration. The **Arrhenius equation** k = A·e^(−Ea/RT) shows rate rising with temperature as more molecules exceed the activation energy. The **rate-determining step** is the slowest elementary step and fixes the rate law. A **catalyst** provides a lower-Ea pathway, increasing rate without being consumed and without changing ΔG.`, estimatedReadTime: 2, orderIndex: 3 },
    { id: "jee-adv-chem-coordination-m01", topicId: "jee-adv-chem-coordination", title: "Coordination & CFT", content: `**Crystal field theory**: in an octahedral field the d orbitals split into lower **t₂g** and higher **e_g** sets separated by Δ_o. **Strong-field ligands** (large Δ_o: CO, CN⁻) give **low-spin**, diamagnetic-tending complexes; weak-field ligands (I⁻, Br⁻) give high-spin. The **spectrochemical series** ranks ligand field strength. Colour arises from **d–d transitions** whose energy equals Δ. Count unpaired electrons to predict magnetic moment μ = √(n(n+2)) BM. Chelating ligands like **EDTA** (hexadentate) form especially stable complexes (the chelate effect).`, estimatedReadTime: 2, orderIndex: 4 },
    { id: "jee-adv-chem-organic-mechanisms-m01", topicId: "jee-adv-chem-organic-mechanisms", title: "Organic Mechanisms", content: `**SN1** is first-order (rate depends only on substrate), goes through a carbocation, and favours 3° substrates and polar protic solvents, giving racemization. **SN2** is second-order, concerted, gives **inversion** (Walden), and favours 1° substrates, strong nucleophiles, and polar aprotic solvents. Carbocation stability is **3° > 2° > 1°** (hyperconjugation and resonance). **Markovnikov** addition puts H on the carbon already bearing more H (via the more stable carbocation). **E1/E2** eliminations compete with substitution; E2 is concerted and needs a strong base. In **electrophilic aromatic substitution**, −OH/−NH₂ are activating, ortho/para directors.`, estimatedReadTime: 2, orderIndex: 5 },
    { id: "jee-adv-chem-stereochemistry-m01", topicId: "jee-adv-chem-stereochemistry", title: "Stereochemistry", content: `A **chiral (stereo) centre** is a carbon bearing four different groups. **Enantiomers** are non-superimposable mirror images with opposite optical rotation; a 50:50 **racemic mixture** is optically inactive. **Diastereomers** are stereoisomers that are not mirror images. With n chiral centres and no symmetry there are up to **2ⁿ stereoisomers**; a **meso compound** contains chiral centres but is achiral overall due to an internal mirror plane. **Geometric (cis/trans, E/Z) isomerism** needs restricted rotation (a double bond or ring). Assign R/S by **CIP priority** of the four groups.`, estimatedReadTime: 2, orderIndex: 6 },
    { id: "jee-adv-chem-ionic-equilibrium-m01", topicId: "jee-adv-chem-ionic-equilibrium", title: "Ionic Equilibrium", content: `At 25 °C **pH + pOH = 14**. A **buffer** resists pH change; the **Henderson–Hasselbalch** equation gives pH = pKa + log([salt]/[acid]) — so at half-neutralization pH = pKa. The **common-ion effect** suppresses the dissociation of a weak electrolyte. Solubility is set by the **solubility product Ksp**; a common ion lowers solubility. Salts hydrolyse: a **weak-acid/strong-base salt** gives a basic solution, a **strong-acid/weak-base salt** an acidic one. By **Ostwald's dilution law** the degree of dissociation of a weak electrolyte increases on dilution.`, estimatedReadTime: 2, orderIndex: 7 },
    { id: "jee-adv-math-limits-continuity-m01", topicId: "jee-adv-math-limits-continuity", title: "Limits & Continuity", content: `Standard limits to memorize: lim_{x→0} sinx/x = 1, lim_{x→0}(1−cosx)/x² = ½, lim_{x→0}(eˣ−1)/x = 1, lim_{x→0}(ln(1+x))/x = 1, and lim_{n→∞}(1+1/n)ⁿ = e. **Continuity** at a requires lim_{x→a} f(x) = f(a). **Differentiability implies continuity**, but not conversely — |x| is continuous yet not differentiable at 0 (corner). Use **L'Hôpital's rule** for 0/0 or ∞/∞ forms by differentiating numerator and denominator. Check one-sided limits for piecewise functions.`, estimatedReadTime: 2, orderIndex: 0 },
    { id: "jee-adv-math-definite-integrals-m01", topicId: "jee-adv-math-definite-integrals", title: "Definite Integrals", content: `The **fundamental theorem**: ∫_a^b f(x)dx = F(b) − F(a). Powerful symmetry properties: ∫_{−a}^{a} f = 0 if f is **odd** and 2∫_0^a f if f is **even**; and the **king property** ∫_0^a f(x)dx = ∫_0^a f(a−x)dx, which collapses many trigonometric integrals. Standard results: ∫_0^{π/2} sinx dx = 1, ∫_0^{π} sinx dx = 2, ∫_0^1 xⁿ dx = 1/(n+1). Definite integrals give **areas** (∫y dx), and areas between curves come from the difference of the bounding functions.`, estimatedReadTime: 2, orderIndex: 1 },
    { id: "jee-adv-math-differential-equations-m01", topicId: "jee-adv-math-differential-equations", title: "Differential Equations", content: `**Order** is the highest derivative present; **degree** is the power of that highest derivative once the equation is polynomial in derivatives. The general solution carries as many arbitrary constants as the order. **Variable-separable** equations integrate directly after separating x and y. A **first-order linear** equation dy/dx + P(x)y = Q(x) is solved with the integrating factor e^{∫P dx}. **Homogeneous** equations use y = vx. The prototype dy/dx = ky has solution y = Ce^{kx} — exponential growth/decay underlying population, cooling, and radioactive-decay models.`, estimatedReadTime: 2, orderIndex: 2 },
    { id: "jee-adv-math-conics-m01", topicId: "jee-adv-math-conics", title: "Conic Sections", content: `Conics are classified by **eccentricity e**: circle e = 0, **ellipse** e < 1, **parabola** e = 1, **hyperbola** e > 1. For the parabola y² = 4ax the focus is (a, 0), directrix x = −a, and latus rectum 4a. An **ellipse** x²/a² + y²/b² = 1 has the sum of focal distances = 2a; a **hyperbola** has the difference = 2a. A **rectangular hyperbola** (a = b) has e = √2. Tangent and normal conditions, and the focus–directrix property (distance to focus = e × distance to directrix), solve most locus problems.`, estimatedReadTime: 2, orderIndex: 3 },
    { id: "jee-adv-math-complex-numbers-m01", topicId: "jee-adv-math-complex-numbers", title: "Complex Numbers", content: `With i² = −1, write z = a + bi; **modulus** |z| = √(a²+b²) and z·z̄ = |z|². Products multiply moduli and add arguments: |z₁z₂| = |z₁||z₂|, arg(z₁z₂) = arg z₁ + arg z₂ — the basis of **De Moivre's theorem** (cosθ + i sinθ)ⁿ = cos nθ + i sin nθ and **Euler's form** e^{iθ} = cosθ + i sinθ. The **n-th roots of unity** are equally spaced on the unit circle and **sum to 0**; the cube roots 1, ω, ω² satisfy 1 + ω + ω² = 0 and ω³ = 1. Rotations of points in the plane are just multiplication by e^{iθ}.`, estimatedReadTime: 2, orderIndex: 4 },
    { id: "jee-adv-math-probability-m01", topicId: "jee-adv-math-probability", title: "Probability", content: `Core rules: **addition** P(A∪B) = P(A) + P(B) − P(A∩B); **complement** P(A′) = 1 − P(A); mutually exclusive events have P(A∩B) = 0. **Conditional probability** P(A|B) = P(A∩B)/P(B); **independence** means P(A∩B) = P(A)P(B). **Bayes' theorem** updates a prior using P(A|B) = P(B|A)P(A)/P(B) — central to 'given the test is positive' problems. Repeated independent trials follow the **binomial** law P(r) = ⁿC_r pʳq^{n−r}. Always confirm the sample space and that probabilities sum to 1.`, estimatedReadTime: 2, orderIndex: 5 },
    { id: "jee-adv-math-vectors-3d-m01", topicId: "jee-adv-math-vectors-3d", title: "Vectors & 3D Geometry", content: `The **dot product** a·b = |a||b|cosθ is zero for perpendicular vectors and gives projections. The **cross product** a×b is perpendicular to both, with |a×b| = |a||b|sinθ equal to the area of the parallelogram they span. The **scalar triple product** [a b c] = a·(b×c) equals the volume of the parallelepiped and is **zero when the vectors are coplanar**. Direction cosines satisfy l² + m² + n² = 1, and a **unit vector** is a/|a|. Lines and planes in 3D reduce to these products (e.g., angle between planes from their normals).`, estimatedReadTime: 2, orderIndex: 6 },
    { id: "jee-adv-math-binomial-series-m01", topicId: "jee-adv-math-binomial-series", title: "Binomial & Series", content: `The **binomial theorem** (a+b)ⁿ has general term T_{r+1} = ⁿC_r a^{n−r}bʳ and n+1 terms; the **middle term** is the (n/2 + 1)-th when n is even. Coefficient facts: **ⁿC_r = ⁿC_{n−r}** and the sum of all coefficients is 2ⁿ (put a = b = 1). For an **AP**, Sₙ = n/2·[2a + (n−1)d]; for a **GP**, Sₙ = a(rⁿ−1)/(r−1) and the infinite sum a/(1−r) when |r| < 1. Useful sums: Σk = n(n+1)/2, Σk² = n(n+1)(2n+1)/6.`, estimatedReadTime: 2, orderIndex: 7 },
    ...advMaterials,
    ...adv2Materials
  ],
  questions: [
    // ── Physics: Rotational Dynamics ──
    { id: "jee-adv-phy-rotational-dynamics-q01", topicId: "jee-adv-phy-rotational-dynamics", text: "The moment of inertia of a uniform solid sphere of mass M and radius R about a diameter is:", optionA: "(2/5)MR²", optionB: "(2/3)MR²", optionC: "MR²", optionD: "(1/2)MR²", correctOption: "A", explanation: "A solid sphere has I = (2/5)MR² about a diameter; (2/3)MR² is for a thin spherical shell.", orderIndex: 0 },
    { id: "jee-adv-phy-rotational-dynamics-q02", topicId: "jee-adv-phy-rotational-dynamics", text: "A solid sphere, a disc, and a ring (same mass and radius) roll down an incline. Which reaches the bottom first?", optionA: "The ring", optionB: "The disc", optionC: "The solid sphere", optionD: "All together", correctOption: "C", explanation: "Acceleration a = g sinθ/(1 + I/MR²); the sphere has the smallest I/MR² (2/5), so the largest acceleration.", orderIndex: 1 },
    { id: "jee-adv-phy-rotational-dynamics-q03", topicId: "jee-adv-phy-rotational-dynamics", text: "For a solid cylinder rolling without slipping, the fraction of its total kinetic energy that is rotational is:", optionA: "1/2", optionB: "1/3", optionC: "2/5", optionD: "2/7", correctOption: "B", explanation: "With I = ½MR² and v = ωR, rotational KE = ½Iω² = ¼Mv², total = ¾Mv², so the fraction is 1/3.", orderIndex: 2 },
    { id: "jee-adv-phy-rotational-dynamics-q04", topicId: "jee-adv-phy-rotational-dynamics", text: "When a spinning skater pulls her arms in, her angular velocity increases because:", optionA: "Her angular momentum increases", optionB: "Her moment of inertia decreases while L is conserved", optionC: "Torque acts on her", optionD: "Her kinetic energy is conserved", correctOption: "B", explanation: "With no external torque, L = Iω is conserved; reducing I raises ω (and KE, supplied by her muscles).", orderIndex: 3 },
    { id: "jee-adv-phy-rotational-dynamics-q05", topicId: "jee-adv-phy-rotational-dynamics", text: "The parallel-axis theorem states that I about an axis a distance d from a parallel axis through the centre of mass is:", optionA: "I_cm − Md²", optionB: "I_cm + Md²", optionC: "I_cm + ½Md²", optionD: "Md² − I_cm", correctOption: "B", explanation: "I = I_cm + Md², adding the term for shifting the axis away from the centre of mass.", orderIndex: 4 },
    { id: "jee-adv-phy-rotational-dynamics-q06", topicId: "jee-adv-phy-rotational-dynamics", text: "During rolling without slipping on a fixed surface, the friction force:", optionA: "Is kinetic and dissipates energy", optionB: "Is static and does no work", optionC: "Is zero always", optionD: "Acts up the plane on level ground", correctOption: "B", explanation: "The contact point is instantaneously at rest, so friction is static and does no work in ideal rolling.", orderIndex: 5 },
    { id: "jee-adv-phy-rotational-dynamics-q07", topicId: "jee-adv-phy-rotational-dynamics", text: "The rotational analogue of Newton's second law is:", optionA: "τ = Iα", optionB: "F = ma", optionC: "L = Iω", optionD: "p = mv", correctOption: "A", explanation: "Net torque equals moment of inertia times angular acceleration: τ = Iα.", orderIndex: 6 },
    { id: "jee-adv-phy-rotational-dynamics-q08", topicId: "jee-adv-phy-rotational-dynamics", text: "The radius of gyration k of a body about an axis is defined by:", optionA: "I = Mk²", optionB: "I = ½Mk²", optionC: "k = MR", optionD: "I = Mk", correctOption: "A", explanation: "k is defined so that I = Mk²; it is the distance at which the whole mass would give the same I.", orderIndex: 7 },

    // ── Physics: SHM & Waves ──
    { id: "jee-adv-phy-shm-waves-q01", topicId: "jee-adv-phy-shm-waves", text: "In simple harmonic motion, the acceleration is:", optionA: "Constant", optionB: "Proportional to and directed opposite the displacement", optionC: "Proportional to velocity", optionD: "Maximum at the mean position", correctOption: "B", explanation: "a = −ω²x: acceleration is proportional to displacement and directed toward the mean position.", orderIndex: 0 },
    { id: "jee-adv-phy-shm-waves-q02", topicId: "jee-adv-phy-shm-waves", text: "The total mechanical energy of an SHM oscillator is proportional to:", optionA: "Amplitude", optionB: "The square of the amplitude", optionC: "1/amplitude", optionD: "The period", correctOption: "B", explanation: "E = ½mω²A², so the energy scales with the square of the amplitude.", orderIndex: 1 },
    { id: "jee-adv-phy-shm-waves-q03", topicId: "jee-adv-phy-shm-waves", text: "The speed of a transverse wave on a stretched string of tension T and linear density μ is:", optionA: "√(T/μ)", optionB: "√(μ/T)", optionC: "T/μ", optionD: "Tμ", correctOption: "A", explanation: "Wave speed on a string is v = √(T/μ).", orderIndex: 2 },
    { id: "jee-adv-phy-shm-waves-q04", topicId: "jee-adv-phy-shm-waves", text: "Two tuning forks of frequencies 256 Hz and 260 Hz sounded together produce beats at:", optionA: "4 Hz", optionB: "516 Hz", optionC: "258 Hz", optionD: "2 Hz", correctOption: "A", explanation: "Beat frequency = |f₁ − f₂| = |260 − 256| = 4 Hz.", orderIndex: 3 },
    { id: "jee-adv-phy-shm-waves-q05", topicId: "jee-adv-phy-shm-waves", text: "In a pipe closed at one end, the fundamental wavelength is:", optionA: "2L", optionB: "4L", optionC: "L", optionD: "L/2", correctOption: "B", explanation: "A closed pipe has a node at the closed end and antinode at the open end, giving λ = 4L for the fundamental.", orderIndex: 4 },
    { id: "jee-adv-phy-shm-waves-q06", topicId: "jee-adv-phy-shm-waves", text: "At the mean position of SHM, the particle has:", optionA: "Maximum velocity and zero acceleration", optionB: "Zero velocity and maximum acceleration", optionC: "Maximum velocity and maximum acceleration", optionD: "Zero of both", correctOption: "A", explanation: "At x = 0 speed is maximum (v = ωA) and acceleration (∝ x) is zero.", orderIndex: 5 },
    { id: "jee-adv-phy-shm-waves-q07", topicId: "jee-adv-phy-shm-waves", text: "Two perpendicular SHMs of equal frequency and amplitude with a phase difference of π/2 trace out:", optionA: "A straight line", optionB: "A circle", optionC: "A parabola", optionD: "A figure-eight", correctOption: "B", explanation: "Equal-amplitude perpendicular SHMs π/2 out of phase give a circular Lissajous figure.", orderIndex: 6 },
    { id: "jee-adv-phy-shm-waves-q08", topicId: "jee-adv-phy-shm-waves", text: "A source of sound moves toward a stationary observer. The observed frequency:", optionA: "Increases", optionB: "Decreases", optionC: "Is unchanged", optionD: "Becomes zero", correctOption: "A", explanation: "By the Doppler effect, an approaching source raises the observed frequency.", orderIndex: 7 },

    // ── Physics: Gauss's Law ──
    { id: "jee-adv-phy-gauss-law-q01", topicId: "jee-adv-phy-gauss-law", text: "The electric field inside a charged hollow conducting sphere (in the cavity, no enclosed charge) is:", optionA: "Zero", optionB: "kQ/r²", optionC: "Constant and nonzero", optionD: "kQ/r", correctOption: "A", explanation: "With no enclosed charge, Gauss's law gives zero field inside the conductor's cavity.", orderIndex: 0 },
    { id: "jee-adv-phy-gauss-law-q02", topicId: "jee-adv-phy-gauss-law", text: "The electric field due to an infinite line charge varies with distance r as:", optionA: "1/r²", optionB: "1/r", optionC: "r", optionD: "Independent of r", correctOption: "B", explanation: "A cylindrical Gaussian surface gives E = λ/(2πε₀r), i.e., E ∝ 1/r.", orderIndex: 1 },
    { id: "jee-adv-phy-gauss-law-q03", topicId: "jee-adv-phy-gauss-law", text: "The field due to an infinite uniformly charged plane sheet is:", optionA: "σ/2ε₀, independent of distance", optionB: "σ/ε₀, falling as 1/r", optionC: "Zero", optionD: "Proportional to distance", correctOption: "A", explanation: "For an infinite sheet E = σ/2ε₀, uniform and independent of distance from the sheet.", orderIndex: 2 },
    { id: "jee-adv-phy-gauss-law-q04", topicId: "jee-adv-phy-gauss-law", text: "The net electric flux through a closed surface enclosing charge q is:", optionA: "q/ε₀", optionB: "qε₀", optionC: "q/2ε₀", optionD: "Zero", correctOption: "A", explanation: "Gauss's law: Φ = q_enclosed/ε₀, independent of the surface's shape or the charge's position inside.", orderIndex: 3 },
    { id: "jee-adv-phy-gauss-law-q05", topicId: "jee-adv-phy-gauss-law", text: "Inside a uniformly charged non-conducting solid sphere, the field at distance r from the centre (r < R) varies as:", optionA: "1/r²", optionB: "Proportional to r", optionC: "Constant", optionD: "1/r", correctOption: "B", explanation: "Enclosed charge ∝ r³, so E ∝ r³/r² = r, growing linearly to the surface.", orderIndex: 4 },
    { id: "jee-adv-phy-gauss-law-q06", topicId: "jee-adv-phy-gauss-law", text: "The electric potential inside a conductor in electrostatic equilibrium is:", optionA: "Zero everywhere", optionB: "Constant (equal to the surface value)", optionC: "Highest at the centre", optionD: "Proportional to r", correctOption: "B", explanation: "Since E = 0 inside a conductor, the potential is constant throughout, equal to its surface potential.", orderIndex: 5 },
    { id: "jee-adv-phy-gauss-law-q07", topicId: "jee-adv-phy-gauss-law", text: "The electric field just outside the surface of a charged conductor is:", optionA: "σ/ε₀", optionB: "σ/2ε₀", optionC: "Zero", optionD: "σε₀", correctOption: "A", explanation: "A pillbox Gaussian surface at a conductor gives E = σ/ε₀ just outside, twice the infinite-sheet value.", orderIndex: 6 },
    { id: "jee-adv-phy-gauss-law-q08", topicId: "jee-adv-phy-gauss-law", text: "Gauss's law is most useful for computing fields when the charge distribution has:", optionA: "High symmetry (spherical, cylindrical, planar)", optionB: "No symmetry", optionC: "Only point charges", optionD: "Time dependence", correctOption: "A", explanation: "Symmetry lets you choose a Gaussian surface on which E is constant, making the integral trivial.", orderIndex: 7 },

    // ── Physics: Transient Circuits & EMI ──
    { id: "jee-adv-phy-transient-circuits-q01", topicId: "jee-adv-phy-transient-circuits", text: "The time constant of an RC charging circuit is:", optionA: "R/C", optionB: "RC", optionC: "1/RC", optionD: "R²C", correctOption: "B", explanation: "The RC circuit time constant is τ = RC, the time to reach (1 − 1/e) of the final charge.", orderIndex: 0 },
    { id: "jee-adv-phy-transient-circuits-q02", topicId: "jee-adv-phy-transient-circuits", text: "In an LR circuit, the current grows with time constant:", optionA: "LR", optionB: "R/L", optionC: "L/R", optionD: "1/LR", correctOption: "C", explanation: "For current growth in an LR circuit, τ = L/R.", orderIndex: 1 },
    { id: "jee-adv-phy-transient-circuits-q03", topicId: "jee-adv-phy-transient-circuits", text: "At the instant a current is switched on (t = 0), an ideal inductor behaves like:", optionA: "A short circuit", optionB: "An open circuit", optionC: "A pure resistor", optionD: "A capacitor", correctOption: "B", explanation: "An inductor opposes sudden change in current, so at t = 0 it acts as an open circuit (zero current).", orderIndex: 2 },
    { id: "jee-adv-phy-transient-circuits-q04", topicId: "jee-adv-phy-transient-circuits", text: "In steady-state DC, a capacitor behaves like:", optionA: "A short circuit", optionB: "An open circuit (no current)", optionC: "A resistor", optionD: "An inductor", correctOption: "B", explanation: "Once fully charged, no further current flows, so the capacitor acts as an open circuit in DC steady state.", orderIndex: 3 },
    { id: "jee-adv-phy-transient-circuits-q05", topicId: "jee-adv-phy-transient-circuits", text: "The energy stored in an inductor carrying current I is:", optionA: "½LI²", optionB: "LI²", optionC: "½L²I", optionD: "½LI", correctOption: "A", explanation: "The magnetic energy stored in an inductor is U = ½LI².", orderIndex: 4 },
    { id: "jee-adv-phy-transient-circuits-q06", topicId: "jee-adv-phy-transient-circuits", text: "Lenz's law states that the induced current opposes:", optionA: "The change in magnetic flux causing it", optionB: "The resistance of the circuit", optionC: "The applied voltage always", optionD: "Any current flow", correctOption: "A", explanation: "The induced current direction opposes the flux change that produces it, ensuring energy conservation.", orderIndex: 5 },
    { id: "jee-adv-phy-transient-circuits-q07", topicId: "jee-adv-phy-transient-circuits", text: "In one time constant, the charge on a discharging capacitor falls to what fraction of its initial value?", optionA: "1/2", optionB: "1/e", optionC: "1 − 1/e", optionD: "Zero", correctOption: "B", explanation: "Q = Q₀e^(−t/τ); at t = τ, Q = Q₀/e ≈ 0.37 Q₀.", orderIndex: 6 },
    { id: "jee-adv-phy-transient-circuits-q08", topicId: "jee-adv-phy-transient-circuits", text: "The self-induced emf in an inductor is given by:", optionA: "−L dI/dt", optionB: "−LI", optionC: "−L/I", optionD: "−dI/dt", correctOption: "A", explanation: "The back-emf of an inductor is ε = −L dI/dt, opposing the change in current.", orderIndex: 7 },

    // ── Physics: Wave Optics ──
    { id: "jee-adv-phy-wave-optics-q01", topicId: "jee-adv-phy-wave-optics", text: "In Young's double-slit experiment, the fringe width is:", optionA: "λd/D", optionB: "λD/d", optionC: "dD/λ", optionD: "λ/dD", correctOption: "B", explanation: "Fringe width β = λD/d, where D is slit-to-screen distance and d the slit separation.", orderIndex: 0 },
    { id: "jee-adv-phy-wave-optics-q02", topicId: "jee-adv-phy-wave-optics", text: "For a bright fringe in double-slit interference, the path difference equals:", optionA: "(n + ½)λ", optionB: "nλ", optionC: "nλ/2", optionD: "λ/n", correctOption: "B", explanation: "Constructive interference (bright fringe) occurs when the path difference is an integer multiple of λ.", orderIndex: 1 },
    { id: "jee-adv-phy-wave-optics-q03", topicId: "jee-adv-phy-wave-optics", text: "If a double-slit apparatus is immersed in water (n ≈ 1.33), the fringe width:", optionA: "Increases", optionB: "Decreases", optionC: "Stays the same", optionD: "Becomes zero", correctOption: "B", explanation: "Wavelength in water is λ/n, so β = λD/(nd) decreases.", orderIndex: 2 },
    { id: "jee-adv-phy-wave-optics-q04", topicId: "jee-adv-phy-wave-optics", text: "In single-slit diffraction, the first minimum occurs when:", optionA: "a sinθ = λ", optionB: "a sinθ = λ/2", optionC: "d sinθ = λ", optionD: "a sinθ = 2λ", correctOption: "A", explanation: "The first diffraction minimum from a slit of width a is at a sinθ = λ.", orderIndex: 3 },
    { id: "jee-adv-phy-wave-optics-q05", topicId: "jee-adv-phy-wave-optics", text: "Sustained interference requires the two sources to be:", optionA: "Coherent (constant phase difference)", optionB: "Of different frequency", optionC: "Incoherent", optionD: "Of different amplitude", correctOption: "A", explanation: "A stable interference pattern needs coherent sources with a fixed phase relationship.", orderIndex: 4 },
    { id: "jee-adv-phy-wave-optics-q06", topicId: "jee-adv-phy-wave-optics", text: "The resultant intensity of two interfering waves is I = I₁ + I₂ + 2√(I₁I₂)cosφ. It is maximum when φ equals:", optionA: "0", optionB: "π/2", optionC: "π", optionD: "3π/2", correctOption: "A", explanation: "Intensity is maximal when cosφ = 1, i.e., φ = 0 (constructive interference).", orderIndex: 5 },
    { id: "jee-adv-phy-wave-optics-q07", topicId: "jee-adv-phy-wave-optics", text: "Reflection at an optically denser medium introduces an extra path difference of:", optionA: "λ", optionB: "λ/2", optionC: "λ/4", optionD: "Zero", correctOption: "B", explanation: "A phase change of π on reflection at a denser medium corresponds to an extra path of λ/2.", orderIndex: 6 },
    { id: "jee-adv-phy-wave-optics-q08", topicId: "jee-adv-phy-wave-optics", text: "The resolving power of a telescope increases when the:", optionA: "Aperture diameter increases", optionB: "Aperture decreases", optionC: "Wavelength increases", optionD: "Focal length decreases", correctOption: "A", explanation: "Resolving power ∝ D/λ, so a larger aperture resolves finer detail.", orderIndex: 7 },

    // ── Physics: Thermodynamics ──
    { id: "jee-adv-phy-thermodynamics-q01", topicId: "jee-adv-phy-thermodynamics", text: "The first law of thermodynamics is expressed as:", optionA: "ΔU = Q − W", optionB: "ΔU = Q + W always with W on gas", optionC: "Q = ΔU × W", optionD: "W = Q + ΔU", correctOption: "A", explanation: "With W the work done by the gas, ΔU = Q − W (energy conservation).", orderIndex: 0 },
    { id: "jee-adv-phy-thermodynamics-q02", topicId: "jee-adv-phy-thermodynamics", text: "In an adiabatic process:", optionA: "Q = 0", optionB: "ΔU = 0", optionC: "W = 0", optionD: "T = constant", correctOption: "A", explanation: "An adiabatic process exchanges no heat with surroundings, so Q = 0.", orderIndex: 1 },
    { id: "jee-adv-phy-thermodynamics-q03", topicId: "jee-adv-phy-thermodynamics", text: "For an ideal gas, the internal energy depends only on:", optionA: "Pressure", optionB: "Volume", optionC: "Temperature", optionD: "Density", correctOption: "C", explanation: "Ideal-gas internal energy is a function of temperature alone.", orderIndex: 2 },
    { id: "jee-adv-phy-thermodynamics-q04", topicId: "jee-adv-phy-thermodynamics", text: "The rms speed of gas molecules is proportional to:", optionA: "T", optionB: "√T", optionC: "1/T", optionD: "T²", correctOption: "B", explanation: "v_rms = √(3RT/M), so it scales as √T.", orderIndex: 3 },
    { id: "jee-adv-phy-thermodynamics-q05", topicId: "jee-adv-phy-thermodynamics", text: "In an isothermal process for an ideal gas:", optionA: "ΔU = 0", optionB: "Q = 0", optionC: "W = 0", optionD: "ΔU = Q + W", correctOption: "A", explanation: "Constant temperature means no change in internal energy for an ideal gas, so ΔU = 0 and Q = W.", orderIndex: 4 },
    { id: "jee-adv-phy-thermodynamics-q06", topicId: "jee-adv-phy-thermodynamics", text: "For one mole of an ideal gas, Cp − Cv equals:", optionA: "R", optionB: "2R", optionC: "R/2", optionD: "Zero", correctOption: "A", explanation: "Mayer's relation: Cp − Cv = R per mole.", orderIndex: 5 },
    { id: "jee-adv-phy-thermodynamics-q07", topicId: "jee-adv-phy-thermodynamics", text: "The efficiency of a Carnot engine operating between hot (T_h) and cold (T_c) reservoirs is:", optionA: "1 − T_c/T_h", optionB: "T_c/T_h", optionC: "1 − T_h/T_c", optionD: "T_h/T_c − 1", correctOption: "A", explanation: "Carnot efficiency η = 1 − T_c/T_h with temperatures in kelvin.", orderIndex: 6 },
    { id: "jee-adv-phy-thermodynamics-q08", topicId: "jee-adv-phy-thermodynamics", text: "The ratio of specific heats γ for a monatomic ideal gas is:", optionA: "5/3", optionB: "7/5", optionC: "4/3", optionD: "1", correctOption: "A", explanation: "A monatomic gas has 3 degrees of freedom, giving Cv = (3/2)R and γ = 5/3.", orderIndex: 7 },

    // ── Physics: Modern Physics ──
    { id: "jee-adv-phy-modern-physics-q01", topicId: "jee-adv-phy-modern-physics", text: "In the photoelectric effect, the maximum kinetic energy of emitted electrons is:", optionA: "hν", optionB: "hν − φ", optionC: "φ − hν", optionD: "hν + φ", correctOption: "B", explanation: "Einstein's photoelectric equation: KE_max = hν − φ, where φ is the work function.", orderIndex: 0 },
    { id: "jee-adv-phy-modern-physics-q02", topicId: "jee-adv-phy-modern-physics", text: "The stopping potential in the photoelectric effect is independent of:", optionA: "Frequency of light", optionB: "Intensity of light", optionC: "Work function", optionD: "The metal used", correctOption: "B", explanation: "Stopping potential depends on frequency and work function but not on intensity.", orderIndex: 1 },
    { id: "jee-adv-phy-modern-physics-q03", topicId: "jee-adv-phy-modern-physics", text: "The de Broglie wavelength of a particle of momentum p is:", optionA: "hp", optionB: "h/p", optionC: "p/h", optionD: "h/p²", correctOption: "B", explanation: "λ = h/p relates a particle's wavelength to its momentum.", orderIndex: 2 },
    { id: "jee-adv-phy-modern-physics-q04", topicId: "jee-adv-phy-modern-physics", text: "In the Bohr model, the angular momentum of the electron is quantized in units of:", optionA: "h/2π", optionB: "h", optionC: "2πh", optionD: "h²", correctOption: "A", explanation: "Bohr's quantization: mvr = n(h/2π).", orderIndex: 3 },
    { id: "jee-adv-phy-modern-physics-q05", topicId: "jee-adv-phy-modern-physics", text: "The energy of the nth level of a hydrogen atom is proportional to:", optionA: "−1/n²", optionB: "−n²", optionC: "−1/n", optionD: "−n", correctOption: "A", explanation: "Eₙ = −13.6/n² eV, so energy ∝ −1/n².", orderIndex: 4 },
    { id: "jee-adv-phy-modern-physics-q06", topicId: "jee-adv-phy-modern-physics", text: "The binding energy per nucleon is maximum for nuclei near:", optionA: "Hydrogen", optionB: "Iron", optionC: "Uranium", optionD: "Helium", correctOption: "B", explanation: "Binding energy per nucleon peaks around iron (A ≈ 56), the most stable region.", orderIndex: 5 },
    { id: "jee-adv-phy-modern-physics-q07", topicId: "jee-adv-phy-modern-physics", text: "Increasing the frequency of incident light (above threshold) in the photoelectric effect:", optionA: "Increases the maximum KE of electrons", optionB: "Increases the number of electrons", optionC: "Has no effect", optionD: "Decreases the stopping potential", correctOption: "A", explanation: "Higher frequency raises photon energy hν, increasing KE_max (and the stopping potential).", orderIndex: 6 },
    { id: "jee-adv-phy-modern-physics-q08", topicId: "jee-adv-phy-modern-physics", text: "The half-life of a radioactive sample with decay constant λ is:", optionA: "λ/ln2", optionB: "ln2/λ", optionC: "1/λ", optionD: "λ ln2", correctOption: "B", explanation: "Half-life t½ = ln2/λ ≈ 0.693/λ.", orderIndex: 7 },

    // ── Physics: COM & Collisions ──
    { id: "jee-adv-phy-com-collisions-q01", topicId: "jee-adv-phy-com-collisions", text: "In an elastic collision, which quantities are conserved?", optionA: "Momentum only", optionB: "Kinetic energy only", optionC: "Both momentum and kinetic energy", optionD: "Neither", correctOption: "C", explanation: "Elastic collisions conserve both linear momentum and kinetic energy.", orderIndex: 0 },
    { id: "jee-adv-phy-com-collisions-q02", topicId: "jee-adv-phy-com-collisions", text: "In a perfectly inelastic collision:", optionA: "KE is conserved", optionB: "Bodies stick together and KE is not conserved", optionC: "Momentum is not conserved", optionD: "Both bodies stop", correctOption: "B", explanation: "The bodies move together afterward; momentum is conserved but kinetic energy is not.", orderIndex: 1 },
    { id: "jee-adv-phy-com-collisions-q03", topicId: "jee-adv-phy-com-collisions", text: "The coefficient of restitution e is defined as:", optionA: "Relative speed of separation ÷ relative speed of approach", optionB: "Speed of approach ÷ speed of separation", optionC: "Momentum after ÷ momentum before", optionD: "KE after ÷ KE before", correctOption: "A", explanation: "e = (relative velocity of separation)/(relative velocity of approach).", orderIndex: 2 },
    { id: "jee-adv-phy-com-collisions-q04", topicId: "jee-adv-phy-com-collisions", text: "In a one-dimensional elastic collision between equal masses, one initially at rest, the result is:", optionA: "They stick together", optionB: "The velocities are exchanged", optionC: "Both reverse direction", optionD: "Both stop", correctOption: "B", explanation: "For equal masses in an elastic collision, the moving body stops and the other moves off with its velocity.", orderIndex: 3 },
    { id: "jee-adv-phy-com-collisions-q05", topicId: "jee-adv-phy-com-collisions", text: "With no net external force on a system, the velocity of its centre of mass:", optionA: "Increases", optionB: "Remains constant", optionC: "Becomes zero", optionD: "Depends on internal forces", correctOption: "B", explanation: "Internal forces cancel; with zero external force, the COM velocity (system momentum) is constant.", orderIndex: 4 },
    { id: "jee-adv-phy-com-collisions-q06", topicId: "jee-adv-phy-com-collisions", text: "For a perfectly elastic collision, the coefficient of restitution is:", optionA: "0", optionB: "0.5", optionC: "1", optionD: "Infinite", correctOption: "C", explanation: "e = 1 for a perfectly elastic collision; e = 0 for a perfectly inelastic one.", orderIndex: 5 },
    { id: "jee-adv-phy-com-collisions-q07", topicId: "jee-adv-phy-com-collisions", text: "Impulse delivered to a body equals:", optionA: "Its change in momentum", optionB: "Its change in kinetic energy", optionC: "Force times distance", optionD: "Mass times acceleration", correctOption: "A", explanation: "Impulse = ∫F dt = change in momentum (the impulse–momentum theorem).", orderIndex: 6 },
    { id: "jee-adv-phy-com-collisions-q08", topicId: "jee-adv-phy-com-collisions", text: "The centre of mass of a system under an external force moves as if:", optionA: "The total mass were concentrated there and the net external force acted on it", optionB: "It were massless", optionC: "Only internal forces act", optionD: "It stays fixed always", correctOption: "A", explanation: "The COM obeys F_ext = M a_cm, moving like a point particle of the total mass.", orderIndex: 7 },

    // ── Chemistry: MOT ──
    { id: "jee-adv-chem-mot-q01", topicId: "jee-adv-chem-mot", text: "The bond order of the O₂ molecule is:", optionA: "1", optionB: "2", optionC: "2.5", optionD: "3", correctOption: "B", explanation: "O₂ has (8 − 4)/2 = 2 for its bond order (a double bond).", orderIndex: 0 },
    { id: "jee-adv-chem-mot-q02", topicId: "jee-adv-chem-mot", text: "Molecular orbital theory explains that O₂ is:", optionA: "Diamagnetic", optionB: "Paramagnetic with two unpaired electrons", optionC: "Non-existent", optionD: "Ionic", correctOption: "B", explanation: "Two unpaired electrons in the degenerate π* orbitals make O₂ paramagnetic — a key MOT success.", orderIndex: 1 },
    { id: "jee-adv-chem-mot-q03", topicId: "jee-adv-chem-mot", text: "Bond order in molecular orbital theory is calculated as:", optionA: "(N_bonding − N_antibonding)/2", optionB: "N_bonding + N_antibonding", optionC: "N_bonding × N_antibonding", optionD: "N_antibonding − N_bonding", correctOption: "A", explanation: "Bond order = ½(bonding electrons − antibonding electrons).", orderIndex: 2 },
    { id: "jee-adv-chem-mot-q04", topicId: "jee-adv-chem-mot", text: "The bond order of the N₂ molecule is:", optionA: "1", optionB: "2", optionC: "3", optionD: "2.5", correctOption: "C", explanation: "N₂ has (10 − 4)/2 = 3, a triple bond — hence its very high bond energy.", orderIndex: 3 },
    { id: "jee-adv-chem-mot-q05", topicId: "jee-adv-chem-mot", text: "The He₂ molecule does not exist because its bond order is:", optionA: "0", optionB: "1", optionC: "0.5", optionD: "2", correctOption: "A", explanation: "Equal bonding and antibonding electrons give a bond order of 0, so He₂ is not stable.", orderIndex: 4 },
    { id: "jee-adv-chem-mot-q06", topicId: "jee-adv-chem-mot", text: "The bond order of the superoxide ion O₂⁻ is:", optionA: "1", optionB: "1.5", optionC: "2", optionD: "2.5", correctOption: "B", explanation: "Adding one electron to O₂ (bond order 2) into a π* orbital gives (8 − 5)/2 = 1.5.", orderIndex: 5 },
    { id: "jee-adv-chem-mot-q07", topicId: "jee-adv-chem-mot", text: "As bond order increases, the bond length generally:", optionA: "Increases", optionB: "Decreases", optionC: "Stays constant", optionD: "Becomes zero", correctOption: "B", explanation: "Higher bond order means a stronger, shorter bond, so bond length decreases.", orderIndex: 6 },
    { id: "jee-adv-chem-mot-q08", topicId: "jee-adv-chem-mot", text: "For molecules up to N₂, the correct MO energy order places the σ2p_z:", optionA: "Below the π2p orbitals", optionB: "Above the π2p orbitals", optionC: "Below the σ2s", optionD: "Equal to the π*2p", correctOption: "B", explanation: "Due to s–p mixing in B₂–N₂, σ2p_z lies above the π2p orbitals (the order flips at O₂).", orderIndex: 7 },

    // ── Chemistry: Thermodynamics & Equilibrium ──
    { id: "jee-adv-chem-thermo-equilibrium-q01", topicId: "jee-adv-chem-thermo-equilibrium", text: "A reaction is spontaneous when:", optionA: "ΔG < 0", optionB: "ΔG > 0", optionC: "ΔH < 0 only", optionD: "ΔS < 0", correctOption: "A", explanation: "Spontaneity at constant T and P requires ΔG = ΔH − TΔS < 0.", orderIndex: 0 },
    { id: "jee-adv-chem-thermo-equilibrium-q02", topicId: "jee-adv-chem-thermo-equilibrium", text: "The relation between standard free energy and the equilibrium constant is:", optionA: "ΔG° = RT ln K", optionB: "ΔG° = −RT ln K", optionC: "ΔG° = −RT/K", optionD: "ΔG° = K/RT", correctOption: "B", explanation: "ΔG° = −RT ln K; a large K corresponds to a strongly negative ΔG°.", orderIndex: 1 },
    { id: "jee-adv-chem-thermo-equilibrium-q03", topicId: "jee-adv-chem-thermo-equilibrium", text: "For an exothermic reaction, increasing temperature:", optionA: "Increases K", optionB: "Decreases K", optionC: "Does not change K", optionD: "Makes K infinite", correctOption: "B", explanation: "By Le Chatelier, heating an exothermic reaction shifts it back, lowering the equilibrium constant.", orderIndex: 2 },
    { id: "jee-adv-chem-thermo-equilibrium-q04", topicId: "jee-adv-chem-thermo-equilibrium", text: "Kp and Kc are related by:", optionA: "Kp = Kc(RT)^Δn", optionB: "Kp = Kc/RT", optionC: "Kp = Kc(RT)^−Δn", optionD: "Kp = Kc + RTΔn", correctOption: "A", explanation: "Kp = Kc(RT)^Δn, where Δn is the change in moles of gas.", orderIndex: 3 },
    { id: "jee-adv-chem-thermo-equilibrium-q05", topicId: "jee-adv-chem-thermo-equilibrium", text: "Increasing the pressure on a gaseous equilibrium shifts it toward the side with:", optionA: "More moles of gas", optionB: "Fewer moles of gas", optionC: "Higher temperature", optionD: "No change ever", correctOption: "B", explanation: "Le Chatelier: higher pressure favours the side with fewer gas molecules.", orderIndex: 4 },
    { id: "jee-adv-chem-thermo-equilibrium-q06", topicId: "jee-adv-chem-thermo-equilibrium", text: "Adding an inert gas at constant volume to an equilibrium mixture:", optionA: "Shifts it forward", optionB: "Shifts it backward", optionC: "Causes no shift", optionD: "Doubles K", correctOption: "C", explanation: "At constant volume, partial pressures of reactants/products are unchanged, so there is no shift.", orderIndex: 5 },
    { id: "jee-adv-chem-thermo-equilibrium-q07", topicId: "jee-adv-chem-thermo-equilibrium", text: "A catalyst affects a reaction at equilibrium by:", optionA: "Shifting equilibrium toward products", optionB: "Changing K", optionC: "Speeding both directions equally without changing K", optionD: "Increasing the yield", correctOption: "C", explanation: "A catalyst lowers Ea for forward and reverse steps equally, so it changes rate but not K or position.", orderIndex: 6 },
    { id: "jee-adv-chem-thermo-equilibrium-q08", topicId: "jee-adv-chem-thermo-equilibrium", text: "The entropy change ΔS is positive when:", optionA: "Gas moles decrease", optionB: "A gas is produced or gas moles increase", optionC: "A gas condenses", optionD: "Temperature falls", correctOption: "B", explanation: "Producing more gas (greater disorder) raises entropy, giving a positive ΔS.", orderIndex: 7 },

    // ── Chemistry: Electrochemistry ──
    { id: "jee-adv-chem-electrochemistry-q01", topicId: "jee-adv-chem-electrochemistry", text: "The Nernst equation at 298 K is E = E° − (0.059/n) log Q. Here n is the:", optionA: "Number of electrons transferred", optionB: "Number of moles of gas", optionC: "Temperature", optionD: "Cell volume", correctOption: "A", explanation: "n is the number of electrons exchanged in the balanced cell reaction.", orderIndex: 0 },
    { id: "jee-adv-chem-electrochemistry-q02", topicId: "jee-adv-chem-electrochemistry", text: "The standard electrode potential of the standard hydrogen electrode is:", optionA: "+0.34 V", optionB: "0 V", optionC: "−0.76 V", optionD: "+1.10 V", correctOption: "B", explanation: "The SHE is the reference electrode, assigned a potential of exactly 0 V.", orderIndex: 1 },
    { id: "jee-adv-chem-electrochemistry-q03", topicId: "jee-adv-chem-electrochemistry", text: "In a galvanic (voltaic) cell, oxidation occurs at the:", optionA: "Cathode", optionB: "Anode", optionC: "Salt bridge", optionD: "Both electrodes", correctOption: "B", explanation: "Oxidation always occurs at the anode; reduction occurs at the cathode.", orderIndex: 2 },
    { id: "jee-adv-chem-electrochemistry-q04", topicId: "jee-adv-chem-electrochemistry", text: "A species with a more positive standard reduction potential is a:", optionA: "Stronger oxidizing agent", optionB: "Stronger reducing agent", optionC: "Weaker oxidizer", optionD: "Neutral species", correctOption: "A", explanation: "A higher reduction potential means a greater tendency to be reduced, i.e., a stronger oxidizing agent.", orderIndex: 3 },
    { id: "jee-adv-chem-electrochemistry-q05", topicId: "jee-adv-chem-electrochemistry", text: "The standard cell potential is calculated as:", optionA: "E°cathode − E°anode", optionB: "E°anode − E°cathode", optionC: "E°cathode + E°anode", optionD: "E°anode × E°cathode", correctOption: "A", explanation: "E°cell = E°cathode − E°anode, using both as standard reduction potentials.", orderIndex: 4 },
    { id: "jee-adv-chem-electrochemistry-q06", topicId: "jee-adv-chem-electrochemistry", text: "By Faraday's laws, the moles of metal deposited by charge It are:", optionA: "It/(nF)", optionB: "nF/(It)", optionC: "ItnF", optionD: "It/F only", correctOption: "A", explanation: "Moles deposited = It/(nF), where n is electrons per ion and F is the Faraday constant.", orderIndex: 5 },
    { id: "jee-adv-chem-electrochemistry-q07", topicId: "jee-adv-chem-electrochemistry", text: "Kohlrausch's law of independent migration gives the limiting molar conductivity as:", optionA: "The product of ionic conductivities", optionB: "The sum of the ions' independent contributions", optionC: "Zero at infinite dilution", optionD: "Independent of the ions", correctOption: "B", explanation: "At infinite dilution, Λ°m is the sum of the independent cationic and anionic molar conductivities.", orderIndex: 6 },
    { id: "jee-adv-chem-electrochemistry-q08", topicId: "jee-adv-chem-electrochemistry", text: "For a spontaneous electrochemical cell:", optionA: "E°cell > 0 and ΔG° < 0", optionB: "E°cell < 0 and ΔG° > 0", optionC: "E°cell = 0", optionD: "ΔG° > 0 and E°cell > 0", correctOption: "A", explanation: "ΔG° = −nFE°cell, so a positive cell potential corresponds to negative ΔG° (spontaneous).", orderIndex: 7 },

    // ── Chemistry: Kinetics ──
    { id: "jee-adv-chem-kinetics-q01", topicId: "jee-adv-chem-kinetics", text: "The half-life of a first-order reaction:", optionA: "Depends on initial concentration", optionB: "Is independent of initial concentration", optionC: "Doubles each half-life", optionD: "Equals 1/k", correctOption: "B", explanation: "For first order, t½ = 0.693/k, independent of the starting concentration.", orderIndex: 0 },
    { id: "jee-adv-chem-kinetics-q02", topicId: "jee-adv-chem-kinetics", text: "The units of the rate constant for a first-order reaction are:", optionA: "mol L⁻¹ s⁻¹", optionB: "s⁻¹", optionC: "L mol⁻¹ s⁻¹", optionD: "L² mol⁻² s⁻¹", correctOption: "B", explanation: "A first-order rate constant has units of s⁻¹ (inverse time).", orderIndex: 1 },
    { id: "jee-adv-chem-kinetics-q03", topicId: "jee-adv-chem-kinetics", text: "The Arrhenius equation is:", optionA: "k = A e^(−Ea/RT)", optionB: "k = A e^(Ea/RT)", optionC: "k = Ea/RT", optionD: "k = A/RT", correctOption: "A", explanation: "k = A e^(−Ea/RT); rate rises as temperature increases or activation energy falls.", orderIndex: 2 },
    { id: "jee-adv-chem-kinetics-q04", topicId: "jee-adv-chem-kinetics", text: "The overall order of a reaction with rate = k[A]²[B] is:", optionA: "1", optionB: "2", optionC: "3", optionD: "0", correctOption: "C", explanation: "Overall order is the sum of exponents: 2 + 1 = 3.", orderIndex: 3 },
    { id: "jee-adv-chem-kinetics-q05", topicId: "jee-adv-chem-kinetics", text: "Increasing temperature increases reaction rate mainly because it:", optionA: "Lowers the activation energy", optionB: "Increases the fraction of molecules with energy ≥ Ea", optionC: "Increases concentration", optionD: "Changes the order", correctOption: "B", explanation: "Higher T shifts the Maxwell–Boltzmann distribution so more collisions exceed Ea.", orderIndex: 4 },
    { id: "jee-adv-chem-kinetics-q06", topicId: "jee-adv-chem-kinetics", text: "The rate of a zero-order reaction is:", optionA: "Independent of reactant concentration", optionB: "Proportional to [A]", optionC: "Proportional to [A]²", optionD: "Inversely proportional to [A]", correctOption: "A", explanation: "A zero-order rate equals k and does not depend on concentration.", orderIndex: 5 },
    { id: "jee-adv-chem-kinetics-q07", topicId: "jee-adv-chem-kinetics", text: "In a multistep reaction, the overall rate is governed by the:", optionA: "Fastest step", optionB: "Slowest (rate-determining) step", optionC: "First step always", optionD: "Last step always", correctOption: "B", explanation: "The slowest elementary step is the rate-determining step and sets the rate law.", orderIndex: 6 },
    { id: "jee-adv-chem-kinetics-q08", topicId: "jee-adv-chem-kinetics", text: "A catalyst increases reaction rate by:", optionA: "Increasing the activation energy", optionB: "Providing an alternative path of lower activation energy", optionC: "Raising the temperature", optionD: "Shifting the equilibrium", correctOption: "B", explanation: "A catalyst offers a lower-Ea pathway, speeding the reaction without being consumed or altering K.", orderIndex: 7 },

    // ── Chemistry: Coordination ──
    { id: "jee-adv-chem-coordination-q01", topicId: "jee-adv-chem-coordination", text: "In an octahedral crystal field, the five d orbitals split into:", optionA: "t₂g (lower) and e_g (higher)", optionB: "e_g (lower) and t₂g (higher)", optionC: "A single level", optionD: "Three equal levels", correctOption: "A", explanation: "Octahedrally, the t₂g set is stabilized and the e_g set raised, separated by Δ_o.", orderIndex: 0 },
    { id: "jee-adv-chem-coordination-q02", topicId: "jee-adv-chem-coordination", text: "A strong-field ligand tends to produce a complex that is:", optionA: "High-spin", optionB: "Low-spin", optionC: "Always tetrahedral", optionD: "Colourless", correctOption: "B", explanation: "A large Δ_o from a strong-field ligand pairs electrons in t₂g, giving a low-spin complex.", orderIndex: 1 },
    { id: "jee-adv-chem-coordination-q03", topicId: "jee-adv-chem-coordination", text: "The colour of transition-metal complexes arises from:", optionA: "d–d electronic transitions", optionB: "Nuclear transitions", optionC: "Bond vibrations", optionD: "Ionization", correctOption: "A", explanation: "Absorption promoting a d electron across Δ gives the complementary observed colour.", orderIndex: 2 },
    { id: "jee-adv-chem-coordination-q04", topicId: "jee-adv-chem-coordination", text: "The complex [Fe(CN)₆]⁴⁻ (Fe²⁺, d⁶, strong field) is:", optionA: "High-spin, paramagnetic", optionB: "Low-spin, diamagnetic", optionC: "Tetrahedral", optionD: "Bond order 3", correctOption: "B", explanation: "CN⁻ is a strong-field ligand, pairing all six d electrons in t₂g — low-spin and diamagnetic.", orderIndex: 3 },
    { id: "jee-adv-chem-coordination-q05", topicId: "jee-adv-chem-coordination", text: "In the spectrochemical series, which ligand produces the largest splitting?", optionA: "I⁻", optionB: "Br⁻", optionC: "H₂O", optionD: "CN⁻", correctOption: "D", explanation: "CN⁻ (and CO) are strong-field ligands at the high-Δ end of the spectrochemical series.", orderIndex: 4 },
    { id: "jee-adv-chem-coordination-q06", topicId: "jee-adv-chem-coordination", text: "EDTA is a ligand of denticity:", optionA: "Monodentate", optionB: "Bidentate", optionC: "Hexadentate", optionD: "Tridentate", correctOption: "C", explanation: "EDTA binds through two N and four O donor sites — it is hexadentate.", orderIndex: 5 },
    { id: "jee-adv-chem-coordination-q07", topicId: "jee-adv-chem-coordination", text: "The magnetic moment (spin-only) of a complex with n unpaired electrons is:", optionA: "√(n(n+2)) BM", optionB: "n BM", optionC: "n² BM", optionD: "2n BM", correctOption: "A", explanation: "The spin-only magnetic moment is μ = √(n(n+2)) Bohr magnetons.", orderIndex: 6 },
    { id: "jee-adv-chem-coordination-q08", topicId: "jee-adv-chem-coordination", text: "The enhanced stability of complexes with chelating ligands is called the:", optionA: "Chelate effect", optionB: "Inert-pair effect", optionC: "Trans effect", optionD: "Jahn–Teller effect", correctOption: "A", explanation: "Chelating (polydentate) ligands form more stable complexes than comparable monodentate ligands — the chelate effect.", orderIndex: 7 },

    // ── Chemistry: Organic Mechanisms ──
    { id: "jee-adv-chem-organic-mechanisms-q01", topicId: "jee-adv-chem-organic-mechanisms", text: "The rate of an SN1 reaction depends on:", optionA: "Concentration of substrate only", optionB: "Concentration of nucleophile only", optionC: "Both substrate and nucleophile", optionD: "Neither", correctOption: "A", explanation: "SN1 is first order — its rate-determining step is carbocation formation from the substrate alone.", orderIndex: 0 },
    { id: "jee-adv-chem-organic-mechanisms-q02", topicId: "jee-adv-chem-organic-mechanisms", text: "An SN2 reaction proceeds with:", optionA: "Retention of configuration", optionB: "Inversion of configuration (Walden inversion)", optionC: "Racemization", optionD: "No stereochemical change", correctOption: "B", explanation: "The nucleophile attacks opposite the leaving group, inverting the stereocentre in a concerted SN2 step.", orderIndex: 1 },
    { id: "jee-adv-chem-organic-mechanisms-q03", topicId: "jee-adv-chem-organic-mechanisms", text: "Markovnikov's rule for HX addition to an alkene states that H adds to the carbon that:", optionA: "Already bears more hydrogens", optionB: "Bears fewer hydrogens", optionC: "Is more substituted", optionD: "Has the double bond only", correctOption: "A", explanation: "H adds to the carbon with more H's, forming the more stable (more substituted) carbocation.", orderIndex: 2 },
    { id: "jee-adv-chem-organic-mechanisms-q04", topicId: "jee-adv-chem-organic-mechanisms", text: "The order of carbocation stability is:", optionA: "1° > 2° > 3°", optionB: "3° > 2° > 1°", optionC: "All equal", optionD: "2° > 3° > 1°", correctOption: "B", explanation: "Tertiary carbocations are most stable due to hyperconjugation and inductive electron donation.", orderIndex: 3 },
    { id: "jee-adv-chem-organic-mechanisms-q05", topicId: "jee-adv-chem-organic-mechanisms", text: "An E2 elimination is best described as:", optionA: "A concerted, single-step process requiring a strong base", optionB: "A two-step process via a carbocation", optionC: "First order in substrate only", optionD: "Independent of base strength", correctOption: "A", explanation: "E2 is a one-step, second-order elimination in which a strong base removes a β-H as the leaving group departs.", orderIndex: 4 },
    { id: "jee-adv-chem-organic-mechanisms-q06", topicId: "jee-adv-chem-organic-mechanisms", text: "In electrophilic aromatic substitution, the −OH group is:", optionA: "Deactivating and meta-directing", optionB: "Activating and ortho/para-directing", optionC: "Deactivating and ortho/para-directing", optionD: "Inert", correctOption: "B", explanation: "−OH donates electron density by resonance, activating the ring and directing to ortho/para positions.", orderIndex: 5 },
    { id: "jee-adv-chem-organic-mechanisms-q07", topicId: "jee-adv-chem-organic-mechanisms", text: "SN2 reactions are favoured by:", optionA: "Tertiary substrates and weak nucleophiles", optionB: "Primary substrates, strong nucleophiles, and polar aprotic solvents", optionC: "Bulky substrates and protic solvents", optionD: "Absence of nucleophile", correctOption: "B", explanation: "Little steric hindrance (1°), a strong nucleophile, and a polar aprotic solvent all speed the SN2 backside attack.", orderIndex: 6 },
    { id: "jee-adv-chem-organic-mechanisms-q08", topicId: "jee-adv-chem-organic-mechanisms", text: "SN1 reactions of a chiral substrate typically give:", optionA: "Pure inversion", optionB: "A racemic (or largely racemized) product", optionC: "Pure retention", optionD: "No reaction", correctOption: "B", explanation: "The planar carbocation intermediate can be attacked from either face, giving racemization.", orderIndex: 7 },

    // ── Chemistry: Stereochemistry ──
    { id: "jee-adv-chem-stereochemistry-q01", topicId: "jee-adv-chem-stereochemistry", text: "A chiral centre is a carbon bonded to:", optionA: "Four different groups", optionB: "Two identical groups", optionC: "Three groups", optionD: "A double bond", correctOption: "A", explanation: "A stereocentre carries four different substituents, making the molecule non-superimposable on its mirror image.", orderIndex: 0 },
    { id: "jee-adv-chem-stereochemistry-q02", topicId: "jee-adv-chem-stereochemistry", text: "Enantiomers are:", optionA: "Identical molecules", optionB: "Non-superimposable mirror images", optionC: "Structural isomers", optionD: "Superimposable mirror images", correctOption: "B", explanation: "Enantiomers are mirror-image stereoisomers that cannot be superimposed; they rotate plane-polarized light oppositely.", orderIndex: 1 },
    { id: "jee-adv-chem-stereochemistry-q03", topicId: "jee-adv-chem-stereochemistry", text: "A molecule with n chiral centres and no internal symmetry has at most how many stereoisomers?", optionA: "2n", optionB: "n²", optionC: "2ⁿ", optionD: "n!", correctOption: "C", explanation: "Each stereocentre doubles the count, giving up to 2ⁿ stereoisomers.", orderIndex: 2 },
    { id: "jee-adv-chem-stereochemistry-q04", topicId: "jee-adv-chem-stereochemistry", text: "A meso compound is:", optionA: "Chiral and optically active", optionB: "Achiral despite having chiral centres (internal mirror plane)", optionC: "A structural isomer", optionD: "A racemic mixture", correctOption: "B", explanation: "A meso compound has stereocentres but an internal plane of symmetry, so it is achiral and optically inactive.", orderIndex: 3 },
    { id: "jee-adv-chem-stereochemistry-q05", topicId: "jee-adv-chem-stereochemistry", text: "Diastereomers are stereoisomers that are:", optionA: "Mirror images", optionB: "Not mirror images of each other", optionC: "Identical", optionD: "Always meso", correctOption: "B", explanation: "Diastereomers are non-mirror-image stereoisomers with different physical properties.", orderIndex: 4 },
    { id: "jee-adv-chem-stereochemistry-q06", topicId: "jee-adv-chem-stereochemistry", text: "Cis–trans (geometric) isomerism requires:", optionA: "Free rotation about a single bond", optionB: "Restricted rotation (a double bond or ring)", optionC: "A chiral centre", optionD: "A racemic mixture", correctOption: "B", explanation: "Restricted rotation, as in a C=C double bond or ring, locks substituents into cis or trans arrangements.", orderIndex: 5 },
    { id: "jee-adv-chem-stereochemistry-q07", topicId: "jee-adv-chem-stereochemistry", text: "A racemic mixture is:", optionA: "Optically inactive (equal enantiomers cancel)", optionB: "Strongly optically active", optionC: "A single enantiomer", optionD: "A meso compound", correctOption: "A", explanation: "Equal amounts of two enantiomers rotate light in opposite directions, cancelling to zero net rotation.", orderIndex: 6 },
    { id: "jee-adv-chem-stereochemistry-q08", topicId: "jee-adv-chem-stereochemistry", text: "R and S configurations are assigned using:", optionA: "Cahn–Ingold–Prelog priority rules", optionB: "Markovnikov's rule", optionC: "Hund's rule", optionD: "Aufbau principle", correctOption: "A", explanation: "CIP rules rank the four groups by priority to assign R (clockwise) or S (counterclockwise).", orderIndex: 7 },

    // ── Chemistry: Ionic Equilibrium ──
    { id: "jee-adv-chem-ionic-equilibrium-q01", topicId: "jee-adv-chem-ionic-equilibrium", text: "At 25 °C, the sum pH + pOH equals:", optionA: "7", optionB: "14", optionC: "1", optionD: "0", correctOption: "B", explanation: "Since K_w = 10⁻¹⁴ at 25 °C, pH + pOH = 14.", orderIndex: 0 },
    { id: "jee-adv-chem-ionic-equilibrium-q02", topicId: "jee-adv-chem-ionic-equilibrium", text: "The Henderson–Hasselbalch equation for an acidic buffer is:", optionA: "pH = pKa + log([salt]/[acid])", optionB: "pH = pKa − log([salt]/[acid])", optionC: "pH = pKa × [salt]/[acid]", optionD: "pH = pKw − pKa", correctOption: "A", explanation: "pH = pKa + log([conjugate base]/[acid]) governs buffer pH.", orderIndex: 1 },
    { id: "jee-adv-chem-ionic-equilibrium-q03", topicId: "jee-adv-chem-ionic-equilibrium", text: "The common-ion effect:", optionA: "Increases the dissociation of a weak electrolyte", optionB: "Suppresses the dissociation of a weak electrolyte", optionC: "Has no effect", optionD: "Changes Kw", correctOption: "B", explanation: "Adding an ion common to the equilibrium shifts it back, suppressing dissociation (Le Chatelier).", orderIndex: 2 },
    { id: "jee-adv-chem-ionic-equilibrium-q04", topicId: "jee-adv-chem-ionic-equilibrium", text: "The solubility product Ksp describes the equilibrium for:", optionA: "A sparingly soluble salt dissolving", optionB: "A gas dissolving", optionC: "Acid dissociation", optionD: "Buffer action", correctOption: "A", explanation: "Ksp is the equilibrium constant for a slightly soluble ionic solid in equilibrium with its ions.", orderIndex: 3 },
    { id: "jee-adv-chem-ionic-equilibrium-q05", topicId: "jee-adv-chem-ionic-equilibrium", text: "A stronger acid has a:", optionA: "Higher pKa", optionB: "Lower pKa", optionC: "pKa of 14", optionD: "pKa of 7", correctOption: "B", explanation: "A larger Ka means a smaller pKa, so stronger acids have lower pKa values.", orderIndex: 4 },
    { id: "jee-adv-chem-ionic-equilibrium-q06", topicId: "jee-adv-chem-ionic-equilibrium", text: "At the half-equivalence point of a weak-acid titration:", optionA: "pH = pKa", optionB: "pH = 7", optionC: "pH = pKw", optionD: "pH = 0", correctOption: "A", explanation: "When [acid] = [salt], the log term is zero, so pH = pKa.", orderIndex: 5 },
    { id: "jee-adv-chem-ionic-equilibrium-q07", topicId: "jee-adv-chem-ionic-equilibrium", text: "An aqueous solution of sodium acetate (salt of a weak acid and strong base) is:", optionA: "Acidic", optionB: "Basic", optionC: "Neutral", optionD: "Amphoteric", correctOption: "B", explanation: "The acetate ion hydrolyses to give OH⁻, making the solution basic.", orderIndex: 6 },
    { id: "jee-adv-chem-ionic-equilibrium-q08", topicId: "jee-adv-chem-ionic-equilibrium", text: "According to Ostwald's dilution law, on dilution the degree of dissociation of a weak electrolyte:", optionA: "Increases", optionB: "Decreases", optionC: "Stays constant", optionD: "Becomes zero", correctOption: "A", explanation: "Dilution shifts the dissociation equilibrium forward, increasing the degree of dissociation.", orderIndex: 7 },

    // ── Mathematics: Limits & Continuity ──
    { id: "jee-adv-math-limits-continuity-q01", topicId: "jee-adv-math-limits-continuity", text: "The value of lim_{x→0} (sin x)/x is:", optionA: "0", optionB: "1", optionC: "∞", optionD: "Undefined", correctOption: "B", explanation: "This standard limit equals 1.", orderIndex: 0 },
    { id: "jee-adv-math-limits-continuity-q02", topicId: "jee-adv-math-limits-continuity", text: "If a function is differentiable at a point, then at that point it is necessarily:", optionA: "Discontinuous", optionB: "Continuous", optionC: "Constant", optionD: "Zero", correctOption: "B", explanation: "Differentiability implies continuity (though the converse is false).", orderIndex: 1 },
    { id: "jee-adv-math-limits-continuity-q03", topicId: "jee-adv-math-limits-continuity", text: "The limit lim_{n→∞} (1 + 1/n)ⁿ equals:", optionA: "1", optionB: "e", optionC: "0", optionD: "∞", correctOption: "B", explanation: "This is the definition of Euler's number e ≈ 2.718.", orderIndex: 2 },
    { id: "jee-adv-math-limits-continuity-q04", topicId: "jee-adv-math-limits-continuity", text: "L'Hôpital's rule can be directly applied to a limit of the form:", optionA: "0/0 or ∞/∞", optionB: "1 + 1", optionC: "Any finite value", optionD: "0 × 1", correctOption: "A", explanation: "L'Hôpital's rule applies to indeterminate forms 0/0 and ∞/∞ by differentiating top and bottom.", orderIndex: 3 },
    { id: "jee-adv-math-limits-continuity-q05", topicId: "jee-adv-math-limits-continuity", text: "The function f(x) = |x| is:", optionA: "Differentiable at x = 0", optionB: "Continuous but not differentiable at x = 0", optionC: "Discontinuous at x = 0", optionD: "Undefined at x = 0", correctOption: "B", explanation: "|x| is continuous everywhere but has a corner at 0, so it is not differentiable there.", orderIndex: 4 },
    { id: "jee-adv-math-limits-continuity-q06", topicId: "jee-adv-math-limits-continuity", text: "The value of lim_{x→0} (1 − cos x)/x² is:", optionA: "1", optionB: "1/2", optionC: "0", optionD: "2", correctOption: "B", explanation: "Using 1 − cos x ≈ x²/2 for small x, the limit is 1/2.", orderIndex: 5 },
    { id: "jee-adv-math-limits-continuity-q07", topicId: "jee-adv-math-limits-continuity", text: "A function f is continuous at x = a if:", optionA: "f(a) exists only", optionB: "lim_{x→a} f(x) = f(a)", optionC: "The limit exists but need not equal f(a)", optionD: "f is differentiable", correctOption: "B", explanation: "Continuity requires the limit to exist and equal the function value at the point.", orderIndex: 6 },
    { id: "jee-adv-math-limits-continuity-q08", topicId: "jee-adv-math-limits-continuity", text: "The value of lim_{x→0} (eˣ − 1)/x is:", optionA: "0", optionB: "1", optionC: "e", optionD: "∞", correctOption: "B", explanation: "This standard limit equals 1 (the derivative of eˣ at 0).", orderIndex: 7 },

    // ── Mathematics: Definite Integrals ──
    { id: "jee-adv-math-definite-integrals-q01", topicId: "jee-adv-math-definite-integrals", text: "By the fundamental theorem of calculus, ∫_a^b f(x) dx equals:", optionA: "F(b) − F(a)", optionB: "F(a) − F(b)", optionC: "F(b) + F(a)", optionD: "f(b) − f(a)", correctOption: "A", explanation: "If F is an antiderivative of f, the definite integral is F(b) − F(a).", orderIndex: 0 },
    { id: "jee-adv-math-definite-integrals-q02", topicId: "jee-adv-math-definite-integrals", text: "For an odd function f, the integral ∫_{−a}^{a} f(x) dx equals:", optionA: "0", optionB: "2∫_0^a f", optionC: "a²", optionD: "f(a)", correctOption: "A", explanation: "The integral of an odd function over a symmetric interval is zero.", orderIndex: 1 },
    { id: "jee-adv-math-definite-integrals-q03", topicId: "jee-adv-math-definite-integrals", text: "The value of ∫_0^{π/2} sin x dx is:", optionA: "0", optionB: "1", optionC: "π/2", optionD: "2", correctOption: "B", explanation: "∫ sin x dx = −cos x; evaluated from 0 to π/2 gives −0 − (−1) = 1.", orderIndex: 2 },
    { id: "jee-adv-math-definite-integrals-q04", topicId: "jee-adv-math-definite-integrals", text: "Which property is valid (the 'king' property)?", optionA: "∫_0^a f(x)dx = ∫_0^a f(a−x)dx", optionB: "∫_0^a f(x)dx = ∫_0^a f(x+a)dx", optionC: "∫_0^a f(x)dx = f(a)−f(0)", optionD: "∫_0^a f(x)dx = 0", correctOption: "A", explanation: "The reflection property ∫_0^a f(x)dx = ∫_0^a f(a−x)dx simplifies many integrals.", orderIndex: 3 },
    { id: "jee-adv-math-definite-integrals-q05", topicId: "jee-adv-math-definite-integrals", text: "The area under a curve y = f(x) from x = a to x = b (with f ≥ 0) is:", optionA: "∫_a^b y dx", optionB: "∫_a^b y² dx", optionC: "f(b) − f(a)", optionD: "dy/dx", correctOption: "A", explanation: "The definite integral ∫_a^b y dx gives the area between the curve and the x-axis.", orderIndex: 4 },
    { id: "jee-adv-math-definite-integrals-q06", topicId: "jee-adv-math-definite-integrals", text: "The value of ∫_0^1 xⁿ dx (n ≠ −1) is:", optionA: "1/(n+1)", optionB: "n+1", optionC: "1/n", optionD: "nⁿ", correctOption: "A", explanation: "∫_0^1 xⁿ dx = [x^{n+1}/(n+1)]_0^1 = 1/(n+1).", orderIndex: 5 },
    { id: "jee-adv-math-definite-integrals-q07", topicId: "jee-adv-math-definite-integrals", text: "For an even function f, ∫_{−a}^{a} f(x) dx equals:", optionA: "0", optionB: "2∫_0^a f(x) dx", optionC: "∫_0^a f", optionD: "a·f(a)", correctOption: "B", explanation: "An even function is symmetric, so its integral over [−a, a] is twice the integral over [0, a].", orderIndex: 6 },
    { id: "jee-adv-math-definite-integrals-q08", topicId: "jee-adv-math-definite-integrals", text: "The value of ∫_0^{π} sin x dx is:", optionA: "0", optionB: "1", optionC: "2", optionD: "π", correctOption: "C", explanation: "∫_0^π sin x dx = [−cos x]_0^π = −(−1) − (−1) = 2.", orderIndex: 7 },

    // ── Mathematics: Differential Equations ──
    { id: "jee-adv-math-differential-equations-q01", topicId: "jee-adv-math-differential-equations", text: "The order of a differential equation is the:", optionA: "Highest-order derivative present", optionB: "Power of the highest derivative", optionC: "Number of terms", optionD: "Degree of the polynomial", correctOption: "A", explanation: "Order is defined by the highest derivative appearing in the equation.", orderIndex: 0 },
    { id: "jee-adv-math-differential-equations-q02", topicId: "jee-adv-math-differential-equations", text: "The degree of a differential equation is the power of the:", optionA: "Highest-order derivative (once polynomial in derivatives)", optionB: "Lowest derivative", optionC: "Independent variable", optionD: "Constant term", correctOption: "A", explanation: "Degree is the exponent of the highest-order derivative when the equation is polynomial in derivatives.", orderIndex: 1 },
    { id: "jee-adv-math-differential-equations-q03", topicId: "jee-adv-math-differential-equations", text: "The solution of dy/dx = ky is:", optionA: "y = kx + C", optionB: "y = Ce^{kx}", optionC: "y = C/x", optionD: "y = kx²", correctOption: "B", explanation: "Separating variables gives ln y = kx + c, i.e., y = Ce^{kx} (exponential growth/decay).", orderIndex: 2 },
    { id: "jee-adv-math-differential-equations-q04", topicId: "jee-adv-math-differential-equations", text: "A first-order linear equation dy/dx + P(x)y = Q(x) is solved using the integrating factor:", optionA: "e^{∫P dx}", optionB: "e^{∫Q dx}", optionC: "∫P dx", optionD: "e^{−x}", correctOption: "A", explanation: "Multiplying by e^{∫P dx} makes the left side an exact derivative.", orderIndex: 3 },
    { id: "jee-adv-math-differential-equations-q05", topicId: "jee-adv-math-differential-equations", text: "The number of arbitrary constants in the general solution equals the:", optionA: "Order of the equation", optionB: "Degree of the equation", optionC: "Number of variables", optionD: "Always one", correctOption: "A", explanation: "A general solution has as many independent arbitrary constants as the order of the equation.", orderIndex: 4 },
    { id: "jee-adv-math-differential-equations-q06", topicId: "jee-adv-math-differential-equations", text: "A homogeneous differential equation dy/dx = f(y/x) is typically solved by the substitution:", optionA: "y = vx", optionB: "x = vy²", optionC: "y = x + v", optionD: "v = xy", correctOption: "A", explanation: "Putting y = vx reduces a homogeneous equation to a variable-separable form in v and x.", orderIndex: 5 },
    { id: "jee-adv-math-differential-equations-q07", topicId: "jee-adv-math-differential-equations", text: "The differential equation of a family with exponential growth is:", optionA: "dy/dx = ky", optionB: "dy/dx = k", optionC: "dy/dx = kx", optionD: "d²y/dx² = 0", correctOption: "A", explanation: "dy/dx = ky (rate proportional to amount) gives exponential growth y = Ce^{kx}.", orderIndex: 6 },
    { id: "jee-adv-math-differential-equations-q08", topicId: "jee-adv-math-differential-equations", text: "The method of separation of variables applies when the equation can be written as:", optionA: "g(y) dy = f(x) dx", optionB: "dy/dx = x + y", optionC: "y·dy/dx = e^{x+y} only", optionD: "It never applies", correctOption: "A", explanation: "If the equation separates into g(y)dy = f(x)dx, both sides can be integrated directly.", orderIndex: 7 },

    // ── Mathematics: Conics ──
    { id: "jee-adv-math-conics-q01", topicId: "jee-adv-math-conics", text: "The eccentricity of a circle is:", optionA: "0", optionB: "1", optionC: "Between 0 and 1", optionD: "Greater than 1", correctOption: "A", explanation: "A circle is a special ellipse with eccentricity 0.", orderIndex: 0 },
    { id: "jee-adv-math-conics-q02", topicId: "jee-adv-math-conics", text: "For the parabola y² = 4ax, the focus is at:", optionA: "(0, a)", optionB: "(a, 0)", optionC: "(−a, 0)", optionD: "(0, −a)", correctOption: "B", explanation: "The standard parabola y² = 4ax opens rightward with focus (a, 0).", orderIndex: 1 },
    { id: "jee-adv-math-conics-q03", topicId: "jee-adv-math-conics", text: "The eccentricity of an ellipse satisfies:", optionA: "e = 0", optionB: "0 < e < 1", optionC: "e = 1", optionD: "e > 1", correctOption: "B", explanation: "An ellipse has eccentricity strictly between 0 and 1.", orderIndex: 2 },
    { id: "jee-adv-math-conics-q04", topicId: "jee-adv-math-conics", text: "A conic with eccentricity greater than 1 is a:", optionA: "Circle", optionB: "Parabola", optionC: "Ellipse", optionD: "Hyperbola", correctOption: "D", explanation: "Eccentricity e > 1 characterizes a hyperbola.", orderIndex: 3 },
    { id: "jee-adv-math-conics-q05", topicId: "jee-adv-math-conics", text: "For an ellipse, the sum of distances of any point from the two foci equals:", optionA: "2a (the major axis length)", optionB: "2b", optionC: "a + b", optionD: "The eccentricity", correctOption: "A", explanation: "The defining property of an ellipse is that this focal sum is constant at 2a.", orderIndex: 4 },
    { id: "jee-adv-math-conics-q06", topicId: "jee-adv-math-conics", text: "The directrix of the parabola y² = 4ax is:", optionA: "x = a", optionB: "x = −a", optionC: "y = a", optionD: "y = −a", correctOption: "B", explanation: "For y² = 4ax the directrix is the line x = −a.", orderIndex: 5 },
    { id: "jee-adv-math-conics-q07", topicId: "jee-adv-math-conics", text: "The eccentricity of a rectangular hyperbola is:", optionA: "1", optionB: "√2", optionC: "2", optionD: "√3", correctOption: "B", explanation: "A rectangular hyperbola has a = b, giving e = √2.", orderIndex: 6 },
    { id: "jee-adv-math-conics-q08", topicId: "jee-adv-math-conics", text: "The length of the latus rectum of y² = 4ax is:", optionA: "a", optionB: "2a", optionC: "4a", optionD: "a/2", correctOption: "C", explanation: "The latus rectum of y² = 4ax has length 4a.", orderIndex: 7 },

    // ── Mathematics: Complex Numbers ──
    { id: "jee-adv-math-complex-numbers-q01", topicId: "jee-adv-math-complex-numbers", text: "The value of i² is:", optionA: "1", optionB: "−1", optionC: "i", optionD: "0", correctOption: "B", explanation: "By definition of the imaginary unit, i² = −1.", orderIndex: 0 },
    { id: "jee-adv-math-complex-numbers-q02", topicId: "jee-adv-math-complex-numbers", text: "For complex numbers, |z₁z₂| equals:", optionA: "|z₁| + |z₂|", optionB: "|z₁||z₂|", optionC: "|z₁| − |z₂|", optionD: "|z₁|/|z₂|", correctOption: "B", explanation: "The modulus of a product is the product of the moduli.", orderIndex: 1 },
    { id: "jee-adv-math-complex-numbers-q03", topicId: "jee-adv-math-complex-numbers", text: "The sum of all n-th roots of unity is:", optionA: "1", optionB: "0", optionC: "n", optionD: "−1", correctOption: "B", explanation: "The n-th roots of unity are symmetric about the origin and sum to zero (for n > 1).", orderIndex: 2 },
    { id: "jee-adv-math-complex-numbers-q04", topicId: "jee-adv-math-complex-numbers", text: "Euler's formula states that e^{iθ} equals:", optionA: "cos θ + i sin θ", optionB: "cos θ − i sin θ", optionC: "sin θ + i cos θ", optionD: "1 + iθ", correctOption: "A", explanation: "Euler's formula: e^{iθ} = cos θ + i sin θ.", orderIndex: 3 },
    { id: "jee-adv-math-complex-numbers-q05", topicId: "jee-adv-math-complex-numbers", text: "For two complex numbers, arg(z₁z₂) equals:", optionA: "arg z₁ − arg z₂", optionB: "arg z₁ + arg z₂", optionC: "arg z₁ × arg z₂", optionD: "0", correctOption: "B", explanation: "Multiplying complex numbers adds their arguments.", orderIndex: 4 },
    { id: "jee-adv-math-complex-numbers-q06", topicId: "jee-adv-math-complex-numbers", text: "For a complex number z, the product z·z̄ equals:", optionA: "|z|²", optionB: "|z|", optionC: "2Re(z)", optionD: "0", correctOption: "A", explanation: "z·z̄ = (a+bi)(a−bi) = a² + b² = |z|².", orderIndex: 5 },
    { id: "jee-adv-math-complex-numbers-q07", topicId: "jee-adv-math-complex-numbers", text: "For the cube roots of unity 1, ω, ω², the sum 1 + ω + ω² equals:", optionA: "0", optionB: "1", optionC: "3", optionD: "ω", correctOption: "A", explanation: "The three cube roots of unity sum to zero, and ω³ = 1.", orderIndex: 6 },
    { id: "jee-adv-math-complex-numbers-q08", topicId: "jee-adv-math-complex-numbers", text: "The modulus of z = a + bi is:", optionA: "a + b", optionB: "√(a² + b²)", optionC: "a² + b²", optionD: "|a| + |b|", correctOption: "B", explanation: "The modulus is the distance from the origin: √(a² + b²).", orderIndex: 7 },

    // ── Mathematics: Probability ──
    { id: "jee-adv-math-probability-q01", topicId: "jee-adv-math-probability", text: "For any two events, P(A ∪ B) equals:", optionA: "P(A) + P(B)", optionB: "P(A) + P(B) − P(A ∩ B)", optionC: "P(A)·P(B)", optionD: "P(A) − P(B)", correctOption: "B", explanation: "The addition rule subtracts the overlap: P(A∪B) = P(A) + P(B) − P(A∩B).", orderIndex: 0 },
    { id: "jee-adv-math-probability-q02", topicId: "jee-adv-math-probability", text: "Two events A and B are independent if:", optionA: "P(A ∩ B) = P(A)P(B)", optionB: "P(A ∩ B) = 0", optionC: "P(A ∪ B) = 1", optionD: "P(A) = P(B)", correctOption: "A", explanation: "Independence means the joint probability equals the product of the individual probabilities.", orderIndex: 1 },
    { id: "jee-adv-math-probability-q03", topicId: "jee-adv-math-probability", text: "Bayes' theorem is used to:", optionA: "Update the probability of a cause given observed evidence", optionB: "Add two probabilities", optionC: "Find a mean", optionD: "Compute variance", correctOption: "A", explanation: "Bayes' theorem reverses conditional probabilities: P(A|B) = P(B|A)P(A)/P(B).", orderIndex: 2 },
    { id: "jee-adv-math-probability-q04", topicId: "jee-adv-math-probability", text: "The conditional probability P(A | B) is defined as:", optionA: "P(A ∩ B)/P(B)", optionB: "P(A)·P(B)", optionC: "P(A ∪ B)/P(A)", optionD: "P(B)/P(A)", correctOption: "A", explanation: "P(A|B) = P(A∩B)/P(B), for P(B) > 0.", orderIndex: 3 },
    { id: "jee-adv-math-probability-q05", topicId: "jee-adv-math-probability", text: "The sum of the probabilities of all outcomes in a sample space is:", optionA: "0", optionB: "1", optionC: "Depends on the events", optionD: "Infinite", correctOption: "B", explanation: "Probabilities over the whole sample space always sum to 1.", orderIndex: 4 },
    { id: "jee-adv-math-probability-q06", topicId: "jee-adv-math-probability", text: "The probability of the complement, P(A′), equals:", optionA: "1 − P(A)", optionB: "P(A)", optionC: "1 + P(A)", optionD: "0", correctOption: "A", explanation: "The complement rule: P(A′) = 1 − P(A).", orderIndex: 5 },
    { id: "jee-adv-math-probability-q07", topicId: "jee-adv-math-probability", text: "In n independent trials with success probability p, the probability of exactly r successes is:", optionA: "ⁿC_r pʳ(1−p)^{n−r}", optionB: "pʳ", optionC: "np", optionD: "ⁿC_r p^{n}", correctOption: "A", explanation: "The binomial distribution gives P(r) = ⁿC_r pʳ q^{n−r} with q = 1 − p.", orderIndex: 6 },
    { id: "jee-adv-math-probability-q08", topicId: "jee-adv-math-probability", text: "For mutually exclusive events A and B, P(A ∩ B) equals:", optionA: "P(A)P(B)", optionB: "0", optionC: "P(A) + P(B)", optionD: "1", correctOption: "B", explanation: "Mutually exclusive events cannot occur together, so their joint probability is 0.", orderIndex: 7 },

    // ── Mathematics: Vectors & 3D ──
    { id: "jee-adv-math-vectors-3d-q01", topicId: "jee-adv-math-vectors-3d", text: "The dot product a·b equals:", optionA: "|a||b| sin θ", optionB: "|a||b| cos θ", optionC: "|a| + |b|", optionD: "|a×b|", correctOption: "B", explanation: "The scalar (dot) product is a·b = |a||b|cos θ.", orderIndex: 0 },
    { id: "jee-adv-math-vectors-3d-q02", topicId: "jee-adv-math-vectors-3d", text: "Two nonzero vectors are perpendicular if their dot product is:", optionA: "1", optionB: "0", optionC: "|a||b|", optionD: "Negative", correctOption: "B", explanation: "a·b = 0 (with cos 90° = 0) means the vectors are perpendicular.", orderIndex: 1 },
    { id: "jee-adv-math-vectors-3d-q03", topicId: "jee-adv-math-vectors-3d", text: "The magnitude |a × b| represents the:", optionA: "Volume of a cube", optionB: "Area of the parallelogram formed by a and b", optionC: "Length of a", optionD: "Dot product", correctOption: "B", explanation: "|a×b| = |a||b|sin θ equals the area of the parallelogram spanned by a and b.", orderIndex: 2 },
    { id: "jee-adv-math-vectors-3d-q04", topicId: "jee-adv-math-vectors-3d", text: "The cross product a × b is a vector that is:", optionA: "Parallel to a", optionB: "Perpendicular to both a and b", optionC: "In the plane of a and b", optionD: "Equal to a·b", correctOption: "B", explanation: "The cross product is perpendicular to the plane containing a and b.", orderIndex: 3 },
    { id: "jee-adv-math-vectors-3d-q05", topicId: "jee-adv-math-vectors-3d", text: "The scalar triple product [a b c] gives the:", optionA: "Area of a triangle", optionB: "Volume of the parallelepiped formed by a, b, c", optionC: "A unit vector", optionD: "An angle", correctOption: "B", explanation: "a·(b×c) equals the (signed) volume of the parallelepiped with edges a, b, c.", orderIndex: 4 },
    { id: "jee-adv-math-vectors-3d-q06", topicId: "jee-adv-math-vectors-3d", text: "Three vectors are coplanar if their scalar triple product is:", optionA: "1", optionB: "0", optionC: "Positive", optionD: "Negative", correctOption: "B", explanation: "A zero scalar triple product means zero enclosed volume, so the vectors are coplanar.", orderIndex: 5 },
    { id: "jee-adv-math-vectors-3d-q07", topicId: "jee-adv-math-vectors-3d", text: "The direction cosines l, m, n of a line satisfy:", optionA: "l + m + n = 1", optionB: "l² + m² + n² = 1", optionC: "lmn = 1", optionD: "l² + m² + n² = 0", correctOption: "B", explanation: "Direction cosines always satisfy l² + m² + n² = 1.", orderIndex: 6 },
    { id: "jee-adv-math-vectors-3d-q08", topicId: "jee-adv-math-vectors-3d", text: "A unit vector in the direction of a is:", optionA: "a/|a|", optionB: "|a|·a", optionC: "a·a", optionD: "a × a", correctOption: "A", explanation: "Dividing a vector by its magnitude gives a unit vector in the same direction.", orderIndex: 7 },

    // ── Mathematics: Binomial & Series ──
    { id: "jee-adv-math-binomial-series-q01", topicId: "jee-adv-math-binomial-series", text: "In the expansion of (1 + x)ⁿ, the general term T_{r+1} is:", optionA: "ⁿC_r xʳ", optionB: "ⁿC_r x^{n−r}", optionC: "xʳ", optionD: "ⁿC_r", correctOption: "A", explanation: "The (r+1)-th term of (1+x)ⁿ is ⁿC_r xʳ.", orderIndex: 0 },
    { id: "jee-adv-math-binomial-series-q02", topicId: "jee-adv-math-binomial-series", text: "The sum of the binomial coefficients ⁿC_0 + ⁿC_1 + … + ⁿC_n equals:", optionA: "2ⁿ", optionB: "n²", optionC: "n!", optionD: "2n", correctOption: "A", explanation: "Setting x = 1 in (1+x)ⁿ gives the coefficient sum 2ⁿ.", orderIndex: 1 },
    { id: "jee-adv-math-binomial-series-q03", topicId: "jee-adv-math-binomial-series", text: "The number of terms in the expansion of (a + b)ⁿ is:", optionA: "n", optionB: "n + 1", optionC: "2n", optionD: "n − 1", correctOption: "B", explanation: "The exponents of a run from n down to 0, giving n + 1 terms.", orderIndex: 2 },
    { id: "jee-adv-math-binomial-series-q04", topicId: "jee-adv-math-binomial-series", text: "In the expansion of (a + b)ⁿ with n even, the middle term is the:", optionA: "(n/2)-th term", optionB: "(n/2 + 1)-th term", optionC: "(n + 1)-th term", optionD: "First term", correctOption: "B", explanation: "For even n there is a single middle term, the (n/2 + 1)-th.", orderIndex: 3 },
    { id: "jee-adv-math-binomial-series-q05", topicId: "jee-adv-math-binomial-series", text: "The sum of the first n terms of an AP with first term a and common difference d is:", optionA: "n/2·[2a + (n−1)d]", optionB: "a + (n−1)d", optionC: "n·a·d", optionD: "a·rⁿ", correctOption: "A", explanation: "The AP sum formula is Sₙ = n/2·[2a + (n−1)d].", orderIndex: 4 },
    { id: "jee-adv-math-binomial-series-q06", topicId: "jee-adv-math-binomial-series", text: "The sum to infinity of a GP with first term a and ratio r (|r| < 1) is:", optionA: "a/(1 − r)", optionB: "a(1 − r)", optionC: "a·rⁿ", optionD: "a/r", correctOption: "A", explanation: "For |r| < 1 the infinite GP converges to a/(1 − r).", orderIndex: 5 },
    { id: "jee-adv-math-binomial-series-q07", topicId: "jee-adv-math-binomial-series", text: "The sum of the first n natural numbers is:", optionA: "n(n+1)/2", optionB: "n²", optionC: "n(n+1)(2n+1)/6", optionD: "n(n−1)/2", correctOption: "A", explanation: "1 + 2 + … + n = n(n+1)/2.", orderIndex: 6 },
    { id: "jee-adv-math-binomial-series-q08", topicId: "jee-adv-math-binomial-series", text: "The identity ⁿC_r = ⁿC_{n−r} reflects that:", optionA: "Choosing r items equals leaving out n−r items", optionB: "Coefficients are always 1", optionC: "r must equal n", optionD: "The sum is 2ⁿ", correctOption: "A", explanation: "Selecting r objects is equivalent to excluding the other n − r, so the coefficients are equal.", orderIndex: 7 },
    ...advQuestions,
    ...adv2Questions
  ]
});
