// NEET extra chapters — rounds out the remaining major NCERT chapters across
// Biology, Chemistry, and Physics. Each is a new topic with a study material
// and 12 questions. Ids namespaced neet-<subject>-*.
import type { AuthoredMaterial } from "./builder";
import type { Question, Topic } from "@jyotir/core";

export const extraTopics: Topic[] = [
  // Biology
  { id: "neet-biology-reproduction-in-organisms", subjectId: "neet-biology", name: "Reproduction in Organisms", slug: "reproduction-in-organisms", orderIndex: 36 },
  { id: "neet-biology-strategies-food-production", subjectId: "neet-biology", name: "Strategies for Enhancement in Food Production", slug: "strategies-food-production", orderIndex: 37 },
  { id: "neet-biology-biodiversity-conservation", subjectId: "neet-biology", name: "Biodiversity & Conservation", slug: "biodiversity-conservation", orderIndex: 38 },
  // Chemistry
  { id: "neet-chemistry-hydrogen", subjectId: "neet-chemistry", name: "Hydrogen", slug: "hydrogen", orderIndex: 26 },
  { id: "neet-chemistry-environmental-chemistry", subjectId: "neet-chemistry", name: "Environmental Chemistry", slug: "environmental-chemistry", orderIndex: 27 },
  { id: "neet-chemistry-p-block-15-18", subjectId: "neet-chemistry", name: "p-Block Elements (Groups 15–18)", slug: "p-block-15-18", orderIndex: 28 },
  // Physics
  { id: "neet-physics-alternating-current", subjectId: "neet-physics", name: "Alternating Current", slug: "alternating-current", orderIndex: 25 }
];

export const extraMaterials: AuthoredMaterial[] = [
  { id: "neet-biology-reproduction-in-organisms-m01", topicId: "neet-biology-reproduction-in-organisms", title: "Reproduction in Organisms", content: `**Reproduction** ensures continuity of a species. **Asexual reproduction** (single parent, offspring genetically identical — clones) includes binary fission (Amoeba), budding (yeast, Hydra), fragmentation, spore formation, and vegetative propagation in plants (runners, rhizomes, tubers, bulbs). **Sexual reproduction** (two parents, gamete fusion) creates **variation** and involves **meiosis** and **fertilisation**. Organisms are **unisexual** (dioecious) or **bisexual** (monoecious/hermaphrodite). The **life span** varies widely and is unrelated to size. Events are grouped into **pre-fertilisation** (gametogenesis, gamete transfer), **fertilisation** (syngamy), and **post-fertilisation** (zygote, embryogenesis).`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "neet-biology-strategies-food-production-m01", topicId: "neet-biology-strategies-food-production", title: "Strategies for Enhancement in Food Production", content: `**Animal husbandry** manages livestock, poultry, and fisheries. **Breeding**: inbreeding increases homozygosity (can cause inbreeding depression); **outbreeding** (out-crossing, cross-breeding, hybridisation) introduces vigour. **MOET** (multiple ovulation embryo transfer) speeds cattle improvement. **Apiculture** (beekeeping) and **pisciculture** aid food output. **Plant breeding** develops improved varieties via germplasm collection, selection, hybridisation, and testing (e.g., high-yield wheat, disease-resistant crops; the Green Revolution). **Biofortification** breeds nutrient-rich crops. **Single-cell protein (SCP)** (Spirulina) and **tissue culture** (micropropagation, somaclones, somatic hybridisation) provide additional food and clonal plants; **totipotency** enables whole plants from single cells.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "neet-biology-biodiversity-conservation-m01", topicId: "neet-biology-biodiversity-conservation", title: "Biodiversity & Conservation", content: `**Biodiversity** exists at genetic, species, and ecological levels. Diversity is highest in the **tropics** and decreases toward the poles (latitudinal gradient); the **species–area relationship** is a rising curve. The importance of biodiversity is captured by the 'rivet-popper' analogy. **Loss** drivers — the 'Evil Quartet': **habitat loss and fragmentation, over-exploitation, invasive alien species, and co-extinctions**. **Conservation** is **in-situ** (biosphere reserves, national parks, wildlife sanctuaries, sacred groves; protects **hotspots**) or **ex-situ** (zoos, botanical gardens, seed/gene banks, cryopreservation). India is a mega-diverse country; global efforts include the **Rio Earth Summit** and **CBD**.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "neet-chemistry-hydrogen-m01", topicId: "neet-chemistry-hydrogen", title: "Hydrogen", content: `**Hydrogen** (1s¹) resembles both alkali metals (forms H⁺) and halogens (forms H⁻, needs one electron for a stable shell), so its periodic position is unique. It has three isotopes: **protium (¹H), deuterium (²H/D), and tritium (³H/T, radioactive)**. **Dihydrogen (H₂)** is prepared industrially by steam reforming and is used in the **Haber process** (ammonia) and hydrogenation of oils. **Hydrides** are ionic (with s-block metals), covalent (with p-block), or metallic (interstitial, with d/f-block). **Water** shows hardness — **temporary** (bicarbonates, removed by boiling/Clark's method) and **permanent** (sulphates/chlorides, removed by washing soda/ion exchange). **Hydrogen peroxide (H₂O₂)** acts as both oxidising and reducing agent. Hydrogen is a promising clean **fuel**.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "neet-chemistry-environmental-chemistry-m01", topicId: "neet-chemistry-environmental-chemistry", title: "Environmental Chemistry", content: `**Air pollution**: oxides of sulphur and nitrogen cause **acid rain** (pH < 5.6); CO is a poison binding haemoglobin; particulates form smog. **Classical (London) smog** is reducing (SO₂ + fog); **photochemical (Los Angeles) smog** is oxidising (NOx + hydrocarbons + sunlight → ozone, PAN). **Greenhouse gases** (CO₂, CH₄, N₂O, CFCs, water vapour) drive **global warming**. **Stratospheric ozone** shields UV; CFCs deplete it (the ozone hole). **Water pollution**: high **BOD** and **eutrophication** from nutrients; heavy metals and pathogens threaten health. **Green chemistry** designs processes that reduce or eliminate hazardous substances (e.g., using H₂O₂ or safer solvents).`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "neet-chemistry-p-block-15-18-m01", topicId: "neet-chemistry-p-block-15-18", title: "p-Block: Groups 15–18", content: `**Group 15 (nitrogen family)**: N₂ is inert (triple bond); key compounds NH₃ (Haber process), HNO₃ (Ostwald process); oxidation states −3 to +5. **Group 16 (oxygen family/chalcogens)**: O and S; **H₂SO₄** by the Contact process ('king of chemicals'); allotropes of sulphur. **Group 17 (halogens)**: most reactive non-metals, strong oxidisers (F₂ > Cl₂ > Br₂ > I₂); form HX acids (HF weakest due to strong H-bonding, but attacks glass) and interhalogens. **Group 18 (noble gases)**: full octet, largely inert; **Xe** forms fluorides (XeF₂, XeF₄, XeF₆). Down each group, metallic character rises and non-metallic/oxidising character falls; the first member is anomalous (small size, no d-orbitals).`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "neet-physics-alternating-current-m01", topicId: "neet-physics-alternating-current", title: "Alternating Current", content: `**AC** varies sinusoidally; the **RMS value** relates to the peak by I_rms = I₀/√2 (and V_rms = V₀/√2). In AC circuits, opposition to current is **reactance**: inductive **X_L = ωL** (grows with frequency) and capacitive **X_C = 1/ωC** (falls with frequency); combined with resistance they give the **impedance Z = √(R² + (X_L − X_C)²)**. In a pure inductor, current lags voltage by 90°; in a pure capacitor, current leads by 90°. **Resonance** in a series LCR circuit occurs when X_L = X_C, giving minimum impedance (= R) and maximum current, at f = 1/(2π√(LC)). Average **power = V_rms·I_rms·cosφ**, where cosφ is the **power factor**. A **transformer** changes AC voltage using mutual induction (V_s/V_p = N_s/N_p).`, estimatedReadTime: 2, orderIndex: 0 }
];

export const extraQuestions: Question[] = [
  // ── Biology: Reproduction in Organisms ──
  { id: "neet-biology-reproduction-in-organisms-q01", topicId: "neet-biology-reproduction-in-organisms", text: "Offspring produced by asexual reproduction are:", optionA: "Genetically identical to the parent (clones)", optionB: "Genetically variable", optionC: "Always different sexes", optionD: "Sterile", correctOption: "A", explanation: "Asexual reproduction involves one parent and produces genetically identical clones.", orderIndex: 0 },
  { id: "neet-biology-reproduction-in-organisms-q02", topicId: "neet-biology-reproduction-in-organisms", text: "Binary fission is a mode of asexual reproduction seen in:", optionA: "Amoeba", optionB: "Humans", optionC: "Mango trees", optionD: "Ferns", correctOption: "A", explanation: "Amoeba and many unicellular organisms reproduce by binary fission.", orderIndex: 1 },
  { id: "neet-biology-reproduction-in-organisms-q03", topicId: "neet-biology-reproduction-in-organisms", text: "Budding is a form of asexual reproduction characteristic of:", optionA: "Yeast and Hydra", optionB: "Frogs", optionC: "Birds", optionD: "Ferns", correctOption: "A", explanation: "Yeast and Hydra reproduce asexually by budding.", orderIndex: 2 },
  { id: "neet-biology-reproduction-in-organisms-q04", topicId: "neet-biology-reproduction-in-organisms", text: "The main advantage of sexual reproduction is:", optionA: "Genetic variation", optionB: "Identical offspring", optionC: "No need for gametes", optionD: "Faster reproduction always", correctOption: "A", explanation: "Sexual reproduction generates variation, aiding adaptation and evolution.", orderIndex: 3 },
  { id: "neet-biology-reproduction-in-organisms-q05", topicId: "neet-biology-reproduction-in-organisms", text: "An organism having both male and female reproductive organs is called:", optionA: "Unisexual", optionB: "Bisexual (hermaphrodite)", optionC: "Dioecious", optionD: "Sterile", correctOption: "B", explanation: "A bisexual (monoecious/hermaphrodite) organism bears both sex organs.", orderIndex: 4 },
  { id: "neet-biology-reproduction-in-organisms-q06", topicId: "neet-biology-reproduction-in-organisms", text: "Vegetative propagation by runners is seen in:", optionA: "Grass/strawberry", optionB: "Amoeba", optionC: "Yeast", optionD: "Bacteria", correctOption: "A", explanation: "Runners are horizontal stems producing new plants (e.g., grass, strawberry).", orderIndex: 5 },
  { id: "neet-biology-reproduction-in-organisms-q07", topicId: "neet-biology-reproduction-in-organisms", text: "The fusion of male and female gametes is called:", optionA: "Syngamy (fertilisation)", optionB: "Meiosis", optionC: "Budding", optionD: "Fragmentation", correctOption: "A", explanation: "Syngamy is the fusion of gametes to form a zygote.", orderIndex: 6 },
  { id: "neet-biology-reproduction-in-organisms-q08", topicId: "neet-biology-reproduction-in-organisms", text: "Which cell division reduces the chromosome number during gamete formation?", optionA: "Mitosis", optionB: "Meiosis", optionC: "Binary fission", optionD: "Budding", correctOption: "B", explanation: "Meiosis halves the chromosome number, producing haploid gametes.", orderIndex: 7 },
  { id: "neet-biology-reproduction-in-organisms-q09", topicId: "neet-biology-reproduction-in-organisms", text: "The potato reproduces vegetatively through its:", optionA: "Tuber (with eyes/buds)", optionB: "Leaves only", optionC: "Flowers", optionD: "Seeds only", correctOption: "A", explanation: "Potato tubers bear buds ('eyes') that grow into new plants.", orderIndex: 8 },
  { id: "neet-biology-reproduction-in-organisms-q10", topicId: "neet-biology-reproduction-in-organisms", text: "The zygote formed after fertilisation is:", optionA: "Diploid", optionB: "Haploid", optionC: "Triploid", optionD: "Tetraploid", correctOption: "A", explanation: "Fusion of two haploid gametes gives a diploid zygote.", orderIndex: 9 },
  { id: "neet-biology-reproduction-in-organisms-q11", topicId: "neet-biology-reproduction-in-organisms", text: "The life span of an organism is:", optionA: "Independent of body size", optionB: "Always proportional to size", optionC: "The same for all organisms", optionD: "Determined only by colour", correctOption: "A", explanation: "Life span varies widely and is not related to organism size.", orderIndex: 10 },
  { id: "neet-biology-reproduction-in-organisms-q12", topicId: "neet-biology-reproduction-in-organisms", text: "Spore formation as a mode of asexual reproduction is common in:", optionA: "Fungi and some plants", optionB: "Mammals", optionC: "Birds", optionD: "Reptiles", correctOption: "A", explanation: "Many fungi and lower plants reproduce asexually by producing spores.", orderIndex: 11 },

  // ── Biology: Strategies for Enhancement in Food Production ──
  { id: "neet-biology-strategies-food-production-q01", topicId: "neet-biology-strategies-food-production", text: "The management and breeding of livestock is called:", optionA: "Animal husbandry", optionB: "Apiculture", optionC: "Horticulture", optionD: "Sericulture", correctOption: "A", explanation: "Animal husbandry is the scientific rearing and management of livestock.", orderIndex: 0 },
  { id: "neet-biology-strategies-food-production-q02", topicId: "neet-biology-strategies-food-production", text: "Apiculture is the rearing of:", optionA: "Honeybees", optionB: "Fish", optionC: "Silkworms", optionD: "Cattle", correctOption: "A", explanation: "Apiculture is beekeeping for honey and wax.", orderIndex: 1 },
  { id: "neet-biology-strategies-food-production-q03", topicId: "neet-biology-strategies-food-production", text: "Inbreeding, if continued, may reduce fertility and productivity — a phenomenon called:", optionA: "Inbreeding depression", optionB: "Hybrid vigour", optionC: "Heterosis", optionD: "Outbreeding", correctOption: "A", explanation: "Continued inbreeding increases homozygosity, causing inbreeding depression.", orderIndex: 2 },
  { id: "neet-biology-strategies-food-production-q04", topicId: "neet-biology-strategies-food-production", text: "MOET, used to improve cattle rapidly, stands for:", optionA: "Multiple Ovulation Embryo Transfer", optionB: "Male Ova Extraction Technique", optionC: "Mammalian Oocyte Enzyme Test", optionD: "Milk Output Enhancement Treatment", correctOption: "A", explanation: "MOET induces multiple ovulation and transfers embryos to surrogates for faster herd improvement.", orderIndex: 3 },
  { id: "neet-biology-strategies-food-production-q05", topicId: "neet-biology-strategies-food-production", text: "The culture of fish for food is called:", optionA: "Pisciculture", optionB: "Apiculture", optionC: "Sericulture", optionD: "Floriculture", correctOption: "A", explanation: "Pisciculture is fish farming, a form of aquaculture.", orderIndex: 4 },
  { id: "neet-biology-strategies-food-production-q06", topicId: "neet-biology-strategies-food-production", text: "Growing whole plants from small tissue explants in vitro is:", optionA: "Tissue culture (micropropagation)", optionB: "Grafting", optionC: "Layering", optionD: "Budding", correctOption: "A", explanation: "Tissue culture exploits totipotency to grow many plants from small explants.", orderIndex: 5 },
  { id: "neet-biology-strategies-food-production-q07", topicId: "neet-biology-strategies-food-production", text: "The ability of a single plant cell to develop into a whole plant is:", optionA: "Totipotency", optionB: "Pluripotency", optionC: "Senescence", optionD: "Dormancy", correctOption: "A", explanation: "Totipotency is the capacity of a cell to regenerate a complete organism.", orderIndex: 6 },
  { id: "neet-biology-strategies-food-production-q08", topicId: "neet-biology-strategies-food-production", text: "Single-cell protein (SCP) is obtained from microbes such as:", optionA: "Spirulina", optionB: "Wheat", optionC: "Cattle", optionD: "Rice", correctOption: "A", explanation: "SCP from microbes like Spirulina is a protein-rich food/feed supplement.", orderIndex: 7 },
  { id: "neet-biology-strategies-food-production-q09", topicId: "neet-biology-strategies-food-production", text: "Breeding crops for higher vitamin, mineral, or protein content is called:", optionA: "Biofortification", optionB: "Hybridisation only", optionC: "Vernalisation", optionD: "Grafting", correctOption: "A", explanation: "Biofortification improves the nutritional quality of crops through breeding.", orderIndex: 8 },
  { id: "neet-biology-strategies-food-production-q10", topicId: "neet-biology-strategies-food-production", text: "The dramatic rise in food-grain output through high-yielding varieties was the:", optionA: "Green Revolution", optionB: "White Revolution", optionC: "Blue Revolution", optionD: "Industrial Revolution", correctOption: "A", explanation: "The Green Revolution boosted crop yields via improved varieties and practices.", orderIndex: 9 },
  { id: "neet-biology-strategies-food-production-q11", topicId: "neet-biology-strategies-food-production", text: "Somatic hybridisation involves fusing:", optionA: "Protoplasts of two different plant cells", optionB: "Two gametes", optionC: "Two zygotes", optionD: "Sperm and egg", correctOption: "A", explanation: "Somatic hybridisation fuses protoplasts to combine traits without fertilisation.", orderIndex: 10 },
  { id: "neet-biology-strategies-food-production-q12", topicId: "neet-biology-strategies-food-production", text: "Outbreeding (out-crossing/hybridisation) is used mainly to:", optionA: "Introduce desirable variation / hybrid vigour", optionB: "Increase homozygosity", optionC: "Reduce yield", optionD: "Cause inbreeding depression", correctOption: "A", explanation: "Outbreeding introduces new variation and hybrid vigour (heterosis).", orderIndex: 11 },

  // ── Biology: Biodiversity & Conservation ──
  { id: "neet-biology-biodiversity-conservation-q01", topicId: "neet-biology-biodiversity-conservation", text: "Biodiversity is generally highest in:", optionA: "Tropical regions", optionB: "Polar regions", optionC: "Deserts", optionD: "Tundra", correctOption: "A", explanation: "Species diversity is greatest in the tropics and decreases toward the poles.", orderIndex: 0 },
  { id: "neet-biology-biodiversity-conservation-q02", topicId: "neet-biology-biodiversity-conservation", text: "Which is an example of in-situ conservation?", optionA: "National park", optionB: "Zoo", optionC: "Seed bank", optionD: "Botanical garden", correctOption: "A", explanation: "In-situ conservation protects species in their natural habitat (parks, sanctuaries, reserves).", orderIndex: 1 },
  { id: "neet-biology-biodiversity-conservation-q03", topicId: "neet-biology-biodiversity-conservation", text: "Ex-situ conservation includes:", optionA: "Zoos and seed banks", optionB: "National parks", optionC: "Biosphere reserves", optionD: "Sacred groves", correctOption: "A", explanation: "Ex-situ conservation protects species outside their habitat (zoos, gene/seed banks).", orderIndex: 2 },
  { id: "neet-biology-biodiversity-conservation-q04", topicId: "neet-biology-biodiversity-conservation", text: "The single largest cause of biodiversity loss is:", optionA: "Habitat loss and fragmentation", optionB: "Volcanoes", optionC: "Earthquakes", optionD: "Rainfall", correctOption: "A", explanation: "Habitat loss/fragmentation is the leading driver in the 'Evil Quartet'.", orderIndex: 3 },
  { id: "neet-biology-biodiversity-conservation-q05", topicId: "neet-biology-biodiversity-conservation", text: "Areas with very high species richness and high endemism under threat are called:", optionA: "Biodiversity hotspots", optionB: "Deserts", optionC: "Grasslands", optionD: "Estuaries", correctOption: "A", explanation: "Hotspots have exceptional endemic diversity and severe habitat loss, prioritised for conservation.", orderIndex: 4 },
  { id: "neet-biology-biodiversity-conservation-q06", topicId: "neet-biology-biodiversity-conservation", text: "An invasive alien species can cause biodiversity loss by:", optionA: "Out-competing or preying on native species", optionB: "Increasing native populations", optionC: "Adding rainfall", optionD: "Enriching soil only", correctOption: "A", explanation: "Introduced species may outcompete or prey upon natives, causing decline/extinction.", orderIndex: 5 },
  { id: "neet-biology-biodiversity-conservation-q07", topicId: "neet-biology-biodiversity-conservation", text: "The species–area relationship, when plotted, is typically a:", optionA: "Rectangular hyperbola (rising curve)", optionB: "Straight vertical line", optionC: "Downward curve", optionD: "Circle", correctOption: "A", explanation: "Larger areas hold more species, described by a rising rectangular-hyperbola curve.", orderIndex: 6 },
  { id: "neet-biology-biodiversity-conservation-q08", topicId: "neet-biology-biodiversity-conservation", text: "Sacred groves are an example of conservation that is:", optionA: "In-situ (community protected forests)", optionB: "Ex-situ", optionC: "Cryopreservation", optionD: "Seed banking", correctOption: "A", explanation: "Sacred groves are traditionally protected forest patches — a form of in-situ conservation.", orderIndex: 7 },
  { id: "neet-biology-biodiversity-conservation-q09", topicId: "neet-biology-biodiversity-conservation", text: "The three levels at which biodiversity is described are:", optionA: "Genetic, species, and ecological", optionB: "Small, medium, large", optionC: "Land, water, air", optionD: "Plant, animal, microbe only", correctOption: "A", explanation: "Biodiversity spans genetic, species, and ecosystem (ecological) diversity.", orderIndex: 8 },
  { id: "neet-biology-biodiversity-conservation-q10", topicId: "neet-biology-biodiversity-conservation", text: "The disappearance of one species leading to loss of others depending on it is:", optionA: "Co-extinction", optionB: "Speciation", optionC: "Migration", optionD: "Adaptation", correctOption: "A", explanation: "Co-extinction is one of the 'Evil Quartet' — obligate dependents die out with their host/partner.", orderIndex: 9 },
  { id: "neet-biology-biodiversity-conservation-q11", topicId: "neet-biology-biodiversity-conservation", text: "Cryopreservation of gametes/tissues is a technique of:", optionA: "Ex-situ conservation", optionB: "In-situ conservation", optionC: "Habitat restoration", optionD: "Biological control", correctOption: "A", explanation: "Cryopreservation stores germplasm at very low temperatures — an ex-situ method.", orderIndex: 10 },
  { id: "neet-biology-biodiversity-conservation-q12", topicId: "neet-biology-biodiversity-conservation", text: "The 'rivet-popper hypothesis' illustrates the importance of:", optionA: "Every species to ecosystem stability", optionB: "Only large animals", optionC: "Only plants", optionD: "Removing species", correctOption: "A", explanation: "Paul Ehrlich's analogy shows each species (rivet) contributes to ecosystem integrity.", orderIndex: 11 },

  // ── Chemistry: Hydrogen ──
  { id: "neet-chemistry-hydrogen-q01", topicId: "neet-chemistry-hydrogen", text: "The isotope of hydrogen that is radioactive is:", optionA: "Protium", optionB: "Tritium", optionC: "Deuterium", optionD: "None", correctOption: "B", explanation: "Tritium (³H) is the radioactive isotope of hydrogen.", orderIndex: 0 },
  { id: "neet-chemistry-hydrogen-q02", topicId: "neet-chemistry-hydrogen", text: "Hydrogen resembles alkali metals because it can form:", optionA: "H⁺ ions (loses an electron)", optionB: "Only H⁻", optionC: "H₂ only", optionD: "No ions", correctOption: "A", explanation: "Like alkali metals, hydrogen can lose its electron to form H⁺.", orderIndex: 1 },
  { id: "neet-chemistry-hydrogen-q03", topicId: "neet-chemistry-hydrogen", text: "Temporary hardness of water is due to:", optionA: "Bicarbonates of calcium and magnesium", optionB: "Sulphates of calcium", optionC: "Chlorides of sodium", optionD: "Nitrates", correctOption: "A", explanation: "Temporary hardness comes from Ca/Mg bicarbonates, removed by boiling.", orderIndex: 2 },
  { id: "neet-chemistry-hydrogen-q04", topicId: "neet-chemistry-hydrogen", text: "Permanent hardness of water is removed by:", optionA: "Boiling", optionB: "Adding washing soda / ion exchange", optionC: "Filtration", optionD: "Cooling", correctOption: "B", explanation: "Permanent hardness (sulphates/chlorides) is removed chemically, e.g., by washing soda or ion exchange.", orderIndex: 3 },
  { id: "neet-chemistry-hydrogen-q05", topicId: "neet-chemistry-hydrogen", text: "Hydrogen peroxide (H₂O₂) can act as:", optionA: "Both an oxidising and a reducing agent", optionB: "Only an oxidising agent", optionC: "Only a reducing agent", optionD: "Neither", correctOption: "A", explanation: "H₂O₂ functions as both an oxidiser and a reducer depending on conditions.", orderIndex: 4 },
  { id: "neet-chemistry-hydrogen-q06", topicId: "neet-chemistry-hydrogen", text: "Heavy water is chemically:", optionA: "D₂O (deuterium oxide)", optionB: "H₂O₂", optionC: "T₂O", optionD: "H₂O", correctOption: "A", explanation: "Heavy water is deuterium oxide, D₂O, used as a moderator in nuclear reactors.", orderIndex: 5 },
  { id: "neet-chemistry-hydrogen-q07", topicId: "neet-chemistry-hydrogen", text: "Interstitial (metallic) hydrides are formed by hydrogen with:", optionA: "Transition (d-block) metals", optionB: "Noble gases", optionC: "Alkali metals only", optionD: "Halogens", correctOption: "A", explanation: "Many d-block metals form non-stoichiometric interstitial (metallic) hydrides.", orderIndex: 6 },
  { id: "neet-chemistry-hydrogen-q08", topicId: "neet-chemistry-hydrogen", text: "Dihydrogen is used industrially in the Haber process to make:", optionA: "Ammonia", optionB: "Nitric acid directly", optionC: "Sulphuric acid", optionD: "Chlorine", correctOption: "A", explanation: "The Haber process combines N₂ and H₂ to synthesise ammonia.", orderIndex: 7 },
  { id: "neet-chemistry-hydrogen-q09", topicId: "neet-chemistry-hydrogen", text: "Hydrogen resembles halogens because it can:", optionA: "Gain one electron to form H⁻ (hydride)", optionB: "Lose two electrons", optionC: "Form a full d-subshell", optionD: "Never bond", correctOption: "A", explanation: "Like halogens, hydrogen needs one electron for a stable configuration, forming H⁻.", orderIndex: 8 },
  { id: "neet-chemistry-hydrogen-q10", topicId: "neet-chemistry-hydrogen", text: "Hydrogenation of vegetable oils (to make vanaspati) uses hydrogen with a catalyst of:", optionA: "Nickel", optionB: "Sodium", optionC: "Copper only", optionD: "Gold", correctOption: "A", explanation: "Unsaturated oils are hydrogenated over a nickel catalyst to give solid fats.", orderIndex: 9 },
  { id: "neet-chemistry-hydrogen-q11", topicId: "neet-chemistry-hydrogen", text: "The most abundant element in the universe is:", optionA: "Hydrogen", optionB: "Oxygen", optionC: "Helium", optionD: "Carbon", correctOption: "A", explanation: "Hydrogen is the most abundant element in the universe.", orderIndex: 10 },
  { id: "neet-chemistry-hydrogen-q12", topicId: "neet-chemistry-hydrogen", text: "Hydrogen is considered a clean fuel because its combustion mainly produces:", optionA: "Water", optionB: "Carbon dioxide", optionC: "Sulphur dioxide", optionD: "Soot", correctOption: "A", explanation: "Burning hydrogen yields water, making it a clean, non-polluting fuel.", orderIndex: 11 },

  // ── Chemistry: Environmental Chemistry ──
  { id: "neet-chemistry-environmental-chemistry-q01", topicId: "neet-chemistry-environmental-chemistry", text: "Acid rain is mainly caused by oxides of:", optionA: "Sulphur and nitrogen", optionB: "Carbon only", optionC: "Sodium", optionD: "Silicon", correctOption: "A", explanation: "SO₂ and NOx form sulphuric and nitric acids, producing acid rain.", orderIndex: 0 },
  { id: "neet-chemistry-environmental-chemistry-q02", topicId: "neet-chemistry-environmental-chemistry", text: "Photochemical smog is an oxidising smog formed from NOx, hydrocarbons, and:", optionA: "Sunlight", optionB: "Fog only", optionC: "Rain", optionD: "Snow", correctOption: "A", explanation: "Photochemical (Los Angeles) smog forms when sunlight acts on NOx and hydrocarbons.", orderIndex: 1 },
  { id: "neet-chemistry-environmental-chemistry-q03", topicId: "neet-chemistry-environmental-chemistry", text: "Carbon monoxide is poisonous because it binds strongly to:", optionA: "Haemoglobin", optionB: "Water", optionC: "Bone", optionD: "Enzymes only", correctOption: "A", explanation: "CO binds haemoglobin more strongly than O₂, reducing oxygen transport.", orderIndex: 2 },
  { id: "neet-chemistry-environmental-chemistry-q04", topicId: "neet-chemistry-environmental-chemistry", text: "The main greenhouse gas contributing to global warming is:", optionA: "Carbon dioxide", optionB: "Oxygen", optionC: "Nitrogen", optionD: "Argon", correctOption: "A", explanation: "CO₂ is the principal greenhouse gas driving global warming.", orderIndex: 3 },
  { id: "neet-chemistry-environmental-chemistry-q05", topicId: "neet-chemistry-environmental-chemistry", text: "Classical (London) smog is:", optionA: "Reducing (SO₂ + fog)", optionB: "Oxidising", optionC: "Neutral", optionD: "Radioactive", correctOption: "A", explanation: "London smog is a reducing smog of SO₂, soot, and fog.", orderIndex: 4 },
  { id: "neet-chemistry-environmental-chemistry-q06", topicId: "neet-chemistry-environmental-chemistry", text: "Depletion of the stratospheric ozone layer is caused chiefly by:", optionA: "Chlorofluorocarbons (CFCs)", optionB: "Carbon dioxide", optionC: "Oxygen", optionD: "Methane only", correctOption: "A", explanation: "CFCs release chlorine radicals that catalytically destroy ozone.", orderIndex: 5 },
  { id: "neet-chemistry-environmental-chemistry-q07", topicId: "neet-chemistry-environmental-chemistry", text: "High BOD of a water body indicates:", optionA: "High organic pollution", optionB: "Clean water", optionC: "High oxygen", optionD: "Low bacteria", correctOption: "A", explanation: "A high biochemical oxygen demand means more organic waste and greater pollution.", orderIndex: 6 },
  { id: "neet-chemistry-environmental-chemistry-q08", topicId: "neet-chemistry-environmental-chemistry", text: "Green chemistry aims to:", optionA: "Reduce or eliminate hazardous substances in processes", optionB: "Increase pollution", optionC: "Use more toxic solvents", optionD: "Avoid catalysts", correctOption: "A", explanation: "Green chemistry designs safer, less polluting chemical processes.", orderIndex: 7 },
  { id: "neet-chemistry-environmental-chemistry-q09", topicId: "neet-chemistry-environmental-chemistry", text: "Eutrophication of lakes is caused by excess:", optionA: "Nutrients (nitrates and phosphates)", optionB: "Oxygen", optionC: "Acids only", optionD: "Salt", correctOption: "A", explanation: "Nutrient enrichment causes algal blooms, later depleting dissolved oxygen.", orderIndex: 8 },
  { id: "neet-chemistry-environmental-chemistry-q10", topicId: "neet-chemistry-environmental-chemistry", text: "The pH below which rain is considered 'acid rain' is about:", optionA: "5.6", optionB: "7", optionC: "9", optionD: "12", correctOption: "A", explanation: "Rain with pH below ~5.6 (from dissolved acidic oxides) is termed acid rain.", orderIndex: 9 },
  { id: "neet-chemistry-environmental-chemistry-q11", topicId: "neet-chemistry-environmental-chemistry", text: "PAN (peroxyacetyl nitrate), an eye irritant, is a component of:", optionA: "Photochemical smog", optionB: "Classical smog", optionC: "Acid rain", optionD: "Ozone layer", correctOption: "A", explanation: "PAN is produced in photochemical smog and irritates the eyes and lungs.", orderIndex: 10 },
  { id: "neet-chemistry-environmental-chemistry-q12", topicId: "neet-chemistry-environmental-chemistry", text: "Stratospheric ozone is beneficial because it:", optionA: "Absorbs harmful UV radiation", optionB: "Causes global warming", optionC: "Is a pollutant near the ground only", optionD: "Provides oxygen to breathe", correctOption: "A", explanation: "The ozone layer shields the surface from harmful ultraviolet radiation.", orderIndex: 11 },

  // ── Chemistry: p-Block Groups 15–18 ──
  { id: "neet-chemistry-p-block-15-18-q01", topicId: "neet-chemistry-p-block-15-18", text: "The group 15 element that exists as an inert diatomic gas is:", optionA: "Nitrogen", optionB: "Phosphorus", optionC: "Arsenic", optionD: "Bismuth", correctOption: "A", explanation: "Nitrogen exists as N₂ with a very stable triple bond, making it relatively inert.", orderIndex: 0 },
  { id: "neet-chemistry-p-block-15-18-q02", topicId: "neet-chemistry-p-block-15-18", text: "Ammonia is manufactured by the:", optionA: "Haber process", optionB: "Contact process", optionC: "Ostwald process", optionD: "Hall–Héroult process", correctOption: "A", explanation: "The Haber process synthesises NH₃ from N₂ and H₂ at high pressure with an iron catalyst.", orderIndex: 1 },
  { id: "neet-chemistry-p-block-15-18-q03", topicId: "neet-chemistry-p-block-15-18", text: "Sulphuric acid is manufactured by the:", optionA: "Contact process", optionB: "Haber process", optionC: "Ostwald process", optionD: "Solvay process", correctOption: "A", explanation: "The Contact process produces H₂SO₄ via SO₂ → SO₃ over a V₂O₅ catalyst.", orderIndex: 2 },
  { id: "neet-chemistry-p-block-15-18-q04", topicId: "neet-chemistry-p-block-15-18", text: "Nitric acid is produced industrially by the:", optionA: "Ostwald process", optionB: "Contact process", optionC: "Haber process", optionD: "Hall process", correctOption: "A", explanation: "The Ostwald process oxidises ammonia to nitric acid.", orderIndex: 3 },
  { id: "neet-chemistry-p-block-15-18-q05", topicId: "neet-chemistry-p-block-15-18", text: "Among halogens, the strongest oxidising agent is:", optionA: "Fluorine", optionB: "Iodine", optionC: "Bromine", optionD: "Chlorine", correctOption: "A", explanation: "Fluorine is the strongest oxidising agent among the halogens.", orderIndex: 4 },
  { id: "neet-chemistry-p-block-15-18-q06", topicId: "neet-chemistry-p-block-15-18", text: "The noble gas that forms fluorides such as XeF₂ and XeF₄ is:", optionA: "Xenon", optionB: "Helium", optionC: "Neon", optionD: "Argon", correctOption: "A", explanation: "Xenon, being large and polarisable, forms fluorides with fluorine.", orderIndex: 5 },
  { id: "neet-chemistry-p-block-15-18-q07", topicId: "neet-chemistry-p-block-15-18", text: "HF is a weaker acid than HCl mainly because of:", optionA: "Strong hydrogen bonding in HF", optionB: "Its large size", optionC: "Its low electronegativity", optionD: "Its metallic nature", correctOption: "A", explanation: "Strong H-bonding and the strong H–F bond make HF the weakest hydrohalic acid.", orderIndex: 6 },
  { id: "neet-chemistry-p-block-15-18-q08", topicId: "neet-chemistry-p-block-15-18", text: "Group 16 elements are collectively called the:", optionA: "Chalcogens", optionB: "Pnictogens", optionC: "Halogens", optionD: "Noble gases", correctOption: "A", explanation: "Group 16 (O, S, Se, Te) are the chalcogens (ore-forming elements).", orderIndex: 7 },
  { id: "neet-chemistry-p-block-15-18-q09", topicId: "neet-chemistry-p-block-15-18", text: "Down group 17, the oxidising power of the halogens:", optionA: "Decreases", optionB: "Increases", optionC: "Stays constant", optionD: "Becomes zero", correctOption: "A", explanation: "Oxidising power decreases down the group (F₂ strongest, I₂ weakest).", orderIndex: 8 },
  { id: "neet-chemistry-p-block-15-18-q10", topicId: "neet-chemistry-p-block-15-18", text: "The maximum oxidation state shown by nitrogen is:", optionA: "+5", optionB: "+3", optionC: "+7", optionD: "+2", correctOption: "A", explanation: "Nitrogen shows a maximum oxidation state of +5 (e.g., in HNO₃).", orderIndex: 9 },
  { id: "neet-chemistry-p-block-15-18-q11", topicId: "neet-chemistry-p-block-15-18", text: "Noble gases are largely unreactive because they have:", optionA: "A completely filled valence shell", optionB: "One valence electron", optionC: "High reactivity", optionD: "Unpaired electrons", correctOption: "A", explanation: "A full octet gives noble gases very high stability and low reactivity.", orderIndex: 10 },
  { id: "neet-chemistry-p-block-15-18-q12", topicId: "neet-chemistry-p-block-15-18", text: "Compounds formed between two different halogens are called:", optionA: "Interhalogens", optionB: "Hydrides", optionC: "Oxides", optionD: "Amines", correctOption: "A", explanation: "Interhalogen compounds (e.g., ClF₃, ICl) form between two different halogens.", orderIndex: 11 },

  // ── Physics: Alternating Current ──
  { id: "neet-physics-alternating-current-q01", topicId: "neet-physics-alternating-current", text: "The RMS value of an alternating current with peak I₀ is:", optionA: "I₀/√2", optionB: "I₀√2", optionC: "I₀", optionD: "2I₀", correctOption: "A", explanation: "For sinusoidal AC, I_rms = I₀/√2 ≈ 0.707 I₀.", orderIndex: 0 },
  { id: "neet-physics-alternating-current-q02", topicId: "neet-physics-alternating-current", text: "The inductive reactance X_L is given by:", optionA: "ωL", optionB: "1/ωL", optionC: "ωC", optionD: "1/ωC", correctOption: "A", explanation: "Inductive reactance X_L = ωL, increasing with frequency.", orderIndex: 1 },
  { id: "neet-physics-alternating-current-q03", topicId: "neet-physics-alternating-current", text: "The capacitive reactance X_C is given by:", optionA: "1/ωC", optionB: "ωC", optionC: "ωL", optionD: "1/ωL", correctOption: "A", explanation: "Capacitive reactance X_C = 1/ωC, decreasing with frequency.", orderIndex: 2 },
  { id: "neet-physics-alternating-current-q04", topicId: "neet-physics-alternating-current", text: "In a purely inductive AC circuit, the current:", optionA: "Lags the voltage by 90°", optionB: "Leads by 90°", optionC: "Is in phase", optionD: "Is zero", correctOption: "A", explanation: "In a pure inductor, current lags the voltage by a quarter cycle (90°).", orderIndex: 3 },
  { id: "neet-physics-alternating-current-q05", topicId: "neet-physics-alternating-current", text: "In a purely capacitive AC circuit, the current:", optionA: "Leads the voltage by 90°", optionB: "Lags by 90°", optionC: "Is in phase", optionD: "Is constant", correctOption: "A", explanation: "In a pure capacitor, current leads the voltage by 90°.", orderIndex: 4 },
  { id: "neet-physics-alternating-current-q06", topicId: "neet-physics-alternating-current", text: "Series LCR resonance occurs when:", optionA: "X_L = X_C", optionB: "X_L = 0", optionC: "R = 0", optionD: "X_C = 2X_L", correctOption: "A", explanation: "At resonance the reactances cancel (X_L = X_C), leaving impedance = R.", orderIndex: 5 },
  { id: "neet-physics-alternating-current-q07", topicId: "neet-physics-alternating-current", text: "At resonance in a series LCR circuit, the current is:", optionA: "Maximum", optionB: "Zero", optionC: "Minimum", optionD: "Negative", correctOption: "A", explanation: "Minimum impedance at resonance gives maximum current.", orderIndex: 6 },
  { id: "neet-physics-alternating-current-q08", topicId: "neet-physics-alternating-current", text: "The impedance of a series LCR circuit is:", optionA: "√(R² + (X_L − X_C)²)", optionB: "R + X_L + X_C", optionC: "R × X_L", optionD: "X_L − X_C only", correctOption: "A", explanation: "Impedance Z = √(R² + (X_L − X_C)²).", orderIndex: 7 },
  { id: "neet-physics-alternating-current-q09", topicId: "neet-physics-alternating-current", text: "The average power in an AC circuit is:", optionA: "V_rms·I_rms·cosφ", optionB: "V_rms·I_rms only", optionC: "V₀I₀", optionD: "Zero always", correctOption: "A", explanation: "Average power = V_rms·I_rms·cosφ, where cosφ is the power factor.", orderIndex: 8 },
  { id: "neet-physics-alternating-current-q10", topicId: "neet-physics-alternating-current", text: "The term cosφ in AC power is called the:", optionA: "Power factor", optionB: "Impedance", optionC: "Reactance", optionD: "Resonance", correctOption: "A", explanation: "cosφ is the power factor, the ratio of real to apparent power.", orderIndex: 9 },
  { id: "neet-physics-alternating-current-q11", topicId: "neet-physics-alternating-current", text: "The resonant frequency of a series LCR circuit is:", optionA: "1/(2π√(LC))", optionB: "2π√(LC)", optionC: "1/(2πLC)", optionD: "√(LC)", correctOption: "A", explanation: "Resonance occurs at f = 1/(2π√(LC)).", orderIndex: 10 },
  { id: "neet-physics-alternating-current-q12", topicId: "neet-physics-alternating-current", text: "A transformer changes AC voltage using the principle of:", optionA: "Mutual induction", optionB: "Self-induction only", optionC: "Electrostatics", optionD: "Resistance", correctOption: "A", explanation: "A transformer transfers energy between coils by mutual induction (V_s/V_p = N_s/N_p).", orderIndex: 11 }
];
