// NEET Physics expansion. Tops up every existing Physics reading from 8 to 12
// questions and adds the major missing NCERT chapters, each with a study
// material and 12 questions. Ids namespaced neet-physics-*.
import type { AuthoredMaterial } from "./builder";
import type { Question, Topic } from "@jyotir/core";

export const phyTopics: Topic[] = [
  { id: "neet-physics-units-measurements", subjectId: "neet-physics", name: "Units, Measurements & Errors", slug: "units-measurements", orderIndex: 13 },
  { id: "neet-physics-motion-in-a-plane", subjectId: "neet-physics", name: "Motion in a Plane & Projectiles", slug: "motion-in-a-plane", orderIndex: 14 },
  { id: "neet-physics-rotational-motion", subjectId: "neet-physics", name: "System of Particles & Rotational Motion", slug: "rotational-motion", orderIndex: 15 },
  { id: "neet-physics-mechanical-properties-solids", subjectId: "neet-physics", name: "Mechanical Properties of Solids", slug: "mechanical-properties-solids", orderIndex: 16 },
  { id: "neet-physics-mechanical-properties-fluids", subjectId: "neet-physics", name: "Mechanical Properties of Fluids", slug: "mechanical-properties-fluids", orderIndex: 17 },
  { id: "neet-physics-thermal-properties-matter", subjectId: "neet-physics", name: "Thermal Properties of Matter", slug: "thermal-properties-matter", orderIndex: 18 },
  { id: "neet-physics-kinetic-theory", subjectId: "neet-physics", name: "Kinetic Theory of Gases", slug: "kinetic-theory", orderIndex: 19 },
  { id: "neet-physics-wave-optics", subjectId: "neet-physics", name: "Wave Optics", slug: "wave-optics", orderIndex: 20 },
  { id: "neet-physics-magnetism-matter", subjectId: "neet-physics", name: "Magnetism & Matter", slug: "magnetism-matter", orderIndex: 21 },
  { id: "neet-physics-electromagnetic-waves", subjectId: "neet-physics", name: "Electromagnetic Waves", slug: "electromagnetic-waves", orderIndex: 22 },
  { id: "neet-physics-atoms", subjectId: "neet-physics", name: "Atoms & Bohr Model", slug: "atoms", orderIndex: 23 },
  { id: "neet-physics-nuclei", subjectId: "neet-physics", name: "Nuclei & Radioactivity", slug: "nuclei", orderIndex: 24 }
];

export const phyMaterials: AuthoredMaterial[] = [
  { id: "neet-physics-units-measurements-m01", topicId: "neet-physics-units-measurements", title: "Units, Measurements & Errors", content: `Physical quantities are expressed in the **SI system** with seven base units (metre, kilogram, second, ampere, kelvin, mole, candela). **Dimensional analysis** checks equation consistency and derives relations — only terms with the same dimensions can be added. **Errors**: absolute, relative, and percentage. When quantities are **multiplied/divided, relative errors add**; when **added/subtracted, absolute errors add**. **Significant figures** convey precision. **Accuracy** is closeness to the true value; **precision** is reproducibility. Least count is the smallest measurable value of an instrument.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "neet-physics-motion-in-a-plane-m01", topicId: "neet-physics-motion-in-a-plane", title: "Motion in a Plane & Projectiles", content: `Two-dimensional motion is analysed by resolving vectors into **independent x and y components**. For a **projectile** launched at speed u and angle θ: horizontal velocity u cosθ is constant, vertical motion is under gravity. Key results: **time of flight T = 2u sinθ/g**, **maximum height H = u²sin²θ/2g**, and **range R = u²sin2θ/g** (maximum at θ = 45°). The trajectory is a **parabola**. In **uniform circular motion**, speed is constant but velocity changes direction, requiring a **centripetal acceleration a = v²/r** directed toward the centre.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "neet-physics-rotational-motion-m01", topicId: "neet-physics-rotational-motion", title: "System of Particles & Rotational Motion", content: `The **centre of mass** moves under the net external force as if all mass were concentrated there. **Torque** τ = r × F, and **τ = Iα** is the rotational Newton's second law. **Moment of inertia** I depends on mass distribution (solid sphere 2/5 MR², disc ½ MR², ring MR²); use the **parallel-axis theorem** I = I_cm + Md². **Angular momentum** L = Iω is conserved when net torque is zero. For **rolling without slipping**, v = ωR and total KE = ½mv² + ½Iω². Rotational kinematics mirror linear ones with θ, ω, α.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "neet-physics-mechanical-properties-solids-m01", topicId: "neet-physics-mechanical-properties-solids", title: "Mechanical Properties of Solids", content: `**Stress** = force/area; **strain** = fractional deformation (dimensionless). **Hooke's law**: within the elastic limit, stress ∝ strain, the constant being a **modulus of elasticity**. **Young's modulus** (Y = longitudinal stress/strain) measures resistance to length change; **bulk modulus** to volume change; **shear (rigidity) modulus** to shape change. The **stress–strain curve** shows the elastic region, yield point, and fracture point. **Elastic potential energy** per unit volume = ½ × stress × strain. A material with higher Young's modulus is stiffer.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "neet-physics-mechanical-properties-fluids-m01", topicId: "neet-physics-mechanical-properties-fluids", title: "Mechanical Properties of Fluids", content: `**Pressure** in a fluid at depth h is P = P₀ + ρgh. **Pascal's law**: pressure applied to an enclosed fluid is transmitted equally (basis of hydraulic lifts). **Archimedes' principle**: buoyant force = weight of displaced fluid. **Bernoulli's theorem** (energy conservation): P + ½ρv² + ρgh = constant along a streamline — higher speed means lower pressure. **Continuity equation**: Av = constant. **Viscosity** resists relative flow; **Stokes' law** F = 6πηrv governs a sphere's terminal velocity. **Surface tension** minimises surface area, causing capillary rise.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "neet-physics-thermal-properties-matter-m01", topicId: "neet-physics-thermal-properties-matter", title: "Thermal Properties of Matter", content: `**Thermal expansion**: linear (α), area (β = 2α), and volume (γ = 3α) coefficients. **Heat capacity** Q = mcΔT; **latent heat** Q = mL applies at phase changes (no temperature change). Heat transfers by **conduction** (through solids, rate ∝ kAΔT/L), **convection** (fluid movement), and **radiation** (electromagnetic waves, needs no medium). **Stefan–Boltzmann law**: radiated power ∝ T⁴. **Newton's law of cooling**: rate of cooling ∝ temperature difference with surroundings. **Wien's law**: peak wavelength ∝ 1/T. A black body is a perfect absorber and emitter.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "neet-physics-kinetic-theory-m01", topicId: "neet-physics-kinetic-theory", title: "Kinetic Theory of Gases", content: `Gases consist of many molecules in random motion; pressure results from their collisions. The pressure relation is **P = (1/3)(mn/V)v̄² = (1/3)ρv̄²**. **Average kinetic energy per molecule = (3/2)kT**, so temperature measures molecular KE. Molecular speeds: **v_rms = √(3RT/M) > v_avg > v_mp**. **Equipartition theorem**: each degree of freedom carries ½kT. Degrees of freedom give **γ = 5/3 (monatomic), 7/5 (diatomic)**. **Mean free path** is the average distance between collisions; it decreases with pressure and molecular size.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "neet-physics-wave-optics-m01", topicId: "neet-physics-wave-optics", title: "Wave Optics", content: `Light behaves as a wave, explaining interference and diffraction. **Huygens' principle** treats each wavefront point as a secondary source. In **Young's double-slit**, fringe width **β = λD/d**; bright fringes at path difference nλ, dark at (n+½)λ. **Coherent sources** are needed for a stable pattern. **Single-slit diffraction** gives a central maximum with the first minimum at a sinθ = λ. **Polarisation** (transverse waves only) is described by **Malus's law** I = I₀cos²θ. **Brewster's law**: tan θ_p = μ gives complete polarisation on reflection. Resolving power increases with aperture.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "neet-physics-magnetism-matter-m01", topicId: "neet-physics-magnetism-matter", title: "Magnetism & Matter", content: `A **magnetic dipole** (bar magnet) has a moment m; torque in a field τ = m × B. The Earth acts like a magnet with **declination, dip (inclination), and horizontal component**. Materials are classified by their response: **diamagnetic** (weakly repelled, χ small negative), **paramagnetic** (weakly attracted, χ small positive, obeys Curie's law χ ∝ 1/T), and **ferromagnetic** (strongly attracted, form domains, show hysteresis; lose magnetism above the Curie temperature). **Magnetic susceptibility (χ)** and **permeability (μ)** quantify a material's magnetic behaviour. Soft iron (narrow hysteresis loop) suits electromagnets; steel (wide loop) suits permanent magnets.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "neet-physics-electromagnetic-waves-m01", topicId: "neet-physics-electromagnetic-waves", title: "Electromagnetic Waves", content: `EM waves are **self-propagating oscillating electric and magnetic fields**, mutually perpendicular and perpendicular to the direction of propagation (**transverse**). They travel in vacuum at **c = 3 × 10⁸ m/s = 1/√(μ₀ε₀)** and need **no medium**. They carry energy and momentum. The **EM spectrum** in order of increasing frequency: radio → microwave → infrared → visible → ultraviolet → X-rays → gamma rays. Each region has characteristic uses (radio — communication; microwave — radar/ovens; IR — heating; UV — sterilisation; X-rays — imaging; gamma — cancer therapy). Maxwell predicted them; Hertz demonstrated them.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "neet-physics-atoms-m01", topicId: "neet-physics-atoms", title: "Atoms & the Bohr Model", content: `**Rutherford's** α-scattering experiment revealed a tiny, dense, positive nucleus. **Bohr's model** postulates: electrons occupy **stationary orbits** with quantised angular momentum (mvr = nh/2π); they radiate only when jumping between levels (E = hν). For hydrogen, **Eₙ = −13.6/n² eV**, with n = 1 the ground state. Spectral series (**Lyman — UV, Balmer — visible, Paschen — IR**) arise from transitions to a given level. The **Rydberg formula** gives 1/λ = R(1/n₁² − 1/n₂²). The model explains the hydrogen spectrum but fails for multi-electron atoms.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "neet-physics-nuclei-m01", topicId: "neet-physics-nuclei", title: "Nuclei & Radioactivity", content: `The nucleus contains protons and neutrons (**nucleons**); its radius R = R₀A^(1/3), so nuclear density is nearly constant. **Mass defect** (Δm) converts to **binding energy** E = Δmc²; **binding energy per nucleon** peaks near iron, driving **fusion** (light nuclei) and **fission** (heavy nuclei). **Radioactive decay** is exponential: N = N₀e^(−λt), half-life t½ = 0.693/λ. Emissions: **alpha** (He nucleus), **beta** (electron/positron), and **gamma** (high-energy photons). Nuclear reactors use controlled fission with moderators and control rods; the Sun is powered by fusion.`, estimatedReadTime: 2, orderIndex: 0 }
];

export const phyQuestions: Question[] = [
  // ── Top-ups (q09–q12) ──
  // Ray Optics
  { id: "neet-physics-ray-optics-q09", topicId: "neet-physics-ray-optics", text: "The power of a lens is measured in:", optionA: "Watt", optionB: "Dioptre", optionC: "Newton", optionD: "Joule", correctOption: "B", explanation: "Lens power (P = 1/f in metres) is measured in dioptres (D).", orderIndex: 8 },
  { id: "neet-physics-ray-optics-q10", topicId: "neet-physics-ray-optics", text: "For a concave mirror, a real image is formed when the object is:", optionA: "Between the pole and focus", optionB: "Beyond the focus", optionC: "At the focus", optionD: "At infinity only", correctOption: "B", explanation: "A concave mirror forms a real image when the object lies beyond the focal point.", orderIndex: 9 },
  { id: "neet-physics-ray-optics-q11", topicId: "neet-physics-ray-optics", text: "Total internal reflection occurs when light travels from a denser to a rarer medium and the angle of incidence:", optionA: "Exceeds the critical angle", optionB: "Is zero", optionC: "Is less than the critical angle", optionD: "Equals 90°", correctOption: "A", explanation: "Beyond the critical angle, light is totally internally reflected (basis of optical fibres).", orderIndex: 10 },
  { id: "neet-physics-ray-optics-q12", topicId: "neet-physics-ray-optics", text: "The refractive index of a medium is defined as:", optionA: "Speed of light in vacuum / speed in the medium", optionB: "Speed in medium / speed in vacuum", optionC: "Frequency ratio", optionD: "Wavelength product", correctOption: "A", explanation: "μ = c/v: the ratio of light's speed in vacuum to its speed in the medium.", orderIndex: 11 },
  // Kinematics
  { id: "neet-physics-kinematics-q09", topicId: "neet-physics-kinematics", text: "For uniformly accelerated motion, v = u + at is which equation of motion?", optionA: "First", optionB: "Second", optionC: "Third", optionD: "Fourth", correctOption: "A", explanation: "v = u + at is the first equation of motion relating velocity, acceleration, and time.", orderIndex: 8 },
  { id: "neet-physics-kinematics-q10", topicId: "neet-physics-kinematics", text: "The area under a velocity–time graph gives:", optionA: "Acceleration", optionB: "Displacement", optionC: "Force", optionD: "Jerk", correctOption: "B", explanation: "The area under a v–t graph equals the displacement of the object.", orderIndex: 9 },
  { id: "neet-physics-kinematics-q11", topicId: "neet-physics-kinematics", text: "The slope of a velocity–time graph represents:", optionA: "Displacement", optionB: "Acceleration", optionC: "Speed", optionD: "Distance", correctOption: "B", explanation: "The slope (rate of change of velocity) of a v–t graph is the acceleration.", orderIndex: 10 },
  { id: "neet-physics-kinematics-q12", topicId: "neet-physics-kinematics", text: "A body thrown vertically upward has, at its highest point, a velocity of:", optionA: "Maximum", optionB: "Zero (acceleration g downward)", optionC: "Equal to g", optionD: "Infinite", correctOption: "B", explanation: "At the top, velocity is momentarily zero while acceleration remains g downward.", orderIndex: 11 },
  // Laws of Motion
  { id: "neet-physics-laws-of-motion-q09", topicId: "neet-physics-laws-of-motion", text: "Newton's second law expresses force as:", optionA: "F = ma (rate of change of momentum)", optionB: "F = mv", optionC: "F = m/a", optionD: "F = a/m", correctOption: "A", explanation: "Force equals the rate of change of momentum, F = ma for constant mass.", orderIndex: 8 },
  { id: "neet-physics-laws-of-motion-q10", topicId: "neet-physics-laws-of-motion", text: "Newton's third law states that action and reaction are:", optionA: "Equal and in the same direction", optionB: "Equal and opposite, on different bodies", optionC: "Unequal", optionD: "On the same body", correctOption: "B", explanation: "Every action has an equal and opposite reaction, acting on different bodies.", orderIndex: 9 },
  { id: "neet-physics-laws-of-motion-q11", topicId: "neet-physics-laws-of-motion", text: "The principle of conservation of linear momentum follows from:", optionA: "Newton's first law", optionB: "Newton's third law (and no external force)", optionC: "Hooke's law", optionD: "Ohm's law", correctOption: "B", explanation: "With no external force, momentum is conserved — a consequence of the third law.", orderIndex: 10 },
  { id: "neet-physics-laws-of-motion-q12", topicId: "neet-physics-laws-of-motion", text: "The maximum static friction before sliding is:", optionA: "μ_s N", optionB: "μ_k N only", optionC: "Zero", optionD: "mg always", correctOption: "A", explanation: "Limiting static friction equals μ_s N, usually greater than kinetic friction μ_k N.", orderIndex: 11 },
  // Work, Energy & Power
  { id: "neet-physics-work-energy-power-q09", topicId: "neet-physics-work-energy-power", text: "The work–energy theorem states that net work done equals the change in:", optionA: "Potential energy", optionB: "Kinetic energy", optionC: "Momentum", optionD: "Power", correctOption: "B", explanation: "Net work done on a body equals its change in kinetic energy.", orderIndex: 8 },
  { id: "neet-physics-work-energy-power-q10", topicId: "neet-physics-work-energy-power", text: "The SI unit of power is the:", optionA: "Joule", optionB: "Watt", optionC: "Newton", optionD: "Pascal", correctOption: "B", explanation: "Power (rate of doing work) is measured in watts (1 W = 1 J/s).", orderIndex: 9 },
  { id: "neet-physics-work-energy-power-q11", topicId: "neet-physics-work-energy-power", text: "In an elastic collision, the quantity that is conserved besides momentum is:", optionA: "Kinetic energy", optionB: "Temperature", optionC: "Charge", optionD: "Volume", correctOption: "A", explanation: "Elastic collisions conserve both momentum and kinetic energy.", orderIndex: 10 },
  { id: "neet-physics-work-energy-power-q12", topicId: "neet-physics-work-energy-power", text: "The work done by a force perpendicular to the displacement is:", optionA: "Maximum", optionB: "Zero", optionC: "Negative", optionD: "Equal to the force", correctOption: "B", explanation: "Work = Fd cosθ; at θ = 90°, cosθ = 0, so the work is zero.", orderIndex: 11 },
  // Gravitation
  { id: "neet-physics-gravitation-q09", topicId: "neet-physics-gravitation", text: "Newton's law of gravitation states that the force between two masses is proportional to:", optionA: "The product of the masses and inversely to the square of the distance", optionB: "The sum of masses", optionC: "The distance", optionD: "The cube of the distance", correctOption: "A", explanation: "F = Gm₁m₂/r², proportional to the masses' product and inverse-square in distance.", orderIndex: 8 },
  { id: "neet-physics-gravitation-q10", topicId: "neet-physics-gravitation", text: "The acceleration due to gravity g at the Earth's centre is:", optionA: "Maximum", optionB: "Zero", optionC: "9.8 m/s²", optionD: "Infinite", correctOption: "B", explanation: "At the centre, the net gravitational field (and g) is zero.", orderIndex: 9 },
  { id: "neet-physics-gravitation-q11", topicId: "neet-physics-gravitation", text: "The escape velocity from the Earth's surface is approximately:", optionA: "11.2 km/s", optionB: "7.9 km/s", optionC: "3 × 10⁸ m/s", optionD: "1 km/s", correctOption: "A", explanation: "Escape velocity from Earth is about 11.2 km/s.", orderIndex: 10 },
  { id: "neet-physics-gravitation-q12", topicId: "neet-physics-gravitation", text: "A geostationary satellite has an orbital period of:", optionA: "24 hours", optionB: "1 hour", optionC: "12 hours", optionD: "1 month", correctOption: "A", explanation: "A geostationary satellite orbits with a 24-hour period, matching Earth's rotation.", orderIndex: 11 },
  // Thermodynamics (physics)
  { id: "neet-physics-thermodynamics-q09", topicId: "neet-physics-thermodynamics", text: "The first law of thermodynamics is written as:", optionA: "ΔU = Q − W", optionB: "Q = ΔU × W", optionC: "W = QΔU", optionD: "ΔU = QW", correctOption: "A", explanation: "First law: change in internal energy equals heat added minus work done by the system.", orderIndex: 8 },
  { id: "neet-physics-thermodynamics-q10", topicId: "neet-physics-thermodynamics", text: "In an isothermal process, the temperature:", optionA: "Increases", optionB: "Remains constant", optionC: "Decreases", optionD: "Becomes zero", correctOption: "B", explanation: "An isothermal process occurs at constant temperature.", orderIndex: 9 },
  { id: "neet-physics-thermodynamics-q11", topicId: "neet-physics-thermodynamics", text: "The efficiency of a Carnot engine depends only on the:", optionA: "Working substance", optionB: "Temperatures of the two reservoirs", optionC: "Pressure", optionD: "Volume", correctOption: "B", explanation: "Carnot efficiency η = 1 − T_c/T_h depends only on the reservoir temperatures.", orderIndex: 10 },
  { id: "neet-physics-thermodynamics-q12", topicId: "neet-physics-thermodynamics", text: "The second law of thermodynamics implies that the entropy of an isolated system:", optionA: "Always decreases", optionB: "Never decreases", optionC: "Is constant", optionD: "Is zero", correctOption: "B", explanation: "Entropy of an isolated system never decreases (it stays constant or increases).", orderIndex: 11 },
  // Oscillations & Waves
  { id: "neet-physics-oscillations-waves-q09", topicId: "neet-physics-oscillations-waves", text: "The time period of a simple pendulum depends on:", optionA: "Its mass", optionB: "Its length and g", optionC: "The amplitude only", optionD: "The material", correctOption: "B", explanation: "T = 2π√(L/g); the period depends on length and gravitational acceleration, not mass.", orderIndex: 8 },
  { id: "neet-physics-oscillations-waves-q10", topicId: "neet-physics-oscillations-waves", text: "In SHM, the total energy is proportional to the square of the:", optionA: "Amplitude", optionB: "Mass", optionC: "Time", optionD: "Phase", correctOption: "A", explanation: "Total energy E = ½mω²A² ∝ amplitude².", orderIndex: 9 },
  { id: "neet-physics-oscillations-waves-q11", topicId: "neet-physics-oscillations-waves", text: "The speed of a wave is related to frequency and wavelength by:", optionA: "v = fλ", optionB: "v = f/λ", optionC: "v = λ/f", optionD: "v = f + λ", correctOption: "A", explanation: "Wave speed v = frequency × wavelength = fλ.", orderIndex: 10 },
  { id: "neet-physics-oscillations-waves-q12", topicId: "neet-physics-oscillations-waves", text: "Sound waves are:", optionA: "Transverse", optionB: "Longitudinal", optionC: "Electromagnetic", optionD: "Stationary only", correctOption: "B", explanation: "Sound propagates as longitudinal (compression) waves requiring a medium.", orderIndex: 11 },
  // Electrostatics
  { id: "neet-physics-electrostatics-q09", topicId: "neet-physics-electrostatics", text: "Coulomb's law states that the force between two point charges is proportional to:", optionA: "The product of charges / (distance)²", optionB: "The sum of charges", optionC: "The distance", optionD: "1/charge", correctOption: "A", explanation: "F = kq₁q₂/r²: proportional to the product of charges and inverse-square in distance.", orderIndex: 8 },
  { id: "neet-physics-electrostatics-q10", topicId: "neet-physics-electrostatics", text: "The electric field inside a hollow charged conductor is:", optionA: "Maximum", optionB: "Zero", optionC: "Uniform and nonzero", optionD: "Infinite", correctOption: "B", explanation: "The field inside a conductor in electrostatic equilibrium is zero.", orderIndex: 9 },
  { id: "neet-physics-electrostatics-q11", topicId: "neet-physics-electrostatics", text: "The capacitance of a parallel-plate capacitor increases when a dielectric is inserted because the dielectric:", optionA: "Reduces the field, storing more charge for the same voltage", optionB: "Increases the plate distance", optionC: "Removes charge", optionD: "Has no effect", correctOption: "A", explanation: "A dielectric of constant K increases capacitance by factor K (C = Kε₀A/d).", orderIndex: 10 },
  { id: "neet-physics-electrostatics-q12", topicId: "neet-physics-electrostatics", text: "The energy stored in a capacitor is:", optionA: "½CV²", optionB: "CV", optionC: "½C²V", optionD: "CV²", correctOption: "A", explanation: "Energy stored = ½CV² = ½QV = Q²/2C.", orderIndex: 11 },
  // Current Electricity
  { id: "neet-physics-current-electricity-q09", topicId: "neet-physics-current-electricity", text: "Ohm's law states that voltage equals:", optionA: "IR (current × resistance)", optionB: "I/R", optionC: "I + R", optionD: "R/I", correctOption: "A", explanation: "Ohm's law: V = IR, where R is the resistance.", orderIndex: 8 },
  { id: "neet-physics-current-electricity-q10", topicId: "neet-physics-current-electricity", text: "Resistances in series combine as:", optionA: "R = R₁ + R₂ + …", optionB: "1/R = 1/R₁ + 1/R₂", optionC: "R = R₁R₂", optionD: "R = R₁ − R₂", correctOption: "A", explanation: "In series, total resistance is the sum of individual resistances.", orderIndex: 9 },
  { id: "neet-physics-current-electricity-q11", topicId: "neet-physics-current-electricity", text: "The power dissipated in a resistor is:", optionA: "I²R", optionB: "IR only", optionC: "I/R", optionD: "R/I²", correctOption: "A", explanation: "Power P = I²R = V²/R = VI (Joule heating).", orderIndex: 10 },
  { id: "neet-physics-current-electricity-q12", topicId: "neet-physics-current-electricity", text: "Kirchhoff's junction (current) rule is based on conservation of:", optionA: "Energy", optionB: "Charge", optionC: "Momentum", optionD: "Mass", correctOption: "B", explanation: "The junction rule (sum of currents in = out) expresses conservation of charge.", orderIndex: 11 },
  // Moving Charges & Magnetism
  { id: "neet-physics-moving-charges-magnetism-q09", topicId: "neet-physics-moving-charges-magnetism", text: "The force on a charge q moving with velocity v in a magnetic field B is:", optionA: "qv × B", optionB: "qB/v", optionC: "q/vB", optionD: "qvB parallel to v", correctOption: "A", explanation: "The magnetic (Lorentz) force is F = qv × B, perpendicular to both v and B.", orderIndex: 8 },
  { id: "neet-physics-moving-charges-magnetism-q10", topicId: "neet-physics-moving-charges-magnetism", text: "A charged particle moving parallel to a magnetic field experiences a force that is:", optionA: "Maximum", optionB: "Zero", optionC: "Perpendicular", optionD: "Equal to qE", correctOption: "B", explanation: "When v is parallel to B, the angle is 0 and F = qvB sin0 = 0.", orderIndex: 9 },
  { id: "neet-physics-moving-charges-magnetism-q11", topicId: "neet-physics-moving-charges-magnetism", text: "The magnetic field inside a long solenoid is:", optionA: "Uniform and along the axis", optionB: "Zero", optionC: "Radial", optionD: "Maximum at the ends", correctOption: "A", explanation: "A long solenoid has a nearly uniform axial field B = μ₀nI inside.", orderIndex: 10 },
  { id: "neet-physics-moving-charges-magnetism-q12", topicId: "neet-physics-moving-charges-magnetism", text: "A device that measures small currents using a coil in a magnetic field is a:", optionA: "Galvanometer", optionB: "Voltmeter only", optionC: "Transformer", optionD: "Capacitor", correctOption: "A", explanation: "A moving-coil galvanometer detects and measures small currents via torque on a coil.", orderIndex: 11 },
  // Electromagnetic Induction & AC
  { id: "neet-physics-electromagnetic-induction-ac-q09", topicId: "neet-physics-electromagnetic-induction-ac", text: "Faraday's law states that the induced EMF equals the rate of change of:", optionA: "Charge", optionB: "Magnetic flux", optionC: "Current only", optionD: "Resistance", correctOption: "B", explanation: "Induced EMF = −dΦ/dt, the negative rate of change of magnetic flux.", orderIndex: 8 },
  { id: "neet-physics-electromagnetic-induction-ac-q10", topicId: "neet-physics-electromagnetic-induction-ac", text: "Lenz's law is a consequence of the conservation of:", optionA: "Charge", optionB: "Energy", optionC: "Momentum", optionD: "Mass", correctOption: "B", explanation: "Lenz's law (opposing the change) ensures energy conservation.", orderIndex: 9 },
  { id: "neet-physics-electromagnetic-induction-ac-q11", topicId: "neet-physics-electromagnetic-induction-ac", text: "A transformer works on the principle of:", optionA: "Self-induction only", optionB: "Mutual induction", optionC: "Electrostatics", optionD: "Resistance heating", correctOption: "B", explanation: "A transformer transfers energy between coils via mutual induction (AC only).", orderIndex: 10 },
  { id: "neet-physics-electromagnetic-induction-ac-q12", topicId: "neet-physics-electromagnetic-induction-ac", text: "The RMS value of an AC of peak current I₀ is:", optionA: "I₀/√2", optionB: "I₀√2", optionC: "I₀", optionD: "2I₀", correctOption: "A", explanation: "For sinusoidal AC, I_rms = I₀/√2 ≈ 0.707 I₀.", orderIndex: 11 },
  // Dual Nature & Modern Physics
  { id: "neet-physics-dual-nature-modern-physics-q09", topicId: "neet-physics-dual-nature-modern-physics", text: "The photoelectric equation gives the maximum kinetic energy of electrons as:", optionA: "hν − φ", optionB: "hν + φ", optionC: "φ − hν", optionD: "hν", correctOption: "A", explanation: "KE_max = hν − φ (work function), Einstein's photoelectric equation.", orderIndex: 8 },
  { id: "neet-physics-dual-nature-modern-physics-q10", topicId: "neet-physics-dual-nature-modern-physics", text: "The de Broglie wavelength of a particle is inversely proportional to its:", optionA: "Charge", optionB: "Momentum", optionC: "Volume", optionD: "Temperature", correctOption: "B", explanation: "λ = h/p, so wavelength is inversely proportional to momentum.", orderIndex: 9 },
  { id: "neet-physics-dual-nature-modern-physics-q11", topicId: "neet-physics-dual-nature-modern-physics", text: "The stopping potential in the photoelectric effect depends on the light's:", optionA: "Intensity", optionB: "Frequency", optionC: "Colourless nature", optionD: "Polarisation", correctOption: "B", explanation: "Stopping potential depends on frequency (via KE_max), not on intensity.", orderIndex: 10 },
  { id: "neet-physics-dual-nature-modern-physics-q12", topicId: "neet-physics-dual-nature-modern-physics", text: "The photon is a packet (quantum) of:", optionA: "Charge", optionB: "Electromagnetic energy", optionC: "Mass", optionD: "Momentum only", correctOption: "B", explanation: "A photon is a quantum of electromagnetic energy, E = hν.", orderIndex: 11 },
  // Semiconductor Electronics
  { id: "neet-physics-semiconductor-electronics-q09", topicId: "neet-physics-semiconductor-electronics", text: "Adding a pentavalent impurity to silicon produces a(n):", optionA: "p-type semiconductor", optionB: "n-type semiconductor", optionC: "Insulator", optionD: "Conductor", correctOption: "B", explanation: "Pentavalent (donor) doping adds free electrons, giving an n-type semiconductor.", orderIndex: 8 },
  { id: "neet-physics-semiconductor-electronics-q10", topicId: "neet-physics-semiconductor-electronics", text: "A p–n junction diode allows current to flow easily when it is:", optionA: "Forward biased", optionB: "Reverse biased", optionC: "Unbiased", optionD: "At absolute zero", correctOption: "A", explanation: "In forward bias the depletion region narrows and the diode conducts.", orderIndex: 9 },
  { id: "neet-physics-semiconductor-electronics-q11", topicId: "neet-physics-semiconductor-electronics", text: "The main function of a diode in a circuit is to act as a:", optionA: "Rectifier", optionB: "Amplifier", optionC: "Oscillator", optionD: "Capacitor", correctOption: "A", explanation: "A diode conducts in one direction, rectifying AC to DC.", orderIndex: 10 },
  { id: "neet-physics-semiconductor-electronics-q12", topicId: "neet-physics-semiconductor-electronics", text: "Adding a trivalent impurity to silicon creates a p-type semiconductor with majority carriers being:", optionA: "Electrons", optionB: "Holes", optionC: "Protons", optionD: "Neutrons", correctOption: "B", explanation: "Trivalent (acceptor) doping creates holes as the majority charge carriers.", orderIndex: 11 },

  // ── New: Units, Measurements & Errors ──
  { id: "neet-physics-units-measurements-q01", topicId: "neet-physics-units-measurements", text: "How many base units are there in the SI system?", optionA: "5", optionB: "7", optionC: "9", optionD: "3", correctOption: "B", explanation: "The SI system has seven base units (m, kg, s, A, K, mol, cd).", orderIndex: 0 },
  { id: "neet-physics-units-measurements-q02", topicId: "neet-physics-units-measurements", text: "The dimensional formula of force is:", optionA: "MLT⁻²", optionB: "ML²T⁻²", optionC: "MLT⁻¹", optionD: "ML⁻¹T⁻²", correctOption: "A", explanation: "Force = mass × acceleration = M × LT⁻² = MLT⁻².", orderIndex: 1 },
  { id: "neet-physics-units-measurements-q03", topicId: "neet-physics-units-measurements", text: "When quantities are multiplied or divided, the ______ errors add.", optionA: "Absolute", optionB: "Relative (fractional)", optionC: "Random", optionD: "Zero", correctOption: "B", explanation: "For products/quotients, the fractional (relative) errors add.", orderIndex: 2 },
  { id: "neet-physics-units-measurements-q04", topicId: "neet-physics-units-measurements", text: "Accuracy of a measurement refers to how close it is to the:", optionA: "True value", optionB: "Mean of readings", optionC: "Least count", optionD: "Zero error", correctOption: "A", explanation: "Accuracy is closeness to the true value; precision is reproducibility.", orderIndex: 3 },
  { id: "neet-physics-units-measurements-q05", topicId: "neet-physics-units-measurements", text: "The dimensional formula of energy (work) is:", optionA: "ML²T⁻²", optionB: "MLT⁻²", optionC: "ML²T⁻¹", optionD: "MLT⁻¹", correctOption: "A", explanation: "Energy = force × distance = MLT⁻² × L = ML²T⁻².", orderIndex: 4 },
  { id: "neet-physics-units-measurements-q06", topicId: "neet-physics-units-measurements", text: "Dimensional analysis can be used to:", optionA: "Check the consistency of an equation", optionB: "Find numerical constants exactly", optionC: "Determine direction", optionD: "Measure mass", correctOption: "A", explanation: "Dimensional analysis checks homogeneity/consistency but cannot find dimensionless constants.", orderIndex: 5 },
  { id: "neet-physics-units-measurements-q07", topicId: "neet-physics-units-measurements", text: "The number of significant figures in 0.00420 is:", optionA: "2", optionB: "3", optionC: "5", optionD: "6", correctOption: "B", explanation: "Leading zeros are not significant; 4, 2, and the trailing 0 give three significant figures.", orderIndex: 6 },
  { id: "neet-physics-units-measurements-q08", topicId: "neet-physics-units-measurements", text: "The smallest value an instrument can measure is its:", optionA: "Range", optionB: "Least count", optionC: "Zero error", optionD: "Accuracy", correctOption: "B", explanation: "The least count is the smallest measurable increment of an instrument.", orderIndex: 7 },
  { id: "neet-physics-units-measurements-q09", topicId: "neet-physics-units-measurements", text: "The dimensional formula of pressure is:", optionA: "ML⁻¹T⁻²", optionB: "MLT⁻²", optionC: "ML²T⁻²", optionD: "MT⁻²", correctOption: "A", explanation: "Pressure = force/area = MLT⁻²/L² = ML⁻¹T⁻².", orderIndex: 8 },
  { id: "neet-physics-units-measurements-q10", topicId: "neet-physics-units-measurements", text: "When quantities are added or subtracted, the ______ errors add.", optionA: "Absolute", optionB: "Relative", optionC: "Percentage only", optionD: "No", correctOption: "A", explanation: "For sums/differences, the absolute errors add.", orderIndex: 9 },
  { id: "neet-physics-units-measurements-q11", topicId: "neet-physics-units-measurements", text: "The candela is the SI base unit of:", optionA: "Luminous intensity", optionB: "Electric current", optionC: "Temperature", optionD: "Amount of substance", correctOption: "A", explanation: "The candela measures luminous intensity.", orderIndex: 10 },
  { id: "neet-physics-units-measurements-q12", topicId: "neet-physics-units-measurements", text: "A dimensionless quantity among the following is:", optionA: "Strain", optionB: "Force", optionC: "Velocity", optionD: "Momentum", correctOption: "A", explanation: "Strain is a ratio of lengths, so it is dimensionless.", orderIndex: 11 },

  // ── New: Motion in a Plane & Projectiles ──
  { id: "neet-physics-motion-in-a-plane-q01", topicId: "neet-physics-motion-in-a-plane", text: "The horizontal component of a projectile's velocity during flight (ignoring air resistance):", optionA: "Increases", optionB: "Remains constant", optionC: "Decreases", optionD: "Becomes zero at the top", correctOption: "B", explanation: "With no horizontal force, the horizontal velocity u cosθ stays constant.", orderIndex: 0 },
  { id: "neet-physics-motion-in-a-plane-q02", topicId: "neet-physics-motion-in-a-plane", text: "The range of a projectile is maximum at a launch angle of:", optionA: "30°", optionB: "45°", optionC: "60°", optionD: "90°", correctOption: "B", explanation: "R = u²sin2θ/g is maximum when sin2θ = 1, i.e., θ = 45°.", orderIndex: 1 },
  { id: "neet-physics-motion-in-a-plane-q03", topicId: "neet-physics-motion-in-a-plane", text: "The path (trajectory) of a projectile is a:", optionA: "Straight line", optionB: "Parabola", optionC: "Circle", optionD: "Hyperbola", correctOption: "B", explanation: "Combining uniform horizontal and accelerated vertical motion gives a parabolic path.", orderIndex: 2 },
  { id: "neet-physics-motion-in-a-plane-q04", topicId: "neet-physics-motion-in-a-plane", text: "The centripetal acceleration in uniform circular motion is:", optionA: "v²/r toward the centre", optionB: "v²r outward", optionC: "Zero", optionD: "vr", correctOption: "A", explanation: "Centripetal acceleration a = v²/r points toward the centre of the circle.", orderIndex: 3 },
  { id: "neet-physics-motion-in-a-plane-q05", topicId: "neet-physics-motion-in-a-plane", text: "At the highest point of its trajectory, a projectile's vertical velocity is:", optionA: "Maximum", optionB: "Zero", optionC: "Equal to u", optionD: "Equal to g", correctOption: "B", explanation: "The vertical velocity becomes zero at the peak before the descent.", orderIndex: 4 },
  { id: "neet-physics-motion-in-a-plane-q06", topicId: "neet-physics-motion-in-a-plane", text: "The time of flight of a projectile launched at speed u and angle θ is:", optionA: "2u sinθ/g", optionB: "u cosθ/g", optionC: "u²/g", optionD: "u sinθ/2g", correctOption: "A", explanation: "Time of flight T = 2u sinθ/g.", orderIndex: 5 },
  { id: "neet-physics-motion-in-a-plane-q07", topicId: "neet-physics-motion-in-a-plane", text: "In uniform circular motion, the quantity that changes continuously is the:", optionA: "Speed", optionB: "Direction of velocity", optionC: "Kinetic energy", optionD: "Radius", correctOption: "B", explanation: "Speed is constant but velocity's direction changes, requiring centripetal acceleration.", orderIndex: 6 },
  { id: "neet-physics-motion-in-a-plane-q08", topicId: "neet-physics-motion-in-a-plane", text: "The maximum height of a projectile is given by:", optionA: "u²sin²θ/2g", optionB: "u²sin2θ/g", optionC: "2u sinθ/g", optionD: "u cosθ/g", correctOption: "A", explanation: "Maximum height H = u²sin²θ/2g.", orderIndex: 7 },
  { id: "neet-physics-motion-in-a-plane-q09", topicId: "neet-physics-motion-in-a-plane", text: "Two vectors of equal magnitude have a resultant equal to either one when the angle between them is:", optionA: "60°", optionB: "120°", optionC: "90°", optionD: "180°", correctOption: "B", explanation: "For equal vectors, the resultant equals their magnitude when the angle is 120°.", orderIndex: 8 },
  { id: "neet-physics-motion-in-a-plane-q10", topicId: "neet-physics-motion-in-a-plane", text: "The horizontal range is the same for launch angles of:", optionA: "θ and (90° − θ)", optionB: "θ and 90°", optionC: "θ and 180°", optionD: "Only 45°", correctOption: "A", explanation: "Complementary angles (θ and 90°−θ) give the same range since sin2θ = sin(180°−2θ).", orderIndex: 9 },
  { id: "neet-physics-motion-in-a-plane-q11", topicId: "neet-physics-motion-in-a-plane", text: "The centripetal force required for circular motion is directed:", optionA: "Along the velocity", optionB: "Toward the centre", optionC: "Away from the centre", optionD: "Tangentially", correctOption: "B", explanation: "Centripetal force points toward the centre, providing the acceleration v²/r.", orderIndex: 10 },
  { id: "neet-physics-motion-in-a-plane-q12", topicId: "neet-physics-motion-in-a-plane", text: "A scalar quantity among the following is:", optionA: "Velocity", optionB: "Speed", optionC: "Displacement", optionD: "Acceleration", correctOption: "B", explanation: "Speed is a scalar (magnitude only); the others are vectors.", orderIndex: 11 },

  // ── New: Rotational Motion ──
  { id: "neet-physics-rotational-motion-q01", topicId: "neet-physics-rotational-motion", text: "The rotational analogue of force is:", optionA: "Torque", optionB: "Momentum", optionC: "Power", optionD: "Impulse", correctOption: "A", explanation: "Torque (τ = r × F) is the rotational analogue of force.", orderIndex: 0 },
  { id: "neet-physics-rotational-motion-q02", topicId: "neet-physics-rotational-motion", text: "The moment of inertia of a solid sphere about a diameter is:", optionA: "(2/5)MR²", optionB: "MR²", optionC: "(1/2)MR²", optionD: "(2/3)MR²", correctOption: "A", explanation: "A solid sphere has I = (2/5)MR² about a diameter.", orderIndex: 1 },
  { id: "neet-physics-rotational-motion-q03", topicId: "neet-physics-rotational-motion", text: "Angular momentum is conserved when the net external ______ is zero.", optionA: "Force", optionB: "Torque", optionC: "Momentum", optionD: "Energy", correctOption: "B", explanation: "Angular momentum L = Iω is conserved in the absence of a net external torque.", orderIndex: 2 },
  { id: "neet-physics-rotational-motion-q04", topicId: "neet-physics-rotational-motion", text: "The rotational form of Newton's second law is:", optionA: "τ = Iα", optionB: "F = ma", optionC: "L = Iω", optionD: "p = mv", correctOption: "A", explanation: "Net torque equals moment of inertia times angular acceleration, τ = Iα.", orderIndex: 3 },
  { id: "neet-physics-rotational-motion-q05", topicId: "neet-physics-rotational-motion", text: "The parallel-axis theorem is written as:", optionA: "I = I_cm + Md²", optionB: "I = I_cm − Md²", optionC: "I = Md²", optionD: "I = I_cm/2", correctOption: "A", explanation: "I about a parallel axis is I_cm + Md², where d is the axis separation.", orderIndex: 4 },
  { id: "neet-physics-rotational-motion-q06", topicId: "neet-physics-rotational-motion", text: "For rolling without slipping, the linear and angular speeds are related by:", optionA: "v = ωR", optionB: "v = ω/R", optionC: "v = ωR²", optionD: "v = R/ω", correctOption: "A", explanation: "Rolling without slipping requires v = ωR.", orderIndex: 5 },
  { id: "neet-physics-rotational-motion-q07", topicId: "neet-physics-rotational-motion", text: "The moment of inertia of a ring about its central axis is:", optionA: "MR²", optionB: "(1/2)MR²", optionC: "(2/5)MR²", optionD: "(1/3)MR²", correctOption: "A", explanation: "A thin ring has all its mass at radius R, so I = MR².", orderIndex: 6 },
  { id: "neet-physics-rotational-motion-q08", topicId: "neet-physics-rotational-motion", text: "When a ballerina pulls in her arms, her angular speed increases because her:", optionA: "Moment of inertia decreases (L conserved)", optionB: "Torque increases", optionC: "Mass decreases", optionD: "Energy decreases", correctOption: "A", explanation: "With L conserved, reducing I raises ω.", orderIndex: 7 },
  { id: "neet-physics-rotational-motion-q09", topicId: "neet-physics-rotational-motion", text: "The kinetic energy of a rolling body is:", optionA: "½mv² + ½Iω²", optionB: "½mv² only", optionC: "½Iω² only", optionD: "mv²", correctOption: "A", explanation: "A rolling body has both translational (½mv²) and rotational (½Iω²) kinetic energy.", orderIndex: 8 },
  { id: "neet-physics-rotational-motion-q10", topicId: "neet-physics-rotational-motion", text: "The moment of inertia of a disc about its central axis is:", optionA: "(1/2)MR²", optionB: "MR²", optionC: "(2/5)MR²", optionD: "(1/4)MR²", correctOption: "A", explanation: "A uniform disc has I = ½MR² about its central axis.", orderIndex: 9 },
  { id: "neet-physics-rotational-motion-q11", topicId: "neet-physics-rotational-motion", text: "The centre of mass of a uniform rod lies at its:", optionA: "One end", optionB: "Geometric centre (midpoint)", optionC: "Quarter length", optionD: "Outside the rod", correctOption: "B", explanation: "For a uniform rod, the centre of mass is at the midpoint.", orderIndex: 10 },
  { id: "neet-physics-rotational-motion-q12", topicId: "neet-physics-rotational-motion", text: "Radius of gyration k relates to moment of inertia by:", optionA: "I = Mk²", optionB: "I = Mk", optionC: "k = MI", optionD: "I = k/M", correctOption: "A", explanation: "The radius of gyration is defined by I = Mk².", orderIndex: 11 },

  // ── New: Mechanical Properties of Solids ──
  { id: "neet-physics-mechanical-properties-solids-q01", topicId: "neet-physics-mechanical-properties-solids", text: "Stress is defined as:", optionA: "Force per unit area", optionB: "Change in length", optionC: "Force × area", optionD: "Length per unit force", correctOption: "A", explanation: "Stress = restoring force per unit cross-sectional area.", orderIndex: 0 },
  { id: "neet-physics-mechanical-properties-solids-q02", topicId: "neet-physics-mechanical-properties-solids", text: "Strain is a:", optionA: "Dimensionless ratio", optionB: "Force", optionC: "Pressure", optionD: "Vector with units", correctOption: "A", explanation: "Strain is the fractional deformation (change/original), so it is dimensionless.", orderIndex: 1 },
  { id: "neet-physics-mechanical-properties-solids-q03", topicId: "neet-physics-mechanical-properties-solids", text: "Hooke's law states that within the elastic limit, stress is:", optionA: "Proportional to strain", optionB: "Inversely proportional to strain", optionC: "Independent of strain", optionD: "Equal to strain squared", correctOption: "A", explanation: "Hooke's law: stress ∝ strain within the elastic limit.", orderIndex: 2 },
  { id: "neet-physics-mechanical-properties-solids-q04", topicId: "neet-physics-mechanical-properties-solids", text: "Young's modulus measures resistance to change in:", optionA: "Length", optionB: "Volume", optionC: "Shape only", optionD: "Temperature", correctOption: "A", explanation: "Young's modulus (Y) = longitudinal stress/strain, resisting length change.", orderIndex: 3 },
  { id: "neet-physics-mechanical-properties-solids-q05", topicId: "neet-physics-mechanical-properties-solids", text: "The bulk modulus is related to a change in:", optionA: "Volume", optionB: "Length", optionC: "Shape", optionD: "Mass", correctOption: "A", explanation: "Bulk modulus measures resistance to uniform volume compression.", orderIndex: 4 },
  { id: "neet-physics-mechanical-properties-solids-q06", topicId: "neet-physics-mechanical-properties-solids", text: "The shear (rigidity) modulus concerns a change in:", optionA: "Shape", optionB: "Volume", optionC: "Length", optionD: "Density", correctOption: "A", explanation: "The shear modulus measures resistance to a change in shape (shear strain).", orderIndex: 5 },
  { id: "neet-physics-mechanical-properties-solids-q07", topicId: "neet-physics-mechanical-properties-solids", text: "A material with a higher Young's modulus is:", optionA: "More elastic/stiffer", optionB: "More plastic", optionC: "Softer", optionD: "Weaker", correctOption: "A", explanation: "A higher Young's modulus means the material resists deformation more (stiffer).", orderIndex: 6 },
  { id: "neet-physics-mechanical-properties-solids-q08", topicId: "neet-physics-mechanical-properties-solids", text: "The SI unit of stress and Young's modulus is the:", optionA: "Pascal (N/m²)", optionB: "Newton", optionC: "Joule", optionD: "Watt", correctOption: "A", explanation: "Stress (and modulus) has units of pascals, N/m².", orderIndex: 7 },
  { id: "neet-physics-mechanical-properties-solids-q09", topicId: "neet-physics-mechanical-properties-solids", text: "The elastic potential energy stored per unit volume is:", optionA: "½ × stress × strain", optionB: "stress × strain", optionC: "½ × stress²", optionD: "strain²", correctOption: "A", explanation: "Elastic energy density = ½ × stress × strain.", orderIndex: 8 },
  { id: "neet-physics-mechanical-properties-solids-q10", topicId: "neet-physics-mechanical-properties-solids", text: "The point beyond which a material does not return to its original shape is the:", optionA: "Elastic limit", optionB: "Yield increase", optionC: "Origin", optionD: "Melting point", correctOption: "A", explanation: "Beyond the elastic limit, permanent (plastic) deformation occurs.", orderIndex: 9 },
  { id: "neet-physics-mechanical-properties-solids-q11", topicId: "neet-physics-mechanical-properties-solids", text: "A brittle material breaks:", optionA: "Soon after the elastic limit with little plastic deformation", optionB: "Only after large stretching", optionC: "Never", optionD: "At zero stress", correctOption: "A", explanation: "Brittle materials fracture shortly beyond the elastic region with little plasticity.", orderIndex: 10 },
  { id: "neet-physics-mechanical-properties-solids-q12", topicId: "neet-physics-mechanical-properties-solids", text: "The ratio of lateral strain to longitudinal strain is called:", optionA: "Poisson's ratio", optionB: "Young's modulus", optionC: "Bulk modulus", optionD: "Shear strain", correctOption: "A", explanation: "Poisson's ratio is the ratio of lateral to longitudinal strain.", orderIndex: 11 },

  // ── New: Mechanical Properties of Fluids ──
  { id: "neet-physics-mechanical-properties-fluids-q01", topicId: "neet-physics-mechanical-properties-fluids", text: "Pascal's law states that pressure applied to an enclosed fluid is transmitted:", optionA: "Equally in all directions", optionB: "Only downward", optionC: "Only upward", optionD: "In one direction", correctOption: "A", explanation: "Pascal's law is the basis of hydraulic presses — pressure is transmitted undiminished.", orderIndex: 0 },
  { id: "neet-physics-mechanical-properties-fluids-q02", topicId: "neet-physics-mechanical-properties-fluids", text: "Archimedes' principle states that the buoyant force equals the weight of:", optionA: "The object", optionB: "The fluid displaced", optionC: "The container", optionD: "Air above", correctOption: "B", explanation: "Buoyant force equals the weight of the fluid displaced by the submerged part.", orderIndex: 1 },
  { id: "neet-physics-mechanical-properties-fluids-q03", topicId: "neet-physics-mechanical-properties-fluids", text: "The pressure at depth h in a liquid of density ρ is:", optionA: "P₀ + ρgh", optionB: "ρg/h", optionC: "P₀ − ρgh", optionD: "ρh/g", correctOption: "A", explanation: "Fluid pressure increases with depth: P = P₀ + ρgh.", orderIndex: 2 },
  { id: "neet-physics-mechanical-properties-fluids-q04", topicId: "neet-physics-mechanical-properties-fluids", text: "According to Bernoulli's theorem, where fluid speed is high, the pressure is:", optionA: "Low", optionB: "High", optionC: "Unchanged", optionD: "Infinite", correctOption: "A", explanation: "Bernoulli's principle: faster-moving fluid has lower pressure (energy conservation).", orderIndex: 3 },
  { id: "neet-physics-mechanical-properties-fluids-q05", topicId: "neet-physics-mechanical-properties-fluids", text: "The equation of continuity (Av = constant) is based on conservation of:", optionA: "Mass", optionB: "Charge", optionC: "Momentum", optionD: "Energy", correctOption: "A", explanation: "Continuity (A₁v₁ = A₂v₂) expresses conservation of mass for an incompressible fluid.", orderIndex: 4 },
  { id: "neet-physics-mechanical-properties-fluids-q06", topicId: "neet-physics-mechanical-properties-fluids", text: "Viscosity is a measure of a fluid's:", optionA: "Resistance to flow", optionB: "Density", optionC: "Surface area", optionD: "Colour", correctOption: "A", explanation: "Viscosity is the internal friction resisting relative motion between fluid layers.", orderIndex: 5 },
  { id: "neet-physics-mechanical-properties-fluids-q07", topicId: "neet-physics-mechanical-properties-fluids", text: "Stokes' law gives the viscous force on a small sphere as:", optionA: "6πηrv", optionB: "πr²v", optionC: "ρgh", optionD: "½ρv²", correctOption: "A", explanation: "Stokes' law: F = 6πηrv for a sphere of radius r moving at speed v.", orderIndex: 6 },
  { id: "neet-physics-mechanical-properties-fluids-q08", topicId: "neet-physics-mechanical-properties-fluids", text: "Surface tension arises due to:", optionA: "Cohesive forces between molecules at the surface", optionB: "Gravity only", optionC: "Air pressure", optionD: "Temperature only", correctOption: "A", explanation: "Unbalanced cohesive forces on surface molecules produce surface tension.", orderIndex: 7 },
  { id: "neet-physics-mechanical-properties-fluids-q09", topicId: "neet-physics-mechanical-properties-fluids", text: "Capillary rise of a liquid is due to:", optionA: "Surface tension and adhesion", optionB: "Gravity alone", optionC: "Viscosity", optionD: "Pressure only", correctOption: "A", explanation: "Surface tension with adhesion causes liquids to rise in narrow tubes (capillarity).", orderIndex: 8 },
  { id: "neet-physics-mechanical-properties-fluids-q10", topicId: "neet-physics-mechanical-properties-fluids", text: "An object floats when its weight is:", optionA: "Equal to the buoyant force", optionB: "Greater than buoyant force", optionC: "Zero", optionD: "Greater than gravity", correctOption: "A", explanation: "Floating occurs when the buoyant force balances the object's weight.", orderIndex: 9 },
  { id: "neet-physics-mechanical-properties-fluids-q11", topicId: "neet-physics-mechanical-properties-fluids", text: "The terminal velocity of a sphere falling through a viscous fluid is reached when:", optionA: "Net force is zero (weight = drag + buoyancy)", optionB: "Speed is zero", optionC: "Drag is zero", optionD: "Buoyancy is zero", correctOption: "A", explanation: "At terminal velocity, gravity is balanced by viscous drag and buoyancy, so acceleration is zero.", orderIndex: 10 },
  { id: "neet-physics-mechanical-properties-fluids-q12", topicId: "neet-physics-mechanical-properties-fluids", text: "The lift on an aeroplane wing is explained by:", optionA: "Bernoulli's principle", optionB: "Archimedes' principle", optionC: "Pascal's law", optionD: "Hooke's law", correctOption: "A", explanation: "Faster airflow over the curved upper wing lowers pressure, generating lift (Bernoulli).", orderIndex: 11 },

  // ── New: Thermal Properties of Matter ──
  { id: "neet-physics-thermal-properties-matter-q01", topicId: "neet-physics-thermal-properties-matter", text: "The coefficient of volume expansion (γ) is related to linear expansion (α) by:", optionA: "γ = 3α", optionB: "γ = α", optionC: "γ = 2α", optionD: "γ = α/3", correctOption: "A", explanation: "For isotropic solids, γ = 3α (and area coefficient β = 2α).", orderIndex: 0 },
  { id: "neet-physics-thermal-properties-matter-q02", topicId: "neet-physics-thermal-properties-matter", text: "Heat transfer through a solid without bulk movement of matter is:", optionA: "Conduction", optionB: "Convection", optionC: "Radiation", optionD: "Evaporation", correctOption: "A", explanation: "Conduction transfers heat through a material via molecular vibration/electron motion.", orderIndex: 1 },
  { id: "neet-physics-thermal-properties-matter-q03", topicId: "neet-physics-thermal-properties-matter", text: "Heat transfer that requires no medium is:", optionA: "Conduction", optionB: "Convection", optionC: "Radiation", optionD: "Diffusion", correctOption: "C", explanation: "Radiation transfers heat via electromagnetic waves and can occur through a vacuum.", orderIndex: 2 },
  { id: "neet-physics-thermal-properties-matter-q04", topicId: "neet-physics-thermal-properties-matter", text: "The Stefan–Boltzmann law states that radiated power is proportional to:", optionA: "T⁴", optionB: "T", optionC: "T²", optionD: "1/T", correctOption: "A", explanation: "A body radiates power ∝ T⁴ (absolute temperature).", orderIndex: 3 },
  { id: "neet-physics-thermal-properties-matter-q05", topicId: "neet-physics-thermal-properties-matter", text: "Latent heat is the heat absorbed or released during a:", optionA: "Phase change (at constant temperature)", optionB: "Temperature rise", optionC: "Pressure change", optionD: "Volume change only", correctOption: "A", explanation: "Latent heat accompanies phase changes with no temperature change (Q = mL).", orderIndex: 4 },
  { id: "neet-physics-thermal-properties-matter-q06", topicId: "neet-physics-thermal-properties-matter", text: "Newton's law of cooling states the rate of heat loss is proportional to the:", optionA: "Temperature difference with surroundings", optionB: "Square of temperature", optionC: "Volume", optionD: "Mass only", correctOption: "A", explanation: "Newton's law of cooling: cooling rate ∝ (T_body − T_surroundings) for small differences.", orderIndex: 5 },
  { id: "neet-physics-thermal-properties-matter-q07", topicId: "neet-physics-thermal-properties-matter", text: "The heat required to raise the temperature is Q = mcΔT, where c is the:", optionA: "Specific heat capacity", optionB: "Latent heat", optionC: "Thermal conductivity", optionD: "Emissivity", correctOption: "A", explanation: "c is the specific heat capacity, the heat per unit mass per degree.", orderIndex: 6 },
  { id: "neet-physics-thermal-properties-matter-q08", topicId: "neet-physics-thermal-properties-matter", text: "A perfect black body is one that:", optionA: "Absorbs and emits all radiation", optionB: "Reflects all radiation", optionC: "Transmits all radiation", optionD: "Emits no radiation", correctOption: "A", explanation: "A black body absorbs all incident radiation and is the best possible emitter.", orderIndex: 7 },
  { id: "neet-physics-thermal-properties-matter-q09", topicId: "neet-physics-thermal-properties-matter", text: "Wien's displacement law relates the peak emission wavelength to temperature as:", optionA: "λ_max ∝ 1/T", optionB: "λ_max ∝ T", optionC: "λ_max ∝ T⁴", optionD: "λ_max ∝ T²", correctOption: "A", explanation: "Wien's law: the peak wavelength is inversely proportional to absolute temperature.", orderIndex: 8 },
  { id: "neet-physics-thermal-properties-matter-q10", topicId: "neet-physics-thermal-properties-matter", text: "Heat transfer in liquids and gases by actual movement of matter is:", optionA: "Convection", optionB: "Conduction", optionC: "Radiation", optionD: "Sublimation", correctOption: "A", explanation: "Convection transfers heat through the bulk movement of heated fluid.", orderIndex: 9 },
  { id: "neet-physics-thermal-properties-matter-q11", topicId: "neet-physics-thermal-properties-matter", text: "Water has an unusually high value of:", optionA: "Specific heat capacity", optionB: "Thermal conductivity", optionC: "Density at all temperatures", optionD: "Emissivity", correctOption: "A", explanation: "Water's high specific heat lets it absorb much heat with little temperature rise.", orderIndex: 10 },
  { id: "neet-physics-thermal-properties-matter-q12", topicId: "neet-physics-thermal-properties-matter", text: "The area coefficient of expansion β equals:", optionA: "2α", optionB: "3α", optionC: "α", optionD: "α/2", correctOption: "A", explanation: "For isotropic solids, the area expansion coefficient β = 2α.", orderIndex: 11 },

  // ── New: Kinetic Theory of Gases ──
  { id: "neet-physics-kinetic-theory-q01", topicId: "neet-physics-kinetic-theory", text: "According to kinetic theory, the pressure of a gas arises from:", optionA: "Molecular collisions with the walls", optionB: "Molecular colour", optionC: "Gravity", optionD: "Chemical bonds", correctOption: "A", explanation: "Gas pressure results from momentum transfer during molecular collisions with the container.", orderIndex: 0 },
  { id: "neet-physics-kinetic-theory-q02", topicId: "neet-physics-kinetic-theory", text: "The average kinetic energy of a gas molecule is proportional to:", optionA: "Absolute temperature", optionB: "Pressure", optionC: "Volume", optionD: "Molar mass", correctOption: "A", explanation: "Average KE per molecule = (3/2)kT, proportional to absolute temperature.", orderIndex: 1 },
  { id: "neet-physics-kinetic-theory-q03", topicId: "neet-physics-kinetic-theory", text: "The rms speed of gas molecules is proportional to:", optionA: "√T", optionB: "T", optionC: "T²", optionD: "1/T", correctOption: "A", explanation: "v_rms = √(3RT/M), so it scales as the square root of temperature.", orderIndex: 2 },
  { id: "neet-physics-kinetic-theory-q04", topicId: "neet-physics-kinetic-theory", text: "The number of degrees of freedom of a monatomic gas molecule is:", optionA: "3", optionB: "5", optionC: "6", optionD: "1", correctOption: "A", explanation: "A monatomic gas has 3 translational degrees of freedom.", orderIndex: 3 },
  { id: "neet-physics-kinetic-theory-q05", topicId: "neet-physics-kinetic-theory", text: "The equipartition theorem assigns energy per degree of freedom of:", optionA: "½kT", optionB: "kT", optionC: "(3/2)kT", optionD: "2kT", correctOption: "A", explanation: "Each degree of freedom carries an average energy of ½kT.", orderIndex: 4 },
  { id: "neet-physics-kinetic-theory-q06", topicId: "neet-physics-kinetic-theory", text: "For a diatomic gas, the ratio of specific heats γ is:", optionA: "7/5", optionB: "5/3", optionC: "4/3", optionD: "1", correctOption: "A", explanation: "A diatomic gas (5 degrees of freedom) has γ = 7/5.", orderIndex: 5 },
  { id: "neet-physics-kinetic-theory-q07", topicId: "neet-physics-kinetic-theory", text: "The mean free path of gas molecules ______ as pressure increases.", optionA: "Decreases", optionB: "Increases", optionC: "Stays constant", optionD: "Becomes infinite", correctOption: "A", explanation: "Higher pressure means more molecules per volume, so the mean free path decreases.", orderIndex: 6 },
  { id: "neet-physics-kinetic-theory-q08", topicId: "neet-physics-kinetic-theory", text: "Among molecular speeds, the correct order is:", optionA: "v_rms > v_avg > v_mp", optionB: "v_mp > v_avg > v_rms", optionC: "All equal", optionD: "v_avg > v_rms > v_mp", correctOption: "A", explanation: "For a Maxwell distribution, v_rms > v_average > v_most-probable.", orderIndex: 7 },
  { id: "neet-physics-kinetic-theory-q09", topicId: "neet-physics-kinetic-theory", text: "Kinetic theory shows gas pressure P equals:", optionA: "(1/3)ρv̄²", optionB: "ρgh", optionC: "½ρv²", optionD: "ρv", correctOption: "A", explanation: "P = (1/3)ρv̄² relates pressure to density and mean-square molecular speed.", orderIndex: 8 },
  { id: "neet-physics-kinetic-theory-q10", topicId: "neet-physics-kinetic-theory", text: "At the same temperature, two different gases have the same average:", optionA: "Kinetic energy per molecule", optionB: "Speed", optionC: "Mass", optionD: "Density", correctOption: "A", explanation: "At equal temperature, molecules have the same average KE, though speeds differ with mass.", orderIndex: 9 },
  { id: "neet-physics-kinetic-theory-q11", topicId: "neet-physics-kinetic-theory", text: "Absolute zero corresponds to the temperature at which molecular motion:", optionA: "Theoretically ceases (minimum energy)", optionB: "Is maximum", optionC: "Is random and high", optionD: "Doubles", correctOption: "A", explanation: "At 0 K, molecular translational motion is at its theoretical minimum.", orderIndex: 10 },
  { id: "neet-physics-kinetic-theory-q12", topicId: "neet-physics-kinetic-theory", text: "For a diatomic gas, the number of degrees of freedom (translational + rotational) at room temperature is:", optionA: "5", optionB: "3", optionC: "7", optionD: "1", correctOption: "A", explanation: "A diatomic molecule has 3 translational + 2 rotational = 5 degrees of freedom.", orderIndex: 11 },

  // ── New: Wave Optics ──
  { id: "neet-physics-wave-optics-q01", topicId: "neet-physics-wave-optics", text: "In Young's double-slit experiment, the fringe width is given by:", optionA: "λD/d", optionB: "λd/D", optionC: "dD/λ", optionD: "λ/dD", correctOption: "A", explanation: "Fringe width β = λD/d.", orderIndex: 0 },
  { id: "neet-physics-wave-optics-q02", topicId: "neet-physics-wave-optics", text: "Sustained interference requires the two sources to be:", optionA: "Coherent", optionB: "Of different frequency", optionC: "Incoherent", optionD: "Point sources only", correctOption: "A", explanation: "Coherent sources with a constant phase difference are needed for stable interference.", orderIndex: 1 },
  { id: "neet-physics-wave-optics-q03", topicId: "neet-physics-wave-optics", text: "Diffraction becomes significant when the obstacle/aperture size is comparable to the:", optionA: "Wavelength", optionB: "Frequency", optionC: "Amplitude", optionD: "Speed", correctOption: "A", explanation: "Diffraction is pronounced when the aperture is comparable to the wavelength of light.", orderIndex: 2 },
  { id: "neet-physics-wave-optics-q04", topicId: "neet-physics-wave-optics", text: "The phenomenon that confirms light is a transverse wave is:", optionA: "Polarisation", optionB: "Interference", optionC: "Diffraction", optionD: "Refraction", correctOption: "A", explanation: "Only transverse waves can be polarised, confirming light's transverse nature.", orderIndex: 3 },
  { id: "neet-physics-wave-optics-q05", topicId: "neet-physics-wave-optics", text: "Malus's law relates the transmitted intensity through a polariser to:", optionA: "cos²θ", optionB: "sinθ", optionC: "tanθ", optionD: "cosθ", correctOption: "A", explanation: "Malus's law: I = I₀cos²θ, where θ is the angle between polariser axes.", orderIndex: 4 },
  { id: "neet-physics-wave-optics-q06", topicId: "neet-physics-wave-optics", text: "Huygens' principle treats each point on a wavefront as a source of:", optionA: "Secondary wavelets", optionB: "Particles", optionC: "Photons only", optionD: "Sound", correctOption: "A", explanation: "Huygens' principle: each wavefront point emits secondary spherical wavelets.", orderIndex: 5 },
  { id: "neet-physics-wave-optics-q07", topicId: "neet-physics-wave-optics", text: "For constructive interference, the path difference must be:", optionA: "An integer multiple of λ", optionB: "A half-integer multiple of λ", optionC: "Zero only", optionD: "λ/4", correctOption: "A", explanation: "Bright fringes occur at path differences of nλ.", orderIndex: 6 },
  { id: "neet-physics-wave-optics-q08", topicId: "neet-physics-wave-optics", text: "In single-slit diffraction, the first minimum occurs at:", optionA: "a sinθ = λ", optionB: "a sinθ = λ/2", optionC: "d sinθ = λ", optionD: "a sinθ = 2λ", correctOption: "A", explanation: "The first diffraction minimum from a slit of width a is at a sinθ = λ.", orderIndex: 7 },
  { id: "neet-physics-wave-optics-q09", topicId: "neet-physics-wave-optics", text: "When the double-slit apparatus is immersed in water, the fringe width:", optionA: "Decreases", optionB: "Increases", optionC: "Stays the same", optionD: "Becomes zero", correctOption: "A", explanation: "Wavelength decreases in water (λ/μ), so the fringe width β decreases.", orderIndex: 8 },
  { id: "neet-physics-wave-optics-q10", topicId: "neet-physics-wave-optics", text: "Brewster's law relates the polarising angle to refractive index by:", optionA: "tan θ_p = μ", optionB: "sin θ_p = μ", optionC: "cos θ_p = μ", optionD: "θ_p = μ", correctOption: "A", explanation: "Brewster's law: tan θ_p = μ, at which reflected light is fully polarised.", orderIndex: 9 },
  { id: "neet-physics-wave-optics-q11", topicId: "neet-physics-wave-optics", text: "The resolving power of an optical instrument increases with:", optionA: "Larger aperture", optionB: "Smaller aperture", optionC: "Longer wavelength", optionD: "Lower frequency", correctOption: "A", explanation: "Resolving power ∝ aperture/λ, so a larger aperture resolves finer detail.", orderIndex: 10 },
  { id: "neet-physics-wave-optics-q12", topicId: "neet-physics-wave-optics", text: "The central fringe in Young's experiment (zero path difference) is:", optionA: "Bright", optionB: "Dark", optionC: "Coloured", optionD: "Absent", correctOption: "A", explanation: "At zero path difference, constructive interference gives a bright central fringe.", orderIndex: 11 },

  // ── New: Magnetism & Matter ──
  { id: "neet-physics-magnetism-matter-q01", topicId: "neet-physics-magnetism-matter", text: "Diamagnetic materials are:", optionA: "Weakly repelled by a magnetic field", optionB: "Strongly attracted", optionC: "Permanently magnetic", optionD: "Non-magnetic entirely", correctOption: "A", explanation: "Diamagnetic substances are weakly repelled and have small negative susceptibility.", orderIndex: 0 },
  { id: "neet-physics-magnetism-matter-q02", topicId: "neet-physics-magnetism-matter", text: "Ferromagnetic materials, such as iron, are:", optionA: "Strongly attracted and can be permanently magnetised", optionB: "Weakly repelled", optionC: "Never magnetic", optionD: "Only paramagnetic", correctOption: "A", explanation: "Ferromagnets have magnetic domains and can retain strong permanent magnetism.", orderIndex: 1 },
  { id: "neet-physics-magnetism-matter-q03", topicId: "neet-physics-magnetism-matter", text: "Paramagnetic susceptibility varies with temperature according to:", optionA: "Curie's law (χ ∝ 1/T)", optionB: "Ohm's law", optionC: "Hooke's law", optionD: "Stefan's law", correctOption: "A", explanation: "Curie's law: paramagnetic susceptibility is inversely proportional to temperature.", orderIndex: 2 },
  { id: "neet-physics-magnetism-matter-q04", topicId: "neet-physics-magnetism-matter", text: "A ferromagnet loses its magnetism above the:", optionA: "Curie temperature", optionB: "Boiling point", optionC: "Triple point", optionD: "Absolute zero", correctOption: "A", explanation: "Above the Curie temperature, thermal agitation destroys domain alignment and ferromagnetism.", orderIndex: 3 },
  { id: "neet-physics-magnetism-matter-q05", topicId: "neet-physics-magnetism-matter", text: "The angle between the Earth's magnetic field and the horizontal is the:", optionA: "Angle of dip (inclination)", optionB: "Declination", optionC: "Azimuth", optionD: "Latitude", correctOption: "A", explanation: "The dip (inclination) is the angle the Earth's field makes with the horizontal.", orderIndex: 4 },
  { id: "neet-physics-magnetism-matter-q06", topicId: "neet-physics-magnetism-matter", text: "Soft iron is preferred for electromagnets because it has a:", optionA: "Narrow hysteresis loop (low retentivity)", optionB: "Wide hysteresis loop", optionC: "High permanent magnetism", optionD: "Zero permeability", correctOption: "A", explanation: "Soft iron's narrow hysteresis loop lets it magnetise and demagnetise easily — ideal for electromagnets.", orderIndex: 5 },
  { id: "neet-physics-magnetism-matter-q07", topicId: "neet-physics-magnetism-matter", text: "Steel is used for permanent magnets because it has:", optionA: "High retentivity and a wide hysteresis loop", optionB: "Low retentivity", optionC: "Zero coercivity", optionD: "Diamagnetism", correctOption: "A", explanation: "Steel retains magnetism well (high retentivity/coercivity), suiting permanent magnets.", orderIndex: 6 },
  { id: "neet-physics-magnetism-matter-q08", topicId: "neet-physics-magnetism-matter", text: "The torque on a magnetic dipole of moment m in a field B is:", optionA: "m × B", optionB: "m·B", optionC: "m/B", optionD: "mB²", correctOption: "A", explanation: "Torque τ = m × B, maximal when the dipole is perpendicular to the field.", orderIndex: 7 },
  { id: "neet-physics-magnetism-matter-q09", topicId: "neet-physics-magnetism-matter", text: "The magnetic susceptibility of a diamagnetic material is:", optionA: "Small and negative", optionB: "Small and positive", optionC: "Large and positive", optionD: "Zero", correctOption: "A", explanation: "Diamagnetic materials have small negative susceptibility.", orderIndex: 8 },
  { id: "neet-physics-magnetism-matter-q10", topicId: "neet-physics-magnetism-matter", text: "The property by which a ferromagnet's magnetisation lags behind the applied field is:", optionA: "Hysteresis", optionB: "Resonance", optionC: "Diffraction", optionD: "Polarisation", correctOption: "A", explanation: "Hysteresis is the lag of magnetisation behind the magnetising field in ferromagnets.", orderIndex: 9 },
  { id: "neet-physics-magnetism-matter-q11", topicId: "neet-physics-magnetism-matter", text: "The Earth behaves approximately like a giant:", optionA: "Bar magnet", optionB: "Electric charge", optionC: "Capacitor", optionD: "Resistor", correctOption: "A", explanation: "The geomagnetic field resembles that of a bar magnet tilted from the rotation axis.", orderIndex: 10 },
  { id: "neet-physics-magnetism-matter-q12", topicId: "neet-physics-magnetism-matter", text: "Paramagnetic materials are:", optionA: "Weakly attracted by a magnetic field", optionB: "Strongly repelled", optionC: "Permanently magnetic", optionD: "Insulators only", correctOption: "A", explanation: "Paramagnetic substances are weakly attracted and have small positive susceptibility.", orderIndex: 11 },

  // ── New: Electromagnetic Waves ──
  { id: "neet-physics-electromagnetic-waves-q01", topicId: "neet-physics-electromagnetic-waves", text: "Electromagnetic waves travel in a vacuum at a speed of:", optionA: "3 × 10⁸ m/s", optionB: "3 × 10⁶ m/s", optionC: "1500 m/s", optionD: "340 m/s", correctOption: "A", explanation: "EM waves travel at c ≈ 3 × 10⁸ m/s in vacuum.", orderIndex: 0 },
  { id: "neet-physics-electromagnetic-waves-q02", topicId: "neet-physics-electromagnetic-waves", text: "In an electromagnetic wave, the electric and magnetic fields are:", optionA: "Mutually perpendicular and perpendicular to propagation", optionB: "Parallel to each other", optionC: "Along the propagation direction", optionD: "Static", correctOption: "A", explanation: "E and B are perpendicular to each other and to the direction of propagation (transverse).", orderIndex: 1 },
  { id: "neet-physics-electromagnetic-waves-q03", topicId: "neet-physics-electromagnetic-waves", text: "Which has the highest frequency?", optionA: "Radio waves", optionB: "Gamma rays", optionC: "Infrared", optionD: "Visible light", correctOption: "B", explanation: "Gamma rays have the highest frequency (and shortest wavelength) in the EM spectrum.", orderIndex: 2 },
  { id: "neet-physics-electromagnetic-waves-q04", topicId: "neet-physics-electromagnetic-waves", text: "Which has the longest wavelength?", optionA: "Radio waves", optionB: "X-rays", optionC: "Ultraviolet", optionD: "Gamma rays", correctOption: "A", explanation: "Radio waves have the longest wavelength (lowest frequency).", orderIndex: 3 },
  { id: "neet-physics-electromagnetic-waves-q05", topicId: "neet-physics-electromagnetic-waves", text: "Electromagnetic waves require which medium to propagate?", optionA: "No medium (can travel in vacuum)", optionB: "Air only", optionC: "Water only", optionD: "Solid only", correctOption: "A", explanation: "Unlike sound, EM waves need no material medium and travel through vacuum.", orderIndex: 4 },
  { id: "neet-physics-electromagnetic-waves-q06", topicId: "neet-physics-electromagnetic-waves", text: "Microwaves are commonly used in:", optionA: "Radar and ovens", optionB: "Medical X-rays", optionC: "Cancer therapy", optionD: "Night-vision only", correctOption: "A", explanation: "Microwaves are used in radar, communications, and microwave ovens.", orderIndex: 5 },
  { id: "neet-physics-electromagnetic-waves-q07", topicId: "neet-physics-electromagnetic-waves", text: "Ultraviolet radiation is used for:", optionA: "Sterilisation of water/equipment", optionB: "Cooking food", optionC: "AM radio", optionD: "Seeing in the dark", correctOption: "A", explanation: "UV light kills microorganisms, so it is used for sterilisation.", orderIndex: 6 },
  { id: "neet-physics-electromagnetic-waves-q08", topicId: "neet-physics-electromagnetic-waves", text: "The existence of electromagnetic waves was predicted theoretically by:", optionA: "Maxwell", optionB: "Newton", optionC: "Faraday only", optionD: "Bohr", correctOption: "A", explanation: "Maxwell predicted EM waves; Hertz later demonstrated them experimentally.", orderIndex: 7 },
  { id: "neet-physics-electromagnetic-waves-q09", topicId: "neet-physics-electromagnetic-waves", text: "Infrared radiation is chiefly associated with:", optionA: "Heat (thermal radiation)", optionB: "Ionisation", optionC: "Radio broadcasting", optionD: "Gamma emission", correctOption: "A", explanation: "Infrared radiation is felt as heat and used in thermal imaging and heating.", orderIndex: 8 },
  { id: "neet-physics-electromagnetic-waves-q10", topicId: "neet-physics-electromagnetic-waves", text: "X-rays are widely used for:", optionA: "Medical imaging of bones", optionB: "Cooking", optionC: "Radio communication", optionD: "Water sterilisation", correctOption: "A", explanation: "X-rays penetrate soft tissue and are used to image bones and internal structures.", orderIndex: 9 },
  { id: "neet-physics-electromagnetic-waves-q11", topicId: "neet-physics-electromagnetic-waves", text: "Electromagnetic waves carry:", optionA: "Both energy and momentum", optionB: "Only mass", optionC: "Only charge", optionD: "Nothing", correctOption: "A", explanation: "EM waves transport energy and momentum (exerting radiation pressure).", orderIndex: 10 },
  { id: "neet-physics-electromagnetic-waves-q12", topicId: "neet-physics-electromagnetic-waves", text: "The correct order of increasing frequency is:", optionA: "Radio < infrared < visible < X-rays", optionB: "X-rays < visible < radio", optionC: "Visible < radio < infrared", optionD: "Gamma < radio < visible", correctOption: "A", explanation: "Frequency increases: radio < microwave < infrared < visible < UV < X-ray < gamma.", orderIndex: 11 },

  // ── New: Atoms & Bohr Model ──
  { id: "neet-physics-atoms-q01", topicId: "neet-physics-atoms", text: "Rutherford's alpha-scattering experiment established the existence of the:", optionA: "Nucleus", optionB: "Electron", optionC: "Neutron", optionD: "Photon", correctOption: "A", explanation: "The scattering of alpha particles revealed a tiny, dense, positively charged nucleus.", orderIndex: 0 },
  { id: "neet-physics-atoms-q02", topicId: "neet-physics-atoms", text: "In the Bohr model, electrons revolve in orbits with quantised:", optionA: "Angular momentum", optionB: "Charge", optionC: "Mass", optionD: "Colour", correctOption: "A", explanation: "Bohr postulated quantised angular momentum, mvr = nh/2π.", orderIndex: 1 },
  { id: "neet-physics-atoms-q03", topicId: "neet-physics-atoms", text: "The energy of the nth level of a hydrogen atom is:", optionA: "−13.6/n² eV", optionB: "−13.6n² eV", optionC: "13.6/n eV", optionD: "−13.6/n eV", correctOption: "A", explanation: "For hydrogen, Eₙ = −13.6/n² eV, with the ground state (n=1) at −13.6 eV.", orderIndex: 2 },
  { id: "neet-physics-atoms-q04", topicId: "neet-physics-atoms", text: "An electron emits a photon when it jumps from a higher to a:", optionA: "Lower energy level", optionB: "Higher level", optionC: "The nucleus", optionD: "Same level", correctOption: "A", explanation: "A downward transition releases a photon of energy equal to the level difference.", orderIndex: 3 },
  { id: "neet-physics-atoms-q05", topicId: "neet-physics-atoms", text: "The Balmer series of hydrogen lies in which region?", optionA: "Visible", optionB: "Ultraviolet", optionC: "Infrared", optionD: "X-ray", correctOption: "A", explanation: "The Balmer series (transitions to n=2) falls in the visible region.", orderIndex: 4 },
  { id: "neet-physics-atoms-q06", topicId: "neet-physics-atoms", text: "The Lyman series of hydrogen lies in which region?", optionA: "Ultraviolet", optionB: "Visible", optionC: "Infrared", optionD: "Microwave", correctOption: "A", explanation: "The Lyman series (transitions to n=1) lies in the ultraviolet.", orderIndex: 5 },
  { id: "neet-physics-atoms-q07", topicId: "neet-physics-atoms", text: "The ground-state energy of hydrogen is:", optionA: "−13.6 eV", optionB: "−3.4 eV", optionC: "0 eV", optionD: "+13.6 eV", correctOption: "A", explanation: "The ground state (n=1) energy of hydrogen is −13.6 eV.", orderIndex: 6 },
  { id: "neet-physics-atoms-q08", topicId: "neet-physics-atoms", text: "The Rydberg formula gives the reciprocal of the wavelength of spectral lines as:", optionA: "R(1/n₁² − 1/n₂²)", optionB: "R(n₁ − n₂)", optionC: "R/n²", optionD: "Rn²", correctOption: "A", explanation: "1/λ = R(1/n₁² − 1/n₂²) predicts hydrogen's spectral line wavelengths.", orderIndex: 7 },
  { id: "neet-physics-atoms-q09", topicId: "neet-physics-atoms", text: "Bohr's model successfully explains the spectrum of:", optionA: "Hydrogen (single-electron atoms)", optionB: "All atoms", optionC: "Molecules", optionD: "Metals only", correctOption: "A", explanation: "The Bohr model works for hydrogen and hydrogen-like ions but fails for multi-electron atoms.", orderIndex: 8 },
  { id: "neet-physics-atoms-q10", topicId: "neet-physics-atoms", text: "In stationary orbits, electrons:", optionA: "Do not radiate energy", optionB: "Continuously radiate", optionC: "Absorb energy always", optionD: "Have zero energy", correctOption: "A", explanation: "Bohr postulated that electrons in allowed orbits do not radiate energy.", orderIndex: 9 },
  { id: "neet-physics-atoms-q11", topicId: "neet-physics-atoms", text: "The Paschen series of hydrogen lies in which region?", optionA: "Infrared", optionB: "Visible", optionC: "Ultraviolet", optionD: "Gamma", correctOption: "A", explanation: "The Paschen series (transitions to n=3) lies in the infrared.", orderIndex: 10 },
  { id: "neet-physics-atoms-q12", topicId: "neet-physics-atoms", text: "The radius of the electron's orbit in the Bohr model is proportional to:", optionA: "n²", optionB: "1/n²", optionC: "n", optionD: "1/n", correctOption: "A", explanation: "The Bohr orbit radius rₙ ∝ n² (rₙ = n²·a₀ for hydrogen).", orderIndex: 11 },

  // ── New: Nuclei & Radioactivity ──
  { id: "neet-physics-nuclei-q01", topicId: "neet-physics-nuclei", text: "The particles found in the nucleus (nucleons) are:", optionA: "Protons and neutrons", optionB: "Protons and electrons", optionC: "Electrons and neutrons", optionD: "Photons", correctOption: "A", explanation: "The nucleus contains protons and neutrons, collectively called nucleons.", orderIndex: 0 },
  { id: "neet-physics-nuclei-q02", topicId: "neet-physics-nuclei", text: "The energy equivalent of a mass defect is given by:", optionA: "E = mc²", optionB: "E = mgh", optionC: "E = ½mv²", optionD: "E = hf only", correctOption: "A", explanation: "Einstein's relation E = Δmc² converts the nuclear mass defect into binding energy.", orderIndex: 1 },
  { id: "neet-physics-nuclei-q03", topicId: "neet-physics-nuclei", text: "The binding energy per nucleon is maximum near which element?", optionA: "Iron", optionB: "Hydrogen", optionC: "Uranium", optionD: "Helium", correctOption: "A", explanation: "Binding energy per nucleon peaks near iron (A ≈ 56), the most stable nuclei.", orderIndex: 2 },
  { id: "neet-physics-nuclei-q04", topicId: "neet-physics-nuclei", text: "Radioactive decay follows the law:", optionA: "N = N₀e^(−λt)", optionB: "N = N₀ + λt", optionC: "N = N₀λt", optionD: "N = N₀/t", correctOption: "A", explanation: "The number of undecayed nuclei falls exponentially, N = N₀e^(−λt).", orderIndex: 3 },
  { id: "neet-physics-nuclei-q05", topicId: "neet-physics-nuclei", text: "The half-life in terms of the decay constant λ is:", optionA: "0.693/λ", optionB: "λ/0.693", optionC: "λ²", optionD: "1/λ²", correctOption: "A", explanation: "Half-life t½ = ln2/λ = 0.693/λ.", orderIndex: 4 },
  { id: "neet-physics-nuclei-q06", topicId: "neet-physics-nuclei", text: "An alpha particle is identical to a:", optionA: "Helium nucleus", optionB: "Electron", optionC: "Proton", optionD: "Photon", correctOption: "A", explanation: "An alpha particle is a helium nucleus (2 protons + 2 neutrons).", orderIndex: 5 },
  { id: "neet-physics-nuclei-q07", topicId: "neet-physics-nuclei", text: "Nuclear fusion involves:", optionA: "Combining light nuclei to form a heavier one", optionB: "Splitting a heavy nucleus", optionC: "Emitting only alpha particles", optionD: "Electron capture only", correctOption: "A", explanation: "Fusion joins light nuclei (as in the Sun), releasing energy.", orderIndex: 6 },
  { id: "neet-physics-nuclei-q08", topicId: "neet-physics-nuclei", text: "Nuclear fission involves:", optionA: "Splitting a heavy nucleus into lighter ones", optionB: "Combining light nuclei", optionC: "Radioactive dating", optionD: "Electron emission only", correctOption: "A", explanation: "Fission splits a heavy nucleus (e.g., uranium), releasing energy and neutrons.", orderIndex: 7 },
  { id: "neet-physics-nuclei-q09", topicId: "neet-physics-nuclei", text: "A beta particle is a(n):", optionA: "Electron (or positron)", optionB: "Helium nucleus", optionC: "Proton", optionD: "Neutron", correctOption: "A", explanation: "Beta-minus decay emits a high-energy electron from the nucleus.", orderIndex: 8 },
  { id: "neet-physics-nuclei-q10", topicId: "neet-physics-nuclei", text: "Gamma rays emitted during nuclear decay are:", optionA: "High-energy electromagnetic photons", optionB: "Helium nuclei", optionC: "Electrons", optionD: "Neutrons", correctOption: "A", explanation: "Gamma rays are highly penetrating electromagnetic radiation with no charge or mass.", orderIndex: 9 },
  { id: "neet-physics-nuclei-q11", topicId: "neet-physics-nuclei", text: "Nuclear density is approximately:", optionA: "The same for all nuclei", optionB: "Proportional to mass number", optionC: "Zero", optionD: "Proportional to radius", correctOption: "A", explanation: "Since R ∝ A^(1/3), nuclear density is nearly independent of the nucleus (roughly constant).", orderIndex: 10 },
  { id: "neet-physics-nuclei-q12", topicId: "neet-physics-nuclei", text: "The Sun's energy is produced primarily by:", optionA: "Nuclear fusion of hydrogen", optionB: "Nuclear fission of uranium", optionC: "Chemical combustion", optionD: "Radioactive decay only", correctOption: "A", explanation: "The Sun fuses hydrogen into helium, releasing enormous energy.", orderIndex: 11 }
];
