// NEET depth expansion — question-density top-up. Raises the highest-yield
// NEET chapters from 12 to 16 questions each (q13–q16, orderIndex 12–15),
// weighted toward Biology (≈50% of the NEET paper). No new topics or notes.
import type { Question } from "@jyotir/core";

export const neetDepthQuestions: Question[] = [
  // ── Biology: Principles of Inheritance & Variation ──
  { id: "neet-biology-principles-inheritance-variation-q13", topicId: "neet-biology-principles-inheritance-variation", text: "A cross between two heterozygous tall plants (Tt × Tt) gives a phenotypic ratio of:", optionA: "3 tall : 1 dwarf", optionB: "1 tall : 1 dwarf", optionC: "9 : 3 : 3 : 1", optionD: "All tall", correctOption: "A", explanation: "A monohybrid cross of two heterozygotes yields a 3:1 phenotypic ratio.", orderIndex: 12 },
  { id: "neet-biology-principles-inheritance-variation-q14", topicId: "neet-biology-principles-inheritance-variation", text: "The law of independent assortment is illustrated by which type of cross?", optionA: "Dihybrid cross", optionB: "Monohybrid cross", optionC: "Test cross for one gene", optionD: "Reciprocal cross", correctOption: "A", explanation: "Independent assortment is seen in dihybrid crosses (two gene pairs), giving 9:3:3:1.", orderIndex: 13 },
  { id: "neet-biology-principles-inheritance-variation-q15", topicId: "neet-biology-principles-inheritance-variation", text: "In humans, colour blindness is inherited as a(n):", optionA: "X-linked recessive trait", optionB: "Y-linked trait", optionC: "Autosomal dominant trait", optionD: "Mitochondrial trait", correctOption: "A", explanation: "Colour blindness is X-linked recessive, so it is more common in males.", orderIndex: 14 },
  { id: "neet-biology-principles-inheritance-variation-q16", topicId: "neet-biology-principles-inheritance-variation", text: "ABO blood grouping in humans is an example of:", optionA: "Multiple alleles and codominance", optionB: "Simple dominance", optionC: "Sex linkage", optionD: "Polygenic inheritance", correctOption: "A", explanation: "The ABO system involves three alleles (I^A, I^B, i) with I^A and I^B codominant.", orderIndex: 15 },

  // ── Biology: Molecular Basis of Inheritance ──
  { id: "neet-biology-molecular-basis-inheritance-q13", topicId: "neet-biology-molecular-basis-inheritance", text: "In DNA, adenine pairs with thymine through how many hydrogen bonds?", optionA: "Two", optionB: "Three", optionC: "One", optionD: "Four", correctOption: "A", explanation: "A–T pairs form two hydrogen bonds; G–C pairs form three.", orderIndex: 12 },
  { id: "neet-biology-molecular-basis-inheritance-q14", topicId: "neet-biology-molecular-basis-inheritance", text: "The enzyme that synthesises RNA from a DNA template is:", optionA: "RNA polymerase", optionB: "DNA ligase", optionC: "Helicase", optionD: "Primase", correctOption: "A", explanation: "RNA polymerase carries out transcription, building RNA from a DNA template.", orderIndex: 13 },
  { id: "neet-biology-molecular-basis-inheritance-q15", topicId: "neet-biology-molecular-basis-inheritance", text: "The Meselson–Stahl experiment demonstrated that DNA replication is:", optionA: "Semiconservative", optionB: "Conservative", optionC: "Dispersive", optionD: "Random", correctOption: "A", explanation: "Meselson and Stahl showed replication is semiconservative — each new duplex has one old strand.", orderIndex: 14 },
  { id: "neet-biology-molecular-basis-inheritance-q16", topicId: "neet-biology-molecular-basis-inheritance", text: "A codon consists of how many nucleotides?", optionA: "Three", optionB: "Two", optionC: "One", optionD: "Four", correctOption: "A", explanation: "A codon is a triplet of three nucleotides specifying one amino acid.", orderIndex: 15 },

  // ── Biology: Human Reproduction ──
  { id: "neet-biology-human-reproduction-q13", topicId: "neet-biology-human-reproduction", text: "In human females, fertilisation normally occurs in the:", optionA: "Ampulla of the fallopian tube", optionB: "Uterus", optionC: "Ovary", optionD: "Cervix", correctOption: "A", explanation: "Fertilisation typically occurs at the ampullary-isthmic junction of the oviduct.", orderIndex: 12 },
  { id: "neet-biology-human-reproduction-q14", topicId: "neet-biology-human-reproduction", text: "The hormone that triggers ovulation is a surge of:", optionA: "Luteinising hormone (LH)", optionB: "Progesterone", optionC: "Prolactin", optionD: "Oxytocin", correctOption: "A", explanation: "A mid-cycle LH surge triggers ovulation from the mature Graafian follicle.", orderIndex: 13 },
  { id: "neet-biology-human-reproduction-q15", topicId: "neet-biology-human-reproduction", text: "The structure that nourishes the developing foetus and exchanges materials is the:", optionA: "Placenta", optionB: "Corpus luteum", optionC: "Endometrium only", optionD: "Amnion", correctOption: "A", explanation: "The placenta connects foetus and mother for nutrient, gas and waste exchange.", orderIndex: 14 },
  { id: "neet-biology-human-reproduction-q16", topicId: "neet-biology-human-reproduction", text: "The process of release of a secondary oocyte from the ovary is called:", optionA: "Ovulation", optionB: "Implantation", optionC: "Parturition", optionD: "Gastrulation", correctOption: "A", explanation: "Ovulation is the release of the secondary oocyte from the mature follicle.", orderIndex: 15 },

  // ── Biology: Biotechnology: Principles ──
  { id: "neet-biology-biotechnology-principles-q13", topicId: "neet-biology-biotechnology-principles", text: "Restriction endonucleases are enzymes that:", optionA: "Cut DNA at specific recognition sequences", optionB: "Join DNA fragments", optionC: "Synthesise RNA", optionD: "Replicate whole genomes", correctOption: "A", explanation: "Restriction enzymes recognise specific palindromic sequences and cut the DNA there.", orderIndex: 12 },
  { id: "neet-biology-biotechnology-principles-q14", topicId: "neet-biology-biotechnology-principles", text: "The enzyme used to join DNA fragments in recombinant technology is:", optionA: "DNA ligase", optionB: "DNA polymerase", optionC: "Restriction enzyme", optionD: "Amylase", correctOption: "A", explanation: "DNA ligase seals the phosphodiester backbone, joining fragments.", orderIndex: 13 },
  { id: "neet-biology-biotechnology-principles-q15", topicId: "neet-biology-biotechnology-principles", text: "The polymerase chain reaction (PCR) is used to:", optionA: "Amplify specific DNA sequences", optionB: "Cut DNA", optionC: "Translate proteins", optionD: "Sequence proteins", correctOption: "A", explanation: "PCR amplifies a target DNA segment through repeated cycles of denaturation, annealing and extension.", orderIndex: 14 },
  { id: "neet-biology-biotechnology-principles-q16", topicId: "neet-biology-biotechnology-principles", text: "A commonly used cloning vector derived from bacteria is a:", optionA: "Plasmid", optionB: "Ribosome", optionC: "Lysosome", optionD: "Centriole", correctOption: "A", explanation: "Plasmids are extrachromosomal circular DNA used as cloning vectors.", orderIndex: 15 },

  // ── Biology: Ecosystem & Biodiversity ──
  { id: "neet-biology-ecosystem-biodiversity-q13", topicId: "neet-biology-ecosystem-biodiversity", text: "The 10% law of energy transfer between trophic levels was given by:", optionA: "Lindeman", optionB: "Darwin", optionC: "Mendel", optionD: "Haeckel", correctOption: "A", explanation: "Lindeman's 10% law states only ~10% of energy passes to the next trophic level.", orderIndex: 12 },
  { id: "neet-biology-ecosystem-biodiversity-q14", topicId: "neet-biology-ecosystem-biodiversity", text: "An inverted pyramid of numbers is typically seen in a:", optionA: "Single tree ecosystem", optionB: "Grassland", optionC: "Pond", optionD: "Desert", correctOption: "A", explanation: "A big tree supporting many insects/birds gives an inverted pyramid of numbers.", orderIndex: 13 },
  { id: "neet-biology-ecosystem-biodiversity-q15", topicId: "neet-biology-ecosystem-biodiversity", text: "Organisms that break down dead organic matter are called:", optionA: "Decomposers", optionB: "Producers", optionC: "Primary consumers", optionD: "Carnivores", correctOption: "A", explanation: "Decomposers (saprotrophs) break down detritus, recycling nutrients.", orderIndex: 14 },
  { id: "neet-biology-ecosystem-biodiversity-q16", topicId: "neet-biology-ecosystem-biodiversity", text: "The most species-rich region on Earth in terms of biodiversity is the:", optionA: "Tropical rainforest", optionB: "Tundra", optionC: "Desert", optionD: "Temperate grassland", correctOption: "A", explanation: "Tropical rainforests hold the greatest biodiversity of any biome.", orderIndex: 15 },

  // ── Biology: Cell Cycle & Cell Division ──
  { id: "neet-biology-cell-cycle-cell-division-q13", topicId: "neet-biology-cell-cycle-cell-division", text: "DNA replication (S phase) occurs during which stage of the cell cycle?", optionA: "Interphase", optionB: "Metaphase", optionC: "Anaphase", optionD: "Telophase", correctOption: "A", explanation: "DNA is synthesised in the S phase of interphase, before mitosis.", orderIndex: 12 },
  { id: "neet-biology-cell-cycle-cell-division-q14", topicId: "neet-biology-cell-cycle-cell-division", text: "Sister chromatids separate and move to opposite poles during:", optionA: "Anaphase", optionB: "Prophase", optionC: "Metaphase", optionD: "Interphase", correctOption: "A", explanation: "In anaphase, sister chromatids split and migrate to opposite poles.", orderIndex: 13 },
  { id: "neet-biology-cell-cycle-cell-division-q15", topicId: "neet-biology-cell-cycle-cell-division", text: "Meiosis results in daughter cells that are:", optionA: "Haploid (n)", optionB: "Diploid (2n)", optionC: "Tetraploid", optionD: "Identical to the parent", correctOption: "A", explanation: "Meiosis halves the chromosome number, producing haploid gametes.", orderIndex: 14 },
  { id: "neet-biology-cell-cycle-cell-division-q16", topicId: "neet-biology-cell-cycle-cell-division", text: "Crossing over, which increases genetic variation, occurs during:", optionA: "Prophase I of meiosis", optionB: "Metaphase of mitosis", optionC: "Anaphase II", optionD: "The S phase", correctOption: "A", explanation: "Crossing over between homologous chromosomes occurs in pachytene of prophase I.", orderIndex: 15 },

  // ── Biology: Photosynthesis in Higher Plants ──
  { id: "neet-biology-photosynthesis-higher-plants-q13", topicId: "neet-biology-photosynthesis-higher-plants", text: "The light-dependent reactions of photosynthesis occur in the:", optionA: "Thylakoid membranes", optionB: "Stroma", optionC: "Cytoplasm", optionD: "Mitochondria", correctOption: "A", explanation: "The light reactions occur on the thylakoid membranes of chloroplasts.", orderIndex: 12 },
  { id: "neet-biology-photosynthesis-higher-plants-q14", topicId: "neet-biology-photosynthesis-higher-plants", text: "The Calvin cycle (dark reactions) takes place in the:", optionA: "Stroma", optionB: "Thylakoid lumen", optionC: "Grana", optionD: "Nucleus", correctOption: "A", explanation: "Carbon fixation via the Calvin cycle occurs in the stroma.", orderIndex: 13 },
  { id: "neet-biology-photosynthesis-higher-plants-q15", topicId: "neet-biology-photosynthesis-higher-plants", text: "The primary CO₂ acceptor in C3 plants is:", optionA: "RuBP", optionB: "PEP", optionC: "OAA", optionD: "Pyruvate", correctOption: "A", explanation: "In C3 plants RuBP accepts CO₂, catalysed by RuBisCO.", orderIndex: 14 },
  { id: "neet-biology-photosynthesis-higher-plants-q16", topicId: "neet-biology-photosynthesis-higher-plants", text: "In C4 plants, the primary CO₂ fixation product is the four-carbon:", optionA: "Oxaloacetic acid (OAA)", optionB: "3-PGA", optionC: "RuBP", optionD: "Glucose", correctOption: "A", explanation: "C4 plants first fix CO₂ into OAA via PEP carboxylase in mesophyll cells.", orderIndex: 15 },

  // ── Biology: Human Health & Disease ──
  { id: "neet-biology-human-health-disease-q13", topicId: "neet-biology-human-health-disease", text: "Malaria is caused by a protozoan of the genus:", optionA: "Plasmodium", optionB: "Entamoeba", optionC: "Trypanosoma", optionD: "Leishmania", correctOption: "A", explanation: "Plasmodium species cause malaria, transmitted by female Anopheles mosquitoes.", orderIndex: 12 },
  { id: "neet-biology-human-health-disease-q14", topicId: "neet-biology-human-health-disease", text: "Antibodies are produced by which type of cell?", optionA: "B lymphocytes (plasma cells)", optionB: "Red blood cells", optionC: "Platelets", optionD: "Neurons", correctOption: "A", explanation: "B lymphocytes differentiate into plasma cells that secrete antibodies.", orderIndex: 13 },
  { id: "neet-biology-human-health-disease-q15", topicId: "neet-biology-human-health-disease", text: "The AIDS-causing virus HIV primarily attacks which cells?", optionA: "Helper T lymphocytes", optionB: "Neurons", optionC: "Hepatocytes", optionD: "Osteocytes", correctOption: "A", explanation: "HIV infects and destroys helper T (CD4+) cells, weakening immunity.", orderIndex: 14 },
  { id: "neet-biology-human-health-disease-q16", topicId: "neet-biology-human-health-disease", text: "Vaccination provides which type of immunity?", optionA: "Active acquired immunity", optionB: "Passive immunity", optionC: "Innate immunity only", optionD: "No immunity", correctOption: "A", explanation: "A vaccine stimulates the body to make its own antibodies — active acquired immunity.", orderIndex: 15 },

  // ── Chemistry: Chemical Bonding & Molecular Structure ──
  { id: "neet-chemistry-chemical-bonding-molecular-structure-q13", topicId: "neet-chemistry-chemical-bonding-molecular-structure", text: "The shape of a methane (CH₄) molecule is:", optionA: "Tetrahedral", optionB: "Trigonal planar", optionC: "Linear", optionD: "Bent", correctOption: "A", explanation: "sp³ hybridised carbon with four bond pairs gives a tetrahedral shape.", orderIndex: 12 },
  { id: "neet-chemistry-chemical-bonding-molecular-structure-q14", topicId: "neet-chemistry-chemical-bonding-molecular-structure", text: "The bond angle in a water molecule is approximately:", optionA: "104.5°", optionB: "120°", optionC: "180°", optionD: "90°", correctOption: "A", explanation: "Two lone pairs on oxygen compress the H–O–H angle to about 104.5°.", orderIndex: 13 },
  { id: "neet-chemistry-chemical-bonding-molecular-structure-q15", topicId: "neet-chemistry-chemical-bonding-molecular-structure", text: "According to MOT, the bond order of the O₂ molecule is:", optionA: "2", optionB: "1", optionC: "3", optionD: "0", correctOption: "A", explanation: "O₂ has bond order (8−4)/2 = 2 and is paramagnetic.", orderIndex: 14 },
  { id: "neet-chemistry-chemical-bonding-molecular-structure-q16", topicId: "neet-chemistry-chemical-bonding-molecular-structure", text: "A coordinate (dative) bond involves electron pair sharing where both electrons come from:", optionA: "One atom", optionB: "Both atoms equally", optionC: "No atom", optionD: "A metal only", correctOption: "A", explanation: "In a coordinate bond one atom donates both electrons of the shared pair.", orderIndex: 15 },

  // ── Chemistry: Equilibrium ──
  { id: "neet-chemistry-equilibrium-q13", topicId: "neet-chemistry-equilibrium", text: "For the reaction N₂ + 3H₂ ⇌ 2NH₃, increasing pressure shifts the equilibrium:", optionA: "Toward the products (fewer moles of gas)", optionB: "Toward the reactants", optionC: "No shift", optionD: "Toward solids", correctOption: "A", explanation: "By Le Chatelier's principle, higher pressure favours the side with fewer gas moles (NH₃).", orderIndex: 12 },
  { id: "neet-chemistry-equilibrium-q14", topicId: "neet-chemistry-equilibrium", text: "The pH of a neutral aqueous solution at 25°C is:", optionA: "7", optionB: "0", optionC: "14", optionD: "1", correctOption: "A", explanation: "At 25°C a neutral solution has [H⁺] = 10⁻⁷ M, so pH = 7.", orderIndex: 13 },
  { id: "neet-chemistry-equilibrium-q15", topicId: "neet-chemistry-equilibrium", text: "A buffer solution resists changes in:", optionA: "pH", optionB: "Temperature", optionC: "Volume", optionD: "Colour", correctOption: "A", explanation: "A buffer resists pH change on adding small amounts of acid or base.", orderIndex: 14 },
  { id: "neet-chemistry-equilibrium-q16", topicId: "neet-chemistry-equilibrium", text: "For a reaction at equilibrium, the value of ΔG is:", optionA: "Zero", optionB: "Positive", optionC: "Negative", optionD: "Infinite", correctOption: "A", explanation: "At equilibrium the Gibbs free energy change ΔG equals zero.", orderIndex: 15 },

  // ── Chemistry: Aldehydes, Ketones & Carboxylic Acids ──
  { id: "neet-chemistry-aldehydes-ketones-carboxylic-acids-q13", topicId: "neet-chemistry-aldehydes-ketones-carboxylic-acids", text: "The functional group present in aldehydes is:", optionA: "–CHO", optionB: "–COOH", optionC: "–OH", optionD: "–NH₂", correctOption: "A", explanation: "Aldehydes contain the terminal carbonyl group –CHO.", orderIndex: 12 },
  { id: "neet-chemistry-aldehydes-ketones-carboxylic-acids-q14", topicId: "neet-chemistry-aldehydes-ketones-carboxylic-acids", text: "Tollens' reagent gives a silver mirror with:", optionA: "Aldehydes", optionB: "Ketones", optionC: "Alcohols", optionD: "Ethers", correctOption: "A", explanation: "Aldehydes reduce Tollens' reagent, depositing a silver mirror; ketones do not.", orderIndex: 13 },
  { id: "neet-chemistry-aldehydes-ketones-carboxylic-acids-q15", topicId: "neet-chemistry-aldehydes-ketones-carboxylic-acids", text: "Carboxylic acids contain which functional group?", optionA: "–COOH", optionB: "–CHO", optionC: "–CO–", optionD: "–OH", correctOption: "A", explanation: "Carboxylic acids have the carboxyl group –COOH.", orderIndex: 14 },
  { id: "neet-chemistry-aldehydes-ketones-carboxylic-acids-q16", topicId: "neet-chemistry-aldehydes-ketones-carboxylic-acids", text: "The aldol condensation requires the carbonyl compound to have a(n):", optionA: "Alpha-hydrogen", optionB: "Benzene ring", optionC: "Halogen", optionD: "Nitro group", correctOption: "A", explanation: "Aldol condensation needs an α-hydrogen to form the enolate intermediate.", orderIndex: 15 },

  // ── Chemistry: Coordination Compounds ──
  { id: "neet-chemistry-coordination-compounds-q13", topicId: "neet-chemistry-coordination-compounds", text: "The coordination number of the central metal in [Co(NH₃)₆]³⁺ is:", optionA: "6", optionB: "3", optionC: "4", optionD: "2", correctOption: "A", explanation: "Six ammonia ligands give a coordination number of 6.", orderIndex: 12 },
  { id: "neet-chemistry-coordination-compounds-q14", topicId: "neet-chemistry-coordination-compounds", text: "The oxidation state of iron in [Fe(CN)₆]³⁻ is:", optionA: "+3", optionB: "+2", optionC: "+6", optionD: "0", correctOption: "A", explanation: "Six CN⁻ (−1 each) with an overall −3 charge gives iron +3.", orderIndex: 13 },
  { id: "neet-chemistry-coordination-compounds-q15", topicId: "neet-chemistry-coordination-compounds", text: "EDTA is classified as which type of ligand?", optionA: "Hexadentate", optionB: "Monodentate", optionC: "Bidentate", optionD: "Ambidentate", correctOption: "A", explanation: "EDTA binds through six donor atoms, making it hexadentate.", orderIndex: 14 },
  { id: "neet-chemistry-coordination-compounds-q16", topicId: "neet-chemistry-coordination-compounds", text: "According to crystal field theory, a strong-field ligand tends to form:", optionA: "Low-spin complexes", optionB: "High-spin complexes always", optionC: "No complex", optionD: "Ionic bonds only", correctOption: "A", explanation: "Strong-field ligands cause large splitting, favouring electron pairing (low spin).", orderIndex: 15 },

  // ── Physics: Electrostatics ──
  { id: "neet-physics-electrostatics-q13", topicId: "neet-physics-electrostatics", text: "The electric field inside a hollow charged conductor is:", optionA: "Zero", optionB: "kQ/r²", optionC: "Uniform and non-zero", optionD: "Infinite", correctOption: "A", explanation: "By Gauss's law the field inside a hollow conductor's cavity is zero.", orderIndex: 12 },
  { id: "neet-physics-electrostatics-q14", topicId: "neet-physics-electrostatics", text: "Coulomb's law states that the force between two point charges is inversely proportional to the:", optionA: "Square of the distance", optionB: "Distance", optionC: "Cube of the distance", optionD: "Product of charges", correctOption: "A", explanation: "Coulomb's force varies as 1/r², inversely with the square of separation.", orderIndex: 13 },
  { id: "neet-physics-electrostatics-q15", topicId: "neet-physics-electrostatics", text: "The work done in moving a charge along an equipotential surface is:", optionA: "Zero", optionB: "qV", optionC: "Maximum", optionD: "qE·d", correctOption: "A", explanation: "No work is done moving a charge on an equipotential surface (ΔV = 0).", orderIndex: 14 },
  { id: "neet-physics-electrostatics-q16", topicId: "neet-physics-electrostatics", text: "The SI unit of electric field intensity is:", optionA: "N/C (or V/m)", optionB: "C/N", optionC: "J/C", optionD: "C·m", correctOption: "A", explanation: "Electric field is force per unit charge, N/C, equivalent to V/m.", orderIndex: 15 },

  // ── Physics: Current Electricity ──
  { id: "neet-physics-current-electricity-q13", topicId: "neet-physics-current-electricity", text: "Ohm's law states that V equals:", optionA: "IR", optionB: "I/R", optionC: "R/I", optionD: "I²R", correctOption: "A", explanation: "Ohm's law: V = IR for an ohmic conductor.", orderIndex: 12 },
  { id: "neet-physics-current-electricity-q14", topicId: "neet-physics-current-electricity", text: "The equivalent resistance of two resistors R in parallel is:", optionA: "R/2", optionB: "2R", optionC: "R", optionD: "R²", correctOption: "A", explanation: "Two equal resistances R in parallel give R/2.", orderIndex: 13 },
  { id: "neet-physics-current-electricity-q15", topicId: "neet-physics-current-electricity", text: "The power dissipated in a resistor carrying current I is:", optionA: "I²R", optionB: "IR", optionC: "I/R", optionD: "IR²", correctOption: "A", explanation: "Power dissipated = I²R (also VI or V²/R).", orderIndex: 14 },
  { id: "neet-physics-current-electricity-q16", topicId: "neet-physics-current-electricity", text: "Kirchhoff's junction rule is based on the conservation of:", optionA: "Charge", optionB: "Energy", optionC: "Momentum", optionD: "Mass", correctOption: "A", explanation: "The junction (current) rule expresses conservation of electric charge.", orderIndex: 15 },

  // ── Physics: System of Particles & Rotational Motion ──
  { id: "neet-physics-rotational-motion-q13", topicId: "neet-physics-rotational-motion", text: "The moment of inertia of a solid sphere about its diameter is:", optionA: "(2/5)MR²", optionB: "(2/3)MR²", optionC: "MR²", optionD: "½MR²", correctOption: "A", explanation: "A solid sphere has I = (2/5)MR² about a diameter.", orderIndex: 12 },
  { id: "neet-physics-rotational-motion-q14", topicId: "neet-physics-rotational-motion", text: "Angular momentum is conserved when the net external:", optionA: "Torque is zero", optionB: "Force is zero", optionC: "Power is zero", optionD: "Energy is zero", correctOption: "A", explanation: "Zero net external torque conserves angular momentum.", orderIndex: 13 },
  { id: "neet-physics-rotational-motion-q15", topicId: "neet-physics-rotational-motion", text: "Torque is the rotational analogue of:", optionA: "Force", optionB: "Momentum", optionC: "Displacement", optionD: "Energy", correctOption: "A", explanation: "Torque plays the role in rotation that force plays in translation.", orderIndex: 14 },
  { id: "neet-physics-rotational-motion-q16", topicId: "neet-physics-rotational-motion", text: "For a body rolling without slipping, the velocity of the contact point is:", optionA: "Zero", optionB: "v", optionC: "2v", optionD: "ωR/2", correctOption: "A", explanation: "In rolling without slipping the point of contact is instantaneously at rest.", orderIndex: 15 },

  // ── Physics: Dual Nature & Modern Physics ──
  { id: "neet-physics-dual-nature-modern-physics-q13", topicId: "neet-physics-dual-nature-modern-physics", text: "The de Broglie wavelength of a particle of momentum p is:", optionA: "h/p", optionB: "p/h", optionC: "hp", optionD: "h/p²", correctOption: "A", explanation: "λ = h/p, the de Broglie relation for matter waves.", orderIndex: 12 },
  { id: "neet-physics-dual-nature-modern-physics-q14", topicId: "neet-physics-dual-nature-modern-physics", text: "In the photoelectric effect, the stopping potential depends on the light's:", optionA: "Frequency", optionB: "Intensity", optionC: "Polarisation", optionD: "Phase", correctOption: "A", explanation: "Stopping potential depends on frequency, not intensity (Einstein's relation).", orderIndex: 13 },
  { id: "neet-physics-dual-nature-modern-physics-q15", topicId: "neet-physics-dual-nature-modern-physics", text: "The work function of a metal is the minimum energy needed to:", optionA: "Eject an electron from the surface", optionB: "Ionise the nucleus", optionC: "Melt the metal", optionD: "Excite an electron to n=2", correctOption: "A", explanation: "The work function is the least energy required to free a surface electron.", orderIndex: 14 },
  { id: "neet-physics-dual-nature-modern-physics-q16", topicId: "neet-physics-dual-nature-modern-physics", text: "The energy of a photon of frequency ν is given by:", optionA: "hν", optionB: "h/ν", optionC: "ν/h", optionD: "hν²", correctOption: "A", explanation: "Photon energy E = hν, where h is Planck's constant.", orderIndex: 15 }
];
