// SSC CGL depth expansion — question-density top-up. Raises the highest-yield
// SSC CGL topics from 12 to 16 questions each (q13–q16, orderIndex 12–15). No
// new topics or study notes.
import type { Question } from "@jyotir/core";

export const sscDepthQuestions: Question[] = [
  // ── Quant: Percentages & Profit-Loss ──
  { id: "ssc-cgl-quant-percentages-profit-loss-q13", topicId: "ssc-cgl-quant-percentages-profit-loss", text: "An article bought for 500 is sold for 600. The profit percentage is:", optionA: "20%", optionB: "16.7%", optionC: "25%", optionD: "10%", correctOption: "A", explanation: "Profit = 100 on 500, so profit% = 100/500 × 100 = 20%.", orderIndex: 12 },
  { id: "ssc-cgl-quant-percentages-profit-loss-q14", topicId: "ssc-cgl-quant-percentages-profit-loss", text: "If the price of an item increases from 200 to 250, the percentage increase is:", optionA: "25%", optionB: "20%", optionC: "50%", optionD: "10%", correctOption: "A", explanation: "Increase = 50 on 200, so 50/200 × 100 = 25%.", orderIndex: 13 },
  { id: "ssc-cgl-quant-percentages-profit-loss-q15", topicId: "ssc-cgl-quant-percentages-profit-loss", text: "A shopkeeper offers a 10% discount on a marked price of 500. The selling price is:", optionA: "450", optionB: "490", optionC: "400", optionD: "550", correctOption: "A", explanation: "SP = 500 × 0.90 = 450.", orderIndex: 14 },
  { id: "ssc-cgl-quant-percentages-profit-loss-q16", topicId: "ssc-cgl-quant-percentages-profit-loss", text: "Selling at a loss of 20%, an item priced (cost) 250 fetches:", optionA: "200", optionB: "230", optionC: "300", optionD: "210", correctOption: "A", explanation: "SP = 250 × 0.80 = 200.", orderIndex: 15 },

  // ── Quant: Time, Speed & Distance ──
  { id: "ssc-cgl-quant-time-speed-distance-q13", topicId: "ssc-cgl-quant-time-speed-distance", text: "A car travels 180 km in 3 hours. Its average speed is:", optionA: "60 km/h", optionB: "50 km/h", optionC: "540 km/h", optionD: "45 km/h", correctOption: "A", explanation: "Speed = distance/time = 180/3 = 60 km/h.", orderIndex: 12 },
  { id: "ssc-cgl-quant-time-speed-distance-q14", topicId: "ssc-cgl-quant-time-speed-distance", text: "To convert 72 km/h into m/s, multiply by 5/18 to get:", optionA: "20 m/s", optionB: "25 m/s", optionC: "18 m/s", optionD: "10 m/s", correctOption: "A", explanation: "Convert: 72 × 5/18 = 20 m/s.", orderIndex: 13 },
  { id: "ssc-cgl-quant-time-speed-distance-q15", topicId: "ssc-cgl-quant-time-speed-distance", text: "Two trains move toward each other at 40 and 60 km/h. Their relative speed is:", optionA: "100 km/h", optionB: "20 km/h", optionC: "50 km/h", optionD: "2400 km/h", correctOption: "A", explanation: "Approaching speeds add: 40 + 60 = 100 km/h.", orderIndex: 14 },
  { id: "ssc-cgl-quant-time-speed-distance-q16", topicId: "ssc-cgl-quant-time-speed-distance", text: "A man covers 30 km at 10 km/h. The time taken is:", optionA: "3 hours", optionB: "2 hours", optionC: "300 hours", optionD: "1 hour", correctOption: "A", explanation: "Time = distance/speed = 30/10 = 3 hours.", orderIndex: 15 },

  // ── Quant: Simple & Compound Interest ──
  { id: "ssc-cgl-quant-simple-compound-interest-q13", topicId: "ssc-cgl-quant-simple-compound-interest", text: "The simple interest on 1000 at 5% per annum for 2 years is:", optionA: "100", optionB: "50", optionC: "1050", optionD: "200", correctOption: "A", explanation: "SI = PRT/100 = 1000 × 5 × 2 / 100 = 100.", orderIndex: 12 },
  { id: "ssc-cgl-quant-simple-compound-interest-q14", topicId: "ssc-cgl-quant-simple-compound-interest", text: "The compound interest on 1000 at 10% per annum for 2 years is:", optionA: "210", optionB: "200", optionC: "100", optionD: "121", correctOption: "A", explanation: "Amount = 1000(1.1)² = 1210, so CI = 210.", orderIndex: 13 },
  { id: "ssc-cgl-quant-simple-compound-interest-q15", topicId: "ssc-cgl-quant-simple-compound-interest", text: "At simple interest, a sum doubles in 10 years. The annual rate is:", optionA: "10%", optionB: "5%", optionC: "20%", optionD: "12%", correctOption: "A", explanation: "To double, SI = P, so R = 100/T = 100/10 = 10%.", orderIndex: 14 },
  { id: "ssc-cgl-quant-simple-compound-interest-q16", topicId: "ssc-cgl-quant-simple-compound-interest", text: "For the same principal, rate and time (>1 year), compound interest is:", optionA: "Greater than simple interest", optionB: "Less than simple interest", optionC: "Equal to simple interest", optionD: "Always zero", correctOption: "A", explanation: "CI exceeds SI beyond the first period because interest is earned on interest.", orderIndex: 15 },

  // ── Quant: Number System (LCM/HCF) ──
  { id: "ssc-cgl-quant-number-system-q13", topicId: "ssc-cgl-quant-number-system", text: "The HCF of 12 and 18 is:", optionA: "6", optionB: "36", optionC: "3", optionD: "2", correctOption: "A", explanation: "The greatest common divisor of 12 and 18 is 6.", orderIndex: 12 },
  { id: "ssc-cgl-quant-number-system-q14", topicId: "ssc-cgl-quant-number-system", text: "The LCM of 4 and 6 is:", optionA: "12", optionB: "24", optionC: "2", optionD: "10", correctOption: "A", explanation: "The least common multiple of 4 and 6 is 12.", orderIndex: 13 },
  { id: "ssc-cgl-quant-number-system-q15", topicId: "ssc-cgl-quant-number-system", text: "For two numbers, the product of the LCM and HCF equals:", optionA: "The product of the numbers", optionB: "Their sum", optionC: "Their difference", optionD: "Their average", correctOption: "A", explanation: "LCM × HCF = product of the two numbers.", orderIndex: 14 },
  { id: "ssc-cgl-quant-number-system-q16", topicId: "ssc-cgl-quant-number-system", text: "A number divisible by both 2 and 3 is always divisible by:", optionA: "6", optionB: "5", optionC: "4", optionD: "9", correctOption: "A", explanation: "Divisibility by 2 and 3 (co-prime) implies divisibility by 6.", orderIndex: 15 },

  // ── Reasoning: Coding-Decoding & Series ──
  { id: "ssc-cgl-reasoning-coding-decoding-series-q13", topicId: "ssc-cgl-reasoning-coding-decoding-series", text: "If CAT is coded as DBU (each letter +1), then DOG is coded as:", optionA: "EPH", optionB: "CNF", optionC: "EPG", optionD: "FQI", correctOption: "A", explanation: "Shifting each letter forward by one: D→E, O→P, G→H gives EPH.", orderIndex: 12 },
  { id: "ssc-cgl-reasoning-coding-decoding-series-q14", topicId: "ssc-cgl-reasoning-coding-decoding-series", text: "Find the next term: 2, 6, 12, 20, __", optionA: "30", optionB: "28", optionC: "24", optionD: "26", correctOption: "A", explanation: "Differences 4, 6, 8, 10 give 20 + 10 = 30.", orderIndex: 13 },
  { id: "ssc-cgl-reasoning-coding-decoding-series-q15", topicId: "ssc-cgl-reasoning-coding-decoding-series", text: "Complete the series: 3, 9, 27, 81, __", optionA: "243", optionB: "162", optionC: "108", optionD: "324", correctOption: "A", explanation: "Each term is multiplied by 3: 81 × 3 = 243.", orderIndex: 14 },
  { id: "ssc-cgl-reasoning-coding-decoding-series-q16", topicId: "ssc-cgl-reasoning-coding-decoding-series", text: "In a code, if A=1, B=2, ..., then the sum for the word 'BAD' is:", optionA: "7", optionB: "6", optionC: "8", optionD: "5", correctOption: "A", explanation: "B(2) + A(1) + D(4) = 7.", orderIndex: 15 },

  // ── Reasoning: Blood Relations ──
  { id: "ssc-cgl-reasoning-blood-relations-q13", topicId: "ssc-cgl-reasoning-blood-relations", text: "Your father's brother is your:", optionA: "Uncle", optionB: "Nephew", optionC: "Cousin", optionD: "Brother", correctOption: "A", explanation: "The father's brother is one's (paternal) uncle.", orderIndex: 12 },
  { id: "ssc-cgl-reasoning-blood-relations-q14", topicId: "ssc-cgl-reasoning-blood-relations", text: "Your mother's mother is your:", optionA: "Grandmother", optionB: "Aunt", optionC: "Sister", optionD: "Niece", correctOption: "A", explanation: "The mother's mother is the maternal grandmother.", orderIndex: 13 },
  { id: "ssc-cgl-reasoning-blood-relations-q15", topicId: "ssc-cgl-reasoning-blood-relations", text: "Pointing to a man, a woman said 'He is the son of my grandfather's only son.' The man is the woman's:", optionA: "Brother", optionB: "Father", optionC: "Uncle", optionD: "Cousin", correctOption: "A", explanation: "Her grandfather's only son is her father; his son is her brother.", orderIndex: 14 },
  { id: "ssc-cgl-reasoning-blood-relations-q16", topicId: "ssc-cgl-reasoning-blood-relations", text: "Your sister's daughter is your:", optionA: "Niece", optionB: "Cousin", optionC: "Aunt", optionD: "Sister", correctOption: "A", explanation: "A sister's daughter is one's niece.", orderIndex: 15 },

  // ── Reasoning: Syllogism ──
  { id: "ssc-cgl-reasoning-syllogism-q13", topicId: "ssc-cgl-reasoning-syllogism", text: "All cats are animals. All animals breathe. Therefore:", optionA: "All cats breathe", optionB: "All animals are cats", optionC: "No cat breathes", optionD: "Some animals are plants", correctOption: "A", explanation: "By transitivity, all cats are animals and all animals breathe, so all cats breathe.", orderIndex: 12 },
  { id: "ssc-cgl-reasoning-syllogism-q14", topicId: "ssc-cgl-reasoning-syllogism", text: "In syllogisms, a conclusion is valid only if it:", optionA: "Necessarily follows from the premises", optionB: "Sounds reasonable", optionC: "Is factually true", optionD: "Is possible", correctOption: "A", explanation: "Validity requires the conclusion to follow necessarily from the given premises.", orderIndex: 13 },
  { id: "ssc-cgl-reasoning-syllogism-q15", topicId: "ssc-cgl-reasoning-syllogism", text: "'No A is B' logically implies:", optionA: "No B is A", optionB: "All B are A", optionC: "Some A are B", optionD: "All A are B", correctOption: "A", explanation: "A universal negative converts: 'No A is B' means 'No B is A'.", orderIndex: 14 },
  { id: "ssc-cgl-reasoning-syllogism-q16", topicId: "ssc-cgl-reasoning-syllogism", text: "All roses are flowers. Some flowers fade quickly. It definitely follows that:", optionA: "Nothing definite about roses fading", optionB: "All roses fade quickly", optionC: "No rose fades", optionD: "Some roses are not flowers", correctOption: "A", explanation: "The 'some flowers fade' premise does not necessarily include roses, so nothing definite follows.", orderIndex: 15 },

  // ── English: Spotting Errors ──
  { id: "ssc-cgl-english-spotting-errors-q13", topicId: "ssc-cgl-english-spotting-errors", text: "Choose the correct sentence:", optionA: "He has been living here since 2010.", optionB: "He is living here since 2010.", optionC: "He living here since 2010.", optionD: "He has living here since 2010.", correctOption: "A", explanation: "'Since' with a point in time takes the present perfect continuous: has been living.", orderIndex: 12 },
  { id: "ssc-cgl-english-spotting-errors-q14", topicId: "ssc-cgl-english-spotting-errors", text: "Identify the correct subject-verb agreement:", optionA: "Each of the boys was present.", optionB: "Each of the boys were present.", optionC: "Each of the boys are present.", optionD: "Each of the boys have present.", correctOption: "A", explanation: "'Each' is singular, so it takes the singular verb 'was'.", orderIndex: 13 },
  { id: "ssc-cgl-english-spotting-errors-q15", topicId: "ssc-cgl-english-spotting-errors", text: "Choose the grammatically correct option:", optionA: "One of my friends is a doctor.", optionB: "One of my friends are a doctor.", optionC: "One of my friend is a doctor.", optionD: "One of my friends are doctors.", correctOption: "A", explanation: "'One of my friends' takes a singular verb: 'is'.", orderIndex: 14 },
  { id: "ssc-cgl-english-spotting-errors-q16", topicId: "ssc-cgl-english-spotting-errors", text: "Select the sentence with correct preposition usage:", optionA: "She is good at mathematics.", optionB: "She is good in mathematics.", optionC: "She is good on mathematics.", optionD: "She is good for mathematics.", correctOption: "A", explanation: "The idiomatic preposition after 'good' for a skill is 'at'.", orderIndex: 15 },

  // ── Quant: Ratio & Proportion ──
  { id: "ssc-cgl-quant-ratio-proportion-q13", topicId: "ssc-cgl-quant-ratio-proportion", text: "If a : b = 2 : 3 and b = 12, then a equals:", optionA: "8", optionB: "18", optionC: "6", optionD: "9", correctOption: "A", explanation: "a/b = 2/3, so a = (2/3) × 12 = 8.", orderIndex: 12 },
  { id: "ssc-cgl-quant-ratio-proportion-q14", topicId: "ssc-cgl-quant-ratio-proportion", text: "Divide 300 in the ratio 2 : 3. The larger part is:", optionA: "180", optionB: "120", optionC: "150", optionD: "200", correctOption: "A", explanation: "Total 5 parts; larger = 3/5 × 300 = 180.", orderIndex: 13 },
  { id: "ssc-cgl-quant-ratio-proportion-q15", topicId: "ssc-cgl-quant-ratio-proportion", text: "The fourth proportional to 3, 6 and 5 is:", optionA: "10", optionB: "15", optionC: "8", optionD: "9", correctOption: "A", explanation: "3 : 6 :: 5 : x ⇒ x = (6 × 5)/3 = 10.", orderIndex: 14 },
  { id: "ssc-cgl-quant-ratio-proportion-q16", topicId: "ssc-cgl-quant-ratio-proportion", text: "If the ratio of two numbers is 5 : 7 and their sum is 96, the smaller number is:", optionA: "40", optionB: "56", optionC: "48", optionD: "35", correctOption: "A", explanation: "12 parts = 96, so 5 parts = 5 × 8 = 40.", orderIndex: 15 },

  // ── Quant: Averages ──
  { id: "ssc-cgl-quant-averages-q13", topicId: "ssc-cgl-quant-averages", text: "The average of 5, 10 and 15 is:", optionA: "10", optionB: "15", optionC: "30", optionD: "5", correctOption: "A", explanation: "Sum is 5+10+15 = 30; divide by 3 to get 10.", orderIndex: 12 },
  { id: "ssc-cgl-quant-averages-q14", topicId: "ssc-cgl-quant-averages", text: "The average of the first five even numbers (2,4,6,8,10) is:", optionA: "6", optionB: "5", optionC: "10", optionD: "30", correctOption: "A", explanation: "Sum is 2+4+6+8+10 = 30; divide by 5 to get 6.", orderIndex: 13 },
  { id: "ssc-cgl-quant-averages-q15", topicId: "ssc-cgl-quant-averages", text: "If the average of 4 numbers is 20, their sum is:", optionA: "80", optionB: "24", optionC: "16", optionD: "100", correctOption: "A", explanation: "Sum = average × count = 20 × 4 = 80.", orderIndex: 14 },
  { id: "ssc-cgl-quant-averages-q16", topicId: "ssc-cgl-quant-averages", text: "A batsman's average in 10 innings is 40. His total runs are:", optionA: "400", optionB: "50", optionC: "410", optionD: "4", correctOption: "A", explanation: "Total = 40 × 10 = 400 runs.", orderIndex: 15 },

  // ── Quant: Time & Work ──
  { id: "ssc-cgl-quant-time-and-work-q13", topicId: "ssc-cgl-quant-time-and-work", text: "If A does a job in 10 days, A's one-day work is:", optionA: "1/10", optionB: "10", optionC: "1/5", optionD: "1/20", correctOption: "A", explanation: "One day's work is the reciprocal of the days: 1/10.", orderIndex: 12 },
  { id: "ssc-cgl-quant-time-and-work-q14", topicId: "ssc-cgl-quant-time-and-work", text: "A and B finish work in 12 and 6 days. Together they take:", optionA: "4 days", optionB: "9 days", optionC: "18 days", optionD: "3 days", correctOption: "A", explanation: "Combined rate = 1/12 + 1/6 = 1/4, so 4 days.", orderIndex: 13 },
  { id: "ssc-cgl-quant-time-and-work-q15", topicId: "ssc-cgl-quant-time-and-work", text: "If 5 workers build a wall in 8 days, 10 workers (same rate) take:", optionA: "4 days", optionB: "16 days", optionC: "8 days", optionD: "2 days", correctOption: "A", explanation: "Doubling workers halves the time: 8/2 = 4 days.", orderIndex: 14 },
  { id: "ssc-cgl-quant-time-and-work-q16", topicId: "ssc-cgl-quant-time-and-work", text: "A pipe fills a tank in 6 hours. In 2 hours it fills what fraction?", optionA: "1/3", optionB: "1/2", optionC: "1/6", optionD: "2/3", correctOption: "A", explanation: "In 2 of the 6 hours it fills 2/6 = 1/3 of the tank.", orderIndex: 15 },

  // ── Quant: Mensuration ──
  { id: "ssc-cgl-quant-mensuration-q13", topicId: "ssc-cgl-quant-mensuration", text: "The area of a rectangle 8 cm by 5 cm is:", optionA: "40 cm²", optionB: "26 cm²", optionC: "13 cm²", optionD: "45 cm²", correctOption: "A", explanation: "Area = length × breadth = 8 × 5 = 40 cm².", orderIndex: 12 },
  { id: "ssc-cgl-quant-mensuration-q14", topicId: "ssc-cgl-quant-mensuration", text: "The area of a circle of radius 7 cm (π = 22/7) is:", optionA: "154 cm²", optionB: "44 cm²", optionC: "49 cm²", optionD: "22 cm²", correctOption: "A", explanation: "Area = πr² = 22/7 × 49 = 154 cm².", orderIndex: 13 },
  { id: "ssc-cgl-quant-mensuration-q15", topicId: "ssc-cgl-quant-mensuration", text: "The volume of a cube of side 3 cm is:", optionA: "27 cm³", optionB: "9 cm³", optionC: "54 cm³", optionD: "18 cm³", correctOption: "A", explanation: "Volume = side³ = 3³ = 27 cm³.", orderIndex: 14 },
  { id: "ssc-cgl-quant-mensuration-q16", topicId: "ssc-cgl-quant-mensuration", text: "The perimeter of a square of side 6 cm is:", optionA: "24 cm", optionB: "36 cm", optionC: "12 cm", optionD: "30 cm", correctOption: "A", explanation: "Perimeter = 4 × side = 4 × 6 = 24 cm.", orderIndex: 15 },

  // ── Reasoning: Analogy & Classification ──
  { id: "ssc-cgl-reasoning-analogy-classification-q13", topicId: "ssc-cgl-reasoning-analogy-classification", text: "Hand is to glove as foot is to:", optionA: "Sock", optionB: "Shoe rack", optionC: "Toe", optionD: "Leg", correctOption: "A", explanation: "A glove covers a hand as a sock covers a foot.", orderIndex: 12 },
  { id: "ssc-cgl-reasoning-analogy-classification-q14", topicId: "ssc-cgl-reasoning-analogy-classification", text: "Find the odd one out: Rose, Lily, Mango, Jasmine.", optionA: "Mango", optionB: "Rose", optionC: "Lily", optionD: "Jasmine", correctOption: "A", explanation: "Mango is a fruit; the others are flowers.", orderIndex: 13 },
  { id: "ssc-cgl-reasoning-analogy-classification-q15", topicId: "ssc-cgl-reasoning-analogy-classification", text: "Doctor is to hospital as teacher is to:", optionA: "School", optionB: "Book", optionC: "Student", optionD: "Chalk", correctOption: "A", explanation: "A doctor works in a hospital as a teacher works in a school.", orderIndex: 14 },
  { id: "ssc-cgl-reasoning-analogy-classification-q16", topicId: "ssc-cgl-reasoning-analogy-classification", text: "Find the odd one out: 2, 3, 5, 9, 11.", optionA: "9", optionB: "3", optionC: "5", optionD: "11", correctOption: "A", explanation: "2, 3, 5, 11 are prime; 9 is not.", orderIndex: 15 },

  // ── Reasoning: Direction Sense ──
  { id: "ssc-cgl-reasoning-direction-sense-q13", topicId: "ssc-cgl-reasoning-direction-sense", text: "Facing north and turning 90° clockwise, you face:", optionA: "East", optionB: "West", optionC: "South", optionD: "North", correctOption: "A", explanation: "A 90° clockwise turn from north points to the east.", orderIndex: 12 },
  { id: "ssc-cgl-reasoning-direction-sense-q14", topicId: "ssc-cgl-reasoning-direction-sense", text: "If you walk south then turn left, you are heading:", optionA: "East", optionB: "West", optionC: "North", optionD: "South", correctOption: "A", explanation: "Turning left while facing south points you east.", orderIndex: 13 },
  { id: "ssc-cgl-reasoning-direction-sense-q15", topicId: "ssc-cgl-reasoning-direction-sense", text: "At sunrise, your shadow falls toward the:", optionA: "West", optionB: "East", optionC: "North", optionD: "South", correctOption: "A", explanation: "The sun rises in the east, so shadows point west.", orderIndex: 14 },
  { id: "ssc-cgl-reasoning-direction-sense-q16", topicId: "ssc-cgl-reasoning-direction-sense", text: "Facing east and turning 180°, you now face:", optionA: "West", optionB: "North", optionC: "South", optionD: "East", correctOption: "A", explanation: "A 180° turn from east faces west.", orderIndex: 15 },

  // ── English: Synonyms & Antonyms ──
  { id: "ssc-cgl-english-synonyms-antonyms-q13", topicId: "ssc-cgl-english-synonyms-antonyms", text: "Choose the synonym of 'Happy':", optionA: "Joyful", optionB: "Sad", optionC: "Angry", optionD: "Tired", correctOption: "A", explanation: "'Joyful' is a synonym of 'happy'.", orderIndex: 12 },
  { id: "ssc-cgl-english-synonyms-antonyms-q14", topicId: "ssc-cgl-english-synonyms-antonyms", text: "Choose the antonym of 'Ancient':", optionA: "Modern", optionB: "Old", optionC: "Historic", optionD: "Aged", correctOption: "A", explanation: "'Modern' is the opposite of 'ancient'.", orderIndex: 13 },
  { id: "ssc-cgl-english-synonyms-antonyms-q15", topicId: "ssc-cgl-english-synonyms-antonyms", text: "Choose the synonym of 'Brave':", optionA: "Courageous", optionB: "Timid", optionC: "Weak", optionD: "Fearful", correctOption: "A", explanation: "'Courageous' is a synonym of 'brave'.", orderIndex: 14 },
  { id: "ssc-cgl-english-synonyms-antonyms-q16", topicId: "ssc-cgl-english-synonyms-antonyms", text: "Choose the antonym of 'Expand':", optionA: "Contract", optionB: "Enlarge", optionC: "Grow", optionD: "Increase", correctOption: "A", explanation: "'Contract' is the opposite of 'expand'.", orderIndex: 15 },

  // ── English: Idioms & One-Word Substitution ──
  { id: "ssc-cgl-english-idioms-one-word-q13", topicId: "ssc-cgl-english-idioms-one-word", text: "The idiom 'a piece of cake' means something that is:", optionA: "Very easy", optionB: "Very difficult", optionC: "Delicious", optionD: "Expensive", correctOption: "A", explanation: "'A piece of cake' means very easy to do.", orderIndex: 12 },
  { id: "ssc-cgl-english-idioms-one-word-q14", topicId: "ssc-cgl-english-idioms-one-word", text: "One word for 'a person who eats everything':", optionA: "Omnivore", optionB: "Herbivore", optionC: "Carnivore", optionD: "Vegetarian", correctOption: "A", explanation: "An omnivore eats both plants and animals — everything.", orderIndex: 13 },
  { id: "ssc-cgl-english-idioms-one-word-q15", topicId: "ssc-cgl-english-idioms-one-word", text: "The idiom 'to break the ice' means to:", optionA: "Start a conversation", optionB: "Freeze water", optionC: "End a friendship", optionD: "Cause trouble", correctOption: "A", explanation: "'Break the ice' means to ease initial social tension and start talking.", orderIndex: 14 },
  { id: "ssc-cgl-english-idioms-one-word-q16", topicId: "ssc-cgl-english-idioms-one-word", text: "One word for 'a government by the people':", optionA: "Democracy", optionB: "Monarchy", optionC: "Autocracy", optionD: "Oligarchy", correctOption: "A", explanation: "Democracy is rule by the people.", orderIndex: 15 }
];
