// SSC CGL depth top-up (pass 1). Every existing SSC CGL topic held only 8
// questions; this adds q09–q12 to each so all reach the 12-question standard
// used across the catalog. No new topics or materials.
import type { Question } from "@jyotir/core";

export const sscTopUp: Question[] = [
  // ── Quant: Percentages & Profit-Loss ──
  { id: "ssc-cgl-quant-percentages-profit-loss-q09", topicId: "ssc-cgl-quant-percentages-profit-loss", text: "If the price of an article is increased by 25%, by what percent must it be reduced to restore the original price?", optionA: "25%", optionB: "20%", optionC: "15%", optionD: "30%", correctOption: "B", explanation: "Reduction % = 25/(100+25) × 100 = 20%.", orderIndex: 8 },
  { id: "ssc-cgl-quant-percentages-profit-loss-q10", topicId: "ssc-cgl-quant-percentages-profit-loss", text: "An item costing ₹500 is sold at a 20% profit. Its selling price is:", optionA: "₹600", optionB: "₹520", optionC: "₹580", optionD: "₹620", correctOption: "A", explanation: "SP = 500 × 1.20 = ₹600.", orderIndex: 9 },
  { id: "ssc-cgl-quant-percentages-profit-loss-q11", topicId: "ssc-cgl-quant-percentages-profit-loss", text: "40% of 250 is:", optionA: "80", optionB: "100", optionC: "120", optionD: "90", correctOption: "B", explanation: "40% of 250 = 0.40 × 250 = 100.", orderIndex: 10 },
  { id: "ssc-cgl-quant-percentages-profit-loss-q12", topicId: "ssc-cgl-quant-percentages-profit-loss", text: "An article bought for ₹400 is sold for ₹360. The loss percent is:", optionA: "10%", optionB: "8%", optionC: "12%", optionD: "5%", correctOption: "A", explanation: "Loss = 40; loss% = 40/400 × 100 = 10%.", orderIndex: 11 },

  // ── Quant: Time, Speed & Distance ──
  { id: "ssc-cgl-quant-time-speed-distance-q09", topicId: "ssc-cgl-quant-time-speed-distance", text: "A car travels 240 km in 4 hours. Its average speed is:", optionA: "60 km/h", optionB: "50 km/h", optionC: "70 km/h", optionD: "48 km/h", correctOption: "A", explanation: "Speed = distance/time = 240/4 = 60 km/h.", orderIndex: 8 },
  { id: "ssc-cgl-quant-time-speed-distance-q10", topicId: "ssc-cgl-quant-time-speed-distance", text: "72 km/h expressed in m/s is:", optionA: "20 m/s", optionB: "18 m/s", optionC: "25 m/s", optionD: "15 m/s", correctOption: "A", explanation: "To convert km/h to m/s, multiply by 5/18: 72 × 5/18 = 20 m/s.", orderIndex: 9 },
  { id: "ssc-cgl-quant-time-speed-distance-q11", topicId: "ssc-cgl-quant-time-speed-distance", text: "A 150 m long train crosses a pole in 15 seconds. Its speed is:", optionA: "10 m/s", optionB: "15 m/s", optionC: "12 m/s", optionD: "9 m/s", correctOption: "A", explanation: "Speed = 150/15 = 10 m/s.", orderIndex: 10 },
  { id: "ssc-cgl-quant-time-speed-distance-q12", topicId: "ssc-cgl-quant-time-speed-distance", text: "Two trains move toward each other at 40 km/h and 50 km/h. Their relative speed is:", optionA: "90 km/h", optionB: "10 km/h", optionC: "45 km/h", optionD: "80 km/h", correctOption: "A", explanation: "For opposite directions relative speed = 40 + 50 = 90 km/h.", orderIndex: 11 },

  // ── Quant: Ratio & Proportion ──
  { id: "ssc-cgl-quant-ratio-proportion-q09", topicId: "ssc-cgl-quant-ratio-proportion", text: "If a:b = 2:3 and b:c = 4:5, then a:c equals:", optionA: "8:15", optionB: "2:5", optionC: "8:5", optionD: "6:5", correctOption: "A", explanation: "a:b = 8:12, b:c = 12:15, so a:c = 8:15.", orderIndex: 8 },
  { id: "ssc-cgl-quant-ratio-proportion-q10", topicId: "ssc-cgl-quant-ratio-proportion", text: "₹600 is divided in the ratio 2:3. The larger share is:", optionA: "₹360", optionB: "₹240", optionC: "₹300", optionD: "₹400", correctOption: "A", explanation: "Larger share = 600 × 3/5 = ₹360.", orderIndex: 9 },
  { id: "ssc-cgl-quant-ratio-proportion-q11", topicId: "ssc-cgl-quant-ratio-proportion", text: "The fourth proportional to 3, 6 and 4 is:", optionA: "8", optionB: "6", optionC: "12", optionD: "9", correctOption: "A", explanation: "3:6 = 4:x → x = 6 × 4 / 3 = 8.", orderIndex: 10 },
  { id: "ssc-cgl-quant-ratio-proportion-q12", topicId: "ssc-cgl-quant-ratio-proportion", text: "The mean proportional between 4 and 9 is:", optionA: "6", optionB: "5", optionC: "13", optionD: "36", correctOption: "A", explanation: "Mean proportional = √(4 × 9) = √36 = 6.", orderIndex: 11 },

  // ── Quant: Averages ──
  { id: "ssc-cgl-quant-averages-q09", topicId: "ssc-cgl-quant-averages", text: "The average of the first 5 natural numbers is:", optionA: "3", optionB: "2.5", optionC: "4", optionD: "5", correctOption: "A", explanation: "(1+2+3+4+5)/5 = 15/5 = 3.", orderIndex: 8 },
  { id: "ssc-cgl-quant-averages-q10", topicId: "ssc-cgl-quant-averages", text: "The average of 10, 20, 30, 40 and 50 is:", optionA: "30", optionB: "25", optionC: "35", optionD: "40", correctOption: "A", explanation: "Average = sum ÷ count = (10+20+30+40+50)/5 = 150/5 = 30.", orderIndex: 9 },
  { id: "ssc-cgl-quant-averages-q11", topicId: "ssc-cgl-quant-averages", text: "The average of 4 numbers is 25. Their sum is:", optionA: "100", optionB: "50", optionC: "125", optionD: "75", correctOption: "A", explanation: "Sum = average × count = 25 × 4 = 100.", orderIndex: 10 },
  { id: "ssc-cgl-quant-averages-q12", topicId: "ssc-cgl-quant-averages", text: "The average of the first 10 even numbers (2 to 20) is:", optionA: "11", optionB: "10", optionC: "12", optionD: "20", correctOption: "A", explanation: "Sum = 110; average = 110/10 = 11.", orderIndex: 11 },

  // ── Quant: Simple & Compound Interest ──
  { id: "ssc-cgl-quant-simple-compound-interest-q09", topicId: "ssc-cgl-quant-simple-compound-interest", text: "The simple interest on ₹1000 at 5% per annum for 2 years is:", optionA: "₹100", optionB: "₹50", optionC: "₹110", optionD: "₹200", correctOption: "A", explanation: "SI = PRT/100 = 1000 × 5 × 2 / 100 = ₹100.", orderIndex: 8 },
  { id: "ssc-cgl-quant-simple-compound-interest-q10", topicId: "ssc-cgl-quant-simple-compound-interest", text: "The compound interest on ₹1000 at 10% per annum for 2 years is:", optionA: "₹210", optionB: "₹200", optionC: "₹100", optionD: "₹220", correctOption: "A", explanation: "Amount = 1000 × 1.1² = 1210; CI = 1210 − 1000 = ₹210.", orderIndex: 9 },
  { id: "ssc-cgl-quant-simple-compound-interest-q11", topicId: "ssc-cgl-quant-simple-compound-interest", text: "In how many years will the simple interest on a sum equal the principal at 25% per annum?", optionA: "4 years", optionB: "5 years", optionC: "3 years", optionD: "8 years", correctOption: "A", explanation: "Time = 100 / rate = 100/25 = 4 years.", orderIndex: 10 },
  { id: "ssc-cgl-quant-simple-compound-interest-q12", topicId: "ssc-cgl-quant-simple-compound-interest", text: "A sum doubles itself in 8 years at simple interest. The rate per annum is:", optionA: "12.5%", optionB: "10%", optionC: "8%", optionD: "15%", correctOption: "A", explanation: "To double, SI = principal; rate = 100/8 = 12.5%.", orderIndex: 11 },

  // ── Quant: Time & Work ──
  { id: "ssc-cgl-quant-time-and-work-q09", topicId: "ssc-cgl-quant-time-and-work", text: "A can do a work in 10 days and B in 15 days. Working together they finish it in:", optionA: "6 days", optionB: "5 days", optionC: "8 days", optionD: "12 days", correctOption: "A", explanation: "1/10 + 1/15 = 1/6, so together 6 days.", orderIndex: 8 },
  { id: "ssc-cgl-quant-time-and-work-q10", topicId: "ssc-cgl-quant-time-and-work", text: "If 6 men complete a work in 8 days, how many men are needed to finish it in 4 days?", optionA: "12", optionB: "10", optionC: "8", optionD: "16", correctOption: "A", explanation: "Men × days is constant: 6 × 8 / 4 = 12 men.", orderIndex: 9 },
  { id: "ssc-cgl-quant-time-and-work-q11", topicId: "ssc-cgl-quant-time-and-work", text: "A does 1/4 of a work in 5 days. The whole work takes him:", optionA: "20 days", optionB: "15 days", optionC: "25 days", optionD: "10 days", correctOption: "A", explanation: "If 1/4 takes 5 days, the full work takes 4 × 5 = 20 days.", orderIndex: 10 },
  { id: "ssc-cgl-quant-time-and-work-q12", topicId: "ssc-cgl-quant-time-and-work", text: "A is twice as efficient as B. If A finishes a job in 6 days, B alone takes:", optionA: "12 days", optionB: "3 days", optionC: "9 days", optionD: "6 days", correctOption: "A", explanation: "Twice as efficient means B takes double the time: 2 × 6 = 12 days.", orderIndex: 11 },

  // ── Quant: Number System (LCM/HCF) ──
  { id: "ssc-cgl-quant-number-system-q09", topicId: "ssc-cgl-quant-number-system", text: "The LCM of 12 and 18 is:", optionA: "36", optionB: "6", optionC: "72", optionD: "216", correctOption: "A", explanation: "The lowest common multiple of 12 and 18 is 36 (12 = 2²·3, 18 = 2·3²).", orderIndex: 8 },
  { id: "ssc-cgl-quant-number-system-q10", topicId: "ssc-cgl-quant-number-system", text: "The HCF of 24 and 36 is:", optionA: "12", optionB: "6", optionC: "24", optionD: "72", correctOption: "A", explanation: "The highest common factor of 24 and 36 is 12, their largest common divisor.", orderIndex: 9 },
  { id: "ssc-cgl-quant-number-system-q11", topicId: "ssc-cgl-quant-number-system", text: "Two numbers are 12 and 18. If their LCM is 36, their HCF is:", optionA: "6", optionB: "12", optionC: "3", optionD: "9", correctOption: "A", explanation: "Product = LCM × HCF, so HCF = (12 × 18)/36 = 6.", orderIndex: 10 },
  { id: "ssc-cgl-quant-number-system-q12", topicId: "ssc-cgl-quant-number-system", text: "The smallest number exactly divisible by both 4 and 6 is:", optionA: "12", optionB: "24", optionC: "10", optionD: "8", correctOption: "A", explanation: "The smallest such number is their LCM = 12.", orderIndex: 11 },

  // ── Quant: Mensuration ──
  { id: "ssc-cgl-quant-mensuration-q09", topicId: "ssc-cgl-quant-mensuration", text: "The area of a circle of radius 7 cm (π = 22/7) is:", optionA: "154 cm²", optionB: "44 cm²", optionC: "49 cm²", optionD: "22 cm²", correctOption: "A", explanation: "Area = πr² = 22/7 × 49 = 154 cm².", orderIndex: 8 },
  { id: "ssc-cgl-quant-mensuration-q10", topicId: "ssc-cgl-quant-mensuration", text: "The volume of a cube of side 5 cm is:", optionA: "125 cm³", optionB: "25 cm³", optionC: "75 cm³", optionD: "150 cm³", correctOption: "A", explanation: "Volume = side³ = 5³ = 125 cm³.", orderIndex: 9 },
  { id: "ssc-cgl-quant-mensuration-q11", topicId: "ssc-cgl-quant-mensuration", text: "The area of a rectangle 8 cm by 5 cm is:", optionA: "40 cm²", optionB: "13 cm²", optionC: "26 cm²", optionD: "45 cm²", correctOption: "A", explanation: "Area = length × breadth = 8 × 5 = 40 cm².", orderIndex: 10 },
  { id: "ssc-cgl-quant-mensuration-q12", topicId: "ssc-cgl-quant-mensuration", text: "The perimeter of a square of side 9 cm is:", optionA: "36 cm", optionB: "81 cm", optionC: "18 cm", optionD: "45 cm", correctOption: "A", explanation: "Perimeter = 4 × side = 4 × 9 = 36 cm.", orderIndex: 11 },

  // ── Quant: Algebra Basics ──
  { id: "ssc-cgl-quant-algebra-basics-q09", topicId: "ssc-cgl-quant-algebra-basics", text: "If x + 1/x = 2, then x² + 1/x² equals:", optionA: "2", optionB: "4", optionC: "0", optionD: "1", correctOption: "A", explanation: "(x + 1/x)² − 2 = 2² − 2 = 2.", orderIndex: 8 },
  { id: "ssc-cgl-quant-algebra-basics-q10", topicId: "ssc-cgl-quant-algebra-basics", text: "If a + b = 5 and ab = 6, then a² + b² equals:", optionA: "13", optionB: "11", optionC: "25", optionD: "19", correctOption: "A", explanation: "a² + b² = (a+b)² − 2ab = 25 − 12 = 13.", orderIndex: 9 },
  { id: "ssc-cgl-quant-algebra-basics-q11", topicId: "ssc-cgl-quant-algebra-basics", text: "The roots of x² − 5x + 6 = 0 are:", optionA: "2 and 3", optionB: "1 and 6", optionC: "−2 and −3", optionD: "5 and 6", correctOption: "A", explanation: "x² − 5x + 6 = (x−2)(x−3) = 0, so x = 2 or 3.", orderIndex: 10 },
  { id: "ssc-cgl-quant-algebra-basics-q12", topicId: "ssc-cgl-quant-algebra-basics", text: "If 3x − 7 = 8, then x equals:", optionA: "5", optionB: "3", optionC: "15", optionD: "1", correctOption: "A", explanation: "Add 7 to both sides to get 3x = 15, then divide by 3: x = 5.", orderIndex: 11 },

  // ── Quant: Trigonometry ──
  { id: "ssc-cgl-quant-trigonometry-q09", topicId: "ssc-cgl-quant-trigonometry", text: "The value of sin 30° is:", optionA: "1/2", optionB: "√3/2", optionC: "1", optionD: "0", correctOption: "A", explanation: "The standard trigonometric value of sin 30° is 1/2.", orderIndex: 8 },
  { id: "ssc-cgl-quant-trigonometry-q10", topicId: "ssc-cgl-quant-trigonometry", text: "The value of cos 60° is:", optionA: "1/2", optionB: "√3/2", optionC: "1", optionD: "0", correctOption: "A", explanation: "The standard trigonometric value of cos 60° is 1/2 (equal to sin 30°).", orderIndex: 9 },
  { id: "ssc-cgl-quant-trigonometry-q11", topicId: "ssc-cgl-quant-trigonometry", text: "The value of tan 45° is:", optionA: "1", optionB: "0", optionC: "√3", optionD: "1/√3", correctOption: "A", explanation: "The standard trigonometric value of tan 45° is 1, since sin 45° = cos 45°.", orderIndex: 10 },
  { id: "ssc-cgl-quant-trigonometry-q12", topicId: "ssc-cgl-quant-trigonometry", text: "The value of sin²θ + cos²θ is:", optionA: "1", optionB: "0", optionC: "2", optionD: "θ", correctOption: "A", explanation: "The identity sin²θ + cos²θ = 1 holds for all θ.", orderIndex: 11 },

  // ── Quant: Geometry ──
  { id: "ssc-cgl-quant-geometry-q09", topicId: "ssc-cgl-quant-geometry", text: "The sum of the interior angles of a triangle is:", optionA: "180°", optionB: "360°", optionC: "90°", optionD: "270°", correctOption: "A", explanation: "The interior angles of a triangle add up to 180°.", orderIndex: 8 },
  { id: "ssc-cgl-quant-geometry-q10", topicId: "ssc-cgl-quant-geometry", text: "The sum of the interior angles of a quadrilateral is:", optionA: "360°", optionB: "180°", optionC: "270°", optionD: "540°", correctOption: "A", explanation: "A quadrilateral's interior angles sum to 360°.", orderIndex: 9 },
  { id: "ssc-cgl-quant-geometry-q11", topicId: "ssc-cgl-quant-geometry", text: "Each interior angle of an equilateral triangle measures:", optionA: "60°", optionB: "90°", optionC: "45°", optionD: "120°", correctOption: "A", explanation: "Each angle = 180°/3 = 60°.", orderIndex: 10 },
  { id: "ssc-cgl-quant-geometry-q12", topicId: "ssc-cgl-quant-geometry", text: "The angle inscribed in a semicircle is always:", optionA: "90°", optionB: "60°", optionC: "45°", optionD: "180°", correctOption: "A", explanation: "An angle in a semicircle (subtended by the diameter) is a right angle, 90°.", orderIndex: 11 },

  // ── Quant: Data Interpretation ──
  { id: "ssc-cgl-quant-data-interpretation-q09", topicId: "ssc-cgl-quant-data-interpretation", text: "In a pie chart, a sector representing 25% of the total corresponds to:", optionA: "90°", optionB: "72°", optionC: "60°", optionD: "120°", correctOption: "A", explanation: "A full pie chart is 360°, so 25% corresponds to 0.25 × 360° = 90°.", orderIndex: 8 },
  { id: "ssc-cgl-quant-data-interpretation-q10", topicId: "ssc-cgl-quant-data-interpretation", text: "In a pie chart, 20% of the total is shown by an angle of:", optionA: "72°", optionB: "90°", optionC: "60°", optionD: "45°", correctOption: "A", explanation: "A full pie chart is 360°, so 20% corresponds to 0.20 × 360° = 72°.", orderIndex: 9 },
  { id: "ssc-cgl-quant-data-interpretation-q11", topicId: "ssc-cgl-quant-data-interpretation", text: "A bar graph shows sales rising from 40 to 60 units. The percentage increase is:", optionA: "50%", optionB: "20%", optionC: "33%", optionD: "40%", correctOption: "A", explanation: "Increase = 20 on 40 = 20/40 × 100 = 50%.", orderIndex: 10 },
  { id: "ssc-cgl-quant-data-interpretation-q12", topicId: "ssc-cgl-quant-data-interpretation", text: "The average of the values 30, 40 and 50 shown in a graph is:", optionA: "40", optionB: "30", optionC: "45", optionD: "50", correctOption: "A", explanation: "(30 + 40 + 50)/3 = 120/3 = 40.", orderIndex: 11 },

  // ── Reasoning: Coding-Decoding & Series ──
  { id: "ssc-cgl-reasoning-coding-decoding-series-q09", topicId: "ssc-cgl-reasoning-coding-decoding-series", text: "If CAT is coded as DBU (each letter shifted +1), then DOG is coded as:", optionA: "EPH", optionB: "CPF", optionC: "EPG", optionD: "DPH", correctOption: "A", explanation: "Each letter moves one step forward: D→E, O→P, G→H = EPH.", orderIndex: 8 },
  { id: "ssc-cgl-reasoning-coding-decoding-series-q10", topicId: "ssc-cgl-reasoning-coding-decoding-series", text: "Find the next term: 2, 4, 8, 16, ?", optionA: "32", optionB: "24", optionC: "20", optionD: "18", correctOption: "A", explanation: "Each term doubles: 16 × 2 = 32.", orderIndex: 9 },
  { id: "ssc-cgl-reasoning-coding-decoding-series-q11", topicId: "ssc-cgl-reasoning-coding-decoding-series", text: "Find the next term: 1, 4, 9, 16, ?", optionA: "25", optionB: "20", optionC: "24", optionD: "36", correctOption: "A", explanation: "These are perfect squares: 5² = 25.", orderIndex: 10 },
  { id: "ssc-cgl-reasoning-coding-decoding-series-q12", topicId: "ssc-cgl-reasoning-coding-decoding-series", text: "If A = 1, B = 2, C = 3 …, then the sum of the letters in 'CAB' is:", optionA: "6", optionB: "5", optionC: "7", optionD: "9", correctOption: "A", explanation: "C + A + B = 3 + 1 + 2 = 6.", orderIndex: 11 },

  // ── Reasoning: Analogy & Classification ──
  { id: "ssc-cgl-reasoning-analogy-classification-q09", topicId: "ssc-cgl-reasoning-analogy-classification", text: "Bird : Fly :: Fish : ?", optionA: "Swim", optionB: "Walk", optionC: "Run", optionD: "Jump", correctOption: "A", explanation: "A bird flies as a fish swims.", orderIndex: 8 },
  { id: "ssc-cgl-reasoning-analogy-classification-q10", topicId: "ssc-cgl-reasoning-analogy-classification", text: "Find the odd one out: Rose, Lotus, Lily, Mango.", optionA: "Mango", optionB: "Rose", optionC: "Lotus", optionD: "Lily", correctOption: "A", explanation: "Mango is a fruit; the others are flowers.", orderIndex: 9 },
  { id: "ssc-cgl-reasoning-analogy-classification-q11", topicId: "ssc-cgl-reasoning-analogy-classification", text: "Doctor : Hospital :: Teacher : ?", optionA: "School", optionB: "Book", optionC: "Student", optionD: "Class", correctOption: "A", explanation: "A doctor works in a hospital as a teacher works in a school.", orderIndex: 10 },
  { id: "ssc-cgl-reasoning-analogy-classification-q12", topicId: "ssc-cgl-reasoning-analogy-classification", text: "Find the odd one out: 2, 3, 5, 9.", optionA: "9", optionB: "2", optionC: "3", optionD: "5", correctOption: "A", explanation: "2, 3 and 5 are prime; 9 is not.", orderIndex: 11 },

  // ── Reasoning: Blood Relations ──
  { id: "ssc-cgl-reasoning-blood-relations-q09", topicId: "ssc-cgl-reasoning-blood-relations", text: "A is the father of B. Then A is B's:", optionA: "Father", optionB: "Son", optionC: "Uncle", optionD: "Brother", correctOption: "A", explanation: "If A is the father of B, A is B's father.", orderIndex: 8 },
  { id: "ssc-cgl-reasoning-blood-relations-q10", topicId: "ssc-cgl-reasoning-blood-relations", text: "Your mother's brother is your:", optionA: "Maternal uncle", optionB: "Paternal uncle", optionC: "Cousin", optionD: "Nephew", correctOption: "A", explanation: "The mother's brother is the maternal uncle (mama).", orderIndex: 9 },
  { id: "ssc-cgl-reasoning-blood-relations-q11", topicId: "ssc-cgl-reasoning-blood-relations", text: "The daughter of your father is your:", optionA: "Sister", optionB: "Aunt", optionC: "Niece", optionD: "Cousin", correctOption: "A", explanation: "Your father's daughter is your sister.", orderIndex: 10 },
  { id: "ssc-cgl-reasoning-blood-relations-q12", topicId: "ssc-cgl-reasoning-blood-relations", text: "Your father's father is your:", optionA: "Grandfather", optionB: "Uncle", optionC: "Brother", optionD: "Nephew", correctOption: "A", explanation: "The father's father is the (paternal) grandfather.", orderIndex: 11 },

  // ── Reasoning: Direction Sense ──
  { id: "ssc-cgl-reasoning-direction-sense-q09", topicId: "ssc-cgl-reasoning-direction-sense", text: "A man walks 3 km north, then 4 km east. His straight-line distance from the start is:", optionA: "5 km", optionB: "7 km", optionC: "1 km", optionD: "12 km", correctOption: "A", explanation: "By Pythagoras, √(3² + 4²) = √25 = 5 km.", orderIndex: 8 },
  { id: "ssc-cgl-reasoning-direction-sense-q10", topicId: "ssc-cgl-reasoning-direction-sense", text: "Facing north, you turn 90° clockwise. You now face:", optionA: "East", optionB: "West", optionC: "South", optionD: "North", correctOption: "A", explanation: "A 90° clockwise turn from north points east.", orderIndex: 9 },
  { id: "ssc-cgl-reasoning-direction-sense-q11", topicId: "ssc-cgl-reasoning-direction-sense", text: "The sun rises in the:", optionA: "East", optionB: "West", optionC: "North", optionD: "South", correctOption: "A", explanation: "The sun rises in the east and sets in the west.", orderIndex: 10 },
  { id: "ssc-cgl-reasoning-direction-sense-q12", topicId: "ssc-cgl-reasoning-direction-sense", text: "Facing south, you turn 180°. You now face:", optionA: "North", optionB: "East", optionC: "West", optionD: "South", correctOption: "A", explanation: "A 180° turn from south points north.", orderIndex: 11 },

  // ── Reasoning: Syllogism ──
  { id: "ssc-cgl-reasoning-syllogism-q09", topicId: "ssc-cgl-reasoning-syllogism", text: "All cats are animals. All animals are living things. It follows that:", optionA: "All cats are living things", optionB: "All animals are cats", optionC: "No cat is living", optionD: "Some cats are not animals", correctOption: "A", explanation: "Chaining the two universals gives: all cats are living things.", orderIndex: 8 },
  { id: "ssc-cgl-reasoning-syllogism-q10", topicId: "ssc-cgl-reasoning-syllogism", text: "'Some pens are red.' A valid conversion is:", optionA: "Some red things are pens", optionB: "All pens are red", optionC: "No pen is red", optionD: "All red things are pens", correctOption: "A", explanation: "'Some A are B' converts to 'Some B are A'.", orderIndex: 9 },
  { id: "ssc-cgl-reasoning-syllogism-q11", topicId: "ssc-cgl-reasoning-syllogism", text: "'No dog is a cat.' A valid conclusion is:", optionA: "No cat is a dog", optionB: "Some cats are dogs", optionC: "All cats are dogs", optionD: "Some dogs are cats", correctOption: "A", explanation: "A universal negative converts: 'No dog is a cat' ⇒ 'No cat is a dog'.", orderIndex: 10 },
  { id: "ssc-cgl-reasoning-syllogism-q12", topicId: "ssc-cgl-reasoning-syllogism", text: "All roses are flowers. Some flowers are red. Which follows?", optionA: "No definite conclusion about roses being red", optionB: "All roses are red", optionC: "No rose is red", optionD: "All flowers are roses", correctOption: "A", explanation: "The 'some flowers are red' need not include roses, so no conclusion about red roses follows.", orderIndex: 11 },

  // ── Reasoning: Seating Arrangement & Puzzles ──
  { id: "ssc-cgl-reasoning-seating-puzzles-q09", topicId: "ssc-cgl-reasoning-seating-puzzles", text: "In a row of 5 people, the person exactly in the middle is at position:", optionA: "3rd", optionB: "2nd", optionC: "4th", optionD: "1st", correctOption: "A", explanation: "In a row of 5, the middle is the 3rd position.", orderIndex: 8 },
  { id: "ssc-cgl-reasoning-seating-puzzles-q10", topicId: "ssc-cgl-reasoning-seating-puzzles", text: "If A is to the immediate right of B, then B is to the ___ of A.", optionA: "Left", optionB: "Right", optionC: "Front", optionD: "Back", correctOption: "A", explanation: "If A is on B's right, B must be on A's left.", orderIndex: 9 },
  { id: "ssc-cgl-reasoning-seating-puzzles-q11", topicId: "ssc-cgl-reasoning-seating-puzzles", text: "Eight people sit evenly around a circle facing the centre. The person opposite position 1 is at position:", optionA: "5", optionB: "4", optionC: "8", optionD: "6", correctOption: "A", explanation: "In a circle of 8, the opposite seat is 4 places away: 1 + 4 = 5.", orderIndex: 10 },
  { id: "ssc-cgl-reasoning-seating-puzzles-q12", topicId: "ssc-cgl-reasoning-seating-puzzles", text: "In a row of 6 people, P is 2nd from the left. P's position from the right is:", optionA: "5th", optionB: "4th", optionC: "6th", optionD: "3rd", correctOption: "A", explanation: "Position from right = total − position from left + 1 = 6 − 2 + 1 = 5.", orderIndex: 11 },

  // ── Reasoning: Clock & Calendar ──
  { id: "ssc-cgl-reasoning-clock-calendar-q09", topicId: "ssc-cgl-reasoning-clock-calendar", text: "The angle between the hands of a clock at 3:00 is:", optionA: "90°", optionB: "180°", optionC: "45°", optionD: "60°", correctOption: "A", explanation: "At 3:00 the hands are 3 hours apart: 3 × 30° = 90°.", orderIndex: 8 },
  { id: "ssc-cgl-reasoning-clock-calendar-q10", topicId: "ssc-cgl-reasoning-clock-calendar", text: "In one minute the minute hand of a clock moves through:", optionA: "6°", optionB: "1°", optionC: "12°", optionD: "30°", correctOption: "A", explanation: "The minute hand covers 360° in 60 minutes = 6° per minute.", orderIndex: 9 },
  { id: "ssc-cgl-reasoning-clock-calendar-q11", topicId: "ssc-cgl-reasoning-clock-calendar", text: "The number of odd days in an ordinary (non-leap) year is:", optionA: "1", optionB: "2", optionC: "0", optionD: "3", correctOption: "A", explanation: "365 days = 52 weeks + 1 day, so 1 odd day.", orderIndex: 10 },
  { id: "ssc-cgl-reasoning-clock-calendar-q12", topicId: "ssc-cgl-reasoning-clock-calendar", text: "If today is Monday, the day after exactly 7 days will be:", optionA: "Monday", optionB: "Sunday", optionC: "Tuesday", optionD: "Wednesday", correctOption: "A", explanation: "7 days is exactly one week, so the same day returns: Monday.", orderIndex: 11 },

  // ── Reasoning: Non-Verbal: Mirror & Paper Folding ──
  { id: "ssc-cgl-reasoning-mirror-paper-folding-q09", topicId: "ssc-cgl-reasoning-mirror-paper-folding", text: "In a mirror image, the left side of an object appears on the:", optionA: "Right", optionB: "Left", optionC: "Top", optionD: "Bottom", correctOption: "A", explanation: "A plane mirror laterally inverts, so left appears on the right.", orderIndex: 8 },
  { id: "ssc-cgl-reasoning-mirror-paper-folding-q10", topicId: "ssc-cgl-reasoning-mirror-paper-folding", text: "The left-right reversal seen in a mirror is called:", optionA: "Lateral inversion", optionB: "Vertical inversion", optionC: "Rotation", optionD: "Magnification", correctOption: "A", explanation: "Mirror images show lateral (left-right) inversion.", orderIndex: 9 },
  { id: "ssc-cgl-reasoning-mirror-paper-folding-q11", topicId: "ssc-cgl-reasoning-mirror-paper-folding", text: "The mirror image of the lowercase letter 'b' most resembles:", optionA: "d", optionB: "p", optionC: "q", optionD: "b", correctOption: "A", explanation: "Reflecting 'b' left-to-right gives a shape like 'd'.", orderIndex: 10 },
  { id: "ssc-cgl-reasoning-mirror-paper-folding-q12", topicId: "ssc-cgl-reasoning-mirror-paper-folding", text: "In a water (surface) reflection, an image is inverted:", optionA: "Top to bottom", optionB: "Left to right", optionC: "Not at all", optionD: "Diagonally", correctOption: "A", explanation: "A water reflection flips the image vertically (top-to-bottom).", orderIndex: 11 },

  // ── Reasoning: Statement & Conclusion ──
  { id: "ssc-cgl-reasoning-statement-conclusion-q09", topicId: "ssc-cgl-reasoning-statement-conclusion", text: "Statement: All students passed the exam. Conclusion:", optionA: "No student failed", optionB: "Some students failed", optionC: "The exam was easy", optionD: "Only some passed", correctOption: "A", explanation: "If all passed, then it follows that no student failed.", orderIndex: 8 },
  { id: "ssc-cgl-reasoning-statement-conclusion-q10", topicId: "ssc-cgl-reasoning-statement-conclusion", text: "Statement: It is raining heavily. Which conclusion is best supported?", optionA: "The ground is likely to get wet", optionB: "It will never stop raining", optionC: "There is a drought", optionD: "The sun is shining", correctOption: "A", explanation: "Heavy rain reasonably implies the ground is likely to get wet.", orderIndex: 9 },
  { id: "ssc-cgl-reasoning-statement-conclusion-q11", topicId: "ssc-cgl-reasoning-statement-conclusion", text: "Statement: 'Smoking is injurious to health.' The underlying assumption is:", optionA: "People should avoid smoking", optionB: "Everyone smokes", optionC: "Smoking is healthy", optionD: "Health cannot be harmed", correctOption: "A", explanation: "The statement implies the advisory that people should avoid smoking.", orderIndex: 10 },
  { id: "ssc-cgl-reasoning-statement-conclusion-q12", topicId: "ssc-cgl-reasoning-statement-conclusion", text: "Statement: The library is open from 9 a.m. to 5 p.m. Conclusion:", optionA: "It is closed at 6 p.m.", optionB: "It is open all night", optionC: "It never closes", optionD: "It opens at 8 a.m.", correctOption: "A", explanation: "Closing at 5 p.m. means it is closed at 6 p.m.", orderIndex: 11 },

  // ── English: Idioms & One-Word Substitution ──
  { id: "ssc-cgl-english-idioms-one-word-q09", topicId: "ssc-cgl-english-idioms-one-word", text: "The idiom 'a piece of cake' means:", optionA: "Very easy", optionB: "Very tasty", optionC: "Expensive", optionD: "Difficult", correctOption: "A", explanation: "'A piece of cake' means something very easy to do.", orderIndex: 8 },
  { id: "ssc-cgl-english-idioms-one-word-q10", topicId: "ssc-cgl-english-idioms-one-word", text: "One word for 'an animal that eats both plants and meat' is:", optionA: "Omnivore", optionB: "Herbivore", optionC: "Carnivore", optionD: "Insectivore", correctOption: "A", explanation: "An omnivore eats both plants and animals.", orderIndex: 9 },
  { id: "ssc-cgl-english-idioms-one-word-q11", topicId: "ssc-cgl-english-idioms-one-word", text: "The idiom 'to let the cat out of the bag' means:", optionA: "To reveal a secret", optionB: "To buy a pet", optionC: "To run away", optionD: "To make noise", correctOption: "A", explanation: "'Let the cat out of the bag' means to disclose a secret.", orderIndex: 10 },
  { id: "ssc-cgl-english-idioms-one-word-q12", topicId: "ssc-cgl-english-idioms-one-word", text: "One word for 'a place where books are kept for reading' is:", optionA: "Library", optionB: "Laboratory", optionC: "Gallery", optionD: "Studio", correctOption: "A", explanation: "A library is a place where books are kept.", orderIndex: 11 },

  // ── English: Synonyms & Antonyms ──
  { id: "ssc-cgl-english-synonyms-antonyms-q09", topicId: "ssc-cgl-english-synonyms-antonyms", text: "Choose the synonym of 'HAPPY':", optionA: "Joyful", optionB: "Sad", optionC: "Angry", optionD: "Tired", correctOption: "A", explanation: "'Joyful' is a synonym of 'happy'.", orderIndex: 8 },
  { id: "ssc-cgl-english-synonyms-antonyms-q10", topicId: "ssc-cgl-english-synonyms-antonyms", text: "Choose the antonym of 'ANCIENT':", optionA: "Modern", optionB: "Old", optionC: "Historic", optionD: "Aged", correctOption: "A", explanation: "'Modern' is the opposite of 'ancient'.", orderIndex: 9 },
  { id: "ssc-cgl-english-synonyms-antonyms-q11", topicId: "ssc-cgl-english-synonyms-antonyms", text: "Choose the synonym of 'BRAVE':", optionA: "Courageous", optionB: "Fearful", optionC: "Weak", optionD: "Timid", correctOption: "A", explanation: "'Courageous' is a synonym of 'brave'.", orderIndex: 10 },
  { id: "ssc-cgl-english-synonyms-antonyms-q12", topicId: "ssc-cgl-english-synonyms-antonyms", text: "Choose the antonym of 'EXPAND':", optionA: "Contract", optionB: "Enlarge", optionC: "Grow", optionD: "Widen", correctOption: "A", explanation: "'Contract' is the opposite of 'expand'.", orderIndex: 11 },

  // ── English: Spotting Errors ──
  { id: "ssc-cgl-english-spotting-errors-q09", topicId: "ssc-cgl-english-spotting-errors", text: "Find the error: 'He don't like tea.'", optionA: "don't (should be doesn't)", optionB: "He", optionC: "like", optionD: "tea", correctOption: "A", explanation: "With a singular third-person subject, use 'doesn't', not 'don't'.", orderIndex: 8 },
  { id: "ssc-cgl-english-spotting-errors-q10", topicId: "ssc-cgl-english-spotting-errors", text: "Find the error: 'She is more taller than me.'", optionA: "more taller (double comparative)", optionB: "She", optionC: "than", optionD: "me", correctOption: "A", explanation: "'Taller' is already comparative; 'more taller' is incorrect.", orderIndex: 9 },
  { id: "ssc-cgl-english-spotting-errors-q11", topicId: "ssc-cgl-english-spotting-errors", text: "Find the error: 'One of the boys are absent.'", optionA: "are (should be is)", optionB: "One", optionC: "boys", optionD: "absent", correctOption: "A", explanation: "'One of the boys' is singular, so use 'is', not 'are'.", orderIndex: 10 },
  { id: "ssc-cgl-english-spotting-errors-q12", topicId: "ssc-cgl-english-spotting-errors", text: "Find the error: 'I have visited him yesterday.'", optionA: "have visited (should be visited)", optionB: "I", optionC: "him", optionD: "yesterday", correctOption: "A", explanation: "'Yesterday' needs the simple past 'visited', not the present perfect.", orderIndex: 11 },

  // ── English: Sentence Improvement & Spelling ──
  { id: "ssc-cgl-english-sentence-improvement-spelling-q09", topicId: "ssc-cgl-english-sentence-improvement-spelling", text: "Choose the correctly spelt word:", optionA: "Receive", optionB: "Recieve", optionC: "Receeve", optionD: "Receve", correctOption: "A", explanation: "The rule 'i before e except after c' gives 'receive'.", orderIndex: 8 },
  { id: "ssc-cgl-english-sentence-improvement-spelling-q10", topicId: "ssc-cgl-english-sentence-improvement-spelling", text: "Choose the correctly spelt word:", optionA: "Accommodate", optionB: "Acommodate", optionC: "Accomodate", optionD: "Acomodate", correctOption: "A", explanation: "'Accommodate' has double c and double m.", orderIndex: 9 },
  { id: "ssc-cgl-english-sentence-improvement-spelling-q11", topicId: "ssc-cgl-english-sentence-improvement-spelling", text: "Choose the correctly spelt word:", optionA: "Definitely", optionB: "Definately", optionC: "Definatly", optionD: "Definitly", correctOption: "A", explanation: "The correct spelling is 'definitely'.", orderIndex: 10 },
  { id: "ssc-cgl-english-sentence-improvement-spelling-q12", topicId: "ssc-cgl-english-sentence-improvement-spelling", text: "Choose the correctly spelt word:", optionA: "Occurrence", optionB: "Occurence", optionC: "Ocurrence", optionD: "Occurance", correctOption: "A", explanation: "'Occurrence' has double c, double r and ends in -ence.", orderIndex: 11 },

  // ── English: Reading Comprehension ──
  { id: "ssc-cgl-english-reading-comprehension-q09", topicId: "ssc-cgl-english-reading-comprehension", text: "Passage: 'Regular exercise improves health and reduces stress.' According to the passage, exercise reduces:", optionA: "Stress", optionB: "Health", optionC: "Sleep", optionD: "Appetite", correctOption: "A", explanation: "The passage states exercise reduces stress.", orderIndex: 8 },
  { id: "ssc-cgl-english-reading-comprehension-q10", topicId: "ssc-cgl-english-reading-comprehension", text: "In the sentence 'The novel was so gripping she read it in one sitting', 'gripping' most nearly means:", optionA: "Engrossing", optionB: "Boring", optionC: "Short", optionD: "Difficult", correctOption: "A", explanation: "'Gripping' means holding the attention — engrossing.", orderIndex: 9 },
  { id: "ssc-cgl-english-reading-comprehension-q11", topicId: "ssc-cgl-english-reading-comprehension", text: "The main idea of a paragraph is usually stated in its:", optionA: "Topic sentence", optionB: "Last word", optionC: "Title only", optionD: "Footnote", correctOption: "A", explanation: "The topic sentence carries the paragraph's main idea.", orderIndex: 10 },
  { id: "ssc-cgl-english-reading-comprehension-q12", topicId: "ssc-cgl-english-reading-comprehension", text: "To 'infer' from a passage means to:", optionA: "Draw a conclusion from evidence", optionB: "Copy the text", optionC: "Ignore the details", optionD: "Count the words", correctOption: "A", explanation: "Inference is reaching a conclusion based on evidence in the text.", orderIndex: 11 },

  // ── English: Active & Passive Voice ──
  { id: "ssc-cgl-english-active-passive-voice-q09", topicId: "ssc-cgl-english-active-passive-voice", text: "Change to passive voice: 'She writes a letter.'", optionA: "A letter is written by her", optionB: "A letter was written by her", optionC: "A letter writes her", optionD: "She is written a letter", correctOption: "A", explanation: "Simple present passive: 'A letter is written by her.'", orderIndex: 8 },
  { id: "ssc-cgl-english-active-passive-voice-q10", topicId: "ssc-cgl-english-active-passive-voice", text: "Change to passive voice: 'They are playing football.'", optionA: "Football is being played by them", optionB: "Football is played by them", optionC: "Football was played by them", optionD: "Football has been played", correctOption: "A", explanation: "Present continuous passive: 'Football is being played by them.'", orderIndex: 9 },
  { id: "ssc-cgl-english-active-passive-voice-q11", topicId: "ssc-cgl-english-active-passive-voice", text: "In the active voice, the subject is the ___ of the action.", optionA: "Doer", optionB: "Receiver", optionC: "Object", optionD: "Adverb", correctOption: "A", explanation: "In the active voice the subject performs (does) the action.", orderIndex: 10 },
  { id: "ssc-cgl-english-active-passive-voice-q12", topicId: "ssc-cgl-english-active-passive-voice", text: "Change to passive voice: 'He ate an apple.'", optionA: "An apple was eaten by him", optionB: "An apple is eaten by him", optionC: "An apple has eaten him", optionD: "He was eaten an apple", correctOption: "A", explanation: "Simple past passive: 'An apple was eaten by him.'", orderIndex: 11 },

  // ── English: Cloze Test ──
  { id: "ssc-cgl-english-cloze-test-q09", topicId: "ssc-cgl-english-cloze-test", text: "Fill in the blank: 'He is good ___ mathematics.'", optionA: "at", optionB: "in", optionC: "on", optionD: "for", correctOption: "A", explanation: "The correct collocation is 'good at' a subject.", orderIndex: 8 },
  { id: "ssc-cgl-english-cloze-test-q10", topicId: "ssc-cgl-english-cloze-test", text: "Fill in the blank: 'She has been living here ___ 2010.'", optionA: "since", optionB: "for", optionC: "from", optionD: "by", correctOption: "A", explanation: "Use 'since' with a point in time (2010).", orderIndex: 9 },
  { id: "ssc-cgl-english-cloze-test-q11", topicId: "ssc-cgl-english-cloze-test", text: "Fill in the blank: 'The book is ___ the table.'", optionA: "on", optionB: "in", optionC: "at", optionD: "of", correctOption: "A", explanation: "Something resting on a surface is 'on' the table.", orderIndex: 10 },
  { id: "ssc-cgl-english-cloze-test-q12", topicId: "ssc-cgl-english-cloze-test", text: "Fill in the blank: 'I am fond ___ music.'", optionA: "of", optionB: "for", optionC: "with", optionD: "to", correctOption: "A", explanation: "The correct phrase is 'fond of'.", orderIndex: 11 },

  // ── General Awareness: Indian Polity Quick Facts ──
  { id: "ssc-cgl-general-awareness-indian-polity-facts-q09", topicId: "ssc-cgl-general-awareness-indian-polity-facts", text: "The minimum age to become President of India is:", optionA: "35 years", optionB: "25 years", optionC: "30 years", optionD: "40 years", correctOption: "A", explanation: "A person must be at least 35 years old to be President.", orderIndex: 8 },
  { id: "ssc-cgl-general-awareness-indian-polity-facts-q10", topicId: "ssc-cgl-general-awareness-indian-polity-facts", text: "The number of members nominated to the Rajya Sabha by the President is:", optionA: "12", optionB: "2", optionC: "10", optionD: "20", correctOption: "A", explanation: "The President nominates 12 members to the Rajya Sabha.", orderIndex: 9 },
  { id: "ssc-cgl-general-awareness-indian-polity-facts-q11", topicId: "ssc-cgl-general-awareness-indian-polity-facts", text: "The Fundamental Duties are contained in which article of the Constitution?", optionA: "Article 51A", optionB: "Article 21", optionC: "Article 370", optionD: "Article 14", correctOption: "A", explanation: "Article 51A lists the Fundamental Duties of citizens.", orderIndex: 10 },
  { id: "ssc-cgl-general-awareness-indian-polity-facts-q12", topicId: "ssc-cgl-general-awareness-indian-polity-facts", text: "The minimum age to become a member of the Lok Sabha is:", optionA: "25 years", optionB: "30 years", optionC: "21 years", optionD: "35 years", correctOption: "A", explanation: "A Lok Sabha member must be at least 25 years old.", orderIndex: 11 },

  // ── General Awareness: Static GK: History ──
  { id: "ssc-cgl-general-awareness-history-q09", topicId: "ssc-cgl-general-awareness-history", text: "The Quit India Movement was launched in the year:", optionA: "1942", optionB: "1930", optionC: "1919", optionD: "1947", correctOption: "A", explanation: "Gandhi launched the Quit India Movement in 1942.", orderIndex: 8 },
  { id: "ssc-cgl-general-awareness-history-q10", topicId: "ssc-cgl-general-awareness-history", text: "The first Indian Governor-General of independent India was:", optionA: "C. Rajagopalachari", optionB: "Jawaharlal Nehru", optionC: "Lord Mountbatten", optionD: "Rajendra Prasad", correctOption: "A", explanation: "C. Rajagopalachari was the first (and only) Indian Governor-General.", orderIndex: 9 },
  { id: "ssc-cgl-general-awareness-history-q11", topicId: "ssc-cgl-general-awareness-history", text: "The Indian National Congress was founded in the year:", optionA: "1885", optionB: "1857", optionC: "1905", optionD: "1919", correctOption: "A", explanation: "The Indian National Congress was founded in 1885.", orderIndex: 10 },
  { id: "ssc-cgl-general-awareness-history-q12", topicId: "ssc-cgl-general-awareness-history", text: "The Battle of Plassey was fought in the year:", optionA: "1757", optionB: "1764", optionC: "1857", optionD: "1526", correctOption: "A", explanation: "The Battle of Plassey took place in 1757.", orderIndex: 11 },

  // ── General Awareness: Static GK: Geography ──
  { id: "ssc-cgl-general-awareness-geography-q09", topicId: "ssc-cgl-general-awareness-geography", text: "The longest river in India is the:", optionA: "Ganga", optionB: "Yamuna", optionC: "Godavari", optionD: "Narmada", correctOption: "A", explanation: "The Ganga is the longest river within India.", orderIndex: 8 },
  { id: "ssc-cgl-general-awareness-geography-q10", topicId: "ssc-cgl-general-awareness-geography", text: "The highest mountain peak located in India is:", optionA: "Kanchenjunga", optionB: "Mount Everest", optionC: "Nanda Devi", optionD: "K2", correctOption: "A", explanation: "Kanchenjunga is the highest peak lying within India's borders.", orderIndex: 9 },
  { id: "ssc-cgl-general-awareness-geography-q11", topicId: "ssc-cgl-general-awareness-geography", text: "The Tropic of Cancer passes through how many Indian states?", optionA: "8", optionB: "5", optionC: "10", optionD: "6", correctOption: "A", explanation: "The Tropic of Cancer passes through 8 Indian states.", orderIndex: 10 },
  { id: "ssc-cgl-general-awareness-geography-q12", topicId: "ssc-cgl-general-awareness-geography", text: "The largest Indian state by area is:", optionA: "Rajasthan", optionB: "Madhya Pradesh", optionC: "Maharashtra", optionD: "Uttar Pradesh", correctOption: "A", explanation: "Rajasthan is the largest Indian state by area.", orderIndex: 11 },

  // ── General Awareness: General Science Facts ──
  { id: "ssc-cgl-general-awareness-general-science-q09", topicId: "ssc-cgl-general-awareness-general-science", text: "The chemical symbol for gold is:", optionA: "Au", optionB: "Ag", optionC: "Gd", optionD: "Go", correctOption: "A", explanation: "Gold's symbol is Au (from the Latin 'aurum').", orderIndex: 8 },
  { id: "ssc-cgl-general-awareness-general-science-q10", topicId: "ssc-cgl-general-awareness-general-science", text: "The 'powerhouse of the cell' is the:", optionA: "Mitochondria", optionB: "Nucleus", optionC: "Ribosome", optionD: "Golgi body", correctOption: "A", explanation: "Mitochondria produce ATP and are called the powerhouse of the cell.", orderIndex: 9 },
  { id: "ssc-cgl-general-awareness-general-science-q11", topicId: "ssc-cgl-general-awareness-general-science", text: "The most abundant gas in Earth's atmosphere is:", optionA: "Nitrogen", optionB: "Oxygen", optionC: "Carbon dioxide", optionD: "Hydrogen", correctOption: "A", explanation: "Nitrogen makes up about 78% of the atmosphere.", orderIndex: 10 },
  { id: "ssc-cgl-general-awareness-general-science-q12", topicId: "ssc-cgl-general-awareness-general-science", text: "The SI unit of force is the:", optionA: "Newton", optionB: "Joule", optionC: "Watt", optionD: "Pascal", correctOption: "A", explanation: "Force is measured in newtons (N).", orderIndex: 11 },

  // ── General Awareness: Indian Economy Basics ──
  { id: "ssc-cgl-general-awareness-economy-basics-q09", topicId: "ssc-cgl-general-awareness-economy-basics", text: "The Reserve Bank of India was established in the year:", optionA: "1935", optionB: "1947", optionC: "1950", optionD: "1991", correctOption: "A", explanation: "The RBI was established in 1935.", orderIndex: 8 },
  { id: "ssc-cgl-general-awareness-economy-basics-q10", topicId: "ssc-cgl-general-awareness-economy-basics", text: "The Goods and Services Tax (GST) was introduced in India in:", optionA: "2017", optionB: "2010", optionC: "2020", optionD: "2005", correctOption: "A", explanation: "GST came into effect on 1 July 2017.", orderIndex: 9 },
  { id: "ssc-cgl-general-awareness-economy-basics-q11", topicId: "ssc-cgl-general-awareness-economy-basics", text: "The apex (central) bank of India is the:", optionA: "Reserve Bank of India", optionB: "State Bank of India", optionC: "NABARD", optionD: "SEBI", correctOption: "A", explanation: "The RBI is India's central bank.", orderIndex: 10 },
  { id: "ssc-cgl-general-awareness-economy-basics-q12", topicId: "ssc-cgl-general-awareness-economy-basics", text: "NITI Aayog replaced which earlier body in 2015?", optionA: "Planning Commission", optionB: "Finance Commission", optionC: "Election Commission", optionD: "UGC", correctOption: "A", explanation: "NITI Aayog replaced the Planning Commission in 2015.", orderIndex: 11 },

  // ── General Awareness: Important Days & Current Affairs ──
  { id: "ssc-cgl-general-awareness-days-current-affairs-q09", topicId: "ssc-cgl-general-awareness-days-current-affairs", text: "World Environment Day is observed on:", optionA: "5 June", optionB: "22 April", optionC: "1 May", optionD: "16 September", correctOption: "A", explanation: "World Environment Day is observed on 5 June.", orderIndex: 8 },
  { id: "ssc-cgl-general-awareness-days-current-affairs-q10", topicId: "ssc-cgl-general-awareness-days-current-affairs", text: "International Yoga Day is observed on:", optionA: "21 June", optionB: "5 June", optionC: "8 March", optionD: "2 October", correctOption: "A", explanation: "International Yoga Day is celebrated on 21 June.", orderIndex: 9 },
  { id: "ssc-cgl-general-awareness-days-current-affairs-q11", topicId: "ssc-cgl-general-awareness-days-current-affairs", text: "India celebrates its Independence Day on:", optionA: "15 August", optionB: "26 January", optionC: "2 October", optionD: "14 November", correctOption: "A", explanation: "India's Independence Day is 15 August.", orderIndex: 10 },
  { id: "ssc-cgl-general-awareness-days-current-affairs-q12", topicId: "ssc-cgl-general-awareness-days-current-affairs", text: "World Health Day is observed on:", optionA: "7 April", optionB: "1 December", optionC: "5 June", optionD: "21 June", correctOption: "A", explanation: "World Health Day is observed on 7 April, the WHO's founding day.", orderIndex: 11 },

  // ── General Awareness: Books, Authors & Awards ──
  { id: "ssc-cgl-general-awareness-books-authors-awards-q09", topicId: "ssc-cgl-general-awareness-books-authors-awards", text: "The book 'Wings of Fire' was written by:", optionA: "A. P. J. Abdul Kalam", optionB: "Jawaharlal Nehru", optionC: "R. K. Narayan", optionD: "Arundhati Roy", correctOption: "A", explanation: "'Wings of Fire' is the autobiography of A. P. J. Abdul Kalam.", orderIndex: 8 },
  { id: "ssc-cgl-general-awareness-books-authors-awards-q10", topicId: "ssc-cgl-general-awareness-books-authors-awards", text: "The highest civilian award of India is the:", optionA: "Bharat Ratna", optionB: "Padma Vibhushan", optionC: "Param Vir Chakra", optionD: "Padma Shri", correctOption: "A", explanation: "The Bharat Ratna is India's highest civilian award.", orderIndex: 9 },
  { id: "ssc-cgl-general-awareness-books-authors-awards-q11", topicId: "ssc-cgl-general-awareness-books-authors-awards", text: "The Indian who won the Nobel Prize in Literature for 'Gitanjali' was:", optionA: "Rabindranath Tagore", optionB: "Amartya Sen", optionC: "C. V. Raman", optionD: "Mother Teresa", correctOption: "A", explanation: "Rabindranath Tagore won the 1913 Nobel Prize in Literature for Gitanjali.", orderIndex: 10 },
  { id: "ssc-cgl-general-awareness-books-authors-awards-q12", topicId: "ssc-cgl-general-awareness-books-authors-awards", text: "The book 'The Discovery of India' was written by:", optionA: "Jawaharlal Nehru", optionB: "Mahatma Gandhi", optionC: "B. R. Ambedkar", optionD: "Sardar Patel", correctOption: "A", explanation: "'The Discovery of India' was written by Jawaharlal Nehru.", orderIndex: 11 }
];
