// SSC CGL depth expansion — question-density top-up. Raises the highest-yield
// SSC CGL topics from 12 to 16 questions each (q13–q16, orderIndex 12–15). No
// new topics or study notes.
import type { Question } from "@jyotir/core";

export const sscDepthQuestions: Question[] = [
  // ── Quant: Percentages & Profit-Loss ──
  { id: "ssc-cgl-quant-percentages-profit-loss-q13", topicId: "ssc-cgl-quant-percentages-profit-loss", text: "An article bought for 500 is sold for 600. The profit percentage is:", optionA: "20%", optionB: "16.7%", optionC: "25%", optionD: "10%", correctOption: "A", explanation: "Profit = 100 on 500, so profit% = 100/500 × 100 = 20%.", orderIndex: 12 },
  { id: "ssc-cgl-quant-percentages-profit-loss-q14", topicId: "ssc-cgl-quant-percentages-profit-loss", text: "If the price of an item increases from 200 to 250, the percentage increase is:", optionA: "25%", optionB: "20%", optionC: "50%", optionD: "10%", correctOption: "A", explanation: "Increase = 50 on 200, so 50/200 × 100 = 25%.", orderIndex: 13 },
  { id: "ssc-cgl-quant-percentages-profit-loss-q15", topicId: "ssc-cgl-quant-percentages-profit-loss", text: "A shopkeeper offers a 10% discount on a marked price of 500. The selling price is:", optionA: "450", optionB: "490", optionC: "400", optionD: "550", correctOption: "A", explanation: "SP = 500 × 0.90 = 450.", orderIndex: 14 },
  { id: "ssc-cgl-quant-percentages-profit-loss-q16", topicId: "ssc-cgl-quant-percentages-profit-loss", text: "Selling at a loss of 20%, an item priced (cost) 250 fetches:", optionA: "200", optionB: "230", optionC: "300", optionD: "210", correctOption: "A", explanation: "SP = 250 × 0.80 = 200.", orderIndex: 15 },

  // ── Quant: Time, Speed & Distance ──
  { id: "ssc-cgl-quant-time-speed-distance-q13", topicId: "ssc-cgl-quant-time-speed-distance", text: "A car travels 180 km in 3 hours. Its average speed is:", optionA: "60 km/h", optionB: "50 km/h", optionC: "540 km/h", optionD: "45 km/h", correctOption: "A", explanation: "Speed = distance/time = 180/3 = 60 km/h.", orderIndex: 12 },
  { id: "ssc-cgl-quant-time-speed-distance-q14", topicId: "ssc-cgl-quant-time-speed-distance", text: "To convert 72 km/h into m/s, multiply by 5/18 to get:", optionA: "20 m/s", optionB: "25 m/s", optionC: "18 m/s", optionD: "10 m/s", correctOption: "A", explanation: "Convert: 72 × 5/18 = 20 m/s.", orderIndex: 13 },
  { id: "ssc-cgl-quant-time-speed-distance-q15", topicId: "ssc-cgl-quant-time-speed-distance", text: "Two trains move toward each other at 40 and 60 km/h. Their relative speed is:", optionA: "100 km/h", optionB: "20 km/h", optionC: "50 km/h", optionD: "2400 km/h", correctOption: "A", explanation: "Approaching speeds add: 40 + 60 = 100 km/h.", orderIndex: 14 },
  { id: "ssc-cgl-quant-time-speed-distance-q16", topicId: "ssc-cgl-quant-time-speed-distance", text: "A man covers 30 km at 10 km/h. The time taken is:", optionA: "3 hours", optionB: "2 hours", optionC: "300 hours", optionD: "1 hour", correctOption: "A", explanation: "Time = distance/speed = 30/10 = 3 hours.", orderIndex: 15 },

  // ── Quant: Simple & Compound Interest ──
  { id: "ssc-cgl-quant-simple-compound-interest-q13", topicId: "ssc-cgl-quant-simple-compound-interest", text: "The simple interest on 1000 at 5% per annum for 2 years is:", optionA: "100", optionB: "50", optionC: "1050", optionD: "200", correctOption: "A", explanation: "SI = PRT/100 = 1000 × 5 × 2 / 100 = 100.", orderIndex: 12 },
  { id: "ssc-cgl-quant-simple-compound-interest-q14", topicId: "ssc-cgl-quant-simple-compound-interest", text: "The compound interest on 1000 at 10% per annum for 2 years is:", optionA: "210", optionB: "200", optionC: "100", optionD: "121", correctOption: "A", explanation: "Amount = 1000(1.1)² = 1210, so CI = 210.", orderIndex: 13 },
  { id: "ssc-cgl-quant-simple-compound-interest-q15", topicId: "ssc-cgl-quant-simple-compound-interest", text: "At simple interest, a sum doubles in 10 years. The annual rate is:", optionA: "10%", optionB: "5%", optionC: "20%", optionD: "12%", correctOption: "A", explanation: "To double, SI = P, so R = 100/T = 100/10 = 10%.", orderIndex: 14 },
  { id: "ssc-cgl-quant-simple-compound-interest-q16", topicId: "ssc-cgl-quant-simple-compound-interest", text: "For the same principal, rate and time (>1 year), compound interest is:", optionA: "Greater than simple interest", optionB: "Less than simple interest", optionC: "Equal to simple interest", optionD: "Always zero", correctOption: "A", explanation: "CI exceeds SI beyond the first period because interest is earned on interest.", orderIndex: 15 },

  // ── Quant: Number System (LCM/HCF) ──
  { id: "ssc-cgl-quant-number-system-q13", topicId: "ssc-cgl-quant-number-system", text: "The HCF of 12 and 18 is:", optionA: "6", optionB: "36", optionC: "3", optionD: "2", correctOption: "A", explanation: "The greatest common divisor of 12 and 18 is 6.", orderIndex: 12 },
  { id: "ssc-cgl-quant-number-system-q14", topicId: "ssc-cgl-quant-number-system", text: "The LCM of 4 and 6 is:", optionA: "12", optionB: "24", optionC: "2", optionD: "10", correctOption: "A", explanation: "The least common multiple of 4 and 6 is 12.", orderIndex: 13 },
  { id: "ssc-cgl-quant-number-system-q15", topicId: "ssc-cgl-quant-number-system", text: "For two numbers, the product of the LCM and HCF equals:", optionA: "The product of the numbers", optionB: "Their sum", optionC: "Their difference", optionD: "Their average", correctOption: "A", explanation: "LCM × HCF = product of the two numbers.", orderIndex: 14 },
  { id: "ssc-cgl-quant-number-system-q16", topicId: "ssc-cgl-quant-number-system", text: "A number divisible by both 2 and 3 is always divisible by:", optionA: "6", optionB: "5", optionC: "4", optionD: "9", correctOption: "A", explanation: "Divisibility by 2 and 3 (co-prime) implies divisibility by 6.", orderIndex: 15 },

  // ── Reasoning: Coding-Decoding & Series ──
  { id: "ssc-cgl-reasoning-coding-decoding-series-q13", topicId: "ssc-cgl-reasoning-coding-decoding-series", text: "If CAT is coded as DBU (each letter +1), then DOG is coded as:", optionA: "EPH", optionB: "CNF", optionC: "EPG", optionD: "FQI", correctOption: "A", explanation: "Shifting each letter forward by one: D→E, O→P, G→H gives EPH.", orderIndex: 12 },
  { id: "ssc-cgl-reasoning-coding-decoding-series-q14", topicId: "ssc-cgl-reasoning-coding-decoding-series", text: "Find the next term: 2, 6, 12, 20, __", optionA: "30", optionB: "28", optionC: "24", optionD: "26", correctOption: "A", explanation: "Differences 4, 6, 8, 10 give 20 + 10 = 30.", orderIndex: 13 },
  { id: "ssc-cgl-reasoning-coding-decoding-series-q15", topicId: "ssc-cgl-reasoning-coding-decoding-series", text: "Complete the series: 3, 9, 27, 81, __", optionA: "243", optionB: "162", optionC: "108", optionD: "324", correctOption: "A", explanation: "Each term is multiplied by 3: 81 × 3 = 243.", orderIndex: 14 },
  { id: "ssc-cgl-reasoning-coding-decoding-series-q16", topicId: "ssc-cgl-reasoning-coding-decoding-series", text: "In a code, if A=1, B=2, ..., then the sum for the word 'BAD' is:", optionA: "7", optionB: "6", optionC: "8", optionD: "5", correctOption: "A", explanation: "B(2) + A(1) + D(4) = 7.", orderIndex: 15 },

  // ── Reasoning: Blood Relations ──
  { id: "ssc-cgl-reasoning-blood-relations-q13", topicId: "ssc-cgl-reasoning-blood-relations", text: "Your father's brother is your:", optionA: "Uncle", optionB: "Nephew", optionC: "Cousin", optionD: "Brother", correctOption: "A", explanation: "The father's brother is one's (paternal) uncle.", orderIndex: 12 },
  { id: "ssc-cgl-reasoning-blood-relations-q14", topicId: "ssc-cgl-reasoning-blood-relations", text: "Your mother's mother is your:", optionA: "Grandmother", optionB: "Aunt", optionC: "Sister", optionD: "Niece", correctOption: "A", explanation: "The mother's mother is the maternal grandmother.", orderIndex: 13 },
  { id: "ssc-cgl-reasoning-blood-relations-q15", topicId: "ssc-cgl-reasoning-blood-relations", text: "Pointing to a man, a woman said 'He is the son of my grandfather's only son.' The man is the woman's:", optionA: "Brother", optionB: "Father", optionC: "Uncle", optionD: "Cousin", correctOption: "A", explanation: "Her grandfather's only son is her father; his son is her brother.", orderIndex: 14 },
  { id: "ssc-cgl-reasoning-blood-relations-q16", topicId: "ssc-cgl-reasoning-blood-relations", text: "Your sister's daughter is your:", optionA: "Niece", optionB: "Cousin", optionC: "Aunt", optionD: "Sister", correctOption: "A", explanation: "A sister's daughter is one's niece.", orderIndex: 15 },

  // ── Reasoning: Syllogism ──
  { id: "ssc-cgl-reasoning-syllogism-q13", topicId: "ssc-cgl-reasoning-syllogism", text: "All cats are animals. All animals breathe. Therefore:", optionA: "All cats breathe", optionB: "All animals are cats", optionC: "No cat breathes", optionD: "Some animals are plants", correctOption: "A", explanation: "By transitivity, all cats are animals and all animals breathe, so all cats breathe.", orderIndex: 12 },
  { id: "ssc-cgl-reasoning-syllogism-q14", topicId: "ssc-cgl-reasoning-syllogism", text: "In syllogisms, a conclusion is valid only if it:", optionA: "Necessarily follows from the premises", optionB: "Sounds reasonable", optionC: "Is factually true", optionD: "Is possible", correctOption: "A", explanation: "Validity requires the conclusion to follow necessarily from the given premises.", orderIndex: 13 },
  { id: "ssc-cgl-reasoning-syllogism-q15", topicId: "ssc-cgl-reasoning-syllogism", text: "'No A is B' logically implies:", optionA: "No B is A", optionB: "All B are A", optionC: "Some A are B", optionD: "All A are B", correctOption: "A", explanation: "A universal negative converts: 'No A is B' means 'No B is A'.", orderIndex: 14 },
  { id: "ssc-cgl-reasoning-syllogism-q16", topicId: "ssc-cgl-reasoning-syllogism", text: "All roses are flowers. Some flowers fade quickly. It definitely follows that:", optionA: "Nothing definite about roses fading", optionB: "All roses fade quickly", optionC: "No rose fades", optionD: "Some roses are not flowers", correctOption: "A", explanation: "The 'some flowers fade' premise does not necessarily include roses, so nothing definite follows.", orderIndex: 15 },

  // ── English: Spotting Errors ──
  { id: "ssc-cgl-english-spotting-errors-q13", topicId: "ssc-cgl-english-spotting-errors", text: "Choose the correct sentence:", optionA: "He has been living here since 2010.", optionB: "He is living here since 2010.", optionC: "He living here since 2010.", optionD: "He has living here since 2010.", correctOption: "A", explanation: "'Since' with a point in time takes the present perfect continuous: has been living.", orderIndex: 12 },
  { id: "ssc-cgl-english-spotting-errors-q14", topicId: "ssc-cgl-english-spotting-errors", text: "Identify the correct subject-verb agreement:", optionA: "Each of the boys was present.", optionB: "Each of the boys were present.", optionC: "Each of the boys are present.", optionD: "Each of the boys have present.", correctOption: "A", explanation: "'Each' is singular, so it takes the singular verb 'was'.", orderIndex: 13 },
  { id: "ssc-cgl-english-spotting-errors-q15", topicId: "ssc-cgl-english-spotting-errors", text: "Choose the grammatically correct option:", optionA: "One of my friends is a doctor.", optionB: "One of my friends are a doctor.", optionC: "One of my friend is a doctor.", optionD: "One of my friends are doctors.", correctOption: "A", explanation: "'One of my friends' takes a singular verb: 'is'.", orderIndex: 14 },
  { id: "ssc-cgl-english-spotting-errors-q16", topicId: "ssc-cgl-english-spotting-errors", text: "Select the sentence with correct preposition usage:", optionA: "She is good at mathematics.", optionB: "She is good in mathematics.", optionC: "She is good on mathematics.", optionD: "She is good for mathematics.", correctOption: "A", explanation: "The idiomatic preposition after 'good' for a skill is 'at'.", orderIndex: 15 }
];
