// UPSC depth expansion — Geography (pass 3). Adds core physical, resource, and
// world-geography chapters missing from the Geography subject. Each is a new
// topic with a 2-minute study note and a full 12-question drill.
import type { AuthoredMaterial } from "./builder";
import type { Question, Topic } from "@jyotir/core";

export const geoTopics: Topic[] = [
  // Geography (existing max orderIndex = 3)
  { id: "upsc-geography-geomorphology-and-plate-tectonics", subjectId: "upsc-geography", name: "Geomorphology & Plate Tectonics", slug: "geomorphology-and-plate-tectonics", orderIndex: 4 },
  { id: "upsc-geography-climatology-atmosphere-and-winds", subjectId: "upsc-geography", name: "Climatology: Atmosphere & Winds", slug: "climatology-atmosphere-and-winds", orderIndex: 5 },
  { id: "upsc-geography-oceanography", subjectId: "upsc-geography", name: "Oceanography", slug: "oceanography", orderIndex: 6 },
  { id: "upsc-geography-indian-resources-and-minerals", subjectId: "upsc-geography", name: "Indian Resources & Minerals", slug: "indian-resources-and-minerals", orderIndex: 7 },
  { id: "upsc-geography-economic-and-population-geography", subjectId: "upsc-geography", name: "Economic & Population Geography of India", slug: "economic-and-population-geography", orderIndex: 8 },
  { id: "upsc-geography-world-regional-geography", subjectId: "upsc-geography", name: "World Regional Geography", slug: "world-regional-geography", orderIndex: 9 }
];

export const geoMaterials: AuthoredMaterial[] = [
  { id: "upsc-geography-geomorphology-and-plate-tectonics-m01", topicId: "upsc-geography-geomorphology-and-plate-tectonics", title: "Geomorphology & Plate Tectonics", content: `The **Earth's interior** has three layers: **crust** (thin, silica-alumina 'SIAL' continental and silica-magnesia 'SIMA' oceanic), **mantle** (below the **Mohorovicic discontinuity**), and **core** (outer liquid, inner solid — mostly iron-nickel 'NIFE', source of the magnetic field). We know this mainly from **seismic (earthquake) waves** — P-waves (primary, travel through solids and liquids) and S-waves (secondary, only through solids; their 'shadow zone' proves the outer core is liquid).

**Plate tectonics** (building on Wegener's continental drift and Hess's sea-floor spreading) says the **lithosphere** is broken into plates moving on the plastic **asthenosphere**, driven by **mantle convection**. Boundaries are **divergent** (mid-ocean ridges, new crust), **convergent** (subduction → trenches, fold mountains like the **Himalayas** from the Indian–Eurasian collision; volcanic arcs), and **transform** (sliding, e.g., the San Andreas Fault). Most **earthquakes and volcanoes** occur along boundaries, especially the **Pacific 'Ring of Fire'**. Volcanoes are active, dormant, or extinct.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "upsc-geography-climatology-atmosphere-and-winds-m01", topicId: "upsc-geography-climatology-atmosphere-and-winds", title: "Climatology: Atmosphere & Winds", content: `The **atmosphere** layers upward are **troposphere** (weather, temperature falls with height), **stratosphere** (holds the **ozone layer** that absorbs UV), **mesosphere** (coldest; meteors burn), **thermosphere** (ionosphere reflects radio waves; auroras), and **exosphere**. **Insolation** (incoming solar radiation) heats the earth, which warms air by conduction, convection, and radiation.

**Air pressure** falls with altitude; global **pressure belts** are the equatorial low, subtropical highs, subpolar lows, and polar highs. Winds blow high→low pressure, deflected by the **Coriolis force** (Ferrel's law: right in the Northern Hemisphere, left in the Southern). **Planetary winds**: trade winds (easterlies), westerlies, and polar easterlies. **Periodic winds** include monsoons and land/sea breezes; **local winds** include the Loo, Chinook, and Foehn. **Rainfall** is convectional, orographic (relief), or cyclonic (frontal). **Cyclones** are tropical (hurricanes/typhoons over warm seas) or temperate (frontal). Humidity condenses as dew, fog, clouds (cirrus, cumulus, stratus, nimbus), and precipitation.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "upsc-geography-oceanography-m01", topicId: "upsc-geography-oceanography", title: "Oceanography", content: `Oceans cover ~71% of Earth. The **relief** descends through the **continental shelf** (shallow, richest in fish and petroleum), **continental slope**, **abyssal plain**, and deep **trenches** (the **Mariana Trench** is the deepest point). **Salinity** (average ~35 ppt) is highest in enclosed seas (the Dead Sea, Lake Van) and lowest near river mouths and melting ice.

**Ocean currents** move heat around the globe: **warm currents** (e.g., the **Gulf Stream**, North Atlantic Drift, Kuroshio) flow poleward and warm coasts; **cold currents** (e.g., Labrador, Benguela, Humboldt/Peru) flow equatorward. Where warm and cold currents meet, rich **fishing grounds** form (e.g., Grand Banks, where the Gulf Stream meets the Labrador). **Tides** — the rise and fall of sea level from the Moon's and Sun's gravitational pull — are highest as **spring tides** (new/full moon, when Sun and Moon align) and lowest as **neap tides** (quarter moons). **El Niño** (warming of the eastern Pacific) and **La Niña** disrupt weather worldwide, including the Indian monsoon.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "upsc-geography-indian-resources-and-minerals-m01", topicId: "upsc-geography-indian-resources-and-minerals", title: "Indian Resources & Minerals", content: `India's minerals cluster in the **peninsular plateau** (the Chota Nagpur plateau of Jharkhand–Odisha–Chhattisgarh is the richest belt). **Iron ore**: India has large reserves (hematite, magnetite) in Odisha, Jharkhand, Chhattisgarh, Karnataka. **Coal** (mostly Gondwana, in Damodar, Son, Mahanadi valleys) is the main energy source; **lignite** at Neyveli (Tamil Nadu). **Petroleum**: Mumbai High (offshore), Assam (Digboi — oldest), and Gujarat. **Bauxite** (for aluminium) in Odisha; **manganese, copper, mica** (India leads in mica) also occur.

**Energy**: besides coal and oil, India develops **hydropower**, **nuclear** (Tarapur, Kudankulam), and fast-growing **renewables** — solar (National Solar Mission), wind, and biomass. **Atomic minerals**: monazite sands of Kerala hold thorium (key to India's three-stage nuclear plan). **Multipurpose river valley projects** (Bhakra-Nangal on the Sutlej, Damodar Valley, Hirakud on the Mahanadi, Nagarjuna Sagar) provide irrigation, power, and flood control — Nehru called them the 'temples of modern India'.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "upsc-geography-economic-and-population-geography-m01", topicId: "upsc-geography-economic-and-population-geography", title: "Economic & Population Geography of India", content: `**Population**: India is the world's most populous country. The **2011 Census** recorded ~1.21 billion, a sex ratio of 943 females per 1000 males, and literacy of ~74%. India is in **Stage III of the demographic transition** (falling birth and death rates), with a large young workforce (the **demographic dividend**). **Kerala** leads in literacy and human development; **Bihar** has the highest density and fertility.

**Agriculture** employs the most people; key crops are rice (east, south), wheat (north-west), cotton (Deccan black soil), sugarcane, and tea (Assam, Nilgiris). **Industry**: major regions are Mumbai-Pune, Hooghly (jute), Ahmedabad (cotton textiles), Chota Nagpur (iron & steel — TISCO Jamshedpur, SAIL plants at Bhilai, Bokaro, Rourkela, Durgapur), and Bangalore (IT). **Transport** arteries include the Golden Quadrilateral highways, the vast railway network, and major ports (**Mumbai, JNPT** on the west; **Chennai, Kolkata, Visakhapatnam** on the east). Services, especially IT and finance, now dominate GDP.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "upsc-geography-world-regional-geography-m01", topicId: "upsc-geography-world-regional-geography", title: "World Regional Geography", content: `The Earth is gridded by **latitudes** (parallels: Equator 0°, Tropics of Cancer 23.5°N and Capricorn 23.5°S, Arctic and Antarctic Circles 66.5°) and **longitudes** (meridians: the **Prime Meridian** 0° at Greenwich; the 180° **International Date Line**). The Earth rotates 15° per hour, so **time zones** shift accordingly; India uses **IST at 82.5°E**.

**Continents and features**: Asia is the largest continent; the **Sahara** (Africa) is the largest hot desert; the **Nile** and **Amazon** are the longest and largest rivers; **Mt. Everest** (Himalayas) is the highest peak. **Climatic/biome regions** include equatorial rainforests (Amazon, Congo), tropical grasslands (**Savanna** of Africa), temperate grasslands (**Prairies** of North America, **Steppes** of Eurasia, **Pampas** of South America, **Downs** of Australia, **Velds** of South Africa), **Mediterranean** lands (dry summers), and Tundra. Major straits (Malacca, Hormuz, Gibraltar, Bering) and canals (**Suez** linking the Mediterranean and Red Sea; **Panama** linking the Atlantic and Pacific) are vital to global trade.`, estimatedReadTime: 2, orderIndex: 0 }
];

export const geoQuestions: Question[] = [
  // ── Geomorphology & Plate Tectonics ──
  { id: "upsc-geography-geomorphology-and-plate-tectonics-q01", topicId: "upsc-geography-geomorphology-and-plate-tectonics", text: "The innermost layer of the Earth, composed mainly of iron and nickel, is the:", optionA: "Crust", optionB: "Mantle", optionC: "Core", optionD: "Asthenosphere", correctOption: "C", explanation: "The core (NIFE — nickel and iron) is the Earth's innermost layer.", orderIndex: 0 },
  { id: "upsc-geography-geomorphology-and-plate-tectonics-q02", topicId: "upsc-geography-geomorphology-and-plate-tectonics", text: "Which seismic waves cannot pass through liquids, proving the outer core is liquid?", optionA: "P-waves", optionB: "S-waves", optionC: "L-waves", optionD: "Sound waves", correctOption: "B", explanation: "S-waves travel only through solids; their shadow zone shows the outer core is liquid.", orderIndex: 1 },
  { id: "upsc-geography-geomorphology-and-plate-tectonics-q03", topicId: "upsc-geography-geomorphology-and-plate-tectonics", text: "The boundary between the crust and the mantle is the:", optionA: "Mohorovicic discontinuity", optionB: "Gutenberg discontinuity", optionC: "Lehmann discontinuity", optionD: "Conrad discontinuity", correctOption: "A", explanation: "The Mohorovicic (Moho) discontinuity separates the crust from the mantle.", orderIndex: 2 },
  { id: "upsc-geography-geomorphology-and-plate-tectonics-q04", topicId: "upsc-geography-geomorphology-and-plate-tectonics", text: "The theory of continental drift was proposed by:", optionA: "Alfred Wegener", optionB: "Harry Hess", optionC: "Charles Darwin", optionD: "James Hutton", correctOption: "A", explanation: "Alfred Wegener proposed continental drift and the supercontinent Pangaea.", orderIndex: 3 },
  { id: "upsc-geography-geomorphology-and-plate-tectonics-q05", topicId: "upsc-geography-geomorphology-and-plate-tectonics", text: "The Himalayas were formed by the collision of the Indian plate with the:", optionA: "Eurasian plate", optionB: "Pacific plate", optionC: "African plate", optionD: "Nazca plate", correctOption: "A", explanation: "The Himalayas are fold mountains from the Indian–Eurasian plate convergence.", orderIndex: 4 },
  { id: "upsc-geography-geomorphology-and-plate-tectonics-q06", topicId: "upsc-geography-geomorphology-and-plate-tectonics", text: "New oceanic crust is created at which type of plate boundary?", optionA: "Divergent boundary", optionB: "Convergent boundary", optionC: "Transform boundary", optionD: "Passive margin", correctOption: "A", explanation: "At divergent boundaries (mid-ocean ridges), magma rises and forms new crust.", orderIndex: 5 },
  { id: "upsc-geography-geomorphology-and-plate-tectonics-q07", topicId: "upsc-geography-geomorphology-and-plate-tectonics", text: "The zone with the world's most intense volcanic and earthquake activity is the:", optionA: "Pacific Ring of Fire", optionB: "Mid-Atlantic Ridge only", optionC: "Sahara belt", optionD: "Great Rift Valley only", correctOption: "A", explanation: "The Pacific 'Ring of Fire' has the highest concentration of volcanoes and quakes.", orderIndex: 6 },
  { id: "upsc-geography-geomorphology-and-plate-tectonics-q08", topicId: "upsc-geography-geomorphology-and-plate-tectonics", text: "The San Andreas Fault is an example of which plate boundary?", optionA: "Transform (conservative)", optionB: "Divergent", optionC: "Convergent", optionD: "Subduction", correctOption: "A", explanation: "The San Andreas Fault is a transform boundary where plates slide past each other.", orderIndex: 7 },
  { id: "upsc-geography-geomorphology-and-plate-tectonics-q09", topicId: "upsc-geography-geomorphology-and-plate-tectonics", text: "Sea-floor spreading was proposed by:", optionA: "Harry Hess", optionB: "Alfred Wegener", optionC: "Arthur Holmes", optionD: "Charles Lyell", correctOption: "A", explanation: "Harry Hess proposed sea-floor spreading, supporting plate tectonics.", orderIndex: 8 },
  { id: "upsc-geography-geomorphology-and-plate-tectonics-q10", topicId: "upsc-geography-geomorphology-and-plate-tectonics", text: "The plastic layer of the upper mantle on which plates move is the:", optionA: "Asthenosphere", optionB: "Lithosphere", optionC: "Barysphere", optionD: "Stratosphere", correctOption: "A", explanation: "Plates of the lithosphere ride on the semi-molten asthenosphere.", orderIndex: 9 },
  { id: "upsc-geography-geomorphology-and-plate-tectonics-q11", topicId: "upsc-geography-geomorphology-and-plate-tectonics", text: "Deep ocean trenches are typically formed at:", optionA: "Convergent (subduction) boundaries", optionB: "Divergent boundaries", optionC: "Transform faults", optionD: "Continental shields", correctOption: "A", explanation: "Subduction of one plate under another at convergent boundaries creates trenches.", orderIndex: 10 },
  { id: "upsc-geography-geomorphology-and-plate-tectonics-q12", topicId: "upsc-geography-geomorphology-and-plate-tectonics", text: "A volcano that has not erupted in recorded history but may erupt again is termed:", optionA: "Dormant", optionB: "Active", optionC: "Extinct", optionD: "Shield", correctOption: "A", explanation: "A dormant ('sleeping') volcano is currently inactive but capable of erupting again.", orderIndex: 11 },

  // ── Climatology: Atmosphere & Winds ──
  { id: "upsc-geography-climatology-atmosphere-and-winds-q01", topicId: "upsc-geography-climatology-atmosphere-and-winds", text: "The lowest atmospheric layer, where all weather occurs, is the:", optionA: "Troposphere", optionB: "Stratosphere", optionC: "Mesosphere", optionD: "Thermosphere", correctOption: "A", explanation: "The troposphere is the weather layer, where temperature falls with height.", orderIndex: 0 },
  { id: "upsc-geography-climatology-atmosphere-and-winds-q02", topicId: "upsc-geography-climatology-atmosphere-and-winds", text: "The ozone layer that absorbs harmful ultraviolet radiation lies in the:", optionA: "Stratosphere", optionB: "Troposphere", optionC: "Exosphere", optionD: "Mesosphere", correctOption: "A", explanation: "The ozone layer is in the stratosphere and shields the surface from UV rays.", orderIndex: 1 },
  { id: "upsc-geography-climatology-atmosphere-and-winds-q03", topicId: "upsc-geography-climatology-atmosphere-and-winds", text: "Meteors typically burn up in which atmospheric layer?", optionA: "Mesosphere", optionB: "Troposphere", optionC: "Stratosphere", optionD: "Exosphere", correctOption: "A", explanation: "The mesosphere is the coldest layer, where most meteors burn on entry.", orderIndex: 2 },
  { id: "upsc-geography-climatology-atmosphere-and-winds-q04", topicId: "upsc-geography-climatology-atmosphere-and-winds", text: "The apparent deflection of winds due to the Earth's rotation is the:", optionA: "Coriolis force", optionB: "Centrifugal force", optionC: "Gravitational force", optionD: "Frictional force", correctOption: "A", explanation: "The Coriolis force deflects winds right in the N. Hemisphere and left in the S.", orderIndex: 3 },
  { id: "upsc-geography-climatology-atmosphere-and-winds-q05", topicId: "upsc-geography-climatology-atmosphere-and-winds", text: "Winds that blow from the subtropical high toward the equatorial low are the:", optionA: "Trade winds", optionB: "Westerlies", optionC: "Polar easterlies", optionD: "Monsoons", correctOption: "A", explanation: "The trade winds blow from subtropical highs toward the equator.", orderIndex: 4 },
  { id: "upsc-geography-climatology-atmosphere-and-winds-q06", topicId: "upsc-geography-climatology-atmosphere-and-winds", text: "Rainfall caused by air rising over mountains is called:", optionA: "Orographic (relief) rainfall", optionB: "Convectional rainfall", optionC: "Cyclonic rainfall", optionD: "Frontal rainfall", correctOption: "A", explanation: "Orographic rainfall occurs when moist air is forced up over mountains and cools.", orderIndex: 5 },
  { id: "upsc-geography-climatology-atmosphere-and-winds-q07", topicId: "upsc-geography-climatology-atmosphere-and-winds", text: "Tropical cyclones are known as 'typhoons' in which region?", optionA: "The China Sea / western Pacific", optionB: "The Atlantic", optionC: "The Indian Ocean", optionD: "Australia", correctOption: "A", explanation: "They are called typhoons in the western Pacific and hurricanes in the Atlantic.", orderIndex: 6 },
  { id: "upsc-geography-climatology-atmosphere-and-winds-q08", topicId: "upsc-geography-climatology-atmosphere-and-winds", text: "The hot, dry local wind of northern India in summer is the:", optionA: "Loo", optionB: "Chinook", optionC: "Foehn", optionD: "Mistral", correctOption: "A", explanation: "The Loo is a hot, dry summer wind of the northern Indian plains.", orderIndex: 7 },
  { id: "upsc-geography-climatology-atmosphere-and-winds-q09", topicId: "upsc-geography-climatology-atmosphere-and-winds", text: "The layer that reflects radio waves back to Earth (aiding communication) is the:", optionA: "Ionosphere (thermosphere)", optionB: "Troposphere", optionC: "Stratosphere", optionD: "Exosphere", correctOption: "A", explanation: "The ionosphere reflects radio waves, enabling long-distance radio communication.", orderIndex: 8 },
  { id: "upsc-geography-climatology-atmosphere-and-winds-q10", topicId: "upsc-geography-climatology-atmosphere-and-winds", text: "Incoming solar radiation received by the Earth is called:", optionA: "Insolation", optionB: "Albedo", optionC: "Radiation fog", optionD: "Terrestrial radiation", correctOption: "A", explanation: "Insolation is the incoming solar radiation reaching the Earth's surface.", orderIndex: 9 },
  { id: "upsc-geography-climatology-atmosphere-and-winds-q11", topicId: "upsc-geography-climatology-atmosphere-and-winds", text: "Feathery, high-altitude ice clouds are called:", optionA: "Cirrus", optionB: "Cumulus", optionC: "Stratus", optionD: "Nimbus", correctOption: "A", explanation: "Cirrus clouds are wispy, high-altitude clouds made of ice crystals.", orderIndex: 10 },
  { id: "upsc-geography-climatology-atmosphere-and-winds-q12", topicId: "upsc-geography-climatology-atmosphere-and-winds", text: "Atmospheric pressure with increasing altitude generally:", optionA: "Decreases", optionB: "Increases", optionC: "Stays constant", optionD: "Doubles", correctOption: "A", explanation: "Air pressure decreases with altitude as the overlying air column shrinks.", orderIndex: 11 },

  // ── Oceanography ──
  { id: "upsc-geography-oceanography-q01", topicId: "upsc-geography-oceanography", text: "The shallow, gently sloping margin of a continent under the sea is the:", optionA: "Continental shelf", optionB: "Continental slope", optionC: "Abyssal plain", optionD: "Oceanic trench", correctOption: "A", explanation: "The continental shelf is shallow, rich in fish, and holds most offshore petroleum.", orderIndex: 0 },
  { id: "upsc-geography-oceanography-q02", topicId: "upsc-geography-oceanography", text: "The deepest known point in the oceans is the:", optionA: "Mariana Trench", optionB: "Puerto Rico Trench", optionC: "Java Trench", optionD: "Peru-Chile Trench", correctOption: "A", explanation: "The Mariana Trench (Challenger Deep) in the Pacific is the deepest ocean point.", orderIndex: 1 },
  { id: "upsc-geography-oceanography-q03", topicId: "upsc-geography-oceanography", text: "The warm ocean current off the eastern coast of North America is the:", optionA: "Gulf Stream", optionB: "Labrador Current", optionC: "Benguela Current", optionD: "Humboldt Current", correctOption: "A", explanation: "The warm Gulf Stream flows north along eastern North America and warms NW Europe.", orderIndex: 2 },
  { id: "upsc-geography-oceanography-q04", topicId: "upsc-geography-oceanography", text: "Spring tides, the highest tides, occur when the Sun, Moon, and Earth are:", optionA: "Aligned (new/full moon)", optionB: "At right angles", optionC: "Farthest apart", optionD: "In an eclipse only", correctOption: "A", explanation: "Spring tides occur at new and full moon when Sun and Moon pull in a line.", orderIndex: 3 },
  { id: "upsc-geography-oceanography-q05", topicId: "upsc-geography-oceanography", text: "Rich fishing grounds like the Grand Banks form where:", optionA: "Warm and cold currents meet", optionB: "Rivers dry up", optionC: "Trenches deepen", optionD: "Salinity is highest", correctOption: "A", explanation: "The mixing of warm and cold currents brings nutrients, creating rich fisheries.", orderIndex: 4 },
  { id: "upsc-geography-oceanography-q06", topicId: "upsc-geography-oceanography", text: "The average salinity of ocean water is about:", optionA: "35 parts per thousand", optionB: "3.5 parts per thousand", optionC: "350 parts per thousand", optionD: "10 parts per thousand", correctOption: "A", explanation: "Ocean water averages about 35 ppt (grams of salt per kilogram of water).", orderIndex: 5 },
  { id: "upsc-geography-oceanography-q07", topicId: "upsc-geography-oceanography", text: "The periodic warming of the eastern Pacific that disrupts the Indian monsoon is:", optionA: "El Niño", optionB: "La Niña", optionC: "The Gulf Stream", optionD: "The Humboldt Current", correctOption: "A", explanation: "El Niño (warming of the eastern Pacific) is often linked with weak Indian monsoons.", orderIndex: 6 },
  { id: "upsc-geography-oceanography-q08", topicId: "upsc-geography-oceanography", text: "Neap tides, the lowest tides, occur during the:", optionA: "First and third quarter moons", optionB: "Full moon", optionC: "New moon", optionD: "Solar eclipse", correctOption: "A", explanation: "Neap tides occur at quarter moons when Sun and Moon pull at right angles.", orderIndex: 7 },
  { id: "upsc-geography-oceanography-q09", topicId: "upsc-geography-oceanography", text: "The cold current along the western coast of South America is the:", optionA: "Humboldt (Peru) Current", optionB: "Gulf Stream", optionC: "Kuroshio Current", optionD: "Agulhas Current", correctOption: "A", explanation: "The cold Humboldt (Peru) Current flows along western South America.", orderIndex: 8 },
  { id: "upsc-geography-oceanography-q10", topicId: "upsc-geography-oceanography", text: "The highest salinity is found in which of the following?", optionA: "The Dead Sea", optionB: "The Baltic Sea", optionC: "The mouth of the Amazon", optionD: "The Arctic Ocean", correctOption: "A", explanation: "Enclosed, highly evaporating water bodies like the Dead Sea have extreme salinity.", orderIndex: 9 },
  { id: "upsc-geography-oceanography-q11", topicId: "upsc-geography-oceanography", text: "Ocean currents are set in motion primarily by:", optionA: "Prevailing winds (and temperature/salinity differences)", optionB: "Earthquakes", optionC: "Tsunamis", optionD: "River discharge only", correctOption: "A", explanation: "Surface currents are driven mainly by prevailing winds, modified by Coriolis and density.", orderIndex: 10 },
  { id: "upsc-geography-oceanography-q12", topicId: "upsc-geography-oceanography", text: "The daily rise and fall of sea level caused by gravitational pull is called:", optionA: "Tides", optionB: "Currents", optionC: "Waves", optionD: "Upwelling", correctOption: "A", explanation: "Tides are the periodic rise and fall of sea level due to lunar and solar gravity.", orderIndex: 11 },

  // ── Indian Resources & Minerals ──
  { id: "upsc-geography-indian-resources-and-minerals-q01", topicId: "upsc-geography-indian-resources-and-minerals", text: "India's richest mineral belt is the:", optionA: "Chota Nagpur plateau", optionB: "Thar desert", optionC: "Indo-Gangetic plain", optionD: "Konkan coast", correctOption: "A", explanation: "The Chota Nagpur plateau (Jharkhand–Odisha–Chhattisgarh) is India's mineral heartland.", orderIndex: 0 },
  { id: "upsc-geography-indian-resources-and-minerals-q02", topicId: "upsc-geography-indian-resources-and-minerals", text: "The bulk of India's coal reserves are of which geological type?", optionA: "Gondwana coal", optionB: "Tertiary coal", optionC: "Anthracite", optionD: "Peat", correctOption: "A", explanation: "Most Indian coal is Gondwana coal, found in the Damodar, Son, and Mahanadi valleys.", orderIndex: 1 },
  { id: "upsc-geography-indian-resources-and-minerals-q03", topicId: "upsc-geography-indian-resources-and-minerals", text: "India's oldest oil field, in Assam, is:", optionA: "Digboi", optionB: "Mumbai High", optionC: "Bombay High", optionD: "Ankleshwar", correctOption: "A", explanation: "Digboi in Assam is India's oldest oil field, operational since the 19th century.", orderIndex: 2 },
  { id: "upsc-geography-indian-resources-and-minerals-q04", topicId: "upsc-geography-indian-resources-and-minerals", text: "Bauxite is the chief ore for producing:", optionA: "Aluminium", optionB: "Iron", optionC: "Copper", optionD: "Zinc", correctOption: "A", explanation: "Bauxite is refined into alumina and then smelted into aluminium.", orderIndex: 3 },
  { id: "upsc-geography-indian-resources-and-minerals-q05", topicId: "upsc-geography-indian-resources-and-minerals", text: "India's leading offshore oil producer is:", optionA: "Mumbai High", optionB: "Digboi", optionC: "Neyveli", optionD: "Singareni", correctOption: "A", explanation: "Mumbai High, off the Maharashtra coast, is India's largest offshore oil field.", orderIndex: 4 },
  { id: "upsc-geography-indian-resources-and-minerals-q06", topicId: "upsc-geography-indian-resources-and-minerals", text: "The monazite sands of Kerala are an important source of:", optionA: "Thorium", optionB: "Uranium only", optionC: "Gold", optionD: "Diamond", correctOption: "A", explanation: "Kerala's monazite sands hold thorium, central to India's three-stage nuclear programme.", orderIndex: 5 },
  { id: "upsc-geography-indian-resources-and-minerals-q07", topicId: "upsc-geography-indian-resources-and-minerals", text: "The Bhakra-Nangal multipurpose project is built on the river:", optionA: "Sutlej", optionB: "Mahanadi", optionC: "Damodar", optionD: "Krishna", correctOption: "A", explanation: "The Bhakra-Nangal project is on the Sutlej river in Punjab/Himachal.", orderIndex: 6 },
  { id: "upsc-geography-indian-resources-and-minerals-q08", topicId: "upsc-geography-indian-resources-and-minerals", text: "The Hirakud dam, one of the world's longest, is on the river:", optionA: "Mahanadi", optionB: "Godavari", optionC: "Narmada", optionD: "Kaveri", correctOption: "A", explanation: "The Hirakud dam in Odisha is built across the Mahanadi river.", orderIndex: 7 },
  { id: "upsc-geography-indian-resources-and-minerals-q09", topicId: "upsc-geography-indian-resources-and-minerals", text: "India is a world leader in the production of which mineral used in electrical insulation?", optionA: "Mica", optionB: "Gold", optionC: "Petroleum", optionD: "Nickel", correctOption: "A", explanation: "India has long been a leading producer of mica, valued for electrical insulation.", orderIndex: 8 },
  { id: "upsc-geography-indian-resources-and-minerals-q10", topicId: "upsc-geography-indian-resources-and-minerals", text: "Lignite (brown coal) is mined chiefly at:", optionA: "Neyveli (Tamil Nadu)", optionB: "Jharia (Jharkhand)", optionC: "Raniganj (West Bengal)", optionD: "Korba (Chhattisgarh)", correctOption: "A", explanation: "Neyveli in Tamil Nadu is India's main lignite (brown coal) mining centre.", orderIndex: 9 },
  { id: "upsc-geography-indian-resources-and-minerals-q11", topicId: "upsc-geography-indian-resources-and-minerals", text: "The Kudankulam nuclear power plant is located in:", optionA: "Tamil Nadu", optionB: "Gujarat", optionC: "Rajasthan", optionD: "Maharashtra", correctOption: "A", explanation: "The Kudankulam nuclear plant is in Tamil Nadu, built with Russian cooperation.", orderIndex: 10 },
  { id: "upsc-geography-indian-resources-and-minerals-q12", topicId: "upsc-geography-indian-resources-and-minerals", text: "Nehru famously called multipurpose river valley projects the:", optionA: "'Temples of modern India'", optionB: "'Lungs of the nation'", optionC: "'Arteries of trade'", optionD: "'Engines of growth'", correctOption: "A", explanation: "Nehru called large dams and river valley projects the 'temples of modern India'.", orderIndex: 11 },

  // ── Economic & Population Geography of India ──
  { id: "upsc-geography-economic-and-population-geography-q01", topicId: "upsc-geography-economic-and-population-geography", text: "According to the 2011 Census, India's sex ratio was about:", optionA: "943 females per 1000 males", optionB: "1000 females per 1000 males", optionC: "850 females per 1000 males", optionD: "990 females per 1000 males", correctOption: "A", explanation: "The 2011 Census recorded a sex ratio of 943 females per 1000 males.", orderIndex: 0 },
  { id: "upsc-geography-economic-and-population-geography-q02", topicId: "upsc-geography-economic-and-population-geography", text: "The Indian state with the highest literacy rate is:", optionA: "Kerala", optionB: "Bihar", optionC: "Uttar Pradesh", optionD: "Rajasthan", correctOption: "A", explanation: "Kerala consistently has the highest literacy rate among Indian states.", orderIndex: 1 },
  { id: "upsc-geography-economic-and-population-geography-q03", topicId: "upsc-geography-economic-and-population-geography", text: "The Tata Iron and Steel Company (TISCO) is located at:", optionA: "Jamshedpur", optionB: "Bhilai", optionC: "Rourkela", optionD: "Bokaro", correctOption: "A", explanation: "TISCO, India's first major steel plant, is at Jamshedpur (Jharkhand).", orderIndex: 2 },
  { id: "upsc-geography-economic-and-population-geography-q04", topicId: "upsc-geography-economic-and-population-geography", text: "The 'demographic dividend' refers to the growth potential from:", optionA: "A large working-age population", optionB: "A shrinking population", optionC: "An ageing population", optionD: "High mortality", correctOption: "A", explanation: "The demographic dividend is the economic boost from a rising working-age share.", orderIndex: 3 },
  { id: "upsc-geography-economic-and-population-geography-q05", topicId: "upsc-geography-economic-and-population-geography", text: "The black cotton (regur) soil of the Deccan is best suited for growing:", optionA: "Cotton", optionB: "Tea", optionC: "Rice", optionD: "Coffee", correctOption: "A", explanation: "Black (regur) soil retains moisture and is ideal for cotton cultivation.", orderIndex: 4 },
  { id: "upsc-geography-economic-and-population-geography-q06", topicId: "upsc-geography-economic-and-population-geography", text: "The Hooghly industrial region is historically famous for which industry?", optionA: "Jute", optionB: "Cotton textiles", optionC: "Automobiles", optionD: "Petrochemicals", correctOption: "A", explanation: "The Hooghly belt around Kolkata is the centre of India's jute industry.", orderIndex: 5 },
  { id: "upsc-geography-economic-and-population-geography-q07", topicId: "upsc-geography-economic-and-population-geography", text: "India's Silicon Valley, a hub of the IT industry, is:", optionA: "Bengaluru", optionB: "Kanpur", optionC: "Ludhiana", optionD: "Surat", correctOption: "A", explanation: "Bengaluru (Bangalore) is India's leading information-technology hub.", orderIndex: 6 },
  { id: "upsc-geography-economic-and-population-geography-q08", topicId: "upsc-geography-economic-and-population-geography", text: "The tea-growing region concentrated in the north-east of India is:", optionA: "Assam", optionB: "Punjab", optionC: "Gujarat", optionD: "Haryana", correctOption: "A", explanation: "Assam is India's largest tea-producing region, along with the Nilgiris in the south.", orderIndex: 7 },
  { id: "upsc-geography-economic-and-population-geography-q09", topicId: "upsc-geography-economic-and-population-geography", text: "Jawaharlal Nehru Port (JNPT), India's largest container port, is near:", optionA: "Mumbai", optionB: "Chennai", optionC: "Kolkata", optionD: "Kochi", correctOption: "A", explanation: "JNPT (Nhava Sheva) near Mumbai is India's largest container-handling port.", orderIndex: 8 },
  { id: "upsc-geography-economic-and-population-geography-q10", topicId: "upsc-geography-economic-and-population-geography", text: "In the demographic transition model, India is broadly in:", optionA: "Stage III (falling birth and death rates)", optionB: "Stage I (high birth and death rates)", optionC: "Stage V (declining population)", optionD: "Stage IV only", correctOption: "A", explanation: "India is largely in Stage III, with both birth and death rates declining.", orderIndex: 9 },
  { id: "upsc-geography-economic-and-population-geography-q11", topicId: "upsc-geography-economic-and-population-geography", text: "The steel plant at Bhilai is located in the state of:", optionA: "Chhattisgarh", optionB: "Odisha", optionC: "Jharkhand", optionD: "West Bengal", correctOption: "A", explanation: "The Bhilai Steel Plant (SAIL) is in Chhattisgarh; Rourkela is in Odisha.", orderIndex: 10 },
  { id: "upsc-geography-economic-and-population-geography-q12", topicId: "upsc-geography-economic-and-population-geography", text: "The wheat-growing heartland of India is the:", optionA: "North-western plains (Punjab, Haryana, western UP)", optionB: "Eastern coastal plains", optionC: "Deccan plateau", optionD: "North-eastern hills", correctOption: "A", explanation: "The fertile, irrigated north-western plains are India's wheat bowl.", orderIndex: 11 },

  // ── World Regional Geography ──
  { id: "upsc-geography-world-regional-geography-q01", topicId: "upsc-geography-world-regional-geography", text: "The Prime Meridian (0° longitude) passes through:", optionA: "Greenwich", optionB: "Paris", optionC: "Washington", optionD: "Delhi", correctOption: "A", explanation: "The Prime Meridian passes through Greenwich, London.", orderIndex: 0 },
  { id: "upsc-geography-world-regional-geography-q02", topicId: "upsc-geography-world-regional-geography", text: "The Tropic of Cancer lies at a latitude of:", optionA: "23.5° North", optionB: "23.5° South", optionC: "66.5° North", optionD: "0°", correctOption: "A", explanation: "The Tropic of Cancer is at 23.5° North; the Tropic of Capricorn is at 23.5° South.", orderIndex: 1 },
  { id: "upsc-geography-world-regional-geography-q03", topicId: "upsc-geography-world-regional-geography", text: "The largest hot desert in the world is the:", optionA: "Sahara", optionB: "Gobi", optionC: "Thar", optionD: "Kalahari", correctOption: "A", explanation: "The Sahara in North Africa is the world's largest hot desert.", orderIndex: 2 },
  { id: "upsc-geography-world-regional-geography-q04", topicId: "upsc-geography-world-regional-geography", text: "The temperate grasslands of North America are called the:", optionA: "Prairies", optionB: "Steppes", optionC: "Pampas", optionD: "Velds", correctOption: "A", explanation: "The Prairies are North America's temperate grasslands; Steppes are in Eurasia.", orderIndex: 3 },
  { id: "upsc-geography-world-regional-geography-q05", topicId: "upsc-geography-world-regional-geography", text: "The Suez Canal connects the Mediterranean Sea with the:", optionA: "Red Sea", optionB: "Black Sea", optionC: "Caspian Sea", optionD: "Arabian Sea", correctOption: "A", explanation: "The Suez Canal links the Mediterranean and Red Seas, shortening Europe–Asia trade.", orderIndex: 4 },
  { id: "upsc-geography-world-regional-geography-q06", topicId: "upsc-geography-world-regional-geography", text: "Indian Standard Time (IST) is based on the meridian passing at:", optionA: "82.5° East", optionB: "0°", optionC: "90° East", optionD: "75° East", correctOption: "A", explanation: "IST is set to 82.5°E (near Mirzapur), 5 hours 30 minutes ahead of GMT.", orderIndex: 5 },
  { id: "upsc-geography-world-regional-geography-q07", topicId: "upsc-geography-world-regional-geography", text: "The temperate grasslands of South America are the:", optionA: "Pampas", optionB: "Prairies", optionC: "Downs", optionD: "Savanna", correctOption: "A", explanation: "The Pampas are South America's grasslands; the Downs are in Australia.", orderIndex: 6 },
  { id: "upsc-geography-world-regional-geography-q08", topicId: "upsc-geography-world-regional-geography", text: "The Strait of Malacca is a key shipping route between the Indian Ocean and the:", optionA: "Pacific Ocean (South China Sea)", optionB: "Atlantic Ocean", optionC: "Arctic Ocean", optionD: "Mediterranean Sea", correctOption: "A", explanation: "The Strait of Malacca links the Indian Ocean with the South China Sea/Pacific.", orderIndex: 7 },
  { id: "upsc-geography-world-regional-geography-q09", topicId: "upsc-geography-world-regional-geography", text: "The world's largest continent by area is:", optionA: "Asia", optionB: "Africa", optionC: "North America", optionD: "Europe", correctOption: "A", explanation: "Asia is the largest continent both in area and population.", orderIndex: 8 },
  { id: "upsc-geography-world-regional-geography-q10", topicId: "upsc-geography-world-regional-geography", text: "The 180° meridian roughly corresponds to the:", optionA: "International Date Line", optionB: "Prime Meridian", optionC: "Equator", optionD: "Tropic of Capricorn", correctOption: "A", explanation: "The International Date Line roughly follows the 180° meridian in the Pacific.", orderIndex: 9 },
  { id: "upsc-geography-world-regional-geography-q11", topicId: "upsc-geography-world-regional-geography", text: "Mediterranean-type climate regions are characterised by:", optionA: "Dry summers and wet winters", optionB: "Wet summers and dry winters", optionC: "Year-round rainfall", optionD: "No rainfall at all", correctOption: "A", explanation: "Mediterranean climates have hot dry summers and mild wet winters.", orderIndex: 10 },
  { id: "upsc-geography-world-regional-geography-q12", topicId: "upsc-geography-world-regional-geography", text: "The Panama Canal connects the Atlantic Ocean with the:", optionA: "Pacific Ocean", optionB: "Indian Ocean", optionC: "Arctic Ocean", optionD: "Mediterranean Sea", correctOption: "A", explanation: "The Panama Canal links the Atlantic and Pacific Oceans across Central America.", orderIndex: 11 }
];
