// UPSC depth expansion — History (pass 2). Adds high-yield chapters that were
// missing from Ancient, Medieval, and Modern History. Each is a new topic with
// a 2-minute study note and a full 12-question drill.
import type { AuthoredMaterial } from "./builder";
import type { Question, Topic } from "@jyotir/core";

export const historyTopics: Topic[] = [
  // Ancient History (existing max orderIndex = 3)
  { id: "upsc-ancient-history-vedic-age", subjectId: "upsc-ancient-history", name: "The Vedic Age", slug: "vedic-age", orderIndex: 4 },
  { id: "upsc-ancient-history-mahajanapadas", subjectId: "upsc-ancient-history", name: "Mahajanapadas & Rise of Magadha", slug: "mahajanapadas", orderIndex: 5 },
  { id: "upsc-ancient-history-post-mauryan-age", subjectId: "upsc-ancient-history", name: "Post-Mauryan Age", slug: "post-mauryan-age", orderIndex: 6 },
  { id: "upsc-ancient-history-sangam-age", subjectId: "upsc-ancient-history", name: "The Sangam Age", slug: "sangam-age", orderIndex: 7 },
  // Medieval History (existing max orderIndex = 2)
  { id: "upsc-medieval-history-cholas-and-south-india", subjectId: "upsc-medieval-history", name: "Cholas & South Indian Kingdoms", slug: "cholas-and-south-india", orderIndex: 3 },
  { id: "upsc-medieval-history-vijayanagara-and-bahmani", subjectId: "upsc-medieval-history", name: "Vijayanagara & Bahmani Kingdoms", slug: "vijayanagara-and-bahmani", orderIndex: 4 },
  { id: "upsc-medieval-history-maratha-empire", subjectId: "upsc-medieval-history", name: "The Maratha Empire", slug: "maratha-empire", orderIndex: 5 },
  // Modern History (existing max orderIndex = 3)
  { id: "upsc-modern-history-advent-of-europeans", subjectId: "upsc-modern-history", name: "Advent of Europeans & British Conquest", slug: "advent-of-europeans", orderIndex: 4 },
  { id: "upsc-modern-history-economic-impact-of-british-rule", subjectId: "upsc-modern-history", name: "Economic Impact of British Rule", slug: "economic-impact-of-british-rule", orderIndex: 5 },
  { id: "upsc-modern-history-governor-generals-and-administration", subjectId: "upsc-modern-history", name: "Governor-Generals & British Administration", slug: "governor-generals-and-administration", orderIndex: 6 },
  { id: "upsc-modern-history-towards-independence-and-partition", subjectId: "upsc-modern-history", name: "Towards Independence & Partition", slug: "towards-independence-and-partition", orderIndex: 7 }
];

export const historyMaterials: AuthoredMaterial[] = [
  { id: "upsc-ancient-history-vedic-age-m01", topicId: "upsc-ancient-history-vedic-age", title: "The Vedic Age", content: `The **Vedic Age** (c. 1500–600 BCE) follows the Harappan decline and is known from the **Vedas** (Rig, Sama, Yajur, Atharva). The **Early Vedic (Rig Vedic) period** (1500–1000 BCE) centred on the **Sapta Sindhu** (land of seven rivers, Punjab). Society was **pastoral and tribal**; the *raja* led a *jana* (tribe) advised by assemblies — the **Sabha and Samiti**. Cattle (*gau*) were the main wealth; the family was patriarchal but women had a fair status. **Indra, Agni, and Varuna** were chief deities.

The **Later Vedic period** (1000–600 BCE) shifted east to the **Ganga–Yamuna doab**. Agriculture and **iron (krishna ayas)** rose; larger kingdoms (*janapadas*) emerged and kingship grew hereditary with elaborate sacrifices (*Rajasuya*, *Ashvamedha*). The **varna system** hardened into four classes and women's status declined. The **four Vedas**, Brahmanas, Aranyakas, and **Upanishads** (philosophical texts) form the corpus. 'Satyameva Jayate' comes from the **Mundaka Upanishad**.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "upsc-ancient-history-mahajanapadas-m01", topicId: "upsc-ancient-history-mahajanapadas", title: "Mahajanapadas & Rise of Magadha", content: `By the **6th century BCE**, 16 large states — the **Mahajanapadas** — dominated north India (listed in the Buddhist *Anguttara Nikaya*). They were **monarchies** (e.g., Magadha, Kosala, Vatsa, Avanti) or **republics/ganasanghas** (e.g., Vajji confederacy under the Lichchhavis). This era saw the **second urbanisation**, coinage (**punch-marked coins**), and the rise of Buddhism and Jainism.

**Magadha** (capital first **Rajgir/Girivraja**, later **Pataliputra**) became supreme due to fertile land, iron ore, elephants, and river trade. The **Haryanka dynasty** (Bimbisara, Ajatashatru) expanded it; **Bimbisara** used marriage alliances, **Ajatashatru** defeated the Vajjis. The **Shishunaga** and then **Nanda** dynasties followed; the **Nandas** (Mahapadma Nanda) built a huge army but were overthrown by **Chandragupta Maurya** (with Chanakya) around 321 BCE, founding the Mauryan Empire.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "upsc-ancient-history-post-mauryan-age-m01", topicId: "upsc-ancient-history-post-mauryan-age", title: "Post-Mauryan Age", content: `After Ashoka, the Mauryan Empire declined; the last ruler **Brihadratha** was killed by his general **Pushyamitra Shunga** (185 BCE), founding the **Shunga dynasty**. In the Deccan, the **Satavahanas** (Andhras) rose — **Gautamiputra Satakarni** was their greatest king; they issued lead coins and patronised Prakrit and Buddhist stupas (Amaravati).

In the north-west, successive invaders came: **Indo-Greeks** (Menander/Milinda, first to issue gold coins and portrait coins), **Shakas** (Scythians — Rudradaman I left the Junagadh inscription in Sanskrit), **Parthians**, and the **Kushanas**. The Kushana **Kanishka I** (c. 78 CE, associated with the **Shaka era**) ruled a vast empire from Purushapura (Peshawar), convened the **Fourth Buddhist Council**, and patronised **Mahayana Buddhism** and the **Gandhara and Mathura** schools of art. This age saw flourishing trade on the **Silk Route** and with Rome.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "upsc-ancient-history-sangam-age-m01", topicId: "upsc-ancient-history-sangam-age", title: "The Sangam Age", content: `The **Sangam Age** (c. 300 BCE–300 CE) is the classical period of **Tamil** literature in South India, named after *sangams* (assemblies of poets) held under Pandyan patronage at Madurai. **Sangam literature** (Tolkappiyam on grammar; the Ettuthogai and Pattuppattu anthologies; the epics Silappadikaram and Manimekalai) is the main source, supplemented by Greco-Roman accounts and archaeology.

Three dynasties ruled: the **Cheras** (emblem bow, capital Vanji/Karur — modern Kerala), the **Cholas** (emblem tiger, capital Uraiyur; Karikala was famous), and the **Pandyas** (emblem fish, capital Madurai). The economy thrived on **trade with Rome** (ports like Puhar/Kaveripattinam, Muziris) exporting spices, pearls, and muslin for Roman gold. Society had *tinai* (eco-zones) and honoured heroes with **hero-stones (nadukal)**. The age gave classical Tamil its enduring literary foundation.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "upsc-medieval-history-cholas-and-south-india-m01", topicId: "upsc-medieval-history-cholas-and-south-india", title: "Cholas & South Indian Kingdoms", content: `The **Imperial Cholas** (9th–13th century, capital **Thanjavur**) built South India's greatest medieval empire. **Rajaraja Chola I** built the **Brihadeeswarar (Rajarajeshwara) temple** at Thanjavur (a UNESCO site) and conquered parts of Sri Lanka. His son **Rajendra Chola I** marched to the Ganga (taking the title *Gangaikonda Cholapuram*) and launched a famous **naval expedition to Srivijaya** (Southeast Asia), making the Cholas a maritime power.

Chola administration was notable for **local self-government**: the **Uttaramerur inscriptions** detail elected village assemblies (*ur*, *sabha/mahasabha*) with committees (*variyams*). Art peaked in **Dravidian temple architecture** (soaring *vimanas*) and superb **Chola bronze sculpture** (the dancing Nataraja). Earlier and contemporary powers included the **Pallavas** (Mahabalipuram rock-cut monuments, Narasimhavarman I), the **Chalukyas of Badami** (Pulakeshin II, who checked Harsha), and the **Rashtrakutas** (Ellora's Kailasa temple).`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "upsc-medieval-history-vijayanagara-and-bahmani-m01", topicId: "upsc-medieval-history-vijayanagara-and-bahmani", title: "Vijayanagara & Bahmani Kingdoms", content: `In 1336 **Harihara and Bukka** founded the **Vijayanagara Empire** (capital **Hampi** on the Tungabhadra), and in 1347 the **Bahmani Sultanate** arose in the Deccan — the two clashed for two centuries over the fertile **Raichur doab**. Vijayanagara reached its zenith under **Krishnadevaraya** (Tuluva dynasty, r. 1509–29), a patron of Telugu literature (*Amuktamalyada*) whose court hosted the 'ashtadiggajas'. Foreign travellers (**Nicolo Conti, Abdur Razzaq, Domingo Paes**) described Hampi's wealth. The empire was crushed at the **Battle of Talikota (1565)** by a coalition of Deccan sultans.

The **Bahmani Sultanate** (founded by Alauddin Bahman Shah, capital Gulbarga then Bidar) was ably served by the minister **Mahmud Gawan**. It later fragmented into the five **Deccan Sultanates** — Bijapur (Adil Shahi), Golconda (Qutb Shahi), Ahmadnagar (Nizam Shahi), Bidar, and Berar — remembered for Indo-Islamic architecture like the **Gol Gumbaz** and **Charminar**.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "upsc-medieval-history-maratha-empire-m01", topicId: "upsc-medieval-history-maratha-empire", title: "The Maratha Empire", content: `**Chhatrapati Shivaji** (1630–1680), crowned at Raigad in 1674, founded the **Maratha Empire** against Mughal and Adil Shahi power. He built a strong navy and hill forts, escaped from Agra (1666), and ran an efficient administration with the **Ashtapradhan** (council of eight ministers) and land taxes **chauth** and **sardeshmukhi**. His guerrilla tactics (*ganimi kava*) and Marathi–Sanskrit court culture defined the state.

After the long war with Aurangzeb, real power passed to the **Peshwas** (prime ministers) at Pune. Under **Baji Rao I**, Maratha influence spread across much of India in a confederacy of chiefs (**Scindia** of Gwalior, **Holkar** of Indore, **Gaekwad** of Baroda, **Bhonsle** of Nagpur). Maratha expansion was checked at the **Third Battle of Panipat (1761)** against Ahmad Shah Abdali. The empire finally fell to the British in the three **Anglo-Maratha Wars** (ending 1818).`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "upsc-modern-history-advent-of-europeans-m01", topicId: "upsc-modern-history-advent-of-europeans", title: "Advent of Europeans & British Conquest", content: `**Vasco da Gama** reached Calicut in **1498**, opening the sea route and Portuguese dominance (Goa under Albuquerque). The **Dutch**, **English** (East India Company chartered **1600**), **French**, and Danes followed. The English defeated the Portuguese and, after the **Carnatic Wars**, the French (decisive **Battle of Wandiwash, 1760**), emerging supreme.

British political conquest began in Bengal. The **Battle of Plassey (1757)** — where Robert Clive defeated Nawab **Siraj-ud-Daulah** through the treachery of **Mir Jafar** — gave the Company control of Bengal's resources. The **Battle of Buxar (1764)** against the combined forces of Mir Qasim, Awadh, and Mughal emperor Shah Alam II confirmed British supremacy; the resulting **Treaty of Allahabad (1765)** granted the Company the **Diwani** (revenue rights) of Bengal, Bihar, and Odisha. Expansion continued through the **Subsidiary Alliance** (Wellesley) and the **Doctrine of Lapse** (Dalhousie).`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "upsc-modern-history-economic-impact-of-british-rule-m01", topicId: "upsc-modern-history-economic-impact-of-british-rule", title: "Economic Impact of British Rule", content: `British rule reshaped India's economy to serve Britain. The **Drain of Wealth** theory — articulated by **Dadabhai Naoroji** in *Poverty and Un-British Rule in India* and by R. C. Dutt — held that India's wealth was siphoned off as 'Home Charges', salaries, and unrequited exports without economic return.

Key features: **deindustrialisation** (ruin of Indian handicrafts like Bengal muslin by machine-made British goods and one-way free trade); **commercialisation of agriculture** and forced cash crops (indigo, cotton); and exploitative **land-revenue systems** — the **Permanent Settlement (1793, Cornwallis)** creating zamindars in Bengal, the **Ryotwari system** (Munro, in Madras/Bombay) taxing cultivators directly, and the **Mahalwari system** (north India). High revenue demand caused recurring **famines**. India became a supplier of raw materials and a captive market; railways (from 1853) mainly served colonial trade and troop movement, though they later aided national integration.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "upsc-modern-history-governor-generals-and-administration-m01", topicId: "upsc-modern-history-governor-generals-and-administration", title: "Governor-Generals & British Administration", content: `**Warren Hastings** (first Governor-General of Bengal, 1774) and **Cornwallis** (Permanent Settlement; reformed the civil service — the 'father of civil services') laid early foundations. **Lord Wellesley** introduced the **Subsidiary Alliance**; **Lord William Bentinck** abolished **Sati (1829)** with Raja Ram Mohan Roy and suppressed thuggee; **Lord Dalhousie** annexed states via the **Doctrine of Lapse**, and introduced **railways, telegraph, and the Post Office**.

After the **1857 revolt**, the **Government of India Act 1858** ended Company rule and transferred power to the **Crown**; the Governor-General became **Viceroy** (first, **Canning**). Later Viceroys shaped politics: **Lord Ripon** (Local Self-Government 1882, Ilbert Bill), **Lord Curzon** (Partition of Bengal 1905), **Lord Minto** (Morley-Minto Reforms 1909, separate electorates), **Lord Chelmsford** (Rowlatt Act, Jallianwala Bagh 1919), and **Lord Mountbatten** (last Viceroy, who oversaw the 1947 transfer of power).`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "upsc-modern-history-towards-independence-and-partition-m01", topicId: "upsc-modern-history-towards-independence-and-partition", title: "Towards Independence & Partition", content: `World War II accelerated freedom. The **Cripps Mission (1942)** offered dominion status after the war but was rejected ('a post-dated cheque'), triggering the **Quit India Movement (1942)** — Gandhi's 'Do or Die' call and mass, if suppressed, revolt. Subhas Chandra Bose organised the **Indian National Army (INA)** abroad; the **INA trials** and the **1946 Royal Indian Navy mutiny** shook British authority.

The **Cabinet Mission (1946)** proposed a loose federation but Hindu–Muslim differences hardened after the Muslim League's **Direct Action Day** and communal violence. **Lord Mountbatten's plan (3 June 1947)** accepted Partition. The **Indian Independence Act 1947** created the dominions of **India and Pakistan on 15 August 1947**; the **Radcliffe Line** divided Punjab and Bengal, causing massive migration and bloodshed. The princely states were integrated largely through **Sardar Vallabhbhai Patel** and V. P. Menon (accession, with Hyderabad, Junagadh, and Kashmir as special cases).`, estimatedReadTime: 2, orderIndex: 0 }
];

export const historyQuestions: Question[] = [
  // ── Ancient History: The Vedic Age ──
  { id: "upsc-ancient-history-vedic-age-q01", topicId: "upsc-ancient-history-vedic-age", text: "The Early Vedic (Rig Vedic) people are associated with which region?", optionA: "Sapta Sindhu (land of seven rivers)", optionB: "The Deccan plateau", optionC: "The Gangetic delta", optionD: "The Malabar coast", correctOption: "A", explanation: "The Rig Vedic Aryans lived in the Sapta Sindhu region of Punjab and the north-west.", orderIndex: 0 },
  { id: "upsc-ancient-history-vedic-age-q02", topicId: "upsc-ancient-history-vedic-age", text: "The oldest of the four Vedas is the:", optionA: "Sama Veda", optionB: "Rig Veda", optionC: "Yajur Veda", optionD: "Atharva Veda", correctOption: "B", explanation: "The Rig Veda, a collection of hymns, is the oldest Vedic (and Indo-Aryan) text.", orderIndex: 1 },
  { id: "upsc-ancient-history-vedic-age-q03", topicId: "upsc-ancient-history-vedic-age", text: "The two tribal assemblies of the Rig Vedic polity were the:", optionA: "Sabha and Samiti", optionB: "Ur and Sabha", optionC: "Mahasabha and Nagaram", optionD: "Gana and Sangha", correctOption: "A", explanation: "The Sabha and Samiti were the key tribal assemblies advising the raja.", orderIndex: 2 },
  { id: "upsc-ancient-history-vedic-age-q04", topicId: "upsc-ancient-history-vedic-age", text: "The chief measure of wealth in Rig Vedic society was:", optionA: "Land", optionB: "Cattle (gau)", optionC: "Gold coins", optionD: "Slaves", correctOption: "B", explanation: "Cattle were the main form of wealth; many words for war meant 'search for cattle'.", orderIndex: 3 },
  { id: "upsc-ancient-history-vedic-age-q05", topicId: "upsc-ancient-history-vedic-age", text: "The most frequently invoked deity in the Rig Veda is:", optionA: "Vishnu", optionB: "Shiva", optionC: "Indra", optionD: "Brahma", correctOption: "C", explanation: "Indra, god of war and rain, has the most hymns addressed to him in the Rig Veda.", orderIndex: 4 },
  { id: "upsc-ancient-history-vedic-age-q06", topicId: "upsc-ancient-history-vedic-age", text: "In the Later Vedic period, the centre of activity shifted to the:", optionA: "Ganga–Yamuna doab", optionB: "Indus valley", optionC: "Coromandel coast", optionD: "Kashmir valley", correctOption: "A", explanation: "The Later Vedic people moved east into the fertile Ganga–Yamuna doab.", orderIndex: 5 },
  { id: "upsc-ancient-history-vedic-age-q07", topicId: "upsc-ancient-history-vedic-age", text: "The philosophical texts that form the concluding part of the Vedas are the:", optionA: "Puranas", optionB: "Upanishads", optionC: "Dharmashastras", optionD: "Smritis", correctOption: "B", explanation: "The Upanishads (Vedanta) are the philosophical culmination of Vedic literature.", orderIndex: 6 },
  { id: "upsc-ancient-history-vedic-age-q08", topicId: "upsc-ancient-history-vedic-age", text: "The national motto 'Satyameva Jayate' is taken from the:", optionA: "Rig Veda", optionB: "Mundaka Upanishad", optionC: "Bhagavad Gita", optionD: "Arthashastra", correctOption: "B", explanation: "'Satyameva Jayate' (Truth alone triumphs) comes from the Mundaka Upanishad.", orderIndex: 7 },
  { id: "upsc-ancient-history-vedic-age-q09", topicId: "upsc-ancient-history-vedic-age", text: "The technology that spread widely in the Later Vedic period, aiding expansion, was:", optionA: "Bronze casting", optionB: "Iron (krishna ayas)", optionC: "Steam power", optionD: "Gunpowder", correctOption: "B", explanation: "Iron ('krishna ayas', black metal) enabled forest clearing and farming in the doab.", orderIndex: 8 },
  { id: "upsc-ancient-history-vedic-age-q10", topicId: "upsc-ancient-history-vedic-age", text: "The great royal sacrifices such as Rajasuya and Ashvamedha became prominent in the:", optionA: "Harappan period", optionB: "Later Vedic period", optionC: "Sangam Age", optionD: "Gupta period", correctOption: "B", explanation: "Later Vedic kings performed elaborate sacrifices to assert power and status.", orderIndex: 9 },
  { id: "upsc-ancient-history-vedic-age-q11", topicId: "upsc-ancient-history-vedic-age", text: "Which Veda deals mainly with magic, charms, and everyday life?", optionA: "Atharva Veda", optionB: "Rig Veda", optionC: "Sama Veda", optionD: "Yajur Veda", correctOption: "A", explanation: "The Atharva Veda contains spells and charms reflecting popular beliefs.", orderIndex: 10 },
  { id: "upsc-ancient-history-vedic-age-q12", topicId: "upsc-ancient-history-vedic-age", text: "The Sama Veda is significant because it is the source of Indian:", optionA: "Music", optionB: "Medicine", optionC: "Mathematics", optionD: "Architecture", correctOption: "A", explanation: "The Sama Veda, set to melody for chanting, is regarded as the root of Indian music.", orderIndex: 11 },

  // ── Ancient History: Mahajanapadas & Rise of Magadha ──
  { id: "upsc-ancient-history-mahajanapadas-q01", topicId: "upsc-ancient-history-mahajanapadas", text: "How many Mahajanapadas are listed in Buddhist texts like the Anguttara Nikaya?", optionA: "16", optionB: "8", optionC: "12", optionD: "24", correctOption: "A", explanation: "The Buddhist tradition names sixteen (Solasa) Mahajanapadas of the 6th century BCE.", orderIndex: 0 },
  { id: "upsc-ancient-history-mahajanapadas-q02", topicId: "upsc-ancient-history-mahajanapadas", text: "The Vajji confederacy is an example of a Mahajanapada that was a:", optionA: "Monarchy", optionB: "Republic (gana-sangha)", optionC: "Theocracy", optionD: "Colony", correctOption: "B", explanation: "The Vajji (Lichchhavi) confederacy was a republic or gana-sangha, not a monarchy.", orderIndex: 1 },
  { id: "upsc-ancient-history-mahajanapadas-q03", topicId: "upsc-ancient-history-mahajanapadas", text: "The earliest capital of Magadha was:", optionA: "Pataliputra", optionB: "Rajgir (Girivraja)", optionC: "Ujjain", optionD: "Taxila", correctOption: "B", explanation: "Magadha's first capital was Rajgir (Girivraja); it later shifted to Pataliputra.", orderIndex: 2 },
  { id: "upsc-ancient-history-mahajanapadas-q04", topicId: "upsc-ancient-history-mahajanapadas", text: "Which Haryanka ruler is known for a policy of matrimonial alliances to expand Magadha?", optionA: "Bimbisara", optionB: "Ashoka", optionC: "Kanishka", optionD: "Chandragupta II", correctOption: "A", explanation: "Bimbisara used marriage alliances with Kosala, Vaishali, and others to expand Magadha.", orderIndex: 3 },
  { id: "upsc-ancient-history-mahajanapadas-q05", topicId: "upsc-ancient-history-mahajanapadas", text: "Ajatashatru is best known for defeating the:", optionA: "Vajji confederacy", optionB: "Cholas", optionC: "Kushanas", optionD: "Satavahanas", correctOption: "A", explanation: "Ajatashatru waged a long war and defeated the Vajjis (Lichchhavis) of Vaishali.", orderIndex: 4 },
  { id: "upsc-ancient-history-mahajanapadas-q06", topicId: "upsc-ancient-history-mahajanapadas", text: "The dynasty overthrown by Chandragupta Maurya was the:", optionA: "Nanda dynasty", optionB: "Shunga dynasty", optionC: "Gupta dynasty", optionD: "Pallava dynasty", correctOption: "A", explanation: "Chandragupta Maurya, aided by Chanakya, overthrew the Nanda dynasty around 321 BCE.", orderIndex: 5 },
  { id: "upsc-ancient-history-mahajanapadas-q07", topicId: "upsc-ancient-history-mahajanapadas", text: "The 6th century BCE urban growth in the Ganga valley is called the:", optionA: "First urbanisation", optionB: "Second urbanisation", optionC: "Green revolution", optionD: "Iron collapse", correctOption: "B", explanation: "This period is the 'second urbanisation' (the first being the Harappan cities).", orderIndex: 6 },
  { id: "upsc-ancient-history-mahajanapadas-q08", topicId: "upsc-ancient-history-mahajanapadas", text: "The characteristic coins of the Mahajanapada period were:", optionA: "Punch-marked coins", optionB: "Gold dinars", optionC: "Paper notes", optionD: "Cowrie shells only", correctOption: "A", explanation: "Silver and copper punch-marked coins were the earliest coinage of this era.", orderIndex: 7 },
  { id: "upsc-ancient-history-mahajanapadas-q09", topicId: "upsc-ancient-history-mahajanapadas", text: "Which powerful Mahajanapada had Ujjain as an important centre?", optionA: "Avanti", optionB: "Anga", optionC: "Gandhara", optionD: "Kamboja", correctOption: "A", explanation: "Avanti, with centres at Ujjain and Mahishmati, was among the strongest Mahajanapadas.", orderIndex: 8 },
  { id: "upsc-ancient-history-mahajanapadas-q10", topicId: "upsc-ancient-history-mahajanapadas", text: "The founder of the Nanda dynasty is generally taken to be:", optionA: "Mahapadma Nanda", optionB: "Bindusara", optionC: "Bimbisara", optionD: "Pushyamitra", correctOption: "A", explanation: "Mahapadma Nanda founded the powerful Nanda dynasty of Magadha.", orderIndex: 9 },
  { id: "upsc-ancient-history-mahajanapadas-q11", topicId: "upsc-ancient-history-mahajanapadas", text: "Which geographical advantage helped Magadha's rise?", optionA: "Fertile land, iron ore, and elephants", optionB: "Desert isolation", optionC: "Coastal trade only", optionD: "Mountain barriers", correctOption: "A", explanation: "Fertile Gangetic soil, nearby iron mines, timber, and war-elephants powered Magadha.", orderIndex: 10 },
  { id: "upsc-ancient-history-mahajanapadas-q12", topicId: "upsc-ancient-history-mahajanapadas", text: "Two heterodox religions that arose in this age were:", optionA: "Buddhism and Jainism", optionB: "Sikhism and Islam", optionC: "Christianity and Zoroastrianism", optionD: "Shaivism and Vaishnavism", correctOption: "A", explanation: "Buddhism and Jainism emerged in the 6th century BCE amid the Mahajanapadas.", orderIndex: 11 },

  // ── Ancient History: Post-Mauryan Age ──
  { id: "upsc-ancient-history-post-mauryan-age-q01", topicId: "upsc-ancient-history-post-mauryan-age", text: "The general who founded the Shunga dynasty by killing the last Maurya was:", optionA: "Pushyamitra Shunga", optionB: "Vasudeva Kanva", optionC: "Simuka", optionD: "Kanishka", correctOption: "A", explanation: "Pushyamitra Shunga killed the last Maurya, Brihadratha, in 185 BCE.", orderIndex: 0 },
  { id: "upsc-ancient-history-post-mauryan-age-q02", topicId: "upsc-ancient-history-post-mauryan-age", text: "The greatest ruler of the Satavahana dynasty was:", optionA: "Gautamiputra Satakarni", optionB: "Rudradaman I", optionC: "Menander", optionD: "Kanishka", correctOption: "A", explanation: "Gautamiputra Satakarni was the most powerful Satavahana ruler.", orderIndex: 1 },
  { id: "upsc-ancient-history-post-mauryan-age-q03", topicId: "upsc-ancient-history-post-mauryan-age", text: "The Kushana king associated with the Shaka era (78 CE) is:", optionA: "Kanishka I", optionB: "Ashoka", optionC: "Chandragupta I", optionD: "Kadphises", correctOption: "A", explanation: "Kanishka I is traditionally linked with the start of the Shaka era in 78 CE.", orderIndex: 2 },
  { id: "upsc-ancient-history-post-mauryan-age-q04", topicId: "upsc-ancient-history-post-mauryan-age", text: "The Fourth Buddhist Council was convened under the patronage of:", optionA: "Ashoka", optionB: "Kanishka", optionC: "Harsha", optionD: "Ajatashatru", correctOption: "B", explanation: "Kanishka convened the Fourth Buddhist Council in Kashmir, promoting Mahayana.", orderIndex: 3 },
  { id: "upsc-ancient-history-post-mauryan-age-q05", topicId: "upsc-ancient-history-post-mauryan-age", text: "The Gandhara school of art shows strong influence of:", optionA: "Greco-Roman (Hellenistic) styles", optionB: "Chinese styles", optionC: "Egyptian styles", optionD: "Sumerian styles", correctOption: "A", explanation: "Gandhara art blended Greco-Roman techniques with Buddhist themes.", orderIndex: 4 },
  { id: "upsc-ancient-history-post-mauryan-age-q06", topicId: "upsc-ancient-history-post-mauryan-age", text: "The Indo-Greek rulers were the first in India to issue:", optionA: "Gold coins and portrait coins", optionB: "Paper money", optionC: "Iron coins", optionD: "Cowrie currency", correctOption: "A", explanation: "The Indo-Greeks introduced die-struck gold coins bearing rulers' portraits.", orderIndex: 5 },
  { id: "upsc-ancient-history-post-mauryan-age-q07", topicId: "upsc-ancient-history-post-mauryan-age", text: "The Junagadh rock inscription in Sanskrit was issued by the Shaka ruler:", optionA: "Rudradaman I", optionB: "Nahapana", optionC: "Menander", optionD: "Kanishka", correctOption: "A", explanation: "Rudradaman I's Junagadh inscription is the first long inscription in chaste Sanskrit.", orderIndex: 6 },
  { id: "upsc-ancient-history-post-mauryan-age-q08", topicId: "upsc-ancient-history-post-mauryan-age", text: "The Milindapanho records a dialogue between the monk Nagasena and the Indo-Greek king:", optionA: "Menander (Milinda)", optionB: "Demetrius", optionC: "Seleucus", optionD: "Antiochus", correctOption: "A", explanation: "The Milindapanho is a dialogue between Nagasena and King Menander (Milinda).", orderIndex: 7 },
  { id: "upsc-ancient-history-post-mauryan-age-q09", topicId: "upsc-ancient-history-post-mauryan-age", text: "The Satavahanas issued coins primarily made of:", optionA: "Lead and potin", optionB: "Pure gold", optionC: "Platinum", optionD: "Paper", correctOption: "A", explanation: "The Satavahanas commonly issued lead and potin coins.", orderIndex: 8 },
  { id: "upsc-ancient-history-post-mauryan-age-q10", topicId: "upsc-ancient-history-post-mauryan-age", text: "The Kushana capital Purushapura corresponds to modern:", optionA: "Peshawar", optionB: "Patna", optionC: "Lahore", optionD: "Mathura", correctOption: "A", explanation: "Purushapura, the Kushana capital, is modern Peshawar in Pakistan.", orderIndex: 9 },
  { id: "upsc-ancient-history-post-mauryan-age-q11", topicId: "upsc-ancient-history-post-mauryan-age", text: "Kanishka was a great patron of which branch of Buddhism?", optionA: "Mahayana", optionB: "Theravada only", optionC: "Vajrayana", optionD: "None", correctOption: "A", explanation: "Kanishka patronised Mahayana Buddhism, which spread to Central Asia and China.", orderIndex: 10 },
  { id: "upsc-ancient-history-post-mauryan-age-q12", topicId: "upsc-ancient-history-post-mauryan-age", text: "The post-Mauryan centuries saw flourishing long-distance trade along the:", optionA: "Silk Route", optionB: "Grand Trunk Road only", optionC: "Suez Canal", optionD: "Trans-Siberian route", correctOption: "A", explanation: "The Silk Route linked India to Central Asia, China, and Rome in this period.", orderIndex: 11 },

  // ── Ancient History: The Sangam Age ──
  { id: "upsc-ancient-history-sangam-age-q01", topicId: "upsc-ancient-history-sangam-age", text: "Sangam literature was composed primarily in which language?", optionA: "Sanskrit", optionB: "Tamil", optionC: "Prakrit", optionD: "Telugu", correctOption: "B", explanation: "Sangam literature is the earliest body of classical Tamil poetry.", orderIndex: 0 },
  { id: "upsc-ancient-history-sangam-age-q02", topicId: "upsc-ancient-history-sangam-age", text: "The three ruling dynasties of the Sangam Age were the Cheras, Cholas, and:", optionA: "Pandyas", optionB: "Pallavas", optionC: "Chalukyas", optionD: "Rashtrakutas", correctOption: "A", explanation: "The muvendar — Cheras, Cholas, and Pandyas — ruled the Tamil country.", orderIndex: 1 },
  { id: "upsc-ancient-history-sangam-age-q03", topicId: "upsc-ancient-history-sangam-age", text: "The Sangam assemblies of poets were held under the patronage of the:", optionA: "Pandyas at Madurai", optionB: "Cholas at Thanjavur", optionC: "Cheras at Vanji", optionD: "Pallavas at Kanchi", correctOption: "A", explanation: "The Pandya kings of Madurai are traditionally credited with hosting the sangams.", orderIndex: 2 },
  { id: "upsc-ancient-history-sangam-age-q04", topicId: "upsc-ancient-history-sangam-age", text: "The Tolkappiyam, the earliest Tamil text, is a work on:", optionA: "Grammar and poetics", optionB: "Medicine", optionC: "Astronomy", optionD: "Warfare", correctOption: "A", explanation: "The Tolkappiyam is the oldest Tamil grammar and treatise on poetics.", orderIndex: 3 },
  { id: "upsc-ancient-history-sangam-age-q05", topicId: "upsc-ancient-history-sangam-age", text: "The royal emblem of the Cholas was the:", optionA: "Tiger", optionB: "Fish", optionC: "Bow", optionD: "Lion", correctOption: "A", explanation: "The tiger was the Chola emblem; the Pandyas used the fish and Cheras the bow.", orderIndex: 4 },
  { id: "upsc-ancient-history-sangam-age-q06", topicId: "upsc-ancient-history-sangam-age", text: "The capital of the Pandyas was:", optionA: "Madurai", optionB: "Uraiyur", optionC: "Vanji", optionD: "Kanchipuram", correctOption: "A", explanation: "Madurai was the Pandya capital; Uraiyur was Chola and Vanji was Chera.", orderIndex: 5 },
  { id: "upsc-ancient-history-sangam-age-q07", topicId: "upsc-ancient-history-sangam-age", text: "Sangam-age trade with which empire brought large quantities of gold coins to South India?", optionA: "The Roman Empire", optionB: "The Chinese Empire", optionC: "The Persian Empire", optionD: "The Mauryan Empire", correctOption: "A", explanation: "Brisk trade with Rome (spices, pearls, muslin) brought Roman gold to the Tamil ports.", orderIndex: 6 },
  { id: "upsc-ancient-history-sangam-age-q08", topicId: "upsc-ancient-history-sangam-age", text: "The Tamil epic Silappadikaram was authored by:", optionA: "Ilango Adigal", optionB: "Sittalai Sattanar", optionC: "Tiruvalluvar", optionD: "Kamban", correctOption: "A", explanation: "Silappadikaram ('the tale of the anklet') is attributed to Ilango Adigal.", orderIndex: 7 },
  { id: "upsc-ancient-history-sangam-age-q09", topicId: "upsc-ancient-history-sangam-age", text: "Memorial stones honouring fallen heroes in the Sangam age were called:", optionA: "Nadukal (hero-stones)", optionB: "Stupas", optionC: "Menhirs", optionD: "Rathas", correctOption: "A", explanation: "Nadukal or hero-stones commemorated warriors who died in battle.", orderIndex: 8 },
  { id: "upsc-ancient-history-sangam-age-q10", topicId: "upsc-ancient-history-sangam-age", text: "The famous Chola king of the Sangam age, credited with building embankments on the Kaveri, was:", optionA: "Karikala", optionB: "Rajaraja I", optionC: "Senguttuvan", optionD: "Nedunjeliyan", correctOption: "A", explanation: "Karikala Chola is celebrated in Sangam poetry and linked with Kaveri irrigation works.", orderIndex: 9 },
  { id: "upsc-ancient-history-sangam-age-q11", topicId: "upsc-ancient-history-sangam-age", text: "The important Chola port town of the Sangam age was:", optionA: "Puhar (Kaveripattinam)", optionB: "Tamralipti", optionC: "Bharuch", optionD: "Sopara", correctOption: "A", explanation: "Puhar/Kaveripattinam was the great Chola port described in Sangam literature.", orderIndex: 10 },
  { id: "upsc-ancient-history-sangam-age-q12", topicId: "upsc-ancient-history-sangam-age", text: "Sangam poems classify land into ecological zones known as:", optionA: "Tinai", optionB: "Janapada", optionC: "Vishaya", optionD: "Ahara", correctOption: "A", explanation: "The tinai concept divided the landscape into five poetic/ecological zones.", orderIndex: 11 },

  // ── Medieval History: Cholas & South Indian Kingdoms ──
  { id: "upsc-medieval-history-cholas-and-south-india-q01", topicId: "upsc-medieval-history-cholas-and-south-india", text: "The Brihadeeswarar temple at Thanjavur was built by:", optionA: "Rajaraja Chola I", optionB: "Rajendra Chola I", optionC: "Krishnadevaraya", optionD: "Narasimhavarman I", correctOption: "A", explanation: "Rajaraja Chola I built the Brihadeeswarar (Rajarajeshwara) temple, a UNESCO site.", orderIndex: 0 },
  { id: "upsc-medieval-history-cholas-and-south-india-q02", topicId: "upsc-medieval-history-cholas-and-south-india", text: "Which Chola king led a famous naval expedition to Srivijaya in Southeast Asia?", optionA: "Rajendra Chola I", optionB: "Rajaraja Chola I", optionC: "Kulottunga I", optionD: "Vijayalaya", correctOption: "A", explanation: "Rajendra Chola I sent a naval expedition against Srivijaya, showing Chola sea power.", orderIndex: 1 },
  { id: "upsc-medieval-history-cholas-and-south-india-q03", topicId: "upsc-medieval-history-cholas-and-south-india", text: "The Uttaramerur inscriptions are famous for describing Chola:", optionA: "Local self-government / village assemblies", optionB: "Naval battles", optionC: "Coinage", optionD: "Temple rituals only", correctOption: "A", explanation: "The Uttaramerur inscriptions detail the working of elected village assemblies (sabha).", orderIndex: 2 },
  { id: "upsc-medieval-history-cholas-and-south-india-q04", topicId: "upsc-medieval-history-cholas-and-south-india", text: "Chola bronze sculpture is most iconically represented by the figure of:", optionA: "Nataraja (dancing Shiva)", optionB: "Buddha", optionC: "Mahavira", optionD: "Vishnu Anantasayana", correctOption: "A", explanation: "The dancing Shiva (Nataraja) is the masterpiece of Chola bronze art.", orderIndex: 3 },
  { id: "upsc-medieval-history-cholas-and-south-india-q05", topicId: "upsc-medieval-history-cholas-and-south-india", text: "The Pallava rock-cut monuments and shore temple are located at:", optionA: "Mahabalipuram", optionB: "Thanjavur", optionC: "Hampi", optionD: "Halebidu", correctOption: "A", explanation: "The Pallavas created the rock-cut rathas and shore temple at Mahabalipuram.", orderIndex: 4 },
  { id: "upsc-medieval-history-cholas-and-south-india-q06", topicId: "upsc-medieval-history-cholas-and-south-india", text: "The Chalukya king who defeated Harshavardhana was:", optionA: "Pulakeshin II", optionB: "Mangalesha", optionC: "Kirtivarman", optionD: "Vikramaditya VI", correctOption: "A", explanation: "Pulakeshin II of Badami checked Harsha's advance to the Deccan, per the Aihole inscription.", orderIndex: 5 },
  { id: "upsc-medieval-history-cholas-and-south-india-q07", topicId: "upsc-medieval-history-cholas-and-south-india", text: "The magnificent Kailasa temple at Ellora was carved by the:", optionA: "Rashtrakutas", optionB: "Cholas", optionC: "Pandyas", optionD: "Hoysalas", correctOption: "A", explanation: "The Rashtrakuta king Krishna I had the monolithic Kailasa temple at Ellora carved.", orderIndex: 6 },
  { id: "upsc-medieval-history-cholas-and-south-india-q08", topicId: "upsc-medieval-history-cholas-and-south-india", text: "The Chola capital was:", optionA: "Thanjavur", optionB: "Madurai", optionC: "Kanchipuram", optionD: "Badami", correctOption: "A", explanation: "Thanjavur (Tanjore) was the imperial Chola capital.", orderIndex: 7 },
  { id: "upsc-medieval-history-cholas-and-south-india-q09", topicId: "upsc-medieval-history-cholas-and-south-india", text: "Chola temple architecture belongs to which broad style?", optionA: "Dravidian", optionB: "Nagara", optionC: "Vesara", optionD: "Indo-Saracenic", correctOption: "A", explanation: "Chola temples, with tall pyramidal vimanas, epitomise the Dravidian style.", orderIndex: 8 },
  { id: "upsc-medieval-history-cholas-and-south-india-q10", topicId: "upsc-medieval-history-cholas-and-south-india", text: "The Pallava ruler who defeated the Chalukyas and took the title 'Vatapikonda' was:", optionA: "Narasimhavarman I", optionB: "Mahendravarman II", optionC: "Nandivarman", optionD: "Simhavishnu", correctOption: "A", explanation: "Narasimhavarman I captured the Chalukya capital Vatapi, earning 'Vatapikonda'.", orderIndex: 9 },
  { id: "upsc-medieval-history-cholas-and-south-india-q11", topicId: "upsc-medieval-history-cholas-and-south-india", text: "The Hoysala kingdom is known for its ornate temples at Belur and:", optionA: "Halebidu", optionB: "Konark", optionC: "Khajuraho", optionD: "Modhera", correctOption: "A", explanation: "The Hoysalas built star-shaped, intricately carved temples at Belur and Halebidu.", orderIndex: 10 },
  { id: "upsc-medieval-history-cholas-and-south-india-q12", topicId: "upsc-medieval-history-cholas-and-south-india", text: "Chola village assemblies used which method to elect members, per Uttaramerur?", optionA: "Kudavolai (drawing lots from a pot)", optionB: "Hereditary succession", optionC: "Nomination by the king", optionD: "Purchase of office", correctOption: "A", explanation: "The kudavolai system drew palm-leaf ballots from a pot to select committee members.", orderIndex: 11 },

  // ── Medieval History: Vijayanagara & Bahmani Kingdoms ──
  { id: "upsc-medieval-history-vijayanagara-and-bahmani-q01", topicId: "upsc-medieval-history-vijayanagara-and-bahmani", text: "The Vijayanagara Empire was founded in 1336 by:", optionA: "Harihara and Bukka", optionB: "Krishnadevaraya", optionC: "Alauddin Bahman Shah", optionD: "Mahmud Gawan", correctOption: "A", explanation: "Brothers Harihara and Bukka of the Sangama dynasty founded Vijayanagara in 1336.", orderIndex: 0 },
  { id: "upsc-medieval-history-vijayanagara-and-bahmani-q02", topicId: "upsc-medieval-history-vijayanagara-and-bahmani", text: "The capital of the Vijayanagara Empire was:", optionA: "Hampi", optionB: "Bidar", optionC: "Golconda", optionD: "Gulbarga", correctOption: "A", explanation: "Hampi (Vijayanagara) on the Tungabhadra was the empire's magnificent capital.", orderIndex: 1 },
  { id: "upsc-medieval-history-vijayanagara-and-bahmani-q03", topicId: "upsc-medieval-history-vijayanagara-and-bahmani", text: "The greatest Vijayanagara ruler, of the Tuluva dynasty, was:", optionA: "Krishnadevaraya", optionB: "Harihara II", optionC: "Deva Raya I", optionD: "Rama Raya", correctOption: "A", explanation: "Krishnadevaraya (r. 1509–29) marked the empire's zenith in power and culture.", orderIndex: 2 },
  { id: "upsc-medieval-history-vijayanagara-and-bahmani-q04", topicId: "upsc-medieval-history-vijayanagara-and-bahmani", text: "Krishnadevaraya wrote the Telugu classic:", optionA: "Amuktamalyada", optionB: "Prithviraj Raso", optionC: "Rajatarangini", optionD: "Gita Govinda", correctOption: "A", explanation: "Krishnadevaraya authored the Telugu poem Amuktamalyada and patronised the 'ashtadiggajas'.", orderIndex: 3 },
  { id: "upsc-medieval-history-vijayanagara-and-bahmani-q05", topicId: "upsc-medieval-history-vijayanagara-and-bahmani", text: "The 1565 battle that led to Vijayanagara's decline was the Battle of:", optionA: "Talikota", optionB: "Panipat", optionC: "Plassey", optionD: "Haldighati", correctOption: "A", explanation: "The Battle of Talikota (1565) saw a Deccan-sultanate coalition crush Vijayanagara.", orderIndex: 4 },
  { id: "upsc-medieval-history-vijayanagara-and-bahmani-q06", topicId: "upsc-medieval-history-vijayanagara-and-bahmani", text: "The Bahmani Sultanate was founded in 1347 by:", optionA: "Alauddin Bahman Shah", optionB: "Mahmud Gawan", optionC: "Yusuf Adil Shah", optionD: "Quli Qutb Shah", correctOption: "A", explanation: "Alauddin Bahman Shah (Hasan Gangu) founded the Bahmani Sultanate in the Deccan.", orderIndex: 5 },
  { id: "upsc-medieval-history-vijayanagara-and-bahmani-q07", topicId: "upsc-medieval-history-vijayanagara-and-bahmani", text: "The famous reforming prime minister of the Bahmani kingdom was:", optionA: "Mahmud Gawan", optionB: "Todar Mal", optionC: "Chanakya", optionD: "Birbal", correctOption: "A", explanation: "Mahmud Gawan, a Persian minister, reformed the Bahmani administration and finances.", orderIndex: 6 },
  { id: "upsc-medieval-history-vijayanagara-and-bahmani-q08", topicId: "upsc-medieval-history-vijayanagara-and-bahmani", text: "The Bahmani kingdom later broke up into how many Deccan Sultanates?", optionA: "Five", optionB: "Three", optionC: "Seven", optionD: "Two", correctOption: "A", explanation: "It fragmented into five Deccan Sultanates: Bijapur, Golconda, Ahmadnagar, Bidar, Berar.", orderIndex: 7 },
  { id: "upsc-medieval-history-vijayanagara-and-bahmani-q09", topicId: "upsc-medieval-history-vijayanagara-and-bahmani", text: "The Gol Gumbaz, famous for its whispering gallery, is at Bijapur and was built by the:", optionA: "Adil Shahi dynasty", optionB: "Qutb Shahi dynasty", optionC: "Nizam Shahi dynasty", optionD: "Sangama dynasty", correctOption: "A", explanation: "The Gol Gumbaz is the tomb of Adil Shahi ruler Mohammed Adil Shah at Bijapur.", orderIndex: 8 },
  { id: "upsc-medieval-history-vijayanagara-and-bahmani-q10", topicId: "upsc-medieval-history-vijayanagara-and-bahmani", text: "The Charminar in Hyderabad was built by the:", optionA: "Qutb Shahi dynasty", optionB: "Adil Shahi dynasty", optionC: "Tughlaqs", optionD: "Cholas", correctOption: "A", explanation: "The Charminar was built by Muhammad Quli Qutb Shah of Golconda in 1591.", orderIndex: 9 },
  { id: "upsc-medieval-history-vijayanagara-and-bahmani-q11", topicId: "upsc-medieval-history-vijayanagara-and-bahmani", text: "Foreign travellers Nicolo Conti and Abdur Razzaq described the wealth of:", optionA: "Vijayanagara (Hampi)", optionB: "Delhi", optionC: "Agra", optionD: "Bengal", correctOption: "A", explanation: "Conti, Razzaq, and Paes left vivid accounts of prosperous Vijayanagara.", orderIndex: 10 },
  { id: "upsc-medieval-history-vijayanagara-and-bahmani-q12", topicId: "upsc-medieval-history-vijayanagara-and-bahmani", text: "Vijayanagara and the Bahmani kingdom fought recurrently over the fertile:", optionA: "Raichur doab", optionB: "Ganga delta", optionC: "Malwa plateau", optionD: "Konkan coast", correctOption: "A", explanation: "The Raichur doab between the Krishna and Tungabhadra was long contested.", orderIndex: 11 },

  // ── Medieval History: The Maratha Empire ──
  { id: "upsc-medieval-history-maratha-empire-q01", topicId: "upsc-medieval-history-maratha-empire", text: "The founder of the Maratha Empire, crowned Chhatrapati in 1674, was:", optionA: "Shivaji", optionB: "Baji Rao I", optionC: "Shahu", optionD: "Balaji Vishwanath", correctOption: "A", explanation: "Shivaji was crowned Chhatrapati at Raigad in 1674, founding the Maratha state.", orderIndex: 0 },
  { id: "upsc-medieval-history-maratha-empire-q02", topicId: "upsc-medieval-history-maratha-empire", text: "Shivaji's council of eight ministers was called the:", optionA: "Ashtapradhan", optionB: "Diwan-i-Am", optionC: "Ashtadiggaja", optionD: "Navaratna", correctOption: "A", explanation: "The Ashtapradhan was Shivaji's council of eight ministers, headed by the Peshwa.", orderIndex: 1 },
  { id: "upsc-medieval-history-maratha-empire-q03", topicId: "upsc-medieval-history-maratha-empire", text: "The taxes levied by the Marathas on neighbouring territories were chauth and:", optionA: "Sardeshmukhi", optionB: "Jizya", optionC: "Zakat", optionD: "Khums", correctOption: "A", explanation: "Chauth (one-fourth of revenue) and sardeshmukhi (an extra 10%) funded the Maratha state.", orderIndex: 2 },
  { id: "upsc-medieval-history-maratha-empire-q04", topicId: "upsc-medieval-history-maratha-empire", text: "Shivaji's capital fort was:", optionA: "Raigad", optionB: "Sinhagad", optionC: "Purandar", optionD: "Panhala", correctOption: "A", explanation: "Raigad served as Shivaji's capital and coronation site.", orderIndex: 3 },
  { id: "upsc-medieval-history-maratha-empire-q05", topicId: "upsc-medieval-history-maratha-empire", text: "After Shivaji, effective power passed to hereditary prime ministers called the:", optionA: "Peshwas", optionB: "Nawabs", optionC: "Subedars", optionD: "Diwans", correctOption: "A", explanation: "The Peshwas (Chitpavan Brahmins based at Pune) became the real rulers of the empire.", orderIndex: 4 },
  { id: "upsc-medieval-history-maratha-empire-q06", topicId: "upsc-medieval-history-maratha-empire", text: "The Peshwa who greatly expanded Maratha power across India was:", optionA: "Baji Rao I", optionB: "Balaji Baji Rao", optionC: "Madhav Rao II", optionD: "Narayan Rao", correctOption: "A", explanation: "Baji Rao I (r. 1720–40) expanded Maratha influence deep into north India.", orderIndex: 5 },
  { id: "upsc-medieval-history-maratha-empire-q07", topicId: "upsc-medieval-history-maratha-empire", text: "In the Maratha confederacy, the Scindia family was based at:", optionA: "Gwalior", optionB: "Indore", optionC: "Baroda", optionD: "Nagpur", correctOption: "A", explanation: "The Scindias ruled from Gwalior; Holkars from Indore, Gaekwads from Baroda, Bhonsles from Nagpur.", orderIndex: 6 },
  { id: "upsc-medieval-history-maratha-empire-q08", topicId: "upsc-medieval-history-maratha-empire", text: "The Third Battle of Panipat (1761) was fought between the Marathas and:", optionA: "Ahmad Shah Abdali (Durrani)", optionB: "The British", optionC: "The Mughals", optionD: "The Portuguese", correctOption: "A", explanation: "The Marathas suffered a heavy defeat by Ahmad Shah Abdali at Panipat in 1761.", orderIndex: 7 },
  { id: "upsc-medieval-history-maratha-empire-q09", topicId: "upsc-medieval-history-maratha-empire", text: "Shivaji's guerrilla warfare tactics were known as:", optionA: "Ganimi kava", optionB: "Blitzkrieg", optionC: "Chakravyuha", optionD: "Fabian strategy", correctOption: "A", explanation: "Shivaji perfected 'ganimi kava', hit-and-run guerrilla warfare suited to the hills.", orderIndex: 8 },
  { id: "upsc-medieval-history-maratha-empire-q10", topicId: "upsc-medieval-history-maratha-empire", text: "The Maratha Empire finally ended after the:", optionA: "Third Anglo-Maratha War (1818)", optionB: "Battle of Plassey", optionC: "First Anglo-Sikh War", optionD: "Revolt of 1857", correctOption: "A", explanation: "The Third Anglo-Maratha War (1817–18) ended Maratha power and the Peshwa's rule.", orderIndex: 9 },
  { id: "upsc-medieval-history-maratha-empire-q11", topicId: "upsc-medieval-history-maratha-empire", text: "The first Peshwa to make the office powerful and hereditary was:", optionA: "Balaji Vishwanath", optionB: "Baji Rao II", optionC: "Nana Saheb", optionD: "Raghunath Rao", correctOption: "A", explanation: "Balaji Vishwanath consolidated the Peshwa office under Chhatrapati Shahu.", orderIndex: 10 },
  { id: "upsc-medieval-history-maratha-empire-q12", topicId: "upsc-medieval-history-maratha-empire", text: "Shivaji escaped from the captivity of which Mughal emperor at Agra in 1666?", optionA: "Aurangzeb", optionB: "Akbar", optionC: "Jahangir", optionD: "Shah Jahan", correctOption: "A", explanation: "Shivaji famously escaped from Aurangzeb's court at Agra in 1666.", orderIndex: 11 },

  // ── Modern History: Advent of Europeans & British Conquest ──
  { id: "upsc-modern-history-advent-of-europeans-q01", topicId: "upsc-modern-history-advent-of-europeans", text: "The sea route to India via the Cape of Good Hope was discovered in 1498 by:", optionA: "Vasco da Gama", optionB: "Christopher Columbus", optionC: "Ferdinand Magellan", optionD: "Bartolomeu Dias", correctOption: "A", explanation: "Vasco da Gama, a Portuguese explorer, reached Calicut in 1498.", orderIndex: 0 },
  { id: "upsc-modern-history-advent-of-europeans-q02", topicId: "upsc-modern-history-advent-of-europeans", text: "The English East India Company was chartered by Queen Elizabeth I in:", optionA: "1600", optionB: "1757", optionC: "1526", optionD: "1858", correctOption: "A", explanation: "The English East India Company received its royal charter in 1600.", orderIndex: 1 },
  { id: "upsc-modern-history-advent-of-europeans-q03", topicId: "upsc-modern-history-advent-of-europeans", text: "The Battle of Plassey (1757) was won for the British by:", optionA: "Robert Clive", optionB: "Warren Hastings", optionC: "Lord Cornwallis", optionD: "Lord Dalhousie", correctOption: "A", explanation: "Robert Clive defeated Siraj-ud-Daulah at Plassey, aided by Mir Jafar's treachery.", orderIndex: 2 },
  { id: "upsc-modern-history-advent-of-europeans-q04", topicId: "upsc-modern-history-advent-of-europeans", text: "The Nawab of Bengal defeated at the Battle of Plassey was:", optionA: "Siraj-ud-Daulah", optionB: "Mir Jafar", optionC: "Mir Qasim", optionD: "Alivardi Khan", correctOption: "A", explanation: "Siraj-ud-Daulah was defeated at Plassey; Mir Jafar was installed as a puppet Nawab.", orderIndex: 3 },
  { id: "upsc-modern-history-advent-of-europeans-q05", topicId: "upsc-modern-history-advent-of-europeans", text: "The Battle of Buxar (1764) established British supremacy over the combined forces of Mir Qasim, the Nawab of Awadh, and:", optionA: "Mughal emperor Shah Alam II", optionB: "The Marathas", optionC: "Tipu Sultan", optionD: "The Nizam", correctOption: "A", explanation: "At Buxar the British defeated Mir Qasim, Shuja-ud-Daulah, and Shah Alam II together.", orderIndex: 4 },
  { id: "upsc-modern-history-advent-of-europeans-q06", topicId: "upsc-modern-history-advent-of-europeans", text: "The Diwani of Bengal, Bihar, and Odisha was granted to the Company by the Treaty of:", optionA: "Allahabad (1765)", optionB: "Bassein", optionC: "Salbai", optionD: "Seringapatam", correctOption: "A", explanation: "The 1765 Treaty of Allahabad gave the Company Diwani (revenue) rights over Bengal, Bihar, Odisha.", orderIndex: 5 },
  { id: "upsc-modern-history-advent-of-europeans-q07", topicId: "upsc-modern-history-advent-of-europeans", text: "The decisive battle by which the English ended French ambitions in India was the Battle of:", optionA: "Wandiwash (1760)", optionB: "Plassey", optionC: "Panipat", optionD: "Buxar", correctOption: "A", explanation: "At Wandiwash (1760) the English defeated the French, ending the Carnatic wars in their favour.", orderIndex: 6 },
  { id: "upsc-modern-history-advent-of-europeans-q08", topicId: "upsc-modern-history-advent-of-europeans", text: "The 'Subsidiary Alliance' system was introduced by:", optionA: "Lord Wellesley", optionB: "Lord Dalhousie", optionC: "Warren Hastings", optionD: "Lord Ripon", correctOption: "A", explanation: "Lord Wellesley used the Subsidiary Alliance to bring Indian states under British control.", orderIndex: 7 },
  { id: "upsc-modern-history-advent-of-europeans-q09", topicId: "upsc-modern-history-advent-of-europeans", text: "The 'Doctrine of Lapse' to annex states without a natural heir was applied by:", optionA: "Lord Dalhousie", optionB: "Lord Canning", optionC: "Lord Curzon", optionD: "Lord Minto", correctOption: "A", explanation: "Lord Dalhousie annexed states like Satara, Jhansi, and Nagpur under the Doctrine of Lapse.", orderIndex: 8 },
  { id: "upsc-modern-history-advent-of-europeans-q10", topicId: "upsc-modern-history-advent-of-europeans", text: "The Portuguese governor who established Goa as their Indian base was:", optionA: "Alfonso de Albuquerque", optionB: "Francisco de Almeida", optionC: "Vasco da Gama", optionD: "Pedro Cabral", correctOption: "A", explanation: "Alfonso de Albuquerque captured Goa in 1510, making it the Portuguese headquarters.", orderIndex: 9 },
  { id: "upsc-modern-history-advent-of-europeans-q11", topicId: "upsc-modern-history-advent-of-europeans", text: "Which European power was the last to arrive but first to establish, and last to leave, territory in India?", optionA: "The Portuguese", optionB: "The Dutch", optionC: "The Danes", optionD: "The French", correctOption: "A", explanation: "The Portuguese came first (1498) and left last (Goa liberated in 1961).", orderIndex: 10 },
  { id: "upsc-modern-history-advent-of-europeans-q12", topicId: "upsc-modern-history-advent-of-europeans", text: "The dual system of government in Bengal (Company revenue, Nawab administration) was established by:", optionA: "Robert Clive", optionB: "Warren Hastings", optionC: "Lord Cornwallis", optionD: "Lord Wellesley", correctOption: "A", explanation: "Clive's 'dual government' (1765) split power between Company and Nawab; Hastings ended it.", orderIndex: 11 },

  // ── Modern History: Economic Impact of British Rule ──
  { id: "upsc-modern-history-economic-impact-of-british-rule-q01", topicId: "upsc-modern-history-economic-impact-of-british-rule", text: "The 'Drain of Wealth' theory was most notably expounded by:", optionA: "Dadabhai Naoroji", optionB: "Bal Gangadhar Tilak", optionC: "M. K. Gandhi", optionD: "Subhas Bose", correctOption: "A", explanation: "Dadabhai Naoroji articulated the drain theory in 'Poverty and Un-British Rule in India'.", orderIndex: 0 },
  { id: "upsc-modern-history-economic-impact-of-british-rule-q02", topicId: "upsc-modern-history-economic-impact-of-british-rule", text: "The Permanent Settlement of 1793 in Bengal was introduced by:", optionA: "Lord Cornwallis", optionB: "Thomas Munro", optionC: "Warren Hastings", optionD: "Lord Ripon", correctOption: "A", explanation: "Lord Cornwallis introduced the Permanent Settlement, fixing revenue with zamindars.", orderIndex: 1 },
  { id: "upsc-modern-history-economic-impact-of-british-rule-q03", topicId: "upsc-modern-history-economic-impact-of-british-rule", text: "The Ryotwari system, settling revenue directly with cultivators, was associated with:", optionA: "Thomas Munro", optionB: "Cornwallis", optionC: "Warren Hastings", optionD: "Lord Wellesley", correctOption: "A", explanation: "Thomas Munro (and Reed) developed the Ryotwari system in Madras and Bombay.", orderIndex: 2 },
  { id: "upsc-modern-history-economic-impact-of-british-rule-q04", topicId: "upsc-modern-history-economic-impact-of-british-rule", text: "The decline of Indian handicrafts under British trade policy is called:", optionA: "Deindustrialisation", optionB: "Commercialisation", optionC: "Urbanisation", optionD: "Monetisation", correctOption: "A", explanation: "One-way free trade ruined Indian handicrafts, a process termed deindustrialisation.", orderIndex: 3 },
  { id: "upsc-modern-history-economic-impact-of-british-rule-q05", topicId: "upsc-modern-history-economic-impact-of-british-rule", text: "The land-revenue system prevalent in most of northern India was the:", optionA: "Mahalwari system", optionB: "Ryotwari system", optionC: "Permanent Settlement", optionD: "Jagirdari system", correctOption: "A", explanation: "The Mahalwari system settled revenue with the village (mahal) in north India.", orderIndex: 4 },
  { id: "upsc-modern-history-economic-impact-of-british-rule-q06", topicId: "upsc-modern-history-economic-impact-of-british-rule", text: "The famous book 'Poverty and Un-British Rule in India' was written by:", optionA: "Dadabhai Naoroji", optionB: "R. C. Dutt", optionC: "Gopal Krishna Gokhale", optionD: "M. G. Ranade", correctOption: "A", explanation: "Dadabhai Naoroji, the 'Grand Old Man of India', wrote this on the economic drain.", orderIndex: 5 },
  { id: "upsc-modern-history-economic-impact-of-british-rule-q07", topicId: "upsc-modern-history-economic-impact-of-british-rule", text: "The first railway line in India (1853) ran between:", optionA: "Bombay and Thane", optionB: "Calcutta and Delhi", optionC: "Madras and Bangalore", optionD: "Howrah and Raniganj", correctOption: "A", explanation: "India's first passenger railway ran from Bombay to Thane in 1853.", orderIndex: 6 },
  { id: "upsc-modern-history-economic-impact-of-british-rule-q08", topicId: "upsc-modern-history-economic-impact-of-british-rule", text: "The forced cultivation that led to the Indigo Revolt (1859) affected peasants in:", optionA: "Bengal", optionB: "Punjab", optionC: "Madras", optionD: "Gujarat", correctOption: "A", explanation: "The Indigo Revolt of 1859–60 protested oppressive forced indigo cultivation in Bengal.", orderIndex: 7 },
  { id: "upsc-modern-history-economic-impact-of-british-rule-q09", topicId: "upsc-modern-history-economic-impact-of-british-rule", text: "Under British rule, India was primarily converted into a:", optionA: "Supplier of raw materials and a market for finished goods", optionB: "Leading industrial exporter", optionC: "Self-sufficient closed economy", optionD: "Global financial hub", correctOption: "A", explanation: "Colonial policy made India export raw materials and import British manufactures.", orderIndex: 8 },
  { id: "upsc-modern-history-economic-impact-of-british-rule-q10", topicId: "upsc-modern-history-economic-impact-of-british-rule", text: "'Home Charges' in the drain theory referred to:", optionA: "Payments made in Britain out of Indian revenues", optionB: "Household taxes in India", optionC: "Charges for postal services", optionD: "Municipal taxes", correctOption: "A", explanation: "Home Charges were expenses (pensions, interest, salaries) paid in Britain from Indian revenue.", orderIndex: 9 },
  { id: "upsc-modern-history-economic-impact-of-british-rule-q11", topicId: "upsc-modern-history-economic-impact-of-british-rule", text: "The shift of Indian agriculture to cash crops for the market is called:", optionA: "Commercialisation of agriculture", optionB: "Collectivisation", optionC: "Land reform", optionD: "Consolidation", correctOption: "A", explanation: "The British encouraged commercialisation, pushing farmers toward cash crops like cotton and indigo.", orderIndex: 10 },
  { id: "upsc-modern-history-economic-impact-of-british-rule-q12", topicId: "upsc-modern-history-economic-impact-of-british-rule", text: "Recurrent famines under British rule were worsened by:", optionA: "High revenue demand and export of food grains", optionB: "Overproduction of food", optionC: "Excessive irrigation", optionD: "Land redistribution", correctOption: "A", explanation: "Heavy revenue extraction and grain exports intensified famine mortality.", orderIndex: 11 },

  // ── Modern History: Governor-Generals & British Administration ──
  { id: "upsc-modern-history-governor-generals-and-administration-q01", topicId: "upsc-modern-history-governor-generals-and-administration", text: "The first Governor-General of Bengal was:", optionA: "Warren Hastings", optionB: "Lord Cornwallis", optionC: "Robert Clive", optionD: "Lord Wellesley", correctOption: "A", explanation: "Warren Hastings became the first Governor-General of Bengal in 1774.", orderIndex: 0 },
  { id: "upsc-modern-history-governor-generals-and-administration-q02", topicId: "upsc-modern-history-governor-generals-and-administration", text: "Sati was legally abolished in 1829 by:", optionA: "Lord William Bentinck", optionB: "Lord Dalhousie", optionC: "Lord Curzon", optionD: "Lord Ripon", correctOption: "A", explanation: "Lord William Bentinck, with Raja Ram Mohan Roy's support, abolished Sati in 1829.", orderIndex: 1 },
  { id: "upsc-modern-history-governor-generals-and-administration-q03", topicId: "upsc-modern-history-governor-generals-and-administration", text: "Lord Cornwallis is often called the 'father of' which service?", optionA: "The civil service in India", optionB: "The Indian Army", optionC: "The Indian Railways", optionD: "The police force", correctOption: "A", explanation: "Cornwallis reformed and organised the Company's civil service, earning that title.", orderIndex: 2 },
  { id: "upsc-modern-history-governor-generals-and-administration-q04", topicId: "upsc-modern-history-governor-generals-and-administration", text: "Railways, telegraph, and the modern Post Office in India were introduced under:", optionA: "Lord Dalhousie", optionB: "Warren Hastings", optionC: "Lord Ripon", optionD: "Lord Minto", correctOption: "A", explanation: "Lord Dalhousie introduced railways, the telegraph, and a modern postal system.", orderIndex: 3 },
  { id: "upsc-modern-history-governor-generals-and-administration-q05", topicId: "upsc-modern-history-governor-generals-and-administration", text: "After 1858, the Governor-General was also designated as the:", optionA: "Viceroy", optionB: "Prime Minister", optionC: "President", optionD: "Secretary of State", correctOption: "A", explanation: "The Government of India Act 1858 made the Governor-General also the Viceroy (Crown's representative).", orderIndex: 4 },
  { id: "upsc-modern-history-governor-generals-and-administration-q06", topicId: "upsc-modern-history-governor-generals-and-administration", text: "The first Viceroy of India was:", optionA: "Lord Canning", optionB: "Lord Curzon", optionC: "Lord Ripon", optionD: "Lord Mayo", correctOption: "A", explanation: "Lord Canning, in office during the 1857 revolt, became the first Viceroy in 1858.", orderIndex: 5 },
  { id: "upsc-modern-history-governor-generals-and-administration-q07", topicId: "upsc-modern-history-governor-generals-and-administration", text: "The Partition of Bengal in 1905 was carried out by:", optionA: "Lord Curzon", optionB: "Lord Minto", optionC: "Lord Hardinge", optionD: "Lord Ripon", correctOption: "A", explanation: "Lord Curzon partitioned Bengal in 1905, sparking the Swadeshi movement.", orderIndex: 6 },
  { id: "upsc-modern-history-governor-generals-and-administration-q08", topicId: "upsc-modern-history-governor-generals-and-administration", text: "Separate electorates for Muslims were introduced by the Morley-Minto Reforms of:", optionA: "1909", optionB: "1919", optionC: "1935", optionD: "1892", correctOption: "A", explanation: "The Indian Councils Act 1909 (Morley-Minto) introduced separate communal electorates.", orderIndex: 7 },
  { id: "upsc-modern-history-governor-generals-and-administration-q09", topicId: "upsc-modern-history-governor-generals-and-administration", text: "Lord Ripon is remembered for the Resolution on:", optionA: "Local self-government (1882)", optionB: "Partition of Bengal", optionC: "The Doctrine of Lapse", optionD: "The Rowlatt Act", correctOption: "A", explanation: "Lord Ripon, the 'father of local self-government', passed the 1882 resolution.", orderIndex: 8 },
  { id: "upsc-modern-history-governor-generals-and-administration-q10", topicId: "upsc-modern-history-governor-generals-and-administration", text: "The Jallianwala Bagh massacre (1919) occurred during the viceroyalty of:", optionA: "Lord Chelmsford", optionB: "Lord Reading", optionC: "Lord Irwin", optionD: "Lord Curzon", correctOption: "A", explanation: "The 1919 massacre took place under Viceroy Lord Chelmsford (General Dyer ordered firing).", orderIndex: 9 },
  { id: "upsc-modern-history-governor-generals-and-administration-q11", topicId: "upsc-modern-history-governor-generals-and-administration", text: "The Government of India Act 1858 transferred power from the Company to the:", optionA: "British Crown", optionB: "Indian National Congress", optionC: "Provincial legislatures", optionD: "The Mughal emperor", correctOption: "A", explanation: "The 1858 Act ended Company rule and vested Indian governance in the British Crown.", orderIndex: 10 },
  { id: "upsc-modern-history-governor-generals-and-administration-q12", topicId: "upsc-modern-history-governor-generals-and-administration", text: "The last Viceroy of India, who oversaw the transfer of power in 1947, was:", optionA: "Lord Mountbatten", optionB: "Lord Wavell", optionC: "Lord Linlithgow", optionD: "Lord Willingdon", correctOption: "A", explanation: "Lord Mountbatten was the last Viceroy and presided over Partition and independence.", orderIndex: 11 },

  // ── Modern History: Towards Independence & Partition ──
  { id: "upsc-modern-history-towards-independence-and-partition-q01", topicId: "upsc-modern-history-towards-independence-and-partition", text: "The Quit India Movement was launched in:", optionA: "1942", optionB: "1930", optionC: "1919", optionD: "1946", correctOption: "A", explanation: "Gandhi launched the Quit India Movement in August 1942 with the call 'Do or Die'.", orderIndex: 0 },
  { id: "upsc-modern-history-towards-independence-and-partition-q02", topicId: "upsc-modern-history-towards-independence-and-partition", text: "Gandhi's famous slogan during the Quit India Movement was:", optionA: "Do or Die", optionB: "Inquilab Zindabad", optionC: "Swaraj is my birthright", optionD: "Jai Hind", correctOption: "A", explanation: "'Do or Die' (Karo ya Maro) was Gandhi's call during the 1942 movement.", orderIndex: 1 },
  { id: "upsc-modern-history-towards-independence-and-partition-q03", topicId: "upsc-modern-history-towards-independence-and-partition", text: "The Cripps Mission (1942) offer was famously described by Gandhi as:", optionA: "A post-dated cheque", optionB: "A magna carta", optionC: "A blank cheque", optionD: "A fair deal", correctOption: "A", explanation: "Gandhi called the Cripps offer 'a post-dated cheque on a crashing bank'.", orderIndex: 2 },
  { id: "upsc-modern-history-towards-independence-and-partition-q04", topicId: "upsc-modern-history-towards-independence-and-partition", text: "The Indian National Army (INA) was reorganised and led by:", optionA: "Subhas Chandra Bose", optionB: "Bhagat Singh", optionC: "Chandra Shekhar Azad", optionD: "Jawaharlal Nehru", correctOption: "A", explanation: "Subhas Chandra Bose revitalised the INA with the slogan 'Give me blood, I will give you freedom'.", orderIndex: 3 },
  { id: "upsc-modern-history-towards-independence-and-partition-q05", topicId: "upsc-modern-history-towards-independence-and-partition", text: "The Muslim League observed 'Direct Action Day' on 16 August 1946 to demand:", optionA: "Pakistan", optionB: "Dominion status", optionC: "A united India", optionD: "Separate electorates only", correctOption: "A", explanation: "Direct Action Day pressed the demand for Pakistan and triggered communal riots in Calcutta.", orderIndex: 4 },
  { id: "upsc-modern-history-towards-independence-and-partition-q06", topicId: "upsc-modern-history-towards-independence-and-partition", text: "The Cabinet Mission came to India in:", optionA: "1946", optionB: "1942", optionC: "1935", optionD: "1947", correctOption: "A", explanation: "The Cabinet Mission (1946) proposed a federal plan and framework for a Constituent Assembly.", orderIndex: 5 },
  { id: "upsc-modern-history-towards-independence-and-partition-q07", topicId: "upsc-modern-history-towards-independence-and-partition", text: "The plan that finally accepted the partition of India was announced on 3 June 1947 by:", optionA: "Lord Mountbatten", optionB: "Lord Wavell", optionC: "Stafford Cripps", optionD: "Clement Attlee", correctOption: "A", explanation: "The Mountbatten Plan (3 June 1947) set out the terms for partition and transfer of power.", orderIndex: 6 },
  { id: "upsc-modern-history-towards-independence-and-partition-q08", topicId: "upsc-modern-history-towards-independence-and-partition", text: "The boundary line dividing India and Pakistan was drawn by:", optionA: "Cyril Radcliffe", optionB: "Louis Mountbatten", optionC: "Cyril Jackson", optionD: "Stafford Cripps", correctOption: "A", explanation: "The Radcliffe Line, drawn by Sir Cyril Radcliffe, partitioned Punjab and Bengal.", orderIndex: 7 },
  { id: "upsc-modern-history-towards-independence-and-partition-q09", topicId: "upsc-modern-history-towards-independence-and-partition", text: "India became independent on:", optionA: "15 August 1947", optionB: "26 January 1950", optionC: "26 January 1930", optionD: "2 October 1947", correctOption: "A", explanation: "India gained independence on 15 August 1947 under the Indian Independence Act.", orderIndex: 8 },
  { id: "upsc-modern-history-towards-independence-and-partition-q10", topicId: "upsc-modern-history-towards-independence-and-partition", text: "The integration of over 560 princely states into India was led chiefly by:", optionA: "Sardar Vallabhbhai Patel", optionB: "Jawaharlal Nehru", optionC: "Rajendra Prasad", optionD: "Maulana Azad", correctOption: "A", explanation: "Sardar Patel, with V. P. Menon, integrated the princely states into the Indian Union.", orderIndex: 9 },
  { id: "upsc-modern-history-towards-independence-and-partition-q11", topicId: "upsc-modern-history-towards-independence-and-partition", text: "The 1946 mutiny that shook British confidence was the:", optionA: "Royal Indian Navy (RIN) mutiny", optionB: "Barrackpore mutiny", optionC: "Vellore mutiny", optionD: "Meerut mutiny", correctOption: "A", explanation: "The 1946 RIN naval ratings' mutiny in Bombay signalled crumbling British authority.", orderIndex: 10 },
  { id: "upsc-modern-history-towards-independence-and-partition-q12", topicId: "upsc-modern-history-towards-independence-and-partition", text: "The legislation that created the two dominions of India and Pakistan was the:", optionA: "Indian Independence Act 1947", optionB: "Government of India Act 1935", optionC: "Regulating Act 1773", optionD: "Rowlatt Act 1919", correctOption: "A", explanation: "The Indian Independence Act 1947 partitioned British India into India and Pakistan.", orderIndex: 11 }
];
