// UPSC depth expansion — Current Affairs, International Relations, Governance,
// and Internal Security (pass 5). Rounds out the remaining thin subjects with
// two high-yield chapters each, every topic with a study note and 12-question drill.
import type { AuthoredMaterial } from "./builder";
import type { Question, Topic } from "@jyotir/core";

export const exp5Topics: Topic[] = [
  // Current Affairs (existing max orderIndex = 2)
  { id: "upsc-current-affairs-reports-and-committees", subjectId: "upsc-current-affairs", name: "Reports & Committees in the News", slug: "reports-and-committees", orderIndex: 3 },
  { id: "upsc-current-affairs-global-summits-and-events", subjectId: "upsc-current-affairs", name: "Global Summits & Events", slug: "global-summits-and-events", orderIndex: 4 },
  // International Relations (existing max orderIndex = 3)
  { id: "upsc-international-relations-india-and-major-powers", subjectId: "upsc-international-relations", name: "India & Major Powers", slug: "india-and-major-powers", orderIndex: 4 },
  { id: "upsc-international-relations-border-and-maritime-security", subjectId: "upsc-international-relations", name: "Border Disputes & Maritime Security", slug: "border-and-maritime-security", orderIndex: 5 },
  // Governance & Social Justice (existing max orderIndex = 3)
  { id: "upsc-governance-citizen-centric-governance", subjectId: "upsc-governance", name: "Citizen-Centric Governance & Service Delivery", slug: "citizen-centric-governance", orderIndex: 4 },
  { id: "upsc-governance-civil-services-and-non-state-actors", subjectId: "upsc-governance", name: "Civil Services & Non-State Actors", slug: "civil-services-and-non-state-actors", orderIndex: 5 },
  // Internal Security & Disaster Management (existing max orderIndex = 3)
  { id: "upsc-internal-security-security-forces-and-agencies", subjectId: "upsc-internal-security", name: "Security Forces & Agencies", slug: "security-forces-and-agencies", orderIndex: 4 },
  { id: "upsc-internal-security-extremism-and-terror-financing", subjectId: "upsc-internal-security", name: "Extremism, Terror Financing & Social Media", slug: "extremism-and-terror-financing", orderIndex: 5 }
];

export const exp5Materials: AuthoredMaterial[] = [
  { id: "upsc-current-affairs-reports-and-committees-m01", topicId: "upsc-current-affairs-reports-and-committees", title: "Reports & Committees in the News", content: `UPSC frequently asks 'who publishes what'. Key **flagship reports**: the **Economic Survey** (by the Chief Economic Adviser, Ministry of Finance, tabled before the Budget); the **Human Development Report** (**UNDP**, with the HDI); the **World Development Report** and **Ease of Doing Business** (**World Bank**); the **World Economic Outlook** and **Global Financial Stability Report** (**IMF**); the **Global Competitiveness** and **Global Gender Gap** reports (**World Economic Forum**); the **State of the World's Children** (**UNICEF**); and the **Emissions Gap Report** (**UNEP**).

**Indices** and who releases them: **Global Hunger Index** (Concern Worldwide & Welthungerhilfe), **Corruption Perceptions Index** (**Transparency International**), **Press Freedom Index** (Reporters Without Borders), **World Happiness Report** (SDSN), **Global Innovation Index** (WIPO), and the **Human Freedom Index**. India publishes its own — **NITI Aayog's SDG India Index, Aspirational Districts** rankings, and the multidimensional poverty index. Important **committees**: the many finance and reform panels (e.g., on GST, banking) — always note the chair and the domain.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "upsc-current-affairs-global-summits-and-events-m01", topicId: "upsc-current-affairs-global-summits-and-events", title: "Global Summits & Events", content: `Major **multilateral summits**: the **G20** (India held the presidency and hosted the 2023 New Delhi Summit; its motto was 'Vasudhaiva Kutumbakam — One Earth, One Family, One Future'), the **G7**, **BRICS** (Brazil, Russia, India, China, South Africa — expanded with new members), **SCO** (Shanghai Cooperation Organisation), and **QUAD** (India, US, Japan, Australia). Regional bodies include **ASEAN**, **SAARC**, **BIMSTEC**, and the **African Union** (a new G20 member).

**Climate summits**: the annual **UNFCCC Conference of the Parties (COP)** — COP21 gave the **Paris Agreement (2015)**; COP26 (Glasgow) saw India pledge **net-zero by 2070** and the 'Panchamrit' goals; COP28 (Dubai) agreed to 'transition away' from fossil fuels. Global sporting events (**Olympics, Commonwealth and Asian Games, FIFA World Cup, Cricket World Cup**) and honours (the **Nobel Prizes**, and India's civilian awards — the **Bharat Ratna** and **Padma awards**) are regular exam material. Note the host, year, and outcome of each event.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "upsc-international-relations-india-and-major-powers-m01", topicId: "upsc-international-relations-india-and-major-powers", title: "India & Major Powers", content: `**India–USA**: relations deepened from the 2008 civil nuclear deal into a 'Comprehensive Global Strategic Partnership' spanning defence (foundational agreements **LEMOA, COMCASA, BECA**), technology (**iCET**), and the **QUAD**. **India–Russia**: a long, defence-heavy 'Special and Privileged Strategic Partnership' (the **S-400** deal, the BrahMos co-development, energy); India balances this amid the Ukraine conflict through **strategic autonomy**.

**India–China**: the world's two most populous nations share a disputed border (the **Line of Actual Control**), a large trade deficit, and rivalry (the 2020 **Galwan** clash), managed through mechanisms like the **BRICS/SCO** even as China's Belt and Road (**CPEC through PoK**) strains ties. **India–EU/UK/France/Japan**: growing trade and technology partnerships (an India–EU trade deal under negotiation; Japan's role in infrastructure and the **Indo-Pacific**). India's diplomacy rests on **non-alignment's successor — strategic autonomy and multi-alignment**, engaging all poles while avoiding binding blocs.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "upsc-international-relations-border-and-maritime-security-m01", topicId: "upsc-international-relations-border-and-maritime-security", title: "Border Disputes & Maritime Security", content: `India's land borders are managed along defined lines. The **Line of Control (LoC)** divides Indian- and Pakistan-administered Kashmir (from the 1972 **Simla Agreement**); the **Line of Actual Control (LAC)** is the disputed, undemarcated boundary with China (flashpoints at **Aksai Chin, Doklam, Galwan, Tawang**). The **Radcliffe Line** (with Pakistan) and the **McMahon Line** (with China, in Arunachal, which China disputes) are colonial-era boundaries. The **Durand Line** separates Afghanistan and Pakistan.

**Maritime security**: India sits astride key **Indian Ocean sea lanes**, guarding **choke points** (the Straits of Hormuz, Malacca, Bab-el-Mandeb) vital for energy trade. India's vision **SAGAR (Security and Growth for All in the Region)** and its role as a 'net security provider' involve anti-piracy patrols, disaster relief (HADR), and partnerships (the **IONS**, the **Colombo Security Conclave**, the QUAD's maritime initiatives). India's **Exclusive Economic Zone (EEZ)** extends 200 nautical miles under **UNCLOS**. The **Indian Coast Guard** and Navy secure the coastline and island territories (Andaman & Nicobar, Lakshadweep).`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "upsc-governance-citizen-centric-governance-m01", topicId: "upsc-governance-citizen-centric-governance", title: "Citizen-Centric Governance & Service Delivery", content: `Good governance aims to make administration **citizen-centric** — responsive, accountable, and accessible. **Citizens' Charters** publicly declare an agency's service standards and timelines. The **Sevottam** model assesses public-service delivery. **e-Governance** (envisioned as SMART governance — Simple, Moral, Accountable, Responsive, Transparent) moves through the stages G2C, G2B, G2G, and G2E, with initiatives like **Common Service Centres**, **DigiLocker**, **UMANG**, and **Direct Benefit Transfer (DBT)** to cut leakages.

Accountability tools include the **Right to Information Act (2005)**, **social audits** (pioneered under MGNREGA), the **Lokpal and Lokayuktas**, and grievance-redressal portals like **CPGRAMS**. The **2nd Administrative Reforms Commission (ARC)** recommended wide-ranging reforms for citizen-centric administration. The **Right to Public Services** laws in many states guarantee time-bound delivery. The goals — **transparency, participation, and the rule of law** — align with the idea of 'minimum government, maximum governance' and reducing the citizen–state distance.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "upsc-governance-civil-services-and-non-state-actors-m01", topicId: "upsc-governance-civil-services-and-non-state-actors", title: "Civil Services & Non-State Actors", content: `The **civil services** are the permanent executive that implements policy and ensures continuity. The **All India Services** — **IAS, IPS, and IFoS** — serve both Union and States (Article 312). Civil servants are expected to be politically **neutral, anonymous, and committed to the public interest**, providing 'frank and fearless' advice while ultimately being accountable to elected ministers. Debates cover **generalist vs specialist**, lateral entry, and reforms for a more responsive bureaucracy.

**Non-state actors** enrich governance and development. **NGOs / civil society organisations** deliver services, advocate, and hold the state to account; **Self-Help Groups (SHGs)** (e.g., under the DAY-NRLM, and Kudumbashree in Kerala) drive women's financial inclusion and micro-credit. **Cooperatives** (Amul's dairy model), **pressure and interest groups**, **community-based organisations**, and the media (the 'fourth estate') all shape policy. **Public–private partnerships (PPPs)** and **corporate social responsibility (CSR)** (mandated for large firms under the Companies Act) mobilise private resources for public goals. Their strengths (reach, innovation, participation) are balanced against concerns over accountability and funding transparency (regulated by the **FCRA**).`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "upsc-internal-security-security-forces-and-agencies-m01", topicId: "upsc-internal-security-security-forces-and-agencies", title: "Security Forces & Agencies", content: `India's security architecture spans the **Armed Forces** (Army, Navy, Air Force under the Ministry of Defence, now led by a **Chief of Defence Staff** heading the Department of Military Affairs) and internal-security forces under the **Ministry of Home Affairs**. The **Central Armed Police Forces (CAPFs)** include the **CRPF** (largest; internal security, anti-Naxal), **BSF** (India–Pakistan/Bangladesh borders), **ITBP** (India–China border), **SSB** (Nepal/Bhutan borders), **CISF** (industrial and airport security), and **Assam Rifles** (north-east). Elite units include the **NSG** ('Black Cats', counter-terror) and Special Frontier Force.

**Intelligence and investigation**: the **Intelligence Bureau (IB)** handles internal intelligence; the **Research and Analysis Wing (RAW)** handles external intelligence; the **National Investigation Agency (NIA)** investigates terror offences; the **Enforcement Directorate (ED)** handles economic offences (PMLA/FEMA); and the **CBI** handles major crimes and corruption. Coordination bodies include the **National Security Council (NSC)** (advised by the National Security Adviser), the **Multi-Agency Centre (MAC)**, and **NATGRID**. State police remain the first responders, as 'police' and 'public order' are State subjects under the Seventh Schedule.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "upsc-internal-security-extremism-and-terror-financing-m01", topicId: "upsc-internal-security-extremism-and-terror-financing", title: "Extremism, Terror Financing & Social Media", content: `India faces multiple security threats: **cross-border terrorism**, **Left-Wing Extremism (Naxalism/Maoism)** in the 'Red Corridor', **insurgency in the north-east**, and separatism. Counter-strategies blend security operations with development (the **SAMADHAN** doctrine for LWE) and the legal framework of the **Unlawful Activities (Prevention) Act (UAPA)** and the **National Investigation Agency**.

**Terror financing** exploits money laundering, **hawala**, fake currency, and the misuse of non-profits; it is countered by the **Prevention of Money Laundering Act (PMLA)** and the global **Financial Action Task Force (FATF)**, whose 'grey list' pressures states to act. **Radicalisation** and recruitment increasingly use the **internet and social media** — encrypted messaging, propaganda, and 'lone-wolf' incitement — raising challenges of **online radicalisation, fake news, and cyber-enabled terror**. India responds through de-radicalisation programmes, intelligence monitoring, IT rules on intermediaries, and international cooperation. The overarching aim is to cut off funds, disrupt networks, and counter the ideological narrative while safeguarding civil liberties.`, estimatedReadTime: 2, orderIndex: 0 }
];

export const exp5Questions: Question[] = [
  // ── Current Affairs: Reports & Committees ──
  { id: "upsc-current-affairs-reports-and-committees-q01", topicId: "upsc-current-affairs-reports-and-committees", text: "The Human Development Report and the HDI are published by:", optionA: "UNDP", optionB: "World Bank", optionC: "IMF", optionD: "WEF", correctOption: "A", explanation: "The UN Development Programme (UNDP) publishes the Human Development Report and HDI.", orderIndex: 0 },
  { id: "upsc-current-affairs-reports-and-committees-q02", topicId: "upsc-current-affairs-reports-and-committees", text: "The Economic Survey of India is prepared by the:", optionA: "Chief Economic Adviser (Ministry of Finance)", optionB: "RBI Governor", optionC: "NITI Aayog CEO", optionD: "Comptroller and Auditor General", correctOption: "A", explanation: "The Economic Survey is prepared under the Chief Economic Adviser and tabled before the Budget.", orderIndex: 1 },
  { id: "upsc-current-affairs-reports-and-committees-q03", topicId: "upsc-current-affairs-reports-and-committees", text: "The Corruption Perceptions Index is released by:", optionA: "Transparency International", optionB: "The World Bank", optionC: "The IMF", optionD: "The UN", correctOption: "A", explanation: "Transparency International publishes the annual Corruption Perceptions Index.", orderIndex: 2 },
  { id: "upsc-current-affairs-reports-and-committees-q04", topicId: "upsc-current-affairs-reports-and-committees", text: "The Global Gender Gap Report is published by the:", optionA: "World Economic Forum", optionB: "UN Women", optionC: "World Bank", optionD: "ILO", correctOption: "A", explanation: "The World Economic Forum (WEF) publishes the Global Gender Gap Report.", orderIndex: 3 },
  { id: "upsc-current-affairs-reports-and-committees-q05", topicId: "upsc-current-affairs-reports-and-committees", text: "The World Economic Outlook is a flagship publication of the:", optionA: "IMF", optionB: "World Bank", optionC: "WTO", optionD: "OECD", correctOption: "A", explanation: "The International Monetary Fund (IMF) publishes the World Economic Outlook.", orderIndex: 4 },
  { id: "upsc-current-affairs-reports-and-committees-q06", topicId: "upsc-current-affairs-reports-and-committees", text: "The SDG India Index, tracking states on the Sustainable Development Goals, is released by:", optionA: "NITI Aayog", optionB: "the RBI", optionC: "the Election Commission", optionD: "the Finance Commission", correctOption: "A", explanation: "NITI Aayog publishes the SDG India Index ranking states and UTs.", orderIndex: 5 },
  { id: "upsc-current-affairs-reports-and-committees-q07", topicId: "upsc-current-affairs-reports-and-committees", text: "The Global Innovation Index is co-published by the:", optionA: "World Intellectual Property Organization (WIPO)", optionB: "World Bank", optionC: "IMF", optionD: "UNDP", correctOption: "A", explanation: "WIPO co-publishes the Global Innovation Index.", orderIndex: 6 },
  { id: "upsc-current-affairs-reports-and-committees-q08", topicId: "upsc-current-affairs-reports-and-committees", text: "The State of the World's Children report is published by:", optionA: "UNICEF", optionB: "WHO", optionC: "UNESCO", optionD: "UNHCR", correctOption: "A", explanation: "UNICEF publishes the annual State of the World's Children report.", orderIndex: 7 },
  { id: "upsc-current-affairs-reports-and-committees-q09", topicId: "upsc-current-affairs-reports-and-committees", text: "The Ease of Doing Business rankings were released by the:", optionA: "World Bank", optionB: "World Economic Forum", optionC: "IMF", optionD: "OECD", correctOption: "A", explanation: "The World Bank published the (now discontinued) Ease of Doing Business report.", orderIndex: 8 },
  { id: "upsc-current-affairs-reports-and-committees-q10", topicId: "upsc-current-affairs-reports-and-committees", text: "The Press Freedom Index is compiled by:", optionA: "Reporters Without Borders", optionB: "UNESCO", optionC: "Amnesty International", optionD: "the WEF", correctOption: "A", explanation: "Reporters Without Borders (RSF) publishes the World Press Freedom Index.", orderIndex: 9 },
  { id: "upsc-current-affairs-reports-and-committees-q11", topicId: "upsc-current-affairs-reports-and-committees", text: "NITI Aayog's programme to rapidly develop the most backward districts is the:", optionA: "Aspirational Districts Programme", optionB: "Smart Cities Mission", optionC: "AMRUT", optionD: "Digital India", correctOption: "A", explanation: "The Aspirational Districts Programme targets rapid improvement in India's most underdeveloped districts.", orderIndex: 10 },
  { id: "upsc-current-affairs-reports-and-committees-q12", topicId: "upsc-current-affairs-reports-and-committees", text: "The Emissions Gap Report is published by the:", optionA: "UN Environment Programme (UNEP)", optionB: "IPCC", optionC: "World Bank", optionD: "IEA", correctOption: "A", explanation: "UNEP publishes the annual Emissions Gap Report ahead of climate summits.", orderIndex: 11 },

  // ── Current Affairs: Global Summits & Events ──
  { id: "upsc-current-affairs-global-summits-and-events-q01", topicId: "upsc-current-affairs-global-summits-and-events", text: "India hosted the G20 Leaders' Summit in 2023 in:", optionA: "New Delhi", optionB: "Mumbai", optionC: "Bengaluru", optionD: "Hyderabad", correctOption: "A", explanation: "India's G20 presidency culminated in the September 2023 New Delhi Summit.", orderIndex: 0 },
  { id: "upsc-current-affairs-global-summits-and-events-q02", topicId: "upsc-current-affairs-global-summits-and-events", text: "The theme of India's G20 presidency was:", optionA: "Vasudhaiva Kutumbakam — One Earth, One Family, One Future", optionB: "Make in India", optionC: "Digital First", optionD: "Sabka Saath Sabka Vikas", correctOption: "A", explanation: "India's G20 theme was 'Vasudhaiva Kutumbakam — One Earth, One Family, One Future'.", orderIndex: 1 },
  { id: "upsc-current-affairs-global-summits-and-events-q03", topicId: "upsc-current-affairs-global-summits-and-events", text: "The Paris Agreement on climate change was adopted at which COP?", optionA: "COP21 (2015)", optionB: "COP15", optionC: "COP26", optionD: "COP3", correctOption: "A", explanation: "The Paris Agreement was adopted at COP21 in 2015.", orderIndex: 2 },
  { id: "upsc-current-affairs-global-summits-and-events-q04", topicId: "upsc-current-affairs-global-summits-and-events", text: "The QUAD grouping comprises India, the USA, Japan, and:", optionA: "Australia", optionB: "the UK", optionC: "France", optionD: "Russia", correctOption: "A", explanation: "The QUAD is India, the USA, Japan, and Australia.", orderIndex: 3 },
  { id: "upsc-current-affairs-global-summits-and-events-q05", topicId: "upsc-current-affairs-global-summits-and-events", text: "At COP26 (Glasgow), India pledged to achieve net-zero emissions by:", optionA: "2070", optionB: "2050", optionC: "2030", optionD: "2100", correctOption: "A", explanation: "At COP26, India announced a net-zero target by 2070 (the 'Panchamrit' pledges).", orderIndex: 4 },
  { id: "upsc-current-affairs-global-summits-and-events-q06", topicId: "upsc-current-affairs-global-summits-and-events", text: "The original members of BRICS were Brazil, Russia, India, China, and:", optionA: "South Africa", optionB: "Argentina", optionC: "Egypt", optionD: "Iran", correctOption: "A", explanation: "BRICS added South Africa in 2010 (BRIC → BRICS), later expanding further.", orderIndex: 5 },
  { id: "upsc-current-affairs-global-summits-and-events-q07", topicId: "upsc-current-affairs-global-summits-and-events", text: "The new permanent member admitted to the G20 in 2023 was the:", optionA: "African Union", optionB: "European Union", optionC: "ASEAN", optionD: "SAARC", correctOption: "A", explanation: "The African Union was admitted as a permanent G20 member at the 2023 New Delhi Summit.", orderIndex: 6 },
  { id: "upsc-current-affairs-global-summits-and-events-q08", topicId: "upsc-current-affairs-global-summits-and-events", text: "India's highest civilian award is the:", optionA: "Bharat Ratna", optionB: "Padma Vibhushan", optionC: "Param Vir Chakra", optionD: "Ashoka Chakra", correctOption: "A", explanation: "The Bharat Ratna is India's highest civilian honour.", orderIndex: 7 },
  { id: "upsc-current-affairs-global-summits-and-events-q09", topicId: "upsc-current-affairs-global-summits-and-events", text: "The SCO, which India joined as a full member in 2017, stands for the:", optionA: "Shanghai Cooperation Organisation", optionB: "South China Organisation", optionC: "Strategic Cooperation Order", optionD: "SAARC Coordination Office", correctOption: "A", explanation: "India became a full member of the Shanghai Cooperation Organisation (SCO) in 2017.", orderIndex: 8 },
  { id: "upsc-current-affairs-global-summits-and-events-q10", topicId: "upsc-current-affairs-global-summits-and-events", text: "BIMSTEC is a regional grouping of countries around which body of water?", optionA: "The Bay of Bengal", optionB: "The Arabian Sea", optionC: "The Mediterranean", optionD: "The Caspian Sea", correctOption: "A", explanation: "BIMSTEC links Bay of Bengal littoral and adjacent countries in South and Southeast Asia.", orderIndex: 9 },
  { id: "upsc-current-affairs-global-summits-and-events-q11", topicId: "upsc-current-affairs-global-summits-and-events", text: "COP28, which agreed to 'transition away' from fossil fuels, was held in:", optionA: "Dubai (UAE)", optionB: "Glasgow", optionC: "Sharm el-Sheikh", optionD: "Paris", correctOption: "A", explanation: "COP28 was held in Dubai, UAE, and called for transitioning away from fossil fuels.", orderIndex: 10 },
  { id: "upsc-current-affairs-global-summits-and-events-q12", topicId: "upsc-current-affairs-global-summits-and-events", text: "The Nobel Peace Prize is awarded in which city?", optionA: "Oslo", optionB: "Stockholm", optionC: "Geneva", optionD: "The Hague", correctOption: "A", explanation: "The Nobel Peace Prize is awarded in Oslo, Norway; the others are given in Stockholm.", orderIndex: 11 },

  // ── International Relations: India & Major Powers ──
  { id: "upsc-international-relations-india-and-major-powers-q01", topicId: "upsc-international-relations-india-and-major-powers", text: "The 2020 India-China military clash occurred in which valley?", optionA: "Galwan Valley", optionB: "Nubra Valley", optionC: "Kashmir Valley", optionD: "Silent Valley", correctOption: "A", explanation: "The June 2020 clash occurred in the Galwan Valley along the LAC in Ladakh.", orderIndex: 0 },
  { id: "upsc-international-relations-india-and-major-powers-q02", topicId: "upsc-international-relations-india-and-major-powers", text: "India's purchase of the S-400 air-defence system was from:", optionA: "Russia", optionB: "the USA", optionC: "France", optionD: "Israel", correctOption: "A", explanation: "India signed a deal with Russia for the S-400 Triumf air-defence systems.", orderIndex: 1 },
  { id: "upsc-international-relations-india-and-major-powers-q03", topicId: "upsc-international-relations-india-and-major-powers", text: "The India-US foundational defence agreement enabling geospatial cooperation is:", optionA: "BECA", optionB: "SAARC", optionC: "CEPA", optionD: "TAPI", correctOption: "A", explanation: "BECA (Basic Exchange and Cooperation Agreement) enables geospatial intelligence sharing.", orderIndex: 2 },
  { id: "upsc-international-relations-india-and-major-powers-q04", topicId: "upsc-international-relations-india-and-major-powers", text: "The BrahMos missile is a joint development between India and:", optionA: "Russia", optionB: "France", optionC: "the USA", optionD: "Israel", correctOption: "A", explanation: "BrahMos is a supersonic cruise missile co-developed by India and Russia.", orderIndex: 3 },
  { id: "upsc-international-relations-india-and-major-powers-q05", topicId: "upsc-international-relations-india-and-major-powers", text: "The China-Pakistan Economic Corridor (CPEC), which India objects to, passes through:", optionA: "Pakistan-occupied Kashmir (PoK)", optionB: "Nepal", optionC: "Bhutan", optionD: "Bangladesh", correctOption: "A", explanation: "India objects to CPEC because it runs through Pakistan-occupied Kashmir, violating sovereignty.", orderIndex: 4 },
  { id: "upsc-international-relations-india-and-major-powers-q06", topicId: "upsc-international-relations-india-and-major-powers", text: "India's foreign policy of engaging multiple power centres without binding alliances is termed:", optionA: "Strategic autonomy / multi-alignment", optionB: "Isolationism", optionC: "Bandwagoning", optionD: "Containment", correctOption: "A", explanation: "India follows strategic autonomy (multi-alignment), the successor to non-alignment.", orderIndex: 5 },
  { id: "upsc-international-relations-india-and-major-powers-q07", topicId: "upsc-international-relations-india-and-major-powers", text: "The disputed, undemarcated India-China boundary is called the:", optionA: "Line of Actual Control (LAC)", optionB: "Line of Control (LoC)", optionC: "Radcliffe Line", optionD: "Durand Line", correctOption: "A", explanation: "The Line of Actual Control (LAC) is the effective India-China boundary.", orderIndex: 6 },
  { id: "upsc-international-relations-india-and-major-powers-q08", topicId: "upsc-international-relations-india-and-major-powers", text: "The India-US initiative for cooperation on Critical and Emerging Technology is:", optionA: "iCET", optionB: "LEMOA", optionC: "QUAD", optionD: "IPEF", correctOption: "A", explanation: "iCET (initiative on Critical and Emerging Technology) deepens India-US tech cooperation.", orderIndex: 7 },
  { id: "upsc-international-relations-india-and-major-powers-q09", topicId: "upsc-international-relations-india-and-major-powers", text: "The 2017 India-China standoff at Doklam involved a tri-junction with:", optionA: "Bhutan", optionB: "Nepal", optionC: "Myanmar", optionD: "Bangladesh", correctOption: "A", explanation: "The Doklam standoff occurred at the India-China-Bhutan tri-junction.", orderIndex: 8 },
  { id: "upsc-international-relations-india-and-major-powers-q10", topicId: "upsc-international-relations-india-and-major-powers", text: "India's relationship with Russia is officially described as a:", optionA: "Special and Privileged Strategic Partnership", optionB: "Military alliance", optionC: "Free trade area", optionD: "Customs union", correctOption: "A", explanation: "India and Russia share a 'Special and Privileged Strategic Partnership'.", orderIndex: 9 },
  { id: "upsc-international-relations-india-and-major-powers-q11", topicId: "upsc-international-relations-india-and-major-powers", text: "The India-US logistics agreement allowing use of each other's military facilities is:", optionA: "LEMOA", optionB: "BECA", optionC: "COMCASA", optionD: "GSOMIA", correctOption: "A", explanation: "LEMOA (Logistics Exchange Memorandum of Agreement) enables reciprocal logistics support.", orderIndex: 10 },
  { id: "upsc-international-relations-india-and-major-powers-q12", topicId: "upsc-international-relations-india-and-major-powers", text: "India began normalising trade in nuclear technology after the NSG waiver secured via the deal with:", optionA: "the USA (2008)", optionB: "Russia", optionC: "France", optionD: "Japan", correctOption: "A", explanation: "The 2008 India-US civil nuclear deal led to the NSG waiver enabling nuclear commerce.", orderIndex: 11 },

  // ── International Relations: Border Disputes & Maritime Security ──
  { id: "upsc-international-relations-border-and-maritime-security-q01", topicId: "upsc-international-relations-border-and-maritime-security", text: "The Line of Control (LoC) separates India from Pakistan in:", optionA: "Jammu & Kashmir", optionB: "Punjab", optionC: "Rajasthan", optionD: "Gujarat", correctOption: "A", explanation: "The LoC divides Indian- and Pakistan-administered Kashmir.", orderIndex: 0 },
  { id: "upsc-international-relations-border-and-maritime-security-q02", topicId: "upsc-international-relations-border-and-maritime-security", text: "The McMahon Line demarcates the boundary between India and:", optionA: "China (in Arunachal Pradesh)", optionB: "Pakistan", optionC: "Nepal", optionD: "Myanmar", correctOption: "A", explanation: "The McMahon Line is the India-China boundary in the eastern sector, disputed by China.", orderIndex: 1 },
  { id: "upsc-international-relations-border-and-maritime-security-q03", topicId: "upsc-international-relations-border-and-maritime-security", text: "India's maritime vision for the Indian Ocean region is called:", optionA: "SAGAR", optionB: "SAGARMALA only", optionC: "BharatNet", optionD: "UDAN", correctOption: "A", explanation: "SAGAR — Security and Growth for All in the Region — is India's Indian Ocean vision.", orderIndex: 2 },
  { id: "upsc-international-relations-border-and-maritime-security-q04", topicId: "upsc-international-relations-border-and-maritime-security", text: "Under UNCLOS, a coastal state's Exclusive Economic Zone extends up to:", optionA: "200 nautical miles", optionB: "12 nautical miles", optionC: "50 nautical miles", optionD: "500 nautical miles", correctOption: "A", explanation: "The EEZ extends 200 nautical miles from the baseline under UNCLOS.", orderIndex: 3 },
  { id: "upsc-international-relations-border-and-maritime-security-q05", topicId: "upsc-international-relations-border-and-maritime-security", text: "The Simla Agreement (1972), which converted the ceasefire line into the LoC, was signed with:", optionA: "Pakistan", optionB: "China", optionC: "Bangladesh", optionD: "Sri Lanka", correctOption: "A", explanation: "The 1972 Simla Agreement between India and Pakistan established the LoC.", orderIndex: 4 },
  { id: "upsc-international-relations-border-and-maritime-security-q06", topicId: "upsc-international-relations-border-and-maritime-security", text: "The Strait of Hormuz, a critical oil choke point, connects the Persian Gulf to the:", optionA: "Gulf of Oman / Arabian Sea", optionB: "Red Sea", optionC: "Mediterranean Sea", optionD: "Black Sea", correctOption: "A", explanation: "The Strait of Hormuz links the Persian Gulf to the Gulf of Oman and Arabian Sea.", orderIndex: 5 },
  { id: "upsc-international-relations-border-and-maritime-security-q07", topicId: "upsc-international-relations-border-and-maritime-security", text: "Aksai Chin, a disputed region administered by China, is claimed by India as part of:", optionA: "Ladakh", optionB: "Arunachal Pradesh", optionC: "Sikkim", optionD: "Nagaland", correctOption: "A", explanation: "India claims Aksai Chin (under Chinese control) as part of Ladakh.", orderIndex: 6 },
  { id: "upsc-international-relations-border-and-maritime-security-q08", topicId: "upsc-international-relations-border-and-maritime-security", text: "The Durand Line is the disputed border between:", optionA: "Afghanistan and Pakistan", optionB: "India and Pakistan", optionC: "India and China", optionD: "India and Nepal", correctOption: "A", explanation: "The Durand Line separates Afghanistan and Pakistan.", orderIndex: 7 },
  { id: "upsc-international-relations-border-and-maritime-security-q09", topicId: "upsc-international-relations-border-and-maritime-security", text: "India is often described in the Indian Ocean as a:", optionA: "Net security provider", optionB: "Landlocked state", optionC: "Non-littoral power", optionD: "Neutral bystander", correctOption: "A", explanation: "India acts as a 'net security provider' in the Indian Ocean region.", orderIndex: 8 },
  { id: "upsc-international-relations-border-and-maritime-security-q10", topicId: "upsc-international-relations-border-and-maritime-security", text: "The strategically vital Andaman & Nicobar Islands host India's only:", optionA: "Tri-services theatre command", optionB: "Nuclear plant", optionC: "Spaceport", optionD: "Oil refinery", correctOption: "A", explanation: "The Andaman & Nicobar Command is India's first and only tri-services theatre command.", orderIndex: 9 },
  { id: "upsc-international-relations-border-and-maritime-security-q11", topicId: "upsc-international-relations-border-and-maritime-security", text: "The Strait of Malacca, a key shipping lane, lies between the Malay Peninsula and:", optionA: "Sumatra (Indonesia)", optionB: "Sri Lanka", optionC: "Japan", optionD: "Australia", correctOption: "A", explanation: "The Strait of Malacca runs between the Malay Peninsula and the Indonesian island of Sumatra.", orderIndex: 10 },
  { id: "upsc-international-relations-border-and-maritime-security-q12", topicId: "upsc-international-relations-border-and-maritime-security", text: "The 2017 India-China standoff at Doklam was primarily over a Chinese attempt to build a:", optionA: "Road near the tri-junction", optionB: "Naval base", optionC: "Dam", optionD: "Railway line", correctOption: "A", explanation: "The Doklam standoff arose over Chinese road construction near the tri-junction with Bhutan.", orderIndex: 11 },

  // ── Governance: Citizen-Centric Governance & Service Delivery ──
  { id: "upsc-governance-citizen-centric-governance-q01", topicId: "upsc-governance-citizen-centric-governance", text: "A document declaring an organisation's service standards to the public is a:", optionA: "Citizens' Charter", optionB: "White Paper", optionC: "Gazette", optionD: "Ordinance", correctOption: "A", explanation: "A Citizens' Charter publicly commits an agency to service standards and timelines.", orderIndex: 0 },
  { id: "upsc-governance-citizen-centric-governance-q02", topicId: "upsc-governance-citizen-centric-governance", text: "In 'SMART' governance, the 'T' stands for:", optionA: "Transparent", optionB: "Technical", optionC: "Timely", optionD: "Trustworthy", correctOption: "A", explanation: "SMART governance = Simple, Moral, Accountable, Responsive, and Transparent.", orderIndex: 1 },
  { id: "upsc-governance-citizen-centric-governance-q03", topicId: "upsc-governance-citizen-centric-governance", text: "Transferring subsidies straight to beneficiaries' bank accounts to cut leakages is called:", optionA: "Direct Benefit Transfer (DBT)", optionB: "Cross-subsidy", optionC: "Deficit financing", optionD: "Quantitative easing", correctOption: "A", explanation: "DBT transfers benefits directly to beneficiaries, reducing intermediary leakages.", orderIndex: 2 },
  { id: "upsc-governance-citizen-centric-governance-q04", topicId: "upsc-governance-citizen-centric-governance", text: "The Sevottam model is a framework to assess and improve:", optionA: "Public service delivery", optionB: "Tax collection", optionC: "Election conduct", optionD: "Judicial appointments", correctOption: "A", explanation: "Sevottam is a service-delivery excellence model for public organisations.", orderIndex: 3 },
  { id: "upsc-governance-citizen-centric-governance-q05", topicId: "upsc-governance-citizen-centric-governance", text: "The e-governance interaction between government and citizens is abbreviated:", optionA: "G2C", optionB: "B2B", optionC: "C2C", optionD: "P2P", correctOption: "A", explanation: "G2C (Government-to-Citizen) covers services delivered to citizens.", orderIndex: 4 },
  { id: "upsc-governance-citizen-centric-governance-q06", topicId: "upsc-governance-citizen-centric-governance", text: "Social audits as an accountability tool were pioneered in India under:", optionA: "MGNREGA", optionB: "the GST", optionC: "the RBI Act", optionD: "the Companies Act", correctOption: "A", explanation: "MGNREGA institutionalised social audits by gram sabhas to check corruption.", orderIndex: 5 },
  { id: "upsc-governance-citizen-centric-governance-q07", topicId: "upsc-governance-citizen-centric-governance", text: "The central public grievance redressal portal is:", optionA: "CPGRAMS", optionB: "DigiLocker", optionC: "GeM", optionD: "e-NAM", correctOption: "A", explanation: "CPGRAMS is the Centralised Public Grievance Redress and Monitoring System.", orderIndex: 6 },
  { id: "upsc-governance-citizen-centric-governance-q08", topicId: "upsc-governance-citizen-centric-governance", text: "The Right to Information Act was enacted in:", optionA: "2005", optionB: "2013", optionC: "1998", optionD: "2019", correctOption: "A", explanation: "The RTI Act, empowering citizens to seek public information, was passed in 2005.", orderIndex: 7 },
  { id: "upsc-governance-citizen-centric-governance-q09", topicId: "upsc-governance-citizen-centric-governance", text: "The digital platform for storing and sharing official documents securely is:", optionA: "DigiLocker", optionB: "CPGRAMS", optionC: "UPI", optionD: "NATGRID", correctOption: "A", explanation: "DigiLocker lets citizens store and share verified digital documents.", orderIndex: 8 },
  { id: "upsc-governance-citizen-centric-governance-q10", topicId: "upsc-governance-citizen-centric-governance", text: "The Second Administrative Reforms Commission (ARC) was chaired initially by:", optionA: "Veerappa Moily", optionB: "Morarji Desai", optionC: "B. R. Ambedkar", optionD: "K. Santhanam", correctOption: "A", explanation: "The 2nd ARC was chaired by Veerappa Moily (later M. Veerappa Moily/Y. K. Alagh phases).", orderIndex: 9 },
  { id: "upsc-governance-citizen-centric-governance-q11", topicId: "upsc-governance-citizen-centric-governance", text: "Many states guarantee time-bound public services through laws known as the:", optionA: "Right to Public Services Acts", optionB: "Official Secrets Acts", optionC: "Contempt of Court Acts", optionD: "Sedition laws", correctOption: "A", explanation: "Right to Public Services Acts guarantee time-bound delivery of notified services.", orderIndex: 10 },
  { id: "upsc-governance-citizen-centric-governance-q12", topicId: "upsc-governance-citizen-centric-governance", text: "The slogan capturing the aim of efficient, limited government is:", optionA: "Minimum Government, Maximum Governance", optionB: "Garibi Hatao", optionC: "Jai Jawan Jai Kisan", optionD: "Inclusive Growth", correctOption: "A", explanation: "'Minimum Government, Maximum Governance' expresses the drive for efficient administration.", orderIndex: 11 },

  // ── Governance: Civil Services & Non-State Actors ──
  { id: "upsc-governance-civil-services-and-non-state-actors-q01", topicId: "upsc-governance-civil-services-and-non-state-actors", text: "The All India Services include the IAS, IPS, and the:", optionA: "Indian Forest Service (IFoS)", optionB: "Indian Foreign Service", optionC: "Indian Revenue Service", optionD: "Indian Railway Service", correctOption: "A", explanation: "The three All India Services are the IAS, IPS, and Indian Forest Service (IFoS).", orderIndex: 0 },
  { id: "upsc-governance-civil-services-and-non-state-actors-q02", topicId: "upsc-governance-civil-services-and-non-state-actors", text: "The constitutional article providing for All India Services is:", optionA: "Article 312", optionB: "Article 356", optionC: "Article 21", optionD: "Article 370", correctOption: "A", explanation: "Article 312 empowers Parliament to create All India Services.", orderIndex: 1 },
  { id: "upsc-governance-civil-services-and-non-state-actors-q03", topicId: "upsc-governance-civil-services-and-non-state-actors", text: "Civil servants are expected to be politically:", optionA: "Neutral", optionB: "Partisan", optionC: "Elected", optionD: "Temporary", correctOption: "A", explanation: "Political neutrality and anonymity are core values of a permanent civil service.", orderIndex: 2 },
  { id: "upsc-governance-civil-services-and-non-state-actors-q04", topicId: "upsc-governance-civil-services-and-non-state-actors", text: "Self-Help Groups (SHGs) primarily promote:", optionA: "Financial inclusion and micro-credit", optionB: "National defence", optionC: "Foreign trade", optionD: "Space research", correctOption: "A", explanation: "SHGs pool savings and provide micro-credit, advancing financial inclusion, especially for women.", orderIndex: 3 },
  { id: "upsc-governance-civil-services-and-non-state-actors-q05", topicId: "upsc-governance-civil-services-and-non-state-actors", text: "The Amul dairy success is a model of which type of organisation?", optionA: "Cooperative", optionB: "Multinational corporation", optionC: "Public sector undertaking", optionD: "Sole proprietorship", correctOption: "A", explanation: "Amul exemplifies the cooperative model of collective, farmer-owned enterprise.", orderIndex: 4 },
  { id: "upsc-governance-civil-services-and-non-state-actors-q06", topicId: "upsc-governance-civil-services-and-non-state-actors", text: "Foreign funding of NGOs in India is regulated under the:", optionA: "FCRA", optionB: "FEMA only", optionC: "RTI Act", optionD: "IPC", correctOption: "A", explanation: "The Foreign Contribution (Regulation) Act (FCRA) governs foreign funding of NGOs.", orderIndex: 5 },
  { id: "upsc-governance-civil-services-and-non-state-actors-q07", topicId: "upsc-governance-civil-services-and-non-state-actors", text: "The media is often referred to as the:", optionA: "Fourth estate", optionB: "Fifth column", optionC: "Third house", optionD: "Second chamber", correctOption: "A", explanation: "The media is called the 'fourth estate' for its role in a democracy.", orderIndex: 6 },
  { id: "upsc-governance-civil-services-and-non-state-actors-q08", topicId: "upsc-governance-civil-services-and-non-state-actors", text: "Kudumbashree, a large women's empowerment network, is a programme of:", optionA: "Kerala", optionB: "Gujarat", optionC: "Bihar", optionD: "Punjab", correctOption: "A", explanation: "Kudumbashree is Kerala's flagship women's SHG and poverty-eradication programme.", orderIndex: 7 },
  { id: "upsc-governance-civil-services-and-non-state-actors-q09", topicId: "upsc-governance-civil-services-and-non-state-actors", text: "Mandatory Corporate Social Responsibility (CSR) spending for large firms is under the:", optionA: "Companies Act", optionB: "Income Tax Act", optionC: "RTI Act", optionD: "GST Act", correctOption: "A", explanation: "The Companies Act, 2013 mandates CSR spending by qualifying companies.", orderIndex: 8 },
  { id: "upsc-governance-civil-services-and-non-state-actors-q10", topicId: "upsc-governance-civil-services-and-non-state-actors", text: "Bringing in domain experts from outside the regular services to government posts is called:", optionA: "Lateral entry", optionB: "Deputation only", optionC: "Reservation", optionD: "Impeachment", correctOption: "A", explanation: "Lateral entry recruits specialists directly into senior government positions.", orderIndex: 9 },
  { id: "upsc-governance-civil-services-and-non-state-actors-q11", topicId: "upsc-governance-civil-services-and-non-state-actors", text: "Groups that seek to influence policy without contesting elections are called:", optionA: "Pressure groups", optionB: "Political parties", optionC: "Electoral colleges", optionD: "Tribunals", correctOption: "A", explanation: "Pressure/interest groups influence policy without seeking to form a government.", orderIndex: 10 },
  { id: "upsc-governance-civil-services-and-non-state-actors-q12", topicId: "upsc-governance-civil-services-and-non-state-actors", text: "The principle that civil servants give 'frank and fearless' advice but implement the minister's final decision reflects:", optionA: "Political neutrality and accountability", optionB: "Judicial review", optionC: "Separation of powers", optionD: "Federal supremacy", correctOption: "A", explanation: "Civil servants advise honestly yet remain accountable to elected ministers — a neutrality norm.", orderIndex: 11 },

  // ── Internal Security: Security Forces & Agencies ──
  { id: "upsc-internal-security-security-forces-and-agencies-q01", topicId: "upsc-internal-security-security-forces-and-agencies", text: "India's external intelligence agency is the:", optionA: "Research and Analysis Wing (RAW)", optionB: "Intelligence Bureau (IB)", optionC: "CBI", optionD: "NIA", correctOption: "A", explanation: "RAW is India's external intelligence agency; the IB handles internal intelligence.", orderIndex: 0 },
  { id: "upsc-internal-security-security-forces-and-agencies-q02", topicId: "upsc-internal-security-security-forces-and-agencies", text: "The largest Central Armed Police Force, key to internal security and anti-Naxal operations, is the:", optionA: "CRPF", optionB: "BSF", optionC: "CISF", optionD: "ITBP", correctOption: "A", explanation: "The Central Reserve Police Force (CRPF) is India's largest CAPF.", orderIndex: 1 },
  { id: "upsc-internal-security-security-forces-and-agencies-q03", topicId: "upsc-internal-security-security-forces-and-agencies", text: "The elite counter-terrorism force known as the 'Black Cats' is the:", optionA: "National Security Guard (NSG)", optionB: "CISF", optionC: "SSB", optionD: "Assam Rifles", correctOption: "A", explanation: "The NSG ('Black Cats') is India's elite counter-terrorism and hostage-rescue force.", orderIndex: 2 },
  { id: "upsc-internal-security-security-forces-and-agencies-q04", topicId: "upsc-internal-security-security-forces-and-agencies", text: "The force responsible for security of airports and vital installations is the:", optionA: "CISF", optionB: "BSF", optionC: "ITBP", optionD: "SSB", correctOption: "A", explanation: "The Central Industrial Security Force (CISF) guards airports and industrial installations.", orderIndex: 3 },
  { id: "upsc-internal-security-security-forces-and-agencies-q05", topicId: "upsc-internal-security-security-forces-and-agencies", text: "The head of India's tri-services integration, created in 2019, is the:", optionA: "Chief of Defence Staff (CDS)", optionB: "Cabinet Secretary", optionC: "Home Secretary", optionD: "National Security Adviser", correctOption: "A", explanation: "The Chief of Defence Staff (CDS) heads the Department of Military Affairs and integrates the services.", orderIndex: 4 },
  { id: "upsc-internal-security-security-forces-and-agencies-q06", topicId: "upsc-internal-security-security-forces-and-agencies", text: "The agency that investigates economic offences under the PMLA and FEMA is the:", optionA: "Enforcement Directorate (ED)", optionB: "NIA", optionC: "IB", optionD: "RAW", correctOption: "A", explanation: "The Enforcement Directorate (ED) enforces the PMLA and FEMA against economic offences.", orderIndex: 5 },
  { id: "upsc-internal-security-security-forces-and-agencies-q07", topicId: "upsc-internal-security-security-forces-and-agencies", text: "In the Indian Constitution, 'police' and 'public order' are placed in the:", optionA: "State List", optionB: "Union List", optionC: "Concurrent List", optionD: "Residuary powers", correctOption: "A", explanation: "'Police' and 'public order' are State List subjects under the Seventh Schedule.", orderIndex: 6 },
  { id: "upsc-internal-security-security-forces-and-agencies-q08", topicId: "upsc-internal-security-security-forces-and-agencies", text: "The apex body advising the PM on national security, headed by the NSA, is the:", optionA: "National Security Council (NSC)", optionB: "Finance Commission", optionC: "NITI Aayog", optionD: "Election Commission", correctOption: "A", explanation: "The National Security Council advises the PM, coordinated by the National Security Adviser.", orderIndex: 7 },
  { id: "upsc-internal-security-security-forces-and-agencies-q09", topicId: "upsc-internal-security-security-forces-and-agencies", text: "The Assam Rifles primarily operate in which region?", optionA: "The North-East", optionB: "Rajasthan desert", optionC: "The Deccan", optionD: "Gujarat coast", correctOption: "A", explanation: "The Assam Rifles are the oldest paramilitary force, guarding the north-eastern frontier.", orderIndex: 8 },
  { id: "upsc-internal-security-security-forces-and-agencies-q10", topicId: "upsc-internal-security-security-forces-and-agencies", text: "The premier agency for investigating major crimes and corruption at the central level is the:", optionA: "CBI", optionB: "CISF", optionC: "BSF", optionD: "NDRF", correctOption: "A", explanation: "The Central Bureau of Investigation (CBI) probes major crimes and corruption cases.", orderIndex: 9 },
  { id: "upsc-internal-security-security-forces-and-agencies-q11", topicId: "upsc-internal-security-security-forces-and-agencies", text: "NATGRID is being developed as a:", optionA: "Networked intelligence/database grid for security agencies", optionB: "Power transmission grid", optionC: "Weather monitoring system", optionD: "Payment system", correctOption: "A", explanation: "NATGRID is an integrated intelligence grid linking databases for security agencies.", orderIndex: 10 },
  { id: "upsc-internal-security-security-forces-and-agencies-q12", topicId: "upsc-internal-security-security-forces-and-agencies", text: "India's internal intelligence agency is the:", optionA: "Intelligence Bureau (IB)", optionB: "RAW", optionC: "NIA", optionD: "ED", correctOption: "A", explanation: "The Intelligence Bureau (IB) is India's domestic (internal) intelligence agency.", orderIndex: 11 },

  // ── Internal Security: Extremism, Terror Financing & Social Media ──
  { id: "upsc-internal-security-extremism-and-terror-financing-q01", topicId: "upsc-internal-security-extremism-and-terror-financing", text: "The belt worst affected by Left-Wing Extremism is often called the:", optionA: "Red Corridor", optionB: "Golden Triangle", optionC: "Chicken's Neck", optionD: "Cotton Belt", correctOption: "A", explanation: "The 'Red Corridor' spans LWE-affected districts of central and eastern India.", orderIndex: 0 },
  { id: "upsc-internal-security-extremism-and-terror-financing-q02", topicId: "upsc-internal-security-extremism-and-terror-financing", text: "The main anti-terror law under which terror offences are prosecuted in India is the:", optionA: "UAPA", optionB: "RTI Act", optionC: "RTE Act", optionD: "MGNREGA", correctOption: "A", explanation: "The Unlawful Activities (Prevention) Act (UAPA) is India's principal anti-terror law.", orderIndex: 1 },
  { id: "upsc-internal-security-extremism-and-terror-financing-q03", topicId: "upsc-internal-security-extremism-and-terror-financing", text: "The global watchdog whose 'grey list' pressures states on terror financing is the:", optionA: "FATF", optionB: "WTO", optionC: "UNESCO", optionD: "IMF", correctOption: "A", explanation: "The Financial Action Task Force (FATF) monitors and lists states on money laundering and terror financing.", orderIndex: 2 },
  { id: "upsc-internal-security-extremism-and-terror-financing-q04", topicId: "upsc-internal-security-extremism-and-terror-financing", text: "The informal, illegal money-transfer system often misused for terror funding is:", optionA: "Hawala", optionB: "UPI", optionC: "RTGS", optionD: "NEFT", correctOption: "A", explanation: "Hawala is an informal value-transfer system exploited to move illicit funds.", orderIndex: 3 },
  { id: "upsc-internal-security-extremism-and-terror-financing-q05", topicId: "upsc-internal-security-extremism-and-terror-financing", text: "The government's strategy doctrine to tackle Left-Wing Extremism is called:", optionA: "SAMADHAN", optionB: "SAGAR", optionC: "UDAN", optionD: "AMRUT", correctOption: "A", explanation: "SAMADHAN is the multi-pronged strategy against Left-Wing Extremism.", orderIndex: 4 },
  { id: "upsc-internal-security-extremism-and-terror-financing-q06", topicId: "upsc-internal-security-extremism-and-terror-financing", text: "The central agency that investigates terror-related cases is the:", optionA: "NIA", optionB: "CISF", optionC: "NDRF", optionD: "SSB", correctOption: "A", explanation: "The National Investigation Agency (NIA) investigates terrorism-related offences.", orderIndex: 5 },
  { id: "upsc-internal-security-extremism-and-terror-financing-q07", topicId: "upsc-internal-security-extremism-and-terror-financing", text: "The use of the internet to recruit and incite attackers is known as:", optionA: "Online radicalisation", optionB: "Phishing", optionC: "Firewalling", optionD: "Encryption", correctOption: "A", explanation: "Online radicalisation uses social media and the internet to spread extremist propaganda and recruit.", orderIndex: 6 },
  { id: "upsc-internal-security-extremism-and-terror-financing-q08", topicId: "upsc-internal-security-extremism-and-terror-financing", text: "An attacker who acts alone, often self-radicalised online, is called a:", optionA: "Lone wolf", optionB: "Double agent", optionC: "Whistle-blower", optionD: "Sleeper cell", correctOption: "A", explanation: "A 'lone wolf' attacker operates independently, frequently after online self-radicalisation.", orderIndex: 7 },
  { id: "upsc-internal-security-extremism-and-terror-financing-q09", topicId: "upsc-internal-security-extremism-and-terror-financing", text: "Terror financing through counterfeit currency is countered partly by tracking:", optionA: "Fake Indian Currency Notes (FICN)", optionB: "Postage stamps", optionC: "Coins only", optionD: "Bearer bonds", correctOption: "A", explanation: "Fake Indian Currency Notes (FICN) are a known channel of terror financing.", orderIndex: 8 },
  { id: "upsc-internal-security-extremism-and-terror-financing-q10", topicId: "upsc-internal-security-extremism-and-terror-financing", text: "The law used to attach and confiscate proceeds of crime linked to terror funding is the:", optionA: "PMLA", optionB: "RTI Act", optionC: "RTE Act", optionD: "Companies Act", correctOption: "A", explanation: "The Prevention of Money Laundering Act (PMLA) allows attachment of proceeds of crime.", orderIndex: 9 },
  { id: "upsc-internal-security-extremism-and-terror-financing-q11", topicId: "upsc-internal-security-extremism-and-terror-financing", text: "Programmes to reintegrate former militants into society are known as:", optionA: "De-radicalisation programmes", optionB: "Encryption drives", optionC: "Surveillance audits", optionD: "Cordon operations", correctOption: "A", explanation: "De-radicalisation programmes aim to rehabilitate and reintegrate former extremists.", orderIndex: 10 },
  { id: "upsc-internal-security-extremism-and-terror-financing-q12", topicId: "upsc-internal-security-extremism-and-terror-financing", text: "Rapidly spreading false information online that can inflame tensions is termed:", optionA: "Fake news / disinformation", optionB: "Open data", optionC: "Metadata", optionD: "Firmware", correctOption: "A", explanation: "Fake news/disinformation spread via social media can incite unrest and aid radicalisation.", orderIndex: 11 }
];
