// UPSC depth expansion — Polity and Economy (pass 6). These are the two
// highest-weight GS subjects; this pass fills their remaining high-yield gaps.
// Each new topic has a 2-minute study note and a full 12-question drill.
import type { AuthoredMaterial } from "./builder";
import type { Question, Topic } from "@jyotir/core";

export const exp6Topics: Topic[] = [
  // Polity (existing max orderIndex = 8)
  { id: "upsc-polity-making-of-the-constitution", subjectId: "upsc-polity", name: "Making of the Constitution & Preamble", slug: "making-of-the-constitution", orderIndex: 9 },
  { id: "upsc-polity-elections-and-representation", subjectId: "upsc-polity", name: "Elections & Representation of the People", slug: "elections-and-representation", orderIndex: 10 },
  { id: "upsc-polity-anti-defection-and-committees", subjectId: "upsc-polity", name: "Anti-Defection & Parliamentary Committees", slug: "anti-defection-and-committees", orderIndex: 11 },
  // Economy (existing max orderIndex = 7)
  { id: "upsc-economy-financial-markets-and-sebi", subjectId: "upsc-economy", name: "Financial Markets & SEBI", slug: "financial-markets-and-sebi", orderIndex: 8 },
  { id: "upsc-economy-planning-and-economic-reforms", subjectId: "upsc-economy", name: "Planning & Economic Reforms", slug: "planning-and-economic-reforms", orderIndex: 9 },
  { id: "upsc-economy-industry-and-infrastructure", subjectId: "upsc-economy", name: "Industry, Infrastructure & Investment", slug: "industry-and-infrastructure", orderIndex: 10 }
];

export const exp6Materials: AuthoredMaterial[] = [
  { id: "upsc-polity-making-of-the-constitution-m01", topicId: "upsc-polity-making-of-the-constitution", title: "Making of the Constitution & Preamble", content: `The **Constituent Assembly**, formed under the **Cabinet Mission Plan (1946)**, drafted the Constitution. Its first meeting was on **9 December 1946**; **Dr. Rajendra Prasad** was its President. The **Drafting Committee** was chaired by **Dr. B. R. Ambedkar** (the 'Father of the Constitution'). The Constitution was adopted on **26 November 1949** (Constitution Day) and came into force on **26 January 1950** (Republic Day). It took **2 years, 11 months, and 18 days**.

The Constitution drew from many sources: the **Government of India Act 1935** (federal scheme, most provisions); **Britain** (parliamentary system, rule of law, single citizenship); the **USA** (Fundamental Rights, judicial review, independent judiciary, preamble); **Ireland** (Directive Principles); **Canada** (a strong centre/federation); and the **USSR** (Fundamental Duties, planning). The **Preamble** — based on Nehru's **Objectives Resolution** — declares India a **Sovereign, Socialist, Secular, Democratic Republic** ('Socialist' and 'Secular' were added by the **42nd Amendment, 1976**) and secures Justice, Liberty, Equality, and Fraternity. In *Kesavananda Bharati* and *Berubari*, the courts held the Preamble is a part of the Constitution and can be amended without altering its basic structure.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "upsc-polity-elections-and-representation-m01", topicId: "upsc-polity-elections-and-representation", title: "Elections & Representation of the People", content: `The **Election Commission of India (ECI)**, a **constitutional body under Article 324**, superintends elections to Parliament, State legislatures, and the offices of President and Vice-President. It is a multi-member body (a **Chief Election Commissioner** and two Election Commissioners), who can be removed only like a Supreme Court judge (the CEC) — safeguarding independence. India uses the **First-Past-The-Post** system for Lok Sabha and Assembly elections and **proportional representation (single transferable vote)** for the Rajya Sabha and presidential elections.

Elections are governed by the **Representation of the People Acts (1950 and 1951)**, which cover qualifications, the electoral roll, conduct of elections, and disqualifications (including on conviction). The **Model Code of Conduct** kicks in once elections are announced. Reforms include **EVMs and VVPAT**, **NOTA** (None of the Above, 2013), lowering the voting age to **18 (61st Amendment, 1989)**, and expenditure limits. Recent debates cover **electoral bonds** (struck down by the Supreme Court in 2024), **criminalisation of politics**, and proposals for **'One Nation, One Election'**. Universal adult franchise is a hallmark of Indian democracy.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "upsc-polity-anti-defection-and-committees-m01", topicId: "upsc-polity-anti-defection-and-committees", title: "Anti-Defection & Parliamentary Committees", content: `The **Anti-Defection Law**, added by the **52nd Amendment (1985)** as the **Tenth Schedule**, disqualifies legislators who voluntarily give up party membership or defy the party whip. The **91st Amendment (2003)** removed the earlier exemption for a 'split' (requiring one-third), now allowing only a **merger** (needing two-thirds of members). The **presiding officer** (Speaker/Chairman) decides on disqualification, subject to judicial review.

**Parliamentary Committees** enable detailed scrutiny that the full House cannot manage. **Financial committees**: the **Public Accounts Committee (PAC)** examines audited accounts (its chair is, by convention, from the Opposition); the **Estimates Committee** (the 'continuous economy committee') scrutinises budget estimates; and the **Committee on Public Undertakings** reviews PSUs. **Department-Related Standing Committees (DRSCs)** examine bills, budgets, and policy across ministries. **Ad hoc committees** (e.g., Select/Joint Committees on specific bills, Joint Parliamentary Committees) are temporary. Committees strengthen accountability, allow expert and cross-party deliberation away from the glare of the House, and improve the quality of legislation.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "upsc-economy-financial-markets-and-sebi-m01", topicId: "upsc-economy-financial-markets-and-sebi", title: "Financial Markets & SEBI", content: `The **financial market** channels savings to investment. The **money market** deals in short-term funds (Treasury Bills, Commercial Paper, Certificates of Deposit, call money) and is regulated by the **RBI**. The **capital market** deals in long-term securities — **equity (shares)** and **debt (bonds/debentures)** — split into the **primary market** (new issues via **IPOs**) and the **secondary market** (trading of existing securities on stock exchanges like the **BSE** and **NSE**, tracked by the **Sensex** and **Nifty**).

The **Securities and Exchange Board of India (SEBI)**, a **statutory body (1992)**, regulates the securities market, protects investors, and curbs malpractices like insider trading. Instruments include **mutual funds**, **derivatives** (futures and options), **ETFs**, and, for foreign investors, the **FPI/FII** route. Key concepts: **primary vs secondary market**, **bull vs bear** markets, **market capitalisation**, and **dematerialisation** (holding shares electronically via depositories like **NSDL/CDSL**). Other regulators include **IRDAI** (insurance) and **PFRDA** (pensions). A deep, well-regulated financial market is vital for mobilising capital and financing India's growth.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "upsc-economy-planning-and-economic-reforms-m01", topicId: "upsc-economy-planning-and-economic-reforms", title: "Planning & Economic Reforms", content: `After independence, India adopted **centralised planning** through the **Planning Commission (1950)** and **Five-Year Plans** (modelled partly on the USSR). The **Second Plan (1956)**, based on the **Mahalanobis model**, stressed heavy industry and the public sector (the 'commanding heights'). This era of the **'Licence-Permit-Quota Raj'** brought self-reliance but also inefficiency and slow 'Hindu rate of growth'.

Facing a **balance-of-payments crisis in 1991**, India launched **LPG reforms — Liberalisation, Privatisation, and Globalisation** — under PM Narasimha Rao and FM Manmohan Singh: **industrial delicensing**, lower tariffs, **devaluation**, opening to **FDI**, and disinvestment. Growth accelerated and a large services sector emerged. In **2015**, the Planning Commission was replaced by **NITI Aayog** (National Institution for Transforming India), a think tank promoting **cooperative and competitive federalism** (indices like the SDG Index and Aspirational Districts) rather than allocating funds. Ongoing reforms include **GST**, the **Insolvency and Bankruptcy Code**, labour codes, and 'Make in India' / 'Atmanirbhar Bharat' for self-reliant manufacturing.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "upsc-economy-industry-and-infrastructure-m01", topicId: "upsc-economy-industry-and-infrastructure", title: "Industry, Infrastructure & Investment", content: `**Industry** spans micro, small, medium (**MSMEs** — big employers, defined by investment and turnover), and large enterprises. Government initiatives include **Make in India**, **Production-Linked Incentive (PLI)** schemes to boost manufacturing, **Startup India**, and industrial corridors. The **index of industrial production (IIP)** and the **eight core industries** (coal, crude oil, natural gas, refinery products, fertilisers, steel, cement, electricity) track output; the manufacturing share of GDP is a key policy focus.

**Infrastructure** — power, roads, railways, ports, airports, and digital — underpins growth. Financing uses **public–private partnership (PPP)** models such as **BOT (Build-Operate-Transfer)**, **BOOT**, **HAM (Hybrid Annuity Model)**, and the **viability gap funding** mechanism. Flagship programmes include **Bharatmala** (highways), **Sagarmala** (ports), **UDAN** (regional air connectivity), the **National Infrastructure Pipeline**, **Gati Shakti** (integrated infrastructure planning), and **BharatNet** (rural broadband). **Foreign investment** comes as **FDI** (long-term, in businesses) or **FPI** (portfolio, in markets). Adequate, efficient infrastructure lowers logistics costs and is central to India's ambition of becoming a developed economy.`, estimatedReadTime: 2, orderIndex: 0 }
];

export const exp6Questions: Question[] = [
  // ── Polity: Making of the Constitution & Preamble ──
  { id: "upsc-polity-making-of-the-constitution-q01", topicId: "upsc-polity-making-of-the-constitution", text: "The Chairman of the Drafting Committee of the Constitution was:", optionA: "Dr. B. R. Ambedkar", optionB: "Dr. Rajendra Prasad", optionC: "Jawaharlal Nehru", optionD: "Sardar Patel", correctOption: "A", explanation: "Dr. B. R. Ambedkar chaired the Drafting Committee and is called the 'Father of the Constitution'.", orderIndex: 0 },
  { id: "upsc-polity-making-of-the-constitution-q02", topicId: "upsc-polity-making-of-the-constitution", text: "The Constitution of India came into force on:", optionA: "26 January 1950", optionB: "15 August 1947", optionC: "26 November 1949", optionD: "9 December 1946", correctOption: "A", explanation: "The Constitution came into force on 26 January 1950, celebrated as Republic Day.", orderIndex: 1 },
  { id: "upsc-polity-making-of-the-constitution-q03", topicId: "upsc-polity-making-of-the-constitution", text: "The President of the Constituent Assembly was:", optionA: "Dr. Rajendra Prasad", optionB: "Dr. B. R. Ambedkar", optionC: "Jawaharlal Nehru", optionD: "Sachchidananda Sinha", correctOption: "A", explanation: "Dr. Rajendra Prasad was the permanent President of the Constituent Assembly.", orderIndex: 2 },
  { id: "upsc-polity-making-of-the-constitution-q04", topicId: "upsc-polity-making-of-the-constitution", text: "The Directive Principles of State Policy were borrowed from the Constitution of:", optionA: "Ireland", optionB: "the USA", optionC: "Britain", optionD: "Canada", correctOption: "A", explanation: "The DPSP were inspired by the Irish Constitution.", orderIndex: 3 },
  { id: "upsc-polity-making-of-the-constitution-q05", topicId: "upsc-polity-making-of-the-constitution", text: "The idea of Fundamental Rights and judicial review was drawn mainly from:", optionA: "the USA", optionB: "Britain", optionC: "Ireland", optionD: "the USSR", correctOption: "A", explanation: "Fundamental Rights, judicial review, and the preamble were inspired by the US Constitution.", orderIndex: 4 },
  { id: "upsc-polity-making-of-the-constitution-q06", topicId: "upsc-polity-making-of-the-constitution", text: "The words 'Socialist' and 'Secular' were added to the Preamble by which amendment?", optionA: "42nd Amendment (1976)", optionB: "44th Amendment (1978)", optionC: "1st Amendment (1951)", optionD: "52nd Amendment (1985)", correctOption: "A", explanation: "The 42nd Amendment (1976) added 'Socialist', 'Secular', and 'Integrity' to the Preamble.", orderIndex: 5 },
  { id: "upsc-polity-making-of-the-constitution-q07", topicId: "upsc-polity-making-of-the-constitution", text: "The Objectives Resolution, which inspired the Preamble, was moved by:", optionA: "Jawaharlal Nehru", optionB: "B. R. Ambedkar", optionC: "Rajendra Prasad", optionD: "Vallabhbhai Patel", correctOption: "A", explanation: "Nehru moved the Objectives Resolution, later reflected in the Preamble.", orderIndex: 6 },
  { id: "upsc-polity-making-of-the-constitution-q08", topicId: "upsc-polity-making-of-the-constitution", text: "The bulk of the federal scheme and administrative provisions came from the:", optionA: "Government of India Act, 1935", optionB: "US Constitution", optionC: "Irish Constitution", optionD: "Charter Act, 1833", correctOption: "A", explanation: "The Government of India Act, 1935 supplied the federal structure and many administrative details.", orderIndex: 7 },
  { id: "upsc-polity-making-of-the-constitution-q09", topicId: "upsc-polity-making-of-the-constitution", text: "Fundamental Duties were inspired by the Constitution of:", optionA: "the USSR", optionB: "the USA", optionC: "Ireland", optionD: "Australia", correctOption: "A", explanation: "Fundamental Duties were borrowed from the erstwhile USSR (Soviet) Constitution.", orderIndex: 8 },
  { id: "upsc-polity-making-of-the-constitution-q10", topicId: "upsc-polity-making-of-the-constitution", text: "The Constitution was adopted by the Constituent Assembly on:", optionA: "26 November 1949", optionB: "26 January 1950", optionC: "15 August 1947", optionD: "2 October 1949", correctOption: "A", explanation: "The Constitution was adopted on 26 November 1949, now marked as Constitution Day.", orderIndex: 9 },
  { id: "upsc-polity-making-of-the-constitution-q11", topicId: "upsc-polity-making-of-the-constitution", text: "In the Kesavananda Bharati case, the Preamble was held to be:", optionA: "A part of the Constitution", optionB: "Not a part of the Constitution", optionC: "Superior to the Constitution", optionD: "Legally unenforceable and separate", correctOption: "A", explanation: "Kesavananda Bharati (1973) held the Preamble is a part of the Constitution, reversing Berubari.", orderIndex: 10 },
  { id: "upsc-polity-making-of-the-constitution-q12", topicId: "upsc-polity-making-of-the-constitution", text: "The parliamentary form of government was adopted mainly from:", optionA: "Britain", optionB: "the USA", optionC: "France", optionD: "Switzerland", correctOption: "A", explanation: "India's parliamentary system, rule of law, and single citizenship follow the British model.", orderIndex: 11 },

  // ── Polity: Elections & Representation of the People ──
  { id: "upsc-polity-elections-and-representation-q01", topicId: "upsc-polity-elections-and-representation", text: "The Election Commission of India is established under which article?", optionA: "Article 324", optionB: "Article 280", optionC: "Article 148", optionD: "Article 315", correctOption: "A", explanation: "Article 324 vests the superintendence of elections in the Election Commission of India.", orderIndex: 0 },
  { id: "upsc-polity-elections-and-representation-q02", topicId: "upsc-polity-elections-and-representation", text: "The system used to elect members of the Lok Sabha is:", optionA: "First-Past-The-Post", optionB: "Proportional representation", optionC: "Single transferable vote", optionD: "List system", correctOption: "A", explanation: "Lok Sabha and Assembly members are elected by the First-Past-The-Post system.", orderIndex: 1 },
  { id: "upsc-polity-elections-and-representation-q03", topicId: "upsc-polity-elections-and-representation", text: "The voting age in India was lowered from 21 to 18 by which amendment?", optionA: "61st Amendment (1989)", optionB: "42nd Amendment", optionC: "44th Amendment", optionD: "73rd Amendment", correctOption: "A", explanation: "The 61st Amendment (1989) lowered the voting age to 18 years.", orderIndex: 2 },
  { id: "upsc-polity-elections-and-representation-q04", topicId: "upsc-polity-elections-and-representation", text: "The set of norms that becomes operational once elections are announced is the:", optionA: "Model Code of Conduct", optionB: "Whip", optionC: "Anti-Defection Law", optionD: "Money Bill rule", correctOption: "A", explanation: "The Model Code of Conduct governs parties and candidates once elections are notified.", orderIndex: 3 },
  { id: "upsc-polity-elections-and-representation-q05", topicId: "upsc-polity-elections-and-representation", text: "The conduct of elections is chiefly governed by the:", optionA: "Representation of the People Acts (1950/1951)", optionB: "Indian Penal Code", optionC: "Contract Act", optionD: "RTI Act", correctOption: "A", explanation: "The Representation of the People Acts, 1950 and 1951 govern electoral rolls and the conduct of elections.", orderIndex: 4 },
  { id: "upsc-polity-elections-and-representation-q06", topicId: "upsc-polity-elections-and-representation", text: "The NOTA (None of the Above) option was introduced in Indian elections in:", optionA: "2013", optionB: "1999", optionC: "2004", optionD: "2019", correctOption: "A", explanation: "The Supreme Court ordered the NOTA option, introduced in 2013.", orderIndex: 5 },
  { id: "upsc-polity-elections-and-representation-q07", topicId: "upsc-polity-elections-and-representation", text: "Members of the Rajya Sabha are elected by:", optionA: "Proportional representation by single transferable vote", optionB: "Direct election", optionC: "First-Past-The-Post", optionD: "Nomination only", correctOption: "A", explanation: "Rajya Sabha members are elected by state legislators using proportional representation (STV).", orderIndex: 6 },
  { id: "upsc-polity-elections-and-representation-q08", topicId: "upsc-polity-elections-and-representation", text: "The device that lets a voter verify their vote was recorded correctly is the:", optionA: "VVPAT", optionB: "EVM only", optionC: "Ballot box", optionD: "NOTA", correctOption: "A", explanation: "The Voter-Verifiable Paper Audit Trail (VVPAT) prints a slip confirming the vote.", orderIndex: 7 },
  { id: "upsc-polity-elections-and-representation-q09", topicId: "upsc-polity-elections-and-representation", text: "The Chief Election Commissioner can be removed from office in the manner of a:", optionA: "Supreme Court judge", optionB: "Governor", optionC: "Cabinet minister", optionD: "Civil servant", correctOption: "A", explanation: "The CEC can be removed only through the process used for a Supreme Court judge, ensuring independence.", orderIndex: 8 },
  { id: "upsc-polity-elections-and-representation-q10", topicId: "upsc-polity-elections-and-representation", text: "The electoral bonds scheme for political funding was struck down in 2024 by the:", optionA: "Supreme Court", optionB: "Election Commission", optionC: "Parliament", optionD: "RBI", correctOption: "A", explanation: "The Supreme Court struck down the electoral bonds scheme as unconstitutional in 2024.", orderIndex: 9 },
  { id: "upsc-polity-elections-and-representation-q11", topicId: "upsc-polity-elections-and-representation", text: "The right of every adult citizen to vote regardless of status is called:", optionA: "Universal adult franchise", optionB: "Restricted suffrage", optionC: "Proportional voting", optionD: "Weighted voting", correctOption: "A", explanation: "Universal adult franchise gives every adult citizen the right to vote, a hallmark of Indian democracy.", orderIndex: 10 },
  { id: "upsc-polity-elections-and-representation-q12", topicId: "upsc-polity-elections-and-representation", text: "The proposal to hold simultaneous Lok Sabha and Assembly elections is popularly called:", optionA: "One Nation, One Election", optionB: "One Nation, One Tax", optionC: "One Nation, One Ration Card", optionD: "One Nation, One Grid", correctOption: "A", explanation: "'One Nation, One Election' proposes holding Lok Sabha and state Assembly polls together.", orderIndex: 11 },

  // ── Polity: Anti-Defection & Parliamentary Committees ──
  { id: "upsc-polity-anti-defection-and-committees-q01", topicId: "upsc-polity-anti-defection-and-committees", text: "The Anti-Defection Law is contained in which schedule of the Constitution?", optionA: "Tenth Schedule", optionB: "Seventh Schedule", optionC: "Ninth Schedule", optionD: "Fifth Schedule", correctOption: "A", explanation: "The Anti-Defection Law is in the Tenth Schedule, added by the 52nd Amendment (1985).", orderIndex: 0 },
  { id: "upsc-polity-anti-defection-and-committees-q02", topicId: "upsc-polity-anti-defection-and-committees", text: "The Anti-Defection Law was added by which amendment?", optionA: "52nd Amendment (1985)", optionB: "42nd Amendment", optionC: "44th Amendment", optionD: "73rd Amendment", correctOption: "A", explanation: "The 52nd Amendment (1985) introduced the anti-defection provisions.", orderIndex: 1 },
  { id: "upsc-polity-anti-defection-and-committees-q03", topicId: "upsc-polity-anti-defection-and-committees", text: "Under the anti-defection law, disqualification is decided by the:", optionA: "Presiding officer (Speaker/Chairman)", optionB: "President", optionC: "Supreme Court directly", optionD: "Election Commission", correctOption: "A", explanation: "The Speaker or Chairman decides on disqualification, subject to judicial review.", orderIndex: 2 },
  { id: "upsc-polity-anti-defection-and-committees-q04", topicId: "upsc-polity-anti-defection-and-committees", text: "The 91st Amendment (2003) removed the exemption for a party:", optionA: "Split", optionB: "Merger", optionC: "Alliance", optionD: "Coalition", correctOption: "A", explanation: "The 91st Amendment deleted the 'split' exemption, leaving only 'merger' (two-thirds) valid.", orderIndex: 3 },
  { id: "upsc-polity-anti-defection-and-committees-q05", topicId: "upsc-polity-anti-defection-and-committees", text: "The Public Accounts Committee (PAC) mainly examines the:", optionA: "Audited accounts and the CAG's reports", optionB: "Foreign policy", optionC: "Election disputes", optionD: "Judicial appointments", correctOption: "A", explanation: "The PAC scrutinises government spending using the CAG's audit reports.", orderIndex: 4 },
  { id: "upsc-polity-anti-defection-and-committees-q06", topicId: "upsc-polity-anti-defection-and-committees", text: "By convention, the Chairman of the Public Accounts Committee is from the:", optionA: "Opposition", optionB: "Ruling party", optionC: "Rajya Sabha only", optionD: "Council of Ministers", correctOption: "A", explanation: "By convention the PAC chair is from the Opposition, strengthening accountability.", orderIndex: 5 },
  { id: "upsc-polity-anti-defection-and-committees-q07", topicId: "upsc-polity-anti-defection-and-committees", text: "The committee often called the 'continuous economy committee' is the:", optionA: "Estimates Committee", optionB: "Public Accounts Committee", optionC: "Business Advisory Committee", optionD: "Rules Committee", correctOption: "A", explanation: "The Estimates Committee, examining budget estimates for economy, is called the 'continuous economy committee'.", orderIndex: 6 },
  { id: "upsc-polity-anti-defection-and-committees-q08", topicId: "upsc-polity-anti-defection-and-committees", text: "A directive by a party to its legislators on how to vote is called a:", optionA: "Whip", optionB: "Writ", optionC: "Warrant", optionD: "Motion", correctOption: "A", explanation: "A whip is a party directive on voting; defying it can attract disqualification.", orderIndex: 7 },
  { id: "upsc-polity-anti-defection-and-committees-q09", topicId: "upsc-polity-anti-defection-and-committees", text: "Committees that examine bills, budgets, and policy of specific ministries are the:", optionA: "Department-Related Standing Committees", optionB: "Ad hoc committees", optionC: "Select committees", optionD: "Privileges committees", correctOption: "A", explanation: "Department-Related Standing Committees (DRSCs) examine ministries' bills, budgets, and policies.", orderIndex: 8 },
  { id: "upsc-polity-anti-defection-and-committees-q10", topicId: "upsc-polity-anti-defection-and-committees", text: "The Committee on Public Undertakings scrutinises the working of:", optionA: "Public sector undertakings (PSUs)", optionB: "Private companies", optionC: "Foreign firms", optionD: "Cooperative banks", correctOption: "A", explanation: "The Committee on Public Undertakings reviews the accounts and working of PSUs.", orderIndex: 9 },
  { id: "upsc-polity-anti-defection-and-committees-q11", topicId: "upsc-polity-anti-defection-and-committees", text: "A temporary committee formed to examine a specific bill is an example of a(n):", optionA: "Ad hoc committee", optionB: "Standing committee", optionC: "Financial committee", optionD: "Constitutional body", correctOption: "A", explanation: "Ad hoc committees (like Select/Joint Committees on a bill) are temporary and task-specific.", orderIndex: 10 },
  { id: "upsc-polity-anti-defection-and-committees-q12", topicId: "upsc-polity-anti-defection-and-committees", text: "After the 91st Amendment, a valid defection escape requires a merger involving at least:", optionA: "Two-thirds of the members", optionB: "One-third of the members", optionC: "One-half of the members", optionD: "All the members", correctOption: "A", explanation: "A merger needs at least two-thirds of a legislature party's members to agree.", orderIndex: 11 },

  // ── Economy: Financial Markets & SEBI ──
  { id: "upsc-economy-financial-markets-and-sebi-q01", topicId: "upsc-economy-financial-markets-and-sebi", text: "The regulator of the securities market in India is:", optionA: "SEBI", optionB: "RBI", optionC: "IRDAI", optionD: "PFRDA", correctOption: "A", explanation: "The Securities and Exchange Board of India (SEBI) regulates the securities market.", orderIndex: 0 },
  { id: "upsc-economy-financial-markets-and-sebi-q02", topicId: "upsc-economy-financial-markets-and-sebi", text: "The market where new securities are issued for the first time is the:", optionA: "Primary market", optionB: "Secondary market", optionC: "Money market", optionD: "Forex market", correctOption: "A", explanation: "The primary market is where companies issue new securities (e.g., via IPOs).", orderIndex: 1 },
  { id: "upsc-economy-financial-markets-and-sebi-q03", topicId: "upsc-economy-financial-markets-and-sebi", text: "The first public sale of a company's shares is called a(n):", optionA: "IPO", optionB: "FPO only", optionC: "Buyback", optionD: "Rights issue", correctOption: "A", explanation: "An Initial Public Offering (IPO) is a company's first sale of shares to the public.", orderIndex: 2 },
  { id: "upsc-economy-financial-markets-and-sebi-q04", topicId: "upsc-economy-financial-markets-and-sebi", text: "The benchmark index of the Bombay Stock Exchange is the:", optionA: "Sensex", optionB: "Nifty", optionC: "Dow Jones", optionD: "Nikkei", correctOption: "A", explanation: "The Sensex is the BSE's benchmark index; the Nifty is the NSE's.", orderIndex: 3 },
  { id: "upsc-economy-financial-markets-and-sebi-q05", topicId: "upsc-economy-financial-markets-and-sebi", text: "The money market, dealing in short-term funds, is regulated by the:", optionA: "RBI", optionB: "SEBI", optionC: "IRDAI", optionD: "PFRDA", correctOption: "A", explanation: "The RBI regulates the money market (short-term instruments like T-bills and call money).", orderIndex: 4 },
  { id: "upsc-economy-financial-markets-and-sebi-q06", topicId: "upsc-economy-financial-markets-and-sebi", text: "Buying or selling shares based on unpublished price-sensitive information is:", optionA: "Insider trading", optionB: "Arbitrage", optionC: "Hedging", optionD: "Short selling", correctOption: "A", explanation: "Insider trading — using confidential information — is illegal and policed by SEBI.", orderIndex: 5 },
  { id: "upsc-economy-financial-markets-and-sebi-q07", topicId: "upsc-economy-financial-markets-and-sebi", text: "A pooled investment vehicle managed professionally is a:", optionA: "Mutual fund", optionB: "Treasury Bill", optionC: "Debenture", optionD: "Promissory note", correctOption: "A", explanation: "A mutual fund pools investors' money and invests it in a diversified portfolio.", orderIndex: 6 },
  { id: "upsc-economy-financial-markets-and-sebi-q08", topicId: "upsc-economy-financial-markets-and-sebi", text: "Holding shares in electronic rather than physical form is called:", optionA: "Dematerialisation", optionB: "Securitisation", optionC: "Nationalisation", optionD: "Amortisation", correctOption: "A", explanation: "Dematerialisation converts physical share certificates into electronic form (via NSDL/CDSL).", orderIndex: 7 },
  { id: "upsc-economy-financial-markets-and-sebi-q09", topicId: "upsc-economy-financial-markets-and-sebi", text: "A rising market marked by optimism is called a:", optionA: "Bull market", optionB: "Bear market", optionC: "Flat market", optionD: "Grey market", correctOption: "A", explanation: "A bull market denotes rising prices and investor optimism; a bear market is falling.", orderIndex: 8 },
  { id: "upsc-economy-financial-markets-and-sebi-q10", topicId: "upsc-economy-financial-markets-and-sebi", text: "The insurance sector in India is regulated by:", optionA: "IRDAI", optionB: "SEBI", optionC: "RBI", optionD: "PFRDA", correctOption: "A", explanation: "The Insurance Regulatory and Development Authority of India (IRDAI) regulates insurance.", orderIndex: 9 },
  { id: "upsc-economy-financial-markets-and-sebi-q11", topicId: "upsc-economy-financial-markets-and-sebi", text: "Financial contracts whose value derives from an underlying asset are:", optionA: "Derivatives", optionB: "Equities", optionC: "Fixed deposits", optionD: "Currency notes", correctOption: "A", explanation: "Derivatives (futures, options) derive their value from an underlying asset or index.", orderIndex: 10 },
  { id: "upsc-economy-financial-markets-and-sebi-q12", topicId: "upsc-economy-financial-markets-and-sebi", text: "Foreign investors buying Indian stocks and bonds without controlling stakes are classed as:", optionA: "Foreign Portfolio Investors (FPI)", optionB: "Foreign Direct Investors (FDI)", optionC: "NRIs only", optionD: "Sovereign funds only", correctOption: "A", explanation: "FPI (portfolio) investment is in securities without management control, unlike FDI.", orderIndex: 11 },

  // ── Economy: Planning & Economic Reforms ──
  { id: "upsc-economy-planning-and-economic-reforms-q01", topicId: "upsc-economy-planning-and-economic-reforms", text: "The Planning Commission of India was set up in:", optionA: "1950", optionB: "1947", optionC: "1935", optionD: "1991", correctOption: "A", explanation: "The Planning Commission was established in 1950 to formulate Five-Year Plans.", orderIndex: 0 },
  { id: "upsc-economy-planning-and-economic-reforms-q02", topicId: "upsc-economy-planning-and-economic-reforms", text: "India's Five-Year Plans were modelled partly on the planning experience of:", optionA: "the USSR", optionB: "the USA", optionC: "Japan", optionD: "Britain", correctOption: "A", explanation: "India's central planning drew on the Soviet (USSR) model of Five-Year Plans.", orderIndex: 1 },
  { id: "upsc-economy-planning-and-economic-reforms-q03", topicId: "upsc-economy-planning-and-economic-reforms", text: "The Second Five-Year Plan, stressing heavy industry, was based on the model of:", optionA: "P. C. Mahalanobis", optionB: "Amartya Sen", optionC: "Manmohan Singh", optionD: "Vakil and Brahmananda", correctOption: "A", explanation: "The Second Plan followed the Mahalanobis model emphasising heavy industry.", orderIndex: 2 },
  { id: "upsc-economy-planning-and-economic-reforms-q04", topicId: "upsc-economy-planning-and-economic-reforms", text: "The economic reforms of 1991 are collectively known as:", optionA: "LPG (Liberalisation, Privatisation, Globalisation)", optionB: "GST", optionC: "MGNREGA", optionD: "Green Revolution", correctOption: "A", explanation: "The 1991 reforms are called LPG — Liberalisation, Privatisation, and Globalisation.", orderIndex: 3 },
  { id: "upsc-economy-planning-and-economic-reforms-q05", topicId: "upsc-economy-planning-and-economic-reforms", text: "The 1991 reforms were triggered by a crisis in the:", optionA: "Balance of payments", optionB: "Monsoon", optionC: "Banking licences", optionD: "Stock market", correctOption: "A", explanation: "A severe 1991 balance-of-payments crisis forced India to liberalise.", orderIndex: 4 },
  { id: "upsc-economy-planning-and-economic-reforms-q06", topicId: "upsc-economy-planning-and-economic-reforms", text: "The Finance Minister who spearheaded the 1991 reforms was:", optionA: "Manmohan Singh", optionB: "P. Chidambaram", optionC: "Yashwant Sinha", optionD: "Pranab Mukherjee", correctOption: "A", explanation: "Manmohan Singh, as FM under PM Narasimha Rao, led the 1991 reforms.", orderIndex: 5 },
  { id: "upsc-economy-planning-and-economic-reforms-q07", topicId: "upsc-economy-planning-and-economic-reforms", text: "The Planning Commission was replaced in 2015 by:", optionA: "NITI Aayog", optionB: "the Finance Commission", optionC: "the RBI", optionD: "the CAG", correctOption: "A", explanation: "NITI Aayog replaced the Planning Commission in 2015 as a policy think tank.", orderIndex: 6 },
  { id: "upsc-economy-planning-and-economic-reforms-q08", topicId: "upsc-economy-planning-and-economic-reforms", text: "The restrictive pre-1991 regime of licences and permits was nicknamed the:", optionA: "Licence-Permit-Quota Raj", optionB: "Green Revolution", optionC: "Welfare State", optionD: "Mixed Economy Charter", correctOption: "A", explanation: "The pre-reform regime of pervasive controls was the 'Licence-Permit-Quota Raj'.", orderIndex: 7 },
  { id: "upsc-economy-planning-and-economic-reforms-q09", topicId: "upsc-economy-planning-and-economic-reforms", text: "NITI Aayog primarily functions as a:", optionA: "Policy think tank promoting cooperative federalism", optionB: "Fund-allocating body", optionC: "Tax collector", optionD: "Monetary authority", correctOption: "A", explanation: "Unlike the Planning Commission, NITI Aayog is an advisory think tank, not a fund allocator.", orderIndex: 8 },
  { id: "upsc-economy-planning-and-economic-reforms-q10", topicId: "upsc-economy-planning-and-economic-reforms", text: "The slow growth of the pre-1991 decades was pejoratively called the:", optionA: "Hindu rate of growth", optionB: "Great Leap", optionC: "Dragon growth", optionD: "Tiger economy", correctOption: "A", explanation: "The sluggish ~3-4% pre-reform growth was dubbed the 'Hindu rate of growth'.", orderIndex: 9 },
  { id: "upsc-economy-planning-and-economic-reforms-q11", topicId: "upsc-economy-planning-and-economic-reforms", text: "The 2016 law to resolve corporate insolvency in a time-bound manner is the:", optionA: "Insolvency and Bankruptcy Code", optionB: "Companies Act", optionC: "SARFAESI Act", optionD: "FEMA", correctOption: "A", explanation: "The Insolvency and Bankruptcy Code (IBC), 2016 provides a time-bound insolvency resolution process.", orderIndex: 10 },
  { id: "upsc-economy-planning-and-economic-reforms-q12", topicId: "upsc-economy-planning-and-economic-reforms", text: "The campaign for self-reliant domestic manufacturing is called:", optionA: "Atmanirbhar Bharat", optionB: "Garibi Hatao", optionC: "Look East", optionD: "Shining India", correctOption: "A", explanation: "'Atmanirbhar Bharat' (Self-Reliant India) promotes domestic manufacturing and self-reliance.", orderIndex: 11 },

  // ── Economy: Industry, Infrastructure & Investment ──
  { id: "upsc-economy-industry-and-infrastructure-q01", topicId: "upsc-economy-industry-and-infrastructure", text: "MSME stands for Micro, Small and Medium:", optionA: "Enterprises", optionB: "Exports", optionC: "Estates", optionD: "Economies", correctOption: "A", explanation: "MSME = Micro, Small and Medium Enterprises, a major source of employment.", orderIndex: 0 },
  { id: "upsc-economy-industry-and-infrastructure-q02", topicId: "upsc-economy-industry-and-infrastructure", text: "The scheme giving output-linked incentives to boost manufacturing is the:", optionA: "PLI scheme", optionB: "MGNREGA", optionC: "PM-KISAN", optionD: "Ujjwala scheme", correctOption: "A", explanation: "The Production-Linked Incentive (PLI) scheme rewards incremental manufacturing output.", orderIndex: 1 },
  { id: "upsc-economy-industry-and-infrastructure-q03", topicId: "upsc-economy-industry-and-infrastructure", text: "The flagship programme for developing highways is:", optionA: "Bharatmala", optionB: "Sagarmala", optionC: "UDAN", optionD: "BharatNet", correctOption: "A", explanation: "Bharatmala is the umbrella programme for highway and road development.", orderIndex: 2 },
  { id: "upsc-economy-industry-and-infrastructure-q04", topicId: "upsc-economy-industry-and-infrastructure", text: "The Sagarmala programme focuses on the development of:", optionA: "Ports and coastal economy", optionB: "Airports", optionC: "Rural roads", optionD: "Power plants", correctOption: "A", explanation: "Sagarmala aims at port-led development and modernising India's coastline.", orderIndex: 3 },
  { id: "upsc-economy-industry-and-infrastructure-q05", topicId: "upsc-economy-industry-and-infrastructure", text: "The UDAN scheme is aimed at improving:", optionA: "Regional air connectivity", optionB: "Rural broadband", optionC: "Urban housing", optionD: "River transport", correctOption: "A", explanation: "UDAN (Ude Desh ka Aam Naagrik) promotes affordable regional air connectivity.", orderIndex: 4 },
  { id: "upsc-economy-industry-and-infrastructure-q06", topicId: "upsc-economy-industry-and-infrastructure", text: "In infrastructure financing, BOT stands for:", optionA: "Build-Operate-Transfer", optionB: "Buy-Own-Trade", optionC: "Bond-Option-Trust", optionD: "Basic Output Target", correctOption: "A", explanation: "BOT (Build-Operate-Transfer) is a common PPP model for infrastructure projects.", orderIndex: 5 },
  { id: "upsc-economy-industry-and-infrastructure-q07", topicId: "upsc-economy-industry-and-infrastructure", text: "Partnerships between government and private firms for public projects are called:", optionA: "Public-Private Partnerships (PPP)", optionB: "Joint families", optionC: "Cooperatives", optionD: "Cartels", correctOption: "A", explanation: "PPPs share the costs, risks, and rewards of infrastructure between the public and private sectors.", orderIndex: 6 },
  { id: "upsc-economy-industry-and-infrastructure-q08", topicId: "upsc-economy-industry-and-infrastructure", text: "The 'eight core industries' index includes coal, crude oil, steel, cement, electricity and:", optionA: "Natural gas, refinery products, and fertilisers", optionB: "Textiles and food processing", optionC: "IT and telecom", optionD: "Banking and insurance", correctOption: "A", explanation: "The eight core industries are coal, crude oil, natural gas, refinery products, fertilisers, steel, cement, and electricity.", orderIndex: 7 },
  { id: "upsc-economy-industry-and-infrastructure-q09", topicId: "upsc-economy-industry-and-infrastructure", text: "The initiative for integrated infrastructure planning across ministries is:", optionA: "PM Gati Shakti", optionB: "Make in India", optionC: "Digital India", optionD: "Skill India", correctOption: "A", explanation: "PM Gati Shakti is a national master plan for coordinated, multimodal infrastructure planning.", orderIndex: 8 },
  { id: "upsc-economy-industry-and-infrastructure-q10", topicId: "upsc-economy-industry-and-infrastructure", text: "The programme to provide broadband to rural gram panchayats is:", optionA: "BharatNet", optionB: "Bharatmala", optionC: "Sagarmala", optionD: "AMRUT", correctOption: "A", explanation: "BharatNet aims to connect all gram panchayats with high-speed broadband.", orderIndex: 9 },
  { id: "upsc-economy-industry-and-infrastructure-q11", topicId: "upsc-economy-industry-and-infrastructure", text: "Long-term foreign investment in businesses with management interest is called:", optionA: "Foreign Direct Investment (FDI)", optionB: "Foreign Portfolio Investment", optionC: "External commercial borrowing", optionD: "Remittances", correctOption: "A", explanation: "FDI is long-term investment giving a lasting interest and often management control in a business.", orderIndex: 10 },
  { id: "upsc-economy-industry-and-infrastructure-q12", topicId: "upsc-economy-industry-and-infrastructure", text: "The Hybrid Annuity Model (HAM) is used to finance which kind of projects?", optionA: "Highways/infrastructure (a PPP variant)", optionB: "Agricultural loans", optionC: "Mutual funds", optionD: "Insurance policies", correctOption: "A", explanation: "HAM is a hybrid PPP model mixing government annuity and private investment for highways.", orderIndex: 11 }
];
