// UPSC depth expansion — Art & Culture, Environment, and Science & Technology
// (pass 4). Each of these three subjects had only three topics; this rounds
// them out with high-yield chapters, each with a study note and 12-question drill.
import type { AuthoredMaterial } from "./builder";
import type { Question, Topic } from "@jyotir/core";

export const exp4Topics: Topic[] = [
  // Art & Culture (existing max orderIndex = 2)
  { id: "upsc-art-and-culture-indian-music", subjectId: "upsc-art-and-culture", name: "Indian Music", slug: "indian-music", orderIndex: 3 },
  { id: "upsc-art-and-culture-literature-and-languages", subjectId: "upsc-art-and-culture", name: "Indian Literature & Languages", slug: "literature-and-languages", orderIndex: 4 },
  { id: "upsc-art-and-culture-heritage-festivals-and-fairs", subjectId: "upsc-art-and-culture", name: "Heritage, Festivals & Fairs", slug: "heritage-festivals-and-fairs", orderIndex: 5 },
  // Environment & Ecology (existing max orderIndex = 2)
  { id: "upsc-environment-laws-and-institutions", subjectId: "upsc-environment", name: "Environmental Laws & Institutions", slug: "laws-and-institutions", orderIndex: 3 },
  { id: "upsc-environment-protected-areas-and-wildlife", subjectId: "upsc-environment", name: "Protected Areas & Wildlife Conservation", slug: "protected-areas-and-wildlife", orderIndex: 4 },
  { id: "upsc-environment-pollution-and-waste-management", subjectId: "upsc-environment", name: "Pollution & Waste Management", slug: "pollution-and-waste-management", orderIndex: 5 },
  // Science & Technology (existing max orderIndex = 2)
  { id: "upsc-science-technology-it-computers-and-ai", subjectId: "upsc-science-technology", name: "IT, Computers & Artificial Intelligence", slug: "it-computers-and-ai", orderIndex: 3 },
  { id: "upsc-science-technology-nuclear-technology-and-energy", subjectId: "upsc-science-technology", name: "Nuclear Technology & Energy", slug: "nuclear-technology-and-energy", orderIndex: 4 },
  { id: "upsc-science-technology-health-diseases-and-vaccines", subjectId: "upsc-science-technology", name: "Health, Diseases & Vaccines", slug: "health-diseases-and-vaccines", orderIndex: 5 }
];

export const exp4Materials: AuthoredMaterial[] = [
  { id: "upsc-art-and-culture-indian-music-m01", topicId: "upsc-art-and-culture-indian-music", title: "Indian Music", content: `Indian classical music rests on **raga** (melodic framework) and **tala** (rhythmic cycle), rooted in the **Samaveda**. It has two great traditions. **Hindustani** (North Indian) music absorbed Persian influences and is more improvisational; key forms are **Dhrupad** (oldest, austere), **Khayal**, **Thumri**, and **Tarana**. Instruments include the **sitar, sarod, santoor, shehnai, tabla, and sarangi**. Legendary figures: **Tansen** (in Akbar's court), Ravi Shankar (sitar), Bismillah Khan (shehnai), Zakir Hussain (tabla).

**Carnatic** (South Indian) music is more devotional and composition-based, dominated by the **kriti**. Its 'Trinity' — **Tyagaraja, Muthuswami Dikshitar, and Syama Sastri** — shaped its repertoire. Instruments include the **veena, mridangam, ghatam, and violin** (adapted). The **72 melakarta** system organises its ragas. Beyond classical music, India has rich **folk traditions** (Baul of Bengal, Bhangra of Punjab, Lavani of Maharashtra) recognised in the national cultural fabric.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "upsc-art-and-culture-literature-and-languages-m01", topicId: "upsc-art-and-culture-literature-and-languages", title: "Indian Literature & Languages", content: `Indian literature spans **Sanskrit** classics — the **Vedas**, epics **Ramayana** (Valmiki) and **Mahabharata** (Vyasa, containing the Bhagavad Gita), Kalidasa's **Abhijnana Shakuntalam** and Meghaduta, and Kautilya's **Arthashastra** — through **Prakrit, Pali** (early Buddhist canon), and the great regional languages. Classical **Tamil** Sangam literature is among the oldest.

The Constitution's **Eighth Schedule** lists **22 scheduled languages**. India also recognises **Classical Languages** — Tamil (first, 2004), Sanskrit, Telugu, Kannada, Malayalam, Odia, and later additions — for their ancient, independent heritage. **Hindi** and **English** are the official languages of the Union. Indian writers have won global honours: **Rabindranath Tagore** won the **Nobel Prize in Literature (1913)** for *Gitanjali* and wrote India's national anthem; the **Jnanpith Award** is India's highest literary honour. Bhakti and Sufi poetry (Kabir, Tulsidas, Mirabai, Amir Khusrau) enriched vernacular literatures.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "upsc-art-and-culture-heritage-festivals-and-fairs-m01", topicId: "upsc-art-and-culture-heritage-festivals-and-fairs", title: "Heritage, Festivals & Fairs", content: `**UNESCO World Heritage Sites** in India (40+) include cultural sites — the **Taj Mahal**, Agra Fort, Ajanta and Ellora caves, Khajuraho, Hampi, Konark Sun Temple, Qutb Minar, the Sundarbans and Kaziranga (natural), and the **Western Ghats** and Great Himalayan National Park. UNESCO also recognises **Intangible Cultural Heritage** — Kutiyattam theatre, Vedic chanting, Ramlila, Kumbh Mela, Yoga, and Durga Puja of Kolkata.

**Festivals** reflect India's diversity: **Diwali, Holi, Dussehra, Onam** (Kerala), **Pongal/Makar Sankranti** (harvest), **Bihu** (Assam), **Baisakhi** (Punjab), Eid, Christmas, and Buddha Purnima. **Fairs** like the **Kumbh Mela** (world's largest gathering, rotating among Prayagraj, Haridwar, Ujjain, Nashik), the **Pushkar Camel Fair** (Rajasthan), and **Sonepur Mela** (Bihar) are of huge cultural significance. India's living traditions of dance, theatre (Koodiyattam, Yakshagana), puppetry, and handicrafts are protected through **Geographical Indication (GI) tags** and cultural institutions like the Sangeet Natak Akademi.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "upsc-environment-laws-and-institutions-m01", topicId: "upsc-environment-laws-and-institutions", title: "Environmental Laws & Institutions", content: `India's environmental framework flows from the Constitution — **Article 48A** (Directive Principle: protect the environment) and **Article 51A(g)** (Fundamental Duty of citizens). Key laws: the **Wildlife (Protection) Act, 1972** (national parks, sanctuaries, schedules of protected species), the **Water Act, 1974** and **Air Act, 1981** (which set up the Pollution Control Boards), the umbrella **Environment (Protection) Act, 1986** (passed after the Bhopal tragedy), the **Forest (Conservation) Act, 1980**, and the **Forest Rights Act, 2006** (recognising forest-dweller rights).

**Institutions**: the **Central and State Pollution Control Boards (CPCB/SPCBs)** monitor pollution; the **National Green Tribunal (NGT)**, set up in 2010, gives speedy environmental justice; the **Ministry of Environment, Forest and Climate Change** grants clearances via **Environmental Impact Assessment (EIA)**. Landmark judicial doctrines include the **Polluter Pays Principle**, the **Precautionary Principle**, and the **Public Trust Doctrine**. **Project Tiger (1973)** and **Project Elephant (1992)** are flagship species-conservation programmes.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "upsc-environment-protected-areas-and-wildlife-m01", topicId: "upsc-environment-protected-areas-and-wildlife", title: "Protected Areas & Wildlife Conservation", content: `India's protected-area network (under the Wildlife Protection Act) includes **National Parks**, **Wildlife Sanctuaries**, **Conservation and Community Reserves**, **Biosphere Reserves** (many in UNESCO's MAB network, e.g., Nilgiri, Nanda Devi, Sundarbans), and **Tiger and Elephant Reserves**. Wetlands of international importance are protected as **Ramsar Sites** (India has 80+, including Chilika, Keoladeo, and Loktak).

**Flagship species and habitats**: the **Bengal tiger** (Jim Corbett was India's first national park, 1936; Project Tiger monitors reserves like Bandhavgarh, Ranthambore, Sundarbans); the **one-horned rhinoceros** (Kaziranga, Assam); the **Asiatic lion** (only in **Gir**, Gujarat); and the **Great Indian Bustard** (critically endangered). The **IUCN Red List** classifies species (Least Concern → Near Threatened → Vulnerable → Endangered → Critically Endangered → Extinct). India is a signatory to the **CBD**, **CITES** (regulating wildlife trade), and the **Convention on Migratory Species (CMS)**, and hosts many **biodiversity hotspots** (Himalaya, Western Ghats, Indo-Burma, Sundaland).`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "upsc-environment-pollution-and-waste-management-m01", topicId: "upsc-environment-pollution-and-waste-management", title: "Pollution & Waste Management", content: `**Air pollution** is measured by the **Air Quality Index (AQI)** across parameters (PM2.5, PM10, NO₂, SO₂, CO, O₃); the **National Clean Air Programme (NCAP)** targets reductions in polluted cities. Vehicular norms progressed to **Bharat Stage VI (BS-VI)**. **Water pollution** is worsened by sewage and industrial effluents; flagship clean-up efforts include the **Namami Gange** programme. Nutrient runoff causes **eutrophication**, and high **BOD** indicates organic pollution.

**Solid waste**: rules mandate **segregation** into biodegradable (wet) and non-biodegradable (dry). **Plastic pollution** is tackled by bans on single-use plastics and **Extended Producer Responsibility (EPR)**. **E-waste** and **hazardous waste** have dedicated rules. The **circular economy** and **3 Rs (Reduce, Reuse, Recycle)** guide sustainable management. The **Swachh Bharat Mission** promotes sanitation and waste management. Landmark disasters — the **Bhopal Gas Tragedy (1984, methyl isocyanate)** and Minamata (mercury, Japan) — shaped modern pollution law and the drive toward cleaner technology.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "upsc-science-technology-it-computers-and-ai-m01", topicId: "upsc-science-technology-it-computers-and-ai", title: "IT, Computers & Artificial Intelligence", content: `A **computer** processes data using the **CPU** (control unit + ALU), **memory** (volatile RAM, non-volatile ROM/storage), and input/output devices; it works in **binary** (bits and bytes). **Software** is system (operating systems like Linux, Windows) or application. The **Internet** connects networks via protocols (**TCP/IP, HTTP, DNS**); the **cloud** delivers computing on demand (IaaS, PaaS, SaaS).

**Emerging technologies**: **Artificial Intelligence (AI)** enables machines to learn (**machine learning**, **deep learning** via neural networks) and power applications from language models to vision. **Big Data** analytics, the **Internet of Things (IoT)**, **blockchain** (a decentralised, tamper-evident ledger behind cryptocurrencies), **5G**, and **quantum computing** (using qubits and superposition) are frontier areas. India's **Digital India** push includes **Aadhaar** (biometric ID), the **UPI** real-time payments system, and **DigiLocker**. Governance challenges include **data privacy** (the Digital Personal Data Protection Act, 2023), cybersecurity, the digital divide, and the ethics of AI.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "upsc-science-technology-nuclear-technology-and-energy-m01", topicId: "upsc-science-technology-nuclear-technology-and-energy", title: "Nuclear Technology & Energy", content: `Nuclear energy releases the binding energy of the atom. **Fission** splits heavy nuclei (uranium-235, plutonium-239) in a chain reaction, used in reactors and bombs; **fusion** joins light nuclei (as in the Sun and hydrogen bombs) and is the goal of projects like **ITER**. Reactors use **fuel, moderators** (slow neutrons — heavy water or graphite), **control rods** (absorb neutrons — cadmium/boron), and coolant.

India's programme, led by **Homi Bhabha**, follows a **three-stage plan**: (1) Pressurised Heavy Water Reactors using **natural uranium**; (2) **Fast Breeder Reactors** using plutonium to breed more fuel; (3) reactors using India's vast **thorium** reserves (from Kerala's monazite sands). Bodies include the **Department of Atomic Energy (DAE)**, **BARC**, and **NPCIL**; plants operate at Tarapur, Kudankulam, Kaiga, and Rawatbhata. India is not a signatory to the **NPT** but got a **waiver** via the 2008 **Indo-US Nuclear Deal** and is a member of the MTCR, Wassenaar, and Australia Group (though not the NSG). Renewable energy — **solar** (International Solar Alliance, headquartered in India), wind, and green hydrogen — is expanding rapidly toward India's net-zero-by-2070 goal.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "upsc-science-technology-health-diseases-and-vaccines-m01", topicId: "upsc-science-technology-health-diseases-and-vaccines", title: "Health, Diseases & Vaccines", content: `Diseases are **communicable** (infectious — caused by bacteria, viruses, protozoa, fungi, worms) or **non-communicable** (lifestyle — diabetes, cancer, cardiovascular disease). Major infectious diseases include **tuberculosis, malaria** (protozoan *Plasmodium*, spread by the female *Anopheles* mosquito), **dengue** (*Aedes* mosquito), **HIV/AIDS**, and **COVID-19** (SARS-CoV-2). India eradicated **smallpox** and was declared **polio-free (2014)** through mass immunisation.

**Vaccines** train the immune system using weakened, inactivated, subunit, or **mRNA** platforms; they confer active immunity and can achieve **herd immunity**. India runs the **Universal Immunisation Programme** and **Mission Indradhanush**, and is a global vaccine manufacturer (the Serum Institute is the world's largest by volume; **Covaxin** and Covishield were used against COVID-19). **Antibiotics** treat bacterial (not viral) infections; their overuse drives **antimicrobial resistance (AMR)**, a major global threat. Public health schemes include **Ayushman Bharat** (health insurance + wellness centres) and the goal of **Universal Health Coverage**; the **WHO** coordinates global health.`, estimatedReadTime: 2, orderIndex: 0 }
];

export const exp4Questions: Question[] = [
  // ── Art & Culture: Indian Music ──
  { id: "upsc-art-and-culture-indian-music-q01", topicId: "upsc-art-and-culture-indian-music", text: "The melodic framework of Indian classical music is called:", optionA: "Raga", optionB: "Tala", optionC: "Kriti", optionD: "Gharana", correctOption: "A", explanation: "A raga is the melodic mode; tala is the rhythmic cycle.", orderIndex: 0 },
  { id: "upsc-art-and-culture-indian-music-q02", topicId: "upsc-art-and-culture-indian-music", text: "The rhythmic cycle in Indian classical music is known as:", optionA: "Tala", optionB: "Raga", optionC: "Alap", optionD: "Sur", correctOption: "A", explanation: "Tala is the metrical/rhythmic cycle marked by beats.", orderIndex: 1 },
  { id: "upsc-art-and-culture-indian-music-q03", topicId: "upsc-art-and-culture-indian-music", text: "Indian music traces its origins to which Veda?", optionA: "Samaveda", optionB: "Rigveda", optionC: "Yajurveda", optionD: "Atharvaveda", correctOption: "A", explanation: "The Samaveda, meant for melodic chanting, is the root of Indian music.", orderIndex: 2 },
  { id: "upsc-art-and-culture-indian-music-q04", topicId: "upsc-art-and-culture-indian-music", text: "The oldest and most austere form of Hindustani vocal music is:", optionA: "Dhrupad", optionB: "Khayal", optionC: "Thumri", optionD: "Ghazal", correctOption: "A", explanation: "Dhrupad is the oldest, most austere genre of Hindustani classical vocal music.", orderIndex: 3 },
  { id: "upsc-art-and-culture-indian-music-q05", topicId: "upsc-art-and-culture-indian-music", text: "The legendary musician in Akbar's court was:", optionA: "Tansen", optionB: "Amir Khusrau", optionC: "Baiju Bawra", optionD: "Swami Haridas", correctOption: "A", explanation: "Tansen, one of Akbar's Navaratnas, was a legendary Hindustani musician.", orderIndex: 4 },
  { id: "upsc-art-and-culture-indian-music-q06", topicId: "upsc-art-and-culture-indian-music", text: "The main composition form of Carnatic music is the:", optionA: "Kriti", optionB: "Khayal", optionC: "Dhrupad", optionD: "Tarana", correctOption: "A", explanation: "The kriti is the principal composition form in Carnatic music.", orderIndex: 5 },
  { id: "upsc-art-and-culture-indian-music-q07", topicId: "upsc-art-and-culture-indian-music", text: "Tyagaraja, Muthuswami Dikshitar, and Syama Sastri are known as the:", optionA: "Trinity of Carnatic music", optionB: "Trinity of Hindustani music", optionC: "Tansen's disciples", optionD: "Bhakti poets", correctOption: "A", explanation: "They are revered as the Trinity of Carnatic music.", orderIndex: 6 },
  { id: "upsc-art-and-culture-indian-music-q08", topicId: "upsc-art-and-culture-indian-music", text: "Which instrument did Pandit Ravi Shankar make world-famous?", optionA: "Sitar", optionB: "Tabla", optionC: "Shehnai", optionD: "Veena", correctOption: "A", explanation: "Ravi Shankar was a globally renowned sitar maestro.", orderIndex: 7 },
  { id: "upsc-art-and-culture-indian-music-q09", topicId: "upsc-art-and-culture-indian-music", text: "The shehnai is most associated with which maestro?", optionA: "Bismillah Khan", optionB: "Zakir Hussain", optionC: "Hariprasad Chaurasia", optionD: "Amjad Ali Khan", correctOption: "A", explanation: "Ustad Bismillah Khan was the doyen of the shehnai.", orderIndex: 8 },
  { id: "upsc-art-and-culture-indian-music-q10", topicId: "upsc-art-and-culture-indian-music", text: "The veena and mridangam are chiefly instruments of which tradition?", optionA: "Carnatic music", optionB: "Hindustani music", optionC: "Sufi qawwali", optionD: "Folk music", correctOption: "A", explanation: "The veena and mridangam are central to Carnatic music.", orderIndex: 9 },
  { id: "upsc-art-and-culture-indian-music-q11", topicId: "upsc-art-and-culture-indian-music", text: "The 72 'melakarta' system is used to classify ragas in:", optionA: "Carnatic music", optionB: "Hindustani music", optionC: "Western classical music", optionD: "Folk music", correctOption: "A", explanation: "The melakarta system organises the parent ragas of Carnatic music.", orderIndex: 10 },
  { id: "upsc-art-and-culture-indian-music-q12", topicId: "upsc-art-and-culture-indian-music", text: "The Baul tradition is a folk music form from:", optionA: "Bengal", optionB: "Punjab", optionC: "Rajasthan", optionD: "Kerala", correctOption: "A", explanation: "The Baul are mystic minstrels of Bengal, recognised by UNESCO.", orderIndex: 11 },

  // ── Art & Culture: Indian Literature & Languages ──
  { id: "upsc-art-and-culture-literature-and-languages-q01", topicId: "upsc-art-and-culture-literature-and-languages", text: "The epic Ramayana is traditionally attributed to:", optionA: "Valmiki", optionB: "Vyasa", optionC: "Kalidasa", optionD: "Tulsidas", correctOption: "A", explanation: "Valmiki composed the Sanskrit Ramayana; Vyasa is credited with the Mahabharata.", orderIndex: 0 },
  { id: "upsc-art-and-culture-literature-and-languages-q02", topicId: "upsc-art-and-culture-literature-and-languages", text: "The play Abhijnana Shakuntalam was written by:", optionA: "Kalidasa", optionB: "Banabhatta", optionC: "Bhasa", optionD: "Sudraka", correctOption: "A", explanation: "Kalidasa, the great Sanskrit poet-dramatist, wrote Abhijnana Shakuntalam.", orderIndex: 1 },
  { id: "upsc-art-and-culture-literature-and-languages-q03", topicId: "upsc-art-and-culture-literature-and-languages", text: "The Arthashastra, a treatise on statecraft, was written by:", optionA: "Kautilya (Chanakya)", optionB: "Kalidasa", optionC: "Panini", optionD: "Patanjali", correctOption: "A", explanation: "Kautilya (Chanakya) authored the Arthashastra on polity and economy.", orderIndex: 2 },
  { id: "upsc-art-and-culture-literature-and-languages-q04", topicId: "upsc-art-and-culture-literature-and-languages", text: "How many languages are listed in the Eighth Schedule of the Constitution?", optionA: "22", optionB: "14", optionC: "18", optionD: "28", correctOption: "A", explanation: "The Eighth Schedule currently lists 22 scheduled languages.", orderIndex: 3 },
  { id: "upsc-art-and-culture-literature-and-languages-q05", topicId: "upsc-art-and-culture-literature-and-languages", text: "The first language to be granted 'Classical Language' status in India (2004) was:", optionA: "Tamil", optionB: "Sanskrit", optionC: "Telugu", optionD: "Kannada", correctOption: "A", explanation: "Tamil was the first to be declared a Classical Language of India in 2004.", orderIndex: 4 },
  { id: "upsc-art-and-culture-literature-and-languages-q06", topicId: "upsc-art-and-culture-literature-and-languages", text: "Rabindranath Tagore won the Nobel Prize in Literature in 1913 for:", optionA: "Gitanjali", optionB: "Gora", optionC: "The Home and the World", optionD: "Kabuliwala", correctOption: "A", explanation: "Tagore won the 1913 Nobel Prize for his collection of poems Gitanjali.", orderIndex: 5 },
  { id: "upsc-art-and-culture-literature-and-languages-q07", topicId: "upsc-art-and-culture-literature-and-languages", text: "India's highest literary award is the:", optionA: "Jnanpith Award", optionB: "Bharat Ratna", optionC: "Padma Shri", optionD: "Sahitya Ratna", correctOption: "A", explanation: "The Jnanpith Award is India's highest literary honour.", orderIndex: 6 },
  { id: "upsc-art-and-culture-literature-and-languages-q08", topicId: "upsc-art-and-culture-literature-and-languages", text: "The Bhagavad Gita is a part of which epic?", optionA: "Mahabharata", optionB: "Ramayana", optionC: "Raghuvamsa", optionD: "Meghaduta", correctOption: "A", explanation: "The Bhagavad Gita is a dialogue within the Mahabharata (Bhishma Parva).", orderIndex: 7 },
  { id: "upsc-art-and-culture-literature-and-languages-q09", topicId: "upsc-art-and-culture-literature-and-languages", text: "The Ramcharitmanas, a Hindi (Awadhi) retelling of the Ramayana, was written by:", optionA: "Tulsidas", optionB: "Surdas", optionC: "Kabir", optionD: "Mirabai", correctOption: "A", explanation: "Tulsidas wrote the Ramcharitmanas in the Awadhi dialect.", orderIndex: 8 },
  { id: "upsc-art-and-culture-literature-and-languages-q10", topicId: "upsc-art-and-culture-literature-and-languages", text: "The early Buddhist canonical texts were composed largely in which language?", optionA: "Pali", optionB: "Sanskrit", optionC: "Persian", optionD: "Tamil", correctOption: "A", explanation: "The Theravada Buddhist canon (Tripitaka) was composed in Pali.", orderIndex: 9 },
  { id: "upsc-art-and-culture-literature-and-languages-q11", topicId: "upsc-art-and-culture-literature-and-languages", text: "Amir Khusrau, credited with developing Hindavi and qawwali, was a disciple of the Sufi saint:", optionA: "Nizamuddin Auliya", optionB: "Moinuddin Chishti", optionC: "Baba Farid", optionD: "Salim Chishti", correctOption: "A", explanation: "Amir Khusrau was a devoted disciple of Nizamuddin Auliya of Delhi.", orderIndex: 10 },
  { id: "upsc-art-and-culture-literature-and-languages-q12", topicId: "upsc-art-and-culture-literature-and-languages", text: "The two official languages of the Union Government of India are:", optionA: "Hindi and English", optionB: "Hindi and Sanskrit", optionC: "English and Urdu", optionD: "Hindi and Tamil", correctOption: "A", explanation: "Hindi (in Devanagari) is the official language; English is the associate official language.", orderIndex: 11 },

  // ── Art & Culture: Heritage, Festivals & Fairs ──
  { id: "upsc-art-and-culture-heritage-festivals-and-fairs-q01", topicId: "upsc-art-and-culture-heritage-festivals-and-fairs", text: "The Taj Mahal, a UNESCO World Heritage Site, is located in:", optionA: "Agra", optionB: "Delhi", optionC: "Fatehpur Sikri", optionD: "Jaipur", correctOption: "A", explanation: "The Taj Mahal, built by Shah Jahan, is in Agra, Uttar Pradesh.", orderIndex: 0 },
  { id: "upsc-art-and-culture-heritage-festivals-and-fairs-q02", topicId: "upsc-art-and-culture-heritage-festivals-and-fairs", text: "The Ajanta and Ellora caves are located in which state?", optionA: "Maharashtra", optionB: "Madhya Pradesh", optionC: "Karnataka", optionD: "Odisha", correctOption: "A", explanation: "The Ajanta and Ellora rock-cut caves are in Maharashtra.", orderIndex: 1 },
  { id: "upsc-art-and-culture-heritage-festivals-and-fairs-q03", topicId: "upsc-art-and-culture-heritage-festivals-and-fairs", text: "The Sun Temple, a UNESCO site famous for its chariot form, is at:", optionA: "Konark", optionB: "Khajuraho", optionC: "Hampi", optionD: "Modhera", correctOption: "A", explanation: "The Konark Sun Temple in Odisha is designed as the Sun God's chariot.", orderIndex: 2 },
  { id: "upsc-art-and-culture-heritage-festivals-and-fairs-q04", topicId: "upsc-art-and-culture-heritage-festivals-and-fairs", text: "The Kumbh Mela, inscribed on UNESCO's Intangible Heritage list, rotates among how many cities?", optionA: "Four", optionB: "Two", optionC: "Six", optionD: "Eight", correctOption: "A", explanation: "The Kumbh Mela rotates among Prayagraj, Haridwar, Ujjain, and Nashik.", orderIndex: 3 },
  { id: "upsc-art-and-culture-heritage-festivals-and-fairs-q05", topicId: "upsc-art-and-culture-heritage-festivals-and-fairs", text: "Onam is the harvest festival primarily of which state?", optionA: "Kerala", optionB: "Tamil Nadu", optionC: "Assam", optionD: "Punjab", correctOption: "A", explanation: "Onam is Kerala's major harvest festival, marked by the Vamana-Mahabali legend.", orderIndex: 4 },
  { id: "upsc-art-and-culture-heritage-festivals-and-fairs-q06", topicId: "upsc-art-and-culture-heritage-festivals-and-fairs", text: "Bihu is a set of festivals celebrated in:", optionA: "Assam", optionB: "Odisha", optionC: "Gujarat", optionD: "Karnataka", correctOption: "A", explanation: "Bihu comprises the seasonal festivals of Assam.", orderIndex: 5 },
  { id: "upsc-art-and-culture-heritage-festivals-and-fairs-q07", topicId: "upsc-art-and-culture-heritage-festivals-and-fairs", text: "The famous Pushkar Camel Fair is held in:", optionA: "Rajasthan", optionB: "Gujarat", optionC: "Madhya Pradesh", optionD: "Haryana", correctOption: "A", explanation: "The Pushkar Fair, a major livestock and cultural fair, is held in Rajasthan.", orderIndex: 6 },
  { id: "upsc-art-and-culture-heritage-festivals-and-fairs-q08", topicId: "upsc-art-and-culture-heritage-festivals-and-fairs", text: "Which of these was inscribed as a UNESCO Intangible Cultural Heritage of India in 2016?", optionA: "Yoga", optionB: "The Taj Mahal", optionC: "Kaziranga", optionD: "Hampi", correctOption: "A", explanation: "Yoga was inscribed on UNESCO's Intangible Cultural Heritage list in 2016.", orderIndex: 7 },
  { id: "upsc-art-and-culture-heritage-festivals-and-fairs-q09", topicId: "upsc-art-and-culture-heritage-festivals-and-fairs", text: "Kaziranga National Park, a natural World Heritage Site, is famous for the:", optionA: "One-horned rhinoceros", optionB: "Asiatic lion", optionC: "Snow leopard", optionD: "Great Indian Bustard", correctOption: "A", explanation: "Kaziranga in Assam protects the one-horned rhinoceros.", orderIndex: 8 },
  { id: "upsc-art-and-culture-heritage-festivals-and-fairs-q10", topicId: "upsc-art-and-culture-heritage-festivals-and-fairs", text: "The tag protecting products of specific geographical origin (e.g., Darjeeling tea) is the:", optionA: "Geographical Indication (GI) tag", optionB: "Trademark", optionC: "Copyright", optionD: "Patent", correctOption: "A", explanation: "A GI tag protects goods with a specific geographical origin and reputation.", orderIndex: 9 },
  { id: "upsc-art-and-culture-heritage-festivals-and-fairs-q11", topicId: "upsc-art-and-culture-heritage-festivals-and-fairs", text: "Durga Puja of which city was inscribed on UNESCO's Intangible Heritage list in 2021?", optionA: "Kolkata", optionB: "Mumbai", optionC: "Chennai", optionD: "Varanasi", correctOption: "A", explanation: "Durga Puja in Kolkata was added to UNESCO's Intangible Cultural Heritage list in 2021.", orderIndex: 10 },
  { id: "upsc-art-and-culture-heritage-festivals-and-fairs-q12", topicId: "upsc-art-and-culture-heritage-festivals-and-fairs", text: "Yakshagana is a traditional theatre form of:", optionA: "Karnataka", optionB: "Kerala", optionC: "West Bengal", optionD: "Manipur", correctOption: "A", explanation: "Yakshagana is a folk theatre form of coastal Karnataka.", orderIndex: 11 },

  // ── Environment: Environmental Laws & Institutions ──
  { id: "upsc-environment-laws-and-institutions-q01", topicId: "upsc-environment-laws-and-institutions", text: "The umbrella environmental legislation passed after the Bhopal tragedy is the:", optionA: "Environment (Protection) Act, 1986", optionB: "Water Act, 1974", optionC: "Wildlife Protection Act, 1972", optionD: "Air Act, 1981", correctOption: "A", explanation: "The Environment (Protection) Act, 1986 was enacted following the Bhopal disaster.", orderIndex: 0 },
  { id: "upsc-environment-laws-and-institutions-q02", topicId: "upsc-environment-laws-and-institutions", text: "The National Green Tribunal (NGT) was established in:", optionA: "2010", optionB: "1986", optionC: "2000", optionD: "2016", correctOption: "A", explanation: "The NGT was set up under the NGT Act, 2010, for speedy environmental justice.", orderIndex: 1 },
  { id: "upsc-environment-laws-and-institutions-q03", topicId: "upsc-environment-laws-and-institutions", text: "Which Directive Principle enjoins the State to protect the environment?", optionA: "Article 48A", optionB: "Article 21", optionC: "Article 32", optionD: "Article 19", correctOption: "A", explanation: "Article 48A directs the State to protect and improve the environment.", orderIndex: 2 },
  { id: "upsc-environment-laws-and-institutions-q04", topicId: "upsc-environment-laws-and-institutions", text: "National parks and wildlife sanctuaries are governed by the:", optionA: "Wildlife (Protection) Act, 1972", optionB: "Forest Rights Act, 2006", optionC: "Air Act, 1981", optionD: "EPA, 1986", correctOption: "A", explanation: "The Wildlife (Protection) Act, 1972 provides for protected areas and species.", orderIndex: 3 },
  { id: "upsc-environment-laws-and-institutions-q05", topicId: "upsc-environment-laws-and-institutions", text: "The bodies set up under the Water Act (1974) to monitor pollution are the:", optionA: "Pollution Control Boards", optionB: "Panchayats", optionC: "Zila Parishads", optionD: "Gram Sabhas", correctOption: "A", explanation: "The Water Act created the Central and State Pollution Control Boards.", orderIndex: 4 },
  { id: "upsc-environment-laws-and-institutions-q06", topicId: "upsc-environment-laws-and-institutions", text: "Project Tiger was launched in:", optionA: "1973", optionB: "1992", optionC: "1986", optionD: "2006", correctOption: "A", explanation: "Project Tiger, India's flagship tiger-conservation programme, began in 1973.", orderIndex: 5 },
  { id: "upsc-environment-laws-and-institutions-q07", topicId: "upsc-environment-laws-and-institutions", text: "The principle that the person causing pollution should bear its cost is the:", optionA: "Polluter Pays Principle", optionB: "Precautionary Principle", optionC: "Public Trust Doctrine", optionD: "Sustainable Yield", correctOption: "A", explanation: "The Polluter Pays Principle makes polluters bear the cost of the damage they cause.", orderIndex: 6 },
  { id: "upsc-environment-laws-and-institutions-q08", topicId: "upsc-environment-laws-and-institutions", text: "The process to assess a project's likely environmental effects before clearance is the:", optionA: "Environmental Impact Assessment (EIA)", optionB: "GDP calculation", optionC: "Census", optionD: "Social audit", correctOption: "A", explanation: "EIA evaluates the environmental consequences of a proposed project before approval.", orderIndex: 7 },
  { id: "upsc-environment-laws-and-institutions-q09", topicId: "upsc-environment-laws-and-institutions", text: "The Forest Rights Act was passed in:", optionA: "2006", optionB: "1980", optionC: "1972", optionD: "1996", correctOption: "A", explanation: "The Scheduled Tribes and Other Traditional Forest Dwellers (Recognition of Forest Rights) Act was passed in 2006.", orderIndex: 8 },
  { id: "upsc-environment-laws-and-institutions-q10", topicId: "upsc-environment-laws-and-institutions", text: "The Fundamental Duty to protect the natural environment is under:", optionA: "Article 51A(g)", optionB: "Article 21", optionC: "Article 48A", optionD: "Article 39", correctOption: "A", explanation: "Article 51A(g) makes protecting the environment a Fundamental Duty of citizens.", orderIndex: 9 },
  { id: "upsc-environment-laws-and-institutions-q11", topicId: "upsc-environment-laws-and-institutions", text: "Diversion of forest land for non-forest use is regulated by the:", optionA: "Forest (Conservation) Act, 1980", optionB: "Air Act, 1981", optionC: "Water Act, 1974", optionD: "Wildlife Act, 1972", correctOption: "A", explanation: "The Forest (Conservation) Act, 1980 requires central approval to divert forest land.", orderIndex: 10 },
  { id: "upsc-environment-laws-and-institutions-q12", topicId: "upsc-environment-laws-and-institutions", text: "The principle requiring caution when an activity's harm is scientifically uncertain is the:", optionA: "Precautionary Principle", optionB: "Polluter Pays Principle", optionC: "Absolute Liability", optionD: "Sustainable Yield", correctOption: "A", explanation: "The Precautionary Principle urges preventive action under scientific uncertainty.", orderIndex: 11 },

  // ── Environment: Protected Areas & Wildlife Conservation ──
  { id: "upsc-environment-protected-areas-and-wildlife-q01", topicId: "upsc-environment-protected-areas-and-wildlife", text: "India's first national park (1936) is now known as:", optionA: "Jim Corbett National Park", optionB: "Kaziranga National Park", optionC: "Gir National Park", optionD: "Ranthambore National Park", correctOption: "A", explanation: "Established in 1936 as Hailey National Park, it is now Jim Corbett National Park.", orderIndex: 0 },
  { id: "upsc-environment-protected-areas-and-wildlife-q02", topicId: "upsc-environment-protected-areas-and-wildlife", text: "The Asiatic lion is found in the wild only in:", optionA: "Gir (Gujarat)", optionB: "Kaziranga (Assam)", optionC: "Sundarbans (West Bengal)", optionD: "Ranthambore (Rajasthan)", correctOption: "A", explanation: "The last wild Asiatic lions survive in Gir National Park, Gujarat.", orderIndex: 1 },
  { id: "upsc-environment-protected-areas-and-wildlife-q03", topicId: "upsc-environment-protected-areas-and-wildlife", text: "Wetlands of international importance are designated under which convention?", optionA: "Ramsar Convention", optionB: "CITES", optionC: "Kyoto Protocol", optionD: "Montreal Protocol", correctOption: "A", explanation: "The Ramsar Convention designates wetlands of international importance.", orderIndex: 2 },
  { id: "upsc-environment-protected-areas-and-wildlife-q04", topicId: "upsc-environment-protected-areas-and-wildlife", text: "The convention that regulates international trade in endangered species is:", optionA: "CITES", optionB: "CBD", optionC: "UNFCCC", optionD: "Ramsar", correctOption: "A", explanation: "CITES regulates and restricts trade in endangered species of flora and fauna.", orderIndex: 3 },
  { id: "upsc-environment-protected-areas-and-wildlife-q05", topicId: "upsc-environment-protected-areas-and-wildlife", text: "The IUCN Red List category just above 'Endangered' in threat level is:", optionA: "Critically Endangered", optionB: "Vulnerable", optionC: "Near Threatened", optionD: "Least Concern", correctOption: "A", explanation: "The order of increasing threat is Vulnerable → Endangered → Critically Endangered.", orderIndex: 4 },
  { id: "upsc-environment-protected-areas-and-wildlife-q06", topicId: "upsc-environment-protected-areas-and-wildlife", text: "Which of these is a globally recognised biodiversity hotspot in India?", optionA: "The Western Ghats", optionB: "The Thar Desert", optionC: "The Deccan plateau", optionD: "The Gangetic plain", correctOption: "A", explanation: "The Western Ghats are one of the world's biodiversity hotspots.", orderIndex: 5 },
  { id: "upsc-environment-protected-areas-and-wildlife-q07", topicId: "upsc-environment-protected-areas-and-wildlife", text: "The critically endangered Great Indian Bustard is the state bird of:", optionA: "Rajasthan", optionB: "Kerala", optionC: "Assam", optionD: "Punjab", correctOption: "A", explanation: "The Great Indian Bustard, critically endangered, is Rajasthan's state bird.", orderIndex: 6 },
  { id: "upsc-environment-protected-areas-and-wildlife-q08", topicId: "upsc-environment-protected-areas-and-wildlife", text: "Biosphere reserves in India that are internationally recognised are part of UNESCO's:", optionA: "Man and the Biosphere (MAB) Programme", optionB: "World Food Programme", optionC: "Green Climate Fund", optionD: "Global Environment Facility", correctOption: "A", explanation: "Recognised biosphere reserves belong to UNESCO's Man and the Biosphere network.", orderIndex: 7 },
  { id: "upsc-environment-protected-areas-and-wildlife-q09", topicId: "upsc-environment-protected-areas-and-wildlife", text: "The Sundarbans, a UNESCO site and tiger habitat, is a large:", optionA: "Mangrove forest", optionB: "Coral reef", optionC: "Alpine meadow", optionD: "Desert", correctOption: "A", explanation: "The Sundarbans is the world's largest mangrove forest, shared by India and Bangladesh.", orderIndex: 8 },
  { id: "upsc-environment-protected-areas-and-wildlife-q10", topicId: "upsc-environment-protected-areas-and-wildlife", text: "In a wildlife sanctuary, as compared with a national park, human activities are:", optionA: "Somewhat permitted (limited)", optionB: "Completely banned", optionC: "Unrestricted", optionD: "Encouraged commercially", correctOption: "A", explanation: "Sanctuaries allow certain regulated human activities; national parks are stricter.", orderIndex: 9 },
  { id: "upsc-environment-protected-areas-and-wildlife-q11", topicId: "upsc-environment-protected-areas-and-wildlife", text: "Keoladeo National Park, a famous Ramsar site for migratory birds, is in:", optionA: "Rajasthan", optionB: "Gujarat", optionC: "Odisha", optionD: "Assam", correctOption: "A", explanation: "Keoladeo (Bharatpur) in Rajasthan is a renowned bird sanctuary and Ramsar site.", orderIndex: 10 },
  { id: "upsc-environment-protected-areas-and-wildlife-q12", topicId: "upsc-environment-protected-areas-and-wildlife", text: "Project Elephant was launched to protect elephants in the year:", optionA: "1992", optionB: "1973", optionC: "2006", optionD: "1986", correctOption: "A", explanation: "Project Elephant was launched in 1992 to conserve elephants and their habitats.", orderIndex: 11 },

  // ── Environment: Pollution & Waste Management ──
  { id: "upsc-environment-pollution-and-waste-management-q01", topicId: "upsc-environment-pollution-and-waste-management", text: "The Air Quality Index (AQI) chiefly tracks fine particulate matter measured as:", optionA: "PM2.5 and PM10", optionB: "CO2 only", optionC: "Ozone only", optionD: "Methane", correctOption: "A", explanation: "AQI tracks pollutants including PM2.5 and PM10 particulates, NO₂, SO₂, CO, and O₃.", orderIndex: 0 },
  { id: "upsc-environment-pollution-and-waste-management-q02", topicId: "upsc-environment-pollution-and-waste-management", text: "The Namami Gange programme is aimed at cleaning the river:", optionA: "Ganga", optionB: "Yamuna", optionC: "Godavari", optionD: "Narmada", correctOption: "A", explanation: "Namami Gange is the flagship programme for cleaning and conserving the Ganga.", orderIndex: 1 },
  { id: "upsc-environment-pollution-and-waste-management-q03", topicId: "upsc-environment-pollution-and-waste-management", text: "The Bhopal Gas Tragedy (1984) was caused by the leak of:", optionA: "Methyl isocyanate (MIC)", optionB: "Carbon dioxide", optionC: "Chlorine", optionD: "Ammonia", correctOption: "A", explanation: "The Bhopal disaster resulted from a methyl isocyanate (MIC) gas leak.", orderIndex: 2 },
  { id: "upsc-environment-pollution-and-waste-management-q04", topicId: "upsc-environment-pollution-and-waste-management", text: "India's current vehicular emission norms are:", optionA: "Bharat Stage VI (BS-VI)", optionB: "Bharat Stage II", optionC: "Euro 2", optionD: "BS-III", correctOption: "A", explanation: "India moved to Bharat Stage VI (BS-VI) emission standards in 2020.", orderIndex: 3 },
  { id: "upsc-environment-pollution-and-waste-management-q05", topicId: "upsc-environment-pollution-and-waste-management", text: "The nutrient enrichment of water bodies leading to algal blooms is called:", optionA: "Eutrophication", optionB: "Biomagnification", optionC: "Desalination", optionD: "Acidification", correctOption: "A", explanation: "Eutrophication is nutrient over-enrichment causing algal blooms and oxygen depletion.", orderIndex: 4 },
  { id: "upsc-environment-pollution-and-waste-management-q06", topicId: "upsc-environment-pollution-and-waste-management", text: "High Biological Oxygen Demand (BOD) in water indicates:", optionA: "Heavy organic pollution", optionB: "Clean water", optionC: "High salinity", optionD: "Low temperature", correctOption: "A", explanation: "A high BOD means microbes consume more oxygen, signalling organic pollution.", orderIndex: 5 },
  { id: "upsc-environment-pollution-and-waste-management-q07", topicId: "upsc-environment-pollution-and-waste-management", text: "The policy making producers responsible for the disposal of their products' waste is:", optionA: "Extended Producer Responsibility (EPR)", optionB: "Minimum Support Price", optionC: "Cess", optionD: "Feed-in tariff", correctOption: "A", explanation: "EPR makes producers responsible for managing post-consumer product waste (e.g., plastics, e-waste).", orderIndex: 6 },
  { id: "upsc-environment-pollution-and-waste-management-q08", topicId: "upsc-environment-pollution-and-waste-management", text: "The '3 Rs' of sustainable waste management are:", optionA: "Reduce, Reuse, Recycle", optionB: "Read, Write, Recall", optionC: "Repair, Rebuild, Renew", optionD: "Reform, Reset, Restore", correctOption: "A", explanation: "The 3 Rs — Reduce, Reuse, Recycle — guide sustainable waste management.", orderIndex: 7 },
  { id: "upsc-environment-pollution-and-waste-management-q09", topicId: "upsc-environment-pollution-and-waste-management", text: "The Swachh Bharat Mission is primarily aimed at:", optionA: "Sanitation and cleanliness", optionB: "Rural electrification", optionC: "Digital literacy", optionD: "Crop insurance", correctOption: "A", explanation: "The Swachh Bharat Mission focuses on sanitation, cleanliness, and waste management.", orderIndex: 8 },
  { id: "upsc-environment-pollution-and-waste-management-q10", topicId: "upsc-environment-pollution-and-waste-management", text: "Solid waste rules require households to segregate waste into wet (biodegradable) and:", optionA: "Dry (non-biodegradable)", optionB: "Radioactive", optionC: "Liquid only", optionD: "Gaseous", correctOption: "A", explanation: "Waste is segregated at source into wet (biodegradable) and dry (non-biodegradable) streams.", orderIndex: 9 },
  { id: "upsc-environment-pollution-and-waste-management-q11", topicId: "upsc-environment-pollution-and-waste-management", text: "The Minamata disease in Japan was caused by pollution from:", optionA: "Mercury", optionB: "Lead", optionC: "Arsenic", optionD: "Cadmium", correctOption: "A", explanation: "Minamata disease resulted from mercury poisoning of seafood in Japan.", orderIndex: 10 },
  { id: "upsc-environment-pollution-and-waste-management-q12", topicId: "upsc-environment-pollution-and-waste-management", text: "An economic model that designs out waste and keeps resources in use is the:", optionA: "Circular economy", optionB: "Linear economy", optionC: "Barter economy", optionD: "Command economy", correctOption: "A", explanation: "The circular economy minimises waste by reusing, repairing, and recycling resources.", orderIndex: 11 },

  // ── Science & Technology: IT, Computers & AI ──
  { id: "upsc-science-technology-it-computers-and-ai-q01", topicId: "upsc-science-technology-it-computers-and-ai", text: "The 'brain' of a computer that performs processing is the:", optionA: "CPU", optionB: "Monitor", optionC: "Keyboard", optionD: "Printer", correctOption: "A", explanation: "The Central Processing Unit (CPU) executes instructions and performs computations.", orderIndex: 0 },
  { id: "upsc-science-technology-it-computers-and-ai-q02", topicId: "upsc-science-technology-it-computers-and-ai", text: "Computers fundamentally represent data in which number system?", optionA: "Binary", optionB: "Decimal", optionC: "Roman", optionD: "Hexadecimal only", correctOption: "A", explanation: "Computers use the binary system of 0s and 1s (bits).", orderIndex: 1 },
  { id: "upsc-science-technology-it-computers-and-ai-q03", topicId: "upsc-science-technology-it-computers-and-ai", text: "Volatile memory that loses data when power is off is:", optionA: "RAM", optionB: "ROM", optionC: "Hard disk", optionD: "SSD", correctOption: "A", explanation: "RAM (Random Access Memory) is volatile and loses its contents when powered off.", orderIndex: 2 },
  { id: "upsc-science-technology-it-computers-and-ai-q04", topicId: "upsc-science-technology-it-computers-and-ai", text: "A decentralised, tamper-evident digital ledger underlying cryptocurrencies is called:", optionA: "Blockchain", optionB: "Spreadsheet", optionC: "Firewall", optionD: "Router", correctOption: "A", explanation: "Blockchain is a distributed, tamper-evident ledger technology.", orderIndex: 3 },
  { id: "upsc-science-technology-it-computers-and-ai-q05", topicId: "upsc-science-technology-it-computers-and-ai", text: "The subfield of AI where systems learn patterns from data is:", optionA: "Machine learning", optionB: "Word processing", optionC: "Compilation", optionD: "Defragmentation", correctOption: "A", explanation: "Machine learning lets systems learn from data rather than explicit programming.", orderIndex: 4 },
  { id: "upsc-science-technology-it-computers-and-ai-q06", topicId: "upsc-science-technology-it-computers-and-ai", text: "India's real-time mobile payments system, now used globally, is:", optionA: "UPI", optionB: "SWIFT", optionC: "RTGS only", optionD: "PayPal", correctOption: "A", explanation: "The Unified Payments Interface (UPI) enables instant real-time mobile payments.", orderIndex: 5 },
  { id: "upsc-science-technology-it-computers-and-ai-q07", topicId: "upsc-science-technology-it-computers-and-ai", text: "Aadhaar is best described as India's:", optionA: "Biometric-based unique identity system", optionB: "Payment gateway", optionC: "Stock exchange", optionD: "Search engine", correctOption: "A", explanation: "Aadhaar provides a biometric-linked unique identity number to residents.", orderIndex: 6 },
  { id: "upsc-science-technology-it-computers-and-ai-q08", topicId: "upsc-science-technology-it-computers-and-ai", text: "The basic unit of quantum computing is the:", optionA: "Qubit", optionB: "Bit", optionC: "Byte", optionD: "Pixel", correctOption: "A", explanation: "Quantum computers use qubits, which can exist in superposition of states.", orderIndex: 7 },
  { id: "upsc-science-technology-it-computers-and-ai-q09", topicId: "upsc-science-technology-it-computers-and-ai", text: "The network of internet-connected everyday devices is called the:", optionA: "Internet of Things (IoT)", optionB: "Intranet", optionC: "Dark web", optionD: "Ethernet", correctOption: "A", explanation: "The Internet of Things (IoT) connects sensors and devices over the internet.", orderIndex: 8 },
  { id: "upsc-science-technology-it-computers-and-ai-q10", topicId: "upsc-science-technology-it-computers-and-ai", text: "AI techniques using multi-layered neural networks are called:", optionA: "Deep learning", optionB: "Shallow sorting", optionC: "Batch processing", optionD: "Caching", correctOption: "A", explanation: "Deep learning uses many-layered neural networks to model complex patterns.", orderIndex: 9 },
  { id: "upsc-science-technology-it-computers-and-ai-q11", topicId: "upsc-science-technology-it-computers-and-ai", text: "India's data-protection law enacted in 2023 is the:", optionA: "Digital Personal Data Protection Act", optionB: "IT Act, 2000", optionC: "RTI Act", optionD: "Aadhaar Act", correctOption: "A", explanation: "The Digital Personal Data Protection Act, 2023 governs the processing of personal data.", orderIndex: 10 },
  { id: "upsc-science-technology-it-computers-and-ai-q12", topicId: "upsc-science-technology-it-computers-and-ai", text: "Delivering computing resources over the internet on demand is called:", optionA: "Cloud computing", optionB: "Edge etching", optionC: "Grid drawing", optionD: "Local hosting", correctOption: "A", explanation: "Cloud computing provides on-demand computing resources (IaaS, PaaS, SaaS) over the internet.", orderIndex: 11 },

  // ── Science & Technology: Nuclear Technology & Energy ──
  { id: "upsc-science-technology-nuclear-technology-and-energy-q01", topicId: "upsc-science-technology-nuclear-technology-and-energy", text: "The process of splitting a heavy nucleus to release energy is:", optionA: "Nuclear fission", optionB: "Nuclear fusion", optionC: "Radioactive decay only", optionD: "Ionisation", correctOption: "A", explanation: "Nuclear fission splits heavy nuclei (e.g., U-235) in a chain reaction, releasing energy.", orderIndex: 0 },
  { id: "upsc-science-technology-nuclear-technology-and-energy-q02", topicId: "upsc-science-technology-nuclear-technology-and-energy", text: "The Sun produces its energy mainly through:", optionA: "Nuclear fusion", optionB: "Nuclear fission", optionC: "Combustion", optionD: "Chemical reactions", correctOption: "A", explanation: "The Sun fuses hydrogen into helium (nuclear fusion), releasing vast energy.", orderIndex: 1 },
  { id: "upsc-science-technology-nuclear-technology-and-energy-q03", topicId: "upsc-science-technology-nuclear-technology-and-energy", text: "The 'father of the Indian nuclear programme' is:", optionA: "Homi Bhabha", optionB: "Vikram Sarabhai", optionC: "C. V. Raman", optionD: "A. P. J. Abdul Kalam", correctOption: "A", explanation: "Homi Bhabha founded India's nuclear programme and conceived the three-stage plan.", orderIndex: 2 },
  { id: "upsc-science-technology-nuclear-technology-and-energy-q04", topicId: "upsc-science-technology-nuclear-technology-and-energy", text: "The third stage of India's nuclear programme is designed to use its large reserves of:", optionA: "Thorium", optionB: "Uranium", optionC: "Coal", optionD: "Plutonium", correctOption: "A", explanation: "Stage three exploits India's abundant thorium (from Kerala's monazite sands).", orderIndex: 3 },
  { id: "upsc-science-technology-nuclear-technology-and-energy-q05", topicId: "upsc-science-technology-nuclear-technology-and-energy", text: "In a nuclear reactor, control rods (e.g., cadmium/boron) serve to:", optionA: "Absorb neutrons and control the reaction", optionB: "Speed up the reaction indefinitely", optionC: "Generate steam", optionD: "Store the fuel", correctOption: "A", explanation: "Control rods absorb neutrons to regulate or stop the fission chain reaction.", orderIndex: 4 },
  { id: "upsc-science-technology-nuclear-technology-and-energy-q06", topicId: "upsc-science-technology-nuclear-technology-and-energy", text: "The moderator in many reactors, used to slow down neutrons, can be:", optionA: "Heavy water or graphite", optionB: "Cadmium", optionC: "Uranium", optionD: "Concrete", correctOption: "A", explanation: "Moderators like heavy water or graphite slow neutrons to sustain fission.", orderIndex: 5 },
  { id: "upsc-science-technology-nuclear-technology-and-energy-q07", topicId: "upsc-science-technology-nuclear-technology-and-energy", text: "The Kudankulam and Tarapur facilities are examples of:", optionA: "Nuclear power plants", optionB: "Thermal power plants", optionC: "Hydroelectric dams", optionD: "Wind farms", correctOption: "A", explanation: "Kudankulam and Tarapur are Indian nuclear power stations.", orderIndex: 6 },
  { id: "upsc-science-technology-nuclear-technology-and-energy-q08", topicId: "upsc-science-technology-nuclear-technology-and-energy", text: "The International Solar Alliance (ISA) is headquartered in:", optionA: "India (Gurugram)", optionB: "France", optionC: "the USA", optionD: "the UAE", correctOption: "A", explanation: "The ISA, co-founded by India and France, is headquartered in Gurugram, India.", orderIndex: 7 },
  { id: "upsc-science-technology-nuclear-technology-and-energy-q09", topicId: "upsc-science-technology-nuclear-technology-and-energy", text: "India got a waiver to trade in nuclear technology through the 2008:", optionA: "Indo-US Nuclear Deal", optionB: "Simla Agreement", optionC: "Panchsheel Agreement", optionD: "Tashkent Declaration", correctOption: "A", explanation: "The 2008 Indo-US civil nuclear deal secured an NSG waiver for India.", orderIndex: 8 },
  { id: "upsc-science-technology-nuclear-technology-and-energy-q10", topicId: "upsc-science-technology-nuclear-technology-and-energy", text: "The second stage of India's nuclear plan relies on:", optionA: "Fast Breeder Reactors using plutonium", optionB: "Solar panels", optionC: "Coal gasification", optionD: "Wind turbines", correctOption: "A", explanation: "Stage two uses Fast Breeder Reactors that breed more fissile material from plutonium.", orderIndex: 9 },
  { id: "upsc-science-technology-nuclear-technology-and-energy-q11", topicId: "upsc-science-technology-nuclear-technology-and-energy", text: "The international project to demonstrate fusion power, of which India is a partner, is:", optionA: "ITER", optionB: "CERN", optionC: "ISS", optionD: "LIGO", correctOption: "A", explanation: "ITER is the international thermonuclear (fusion) experimental reactor project.", orderIndex: 10 },
  { id: "upsc-science-technology-nuclear-technology-and-energy-q12", topicId: "upsc-science-technology-nuclear-technology-and-energy", text: "India's premier nuclear research centre near Mumbai is:", optionA: "BARC", optionB: "ISRO", optionC: "DRDO", optionD: "CSIR", correctOption: "A", explanation: "The Bhabha Atomic Research Centre (BARC) is India's premier nuclear research institution.", orderIndex: 11 },

  // ── Science & Technology: Health, Diseases & Vaccines ──
  { id: "upsc-science-technology-health-diseases-and-vaccines-q01", topicId: "upsc-science-technology-health-diseases-and-vaccines", text: "Malaria is caused by a protozoan of the genus Plasmodium, spread by the:", optionA: "Female Anopheles mosquito", optionB: "Aedes mosquito", optionC: "Housefly", optionD: "Tsetse fly", correctOption: "A", explanation: "Malaria is transmitted by the bite of the female Anopheles mosquito.", orderIndex: 0 },
  { id: "upsc-science-technology-health-diseases-and-vaccines-q02", topicId: "upsc-science-technology-health-diseases-and-vaccines", text: "Dengue and chikungunya are transmitted mainly by the:", optionA: "Aedes mosquito", optionB: "Anopheles mosquito", optionC: "Culex mosquito", optionD: "Sandfly", correctOption: "A", explanation: "Dengue and chikungunya are spread by the Aedes aegypti mosquito.", orderIndex: 1 },
  { id: "upsc-science-technology-health-diseases-and-vaccines-q03", topicId: "upsc-science-technology-health-diseases-and-vaccines", text: "India was declared polio-free in:", optionA: "2014", optionB: "2000", optionC: "1975", optionD: "2020", correctOption: "A", explanation: "The WHO declared India polio-free in 2014 after sustained immunisation.", orderIndex: 2 },
  { id: "upsc-science-technology-health-diseases-and-vaccines-q04", topicId: "upsc-science-technology-health-diseases-and-vaccines", text: "Antibiotics are effective against which type of pathogen?", optionA: "Bacteria", optionB: "Viruses", optionC: "All viruses and bacteria equally", optionD: "Only fungi", correctOption: "A", explanation: "Antibiotics treat bacterial infections; they do not work against viruses.", orderIndex: 3 },
  { id: "upsc-science-technology-health-diseases-and-vaccines-q05", topicId: "upsc-science-technology-health-diseases-and-vaccines", text: "The overuse of antibiotics leads to the growing problem of:", optionA: "Antimicrobial resistance (AMR)", optionB: "Herd immunity", optionC: "Eutrophication", optionD: "Vaccination", correctOption: "A", explanation: "Overuse of antibiotics drives antimicrobial resistance (AMR), a major health threat.", orderIndex: 4 },
  { id: "upsc-science-technology-health-diseases-and-vaccines-q06", topicId: "upsc-science-technology-health-diseases-and-vaccines", text: "COVID-19 is caused by which virus?", optionA: "SARS-CoV-2", optionB: "HIV", optionC: "Influenza H1N1", optionD: "Ebola", correctOption: "A", explanation: "COVID-19 is caused by the SARS-CoV-2 coronavirus.", orderIndex: 5 },
  { id: "upsc-science-technology-health-diseases-and-vaccines-q07", topicId: "upsc-science-technology-health-diseases-and-vaccines", text: "India's indigenously developed COVID-19 vaccine is:", optionA: "Covaxin", optionB: "Sputnik V", optionC: "Pfizer", optionD: "Moderna", correctOption: "A", explanation: "Covaxin, by Bharat Biotech and ICMR, is India's indigenous COVID-19 vaccine.", orderIndex: 6 },
  { id: "upsc-science-technology-health-diseases-and-vaccines-q08", topicId: "upsc-science-technology-health-diseases-and-vaccines", text: "Diseases like diabetes and cancer, not spread by pathogens, are classed as:", optionA: "Non-communicable diseases", optionB: "Communicable diseases", optionC: "Epidemics", optionD: "Zoonoses", correctOption: "A", explanation: "Non-communicable (lifestyle) diseases are not transmitted between people.", orderIndex: 7 },
  { id: "upsc-science-technology-health-diseases-and-vaccines-q09", topicId: "upsc-science-technology-health-diseases-and-vaccines", text: "When enough of a population is immune to protect the rest, it is called:", optionA: "Herd immunity", optionB: "Passive immunity", optionC: "Autoimmunity", optionD: "Immunodeficiency", correctOption: "A", explanation: "Herd immunity slows disease spread when a large share of a population is immune.", orderIndex: 8 },
  { id: "upsc-science-technology-health-diseases-and-vaccines-q10", topicId: "upsc-science-technology-health-diseases-and-vaccines", text: "Ayushman Bharat provides health insurance cover along with:", optionA: "Health and Wellness Centres", optionB: "Crop loans", optionC: "Free laptops", optionD: "Housing loans", correctOption: "A", explanation: "Ayushman Bharat combines the PM-JAY insurance scheme with Health and Wellness Centres.", orderIndex: 9 },
  { id: "upsc-science-technology-health-diseases-and-vaccines-q11", topicId: "upsc-science-technology-health-diseases-and-vaccines", text: "The disease officially eradicated worldwide through vaccination is:", optionA: "Smallpox", optionB: "Malaria", optionC: "Tuberculosis", optionD: "Dengue", correctOption: "A", explanation: "Smallpox is the only human disease declared eradicated (WHO, 1980).", orderIndex: 10 },
  { id: "upsc-science-technology-health-diseases-and-vaccines-q12", topicId: "upsc-science-technology-health-diseases-and-vaccines", text: "The global body that coordinates international public health is the:", optionA: "World Health Organization (WHO)", optionB: "World Trade Organization", optionC: "UNESCO", optionD: "World Bank", correctOption: "A", explanation: "The WHO, a UN agency, directs and coordinates international health work.", orderIndex: 11 }
];
