// UPSC depth expansion — History round two (pass 7). Rounds out Modern and
// Medieval History, the thinnest History blocks, with high-yield chapters that
// recur in Prelims. Each new topic has a study note and a full 12-question drill.
import type { AuthoredMaterial } from "./builder";
import type { Question, Topic } from "@jyotir/core";

export const exp7Topics: Topic[] = [
  // Medieval History (existing max orderIndex = 5 after pass 2)
  { id: "upsc-medieval-history-sikhism-and-the-gurus", subjectId: "upsc-medieval-history", name: "Sikhism & the Sikh Gurus", slug: "sikhism-and-the-gurus", orderIndex: 6 },
  { id: "upsc-medieval-history-indo-islamic-architecture", subjectId: "upsc-medieval-history", name: "Indo-Islamic Architecture", slug: "indo-islamic-architecture", orderIndex: 7 },
  // Modern History (existing max orderIndex = 7 after pass 2)
  { id: "upsc-modern-history-peasant-tribal-and-left-movements", subjectId: "upsc-modern-history", name: "Peasant, Tribal & Left Movements", slug: "peasant-tribal-and-left-movements", orderIndex: 8 },
  { id: "upsc-modern-history-post-independence-consolidation", subjectId: "upsc-modern-history", name: "Post-Independence Consolidation", slug: "post-independence-consolidation", orderIndex: 9 }
];

export const exp7Materials: AuthoredMaterial[] = [
  { id: "upsc-medieval-history-sikhism-and-the-gurus-m01", topicId: "upsc-medieval-history-sikhism-and-the-gurus", title: "Sikhism & the Sikh Gurus", content: `**Sikhism** was founded by **Guru Nanak** (1469–1539), the first of the **ten Gurus**, who preached **one God**, equality, honest living, and rejected caste and ritual. Key later Gurus: **Guru Angad** (developed the **Gurmukhi** script); **Guru Amar Das** (institutionalised the **langar**/community kitchen); **Guru Ram Das** (founded **Amritsar**); and **Guru Arjan**, who compiled the **Adi Granth** and built the **Golden Temple (Harmandir Sahib)** — he was executed by Jahangir, becoming the first Sikh martyr.

**Guru Hargobind** militarised the community (the concept of **Miri-Piri**). **Guru Tegh Bahadur**, the ninth Guru, was executed by **Aurangzeb** for defending religious freedom. The tenth Guru, **Guru Gobind Singh**, founded the **Khalsa** in **1699** at Anandpur Sahib, gave the **five Ks**, and declared the **Guru Granth Sahib** the eternal Guru. Later, **Banda Singh Bahadur** led armed resistance, and in the 19th century **Maharaja Ranjit Singh** built a powerful Sikh Empire in Punjab (capital Lahore), which the British annexed after the **Anglo-Sikh Wars** (1849).`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "upsc-medieval-history-indo-islamic-architecture-m01", topicId: "upsc-medieval-history-indo-islamic-architecture", title: "Indo-Islamic Architecture", content: `Indo-Islamic architecture blended Islamic forms (**arch, dome, minaret, calligraphy**, geometric and arabesque ornament — no figural images) with Indian craftsmanship. The **Delhi Sultanate** built the **Qutb Minar** and Quwwat-ul-Islam mosque (Slave dynasty), Alai Darwaza (Khalji), Tughlaqabad, and the Lodi tombs; the **true arch and dome** matured in this period, using the **arcuate** (arch) style versus the older Indian **trabeate** (post-and-lintel).

The **Mughals** perfected the style. **Humayun's Tomb** (Delhi) introduced the Persian **charbagh** (four-part garden) and the double dome — a precursor to the **Taj Mahal** (Shah Jahan's white-marble mausoleum at Agra, with **pietra dura** inlay). **Akbar** built **Fatehpur Sikri** (with the **Buland Darwaza**, the Panch Mahal) in red sandstone. **Shah Jahan's** reign was the golden age — the **Red Fort** and **Jama Masjid** (Delhi), and the **Peacock Throne**. Regional styles flourished too (the **Gol Gumbaz** at Bijapur, the **Charminar** at Hyderabad). Provincial and later **Indo-Saracenic** (British colonial) styles carried the tradition forward.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "upsc-modern-history-peasant-tribal-and-left-movements-m01", topicId: "upsc-modern-history-peasant-tribal-and-left-movements", title: "Peasant, Tribal & Left Movements", content: `British land and forest policies sparked repeated **peasant and tribal revolts**. Early risings included the **Sanyasi Rebellion**, the **Santhal Rebellion (1855–56)** led by Sidhu and Kanhu, the **Munda uprising (Ulgulan)** under **Birsa Munda** (1899–1900), and the **Kol** and **Bhil** revolts. Later peasant movements included the **Indigo Revolt (1859)** in Bengal, the **Deccan Riots (1875)** against moneylenders, the **Champaran (1917)** and **Kheda (1918)** satyagrahas led by Gandhi, the **Moplah (Malabar) rebellion (1921)**, the **Bardoli Satyagraha (1928)** under Sardar Patel, and the **Tebhaga** (Bengal) and **Telangana** (against the Nizam) movements.

The **working class** organised through the **All India Trade Union Congress (AITUC, 1920)**. **Socialist and communist** ideas grew: the **Communist Party of India** was founded (1925), the **Congress Socialist Party** formed within Congress (1934), and revolutionaries like **Bhagat Singh** embraced socialism (the HSRA). Kisan Sabhas (the **All India Kisan Sabha, 1936**) mobilised peasants nationally. These movements broadened the freedom struggle beyond the middle class and shaped post-independence land reforms and labour rights.`, estimatedReadTime: 2, orderIndex: 0 },
  { id: "upsc-modern-history-post-independence-consolidation-m01", topicId: "upsc-modern-history-post-independence-consolidation", title: "Post-Independence Consolidation", content: `After 1947 India faced enormous nation-building tasks. **Sardar Vallabhbhai Patel** and V. P. Menon integrated over **560 princely states**; the tough cases were **Junagadh** (settled by plebiscite), **Hyderabad** (integrated by **Operation Polo, 1948**), and **Jammu & Kashmir** (which acceded after the 1947–48 war and is tied to **Article 370**). Portuguese **Goa** was liberated in **1961** and French enclaves (**Pondicherry**) merged peacefully.

**Linguistic reorganisation**: after agitations (and Potti Sriramulu's death), **Andhra** became the first linguistic state (1953); the **States Reorganisation Act (1956)** redrew state boundaries on language. Economic foundations were laid through **Five-Year Plans**, the Green Revolution, and public-sector industry. India adopted a **non-aligned foreign policy** (Nehru, Panchsheel, the 1955 Bandung Conference) while facing wars — with **China (1962)** and **Pakistan (1947–48, 1965, 1971)**; the 1971 war created **Bangladesh**. Constitutional consolidation, universal franchise, and the first general elections (1951–52) established India as the world's largest democracy.`, estimatedReadTime: 2, orderIndex: 0 }
];

export const exp7Questions: Question[] = [
  // ── Medieval History: Sikhism & the Sikh Gurus ──
  { id: "upsc-medieval-history-sikhism-and-the-gurus-q01", topicId: "upsc-medieval-history-sikhism-and-the-gurus", text: "The founder of Sikhism was:", optionA: "Guru Nanak", optionB: "Guru Gobind Singh", optionC: "Guru Arjan", optionD: "Guru Tegh Bahadur", correctOption: "A", explanation: "Guru Nanak (1469–1539) was the first Guru and founder of Sikhism.", orderIndex: 0 },
  { id: "upsc-medieval-history-sikhism-and-the-gurus-q02", topicId: "upsc-medieval-history-sikhism-and-the-gurus", text: "How many human Gurus were there in the Sikh tradition?", optionA: "Ten", optionB: "Five", optionC: "Twelve", optionD: "Seven", correctOption: "A", explanation: "There were ten human Gurus, after whom the Guru Granth Sahib became the eternal Guru.", orderIndex: 1 },
  { id: "upsc-medieval-history-sikhism-and-the-gurus-q03", topicId: "upsc-medieval-history-sikhism-and-the-gurus", text: "The Khalsa was founded in 1699 by:", optionA: "Guru Gobind Singh", optionB: "Guru Nanak", optionC: "Guru Hargobind", optionD: "Banda Singh Bahadur", correctOption: "A", explanation: "Guru Gobind Singh, the tenth Guru, founded the Khalsa at Anandpur Sahib in 1699.", orderIndex: 2 },
  { id: "upsc-medieval-history-sikhism-and-the-gurus-q04", topicId: "upsc-medieval-history-sikhism-and-the-gurus", text: "The Adi Granth was compiled by:", optionA: "Guru Arjan", optionB: "Guru Nanak", optionC: "Guru Angad", optionD: "Guru Gobind Singh", correctOption: "A", explanation: "Guru Arjan, the fifth Guru, compiled the Adi Granth (Sikh scripture).", orderIndex: 3 },
  { id: "upsc-medieval-history-sikhism-and-the-gurus-q05", topicId: "upsc-medieval-history-sikhism-and-the-gurus", text: "The city of Amritsar was founded by:", optionA: "Guru Ram Das", optionB: "Guru Nanak", optionC: "Guru Gobind Singh", optionD: "Maharaja Ranjit Singh", correctOption: "A", explanation: "Guru Ram Das, the fourth Guru, founded Amritsar, home to the Golden Temple.", orderIndex: 4 },
  { id: "upsc-medieval-history-sikhism-and-the-gurus-q06", topicId: "upsc-medieval-history-sikhism-and-the-gurus", text: "Which Guru was executed by the Mughal emperor Aurangzeb?", optionA: "Guru Tegh Bahadur", optionB: "Guru Nanak", optionC: "Guru Amar Das", optionD: "Guru Angad", correctOption: "A", explanation: "Guru Tegh Bahadur, the ninth Guru, was executed by Aurangzeb for defending religious freedom.", orderIndex: 5 },
  { id: "upsc-medieval-history-sikhism-and-the-gurus-q07", topicId: "upsc-medieval-history-sikhism-and-the-gurus", text: "The Gurmukhi script was developed by:", optionA: "Guru Angad", optionB: "Guru Nanak", optionC: "Guru Arjan", optionD: "Guru Ram Das", correctOption: "A", explanation: "Guru Angad, the second Guru, standardised and popularised the Gurmukhi script.", orderIndex: 6 },
  { id: "upsc-medieval-history-sikhism-and-the-gurus-q08", topicId: "upsc-medieval-history-sikhism-and-the-gurus", text: "The community kitchen central to Sikh practice is the:", optionA: "Langar", optionB: "Sangat", optionC: "Diwan", optionD: "Akhara", correctOption: "A", explanation: "The langar (free community kitchen) embodies equality; it was institutionalised by Guru Amar Das.", orderIndex: 7 },
  { id: "upsc-medieval-history-sikhism-and-the-gurus-q09", topicId: "upsc-medieval-history-sikhism-and-the-gurus", text: "The Sikh Empire in Punjab in the early 19th century was built by:", optionA: "Maharaja Ranjit Singh", optionB: "Banda Singh Bahadur", optionC: "Guru Gobind Singh", optionD: "Hari Singh Nalwa", correctOption: "A", explanation: "Maharaja Ranjit Singh forged a powerful Sikh Empire with its capital at Lahore.", orderIndex: 8 },
  { id: "upsc-medieval-history-sikhism-and-the-gurus-q10", topicId: "upsc-medieval-history-sikhism-and-the-gurus", text: "The eternal Guru of the Sikhs, declared by Guru Gobind Singh, is the:", optionA: "Guru Granth Sahib", optionB: "Adi Granth only", optionC: "Dasam Granth", optionD: "Janamsakhi", correctOption: "A", explanation: "Guru Gobind Singh declared the Guru Granth Sahib the eternal Guru after the ten human Gurus.", orderIndex: 9 },
  { id: "upsc-medieval-history-sikhism-and-the-gurus-q11", topicId: "upsc-medieval-history-sikhism-and-the-gurus", text: "The Harmandir Sahib (Golden Temple) construction was overseen by:", optionA: "Guru Arjan", optionB: "Guru Nanak", optionC: "Guru Gobind Singh", optionD: "Guru Tegh Bahadur", correctOption: "A", explanation: "Guru Arjan oversaw the building of the Harmandir Sahib at Amritsar.", orderIndex: 10 },
  { id: "upsc-medieval-history-sikhism-and-the-gurus-q12", topicId: "upsc-medieval-history-sikhism-and-the-gurus", text: "The concept of Miri-Piri (temporal and spiritual power) was introduced by:", optionA: "Guru Hargobind", optionB: "Guru Nanak", optionC: "Guru Amar Das", optionD: "Guru Ram Das", correctOption: "A", explanation: "Guru Hargobind, the sixth Guru, introduced Miri-Piri, militarising the community.", orderIndex: 11 },

  // ── Medieval History: Indo-Islamic Architecture ──
  { id: "upsc-medieval-history-indo-islamic-architecture-q01", topicId: "upsc-medieval-history-indo-islamic-architecture", text: "The Qutb Minar in Delhi was begun by:", optionA: "Qutb-ud-din Aibak", optionB: "Akbar", optionC: "Shah Jahan", optionD: "Sher Shah Suri", correctOption: "A", explanation: "Qutb-ud-din Aibak began the Qutb Minar; Iltutmish completed it.", orderIndex: 0 },
  { id: "upsc-medieval-history-indo-islamic-architecture-q02", topicId: "upsc-medieval-history-indo-islamic-architecture", text: "The Taj Mahal was built by which Mughal emperor?", optionA: "Shah Jahan", optionB: "Akbar", optionC: "Aurangzeb", optionD: "Humayun", correctOption: "A", explanation: "Shah Jahan built the Taj Mahal at Agra in memory of Mumtaz Mahal.", orderIndex: 1 },
  { id: "upsc-medieval-history-indo-islamic-architecture-q03", topicId: "upsc-medieval-history-indo-islamic-architecture", text: "Fatehpur Sikri, with the Buland Darwaza, was built by:", optionA: "Akbar", optionB: "Shah Jahan", optionC: "Babur", optionD: "Aurangzeb", correctOption: "A", explanation: "Akbar built Fatehpur Sikri in red sandstone, including the towering Buland Darwaza.", orderIndex: 2 },
  { id: "upsc-medieval-history-indo-islamic-architecture-q04", topicId: "upsc-medieval-history-indo-islamic-architecture", text: "Which tomb introduced the Persian charbagh garden and is a precursor to the Taj Mahal?", optionA: "Humayun's Tomb", optionB: "Akbar's Tomb", optionC: "Itmad-ud-Daula's Tomb", optionD: "Jahangir's Tomb", correctOption: "A", explanation: "Humayun's Tomb in Delhi introduced the charbagh layout and double dome.", orderIndex: 3 },
  { id: "upsc-medieval-history-indo-islamic-architecture-q05", topicId: "upsc-medieval-history-indo-islamic-architecture", text: "The decorative inlay of semi-precious stones seen in the Taj Mahal is called:", optionA: "Pietra dura", optionB: "Fresco", optionC: "Filigree", optionD: "Terracotta", correctOption: "A", explanation: "Pietra dura is the inlay of semi-precious stones into marble, used lavishly in the Taj Mahal.", orderIndex: 4 },
  { id: "upsc-medieval-history-indo-islamic-architecture-q06", topicId: "upsc-medieval-history-indo-islamic-architecture", text: "The older Indian post-and-lintel building method is called:", optionA: "Trabeate", optionB: "Arcuate", optionC: "Cantilever", optionD: "Corbel", correctOption: "A", explanation: "The trabeate (post-and-lintel) style predates the arcuate (true arch) style Islam introduced.", orderIndex: 5 },
  { id: "upsc-medieval-history-indo-islamic-architecture-q07", topicId: "upsc-medieval-history-indo-islamic-architecture", text: "The Red Fort and Jama Masjid of Delhi were built by:", optionA: "Shah Jahan", optionB: "Akbar", optionC: "Humayun", optionD: "Babur", correctOption: "A", explanation: "Shah Jahan built the Red Fort (Lal Qila) and the Jama Masjid in Delhi.", orderIndex: 6 },
  { id: "upsc-medieval-history-indo-islamic-architecture-q08", topicId: "upsc-medieval-history-indo-islamic-architecture", text: "A defining feature of Islamic architecture, avoiding human figures, is the use of:", optionA: "Calligraphy and geometric/arabesque designs", optionB: "Portrait sculpture", optionC: "Animal frescoes", optionD: "Idol niches", correctOption: "A", explanation: "Islamic architecture favours calligraphy and geometric/arabesque ornament over figural images.", orderIndex: 7 },
  { id: "upsc-medieval-history-indo-islamic-architecture-q09", topicId: "upsc-medieval-history-indo-islamic-architecture", text: "The Gol Gumbaz at Bijapur is famous for its:", optionA: "Whispering gallery and huge dome", optionB: "Leaning tower", optionC: "Rock-cut caves", optionD: "Stepwell", correctOption: "A", explanation: "The Gol Gumbaz has one of the world's largest domes and a famous whispering gallery.", orderIndex: 8 },
  { id: "upsc-medieval-history-indo-islamic-architecture-q10", topicId: "upsc-medieval-history-indo-islamic-architecture", text: "The Alai Darwaza was added to the Qutb complex by:", optionA: "Alauddin Khalji", optionB: "Iltutmish", optionC: "Balban", optionD: "Firoz Shah Tughlaq", correctOption: "A", explanation: "Alauddin Khalji added the Alai Darwaza, an early example of a true dome and arch.", orderIndex: 9 },
  { id: "upsc-medieval-history-indo-islamic-architecture-q11", topicId: "upsc-medieval-history-indo-islamic-architecture", text: "The vertical tower attached to mosques for the call to prayer is the:", optionA: "Minaret", optionB: "Gopuram", optionC: "Shikhara", optionD: "Vimana", correctOption: "A", explanation: "The minaret is the tower from which the call to prayer is given; gopuram/shikhara are Hindu temple features.", orderIndex: 10 },
  { id: "upsc-medieval-history-indo-islamic-architecture-q12", topicId: "upsc-medieval-history-indo-islamic-architecture", text: "The colonial-era style blending Indian and Islamic motifs with European forms is called:", optionA: "Indo-Saracenic", optionB: "Gothic only", optionC: "Baroque", optionD: "Dravidian", correctOption: "A", explanation: "The Indo-Saracenic style merged Indo-Islamic elements with European architecture under the British.", orderIndex: 11 },

  // ── Modern History: Peasant, Tribal & Left Movements ──
  { id: "upsc-modern-history-peasant-tribal-and-left-movements-q01", topicId: "upsc-modern-history-peasant-tribal-and-left-movements", text: "The Munda uprising (Ulgulan) was led by:", optionA: "Birsa Munda", optionB: "Sidhu Murmu", optionC: "Tantia Bhil", optionD: "Alluri Sitarama Raju", correctOption: "A", explanation: "Birsa Munda led the Munda rebellion (Ulgulan) in the Chotanagpur region around 1899–1900.", orderIndex: 0 },
  { id: "upsc-modern-history-peasant-tribal-and-left-movements-q02", topicId: "upsc-modern-history-peasant-tribal-and-left-movements", text: "The Santhal Rebellion (1855–56) was led by:", optionA: "Sidhu and Kanhu", optionB: "Birsa Munda", optionC: "Bhagat Singh", optionD: "Chittaranjan Das", correctOption: "A", explanation: "The Santhal Rebellion against moneylenders and the British was led by brothers Sidhu and Kanhu.", orderIndex: 1 },
  { id: "upsc-modern-history-peasant-tribal-and-left-movements-q03", topicId: "upsc-modern-history-peasant-tribal-and-left-movements", text: "Gandhi's first satyagraha in India, in 1917, was the:", optionA: "Champaran Satyagraha", optionB: "Bardoli Satyagraha", optionC: "Kheda Satyagraha", optionD: "Salt Satyagraha", correctOption: "A", explanation: "The Champaran Satyagraha (1917) against forced indigo cultivation was Gandhi's first in India.", orderIndex: 2 },
  { id: "upsc-modern-history-peasant-tribal-and-left-movements-q04", topicId: "upsc-modern-history-peasant-tribal-and-left-movements", text: "The Bardoli Satyagraha (1928) was led by:", optionA: "Sardar Vallabhbhai Patel", optionB: "Jawaharlal Nehru", optionC: "Bhagat Singh", optionD: "C. Rajagopalachari", correctOption: "A", explanation: "The Bardoli Satyagraha, a no-tax peasant movement, was led by Vallabhbhai Patel, who earned the title 'Sardar'.", orderIndex: 3 },
  { id: "upsc-modern-history-peasant-tribal-and-left-movements-q05", topicId: "upsc-modern-history-peasant-tribal-and-left-movements", text: "The All India Trade Union Congress (AITUC) was founded in:", optionA: "1920", optionB: "1885", optionC: "1947", optionD: "1936", correctOption: "A", explanation: "The AITUC, India's first major trade union body, was founded in 1920.", orderIndex: 4 },
  { id: "upsc-modern-history-peasant-tribal-and-left-movements-q06", topicId: "upsc-modern-history-peasant-tribal-and-left-movements", text: "The Tebhaga movement of sharecroppers took place in:", optionA: "Bengal", optionB: "Punjab", optionC: "Kerala", optionD: "Bihar", correctOption: "A", explanation: "The Tebhaga movement (1946) demanded a larger crop share for sharecroppers in Bengal.", orderIndex: 5 },
  { id: "upsc-modern-history-peasant-tribal-and-left-movements-q07", topicId: "upsc-modern-history-peasant-tribal-and-left-movements", text: "The Telangana peasant movement was directed against the:", optionA: "Nizam of Hyderabad", optionB: "British Raj", optionC: "Nawab of Awadh", optionD: "Zamindars of Bengal", correctOption: "A", explanation: "The Telangana movement (1946–51) was an armed peasant struggle against the Nizam's feudal rule.", orderIndex: 6 },
  { id: "upsc-modern-history-peasant-tribal-and-left-movements-q08", topicId: "upsc-modern-history-peasant-tribal-and-left-movements", text: "The All India Kisan Sabha was formed in:", optionA: "1936", optionB: "1920", optionC: "1885", optionD: "1942", correctOption: "A", explanation: "The All India Kisan Sabha, mobilising peasants nationally, was formed in 1936.", orderIndex: 7 },
  { id: "upsc-modern-history-peasant-tribal-and-left-movements-q09", topicId: "upsc-modern-history-peasant-tribal-and-left-movements", text: "The Deccan Riots of 1875 were directed mainly against:", optionA: "Moneylenders", optionB: "Factory owners", optionC: "Railway companies", optionD: "Tea planters", correctOption: "A", explanation: "The Deccan Riots targeted moneylenders (sahukars) who exploited indebted peasants.", orderIndex: 8 },
  { id: "upsc-modern-history-peasant-tribal-and-left-movements-q10", topicId: "upsc-modern-history-peasant-tribal-and-left-movements", text: "The Congress Socialist Party was formed within the Congress in:", optionA: "1934", optionB: "1920", optionC: "1947", optionD: "1885", correctOption: "A", explanation: "The Congress Socialist Party was founded in 1934 by Jayaprakash Narayan, Acharya Narendra Deva and others.", orderIndex: 9 },
  { id: "upsc-modern-history-peasant-tribal-and-left-movements-q11", topicId: "upsc-modern-history-peasant-tribal-and-left-movements", text: "The Moplah (Malabar) rebellion of 1921 occurred in present-day:", optionA: "Kerala", optionB: "Tamil Nadu", optionC: "Karnataka", optionD: "Andhra Pradesh", correctOption: "A", explanation: "The Moplah rebellion took place in the Malabar region of present-day Kerala.", orderIndex: 10 },
  { id: "upsc-modern-history-peasant-tribal-and-left-movements-q12", topicId: "upsc-modern-history-peasant-tribal-and-left-movements", text: "The Kheda Satyagraha (1918) demanded relief from land revenue due to:", optionA: "Crop failure/famine", optionB: "War taxes", optionC: "Salt tax", optionD: "Forest laws", correctOption: "A", explanation: "The Kheda Satyagraha sought remission of land revenue after crop failure in Gujarat.", orderIndex: 11 },

  // ── Modern History: Post-Independence Consolidation ──
  { id: "upsc-modern-history-post-independence-consolidation-q01", topicId: "upsc-modern-history-post-independence-consolidation", text: "The integration of the princely states was led chiefly by:", optionA: "Sardar Vallabhbhai Patel", optionB: "Jawaharlal Nehru", optionC: "Rajendra Prasad", optionD: "C. Rajagopalachari", correctOption: "A", explanation: "Sardar Patel, aided by V. P. Menon, integrated over 560 princely states into India.", orderIndex: 0 },
  { id: "upsc-modern-history-post-independence-consolidation-q02", topicId: "upsc-modern-history-post-independence-consolidation", text: "Hyderabad was integrated into India in 1948 through:", optionA: "Operation Polo", optionB: "Operation Vijay", optionC: "Operation Blue Star", optionD: "Operation Cactus", correctOption: "A", explanation: "Operation Polo (1948) was the police action that integrated Hyderabad into India.", orderIndex: 1 },
  { id: "upsc-modern-history-post-independence-consolidation-q03", topicId: "upsc-modern-history-post-independence-consolidation", text: "The first state to be created on a linguistic basis (1953) was:", optionA: "Andhra", optionB: "Kerala", optionC: "Gujarat", optionD: "Maharashtra", correctOption: "A", explanation: "Andhra became the first linguistic state in 1953 after Potti Sriramulu's death.", orderIndex: 2 },
  { id: "upsc-modern-history-post-independence-consolidation-q04", topicId: "upsc-modern-history-post-independence-consolidation", text: "The States Reorganisation Act, redrawing states on linguistic lines, was passed in:", optionA: "1956", optionB: "1947", optionC: "1950", optionD: "1966", correctOption: "A", explanation: "The States Reorganisation Act, 1956 reorganised Indian states largely on a linguistic basis.", orderIndex: 3 },
  { id: "upsc-modern-history-post-independence-consolidation-q05", topicId: "upsc-modern-history-post-independence-consolidation", text: "Goa was liberated from Portuguese rule in:", optionA: "1961", optionB: "1947", optionC: "1975", optionD: "1956", correctOption: "A", explanation: "Goa was liberated from Portuguese control in 1961 via Operation Vijay.", orderIndex: 4 },
  { id: "upsc-modern-history-post-independence-consolidation-q06", topicId: "upsc-modern-history-post-independence-consolidation", text: "India's foreign policy under Nehru was based on:", optionA: "Non-alignment", optionB: "Military alliance with the USA", optionC: "Membership of the Warsaw Pact", optionD: "Isolationism", correctOption: "A", explanation: "Nehru championed non-alignment, steering clear of Cold War blocs.", orderIndex: 5 },
  { id: "upsc-modern-history-post-independence-consolidation-q07", topicId: "upsc-modern-history-post-independence-consolidation", text: "The 1971 India-Pakistan war led to the creation of:", optionA: "Bangladesh", optionB: "Nepal", optionC: "Sri Lanka", optionD: "Myanmar", correctOption: "A", explanation: "The 1971 war resulted in the independence of East Pakistan as Bangladesh.", orderIndex: 6 },
  { id: "upsc-modern-history-post-independence-consolidation-q08", topicId: "upsc-modern-history-post-independence-consolidation", text: "The five principles of peaceful coexistence articulated by India and China were called:", optionA: "Panchsheel", optionB: "Panchayat", optionC: "Panchamrit", optionD: "Panchvarsha", correctOption: "A", explanation: "Panchsheel (1954) set out five principles of peaceful coexistence between India and China.", orderIndex: 7 },
  { id: "upsc-modern-history-post-independence-consolidation-q09", topicId: "upsc-modern-history-post-independence-consolidation", text: "India's first general elections were held in:", optionA: "1951–52", optionB: "1947", optionC: "1950", optionD: "1957", correctOption: "A", explanation: "India held its first general elections in 1951–52, based on universal adult franchise.", orderIndex: 8 },
  { id: "upsc-modern-history-post-independence-consolidation-q10", topicId: "upsc-modern-history-post-independence-consolidation", text: "The border war with China took place in:", optionA: "1962", optionB: "1965", optionC: "1971", optionD: "1948", correctOption: "A", explanation: "India and China fought a border war in 1962.", orderIndex: 9 },
  { id: "upsc-modern-history-post-independence-consolidation-q11", topicId: "upsc-modern-history-post-independence-consolidation", text: "The accession of Junagadh was ultimately settled by:", optionA: "A plebiscite", optionB: "Military conquest only", optionC: "A UN mandate", optionD: "Partition", correctOption: "A", explanation: "Junagadh's accession to India was confirmed through a plebiscite in 1948.", orderIndex: 10 },
  { id: "upsc-modern-history-post-independence-consolidation-q12", topicId: "upsc-modern-history-post-independence-consolidation", text: "The 1955 conference of Afro-Asian nations that promoted non-alignment was held at:", optionA: "Bandung", optionB: "Belgrade", optionC: "Geneva", optionD: "Colombo", correctOption: "A", explanation: "The 1955 Bandung Conference (Indonesia) advanced Afro-Asian solidarity and non-alignment.", orderIndex: 11 }
];
